### ISSUE TITLE
HTMLButtonElement not defined

### ISSUE THREAD

**Issue by pzupan** [jaredpalmer/formik#1006]
When running formik in react-native, handleSubmit is testing the button for the  type, but react native doesn't support an html button type.  More importantly, it appears that HTMLButtonType isn't defined as implemented so testing the instanceof fails.

This is line 398 of src/Formik.tsx:
```js
if (activeElement !== null && activeElement instanceof HTMLButtonElement) {
       warning(!!(activeElement.attributes && activeElement.attributes.getNamedItem('type')), 'You submitted a Formik form using a button with an unspecified `type` attribute.  Most browsers default button elements to `type="submit"`. If this is not a submit button, please add `type="button"`.');
}
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.3.1
| React            |  16.3.1
| TypeScript       | 
| Browser          |
| npm/Yarn         | npm 5.6.0
| Operating System | Win 10

**Comment by scruffles** [comment]
this isn't exclusive to react native.  I'm seeing it in Enzyme tests (mounted components)

**Comment by jlurena** [comment]
I'm seeing this in enzyme tests as well. Anyway we can suppress these warnings in test environments?

**Comment by chira37** [comment]
needed to add width and height to the View

**Comment by ajp8164** [comment]
Using Formik, Sentry, and okta-react-native. There's an issue with the combination of these libs. With okta imports the Formik handleSubmit function results in the error reported by OP. Calling my button submit handler direct avoids the error.

There is no particular use of these libs it's just the presence of import statements for all the libs.

See [https://github.com/getsentry/sentry-react-native/issues/785](https://github.com/getsentry/sentry-react-native/issues/785)
