### ISSUE TITLE
Deselecting radio buttons

### ISSUE THREAD

**Issue by scharepmc2hr** [jaredpalmer/formik#1013]
## 🚀 Feature request
Any idea for deselecting radio buttons?

### Desired Behavior
checked/unchecked radio buttons on click and update formik values.

### Suggested Solution
It can compare the previous value with the new value (prevValue === newValue) and then setting the value of the question to null or maybe add a default value and use defaultChecked...

**Comment by scharepmc2hr** [comment]
@Saifadin In my scenario, I want a selectable list where only one radio option can be selected, like this [solution](https://stackoverflow.com/a/9709425).

**Comment by Saifadin** [comment]
Okay that changes some things, of course. The team has to decide if they want to add that. But until then you can easily do that by checking if the value in `values` matches with the value of the radio.

**Comment by scharepmc2hr** [comment]
Finally, it solved with these steps:

1. change `type="radio"` to `type="checkbox"`.
2. make a function `myHandleChange` that gets the event and makes a new object from current formik `values` and updates new values with `setValues` formik prop:

![carbon 3](https://user-images.githubusercontent.com/22997685/47217340-edae5780-d3b4-11e8-8f46-c7c2bd4ac794.png)
Thanks :clinking_glasses:

**Comment by KevinKelbie** [comment]
Here is a solution I am pretty happy with.

The main takeaways from this code is 
1. Set an `onClick` handler on the parent component of your radio inputs
2. With the following code:

        if (values.group === e.target.id && e.target.checked) {
            e.target.checked = false;
            setValues({group: null})              
        }

3. The `id` and `value` fields on your inputs must be the same

Full Code example:

    <Formik>
        {({
            values,
            setValues,
            errors,
            touched,
            handleChange,
            handleBlur,
            handleSubmit,
            isSubmitting
            /* and other goodies */
        }) => (
            <form onSubmit={handleSubmit}>
                <fieldset onClick={(e) => { // <- note: onClick not onChange
                    // Check if currently selected value in group is the currently clicked item and its already active
                    if (values.group === e.target.id && e.target.checked) {
                        e.target.checked = false; // deactivate it
                        setValues({group: null}) // set value to null since nothing is selected              
                    }
                }}>
                    <label>
                        <input
                            type="radio"
                            name="group"
                            id="one"
                            onChange={handleChange}
                            onBlur={handleBlur}
                            value={"one"}
                        />
                    </label>
                    <label>
                        <input
                            type="radio"
                            name="group"
                            id="two"
                            onChange={handleChange}
                            onBlur={handleBlur}
                            value={"two"}
                        />
                    </label>
                    <label>
                        <input
                            type="radio"
                            name="group"
                            id="three"
                            onChange={handleChange}
                            onBlur={handleBlur}
                            value={"three"}
                        />
                    </label>
                </fieldset>
            </form>
        )}
    </Formik>
