### ISSUE TITLE
`isValid` is true even when there are invalid fields

### ISSUE THREAD

**Issue by skattyadz** [jaredpalmer/formik#102]
#97 introduces `isInitialValid` which marks the form invalid when it's initialized. This gives a confusing result as soon as the form is dirty.

~Because `isValid` works by counting the number of items in `errors`, it doesn't check for fields which haven't had blur events.~ In our project we observed this as a submit button going from disabled to enabled after entering a valid value into an input, even though the other fields weren't valid. This feels like an unexpected behaviour.

Do you have a pattern to deal with this? I understand that you don't want fields to show errors until they're been blurred, but for this case I'd expect formik to keep track of invalid fields even if they haven't been touched

Thanks
Adam

**Comment by jaredpalmer** [comment]
@skattyadz Yeah, should probably have it check for both touched and errors / keys match?

**Comment by skattyadz** [comment]
@jaredpalmer After digging through the code I've discovered that Formik doesn't work in the way I thought when I wrote that ^. formik does validate every field once one is blurred

Correct me if I'm wrong, but is [this](https://github.com/jaredpalmer/formik/blob/0c692260183318c2b1fd19d7ee806aa27e0ef975/src/formik.tsx#L532) doing the opposite of what it should be?

I'd expect the form to be valid if it's dirty and there are *no* errors

**Comment by jaredpalmer** [comment]
No you are 100% correct, this is a mistake. Adding pushing up a patch now + tests
