### ISSUE TITLE
Confusing usage on React Native about `handleChange` and `setFieldValue`

### ISSUE THREAD

**Issue by ivanquirino** [jaredpalmer/formik#1021]
## 📖 Documentation
In the `handleChange` and `handleBlur` formik's props we have the following note: "DOM-only. Use setFieldTouched in React Native.". But int the React Native gist, there is:
```
 onChangeText={props.handleChange('email')}
 onBlur={props.handleBlur('email')}
```
Which form is correct?

**Comment by abglassford** [comment]
I'd also note that in `formik/Formik.tsx`, there's this comment: 

![screen shot 2018-12-05 at 2 05 11 pm](https://user-images.githubusercontent.com/18131395/49543966-d3620780-f896-11e8-91a2-f94b4945411d.png)

**Comment by jaredpalmer** [comment]
Yeah we probably need to update the docs.
