### ISSUE TITLE
What difference between use cases?: submit Form and handleSubmit

### ISSUE THREAD

**Issue by nitaking** [jaredpalmer/formik#1027]
## ❓Question

Looking at the [source](https://github.com/jaredpalmer/formik/blob/a7ce4580926a54dc36b6e1d02d3c5743a6df34eb/src/Formik.tsx#L381-L411), it seems that `submitForm` is used for `handleSubmit`.

What is the difference between these two use cases?

I used to be ReactNative before, as follows.

- `handleSubmit`: caused an error (related to binding?)
- `submitForm`: no error

I want to understand why `submitForm` was solved, but I could not understand it even by looking at the [document](https://jaredpalmer.com/formik/docs/guides/form-submission).
Could anyone tell me?

(sorry if duplicate it.)

**Comment by jaredpalmer** [comment]
handleSubmit can be passed as is to a form's onSubmit event and preventDefault. submitForm cannot.

**Comment by nitaking** [comment]
@jaredpalmer 
thanks. I could understand.

it's close.

**Comment by buschco** [comment]
Is there any difference for react-native? Which one should I use 🤔

**Comment by johnrom** [comment]
@buschco use `<Button onClick={handleSubmit} />` as documented here:

https://jaredpalmer.com/formik/docs/guides/react-native
