### ISSUE TITLE
[docs] Add guide for radio and checkbox input

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/formik#1035]
## 📖 Documentation

I looked through our Algolia DocSearch analytics and it seems like people are searching for radio and checkboxes. Let's create a guide in the docs just for this.

<img width="931" alt="screenshot 2018-10-22 09 57 56" src="https://user-images.githubusercontent.com/4060187/47296751-3ba7a300-d5e1-11e8-9fca-50eb865203b1.png">

**Comment by amcvitty** [comment]
Anecdotally, I was searching for it because they don't bind to values like you'd expect.

#1050 
#1024

I'm going to have a crack at a PR for that

**Comment by adamduncan** [comment]
Hi @jaredpalmer, is there any update on these docs please?

There are a few related PRs (#1064, #1115), as well as some different approaches (#363, #602) being proposed by users of Formik from time to time.

Would be super helpful to have definitive examples of: single checkbox (true/false value), checkbox group (array of values) and radio group (single value).

Thanks

**Comment by maitandat1507** [comment]
Are there any official link to new docs for this? I try to find on Official page https://jaredpalmer.com/formik/ but still can't get it.
I appreciate your help. Many thanks!

**Comment by Andreyco** [comment]
closing in favor of #1315

**Comment by etoxin** [comment]
I would suggest documentation over examples. Just saying.

**Comment by Fieel** [comment]
@Andreyco  y tho

**Comment by ironbyte** [comment]
Why is v2 still not fully documented?

**Comment by hungvu193** [comment]
any updates here?
