### ISSUE TITLE
TypeError: field.resolve is not a function

### ISSUE THREAD

**Issue by sibelius** [jaredpalmer/formik#1040]
### Current Behavior

it was working fine yesterday, but today it stopped working \o/

it is throwing this error;

```jsx
Uncaught (in promise) TypeError: field.resolve is not a function
    at eval (object.js?0109:159)
    at eval (transform.js?50ca:60)
    at arrayEach (_arrayEach.js?8057:15)
    at transform (transform.js?50ca:59)
    at ObjectSchema._cast (object.js?0109:147)
    at ObjectSchema._validate (mixed.js?b64f:261)
    at ObjectSchema._validate (object.js?0109:187)
    at ObjectSchema.validate (mixed.js?b64f:303)
    at validateYupSchema (formik.esm.js?2983:519)
    at eval (formik.esm.js?2983:175)
```

### Expected behavior

it should not thrown an error

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.0.3 and 1.3.1 (tested on both)
| React            | 16.4.1
| TypeScript       | using pure js
| Browser          | chrome
| npm/Yarn         | yarn
| Operating System | mac os

**Comment by sibelius** [comment]
never mind, bug on our validationSchema

tks

**Comment by Srikrishnan96** [comment]
I had this same problem while using nested forms ... I later realized that with nested forms every level on nesting should be wrapped in yup.object ... I did that and it worked for me ... hope this helps :)

**Comment by fedevegili** [comment]
I spent a few minutes trying to solve this issue just to find out that I forgot the method call:

wrong:
```
{
  first_name: Yup.string().required
}
```

correct:
```
{
  first_name: Yup.string().required()
}
```

**Comment by cavasinf** [comment]
In my it was the "object" passed through `initialValues` that was more detailed than the validation schema.

#### User schema
```js
{
  firstname: Yup.string().nullable().required(),
  lastname: Yup.string().nullable(),
}
```

#### User object (through `initialValues`)
```json
{
  "firstname": "Foo",
  "lastname": "Bar",
  "username": "Foo Bar"
}
```

I guess, Yup is trying to resolve the schema for `username` but there is no "field" to resolve for username..

**Comment by ibarapascal** [comment]
> I had this same problem while using nested forms ... I later realized that with nested forms every level on nesting should be wrapped in yup.object ... I did that and it worked for me ... hope this helps :)

This saved my ass.

Maybe it's off-topic, but for someone facing this problem as well, you may want to flatten/unflatten the generated schema but have this issue. (about each layer's `yup.object`)

For me, I just changed my approach to directly using flatten schema with a different delimiter like `_` rather than `.`, and unflatten at the final step, hope it could help.

**Comment by b5414** [comment]
I ran into the problem of a nested handler, it has wrote exactly this error, so for the same as me - I leave this code here brothers

// Material UI + formik (useFormik) + yup
// yup nested object validation

```js
const validationSchema = yup.object({
	nested_object_name: yup.object({
		some_name: yup.string().required(),
	}),
});

const Compo = ()=>{
	const formik = useFormik({
		initialValues: {
			nested_object_name: {
				some_name: 'value',
			},
		},
		validationSchema: validationSchema,
		onSubmit: (values)=>{
			alert(JSON.stringify(values, null, '\t'));
		},
	});

	return (
		<>
			<TextField
				name='nested_object_name.some_name'
				value={formik.values.nested_object_name.some_name}
				label='some name'
				placeholder='some name'
				error={Boolean(formik?.touched?.nested_object_name?.some_name && formik?.errors?.nested_object_name?.some_name)}
				helperText={formik?.touched?.nested_object_name?.some_name && formik?.errors?.nested_object_name?.some_name}
				onChange={formik.handleChange}
				onBlur={formik.handleBlur}
			/>
		</>
	);
};
```

**Comment by vstezhko** [comment]
> 

I have the same 
// Material UI + formik (useFormik) + yup
// yup nested object validation

And the same unresolved problem
Warning: An unhandled error was caught during validation in <Formik validationSchema /> TypeError: field.resolve is not a function formik.esm.js:449

**Comment by syedali042** [comment]
> I had this same problem while using nested forms ... I later realized that with nested forms every level on nesting should be wrapped in yup.object ... I did that and it worked for me ... hope this helps :)

You know @Srikrishnan96, you've just saved my life, thanks :👍👍

**Comment by WATA-Yiju** [comment]
if the data what you validate like this...

```js
{
    kim: {
        age: 30,
        country: 'Seoul'
    },
    joan: {
        age: 28,
        country: 'Jeju'
    }
}
```

then you should generate schema like that. nested schema should have to wrap by yup.object().shape()
```js
const schemaShape = {
    kim: yup.object().shape({
        age: yup.number(10).require(),
        country: yup.string().required()
    }),
    joan: yup.object().shape({
        age: yup.number(10).require(),
        country: yup.string().required()
    })
};

const schema = yup.object().shape(schemaShape);
```
