### ISSUE TITLE
Your sample in sandbox is broken

### ISSUE THREAD

**Issue by golestanirad** [jaredpalmer/formik#1043]
## 📖 Documentation
I went [here ](https://codesandbox.io/s/zKrK5YLDZ) to see the demo but after entering my email and clicking on submit it threw an error 

![image](https://user-images.githubusercontent.com/12256921/47441740-08dee580-d76e-11e8-804a-c622e9593d19.png)

**Comment by michaelryancaputo** [comment]
Can easily be fixed by adding a line between 24 & 25: `onSubmit={console.log}`

**Comment by jaredpalmer** [comment]
Fixed.
