### ISSUE TITLE
Use Formik errors outside of Formik

### ISSUE THREAD

**Issue by aiwatko** [jaredpalmer/formik#1045]
First of all, thanks for all the effort put in creating Formik, it's an amazing tool 👏 🚀 

I have a page with several Formik components and with one button (outside Formik) that needs to depend on those Formik forms errors, i.e. it needs to be enabled (on Formik input field change) if there is no error on any of the forms and disabled back if a validation error is triggered. 

Is there any recommended way to link an external component to internal Formik(s) state and if so, what is the recommended way of doing it?

**Comment by tejovanthn** [comment]
Hey, I think you can use the `connect` [api](https://github.com/jaredpalmer/formik/blob/30773c916017416539da17a82dc37caf6d7cd083/website/versioned_docs/version-1.2.0/api/connect.md) of `Formik`. 
There's an example in the documentation too.
