### ISSUE TITLE
setStatus within handleSubmit *without* overriding status

### ISSUE THREAD

**Issue by stephenrose** [jaredpalmer/formik#1054]
I see `handleSubmit` handler examples with something like:

`setStatus({error:"error message"})`

However, this will **replace** the status of the app.

And unfortunately in the [docs](https://jaredpalmer.com/formik/docs/api/formik#onsubmit-values-values-formikbag-formikbag-void), it mentions:

> Note: errors, touched, status and all event handlers are NOT included in the FormikBag.

So its impossible to do:

`setStatus({...status, error:"error message"})`

Is it not possible to **append** the global status within `handleSubmit`?

I am already storing several global settings in setStatus, but want to set some error message status as well.

**Comment by stephenrose** [comment]
Turns out this is a duplicate of an [open ticket rased two days ago](https://github.com/jaredpalmer/formik/issues/1049).

**Comment by stephenrose** [comment]
Because of this limitation of formik, and a deadline… I'm ending up making my own [Context](https://reactjs.org/docs/context.html), which I put in the root of the app, so I can store "global" values there, and use them throughout the app.

**Comment by jaredpalmer** [comment]
You can use `setFormikState` as a workaround.
