### ISSUE TITLE
How to fill dynamic select fields 

### ISSUE THREAD

**Issue by JSoet** [jaredpalmer/formik#1057]
## ❓Question

I have a question about how to fill select fields which are filled dynamically based on the selected value of another field. 

We're currently using Formik along with Redux and Redux Sagas. When we select one of our fields then it needs to request the possible values for the next field from the server, so we have a handler on the first field, which sends an action (including the current values of the form), triggers a saga, gets the results back from the server, and then writes the results to the store (including the values that existed when the select was selected). We originally had trouble getting this to work until we found out about the enableReinitialize option, but then that re-wrote all the values which the user had entered with only the new values which were grabbed from the server, which is why we had to add the part about saving the current values of the form. This always seemed kind of hacky to me, but it worked until now.

Now we added a new part to our app, which triggers a re-occurring call to the server to get some profile information about the user. This is then passed into the form, but the problem is now that since we don't re-save the current form values which the user has entered before every profile refresh, the form gets re-initialized every time the profile gets refreshed and the user's currently entered values are lost.

Anyway, I'm wondering if there is another pattern we're missing for how to set the dynamic field values. Like I said, it seems kind of hacky to me so I was hoping that there was a better way to do it, but I couldn't find any existing questions about this, which I find surprising, because it seems to me that this should be a common use case? 

If not, then is there any other way to tell Formik when to re-initialize the form other than just the enableReinitialize which reinitializes whenever any of the props passed into the form change?

**Comment by klis87** [comment]
@JSoet maybe do a custom Formik field select component if you dont have it already and connect this to redux to get options, instead of connecting Formik parent component? Then you won't have any rerendering issues.

**Comment by JSoet** [comment]
Hey @klis87, thanks, but we "need" to connect the form itself to the store because the initial values for the form are also retrieved from the server... But I investigated a bit more and I noticed that actually the form isn't just re-initializing when the props which are passed into it change, but whenever the root state changes... This doesn't seem like it should be happening, is it possible we have something set up wrong, or could this be a bug? We have the form component hooked up to the store as follows (since the values in the form are retrieved from the server and stored in the redux store) connect(mapStateToProps, Actions)(formikEnhancer(component))... Should we not be connecting our formik form directly to the store? Or any other ideas?

**Comment by JSoet** [comment]
Oh, I just realized that the problem was that we were using this.props.values.options for the select field, which is why we thought we had to use enableReinitialize... But if we switch to use this.props.options instead then of course that prop holds the latest values directly from the store, which gets around the whole problem, so we can turn off enableReinitialize... Thanks for the tips

**Comment by klis87** [comment]
@JSoet you can always connect the whole form to redux to get initial state, but it doesnt prevent you from connecting a field to get options too. Glad it is working for you now.

Btw, instead of automatic `enableReinitialize`, you can use Formiks `resetForm: (nextValues?: Values) => void` in a lifecycle component method to have more control.

**Comment by JSoet** [comment]
Thanks @klis87 I didn't realize about the resetForm method either :)

**Comment by MareoRaft** [comment]
@JSoet Can you post a code example of what worked?  In particular, I don't know how you managed to fetch the latest values of the form.  The only way I can get a hold of the latest values of the form is through the `onSubmit/handleSubmit` function.

**Comment by JSoet** [comment]
Hi @MareoRaft, we were using the withFormik wrapper, and with that you can get the latest values through `props.values`: https://jaredpalmer.com/formik/docs/api/withformik ... Then for us the initial values were available as the normal props which are still passed through, so `props.<yourField>`
