### ISSUE TITLE
Old error shown when setFieldValue and setFieldTouched are executed together

### ISSUE THREAD

**Issue by skattyadz** [jaredpalmer/formik#106]
After executing the following code, Formik shows an error based on the previous value. The order of the two lines doesn't make a difference.

```js
this.props.setFieldValue('rating', value);
this.props.setFieldTouched('rating', true);
```

Wrapping `setFieldTouched` in `setImmediate` solves the problem so I presume it's some kind of race condition?

**Comment by jaredpalmer** [comment]
Are you in React Native land? In the browser, React batches update to state in response to a change/blur event. Not sure if this behavior is mimicked in RN.

**Comment by skattyadz** [comment]
No, this is in the browser. I'm using a custom StarRating component and the
change is triggered by an onClick under the hood. I assume it would work
properly with radio elements and their onChange, then

**Comment by jontansey** [comment]
FYI in case it's helpful `setValue` and `setTouched` also present the same issue.

**Comment by joshuawootonn** [comment]
Why was this closed :/

**Comment by delphin92** [comment]
I still have this issue:

```
/* Custom field component */
const [field, meta, {setValue, setTouched}] = useField({name: controlId, ...props});
const change = (year, month) => {
        setValue({year: year, month: month});
        setTouched(true);
    };

/* Validation */
yup.addMethod(yup.mixed, 'monthYearLessThan', function (monthYear, message) {
    return this.test('monthYearLessThan', message, function (value) {
        console.log(value);
        return isMonthYearLess(value, this.parent[monthYear]);
    })
});
```

I am changing the value from 2016-01 to 2020-02. The validation was called twice, with new and old value:
```
{year: 2020, month: 2}
{year: 2016, month: 1}
```
So, field was marked as valid, that is incorrect.

I was forced to WA:
```
setValue({year: year, month: month});
setFieldTouched(name, true, false);
```

**Comment by Madyuskin** [comment]
This is still not fixed, wrapping in **setTimeout()** does help, but we need a real fix.

```
setTimeout(
  () => {
    setFieldValue()
  },
  1
)
```

**Comment by lgellert** [comment]
I'm stuck on Fomik 1.5.8 until this gets cleaned up, was working with 2.1.5.
