### ISSUE TITLE
Improving performance with large forms

### ISSUE THREAD

**Issue by albert-olive** [jaredpalmer/formik#1062]
Hi, 

I'm using formik with large forms and I have seen that the performance is bad. I'm using ```Field``` because ```FastField``` is not re-rendering some changes. Also I had to change ```<Formik />``` to ```withFormik()``` in order to use ```shouldComponentUpdate``` and compare: ```nextProps.values === this.props.values```, set ```validateOnChange: false``` and then, the performance has improved a lot (Before that, it was rendering 3 times, inside ```<Formik />```, at every keyboard press).

Just want to put my 5 cents in order to improve this awesome tool :)

**Comment by jaredpalmer** [comment]
Thank you for the feedback. This is exactly how you should optimize--the way you would optimize any React component btw. To me, you story says that we have the correct escape hatches in place. With concurrent React in v2, we will also see a massive perf boost, so stay tuned.

**Comment by jaredpalmer** [comment]
You may find 1.4.0 much more performant https://github.com/jaredpalmer/formik/releases/tag/v1.4.0
