### ISSUE TITLE
 How to set className prop of ErrorMessage component?

### ISSUE THREAD

**Issue by Jungwoo-An** [jaredpalmer/formik#1067]
I can't set className of ErrorMessage when using typescript. cause is `className` is not defined in [ErrorMessage interface](https://github.com/jaredpalmer/formik/blob/master/src/ErrorMessage.tsx#L6).

Thanks.

**Comment by Jungwoo-An** [comment]
Yes. i think it's enough. can i help this issue?

**Comment by akhil-gautam** [comment]
> Yes. i think it's enough. can i help this issue?

Ya sure. Please add a PR for the fix.
