### ISSUE TITLE
Is there recommended way to intercept input values before calling handleChange

### ISSUE THREAD

**Issue by danhayden** [jaredpalmer/formik#107]
I'm trying to format values as users enter data (for formatting card numbers, uppercasing postcode etc.) so I created a function to intercept and change the value before calling `handleChange`:

```js
function handleChangeInterceptor(event, handleChange) {
  event.target.value = event.target.value.toUpperCase();
  handleChange(event);
}

// <input onChange={event => handleChangeInterceptor(event, handleChange)} />
```

This seems to work fine in most browsers but in Safari if you try to edit the value anywhere before the last character the cursor jumps to the end of the input.

When using `handleChange` directly its works as expected, but when intercepting it has the behaviour described above.

Here is a demo to show the issue https://codesandbox.io/s/ADOxMO4zP?hidenavigation=1

Do you know why this may be happening, or perhaps a better way to format values on change?

Thanks

**Comment by jaredpalmer** [comment]
You can use setFieldValue within a bound event handler in a class component

**Comment by danhayden** [comment]
Thanks for your response. Would you mind providing a little more information.

I have tried using the following code:

```js
<input onChange={event => props.setFieldValue(event.target.name, event.target.value.toUpperCase()) } />
```
demo here => https://codesandbox.io/s/nDwvwJBl

But it is subject to the same issue in Safari.

**Comment by midnightcodr** [comment]
I am facing the same problem in Safari, for example
```js
    onChange={e => {
        setFieldValue(
        'amount',
        e.currentTarget.value.replace(/[^0-9\.]/g, '')
        )
    }}
```

works in google Chrome but not Safari. I think this is due to [this](https://stackoverflow.com/questions/47664777/javascript-file-input-onchange-not-working-ios-safari-only). I am clueless on how to fix that.
