### ISSUE TITLE
Support for arrays within arrays

### ISSUE THREAD

**Issue by crsandeep** [jaredpalmer/formik#1093]
I am trying to migrate my app which currently uses redux-form to use Formik.  I have a scenario where I have arrays within arrays (actually I have arrays within arrays within arrays). This is the sample example for arrays within arrays which uses redux-form https://codesandbox.io/s/Ww4QG1Wx. Is it possible to achieve something like this Formik? Any pointers would help me to get started with the migration.

Edit: I asked this question in discord as well but did not get any response

**Comment by jaredpalmer** [comment]
Yes, this is supported.

**Comment by crsandeep** [comment]
@jaredpalmer it would be great if you can point me to some documentation or any sample code for this

**Comment by jaredpalmer** [comment]
```jsx
<FieldArray name="friends">
{() => 
   <>
      {props.values.friends.map((friend, index) => 
         <FieldArray name={`friends[${i}].friends`} key="..." >
            {() => 
              <>{friend.friends.map((fof, jindex) => /** just keep going */)}</>
            }
        </FieldArray>
      )}
   </>
}
</FieldArray>
```

**Comment by crsandeep** [comment]
@jaredpalmer thanks
