### ISSUE TITLE
The equivalent of componentDidMount

### ISSUE THREAD

**Issue by Manocry** [jaredpalmer/formik#1099]
## ❓Question

How to init the initial value with api call instead of the following :
```
initialValues={{
firstName: "",
lastName: "",
email: "",
favoriteColor: ""
}}
```

**Comment by prichodko** [comment]
Initiate API call outside of Formik and pass it as prop to `initialValues`. You may need to set https://jaredpalmer.com/formik/docs/api/withFormik#enablereinitialize-boolean to true, depends on your use case.

I also recommend to learn how to format your code in Markdown - [here](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by brodybits** [comment]
I wonder if this can be documented more clearly?

**Comment by Manocry** [comment]
Thank you @prichodko but your recommendation doesn't works for me. For example :

```
  async componentDidMount() {
   //This the api call 	
   const apidata =  await axios.get('/api/data')
    this.state.initialValues.apidata = apidata.data;
  }
```

  And the call in the Formik is the following 

```
  const App = (props) => (
    <div>
      {console.log("props.categorylist in wizard " + JSON.stringify(props.initialValues))}
      <Wizard
          initialValues= {props.initialValues}
          ........
```

**Comment by jaredpalmer** [comment]
Use a component? Why is this reopened?

**Comment by prichodko** [comment]
New issue pointing to this one opened here - https://github.com/jaredpalmer/formik/issues/1105, so I closed in favor of original (this) one.

**Comment by prichodko** [comment]
@Manocry in your code snippet, you are directly mutating `state` (which does not cause rerender) instead of calling `setState`, which could mean that you are not very familiar with React yet. I recommend reading awesome official (docs)[https://reactjs.org/docs/introducing-jsx.html].

**Comment by Manocry** [comment]
In the following example https://codesandbox.io/s/o7kn2q45lq, I just want to pass the api call result as a props to the Wizard instead of the following block
```
       initialValues = {{
         firstName: "",
         lastName: "",
         E-mail: "",
         favoriteColor: "",
         choice: ""
       }}
```
I do not know where to position the componentDidMount function. Thanks for your help.

**Comment by jaredpalmer** [comment]
@Manocry 
```jsx
class App extends React.Component {
   state = {}
   componentDidMount() {
    Axios.get('https://jsonplaceholder.typicode.com/todos/1').then(res => {
      this.setState({ data: res.data });
    });
  }

  render() {
   if (!this.state.data) {
     return 'loading...'
    }
   return <Wizard
      initialValues={thist.state.data}
      ...
    />
  }
}
```

**Comment by Manocry** [comment]
@jaredpalmer Thank you for the solution. It's work
