### ISSUE TITLE
resetForm Typings

### ISSUE THREAD

**Issue by benneq** [jaredpalmer/formik#1110]
### Current Behavior
`FormikActions.resetForm`'s argument is of type `any`
This allows stuff like `resetForm(42)` or `resetForm({})` even if `initialValues` is an non-empty object. (see codesandbox below)

### Expected behavior
Typings should be more restrictive

### Reproducible example
https://codesandbox.io/s/n7wwl51jz0

Just open Browser Console and press "Submit".

### Suggested solution(s)
Provide a "real" type for `resetForm`. I guess it should be something like `resetForm(nextValues?: Values)`. I'm note entirely sure if `resetForm` accepts some other kind of arguments, too.

### Additional context
Another question in that context that came to my mind: What's the difference between `resetForm` and `setValues`? Both look pretty similar to me. Wouldn't it make sense if one of both would accept `Partial<Values>`?

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.3.2
| React            | 16.6.3
| TypeScript       | 3.1.6
| Browser          | Chrome 70
| npm/Yarn         | npm 6.4.1
| Operating System | macOS 10.14.1

**Comment by gakin95** [comment]
can someone please give a typescript example
