### ISSUE TITLE
Manually Triggering Validation Example is not working

### ISSUE THREAD

**Issue by Davidmycodeguy** [jaredpalmer/formik#1112]
## 📖 Documentation
I copy the code at
https://jaredpalmer.com/formik/docs/guides/validation#manually-triggering-validation

In the example this line breaks the code. 
`<button type="button" onClick={() => validateForm().then(() => console.log(blah)))}>`

It should be
```
<button type="button" onClick={() => validateForm().then(() => console.log("blah"))}>
```

**Comment by Davidmycodeguy** [comment]
I have solved my issue.

In my use case, I had to validate the form then do something different than onSubmit function that is passed to formik as a prop. 

I got around this creating another function that submits the form manually and just adds different logic. Hope it helps someone.  

``` onSubmitDoSomethingDiffrent(props){
props.submitForm()
// do suff here

 setTimeout(() => {
     props.setSubmitting(false);
    }, 1000);
} ```

**Comment by jaredpalmer** [comment]
Can you submit a PR?

**Comment by Davidmycodeguy** [comment]
Yes, I will send soon.

**Comment by atharvajava** [comment]
is this resolved because i am not able to trigger it as well ??
