### ISSUE TITLE
Formik not getting installed

### ISSUE THREAD

**Issue by Jvalal** [jaredpalmer/formik#1114]
I'm trying to try and use/install formik. I'm able to run the install, but with some NPM warnings. I thought it still was installed but using, which or trying to find version doesn't give me any result. 

![image](https://user-images.githubusercontent.com/3803053/48638231-dbf4ab80-e984-11e8-9053-598463b42253.png)

**Comment by jaredpalmer** [comment]
Def don’t install -g

--
Jared

________________________________

**Comment by Jvalal** [comment]
ok, still not working.

![image](https://user-images.githubusercontent.com/3803053/48639479-9a65ff80-e988-11e8-94b9-19eda9e834b0.png)

**Comment by Jvalal** [comment]
It's clearly installing somewhere.

![image](https://user-images.githubusercontent.com/3803053/48641830-e10b2800-e98f-11e8-95c0-f27eeee0553f.png)

**Comment by jaredpalmer** [comment]
Formik is not a CLI. There is no bin command

**Comment by jaredpalmer** [comment]
Closing as this isn’t an issue with Formik.

**Comment by Jvalal** [comment]
thanks for the help. I love devs that help new folks through issues, even
when they're unrelated to their products.

**Comment by jaredpalmer** [comment]
It is installed in node_modules/formik
