### ISSUE TITLE
material-ui bindings

### ISSUE THREAD

**Issue by evdama** [jaredpalmer/formik#1117]
## 📖 Documentation
Both, formik and material-ui are two very prominent libraries.
https://github.com/stackworx/formik-material-ui is a binding to ease the use of formik with material-ui and I think it's worth mentioning this in the docs.

**Comment by jaredpalmer** [comment]
Feel free to submit a PR!

**Comment by Rasheed08** [comment]
@RasheedAljuhani

**Comment by nik72619c** [comment]
anyone working on this?

**Comment by jcolbyfisher** [comment]
I'll take a stab at adding this to the docs.
