### ISSUE TITLE
Do the test examples work?

### ISSUE THREAD

**Issue by skattyadz** [jaredpalmer/formik#112]
Hi Jared. I'm sorry I'm swamping you with issues at the moment

There are a couple of things about the text examples I'd like clarity on:

```js
await tree.find(MyInnerForm).props().submitForm()
```

Using await here gives the impression that `submitForm` returns a promise, which is misleading ([relevant lines](https://github.com/jaredpalmer/formik/blob/master/src/formik.tsx#L407-L435)). If you're using async validations via `validate` or `validationSchema` then it's going to return immediately before before `executeSubmit` is executed

Is it better to just use `executeSubmit` which is sync?

```js
tree.find(MyInnerForm).update().dive()
```

I'm pretty new to Enzyme so found this confusing. Enzyme tells me I can only call `update()` on the root wrapper

**Comment by jaredpalmer** [comment]
AFAIK Awaiting `submitForm()`, will trigger async validation. You can confirm this here...

https://github.com/jaredpalmer/formik/blob/master/test/formik.test.tsx#L335

**Comment by skattyadz** [comment]
Those tests verify that the function gets called, not whether the await is blocking. I have a strong suspicion that the tests will still pass if you remove the 'await' keyword. 

Here's my failing test case:

#### Fails
```js
  it('handles successful submission', async () => {
    const submitMock = () => Promise.resolve();
    const wrapper = shallow(<ReviewForm submitReview={submitMock} />);
    expect(wrapper.length).to.equal(1);

    const getForm = () => wrapper.update().find('InnerForm');
    const diveFind = query => wrapper.update().dive().find(query);

    await getForm().props().submitForm();

    expect(getForm().props().status).to.deep.equal({ success: true });
    expect(diveFind('Success').length).to.equal(1);
    expect(diveFind('form').length).to.equal(0);
  });
```

#### Passes
```js
  it('handles successful submission', async () => {
    const submitMock = () => Promise.resolve();
    const wrapper = shallow(<ReviewForm submitReview={submitMock} />);
    expect(wrapper.length).to.equal(1);

    const getForm = () => wrapper.update().find('InnerForm');
    const diveFind = query => wrapper.update().dive().find(query);

    await getForm().props().submitForm();

    return new Promise(r => setImmediate(r)).then(() => {
      expect(getForm().props().status).to.deep.equal({ success: true });
      expect(diveFind('Success').length).to.equal(1);
      expect(diveFind('form').length).to.equal(0);
    });
  });
```

**Comment by Magellol** [comment]
@skattyadz I'm facing the same issue. I also had to ask the test runner to wait the next tick to do my asserts. Would that be fixed if `submitForm` would return a promise (#79), so we could reliably wait for it to complete (yup validation + actual handleSubmit logic).

**Comment by skattyadz** [comment]
I've just taken a quick look at those tests and it could easily be a false
positive. I can't see another test checking a happy path with an async
promise

**Comment by jaredpalmer** [comment]
These need to be rewritten in 0.9

**Comment by jaredpalmer** [comment]
Move this discussion to #154
