### ISSUE TITLE
The values of the form do not change when the state changes.

### ISSUE THREAD

**Issue by zalmes** [jaredpalmer/formik#1120]
I have simple form, I update state of component, but the form shows not actual data.
What the reason of such behavior?
Thank you

render(){

    let initValues = { ...this.state.account }
 console.log('initValues',initValues)--->STATE CONTAINS GOOD DATA
return(
   <Formik
                                            enableReinitialize   
                                            validationSchema={accountsDetailsSchema}
                                            initialValues={initValues}
                                            onSubmit={this.onSubmitHandler}>

                                            {({ setFieldTouched,
                                                isSubmitting,
                                                errors,
                                                setFieldValue,
                                                handleChange,
                                                handleBlur,
                                                values,
                                                touched }) => (<Form>

   {console.log('values',values)}  ----->DISPLAY NOT ACTUAL DATA

                                                    <div className="form-group">
                                                        <label htmlFor="AccountNumber">Account Number</label>
                                                        <Field type="text" disabled={this.state.isDisabled}
                                                            name="AccountNumber" className="form-control" />
                                                        <ErrorMessage component="div" className='errorMessage' 
                                                         name='AccountNumber' />
                                                        </div>
                                                     
                                                    <div className="form-group">
                                                        <label htmlFor="AccountName">Account Name</label>
                                                        <Field type="text" disabled={this.state.isDisabled}
                                                            name="AccountName" className="form-control" />
                                                        <ErrorMessage component="div" className='errorMessage' name='AccountName' />
                                                    </div>
                                                    <div className="form-group">
                                                        <label htmlFor="AddressLine1">Address Line 1</label>
                                                        <Field type="text"
                                                            placeholder="Enter a Address Line 1"
                                                            name="AddressLine1" className="form-control" />
                                                        <ErrorMessage component="div" className='errorMessage' name='AddressLine1' />
                                                    </div>
                                                    <div className="form-group">
                                                        <label htmlFor="SecondAddressLine2">Address Line 2</label>
                                                        <Field type="text"
                                                            placeholder="Enter a Address Line 2"
                                                            name="AddressLine2" className="form-control" />
                                                        <ErrorMessage component="div" className='errorMessage' name='AddressLine2' />
                                                        </div>
                                                    <div className="form-group">
                                                        <label htmlFor="City">City</label>
                                                        <Field type="text"
                                                            placeholder="Enter a City"
                                                            name="City" className="form-control" />
                                                        <ErrorMessage component="div" className='errorMessage' name='City' />
                                                    </div>
                                                    <div className="form-group">
                                                        <label htmlFor="State">State</label>
                                                        <Select
                                                            name="State"
                                                            options={this.state.states}
                                                            value={values.State}
                                                            touched={touched.State}
                                                            onChange={(item) => {
                                                                setFieldValue('State', item);
                                                            }}
                                                            onBlur={() => {
                                                                setFieldTouched('State', true);
                                                            }}
                                                        />
                                                        <ErrorMessage component="div" className='errorMessage' name='State' />
                                                        </div>
        
                                                    <div className="form-group">
                                                        <label htmlFor="ZipCode">Zip Code</label>
                                                        <MaskedInput mask={[/\d/, /\d/, /\d/, /\d/, /\d/]}
                                                            className="form-control"
                                                            placeholder="Enter a Zip Code"
                                                            name="ZipCode"
                                                            guide={false}
                                                            onChange={handleChange}
                                                            onBlur={handleBlur}
                                                            value={values.ZipCode}
                                                         /> 
                                                                      </Form >
                                            )}
                                        </Formik>)
}

**Comment by yuritoledo** [comment]
Hello @zalmes 

Can you create a codesandbox ?

**Comment by jaredpalmer** [comment]
Please fill out the issue template so that this can be addressed. Closing for now.
