### ISSUE TITLE
resetForm nextValues won't update initialValues 

### ISSUE THREAD

**Issue by vvav3** [jaredpalmer/formik#1121]
### Current Behavior

After successful submit I call resetForm(nextValues), but mapPropsToValues called afterwards has previous values received first time form mounted. enableReinitialize is true

### Expected behavior

mapPropsToValues receives correct nextValues

### Reproducible example

https://codesandbox.io/s/xr7vl9045o

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.3.2
| React            | 16.4.0
| Browser          | Chromium 70.0.3538.77
| npm/Yarn         | Yarn 1.12.3
| Operating System | Ubuntu 18.04

**Comment by jaredpalmer** [comment]
Can you submit a PR?
