### ISSUE TITLE
async mapPropsToValues doesn't seem to work

### ISSUE THREAD

**Issue by smakosh** [jaredpalmer/formik#1129]
### Current Behavior
```js
mapPropsToValues: async () => {
  const test = await someFunction()
  return {
    example: test || ''
  }
},
```
returns `example` as undefined.

### Additional context

I'm using it on React native, here's the full snippet

```js
withFormik({
  mapPropsToValues: async () => {
    const linkCopied = await Clipboard.getString()
    return {
      link: linkCopied || 'test'
    }
  },
  validationSchema: ({ intl: { formatMessage } }) => Yup.object().shape({
    link: Yup.string().url(formatMessage({ id: 'invalid_url' }))
      .required(formatMessage({ id: 'required_field'
    })),
  }),
  handleSubmit({ link }, {
    props: { navigation, generate }, setErrors, setSubmitting, resetForm
  }) {
    generate(link, setSubmitting, navigation, setErrors, resetForm)
  }
})
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.3.0
| React            | 16.5.0
| TypeScript       |
| Browser          |
| npm/Yarn         | Yarn 1.12.1
| Operating System | macOS Mojave

**Comment by jaredpalmer** [comment]
Correct. It does not support async behavior.

**Comment by smakosh** [comment]
Oh, I see, thanks!

**Comment by danielpox** [comment]
So, what is the recommended way of solving this?

**Comment by smakosh** [comment]
Since I'm using `recompose` I solved my issue using the `lifecycle` HOC like so:

```jsx
lifecycle({
  async componentDidMount() {
    const linkCopied = await Clipboard.getString()
    this.setState({ linkCopied })
  }
}),
withFormik({
  mapPropsToValues: ({ linkCopied }) => ({
    link: linkCopied || 'test'
  }),
  validationSchema: ({ intl: { formatMessage } }) => Yup.object().shape({
    link: Yup.string().url(formatMessage({ id: 'invalid_url' }))
      .required(formatMessage({ id: 'required_field'
    })),
  }),
  handleSubmit({ link }, {
    props: { navigation, generate }, setErrors, setSubmitting, resetForm
  }) {
    generate(link, setSubmitting, navigation, setErrors, resetForm)
  }
})
```

**Comment by danielpox** [comment]
I simply added `enableReinitialize: true`, even though that might case some unexpected results later on.

**Comment by smakosh** [comment]
This issue was about using `async/await` within `formik` and not enabling props reinitialization.

**Comment by digitaltopo** [comment]
This would be a great feature... useful for getting data from an api in an edit form for example

**Comment by smakosh** [comment]
You can get your data from a parent component and pass them as props to your form component
