### ISSUE TITLE
Formik used with slatejs in array throws error

### ISSUE THREAD

**Issue by VojtechVidra** [jaredpalmer/formik#1140]
## 🐛 Bug report
Formik used with slatejs in array throws error

### Current Behavior
I am using Formik and slatejs editor in array and every time the value of editor changes, it throws error. In this example i have two editors in array and when you click in any it crashes, because slatejs changes value on focus. I think it has something to do with immutable, but I may be mistaken. I used draft-js with the same setup and it worked fine. So maybe this is related to slatejs, I am not sure.

### Reproducible example

https://codesandbox.io/s/8n0olr8nq2

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.3.2
| React            | 16.5.0
| Slate           | 0.44.6
| Slate-react  | 0.21.12

**Comment by jaredpalmer** [comment]
I don't know enough about slatejs internals. cc @ianstormtaylor any thoughts?

**Comment by VojtechVidra** [comment]
I solved this by converting RichEditor to class component and storing the Value in state. My onChange function of RichEditor: 

```
onChange = value => {
    this.setState({ value });
    const { updating } = this.state;
    if (updating) {
        clearTimeout(updating);
    }
    const timeout = setTimeout(
        () =>
            this.props.onChange(
                this.props.name,
                htmlSerializer.serialize(value)
            ),
        500
    );
    this.setState({ updating: timeout });
};
```

 It's not the best solution, but for small amout of text works just fine. With large amout of text it takes a bit longer, but that is related to SlateJS update performance. If someone has a better idea how to approach this I would be grateful.

**Comment by nithinkashyapn** [comment]
Hey @VojtechVidra,

Can you share the entire snippet with `<FormArray />` ?

Thanks.

**Comment by ayepRahman** [comment]
Hey @VojtechVidra , did you manage to find a better solution for updating the Rich Editor?

**Comment by VojtechVidra** [comment]
Hey @ayepRahman actually I used tinymce instead. Tinymce manages it's own state and only exposes couple of events. It uses HTML as a default format so there is not much performance impact when saving to formik state. If you dont care about custom design and customized features tinymce is way to go. I am using tinymce, not react-tinymce and it works just fine in react.
