### ISSUE TITLE
Set a more descriptive displayName in the connect() HOC

### ISSUE THREAD

**Issue by doug2k1** [jaredpalmer/formik#1145]
### Current Behavior

A component wrapped with the `connect()` function shows as `<C ...>` in the components tree, making it difficult to debug and test.

### Desired Behavior

Connected components should have a more descriptive name, similar to what Redux and other libs do. Ex: `<FormikConnect(OriginalName) ...>`.

### Suggested Solution

Set the `displayName`of the resulting component.

### Who does this impact? Who is this for?

Easier debugging with React devtools and easier testing with Enzyme.

**Comment by jaredpalmer** [comment]
Great Idea. Can you submit a PR?

**Comment by doug2k1** [comment]
Sure. I'll take a look.

**Comment by lubarskyy** [comment]
This issue can be closed due to merged PR #1152
