### ISSUE TITLE
Looking for an example of formik form with the the submit button located in different part of the same page

### ISSUE THREAD

**Issue by brightpixels** [jaredpalmer/formik#1154]
Am looking for an example of formik form with the the submit button located in different part of the same page due to the page has been designed.

**Comment by sebasrodriguez** [comment]
@brightpixels I think that another approach would be to save the Formik ref and pass it to a parent component. And with that reference you can later call the submitForm function. Something like this:

```
<Formik
        ref={(formikRef) => this.setForm(formikRef)}
/>
```

In this case setForm is a function prop implemented in the parent component and stores the reference to formik.

You need to be careful with this approach cause I think it might lead to memory leaks if the form gets unmounted.

**Comment by criles25** [comment]
https://reactjs.org/docs/portals.html could solve your problem. Just wrap your submit button with it.
