### ISSUE TITLE
Typescript 3.2 breaks with strictFunctionTypes enabled in tsconfig

### ISSUE THREAD

**Issue by chdsbd** [jaredpalmer/formik#1155]
### Current Behavior
Typescript v3.2 with strict mode enabled raises errors for onSubmit and render methods of `<Formik/>`

### Expected behavior

Typescript v3.1.6 configured with the same settings doesn't raise an error.

### Reproducible example

I've update [this template](https://codesandbox.io/s/rwxkxl279n), but you need to download it and use typescript@3.2.1 (you can use vscode to select the correct version after running yarn install).

### Suggested solution(s)

I'm not sure if this is a TS issue or a Formik issue. I'm surprised the upgrade changed anything because it appears that there are only a few, seemingly unrelated breaking changes with typescript 3.2.

__EDIT:__ It seems there is one related breaking change here: https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#caveats
__EDIT:__ Disabling `strictFunctionTypes` is tsconfig hides the issue.
__EDIT:__ This may be related: https://github.com/Microsoft/TypeScript/issues/20704
__EDIT:__ This too: https://github.com/Microsoft/TypeScript/issues/27972

### Additional context

My project that has the issue is running newer versions of Formik and React, but I've been able to reproduce using that code sandbox I linked above.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.2.1
| React            | 16.2.0
| TypeScript       | 3.2.1
| Browser          | N/A
| npm/Yarn         | N/A
| Operating System | N/A

**Comment by jaredpalmer** [comment]
This has been fixed in 1.4.3.
