### ISSUE TITLE
Image drop (upload) with preview + Formik

### ISSUE THREAD

**Issue by mwickett** [jaredpalmer/formik#117]
Has anyone integrated something like [`react-dropzone`](https://github.com/okonet/react-dropzone) with Formik? 

I'm having a hard time getting the pattern right on this one.

**Comment by jaredpalmer** [comment]
@mwickett Formik is not designed to do the image upload itself. You should use react-dropzone's `onDrop` to upload the file to your API media endpoint and then just store the returned file path in Formik state using `setFieldValue`. You can use something like `setStatus()` to track the upload's progress/success/failure etc.

**Comment by msmaromi** [comment]
@jaredpalmer  I think `setFieldValue` only can be called via `onChange`. CMIIW.

**Comment by nicoqh** [comment]
@msmaromi `setFieldValue` can be used without `onChange`.

**Comment by MontoyaAndres** [comment]
I'm trying to upload an image through Formik with React-Dropzone, this is the main code:

```
onDrop = ([file]) => {
    const {
      field: { name },
      form: { setFieldValue }
    } = this.props;

    setFieldValue(
      name,
      Object.assign(file, {
        preview: URL.createObjectURL(file)
      })
    );
  };
```

The part:

```
Object.assign(file, {
  preview: URL.createObjectURL(file)
})
```

It's only to do a [preview of an image](https://react-dropzone.netlify.com/#previews). When I do Click in the handleSubmit, only sends me the preview object, the rest of the info disappear.

![gif](https://im2.ezgif.com/tmp/ezgif-2-0d88d5ed874a.gif)

![screenshot from 2019-02-05 18-50-51](https://user-images.githubusercontent.com/15065852/52312004-faac8200-2976-11e9-9388-a20dcf479c9c.png)

Someone can help me? If you need more info, I can create a issue to explain it bettter I guess...

**Comment by caiorios** [comment]
@MontoyaAndres I faced the same issue. The complete object is contained inside the array, so to use them, just iterate over it:

```
JSON.stringify(
    {
        files: values.fotos.map(file => ({
            fileName: file.name,
            type: file.type,
            size: `${file.size} bytes`
        }))
    }
)
```
