### ISSUE TITLE
Compilation error with TypeScript

### ISSUE THREAD

**Issue by alexssandr1992** [jaredpalmer/formik#1175]
Hi,

I use next configuration

tsconfig.json
{
  "compilerOptions": {
    "baseUrl": "ClientApp",
    "target": "es5",
    "jsx": "react",
    "module": "es2015",
    "lib": [ "es6", "dom" ],
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "skipDefaultLibCheck": true,
    "strict": true,
    "removeComments": true
  },
  "exclude": [
    "bin",
    "node_modules"
  ]
}

package.json:

{
  "devDependencies": {
    "@types/react-helmet": "^5.0.7",
    "@types/history": "^4.6.2",
    "@types/lodash": "^4.14.110",
    "@types/react": "^16.7.6",
    "@types/react-dom": "^16.0.9",
    "@types/react-hot-loader": "^4.1.0",
    "@types/react-modal": "^3.1.2",
    "@types/react-redux": "^6.0.2",
    "@types/react-router": "^4.0.26",
    "@types/react-router-dom": "^4.2.7",
    "@types/react-router-redux": "^5.0.15",
    "@types/webpack-env": "^1.13.6",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^3.0.0",
    "aspnet-webpack-react": "^3.0.0",
    "awesome-typescript-loader": "^5.1.1",
    "css-loader": "^0.28.11",
    "file-loader": "^1.1.11",
    "ignore-loader": "^0.1.2",
    "image-webpack-loader": "^4.3.1",
    "mini-css-extract-plugin": "^0.4.0",
    "node-sass": "^4.9.0",
    "optimize-css-assets-webpack-plugin": "^5.0.1",
    "postcss-loader": "^2.1.5",
    "react-hot-loader": "^4.3.12",
    "sass-loader": "^7.0.3",
    "svg-react-loader": "^0.4.5",
    "svg-react-loader2": "^1.0.0",
    "typescript": "^3.2.2",
    "uglifyjs-webpack-plugin": "^2.0.1",
    "url-loader": "^1.0.1",
    "webpack": "^4.12.0",
    "webpack-cli": "^3.1.2",
    "webpack-dev-middleware": "^3.1.3",
    "webpack-hot-middleware": "^2.22.2",
    "webpack-merge": "^4.1.4"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "bind-decorator": "^1.0.11",
    "connected-react-router": "^5.0.1",
    "domain-wait": "^1.1.0",
    "formik": "^1.4.0",
    "history": "^4.7.2",
    "json-to-url": "^1.0.5",
    "react": "^16.6.3",
    "react-dom": "^16.4.1",
    "react-helmet": "^5.2.0",
    "react-localization": "^1.0.10",
    "react-modal": "^3.4.5",
    "react-redux": "^5.0.7",
    "react-router-dom": "^4.3.1",
    "react-router-redux": "^4.0.8",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0"
  }
}

but when I compile, than have many errors in module formik

etc Universal component ComponentClass<P>  is require arguments type of 0 or 1
in file  Field.d.ts

**Comment by jaredpalmer** [comment]
Can you fill out the bug report template and create a sandbox?
