### ISSUE TITLE
How to build the form from a JSON structured data in componentDidMount ?

### ISSUE THREAD

**Issue by Jyodsh** [jaredpalmer/formik#1185]
Hi ,

I have a non-formik implementation and I would like to convert it into Formik.
But my form fields are dynamic and  I will get those information from a REST API. 

**Current implementation.**
All forms are in a modal and when ever user clicks on the CTA , I will make an API call and get the corresponding form data in a JSON response.
Right now I am doing that API call from `componentDidmount` for a better performance. 
Based on the JSON data I will create the form fields and render the same.

Can I achieve the same functionality using Formik ?

I am having some non-solvable and typing issues with current implementation so looking for a solution with Formik.

Thanks

**Comment by weyert** [comment]
Why wouldn't you be able to? You can just render the Formik component after the JSON has been fully loaded?
