### ISSUE TITLE
Formik automatically converts number value type to string

### ISSUE THREAD

**Issue by egorzaremba** [jaredpalmer/formik#1191]
## 🐛 Bug report
<img width="1428" alt="screen shot 2018-12-18 at 4 10 24 am" src="https://user-images.githubusercontent.com/31797554/50126622-b8bc6500-027e-11e9-8a93-447ea1fac94b.png">

I guess I do something silly
so I try to send data to my server, which contains numbers and string types, but if user changes number type fields, Formik will automatically convert number type value to string type

Here is my code

```
import { Button, Form } from 'semantic-ui-react'
import { Formik, Field } from 'formik'
import { Mutation } from 'react-apollo'

import { InputField } from '../components/formik-fields/InputField'
import { ErrorMessage } from '../components/ErrorMessage'
import { normalizeErrors } from '../utils/normalizeErrors'
import {
  CreateOfferMutation,
  CreateOfferMutationVariables
} from '../lib/schema-types'
import { createOfferMutation } from '../graphql/offer/mutation/createOffer'

interface FormValues {
  city: string
  price: number
  place: string
  position: string
  wage: number
  hoursOfWeek: number
}

// @todo validation schema
export default () => (
  <Mutation<CreateOfferMutation, CreateOfferMutationVariables>
    mutation={createOfferMutation}
  >
    {mutate => (
      <Formik<FormValues>
        // @todo fix somehow, formik converts number type to string
        initialValues={{
          city: '',
          place: '',
          position: '',
          price: 0,
          wage: 0,
          hoursOfWeek: 0
        }}

        // its my fix, but maybe there is a better solution
        onSubmit={async (input, { setErrors, setSubmitting }) => {
          const numberInput = ['price', 'wage', 'hoursOfWeek']
          const cloneInput = { ...input }

          Object.keys(cloneInput).forEach(key => {
            if (numberInput.indexOf(key) > -1) {
              cloneInput[key] = parseFloat(cloneInput[key])
            }
          })

          const response = await mutate({
            variables: { input: cloneInput }
          })

          if (
            response &&
            response.data &&
            response.data.createOffer.errors &&
            response.data.createOffer.errors.length
          ) {
            setSubmitting(false)
            return setErrors(normalizeErrors(response.data.createOffer.errors))
          } else {
            setSubmitting(false)
            console.log(response)
            console.log('offer created successful')
          }
        }}
        validateOnBlur={false}
        validateOnChange={false}
      >
        {({ errors, handleSubmit, isSubmitting }) => (
          <Form onSubmit={handleSubmit}>
            <Field
              name="city"
              label="City"
              placeholder="City"
              component={InputField}
            />
            <Field
              name="price"
              label="Offer price"
              placeholder="Offer price"
              component={InputField}
            />
            <Field
              name="place"
              label="Place of work"
              placeholder="Place of work"
              component={InputField}
            />
            <Field
              name="position"
              label="Position of work"
              placeholder="Position of work"
              component={InputField}
            />
            <Field
              name="wage"
              label="Wage per hour"
              placeholder="Wage per hour"
              component={InputField}
            />
            <Field
              name="hoursOfWeek"
              label="Hours of week"
              placeholder="Hours of week"
              component={InputField}
            />
            <ErrorMessage errors={errors as any} />
            <Button disabled={isSubmitting} type="submit">
              Create offer
            </Button>
          </Form>
        )}
      </Formik>
    )}
  </Mutation>
)

```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | "formik": "^1.3.2", |
| React            | "react": "^16.6.3", |
| TypeScript       | "typescript": "3.2.2" |
| Browser          | Google chrome Version 70.0.3538.110 |
| npm/Yarn         | yarn -v 1.12.3 |
| Operating System | MacOS Mojave v 10.14 |

**Comment by Saifadin** [comment]
You are not giving your input the type=number prop, it is a type=text so it will treat it like a string.

**Comment by Enzyoh** [comment]
What if you are not using typescript then?

**Comment by Enzyoh** [comment]
What is you are not using typescript? just es6

**Comment by Fieel** [comment]
@Saifadin this is not true in case of components such as the selelct field. Values are always converted into string.

**Comment by philipwilsonchang** [comment]
I can second that this happens on the select field.

**Comment by dgwaldo** [comment]
So how do you handle the select options with out doing some casting in the code?

**Comment by johnrom** [comment]
Think of it backwards -- onChange's event.target.value is _always_ string unless you use some hacky workarounds (maybe react native supports other primitives? not my wheelhouse). Formik is nice and says "if event.target.type is number, convert the string to a number". If you use a select dropdown, Formik cannot infer the value should be a number for you, since number-like strings shouldn't always be converted to numbers in everyone's code. So you'll have to do the cast yourself, like:

```jsx
<select onChange={event => formik.handleChange(event.target.name)(parseInt(event.target.value, 10))} />
```
In a future version, a parse API has been added to make this easy: #2255

**Comment by dgwaldo** [comment]
@johnrom What if <Field type="number" as="select" /> just did the casting for you?

**Comment by johnrom** [comment]
`Field`'s type prop specifically maps to `input`'s type prop, so I personally think this would be confusing (there is no `<select type="" />` prop), and not that much better of a dev experience than `<Field as="select" parse={stringToIntValueConverter} />` where `const stringToIntValueConverter = (value: string) => parseInt(value, 10);`.

**Comment by giraffesyo** [comment]
Ran into this same issue where I'm using a select that has numeric values and I'm just having to cast within the `onSubmit` function.
```typescript
const class_type = parseInt((values.class_type as unknown) as string,10)
```

**Comment by Probug** [comment]
@giraffesyo please may i have a glimpse at your code?

**Comment by irzum-intangible-solutions** [comment]
while using select it converts the number to string because of which when you revert back the selected option in EDIT form it still says` !dirty = true,` because previously it was number but on you changed now it's converted to string so you wont get `!dirty = false` ever again. is there anyway to keep it in number so we can play with !dirty properly?

**Comment by irzum-intangible-solutions** [comment]
You need to use formic function serFieldValue
```
onChange={(e) => {
    setFieldValue(
      "FieldName",
      parseInt(e.target.value)
    );
  }}
```

**Comment by port-dav** [comment]
How do I make the value field become number instead of string.

**Comment by imprisonedmind** [comment]
2024 and we still have to handle roll solutions for select is wild!
