### ISSUE TITLE
Form is submitted if there are uncaught errors in validate function

### ISSUE THREAD

**Issue by emmenko** [jaredpalmer/formik#1198]
### Current Behavior

At the moment, if within the `validate` function an error is thrown, Formik does not handle it, causing the form to be submitted as it thinks there are no validation errors.

![2018-12-19 16 04 46](https://user-images.githubusercontent.com/1110551/50228298-dcc79580-03a7-11e9-9444-670516373ba2.gif)

### Expected behavior

If an error is thrown, Formik should handle it and do not allow to submit the form.

### Reproducible example

https://codesandbox.io/s/5klqjpl00k

### Suggested solution(s)

~~I think the problem is in the `runValidateHandler` function~~

https://github.com/jaredpalmer/formik/blob/13954fdd10070f727a0259dbbf98824cb980fa92/src/Formik.tsx#L223-L241

~~Given that the `this.props.validate` is wrapped within the `new Promise`, if an error is thrown it will be swallowed.~~

~~The fix is to properly handle those errors.~~

Update: after digging a bit more into the code, the problem is in the `submitForm` function

https://github.com/jaredpalmer/formik/blob/13954fdd10070f727a0259dbbf98824cb980fa92/src/Formik.tsx#L446

If `combinedErrors` is an instance of an `Error`, the check passes

<img width="245" alt="image" src="https://user-images.githubusercontent.com/1110551/50235074-54e98780-03b7-11e9-93a1-b3f74633c845.png">

### Your environment

See codesandbox dependencies.

**Comment by emmenko** [comment]
I can open a PR with the fix if you'd like.

**Comment by emmenko** [comment]
I'm working on the fix. I also noticed that some tests are false positives as they assert "too early". I'll show you in the PR.

**Comment by jaredpalmer** [comment]
Yeah. This is a bug. Thanks for the write up!

**Comment by emmenko** [comment]
Btw: I think part of the problem is in the `submitForm` function

https://github.com/jaredpalmer/formik/blob/13954fdd10070f727a0259dbbf98824cb980fa92/src/Formik.tsx#L446

If `combinedErrors` is an instance of an `Error`, the check passes

<img width="245" alt="image" src="https://user-images.githubusercontent.com/1110551/50235074-54e98780-03b7-11e9-93a1-b3f74633c845.png">

I'll describe it more in detail in the PR.

**Comment by probablyup** [comment]
This is a sample impl of what I ended up doing for our internal projects:

```js
import { get, set } from 'lodash';

export const VALIDATION_TYPE = {
  EXISTS: 1,
  CUSTOM: 2,
};

const BAD_VALUES = ['', NaN, null, undefined];

// not falsy, because 0 and false are allowed
export function isFalsish(x) {
  return BAD_VALUES.includes(x);
}

/**
 * Helper factory for creating formik field validations. Use it like this:
 *
 * ```js
 * import { createValidator, VALIDATION_TYPE } from 'macaw/utils/formik';
 *
 * const handleFormValidation = createValidator({
 *  'address.addressOne': [[VALIDATION_TYPE.EXISTS, 'Please provide the street address']],
 *  'address.zipCode': [
 *    [VALIDATION_TYPE.EXISTS, 'Please provide the zip code'],
 *    [
 *      VALIDATION_TYPE.CUSTOM,
 *      'Please provide a valid zip code',
 *      x => x.replace(/\D/g, '').length === 5,
 *    ],
 *  ],
 *  'phoneNumber': [[VALIDATION_TYPE.EXISTS, 'Please provide a phone number']],
 * });
 *
 * // ...
 *
 * <Formik validate={handleFormValidation}>...</Formik>
 * ```
 *
 * For very obtuse validation that doesn't fit cleanly into the below, a second argument can be
 * passed to `createValidator` as a "finalizer" function: (errors, values) => errors.
 *
 * Just make sure to return the errors object.
 *
 * The validations are performed sequentially and short-circuits for a particular field once
 * an error has been assigned to be shown.
 *
 * createValidator({
 *   [key]: [
 *     [
 *       type: VALIDATION_TYPE.*,
 *       errorMessage: String | (fieldValue, allValues) => String,
 *       customValidationFunction: (fieldValue, allValues) => Boolean, // this is not run for VALIDATION_TYPE.EXISTS
 *     ]
 *   ],
 * })
 *
 * For the second argument (error message), you may pass a function instead with this signature:
 * (fieldValue, allValues) => String
 *
 * For custom validation, pass a function to the third argument with this signature:
 * (fieldValue, allValues) => Boolean
 *
 */
export const createValidator = (mapping, finalizer = x => x) => values => {
  let errors = {};

  /**
   * For whatever reason formik will try to submit anyway if there is an error inside this function,
   * which is super obviously not the right thing to do.
   */
  try {
    for (let key in mapping) {
      mapping[key].forEach(([type, message, validatorFunc]) => {
        const getMessage = typeof message === 'function' ? message : () => message;

        // short circuit if an error is already set for for this leaf of the model
        if (!get(errors, key)) {
          let val = get(values, key);

          switch (type) {
            case VALIDATION_TYPE.EXISTS:
              if (typeof val === 'string') val = val.trim();

              if (isFalsish(val)) set(errors, key, getMessage(val, values));
              break;

            case VALIDATION_TYPE.CUSTOM:
              if (!validatorFunc)
                console.error(`No validation function supplied for key ${key}`, new Error().stack);
              else if (!validatorFunc(val, values)) set(errors, key, getMessage(val, values));
              break;

            default:
              console.warn(`Unknown form error matcher type supplied, ${type}.`);
              break;
          }
        }
      });
    }
  } catch (e) {
    alert(e.message);

    return {
      _: '',
    };
  }

  errors = finalizer(errors, values);

  if (process.env.NODE_ENV !== 'production') {
    console.warn('FORMIK VALIDATION ERRORS', errors);
  }

  return errors;
};
```

Specifically see the try/catch inside the validator factory

**Comment by rathpc** [comment]
The latest patch makes this bug even more apparent now that it sends uncaught exceptions to the console. Please fix!

**Comment by jaredpalmer** [comment]
Yeah i made a mistake with 2.0.7. It's the wrong model. Will revert
