### ISSUE TITLE
Form becomes "isValid" briefly which breaks the tests

### ISSUE THREAD

**Issue by FredyC** [jaredpalmer/formik#1199]
### Current Behavior

When a form is validated for the first time, the `isValid` prop becomes `true` once while it's not correct and then it gets flipped back to `false` and it works correctly after that. This is problematic when running tests against `jsdom` environment as the next update is not seen there.

### Expected behavior

I am not sure what's behind this, but such extra rerender with the invalid state shouldn't be there for sure.

### Reproducible example

[https://codesandbox.io/s/8lj2r5vzol](https://codesandbox.io/embed/8lj2r5vzol?module=%2Fsrc%2Fform.test.js&previewwindow=tests)

There is a test file which actually passes just fine because it's executed against the real DOM. When you look in the console, you see there one render with `isValid === true`.

When you download the sandbox, install dependencies and `npm run test` it will fail because of the jsdom environment which I assume is faster and sees the first invalid render instead of the latest one.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.4.1
| React            | 16.7.0-alpha.2
| TypeScript       | 3.2.2
| Yarn             | 1.10.1
| Operating System | Windows 10 x64

**Comment by eachtime** [comment]
same problem here.

**Comment by hanneswidrig** [comment]
Having this issue when using a callback to get the validity. I am not sure of a solution off the top of my head. I just manually checked the length of the touched fields equal to required fields as a backup.
