### ISSUE TITLE
FieldArray updating when only modifying a FastField

### ISSUE THREAD

**Issue by stramel** [jaredpalmer/formik#1200]
### Current Behavior

Have a `FieldArray` in a `Form` and a fast field in the same form `FastField`. 

When updating only the `FastField`, the entire `FieldArray` updates.

### Expected behavior

Have a `FieldArray` in a `Form` and a fast field in the same form `FastField`. 

When updating only the `FastField`, only the `FastField` should update.

### Reproducible example

https://codesandbox.io/s/6j8w6l3kjw

### Additional context

The performance hit here is negligible, however, my forms internally are quite more complex featuring multiple `FieldArray`s each containing multiple `react-select`s and additional `@material-ui` `TextField`s. This has lead to a lot of unnecessary updates and slow performance.  

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.4.1      |
| React            | 16.6.0     |
| TypeScript       | 3.1.6      |
| Browser          | Chrome 71  |
| npm/Yarn         | 1.12.1     |
| Operating System | Mojave 10.14.1 |

**Comment by jaredpalmer** [comment]
FastField broadcasts its updates to all other Fields and FieldArrays. You would need to implement shouldComponentUpdate in component that wraps FieldArray.

**Comment by jaredpalmer** [comment]
In other words, this isn’t a bug, but rather intended behavior.

**Comment by stramel** [comment]
Alright, I will look into writing a `FastFieldArray` or something similar. Thank you for the quick reply.
