### ISSUE TITLE
Formik hidden field sending null value to server

### ISSUE THREAD

**Issue by abdulqadir88** [jaredpalmer/formik#1202]
Hello There,

I am new to React i am using FormIK which is posting Form data fine unless i add a hidden field into it.

When i post form it sends the Null value of hidden field 
 `<Field type="hidden" className="form-control" name="hiddenField" ></Field>`

Also i have provided initial values to Formik

```
<Formik initialValues={{
            first_name:'',last_name:'',username:'',email:'',password:'',
            password_confirmation:'',distributor:'',phone_number:'',address:'',country:'',
            state:'',city:'',zip_code:'',hiddenField:''
        }} >
```
Any thing which i am missing ?

**Comment by jaredpalmer** [comment]
Each Field needs a name prop

**Comment by jaredpalmer** [comment]
and a value in initialValues in this situation

**Comment by rustedwolf** [comment]
I've just bumped to the same issue: I've tried to use `react-filepond` which generates `type="hidden"` field with async uploaded file data, but Formik still ignores it. Adding the name to the initialValues and to the `<Field component/>` doesn't seems to work.

**Comment by johnrom** [comment]
Your File Uploader needs to trigger Formik's setFieldValue() somehow. Either by passing the File object to initialValues and using enableReinitialize={true} (if updated after initial render), or by doing 

```jsx
<YourFileInput onChange={(value) => formik.handleChange("myField")} />
```

(I have no idea what FilePond is so you'll have to extrapolate my example above to work for you.)
