### ISSUE TITLE
How to pass state values to initial values in formik in react js

### ISSUE THREAD

**Issue by abhiram5** [jaredpalmer/formik#1206]
I'm using formik library in my react application. Initially, I declared state values in the constructor, In componentDidMount I'm calling an API with that app response am updating state values, Can anyone help me in passing state values to fomik initial values

In my situation formik taking initial state values which are declared in the constructor.thanks in advance

```

class Dropdown extends Component {
        constructor(props) {
            super(props);
            this.state = {
              //some data
            };
          }
          componentDidMount() {
           //api call
           this.setState( {
              //update state values with api response data
            });  
         }
       render() {
            return (
            <Formik
              initialValues={this.state}
              validate={validate(validationSchema)}
              onSubmit={onSubmit}
              render={
                ({
                  values,
                  errors,
                  touched,
                  status,
                  dirty,
                  handleChange,
                  handleBlur,
                  handleSubmit,
                  isSubmitting,
                  isValid,
                  handleReset,
                  setTouched
                }) => ( 
                 //form uses initialValues
              )} />
              )
            }
    }
```

**Comment by jaredpalmer** [comment]
Only render the form if your data in state is defined. Otherwise render a loading indicator

**Comment by dgpro** [comment]
@abhiram5 why not to use [enableReinitialize](https://jaredpalmer.com/formik/docs/api/formik#enablereinitialize-boolean)?

**Comment by co2nut** [comment]
@dgpro i'm afraid it will reset the value for other fields

**Comment by ezplora** [comment]
@co2nut , you should set default values for the state data you pass to `initialValues`
