### ISSUE TITLE
[1.4.X] submitForm() isn't hitting handler because combinedErrors = {isCanceled: true}

### ISSUE THREAD

**Issue by MikeSuiter** [jaredpalmer/formik#1209]
### Current Behavior

I'm using [Component Component](https://ui.reach.tech/component-component) to automatically submit my form when a select field changes. The sandbox below works if you use Formik 1.3.2 but doesn't hit the handleSubmit with 1.4.1. Debugging into Formik from my real app shows that in submitForm() it does this:

```
      return _this.runValidations(_this.state.values).then(function (combinedErrors) {
        _this.setState({
          isValidating: false
        });
```

In the code above `combinedErrors = {isCanceled: true}` but I don't know why and I'm assuming this is why my handleSubmit() isn't being called. 

### Expected behavior

My handleSubmit() to be called. 

### Reproducible example

[![Edit Formik Effect vs Component^2](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/p30y4qw2mq)

The console will show when submitForm() and handleSubmit() get called. Typing in the name field will cause submitForm() to get called. If you change the Formik version to 1.3.2 in the sandbox it calls handleSubmit()

### Suggested solution(s)

I'm not sure this is a bug or something changed from 1.3.X to 1.4.X. If you have any suggestions on why isCanceled is being set please let me know. 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.4.1
| React            | 16.7.0
| Browser          | Chrome
| Yarn         |  1.12.3
| Operating System | Windows 10

**Comment by jaredpalmer** [comment]
Hrmmm....you are using submitForm() in a way that's not really intended. What's happening is that you are triggering another validation after you call submitForm() by another handleChange or a handleBlur  because you are submitting your forms on each key stroke.

**Comment by MikeSuiter** [comment]
@jaredpalmer In my real app it's a select field and not a text field but has the same problem. It's a select field to filter a grid and I make a REST call each time the filter changes. Any suggestions on how to do this? I really don't want to add a button as I don't want to make an extra step for the users.

**Comment by jaredpalmer** [comment]
Since this is not a side-effect, something like Formik Effect  (or the didUpdate approach) is not going to work consistently. What you should do is write a custom component for your select that accepts an `onSelect` function like: 

```
<Select
    onSelect={(value) => {
      setFieldValue('thing', value, false) /** last arg tells formik not to run validation and make this change synchronously  */
      submitForm()
   }} 
/>
```

**Comment by MikeSuiter** [comment]
I'll the suggestion posted above. I did try this and it works but seem hacky.

`setTimeout(props.submitForm, 10);`

**Comment by jaredpalmer** [comment]
Did you try with the 3rd argument of setFieldValue?

**Comment by MikeSuiter** [comment]
Yes I have this handler which seems to be working fine. Thanks for your help. 

```javascript
  handleProcessChange = (setFieldValue, submitForm) => event => {
    let { value } = event.target;
    let processIds = value;
    const idx = value.indexOf('');

    if (idx === value.length - 1) {
      value = [''];
      processIds = [];
    } else if (idx === 0) {
      value = value.slice(1);
      processIds = value;
    }

    this.setState({ processIds: value });
    setFieldValue('processIds', processIds, false);
    submitForm();
  };
```

PS - we just converted our redux-form app to Formik and like it a lot better but it's missing some functionality we were using. First redux-form Field has format and normalize which we use for dates, times, etc. and Formik doesn't have that. Second redux-form has FormSection which we use a lot because of our deep model structure. We have coded ways to get this to work with Formik but if they are on the roadmap that would be great to have someday.

**Comment by MikeSuiter** [comment]
@jaredpalmer I can close this unless you prefer to do it?

**Comment by jaredpalmer** [comment]
Thanks for the feedback. Much appreciated. Glad you found a solution that works.

**Comment by cloud-walker** [comment]
@MikeSuiter I still think you are doing it wrong, if you are avoiding the Formik logic, why forcing yourself to use the `formik.submitForm`? Just to trigger the `onSubmit` callback?

You can use the onSubmit callback directly, or the part you need about it

**Comment by MikeSuiter** [comment]
@cloud-walker I think what you're saying is to directly call my handleSubmit() instead of calling submitForm() which will do touched, validation, etc. then call my handleSubmit(). In this case this would work because I'm not doing any form validation just sending the value to the REST call. Heck I probably don't need Formik here at all.

**Comment by jaredpalmer** [comment]
All of this ^^^

**Comment by ematipico** [comment]
I came across with the same issue. This time not with the `setFieldValue` but with the `arrayHelpers`.
I think also these operations `remove`, `add`, etc provided by `arrayHelpers` should provide an option to run them in sync. Or, even better, make them asynchronous by default with a beautiful promise.

A workaround was adding a `setTimeout` to the `submitForm` function

**Comment by petargyurov** [comment]
Coming across this same issue too. Just wanted to reiterate that the workaround does work. 

In my instance I am having to keep track of some values outside of the form using my `redux` setup. Just prior to submitting I do `setFieldValue('myField', myField, true)` -- I need the 3rd param because I want to utilise the validation tests I have in place (using Yup).  The fields in question are all arrays; not sure if that matters.

Anyway, will have to use the workaround for now. If you don't need validation then setting the 3rd param to `false` should work. If you do _and_ you don't want to use the hack, then you'd have to do manual validation.
