### ISSUE TITLE
e.target is null in React Native web leading to error

### ISSUE THREAD

**Issue by MrLoh** [jaredpalmer/formik#1215]
### Current Behavior

I am getting an error in React Native Web when using the `handleBlur('email')` from the react native example: 
`formik.esm.js?8b7e:431 Uncaught TypeError: Cannot read property 'name' of null`

This seems to be because `e.target` is always accessed in the blur handler, in React Native Web it is null however. This is completely unnecessary, since `path` is always used as the field, when using the `handleBlur('email')` syntax. See

https://github.com/jaredpalmer/formik/blob/970e573307e5b7b11511366ffe0dd1a3c7b7a6c6/src/Formik.tsx#L465-L466

### Expected behavior

`e.target` shouldn't be accessed when it isn't needed

### Reproducible example

Not provided 

### Suggested solution(s)

Here is a PR: https://github.com/jaredpalmer/formik/pull/1216

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.4.1
| React            | 16.7.0
| Browser          | Chrome
| Operating System | MacOS Mojave

**Comment by MrLoh** [comment]
I ran into similar issues when calling `handleChange(key)` with a value other than a string (that is not an event either). I had this when for example using a React Native Switch element, which has a `onValueChange: (value: boolean) => void` signature, but also with custom input components for dates, and similar. I updated the PR to improve the handling in such cases.

**Comment by lautaro-osacar** [comment]
@MrLoh 
I Think that you should use `setFieldTouched` for `handleBlur` and `setFieldValue` for `onValueChange` on RN. 
(Check the docs: https://jaredpalmer.com/formik/docs/api/formik)

**Comment by MrLoh** [comment]
@lautaro-osacar not sure what you mean. But `handleBlur(fieldName)` and `handleChange(fieldName)` is definitely the [documented way](https://jaredpalmer.com/formik/docs/guides/react-native).

The issues are real and solved in my PR.

**Comment by MrLoh** [comment]
solved in #1216
