### ISSUE TITLE
Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by samuelcastro** [jaredpalmer/formik#1217]
### Current Behavior

When component is unmounted for any reason and a pending formik workflow is still pending an error message shows up:

```
index.js:2178 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Formik (created by WithFormik(class_1))
    in WithFormik(class_1) (created by Connect(WithFormik(class_1)))
```

### Expected behavior

No error 

### Reproducible steps

1 - Create a simple formik form.
2 - Make a submit event and change view right after. In my case I'm just redirecting the user to another route due to a non-authorized request.

### Versions

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |1.4.1
| React            | 16.7.0
| TypeScript       | 3.2.2
| Browser          | Chrome (71.0.3578.98)
| npm/Yarn         | 1.9.4
| Operating System | OSX

This is might be related:
https://github.com/jaredpalmer/formik/issues/772

**Comment by psachs21** [comment]
Also just ran into this. Except: react 16.6.3 and yarn 1.12.3.

**Comment by jaredpalmer** [comment]
Can you create a sandbox with your example?

**Comment by ZHamburglar** [comment]
Also just ran into this after previously not having issue.

**Comment by tu4mo** [comment]
Getting the same error with `react-testing-library`:

Form.js
```jsx
const Form = () => (
  <Formik initialValues={{ name: 'test' }}>
    {({ handleChange, values }) => (
      <input
        data-testid="name"
        name="name"
        onChange={handleChange}
        value={values.name}
      />
    )}
  </Formik>
)
```

Form.test.js
```jsx
test('test', async () => {
  const { getByTestId } = render(<Form />)
  fireEvent.change(getByTestId('name'), { target: { value: 'asdf' } })
})
```

**Comment by samuelcastro** [comment]
@jaredpalmer I'll create sandbox example asap, just not having the time now. :(

**Comment by rearmitage** [comment]
@tu4mo or anyone else have you had any luck? I'm running into the same issue right now.

**Comment by rearmitage** [comment]
I found the solution [here](https://github.com/kentcdodds/react-testing-library/issues/224)

**Comment by tu4mo** [comment]
`wait`:ing for `expect` solved my problem also. Thanks @rearmitage!

**Comment by lourenci** [comment]
I have this problem too. The `wait` is not a good solution, I could have tests that assert for a mock to not be called.

For example, I have a specific test that when I click on submit button and there are some error in the form, I want to be sure that the backend is not called. I just expect for the `fetchMock` for it doesn't be called.

**Comment by rearmitage** [comment]
You just run that assertion after the wait

```
await wait()
expect(mockSubmit).not().toHaveBeenCalled()
```
or if you don't have async/await

```
return wait().then(() => {
   expect(mockSubmit).not().toHaveBeenCalled()
}
```

**Comment by lourenci** [comment]
`wait` is not a good solution. This seems a problem with the component itself. I can't workaround my test because of it.

**Comment by jaredpalmer** [comment]
@lourenci have you tried with 1.4.3?
