### ISSUE TITLE
Use Formik To Help Manage State For Non-Traditional Text Inputs (i.e. wheel picker)?

### ISSUE THREAD

**Issue by mikeyamato** [jaredpalmer/formik#1219]
## ❓Question

Hey team. I've started to use Formik (via `<Formik render>`) with Yup for a React Native project to help manage state for name and email text inputs. In addition I'm using a [wheel picker](https://github.com/lesliesam/react-native-wheel-picker) for selecting a predefined value. Is it possible to use Formik to store state from the wheel picker? 

The selected value is returned as a string and I don't need to Validate anything if that helps.

![screen shot 2018-12-22 at 5 39 15 pm](https://user-images.githubusercontent.com/27756216/50584533-027f8080-0e25-11e9-85a1-e2a5e25422c8.png)

**Comment by jaredpalmer** [comment]
You can use `setFieldValue` or `handleChange` props.

**Comment by mikeyamato** [comment]
Very cool. Much thanks!
