### ISSUE TITLE
Multistep form

### ISSUE THREAD

**Issue by goodmind** [jaredpalmer/formik#122]
How to make multistep form (aka wizard) with distinct submit buttons, but one form state?

**Comment by jaredpalmer** [comment]
You can use status and setStatus or use multiple Formik components that handleSubmits lift up state

**Comment by jaredpalmer** [comment]
hey, this should be relatively straight forward with the render props API.

**Comment by goodmind** [comment]
@jaredpalmer hello, I tried to do something like this and found that I need intermediate API requests between some steps, this should be in components or in Formik HOC? https://codesandbox.io/s/Bgm22vjyo

**Comment by jaredpalmer** [comment]
This is quite elegant. This should be even easier with the `<Formik/>` component now

**Comment by goodmind** [comment]
@jaredpalmer any examples?

**Comment by jaredpalmer** [comment]
Yeah yours is how I would do it. I would just put async sideeffects inside of nextStep

**Comment by goodmind** [comment]
@jaredpalmer well, can you make it into official examples? Also I don't get how would I get field values in `nextStep`?

**Comment by dineshdoshi** [comment]
@goodmind @jaredpalmer Could you please update the example https://codesandbox.io/s/Bgm22vjyo to **validate the field on first step** and then go to next step.  Thanks

**Comment by willopez** [comment]
@jaredpalmer thanks for this lib, I believe it addresses one of the most painful aspects of integrating Reactjs and forms. A plus 1 for this wizard feature! Thanks!

**Comment by jaredpalmer** [comment]
I think there is a cool way to do this using render props and a `<Wizard step={1} />` component

**Comment by willopez** [comment]
That seems like a better approach, more than more levels of composition makes my head start spinning. I am thinking that the <Wizard /> component would have a management responsibility, it would manage displaying the form corresponding to the specified step. Further, it would merge all the data from the forms it manages and it would submit it. Each step form could be self contained, meaning it would have its own elements, validation etc... and it would elevate its state to the <Wizard /> just some food for thought.

**Comment by jaredpalmer** [comment]
100% agree @willopez

**Comment by adamduncan** [comment]
Love the approach! @willopez, do you think per-step validation would be easy enough to fold in? I guess each form's step would manage its own `validationSchema`? 🤔

**Comment by willopez** [comment]
@adamduncan Yeah, I was thinking that each step from would handle it's own validation. Whether it's easy enough to implement... we will see.

**Comment by jaredpalmer** [comment]
See multistep example

**Comment by kashifullahwebdeveloper** [comment]
@jaredpalmer I fixed the issue, I just change the following line:

`static Page = ({ children }) => children;`

to

```
static Page = ({ children }) => {
    return <div>{children}</div>;
}
```

And it worked!

Thank you so much for amazing form plugin!

**Comment by njj** [comment]
I've noticed the multistep example doesn't validate the the fields on the first step.  Has anyone else had this issue?

**Comment by LiranBri** [comment]
Thank you for the example.

Just all comment.. I would use refs to call the page's validate method, instead of the props trick. [something like this.](https://ourcodeworld.com/articles/read/327/how-to-execute-child-component-function-from-the-parent-component-in-react)

It feels wrong that the parent defined the logic of the internal page validation from outside.
for example, it would be hard to extract the page to its own component right now because of this

**Comment by HPieters** [comment]
> > @jaredpalmer, thank you for Multistep Form, but I am getting this error, and I am very new to React, could you please see this codeSandBox and let me know why I am getting this issue:
> > https://codesandbox.io/s/pp0p6p6qx0
> > Thank you
> 
> Great exemple.
> How to init the initial value with api call instead of the following :
> initialValues={{
> firstName: "",
> lastName: "",
> email: "",
> favoriteColor: ""
> }}

@Manocry I think StackOverflow or similar is a more appropriate channel for your question as it is not really an issue with the library? 

A approach here would be to call your API and use set state for instance. You can simply pass state to the initialValues={this.state.theValuesInState}. You can either choose to not show the form until the API call has been completed, or set the initial state to be empty and see the magic happen once you update state after the API call returns.

**Comment by devjones** [comment]
@LiranBri  Can you post a public sample of that code using the in page validation?

**Comment by abohannon** [comment]
How are you all passing props to the children of <Wizard.Page>? I'm doing the following but running into unexpected behavior (e.g. props being nested and not passing as expected). I need to pass the errors object + blur and touched props to the inputs so they may render their respective error messages.

```
// inside Wizard.jsx
static Page = ({ children, ...rest }) => {
     return Children.map(children, child => cloneElement(child, { ...rest }))
   }
```

**Comment by mjangir** [comment]
I've built a nice wizard component for formik. Please check out here:

[https://github.com/mjangir/formik-wizard-form](https://github.com/mjangir/formik-wizard-form)

**Comment by sunviwo** [comment]
Please @mjangir , can your package be used in React Native?
