### ISSUE TITLE
how to show a success message ?

### ISSUE THREAD

**Issue by converge** [jaredpalmer/formik#1221]
I have been researching about my issue, but couldn't find an answer. I'm new to Formik, and this is my first form validation using Formik.

I'm able to send the email and validate the fields, the only issue is that I'm not able to update/get the status to show an 'email sent' message. Can anyone assist ? Is this the right way to do it ?

When I try to use <div>Success message here: {status.success}</div> it throws an error:
TypeError: status is undefined

```javascript
import React from 'react'
import contactMeBar from '../../imgs/contactme_bar.png'
import './index.css'
import api from '../../services/api'
import { Formik, Field, Form, ErrorMessage } from 'formik'

const EmailForm = () => (
  <div>
    <div className="content-block contact-me-area">
      <p className="title-bar">
        <img src={contactMeBar} alt="Contact Me" />
      </p>
      <div className="email-form">
        <Formik
          initialValues={{
            name: '',
            email: '',
            subject: '',
            msg: '',
          }}
          validate={values => {
            let errors = {}
            if (!values.name) {
              errors.name = 'Name is required'
            } else if (!values.email) {
              errors.email = 'E-mail is required'
            } else if (!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(values.email)) {
              errors.email = 'Invalid email address'
            } else if (!values.subject) {
              errors.subject = 'Subject is required'
            } else if (!values.msg) {
              errors.msg = 'The email content is empty'
            }
            console.log(errors)
            return errors
          }}
          onSubmit ={ async (values, actions) => {
            actions.setSubmitting(false)
            // const response = await api.post('/send_email', {
            //   name: values.name,
            //   email: values.email,
            //   subject: values.subject,
            //   msg: values.msg
            // })
            const response = {}
            response.status = 200
            if (response.status === 200) {
              actions.setStatus( {success: 'Email sent !'} )
              actions.resetForm()
            }
            console.log('ok')
            console.log('response: ', response)
          }}
          render={({ isSubmitting, status }) => (
            <Form>
              <div className="email-item">
                <Field name='name' type='text' placeholder='Name' />
              </div>
              <div className="email-item">
                <Field name='email' type='email' placeholder='E-mail' />
              </div>
              <div className="email-item">
                <Field name='subject' type='text' placeholder='Subject' />
              </div>
              <div className="email-item">
                <Field component='textarea' name='msg' placeholder='Your message' />
              </div>
              <ErrorMessage name='name' className='field-validation' component='div' />
              <ErrorMessage name='email' className='field-validation' component='div' />
              <ErrorMessage name='subject' className='field-validation' component='div' />
              <ErrorMessage name='msg' className='field-validation' component='div' />
              <div>Success message here: {status.success}</div>
              <div className="email-item">
                <button type='submit' disabled={isSubmitting}>Submit</button>
              </div>
              
            </Form>
          )}
        />
      </div>
    </div>
  </div >
)

export default EmailForm
```

**Comment by yuritoledo** [comment]
Maybe the problem is here:
```
actions.setStatus( {success: 'Email sent !'} )
actions.resetForm() 
```
Try to switch the lines.

Or, if possible, create a codesandbox, to we better understand test it.

**Comment by converge** [comment]
@yuritoledo switching lines didn't fix the issue.

Thank you for your suggestion, I created a codesandbox:

[![Edit 0o45qnl9m0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0o45qnl9m0)

**Comment by yuritoledo** [comment]
Thanks, I've fix it

The error appear, because on first render, the `status` is `undefined`, so, the `success` prop doesnt exists.

I fix it just doing a ternary:  `Success message here: {x.status ? x.status.success : ''}`

**Comment by converge** [comment]
@yuritoledo thank you so much!! It's working smoothly 🎉 🎉

**Comment by yuritoledo** [comment]
é nois!

**Comment by rjain15** [comment]
@yuritoledo can you please make the codesandbox available again. I want to see the codesandbox to do the same.

**Comment by yuritoledo** [comment]
@rjain15 I deleted it :/

What problem are you facing?

**Comment by converge** [comment]
@rjain15 I have a working example here https://github.com/converge/personal-website/blob/master/src/components/EmailForm/index.jsx

**Comment by rjain15** [comment]
thanks @converge. I am facing issues in handleReset, and I get an error . I have a form with name, email and comments (Comments form) and when I press cancel, I want to reset the form field. 

`                        <Button label="Cancel" 
                                className="secondary" 
                                disabled={!dirty || isSubmitting}                   
                                onClick={handleReset}/>
                        <Button type="submit" disabled={isSubmitting} primary label="Contact Us" />`

Error : 
`Uncaught TypeError: Cannot read property 'name' of undefined
    at eval (Contact.js:135)
    at Formik.render (formik.esm.js:763)
    at finishClassComponent (react-dom.development.js:14706)
    at updateClassComponent (react-dom.development.js:14661)
    at beginWork (react-dom.development.js:15609)
    at performUnitOfWork (react-dom.development.js:19277)
    at workLoop (react-dom.development.js:19317)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)`

**Comment by sizzle01** [comment]
> Thanks!
> 
> The error appear, because on first render, the `status` is `undefined`, so, the `success` prop doesnt exists.
> 
> I fixed it just doing a ternary: `Success message here: {x.status ? x.status.success : ''}`

hi, what does x represent in this case please

**Comment by converge** [comment]
> > Thanks!
> > The error appear, because on first render, the `status` is `undefined`, so, the `success` prop doesnt exists.
> > I fixed it just doing a ternary: `Success message here: {x.status ? x.status.success : ''}`
> 
> hi, what does x represent in this case please

Hi, I updated the link, it will be more clear now: https://github.com/converge/personal-website/blob/05fabfee1286fa95ecde111ad260464b3a1e8604/src/components/EmailForm/index.jsx
