### ISSUE TITLE
No exported member 'FormikActions'

### ISSUE THREAD

**Issue by j055** [jaredpalmer/formik#1226]
### Current Behavior

TS2305: Module '"../node_modules/formik/dist/formik.esm"' has no exported member 'FormikActions'.

### Expected behavior

clean build

### Reproducible example

Create a .tsx file , enter

```
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { Formik, Field, Form, FormikActions } from 'formik';

ReactDOM.render(
	<h1>Test</h1>,
	document.getElementById('root')
);
```

Build with webpack using 'ts-loader'

### Suggested solution(s)

Please fix

### Additional context

building with webpack v4.28.3

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.4.2
| React            | 16.7.0
| TypeScript       | 3.2.2
| Browser          | any
| npm/Yarn         | 6.4.1 / n/a
| Operating System | Windows 10

**Comment by shubh54** [comment]
I am unable to find FormikActions anywhere within api reference of Formik.

Can you refer to latest api reference and how did you come across FormikActions. You can refer to below file for components that are being exported.

https://github.com/jaredpalmer/formik/blob/master/src/index.tsx

**Comment by jaredpalmer** [comment]
As of 1.4.3, this gets inferred. In the future it will be renamed `FormikHelpers`.

**Comment by jaredpalmer** [comment]
It's here btw: https://github.com/jaredpalmer/formik/blob/master/src/types.tsx#L68
