### ISSUE TITLE
Textarea does not render as a textarea

### ISSUE THREAD

**Issue by aikidoshi** [jaredpalmer/formik#1237]
### Current Behavior

If I try to use a Field of type textarea it renders as a plain single line input object, ignoring rows and no drag handle.

### Expected behavior

Textarea fields should be rendered as multiline textarea field with drag handle

### Reproducible example

Use the formik sandbox (https://codesandbox.io/s/zKrK5YLDZ) and change the email field to type textarea.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.2.0
| React            |16.5
| TypeScript       |None
| Browser          |Chrome
| npm/Yarn         |5.6
| Operating System |Windows 10

**Comment by tbarho** [comment]
Do you have an example of using textarea in a custom component, rather than the component string literal?

**Comment by jtart** [comment]
@tbarho `<Field component={() => <textarea placeholder="Some placeholder">{values.someValue}</textarea>}>`

**Comment by tbarho** [comment]
@jtart @jaredpalmer There is still a bug with this, so it might want to be reopened, reproduced here:  https://codesandbox.io/s/vmq5pxj0ry (open the console before you try)

If you hit enter in the text area, 2 errors are thrown:
```
Assertion failed: Input argument is not an HTMLInputElement
getFormProfile @ onloadwff.js:71
setFieldValue @ onloadwff.js:71
formKeydownListener @ onloadwff.js:71

onloadwff.js:71 Uncaught TypeError: Cannot read property 'type' of undefined
    at e.setFieldValue (onloadwff.js:71)
    at HTMLFormElement.formKeydownListener (onloadwff.js:71)
```

I'm just getting started with Formik, so I might be a little noob to patch that.

**Comment by rarira** [comment]
> onloadwff.js

are you using lastpass chrome extension?
if you are, please refer to https://github.com/KillerCodeMonkey/ngx-quill/issues/351

I had same errors but the link helps..

**Comment by tbarho** [comment]
Yeah, definitely that.  Thanks!

**Comment by hamidra** [comment]
This worked for me. set the component to "textarea" and you can define the number of rows using rows attribute

<Field
                name="messageText"
                component="textarea"
                placeholder="Type a message"
                rows="2"
              />

**Comment by hamidra** [comment]
This worked for me. set the component to "textarea" and you can define the number of rows using rows attribute

```
<Field
                name="messageText"
                component="textarea"
                className="form-control"
                placeholder="Type a message"
                rows="2"
              />
```

**Comment by vijaysadhu2016** [comment]
> This worked for me. set the component to "textarea" and you can define the number of rows using rows attribute
> 
> ```
> <Field
>                 name="messageText"
>                 component="textarea"
>                 rows="2"
>               />
> ```

Thanks!!!

**Comment by d0x1n** [comment]
> `<Field component=“textarea” />`

this works. 👍

**Comment by NeoCortexFr** [comment]
I got same problem.
`<Field component=“textarea” />` works !
Thanks a lot
