### ISSUE TITLE
Augmenting formik bag with custom props

### ISSUE THREAD

**Issue by ericbiewener** [jaredpalmer/formik#1239]
We are augmenting the standard formik bag props with some additional ones. For example, we have a `mergeStatus` function that ensures our use of the [`status`](https://jaredpalmer.com/formik/docs/api/formik#status-any) property conforms to the data structure our team has agreed upon.

We accomplish this prop augmentation with our own context provider that we then render inside the `<Formik>` render method:

```js
<Formik
  ...
  render={(form: FormikPropsT<V>) => {
    const enhancedFormProps = {
      ...form,
      mergeStatus: (status: FormikStatusT) => customMergeStatus(form, status),
    };

    return (
      <CustomFormikContext.Provider value={enhancedFormProps}>
```

Then, in order to gain access to these augmented props, we can't rely on the `form` prop provided via `<Field>`'s render function. Instead, we have to wrap `<Field>` in our`<EnhancedFormikConsumer>`:

```js
<EnhancedFormikConsumer>
  {form => (
    <FieldCmp
      {...props}
      validate={validate}
      render={({ field }: FieldPropsT<V, F>) => {
```

This all works fine. But it feels like a pretty significant change to how we're accessing formik props. And if Formik were to start providing _different_ props in the formik bag on a per-field basis, our enhanced props would not have access to those (although we could still access them via the currently unused `form` prop in the <Field> render method). My sense is that this will not happen; the division of `<Field>`'s render props into `field` and `form` indicate a commitment to preserving non-field-specific props under the `form` namespace. But speculating about intent is not the same as depending on concrete documentation :)

I guess I'm wondering if anyone else has done things like this, and whether the Formik maintainers feel that this is a safe way to use the library.

**Comment by jaredpalmer** [comment]
My suggestion here would be to write your own custom `<Fieldset>` using  `connect()`, put your enhancements onto another React context, and then also pass those into your custom `<Fieldset>`.

**Comment by ericbiewener** [comment]
Yeah, that sounds like the right approach. Thanks!
