### ISSUE TITLE
Best way to implement a custom onChange that behaves like a <input />

### ISSUE THREAD

**Issue by sebastiandeutsch** [jaredpalmer/formik#1243]
## ❓Question

I'm building a custom Input component - I'd like to create a onChange handler which should behave similar to `<input onChange={...} />`.  I've seen that it's recommended to use `setFieldValue` but then the component names are leaking into the setFieldValue callbacks. What would be the best way to satisfy the onChange interface? I've managed to successful mimic the interface like this:

```
const event = {
  persist: () => {},
  target: {
    type: "change",
    id: this.props.id,
    name: this.props.name,
    value: value
  }
};

this.props.onChange(event);
```

Another idea would be to create a SyntheticEvent (but I don't now how to create one - Facebooks documentation is a bit sparse on that issue). What's the best way to archive the desired behaviour when you want to avoid using `setFieldValue`. You can also say: Don't do this there will be dragons :-)

**Comment by jaredpalmer** [comment]
My suggestion is to make 2 components. One that is your vanilla base input with styles etc, and one that hooks into Formik via <Field> or connect(). This way you can get rid of Formik without rewriting every form in your app.

**Comment by sebastiandeutsch** [comment]
Thanks for the answer. But it mimicking the event as described ok? Then I could live with just one component.

**Comment by jaredpalmer** [comment]
I think you should use setFieldValue. That's what it is meant for.

**Comment by techieshark** [comment]
Thanks for the question & advice above ^.

In case anyone needs an example of using this, here's my code which connects a custom component's event handler (onDayChange) to `setFieldValue`:

```
// @flow
import React from 'react';
import { connect } from 'formik';

import { InlineDatePicker } from '../../DatePicker';

type FormikProps = {
  setFieldValue: Function,
  // … and a bunch of other props not mentioned here.
}

type Props = {
  /** Field name. Also used in setting form state */
  name: string,
  /** formik render props passed via Context API and retrieved via Formik's `connect`. */
  formik: FormikProps,
}

class FormikDatePicker extends React.PureComponent<Props> {
  handleChange = (date: Date) => {
    const { name, formik: { setFieldValue } } = this.props;
    setFieldValue(name, date);
  }

  render() {
    return (
      <InlineDatePicker onDayChange={this.handleChange} />
    );
  }
}

export default connect(FormikDatePicker);

```

**Comment by JonathanTR** [comment]
I'm experimenting with Formik in the hope that I can eventually replace ReduxForm with it. For now, I'm using an adapter around existing inputs to try and mimic the api passed into redux-form inputs:

```
import React from "react";
import get from "lodash/get";

export const formikAdapter = ({ field, form, ...props }) => ({
  ...props,
  name: field.name,
  input: {
    ...field,
    onChange: (value) => form.setFieldValue(field.name, value)
  },
  meta: {
    touched: get(form.touched, field.name, false),
    dirty: form.dirty,
    error: get(form.errors, field.name, ""),
    valid: form.isValid,
    submitting: form.isSubmitting
  }
})

export const asFormik = (Input) => (props) => 
  <Input {...formikAdapter(props)} />
```

**Comment by luky1984** [comment]
@techieshark 

Note that you can use decorator connect not export default, in case you like named exports

```
import { connect } from 'formik';

@(connect as any)
export class FormikDatePicker extends React.PureComponent<Props> {
```

**Comment by ktmud** [comment]
For those to use `FieldProps` and general form control components, here's one way to allow your custom component to use `fieldProps` directly.

```ts
/**
 * Allow input component's `onChange` event to pass values directly.
 */
const adaptChangeHandler =
  (onChange: ChangeEventHandler<any>, targetProps: { name: string }) =>
  (e: any, eventType?: string) => {
    if (e && 'nativeEvent' in e) {
      onChange(e);
    } else {
      onChange({
        type: eventType || 'change',
        target: {
          ...targetProps,
          value: e,
        },
      } as unknown as ChangeEvent);
    }
  };


<Field name={name} validate={validate}>
  {({ field: { onChange, ...field }, form }) => (
    <FormControl
      isInvalid={Boolean(form.errors[name] && form.touched[name])}
      isRequired={isRequired}
      key={name}
    >
      <ControlComponent
        onChange={adaptChangeHandler(onChange, {
          name,
        })}
        {...props}
        {...field}
      />
    </FormControl>
  )}
</Field>
```

**Comment by moeinrahimi** [comment]
in my scenario I am using material-tailwind and it's component does not implement default onChange behavior so I used formik's setValues method to set values manually
