### ISSUE TITLE
Unable to set initial errors in formik form

### ISSUE THREAD

**Issue by vijayadurga259** [jaredpalmer/formik#1247]
Hello

How to set initial errors in formik?

Tried below workaround to set it in componentDidMount but didn't work. Even after setting errors in componentDidMount getting errors as empty object in formik props.

```
componentDidMount() {
        if (this.props.savedOperationInputs && !_.isEmpty(this.props.savedOperationInputs.errors) && this.form) {
            this.form.setErrors(this.props.savedOperationInputs.errors);
            this.form.setTouched(this.props.savedOperationInputs.touched);
        }
}

```
Can someone help me to solve this issue?

**Comment by jaredpalmer** [comment]
Hi there! This is in progress #1263. As this is a duplicate, going to close for now.
