### ISSUE TITLE
Validation before setting value to formik state

### ISSUE THREAD

**Issue by boonlai** [jaredpalmer/formik#1248]
## ❓Question

Hi, I am new to formik. I notice that the handleChange function set the value to formik state first. Then, it validation the value, and put error message to the error state if invalid.

I want to ask is it possible to validate the value first. If the validation return false, then don't set the value to value state? Thanks!

**Comment by jaredpalmer** [comment]
You could do this with a custom input that uses it's own handleChange instead of Formik's.

**Comment by jaredpalmer** [comment]
As I am writing out the way to do it, I am going to stop myself as I would highly advise against this because you will be blocking the UI changes of the input during validation which is very very very bad UX.
