### ISSUE TITLE
onSubmit on React Native

### ISSUE THREAD

**Issue by rayhk6** [jaredpalmer/formik#1252]
I tried to pass values to another function by setting onsubmit to something like below. However, it keeps passing the initial values instead of values after setFieldValue.

```
<Formik
                ref={node => this.form = node}
                initialValues={initialValue}
                onSubmit={this.validation}
            >
{({ handleChange, handleSubmit, values, setFieldValue }) =>
....
}
            </Formik>

```

` validation(values, action) {
console.log(values
}
`

**Comment by jaredpalmer** [comment]
Can you share a reproducible example on snack.expo.io and fill out the rest of the issue template? In the meantime, going to close this.
