### ISSUE TITLE
tests with connected components and redux

### ISSUE THREAD

**Issue by henriqueweiand** [jaredpalmer/formik#1262]
## ❓Question

I'm trying to run tests with component connected to redux and formik. I've been testing several ways to get the result of getting submitted and checking in the state if there was indeed the addition, but all attempts were invalid ... Could anyone give me a try on redux test?

projetct: https://github.com/henriqueweiand/reactjs-crud-state-test/blob/master/src/pages/__tests__/formDocumentos.test.js

**Comment by jaredpalmer** [comment]
See #937 . Enzyme's event's are synchronous but Formik's submission is async, which means you cannot test it the way you have.

**Comment by jaredpalmer** [comment]
See #1254
