### ISSUE TITLE
Make FieldProps available for import

### ISSUE THREAD

**Issue by lucasriondel** [jaredpalmer/formik#1266]
### Current Behavior

We cannot import the FieldProps interface https://github.com/jaredpalmer/formik/blob/master/src/Field.tsx#L31

### Desired Behavior

Be able to import it

### Suggested Solution

Set it in the d.ts file

### Who does this impact? Who is this for?

TypeScript users

**Comment by jaredpalmer** [comment]
All of `Field` is exported here: https://github.com/jaredpalmer/formik/blob/master/src/index.tsx#L2

Can you create a reproducible example?

**Comment by lucasriondel** [comment]
My bad, it was a mistake. Thanks for your answer.
