### ISSUE TITLE
React-select's validation triggered in unexpected moments

### ISSUE THREAD

**Issue by virzen** [jaredpalmer/formik#127]
Hi!

I'm trying to use Formik with react-select and I've come across an issue: validation is triggered too early. After selecting a value, though proper field is set in `values`, error is present too. It disappears after blurring another field, which isn't exactly what I expect. 

I was looking for a solution and came across [react-select example](https://codesandbox.io/s/jRzE53pqR) but, sadly, it experiences [similar behaviour](http://take.ms/HJjJG).

Is there solution to this problem, or at least some workaround?

**Comment by jaredpalmer** [comment]
@virzen hey sorry about that, I was playing with this when working out logic for #123 . I put it back...

https://codesandbox.io/s/jRzE53pqR
