### ISSUE TITLE
i want from onChange React-Select in Formik change state component 

### ISSUE THREAD

**Issue by armohammadi56** [jaredpalmer/formik#1272]
onChange={value => {
                            setFieldValue("personTypeId", value.id);
                            if (value.id === 1) {
                              this.setState.isDisableFullTimeType = false;
                            } else {
                              this.setState.isDisableFullTimeType = true;
                            }
                            
                          }}

**Comment by jaredpalmer** [comment]
I'm going to mark this as invalid and close for now. If you can fill out the issue template next time, that would allow us to help you out.

**Comment by armohammadi56** [comment]
tnx :-)
