### ISSUE TITLE
write unit test cases for data validation done with ajv

### ISSUE THREAD

**Issue by MeenalYengul** [jaredpalmer/formik#1275]
Hello,
I have a simple schema written in ajv. how to proceed to write a unit test cases for this data validation.
I tried to write a function where it is taking schema and data as a input and returning validation result. but in place of parameters of function i can see error as Parameter 'schema' implicitly has an 'any' type. I dont understand how to write a function and what to write in that function. and then how to write test case for that function. Please help. I am new bee .

**Comment by jaredpalmer** [comment]
Hi! Formik's `validate` prop takes a function ([full docs](https://jaredpalmer.com/formik/docs/api/formik#validate-values-values-formikerrors-values-promise-any)). I think the best place for this kind of question is the #formik channel of reactiflux.com. People will be able to help you out synchronously there.
