### ISSUE TITLE
setFieldError not working as expected.

### ISSUE THREAD

**Issue by prateek3255** [jaredpalmer/formik#1278]
### Current Behavior

Currently I want to validate a hostName URL using a function that I have and set errors accordingly.

here is the component on which I want to set the errors to -
```
<TextField
        name="github"
        value={values.github}
        onChange={event => handleLinkChange(event, 'github', 'github.com')}
        label="Please link your Github account"
        error={
          errors.github &&
          touched.github && {
            [errors.github]: true,
          }
        }
      />
```
and here is the handleLinkChange function that I use -
```
const handleLinkChange = ({ target: { value } }, name, hostName) => {
          setFieldValue(name, value);
          setFieldTouched(name, true);
          if (!isValidHostURL(hostName, value)) {
            console.log(name);
            setFieldError(name, `Enter a valid ${name} URL`);
          }
        };
```
the function is working fine as it should but the error is not being set accordingly.

### Expected behavior

The error should be set and shown in the field

### Additional context

I am also using Yup for form validation schema and have set github to Yup.string().required() in the Yup.object().shape({}) along with the other fields

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |  1.4.2
| React            |  16.6.3
| TypeScript       | -
| Browser          | chrome 69
| npm/Yarn         | npm 6.4.1
| Operating System | Windows 10 1709

**Comment by abdellah-el-mennani** [comment]
set the third argument of setFeildValue to false: ``` setFieldValue(name, value, false); ```

**Comment by muyiwaoyeniyi** [comment]
@prateek3255 Did @abdellah-el-mennani solution work? It doesn't seem to work for me.

**Comment by prateek3255** [comment]
@muyiwaoyeniyi the solution didn't work for me either.

**Comment by muyiwaoyeniyi** [comment]
ok. @prateek3255 Did you implement a workaround? I think this issue is also related to this - https://github.com/jaredpalmer/formik/issues/1111

**Comment by prateek3255** [comment]
@muyiwaoyeniyi my workaround was that I used two values for the same input, and set one of them to required in yup.
Then I linked my input's value to the dummy value and in the onChange function, and then I changed the original value only when the value is valid according to my validation function else set it to an empty string. The dummy value is always changed.
This is a temporary workaround because I want to fix that issue urgently, but it works fine as expected.

**Comment by muyiwaoyeniyi** [comment]
@prateek3255 got it. Thanks for the info.

**Comment by jaredpalmer** [comment]
setFieldError should not be used in change handlers because validation will not be aware of it during submission. The only real use case for setFieldError is inside of onSubmit where you want to manually set a field error. You should move this logic to validate instead.

**Comment by vaibhavhrt** [comment]
@jaredpalmer  what if on value change (or field blur) I want to immediately make an API call to check if value is valid and set error then, so that users can see errors and correct them before submitting form.
A common use case is to check if username is available in signup forms.

**Comment by nilamsavani** [comment]
@vaibhavhrt Did you find any solution to this? I want to achieve same thing you mentioned.

**Comment by vaibhavhrt** [comment]
@nilamsavani I implemented some workaround in my code, but can't remember what exactly.

**Comment by dagenius007** [comment]
@vaibhavhrt can we see the work around?

**Comment by Keyurkd** [comment]
@nilamsavani @dagenius007 
This works for me.

```
formik.setTouched({ username: true }, true);
formik.setErrors({ username: 'Enter a valid username' });
```

**Comment by sm3sher** [comment]
I had a use case where I solved it this way to remove any existing errors
```js
formik.setFieldValue("password", generateValidPassword(), false);
formik.setFieldError("password", "");
```

**Comment by eugeneborodkin2** [comment]
I need to show a manual field error **On Change of a dropdown** to a certain item. The following did not work. Also tried Keyurkud's suggestion above, didn't work either:
```
formik.setTouched({ username: true }, true);
formik.setErrors({ username: 'Enter a valid username' });
```
My code:
```
<Form.Control as="select"
                custom
                id="approverDropDown"
                name="processAction"
                value={values.processAction}
                onChange={e => {
                    // Call default Formik handleChange()
                    handleChange(e);
                    // If a specific item is selected, start condition check for custom error
                    if (parseInt(e.target.value) === 2) {
                        // Set Inactive Default 2nd Approver error if applicable
                        // This gets here, and the If is executed
                        if (inactiveDefaultSecondApprover) {
                            setFieldError('secondApproverId', 'Selected Approver is no longer eligible. Please choose a different Approver to continue.');
                        }
                    }
```
Note that `setFieldValue` and `setFieldTouched` do work, but `setFieldError` does not.
StackOverflow thread created: https://stackoverflow.com/questions/73013465/formik-manually-set-field-error-on-change-of-dropdown-depending-on-condition

**Comment by aliwaqar981** [comment]
Any solution for this?

**Comment by KnightRidder** [comment]
I found a workaround for this issue, I have used the `validate` callback function to throw an error.

` const validateForm = (formValues: FormikValues['values']) => {
    if (formValues[fieldName] > 100)) {
      return { [fieldName]: 'ErrorMessage' }
    }
    return {}
  }`

`
   <Formik
      validate={validateForm}
     ....
    >
`

official doc: https://formik.org/docs/api/formik#validate-values-values--formikerrorsvalues--promiseany

**Comment by SimonVillalonIT** [comment]
`const handleLinkChange = ({ target: { value } }, name, hostName) => {
          setFieldValue(name, value);
          setFieldTouched(name, true);
          if (!isValidHostURL(hostName, value)) {
            console.log(name);
            return setFieldError(name, `Enter a valid ${name} URL`);
          }
        `};

I added a return in setFieldError and its working fine

**Comment by steel809** [comment]
But it's a void function? Why does this make it work? I am trying to use setFieldError and it doesn't work - setFieldTouched works though. But its giving me error message of a different validation, instead of the error message I am trying to set with setFielError()

**Comment by aUlloaN** [comment]
In case my code helps someone
`formik v2.2.9`


My custom input:
```typescript
<InputDate
  label={birthdayInputLabel}
  errorMessage={formik.errors.birthday || ''}
  value={formik.values.birthday}
  onChange={formik.handleChange('birthday')}
  onStateChange={(state) => handleInputDateStateChange(state)}
/>
``` 

State handler:
```typescript
const handleInputDateStateChange = async (state: string) => {
  await formik.setFieldTouched('birthday', true, true);
  formik.setFieldError(
    'birthday',
    state === 'error' ? formatMessage(messages.errorMessageInvalidDate) : undefined,
  );
};
```
