### ISSUE TITLE
How to submit a dynamic array of objects via a formik form?

### ISSUE THREAD

**Issue by RichMatthews** [jaredpalmer/formik#1280]
I am struggling to use Formik for my use case. I have a form and when I click a button it will add another row to that form. I want to then submit the form and have all the data available to me as an array. I have almost got it working but I have an issue where the form isn't clearing properly.

this is my structure so far:

```
        <Formik
          initialValues={{name:'', sets: '', reps: '', weight: ''}}
          onSubmit={
            (values, {resetForm}) => (
              this.props.submitWorkout(Object.values(values)),
              this.setState({exercises: 0}),
              resetForm({})
            )
          }
          render={() => (
            <Form>
              <FieldArray
                render={() => (
                  <div>
                    {rows}
                  </div>
                )}
              />
              <button type="submit">Submit</button>
            </Form>
          )}
        />
```

but when I try and submit the data, on each subsequent submit it appends the previous data form with it. how can I properly clear the form?

**Comment by jaredpalmer** [comment]
Don’t pass anything to resetForm()

**Comment by RichMatthews** [comment]
this is still not clearing the form properly and previous data is being appended when I submit it 😞

**Comment by RichMatthews** [comment]
sorry I was being dumb with my redux state, consider this closed 👍
