### ISSUE TITLE
Form-level error not displayable in ErrorMessage component

### ISSUE THREAD

**Issue by SvetlinStaev** [jaredpalmer/formik#1286]
### Current Behavior
I have a form which has a few fields and I use the ErrorMessage component with the name of the field to attach error messages to it. It works great but there is a case when the whole form is invalid not based on a value of a single field but multiple and I would like to attach the error to a generic form-level error. I have use the key form to the errors object with `setErrors({ form: 'some message'}). When I use it directly with the errors object I can display that error on top of the form. I wanted to use the ErrorMessage component and gave it the "form" name as `<ErrorMessage name="form" />` but the error doesn't show. 

### Expected behavior
As it is a valid key in the errors object, even if not a valid field I expect to have the ErrorMessage component display that error similarly to the field-level errors.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.4.3`
| React            | 16.5.0 |
| TypeScript       |  X |
| Browser          | React Native |
| npm/Yarn         | 11 / 1.13 |
| Operating System | Mac OSX |

**Comment by jaredpalmer** [comment]
This should probably be handled with setStatus as as ErrorMessage will look for the key inside of touched as well errors.
