### ISSUE TITLE
How to pass values from a component into Formik multi-step form wizard?

### ISSUE THREAD

**Issue by adetoola** [jaredpalmer/formik#1295]
## ❓Question

As the title said.
I have a stateless component based on `react-bootstrap-typeahead`  and a form wizard using the formik example - https://github.com/jaredpalmer/formik/blob/master/examples/MultistepWizard.js.
However, I am unable to pass the values I got from the typeahead component into formik. I can't access setFieldValue .
```
const FormElements = setFieldValue => (
    <Wizard
      initialValues={FORM_VALUES}
      onSubmit={(values, actions) => {
        sleep(300).then(() => {
          window.alert(JSON.stringify(values, null, 2));
          actions.setSubmitting(false);
        });
      }}
    >
      <Wizard.Page>
        <GoogleMapsPlaceLookup
          value={location => {
            console.log("I got the value correctly from my child: ", location);
          }}
        />
      </Wizard.Page>
    </Wizard>
);

export default FormElements;
```

How do I inject this value into `Formik`, so it can be processed `onSubmit`. Any pointer or help will be appreciated.
Thanks

**Comment by jaredpalmer** [comment]
Answered on StackOverflow. 
https://stackoverflow.com/a/54517336
