### ISSUE TITLE
v2.0.0-gamma.1: You should not use <Field component> and <Field render> in the same <Field> component

### ISSUE THREAD

**Issue by gustavopch** [jaredpalmer/formik#1296]
### Current Behavior
Receiving the following warning when using the `render` prop.
```
Warning: You should not use <Field component> and <Field render> in the same <Field> component; <Field component> will be ignored.
```
Because `component` has a default value defined at Field.tsx:144, when you pass a value to `render`, both `component` and `render` are defined. Current implementation doesn't want both properties to be defined at the same time. That triggers the warning.

### Expected behavior
No warning.

### Reproducible example
https://codesandbox.io/s/752qnz8mj

### Suggested solution(s)
Maybe change this at Field.tsx:144?
```diff
-     component = 'input',
+     component = this.props.render || this.props.children ? undefined : 'input',
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |2.0.0-gamma.1
| React            |16.7.0-alpha.0
| Browser          | Chrome 71

**Comment by zaguiini** [comment]
Same here: ```Warning: You should not use <Field render> and <Field children> in the same <Field> component; <Field children> will be ignored```

Strange thing is that I'm using `component` instead of `render` 🤔

**Comment by gustavopch** [comment]
@zaguiini I think my original post fully describes the cause and the solution.

**Comment by gustavopch** [comment]
@jaredpalmer Does v2.0.1-alpha.2 close this issue?

**Comment by Cooryd** [comment]
Looks like it does. Just upgraded to `2.0.1-rc.4` and warnings are gone.
