### ISSUE TITLE
Submitting form on modal trigger both validation on modal and on page

### ISSUE THREAD

**Issue by ducdev** [jaredpalmer/formik#1297]
## ❓Question
Not sure if this is Formik bug or my implementing issue, but please have a look at this recorded loom.
https://www.useloom.com/share/7cab71cf913f4baab75671e8cd084cc0

**Comment by jaredpalmer** [comment]
See #1308. Make sure that your modal button is not of type=“submit” which will trigger validation because it is a submit attempt.

**Comment by jaredpalmer** [comment]
Same suggestion from #13008 applies to this as well:

https://github.com/jaredpalmer/formik/issues/1308#issuecomment-461029656

**Comment by ducdev** [comment]
@jaredpalmer Hey, it's not a nested form, it's separated form on `reactstrap` modal. I removed `type="submit"` and issue still occurs.

**Comment by jaredpalmer** [comment]
Can you create a codesandbox to reproduce this? It’s hard to guess what’s going on.

**Comment by ducdev** [comment]
Hello, after reproducing the issue, I found out it's a nested modal inside form. It was passed in a prop of `react-select/CreatableSelect`.

**Comment by alexandreservian** [comment]
Hello guys, I'm having the same problem quoted by @ducdev:

> Hey, it's not a nested form, it's separated form on reactstrap modal. I removed type="submit" and issue still occurs.

@jaredpalmer I created a codesandbox for this problem:
[https://codesandbox.io/s/modal-within-formik-nw6ev](https://codesandbox.io/s/modal-within-formik-nw6ev)

@jaredpalmer enter the modal, and submit without saving any data, you will find that the first form has been validated. Even the modal form being rederized out of the main form.

**Comment by palodelincak** [comment]
I'm experiencing this issue as well. Once I removed `type="submit"` from button it helped. But that's not a solution... Can we reopen this issue please?
