### ISSUE TITLE
Using setFieldValue in componentDidUpdate

### ISSUE THREAD

**Issue by Taerarenai** [jaredpalmer/formik#1301]
## ❓Question

Can you use ``setFieldValue`` outside of the Formik render? Let's say i need it in my componentDidMount or before my submit goes off, i tried ``this.props.setFieldValue``, i even tried passing ``setFieldValue`` as a param on the onSubmit prop of Formik, nothing works.

Example https://codesandbox.io/s/8n8j3358z9

**Comment by jaredpalmer** [comment]
No you cannot use formik methods above formik’s scope. You can create a component though that renders null but uses a lifecycle hook like componentDidMount to call Formik methods and then render it a child underneath the Formik parent component.
