### ISSUE TITLE
Submitting a form after 1.4.0 does not trigger Formik onSubmit

### ISSUE THREAD

**Issue by jwallet** [jaredpalmer/formik#1302]
### Current Behavior

After updating v1.3.2 to 1.4.0 I'm not able to submit the form anymore.
> touched not working when using validateOnBlur (related to cancelling validation promises ?)
- We use validateOnBlur and validateOnChange (default / true), so it touches all fields.
- We wanted to make sure no error message will appear if the user did not submit the form at least once, so - we added `!!error && touched` as a condition for displaying the message. This method used to work properly in 1.3.2 but since the new release 1.4.X the validation does work but after touching the field i guess it goes back to untouched. See codesandbox.
> shema with required fields does not work if the property is not mention in the object initalValues (related to `Values` being the type instead of `object` ?)
- We do not want to provide the complete object properties of the form to initialValues, so the object will be incomplete sometimes and having this object incomplete make the schema fails on required properties.
- Formik won't touched all fields on form submit if they were not touched manually and if all properties were not set in the initialvalues
> set all fields touched to false does not stay in the formik bag
- we tried to set all fields touched on mount to false, but the formik bag reset it on every submission.

### Expected behavior

It looks like `validateOnBlur` reset the touched fields. I 'm able to submit the form like on 1.3.2 if I disable `validateOnBlur` the form completly

### Reproducible example

https://codesandbox.io/s/13645x66k3

### Suggested solution(s)

maybe getting a console.error when a validation is cancelled will be a good help for devs to know where the error comes from.

### Additional context

i'm using a date-picker and react-select in the form
i'm not using typescript but prop-types only

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.4.0
| React            | 16.7.0
| React dom | 16.5.0
| React select | 2.1.2
| React dates | 18.3.1
| PropTypes | 15.6.2
| Browser          | chrome
| npm/Yarn         | yarn
| Operating System | win 10

**Comment by jaredpalmer** [comment]
Hey! Thanks for putting together that sandbox. It looks like your Yup schema on `name5b` has a `Yup.number()` which will always fail unless you transform the input value into a number manually. This is because Formik mimics React and stores inputs as string out of the box. Once I changed that, onSubmit definitely works 

**Link**

https://codesandbox.io/s/30ky2zqx25

**Screenshot**

<img width="700" alt="screenshot 2019-02-05 11 07 58" src="https://user-images.githubusercontent.com/4060187/52286511-51459c00-2936-11e9-9b47-d9a5038d85b3.png">


TBH I'm still not sure I am properly understanding the issue though. Instead of using "*EDIT* ..." for updates, would you be synthesize this and write it again from the start? Or as a comment? Thanks.

**Comment by jwallet** [comment]
I know actually I don't know why I paste the codesandbox here since it does not show the same error that I get, I will try to fix the error on my side and come back with a proper issue, but you should consider console logging a warning when you cancel a validation to let us know why the form is not submitting since 1.4.X

**Comment by jwallet** [comment]
I updated my codesandbox and my first post with newest detail of the issue

**Comment by jwallet** [comment]
found it
to make sure that every fields were touched during submission of the form we had to touched the field because formik was not using the schema right for required properties that were missing from `Values` so we had this code for our custom Field component
```
if (!this.touched && this.props.form.isValidating) {
      this.props.form.setFieldTouched(this.props.field.name, true);
    }
```
because the third parameter was not set to false, it was sending another validation request. so I guess your minor version was in a way a major version

**Comment by jaredpalmer** [comment]
Correct. You should initialIze all of your values in initialValues.

**Comment by usama-asfar** [comment]
if you want your user to trigger the submit without filling some field, yup validation schema on that field should be only Yup.string()

**Comment by sarink** [comment]
I got here because I was using `<Field validate={...}>` on a field which was meant to be optional, and I forgot to handle the empty case (which should return `undefined`, and therefore be valid)
