### ISSUE TITLE
Calculated values

### ISSUE THREAD

**Issue by AlessandroAnnini** [jaredpalmer/formik#1312]
## ❓Question

If you have to programmatically calculate/recalculate a field value when other field values changes, what would be the best way? Where to add the code?

*example*: price + units => total 
(total should still be editable)

**Comment by jaredpalmer** [comment]
If total is editable, then it is not calculated... 

Perhaps by editable you meant dynamic. My suggestion is to actually not keep total inside your form state. The reasoning is that you should never keep computed values in React state. You should just calculate them where you need to (in render and before you submit). If you really want to go perf crazy you could memoize the calculation.

**Comment by jaredpalmer** [comment]
Avoiding storing computable values in state is a core precept of the React one-way data flow model. It’s explained here in probably my favorite blog post of all time “Thinking in React” 
https://reactjs.org/docs/thinking-in-react.html#step-3-identify-the-minimal-but-complete-representation-of-ui-state

**Comment by sun2rise** [comment]
Thanks Jared, you're right, but unfortunately sometimes it happens to have the need to calculate some value but I could use an input out of formik for this and then simply read its value when I try to submit the data.

**Comment by pavanmehta91** [comment]
What could be the way if that field is editable but its initial value is dependent upon value I entered in some other field. For example, If I enter zipcode, city and state can be pre-filled but I want to keep it editable

**Comment by kimfucious** [comment]
Formik is awesome.  Thanks for making this piece of greatness open source!

I found this thread, while trying to solve a problem.

Let's say a form has two fields for a person's height:  heightMajor (e.g. m or ft) and heightMinor (e.g. cm or in).

I'd like to store the calculated value of hCm, which would be either `heightMajor + heightMinor` or `(heightMajor / 0.32808) + (heightMinor / 0.3937)`, the latter if converting to metric from imperial.

I tried handling this with the below, on submit, but that violates the controlled component, resulting in a warning, which I understand the reasoning of.

`Warning: A component is changing a controlled input of type text to be uncontrolled. Input elements should not switch from controlled to uncontrolled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components`

It seems that having a hidden field in the form would be ideal.  Additionally, it would make doing yup validations a tad easier.  

Having said all that, @jaredpalmer ?, what is the ideal/recommended way to get a calculated value into a Formik form for ultimate submission?

```javascript
      onSubmit={(values, actions) => {
        let heightCm, weightKg;
        if (values.units === "metric") {
          heightCm =
            parseInt(values.heightMajor) * 100 + parseInt(values.heightMinor);
          weightKg = parseFloat(values.weight);
        } else if (values.units === "imperial") {
          heightCm = values.heightMajor / 0.32808 + values.heightMinor / 0.3937;
          weightKg = parseFloat(values.weight) / 2.20462;
        }
        values.heightCm = heightCm;
        values.weightKg = weightKg;
        delete values.heightMajor;
        delete values.heightMinor;
        delete values.weight;
        setTimeout(() => {
          console.log(JSON.stringify(values, null, 2));
          actions.setSubmitting(false);
        }, 2000);```

**Comment by kimfucious** [comment]
I'm currently now thinking that using setFieldValue on the onChange param in the heightMajor and heightMinor Field(s), where the calculated value is supplied might be the right path, but I'm lost down a rabbit hole.

**Comment by Andreyco** [comment]
Instead of settings "computed" value I would compute whenever needed. When setting, you need to remember to sync values whenever you update one of its dependecies.

**Comment by kimfucious** [comment]
I wound up doing the below in each height field (each slightly different as to where `e.target.value` is used), where `calcHeightCm ` is an external function that returns a value based in the params given.

Admittedly, this isn't very elegant, so if there's a better way, I'd love to be enlightened.

Now to figure out the yup stuff, as this complicates things a bit on that front.

On a side note, I attempted to use `setFieldValue() ` on submit, but since it doesn't return anything, it's hard to work with there.  It would be great if `setFieldValue()` returned a promise, so that you could fire it off and wait for its return _**before**_ making an api call to save the form.

```javascript
<Field
  className="form-control"
  id="height-major"
  onChange={e => {
    setFieldValue("heightMajor", e.target.value);
    setFieldValue(
      "heightCm",
      calcHeightCm(
        e.target.value,
        values.heightMinor,
        values.units
      ),
      false
    );
  }}
  name="heightMajor"
  type="text"
/>
```

**Comment by brielov** [comment]
> If total is editable, then it is not calculated...
> 
> Perhaps by editable you meant dynamic. My suggestion is to actually not keep total inside your form state. The reasoning is that you should never keep computed values in React state. You should just calculate them where you need to (in render and before you submit). If you really want to go perf crazy you could memoize the calculation.

But what if total is just a suggestion? You can calculate the total but still let the user decide if that number is right or not. I'm currently struggling with something similar where I calculate a suggested amount of money based on some other fields, but my client wants to be able to adjust it if he wants to.

**Comment by YassineDM** [comment]
@kimfucious I actually have the same issue here: I am trying to get user height and weight and give them the ability to switch from imperial to metric system (a switch component actually helps transitioning from one measurement system to the other). By the way, my API only needs metric values...

I actually don't know how to handle the problem. The options I was thinking of were:
- To view this topic only as a formatting issue. This would mean keeping the metric value as the input value and then formatting/displaying with a simple calculation. I guess yup validations would be based on the metric value but validation messages would be awkward...
- To view this topic as linked inputs. This would mean - besides only rendering the right fields when switching systems - to keep both of the "same" fields in sync: each time one is changed (e.g. height in feet), the other is changed too (e.g. height in cm) with a simple calculation. Both metric and imperial values would be stored and would have separate validations...

My questions are: @jaredpalmer which option fit better with Formik's way and how to actually do it?

**Comment by tonestrike** [comment]
If you are using `useFormik`, you can add a `useEffect` hook to watch for changes on particular keys of the `formik.values` object.

```
const formik = useFormik({})

useEffect(() => {
    formik.setFieldValue('computedProperty', formik.values.propertyOne + formik.values.propertyTwo)
}, [formik.values.propertyOne, formik.values.propertyTwo])
```

I found this to be simpler than adding custom `onChange` handlers on several fields, especially when the computed values might require many unique form properties.

**Comment by ospfranco** [comment]
this seems like a basic use case, shame that it is not contemplated on the API, a formatter function prop would be all I need

**Comment by johnrom** [comment]
@ospfranco format prop will be available in Formik v3, so you could do something like:

```
const { field: priceField } = useField('price');
const { field: unitsField } = useField('units');

return <Field name="total" format={value => value || priceField.value * unitsField.value} />
```

The problem is, that value is never stored in state, therefore total would have to be an optional field in validation, and during your submit function you'd have to also check for `const total = values.total || (values.price * values.units);`.

**Comment by ospfranco** [comment]
my use case is simpler, I do not need a computed value, just switching between units (imperial vs. metric), thanks for the answer though, I will try to give @tonestrike answer a go, see if that works

**Comment by johnrom** [comment]
@belmirp this project hasn't been maintained in a while so I recommend looking elsewhere.

The useEffect version will work for array values if you're working with an existing project, but you probably want to run a deep equals check to make sure the update won't trigger a new effect / infinite loop.
