### ISSUE TITLE
Hooks with Formik

### ISSUE THREAD

**Issue by yuritoledo** [jaredpalmer/formik#1325]
## ❓Question

Any docs to use Formik with hooks?

Thx.

**Comment by carlosagsmendes** [comment]
Hi @yuritoledo, the gamma version or the current version?

**Comment by yuritoledo** [comment]
Anyone of that :D

**Comment by yuritoledo** [comment]
Hello! 
Anyone of them.

**Comment by jaredpalmer** [comment]
See #1063

**Comment by FezVrasta** [comment]
What's the status of the "gamma" branch? Is it usable in production?

**Comment by buzinas** [comment]
The question asked in this issue wasn't addressed after all.

> See #1063 

I read the entire pull request thread, including the hidden comments, the PR reviews etc, and I still don't know if there is any documentation or at least a simple example of how to use Formik gamma with hooks.

I'd love to try it out on some new forms I'm currently working on, and come with some feedback, but I have no clue how to use it at all.

**Comment by joserocha3** [comment]
@buzinas, the `hooks` branch has some documentation

[https://github.com/jaredpalmer/formik/blob/hooks/docs/api/useField.md](https://github.com/jaredpalmer/formik/blob/hooks/docs/api/useField.md)

**Comment by alex-shamshurin** [comment]
Hi guys, so it's not still clear. Is hooks version is ready for prod? Where is the roadmap for v2 branch?
