### ISSUE TITLE
HandleSubmit conflicts with google tag manager

### ISSUE THREAD

**Issue by Dozalex** [jaredpalmer/formik#1328]
### Current Behavior
Field value has node and app used google tag manager.
User click to handleSubmit -> app crashed (Uncaught DOMException: Blocked a frame with origin).
In my case value is:
```javascript
{
    label: <p>{'someLabel'}</p>,
    value: 'someValue',
    id: 'someId',
}
```

### Expected behavior
handleSubmit without errors

### Suggested solution
Solution for users while bug not fixed:

```javascript
handleSubmit = fields => e => {
    e.preventDefault();
    ...
};

...

<Formik
  initialValues={initialValues}
  validationSchema={validate(balance)}
  onSubmit={() => {}}
>
  {
    ({ errors, touched, isValid, values }) => (
      <Form onSubmit={this.handleSubmit(values)}>...</Form>
    )
  }
</Formik>
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.0
| React            | 16.4.0
| TypeScript       | -
| Browser          | Chrome 72.0.3626.96
| npm/Yarn         | yarn 1.12.3
| Operating System | macOS Mojave

**Comment by jaredpalmer** [comment]
That works really nicely actually. Formik's API is designed to be flexible enough to do just this.
