### ISSUE TITLE
Inconsistent path behaviour

### ISSUE THREAD

**Issue by Andreyco** [jaredpalmer/formik#1333]
### Current Behavior

Validation errors are not set consistently with `values` and `touched` when talking about shape of data. Thus, path resolving behaviour is not same and makes things complicated.

```js
setFieldTouched('field.0', true, true) // { field: [ true ] }
setFieldValue('field.0', 'value', true) // { field: [ 'value' ] }
setErrors({ 'field.0': 'Wrong!' }) // { 'field.0': 'Wrong!' }
```
Same applies to validations. Errors are set directly using React's `setState`.

### Expected behavior
```js
setErrors({ 'field.0': 'Wrong!' }) // { 'field': ['Wrong!'] }
```

### Reproducible example
https://codesandbox.io/s/w0o000q9lw

### Suggested solution(s)
Probably iterate over object props and use `setIn` to set `errors` object.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.0
| React            | 16.8

**Comment by jaredpalmer** [comment]
While I admit that this is awkward. I’m not sure it’s a bug. It is also not how react state works (although it would be lit if React supported this). Seems very very magical.

**Comment by Andreyco** [comment]
I agree with you, not a bug. However, since Formik understands dot paths at some places I would expect it to understand them at all places... Not sure, not sure...

**Comment by jaredpalmer** [comment]
I think if other libraries began to support this behavior, I would be fine with it. However, I've never seen it before. Going to close for now, but will mark as unsolved.

**Comment by Andreyco** [comment]
@jaredpalmer agree here. After all, this can be effectively achieved by returning validation errors formatted in desired form.
