### ISSUE TITLE
Can't resolve 'create-react-context' in 'node_modules\formik\dist'

### ISSUE THREAD

**Issue by markwoon** [jaredpalmer/formik#1337]
## 🐛 Bug report

I'm getting:

```
ERROR in ../node_modules/formik/dist/formik.esm.js
Module not found: Error: Can't resolve 'create-react-context' in 'node_modules\formik\dist'
```

This gets resolved if I add `create-react-context` as a dependency.  This shouldn't be necessary since I'm using React 16.8.2.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.0 |
| React            | 16.8.2 |
| TypeScript       |  |
| Browser          | NA |
| npm/Yarn         | yarn 1.13.0 |
| Operating System | windows |

**Comment by albannurkollari** [comment]
I too am having the same issue with almost the same enviroment variables, except in Linux.

**Comment by krisburke** [comment]
Just wanted to mention this is also discussed in #720.

**Comment by menix** [comment]
Got this one time to time when app run
```
/home/....../node_modules/formik/dist/connect.d.ts
(3,66): Cannot find module 'create-react-context'.
```

Formik 1.5.1, Typescript: 3.3.4000, React 16.8.5, Create React App on Ubuntu 18.04.2

**Comment by jaredpalmer** [comment]
Try 1.5.2?

**Comment by markwoon** [comment]
So far so good...  Closing.

**Comment by taygrave** [comment]
This is still a problem
