### ISSUE TITLE
Broken support for Map and Set

### ISSUE THREAD

**Issue by maxaggedon** [jaredpalmer/formik#1339]
### Current Behavior

I use a Map of Set objects in my form `values`, it was working as expected until I upgraded from 0.11 to 1.5.
I found out that `lodash.isEqual` was replaced with `react-fast-compare`, which does not support Maps or Sets (see [this issue](https://github.com/FormidableLabs/react-fast-compare/issues/36)).

### Expected behavior

Correct comparison of Map and Set structures

### Reproducible example

https://codesandbox.io/s/mqjl4qkxyp

### Suggested solution(s)

Go back to `lodash.isEqual` until `react-fast-compare` adds support ?
At least mark this change as breaking in the changelog.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.0
| React            | 16
| TypeScript       |
| Browser          | recent Chrome
| npm/Yarn         | 
| Operating System | macOS

**Comment by jaredpalmer** [comment]
Interesting, I'm 100% fine with not supporting Map and Set. `react-fast-compare` is much much faster for our use case in Formik, so perhaps worth noting this somewhere in the docs.

**Comment by maxaggedon** [comment]
I understand, I adapted my code anyway.

**Comment by tuomokar** [comment]
Could it be at least possible to allow Formik to be given an alternative equality check function with a prop so that we could choose to use something else than `react-fast-compare`? This would allow easy support for Map and Set for those who need it but keep `react-fast-compare` as the default.

I could do a PR about this if this is ok.

**Comment by chrisbolin** [comment]
react-fast-compare will likely add Map etc support in the next month. we are downstream of fast-deep-equal and they have a beta that supports Map etc: https://www.npmjs.com/package/fast-deep-equal/v/3.0.0-beta.1

**Comment by chrisbolin** [comment]
Formik is an ES6 codebase, correct? (I looks like it here: https://github.com/jaredpalmer/formik/blob/67f8369e6ffdc1f330cdf49317f214538655234b/src/utils.ts#L151)

we are considering making v3 of react-fast-compare ES6+ only, but I don't think that'd be a problem for yall. we'd add Map, WeakMap, etc, but would require those globals to exist.

**Comment by ryan-roemer** [comment]
https://github.com/FormidableLabs/react-fast-compare has landed support for `Map`, `Set` and `ArrayBuffer` in `master` and will publish soon.

We don't have `WeakMap` yet, but are tracking at https://github.com/FormidableLabs/react-fast-compare/issues/36

**Comment by ryan-roemer** [comment]
Ah, just checked on `WeakMap` and unlike `Map` and `Set` it's not iterable, so I don't think we can add support to `react-fast-compare` unless someone else here has some ideas?

**Comment by chrisbolin** [comment]
@jaredpalmer we've released a beta of `react-fast-compare` https://www.npmjs.com/package/react-fast-compare/v/3.0.0-beta.1.

I've cloned `formik` locally and upgraded to it and just the test suite. Anything you want to try out before we release?
