### ISSUE TITLE
<ErrorMessage /> attempts to render an object

### ISSUE THREAD

**Issue by qw-in** [jaredpalmer/formik#1341]
### Current Behavior
If there is a nested error within what `<ErrorMessage />` is attached to it will attempt to render an object

### Expected behavior
If there is a nested error within what `<ErrorMessage />` is attached to it will render `null`

### Reproducible example
https://codesandbox.io/s/8x7vpl20lj

### Suggested solution(s)

quick `typeof === 'string'` check

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | `1.5.1`
| React            | `16.8.2`
| TypeScript       |
| Browser          | 
| npm/Yarn         |
| Operating System |

**Comment by Andreyco** [comment]
Easy help here, you need to convert it into something React can render. Iterate over them, and render. See corrected example https://codesandbox.io/s/mo8n0jrzy8

**Comment by qw-in** [comment]
@andreyco thanks for the example. I more meant in the case where you aren't using a render prop. Just seems like it could be confusing considering <ErrorMessage /> is sold in the docs as the easy safe alternative to using the `form.errors` object.

For me the render prop was typed as a `string` in TS so assumed it was not intended

**Comment by Andreyco** [comment]
@qw-in imo, API is good. As long as error is string, it is easy to decide what to render. All other cases should be handler by dev. If `error` is marked as string all the time, then TS type should be corrected.
