### ISSUE TITLE
Calling setFieldValue should only clone the nested value, and its ancestors

### ISSUE THREAD

**Issue by kevhiggins** [jaredpalmer/formik#1355]
### Current Behavior

Calling setFieldValue deep clones all nested values for the given path on the form.
```
const values = {
  a: {
    b: 'target-value',
    c: 'unrelated to impacted value'
  }
}
form.setFieldValue('a.b', 'new value");
```

### Expected behavior

Calling setFieldValue should only clone the nested value, and its direct ancestors. I wouldn't expect value c in the example above to be cloned, just shallow copied.

### Suggested solution(s)

Changing the [setIn](https://github.com/jaredpalmer/formik/blob/1f9cd8e0941057d4faa52062bf1fe7e7d2d81698/src/utils.ts#L38) function to use something like https://github.com/mariocasciaro/object-path-immutable (not an endorsement, just an example) would prevent touching values unrelated to the change.

### Additional context

I was hoping to use PureComponent, reselect and memoization in some of the child components I am using with Formik. When a component depends on a value from another field, its memory reference gets changed whenever any field's value is updated. As it stands I'll have to do a deep compare to allow memoization to work properly.

I was hoping to get a better understanding on if this cloneDeep had to happen, or if it was something that could be changed. I'd be happy to make a PR if it's something that could be adjusted. I'm also aware, that I might just be missing why doing the cloneDeep is important.

**Comment by mattleonowicz** [comment]
I also have problems with the way it works currently. Because of this behaviour, **maintaining forms with a lot of nested states is quite hard**. In nested structures, I often have to use setFieldValue, and guard other components (which needlessly rerender) with shouldComponentUpdate with deep comparison)

Fixing this would allow to guard against unnecessary rerenders out of the box (because of React's Pure components which compare props shallowly).

**Comment by danifus** [comment]
https://github.com/jaredpalmer/formik/pull/1235 should address this. Waiting on some feedback about whether it could have any unwanted side effects. It provided a significant performance boost and simplified my shouldComponentUpdate code as I could just compare object memory locations to check if the object (or any nested object) had been changed.

**Comment by kevhiggins** [comment]
@danifus Awesome! Hopefully, it gets merged. That would solve my issue as well.

**Comment by kevhiggins** [comment]
Closing. This is resolved by https://github.com/jaredpalmer/formik/pull/1235
