### ISSUE TITLE
How to set a datePicker value using antd with formik?

### ISSUE THREAD

**Issue by laxmikamala** [jaredpalmer/formik#1358]
## ❓Question

Seriously, for immediate help, just ask your question on the #formik channel on [Reactiflux](https://discordapp.com/invite/MbKwYuq).
my sample working codebox link [https://codesandbox.io/s/j3pv3xkv1w](url)

**Comment by shubh54** [comment]
Already answered on [stackoverflow](https://stackoverflow.com/questions/54920833/how-to-reset-antd-datepicker-after-submiting-a-value/54926091#54926091).

**Comment by Andreyco** [comment]
@shubh54 is correct here...

**Comment by webuti** [comment]
`     <Formik
        onSubmit={(values) => alert(JSON.stringify(values))}
        initialValues={{
          date: new Date(),
          title: this.props.title,
        }}
      >
        {({
          handleChange,
          handleBlur,
          setFieldValue,
          handleSubmit,
          values,
        }) => (
          <View>
            <Text>Son kullanma tarihine kaç gün var</Text>

            <DateTimePicker
              testID="dateTimePicker"
              timeZoneOffsetInMinutes={0}
              value={values.date}
              is24Hour={true}
              display="default"
              onChange={(date, dateString) => setFieldValue("date", dateString)}
            />

            <Button onPress={handleSubmit} title="Kaydet" />
          </View>
        )}
      </Formik>`
