### ISSUE TITLE
Multiple Forms on the same page

### ISSUE THREAD

**Issue by tylergaugler16** [jaredpalmer/formik#1367]
## How to prevent strange behavior when having two formik components on the same page❓

I have a login and signup form on the same page. Both forms work totally fine in isolation. The main structure I have is this:
```
<SignupAndLoginWrapper>
  <LoginForm />
  <SignupForm />
</SignupAndLoginWrapper>
```

And this is an example of how one of my forms looks: 
```
<Form
          key="login-form"
          initialValues={{ email: "", password: "", test: "" }}
          onSubmit={(values, { setSubmitting }) => {
            this.handleLogin(values);
            setSubmitting(true);
          }}
        >
          {({ values, errors, touched, handleSubmit, handleChange }) => (
            <form onSubmit={handleSubmit} key="login-form-form" id="login-form">
              <div className="columns is-gapless is-centered">
                <div className="column is-10 ">
                  <Field
                    key="login.email"
                    name="email"
                    label="Email"
                    component={TextInput}
                    validate={isEmail}
                  />
                </div>
              </div>
              <div className="columns is-gapless is-centered">
                <div className="column is-10">
                  <Field
                    key="login.password"
                    name="password"
                    label="Password"
                    component={PasswordInput}
                    validate={required}
                  />
                </div>
              </div>
              <div className="columns is-gapless is-centered">
                <div className="column is-10">
                  <Field
                    key="login.test"
                    name="test"
                    label="Test"
                    component={PasswordInput}
                    validate={required}
                  />
                </div>
              </div>
              <div className="columns is-gapless is-centered">
                <div className="column is-10 ">
                  <button
                    className="button medium-button purple-button is-centered-block"
                    type="submit"
                  >
                    Submit
                  </button>
                </div>
              </div>
            </form>
          )}
        </Form>
```

What's happening is that my signup form works fine, but for my login form none of the inputs work. And when i use the react inspector, I notice that the signup fields are inside my Login component (when in my actual component they are not). 

When i do `display: none` on my signup form, the login form behaves normal btw. 

I've tried using keys on both forms to keep them distinct, but that hasnt worked. Any ideas?

**Comment by tylergaugler16** [comment]
Realizing my custom animations were leading the input fields to appear on top of each other and lead to this confusing behavior. Closing issue.

**Comment by edwinwong90** [comment]
@tylergaugler16 rules of form never nest them (<form>).

**Comment by philals** [comment]
Came here from a google.

I had two forms toggled by state on the same page. Giving them different `keys` solved my weird behavior.

**Comment by mateja176** [comment]
@philals What do you mean by?
> Giving them different keys solved my weird behavior.

**Comment by mateja176** [comment]
@philals Is there any documentation regard the `key prop`?

**Comment by philals** [comment]
@mateja176 Hi really sorry I tried looking for the code to remind myself - I even looked at my commits for that day...

I think I was referring to React's standard key prop. https://reactjs.org/docs/lists-and-keys.html

I have a feeling adding this to the Formik component allows it to have two forms on the same page. 

If anyone is able to confirm my memory that would be great.

**Comment by mateja176** [comment]
> @mateja176 Hi really sorry I tried looking for the code to remind myself - I even looked at my commits for that day...
> 
> I think I was referring to React's standard key prop. https://reactjs.org/docs/lists-and-keys.html
> 
> I have a feeling adding this to the Formik component allows it to have two forms on the same page.
> 
> If anyone is able to confirm my memory that would be great.

I'd be inclined to agree if the prop types of `Form` didn't explicitly contain a key prop. There may be more to it, since the `key` prop is usually managed by React. Nevertheless, this might be a red herring.

**Comment by Cristyander** [comment]
You can submit your information on onClick from your submit button. onClick = {() => console.log (values)}

**Comment by dev-bhuptani** [comment]
> @mateja176 Hi really sorry I tried looking for the code to remind myself - I even looked at my commits for that day...
> 
> I think I was referring to React's standard key prop. https://reactjs.org/docs/lists-and-keys.html
> 
> I have a feeling adding this to the Formik component allows it to have two forms on the same page.
> 
> If anyone is able to confirm my memory that would be great.

Thanks, it helped! I'm able to have two different Formik components on the same page by adding key property. But, I'm curious whether this is a correct approach or not. Can someone fill me on why adding key property it works?

**Comment by pdhankhar61** [comment]
The new react hook useId() might help for keys.
