### ISSUE TITLE
[Next] New name for HoC

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/formik#137]
Formik uses named exports and thus we now must decide what to call the new render prop component and the HoC. In the `render props` branch, the component is named `<Formik />` and I think that's what it should be called.

What should the HoC be renamed to?

- `withFormik()`
- `FormikFactory()`
- `FormFactory()`

Thoughts???

**Comment by husa** [comment]
I'd vote for `withFormik`

**Comment by jaredpalmer** [comment]
Going with withFormik
