### ISSUE TITLE
escape square brackets with formik

### ISSUE THREAD

**Issue by Sirius094** [jaredpalmer/formik#1370]
I'm using Formik in react and I'm having issues with square brackets when using the validation in order to show errors on screen. I tried with `"\["` but it didn't work. Insted using something like "text" or "text-i" or even "text(i)" works fine, but I'm having problems only with square brackets.

```
isDataValid = (values: KeyValue<any>) => {
        let errors: FormikErrors<KeyValue<any>> = {};

      (for let i=0; i<... etc) {
        if (!values["text[i]"]) {
            errors["text[i]"] = "Insert title";
        }
     }  

        return errors;
```

any tips?

**Comment by Andreyco** [comment]
would this help?

```
import { getIn } from 'formik';

if (!getIn(values, `text.${i}`) {
    // ...
}
```

**Comment by Sirius094** [comment]
@Andreyco  Unfortunately not :(
The problem is still there. If I remove square brackets from the name property everything works, but I have to use these square brackets...

This is the code

```
               for(let i=0; i<values.question.length; i++){
                     if(!getIn(values, `text[${i}]`)){
			errors[`text[${i}]`] = "Insert title";
		}
```

Then I have an input with this name
```
name={"text["+i+"]"}
```

For example, If I use these settings, the error appears correctly.

```
               for(let i=0; i<values.question.length; i++){
                     if(!getIn(values, `text${i}]`)){
			errors[`text${i}`] = "Insert title";
		}
```

```
name={"text"+i}
```

I don't know how to solve it

**Comment by Andreyco** [comment]
Sorry, this is not Formik issue. You need to convert your date to format Formik understands before setting `initialValues` props and convert it back to original format in `onSubmit` handler.
