### ISSUE TITLE
Input type="password" causes error message in browser

### ISSUE THREAD

**Issue by DPangerl** [jaredpalmer/formik#1379]
### Current Behavior

Considering the following code:

```javascript
<Formik
  initialValues={{ email: "", password: "" }}
  onSubmit={handleFormSubmit}
  render={
    ({ values, handleChange }) => (
      <Form>
        <input
          type="text"
          name="email"
          placeholder="E-Mail"
          onChange={handleChange}
          value={values.email}
        />
        <input
          type="password"
          name="password"
          placeholder="Passwort"
          onChange={handleChange}
          value={values.password}
        />
        <button type="submit">Sign In</button>
      </Form>
      )
    }
/>
```

Every time, I submit this form, Chrome throws the following error:

`Unchecked runtime.lastError: The message port closed before a response was received.`

If I replace the `<input type="password" />` with another type (e.g. `If I replace the `<input type="text" />``)

The error does not occur.

### Expected behavior

There is no error thrown when using `<input type="password" />` within the Formik component's render function.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.1
| React            | 16.8.4
| Chrome Browser          | 72&73
| npm        |6.4.1
| Operating System | macOS Mojave 10.14.3

**Comment by utkez** [comment]
Is it possible that this exception is caused by some Chrome extension, probably 1Password or another password manager?
I've been trying to pinpoint the same problem and got the impression that it's not related to Formik.

**Comment by exeto** [comment]
I also have this problem, really to blame the extension 1Password.

**Comment by DPangerl** [comment]
Yes, can confirm 1password extension is the problem. Thank you!
