### ISSUE TITLE
How do i setup React-Quill and Formik?

### ISSUE THREAD

**Issue by nithinkashyapn** [jaredpalmer/formik#1383]
Hey,

How do i setup React-Quill and Formik?

My current setup is 

```
<Field
    name="designation"
    value={this.props.values.designation}
    render={({ field /* _form */ }) => (
        // <input {...field} placeholder="designation" />
        <ReactQuill
            {...field}
        />
    )}
/>
```

**Comment by andrewphillipoef** [comment]
Well formik fields take onChange({ target: value: "the value" }) and a value prop at a minimum. 

So if you can make your ReactQuillWrapper take a value in and call this.props.onChange when changes occur, you should be okay?

**Comment by nithinkashyapn** [comment]
Thank you, Will try to make that wrapper and update the thread.

**Comment by Andreyco** [comment]
`onChange` has 2 signatures

```
onChange(event: Event) {};
// and
onChange(name: string)(value: string) {};
```
Correct usage would be
```js
<Formik initialValues={{ designation: '' }}>
    <Field>
        {({ field }) => <ReactQuill value={field.value} onChange={field.onChange(field.name)} />}
    </Field>
</Formik>
```

**Comment by quocthangit247** [comment]
> `onChange` has 2 signatures
> 
> ```
> onChange(event: Event) {};
> // and
> onChange(name: string)(value: string) {};
> ```
> 
> Correct usage would be
> 
> ```js
> <Formik initialValues={{ designation: '' }}>
>     <Field name="designation">
>         {({ field }) => <ReactQuill value={field.value} onChange={field.onChange(field.name)} />}
>     </Field>
> </Formik>
> ```

Thank you so much <3

**Comment by vidrepar** [comment]
For anyone using the `useFormik` hook:

```
const { setFieldValue } = useFormik({ ... });

<ReactQuill
    value={values.description}
    onChange={(e) => setFieldValue('description', e)}
/>
```

**Comment by alxvallejo** [comment]
@vidrepar Good solution, however, when i try to re-initialize the value (like when i update my initial value state from an async request), i get an error in console:

>Cannot update a component from inside the function body of a different component.

						<ReactQuill
							theme="bubble"
							name="entry"
							value={values.entry || ''}
							onChange={(e) => setFieldValue('entry', e)}
							placeholder={`Hi ${location.city}! I need a shopper!`}
						/>

**Comment by johnrom** [comment]
You'll need to use an effect with useEffect or an event handler callback, rather than updating the state or context from inside the component body itself.

**Comment by thatal** [comment]
> 
> 
> `onChange` has 2 signatures
> 
> ```
> onChange(event: Event) {};
> // and
> onChange(name: string)(value: string) {};
> ```
> 
> Correct usage would be
> 
> ```js
> <Formik initialValues={{ designation: '' }}>
>     <Field name="designation">
>         {({ field }) => <ReactQuill value={field.value} onChange={field.onChange(field.name)} />}
>     </Field>
> </Formik>
> ```

How to escape HTML tags.

**Comment by johnrom** [comment]
You'll have to read the React Quill docs or general info on escaping HTML tags as it is not something Formik will do for you.

Generally, you'd escape HTML on the server side when saving your info to the database, because React already escapes them for you during render. That method will depend on your language, CMS, or other implementation details.

**Comment by Messa1** [comment]
Did someone also has a example for passing error and on blur?
my code
```
<QuillEditor
                  onChange={(value: string): void => setFieldValue(
                    'costs',
                    value
                  )}
                  placeholder={i18next.t('costs')}
                  sx={{ height: 400 }}
                  value={values.costs}
                  modules={ProjectEditForm.modules}
                  formats={ProjectEditForm.formats}
                />
```

**Comment by samarsingh6965** [comment]
![Uploading Screenshot from 2023-07-25 20-32-05.png…]()
