### ISSUE TITLE
Checkbox input validation inconsistency

### ISSUE THREAD

**Issue by morrisallison** [jaredpalmer/formik#139]
Firstly, thanks for this project, it's pretty cool.

Our form is using `validationSchema`, with both `validateOnChange` and `validateOnBlur` on. Among other inputs, the form has a few checkboxes that are validated with `Yup.boolean()` in the schema.

Reproduce:

A. Toggle a checkbox

1. The checkbox's `value` property is set in `values`
1. The `values` are validated
1. Validation fails: `"on"` is not a boolean
1. The checkbox's `checked` property is set in `values`

B. Click outside the checkbox

1. The values are validated
1. Validation is successful: `true` is a boolean

This only seems to be an issue with `validateOnChange` turned on.

**Comment by jaredpalmer** [comment]
This has been fixed in 0.9.1

**Comment by vuhrmeister** [comment]
I'm experiencing exactly the same with 0.9.4
