### ISSUE TITLE
arrayHelper push 0

### ISSUE THREAD

**Issue by demkovych** [jaredpalmer/formik#1394]
Got an error, when called 
`arrayHelper.push(0)`

**Comment by pierreTklein** [comment]
Can you provide the error that you got? Some context here would be necessary to help you with your bug.

**Comment by demkovych** [comment]
`formik.esm.js:1001 Uncaught TypeError: (array || []).concat is not a function`

**Comment by demkovych** [comment]
It's only happens, when i use <FieldArray> component ,and want to push zero number as array value

**Comment by Andreyco** [comment]
Did you set initial value for array field? It should be empty array

**Comment by demkovych** [comment]
Yes, i set. 
`
initialValues={{cars: []}}
`
And added name attribute to the fieldArray.

**Comment by Andreyco** [comment]
Please, provide codesandbox example, otherwise closing.

**Comment by demkovych** [comment]
Sorry, can't reproduce. Mb i used old version
