### ISSUE TITLE
validateOnSubmit

### ISSUE THREAD

**Issue by DesignMonkey** [jaredpalmer/formik#140]
Hi
First of all. Cool library :) 

Any thoughts on making a validateOnSubmit option? Now if I submit, all the errors disappears, and if I haven't filled out any fields and hit submit, nothing happens.

**Comment by richin13** [comment]
Hey there!

You can achieve this by setting all your fields touched. Here an example:

```javascript
  handleSubmit: (values, {props, setFieldTouch, setErrors, setSubmitting}) => {
    Object(values).keys().each((k) => setFieldTouch(k, true));
    // ...
  }
```

**Comment by jaredpalmer** [comment]
Validation happens when submit is attempted. You can use `isInitialValid` to set the initial validity of the form.
