### ISSUE TITLE
FormikBag empty when separate Formik and Field in a third party package

### ISSUE THREAD

**Issue by k4st0r42** [jaredpalmer/formik#1400]
### Current Behavior

Formikbag is empty when I use Field in a third party package.

example in a third library package :
```
import { Field as FormikField} from 'formik'
const Field = (props) => {
    let { validate,
      ...rest } = props;
      
    return <FormikField {...rest} validate={multiFieldValidation(validate)} />
  }
```
Same problem than #1269 

### Reproducible example

Sorry, I can't do a reproducible example on Codesandbox  because the problem is in the referenced package.

### Suggested solution(s)

I found a temporary solution : 

I encapsulate the Formik form in the same thirt package library that is using the Field.

```
const Form= (props) => {
    return <Formik {...props} />
  }
```

If the Formik and the Field come from the same package, it works...

### Additional context

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |1.5.1
| React            |15.6.2
| npm         | 6.1.0

**Comment by jaredpalmer** [comment]
The only way this is possible is if you are rendering a Field without a Formik parent ancestor component higher up your tree
