### ISSUE TITLE
Field type="email" with multiple attribute cursor jumps to start

### ISSUE THREAD

**Issue by jordyvg** [jaredpalmer/formik#1428]
### Current Behavior

While adding multiple comma separated email addresses the cursor will jump to te beginning the input field.

### Expected behavior

Cursor stays on current position.

### Reproducible example

Example: https://codesandbox.io/embed/k57zw7wz5
MDN docs: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email#multiple

### Additional context

It look like the problem is caused by Field's `value={values.email}` attribute.

**Comment by andrewMuntyan** [comment]
So, I was going on to fix this but after some investigation, I figured out this is not Formik but React issue with `input type="email"` component. @jordyvg you can verify this by looking at this pure React example https://codesandbox.io/embed/0y06zo7l8p

Also, you can see similar behavior in a case when you have some space-separated values and try to delete them one by one.

![screencast 2019-04-13 14-03-27](https://user-images.githubusercontent.com/1164826/56078836-1f006100-5df5-11e9-9e1c-7952dd1b3fc0.gif)

**Comment by jordyvg** [comment]
@andrewMuntyan The same problem here.
It seems to be a React issue, no Formik issue.

**Comment by jordyvg** [comment]
Will submit the [issue](https://github.com/facebook/react/issues/15418) by the React repo.
