### ISSUE TITLE
Update validation message conditionally

### ISSUE THREAD

**Issue by ZeroDarkThirty** [jaredpalmer/formik#1433]
## ❓Question
I'm trying to write a schema where when the user selects an item from a dropdown, it checks whether the clicked item has an associated book or not. If it doesn't, the schema renders a message to the user.

```
    ItemID:
        Yup.string()
            .required("Item is required")
            .when("ItemID", (itemID: string, passSchema: any) => {
                const selectedItem = this.props.AllItems.find((i) => i.ID === itemID);
    
                // Check if selected item includes a book
                if (selectedItem.Book) {
                    // schema pass
                } else {
                    // render message "This item does not include a book."
                }
            }),
```
I've done the above but its throwing this error: Error: Cyclic dependency. I'm assuming its trying to validate the same field that's changing. How can I get around this?

**Comment by marioharper** [comment]
Instead of using `when` you can use [test](https://github.com/jquense/yup#mixedtestname-string-message-string--function-test-function-schema) to write any generic validation. For example: 

```
    .test(
      'itemIncludesBook',
      'This item does not include a book.',
      val => val == null || itemHasBook(val),
    )
```

**Comment by ZeroDarkThirty** [comment]
Thank you so much. That did the trick. I wish the Yup documentation had better examples.
