### ISSUE TITLE
Form is not validating onBlur and onChange

### ISSUE THREAD

**Issue by nareshbhatia** [jaredpalmer/formik#1442]
## ❓Question

My form is not validating onBlur and onChange. It validates only onSubmit. How do I debug this? AFAIK validateOnBlur and validateOnChange default to false.

    const money = new RegExp('^(d+|d{1,3}(,d{3})*)(.d+)?$');

    const validationSchema = yup.object().shape({
        amount: yup
            .string()
            .matches(money)
            .required(),
    });

    return (
        <Formik<FormModel>
            initialValues={txn}
            validationSchema={validationSchema}
            onSubmit={(values, { setSubmitting }) => {
                onSave(mapFormModelToEntity(values));
                setSubmitting(false);
            }}
            render={({ submitForm }) => (
                <Form>
                    <Field
                        name="amount"
                        component={TextInput}
                        label="Amount"
                        fullWidth
                    />
                    ...
                    <Button onClick={submitForm} color="primary">
                        SAVE
                    </Button>
                </Form>
            )}
        />
    );

**Comment by nareshbhatia** [comment]
I am finding that once I submit an invalid form (and the validation errors start showing), then onChange validations start working. As I press a key, the validation takes place immediately. So I must be missing something.

**Comment by nareshbhatia** [comment]
Digging deeper, it seems that `touched` flag is not set even when we start typing into a field. Validations are happening, I can even see the `error` property being populated, but it doesn't show up since `touched` on that field is false.

Incidentally, as soon as the form is submitted all the touched flags are set to true. This seems counter intuitive.

**Comment by jaredpalmer** [comment]
This behavior is expected during submission. See the docs on validation https://jaredpalmer.com/formik/docs/guides/validation and on the submit process https://jaredpalmer.com/formik/docs/guides/form-submission

**Comment by nareshbhatia** [comment]
Thanks @jaredpalmer for pointing me in the right direction. I understand this much better now. My assumption was that the form validation rules also apply at the field level, which is not the case. I suppose https://github.com/jaredpalmer/formik/pull/780 is what I am looking for - but it seems to be stuck since July, 2018!

**Comment by iamwavefly** [comment]
add this to your field `onBlur={formik.handleBlur}`

**Comment by GP3-RS** [comment]
What worked for me is, within your Formik component's callback, 
`if (!formik.touched.{fieldName}) formik.setTouched({ customSlugInput: true });`
Basically, if the field has not been "touched" Formik won't validate it, so on render, check if the field hasn't been touched, and set it's touched value to true.

If you want a more verbose example:

```
<Formik
  initialValues={}
  validationSchema={validationSchema}
>
  {(formik) => {
      if (!formik.touched.{fieldName}) formik.setTouched({ fieldName: true });
      return (
          <>
            {your components here}
          </>
      )
  }}
</Formik>
```

Another viable option is, within your input component, set its "onFocus" attribute, like this: 
`onFocus={() => formik.setTouched({ fieldName: true })
`

**Comment by Prabhat2373** [comment]
You can refer this Gist - https://gist.github.com/Prabhat2373/4563597548fde76f37115323748eed0f 
where you'll find ErrorController which you can place inside Formik component.

and it will trigger or work as validateOnChange.
