### ISSUE TITLE
Update code inside reference documentation link

### ISSUE THREAD

**Issue by septs** [jaredpalmer/formik#1443]
https://github.com/jaredpalmer/formik/blob/c5243947fcf21cd873dd86b57689a30ffc46eab8/src/Formik.tsx#L147-L151
Reference:
https://github.com/jaredpalmer/formik#setstatus-status-any--void bad link

https://github.com/jaredpalmer/formik/blob/c5243947fcf21cd873dd86b57689a30ffc46eab8/src/Formik.tsx#L473-L477
Reference:
https://github.com/jaredpalmer/formik#handleblur-e-reactfocuseventany--void bad link

https://github.com/jaredpalmer/formik/blob/c5243947fcf21cd873dd86b57689a30ffc46eab8/src/Formik.tsx#L323-L327
Reference:
https://github.com/jaredpalmer/formik#handlechange-e-reactchangeeventany--void bad link

**Comment by jaredpalmer** [comment]
Yep. We gotta move those to the docs.

**Comment by septs** [comment]
@jaredpalmer next release fixed?
