### ISSUE TITLE
Get values in validationSchema for dynamic validation rules

### ISSUE THREAD

**Issue by davetimmins** [jaredpalmer/formik#145]
As well as accessing the props in `validationSchema` is it possible to get the current values? I'm wanting a way to define the validation dynamically based on the values selected by the user.

e.g.
```js
validationSchema?: Schema | ((props: Props) => Schema)
// becomes
validationSchema?: Schema | ((values: Values, props: Props) => Schema)
```

happy to submit a PR if you're interested in this.

**Comment by skattyadz** [comment]
Hi Dave

Is yup.lazy enough to solve your problem?
https://github.com/jquense/yup/blob/master/README.md#yuplazyvalue-any--schema-lazy

**Comment by davetimmins** [comment]
Yes it is thanks!

so if anyone is interested it's now

```js
validationSchema: props => {
    return Yup.lazy(values => {      
      return Yup.object().shape({
```

whereas before it was

```js
validationSchema: props =>    
    Yup.object().shape({
```

**Comment by skattyadz** [comment]
👍👍👍

**Comment by nitaking** [comment]
@davetimmins Sounds good!!

**Comment by MohammadHosseinBagheri** [comment]
@davetimmins 
Amazing
