### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by silentlight** [jaredpalmer/formik#1450]
## ❓Question

Is Formik supported by IE11? I open my app on IE11 and form's onChange event handler don't fire at all. Anyone knows how to make it work?

Thanks!

**Comment by msheakoski** [comment]
I had a similar issue with the form not submitting when pressing enter and adding a promise polyfill fixed it for me. Maybe it will also help you? I used the [promise polyfill from core-js](https://github.com/zloirock/core-js#ecmascript-promise).

**Comment by jaredpalmer** [comment]
Are you using react-app-polyfill

**Comment by silentlight** [comment]
In my case it was a different issue, but yes, I had to use polyfill. I am using Nextjs to Promise polyfill is already there

**Comment by SchauweM** [comment]
> In my case it was a different issue, but yes, I had to use polyfill. I am using Nextjs to Promise polyfill is already there

How did you manage to fix it? Having the same issue atm

**Comment by teetotum** [comment]
@SchauweM It usually is caused by missing polyfills when formik is not working in IE11. As discussed [here](https://github.com/formium/formik/issues/1480).
