### ISSUE TITLE
Issue when paging through a wizard with validation on each step

### ISSUE THREAD

**Issue by MatthewKinbaum** [jaredpalmer/formik#1454]
I'm having an issue when navigation back and forth between pages in my form. I am maintaining my form values in a single location like so (simplified for example):
```
const [ formValues, setFormValues ] = useState({
    pageOneField: '',
    pageTwoField: ''
})
```
Then, based on the wizard step, I use a different validationSchema. I maintain each page's validation rules in an array like so:
```
// Multiple fields for each page, but simplified for demonstration
validationSchema = [
    yup.object().shape({
        pageOneField: yup.string().required(),         
    }),
    yup.object().shape({
        pageTwoField: yup.string().required()
    })
];
```
Then I access each page's validation rules using the current page you're on like this:
```
// Simplified for demonstration
Formik
    initialValues={ formValues }
    enableReinitialize={ true }
    validationSchema={ validationSchema[currentPage] }
    onSubmit={ handleSubmit }
    render={ innerProps => (
        <Form>...</Form>
    ) } />
```
It seems to me that Formik will only respect my validationSchema for each page if i enable `enableReinitialize`. This is what causes the issue for me when navigating between pages.

Scenario:
- I enter valid information on both pages of my form. 
- On page 2, I click previous to go back to page 1. 
- I can see the next button on page 1.
- I click the next button to go back to page 2 where I've already filled out valid information. 
- The next button does not appear on page 2 anymore (only appears if new information is added).
- I click the previous button again to go back to page 1.
- The next button is gone from page 1 (same issue as page 2).

I think a diff-check is being performed and when Formik looks at each page you've previously visited, if none of the values have changed, then `isValid` is set to `false`. I'm only able to navigate between pages when modifying a field value.

Has anyone else run into this and if so, are there any workarounds? Each of my form values must be maintained within the single formValues object.

I've included an example of this here:
https://codesandbox.io/s/v3qqyxp3j5

**Comment by MatthewKinbaum** [comment]
Update: I was able to solve my problem by adding the `isInitialValid` prop to the `<Formik />` component. Then calling the `isValidSync` function from my schema:
```
<Formik
    initialValues={ formValues }
    isInitialValid={ ({ initialValues: values }) => schema.isValidSync(values) }
    enableReinitialize={ enableReinitialize }
    validationSchema={ schema }
    onSubmit={ handleSubmit } />
```

**Comment by JoaoFGuiomar** [comment]
@MatthewKinbaum Thanks for the update, this helped me! 🍻

**Comment by MatthewKinbaum** [comment]
@jaredpalmer 

I'm now implementing v2 and I'm getting the deprecation message for `isInitialValid`. Can you provide a specific example that allows me to convert the code above to use `initalErrors` or `validateOnMount`?
