### ISSUE TITLE
Scroll to first invalid element

### ISSUE THREAD

**Issue by cassln** [jaredpalmer/formik#146]
Is there nice and recommended way to scroll to first invalid form element with formik, when form is submitted?

**Comment by Andreyco** [comment]
I would go for component which will react to `errors` prop change.

1. watch change either in `componentWillReceiveProps` or `componentDidUpdate`
2. when change is detected, find first/topmost error message and scroll to message

**Comment by jaredpalmer** [comment]
Yeah `componentDidUpdate` is probs the best way to do this as it is a sideeffect.

**Comment by cassln** [comment]
Side effect in `componentDidUpdate` looks good. But how can I detect in `componentDidUpdate` that it was exact submit, not change. (I'm using `validateOnChange` option)

**Comment by jaredpalmer** [comment]
@cassln There may be more elegant ways to do this, but I would do something like:

```js
// ... 

componentDidUpdate(prevProps) {
   // if form was submitting, but now is not submitting because it is invalid
   if (prevProps.isSubmitting && !this.props.isSubmitting && !this.props.isValid) {
      // and assume you've added refs to each input: `ref={ i => this[name] = i}` , then...
      this.[Object.keys(this.props.errors)[0]].focus() 
  }
}
```

- I think `.focus()` will trigger a scroll in most browsers, maybe janky tho
- Not 100% certain which order your `errors` keys will be in, would depend on your validation function. I believe Yup maintains shape-order (worth checking).

**Comment by cassln** [comment]
@jaredpalmer this condition is working perfect. Thank you very much.

I don't use `.focus()`, because I have complex form components like gallery. I use `div` with `data-scroll-anchor` attribute and find first `div` with the attribute. But I think this is case specific part.

Issue is covered, so i'm going to close issue now. :)

**Comment by lardissone** [comment]
@jaredpalmer this solution is only available on formik enhanced forms right? Is there a similar way to implement this in render props way?

**Comment by Grsmto** [comment]
@lardissone you can do that as well with render props I think. Just create a `ScrollToError` component which contain the above code and after you use it this way:

```
<Formik
  render={formikProps => (
    <form>
      <ScrollToError {...formikProps} />
    </form>
  )}
/>
```

**Comment by cloud-walker** [comment]
We need to be able to know at the same time about three things:
- the errors object
- the isSubmitting state
- the inputs refs

This is not actually possible at the moment, because when you submit the form, formik validate is fired, and the isSubmitting state remain false (when some field is invalid ofc)

There should be a way to know these things, I propose to:

- pass the isSubmitting state on the validate function? Like `validate(values, {isSubmitting})`
- validate should not reset isSubmitting to false?

Thanks in advance!

**Comment by fobdy** [comment]
My temporary solution is to attach an extra click handler to the submit button and check there for errors and scroll if needed. This works because of onChange + onBlur validation, so i have proper validation info before submitting.

**Comment by jon64digital** [comment]
I'm also trying to do this. Does anybody have any example code of how to scroll to the first error on submit using the render props version?

**Comment by dphrag** [comment]
I created this with the most recent version of Formik (1.3.1):

https://gist.github.com/dphrag/4db3b453e02567a0bb52592679554a5b

Just stick that component <ErrorFocus> inside of your Formik like:

```<Formik>
        {({ dirty, isSubmitting, errors }) => {
          return (
            <Form method="post">
              <Field />
              <Field />
              <ErrorFocus />
            [</Form>]
          );
        }}
 </Formik>```

Yeah it uses DOM access directly so you don't have to write refs into every field, but it SHOULD be ok... I think... haha.

**Comment by george-maged** [comment]
I've modified @dphrag 's gist to work with nested errors


```
import React from 'react';
import { connect } from 'formik';
class ErrorFocus extends React.Component {
    isObject(value) {
        return value && typeof value === 'object' && value.constructor === Object;
    }
    getKeysRecursively = (object) => {
        if (!this.isObject(object)) {
            return ''
        }
        const currentKey = Object.keys(object)[0]
        if (!this.getKeysRecursively(object[currentKey])) {
            return currentKey
        }
        return currentKey + "." + this.getKeysRecursively(object[currentKey])
    }
    componentDidUpdate(prevProps) {
        const { isSubmitting, isValidating, errors } = prevProps.formik;
        const keys = Object.keys(errors);
        if (keys.length > 0 && isSubmitting && !isValidating) {
            const selectorKey = this.getKeysRecursively(errors)
            const selector = `[id="${selectorKey}"], [name="${selectorKey}"] `;
            const errorElement = document.querySelector(selector);
            if(errorElement){
                errorElement.focus();
            }
        }
    }
    render() {
        return null;
    }
}
export default connect(ErrorFocus);
```

**Comment by nathanforce** [comment]
I wrote up a post on how we created a lib do this on some of our forms.  

https://palmer.net/blog/form-field-scroll-management-in-react

The API is a bit clunky, but I think Hooks can help quite a lot for something like this.  Let me know what you think!

**Comment by osv** [comment]
Hi, React Hooks + Typescript version how to uncollapse panels, scroll to error and focus input if can using https://gist.github.com/osv/691efa00784def6f6004d31cd6108f56

**Comment by nathanforce** [comment]
I wrote up a hooks library that can help here.

https://github.com/nathanforce/react-register-nodes

Example usage:

https://codesandbox.io/s/10363x25oq

**Comment by MontoyaAndres** [comment]
All those examples does not work when the error is from fetch an api...

**Comment by sarahsmo** [comment]
@cassln @jaredpalmer Can we open this issue back up? 

Reason I ask is because the suggestion to use componentDidUpdate where inside you get errors[0] and focus on that element doesn't work. 

I did some of my own testing, and formik can receive errors with all sorts of ordering. In some instances, formik receives errors in the order that the programmer defines them in the validate prop. Sometimes one error will randomly come first and the rest will be in order. Sometimes the errors are in alphabetical order. It seems we cannot trust that errors returns in the exact order they are defined in.

Here is an example of what I mean
![image](https://user-images.githubusercontent.com/31173144/52659600-a734b980-2ecb-11e9-87e9-59b8b508dcea.png)
So when I create the form, and console log my errors after they are all added, they appear in the order that I added them. 
However, when i console log my errors within the ErrorFocus component, using FormikContext, the errors appear out of order
![image](https://user-images.githubusercontent.com/31173144/52659687-e105c000-2ecb-11e9-9234-1970520c01ec.png)


Therefore, there is no easy way to identify the first error. 

Is there any way we can get support for scrolling to the first error in formik? Can we get an optional prop, like "setScrollError" where when set to true, it scrolls to first error.

The reason I think it would be better if Formik handled it, is because clearly there seems to be issues when later on getting those error values. If formik handled it internally then hopefully they would remain in order!

**Comment by nathanforce** [comment]
@sarahsmo I don't think there's a reliable way for Formik to determine "first" error. Formik would need to know which DOM node you have rendered for your form and then query the ordering of the nodes that correspond to invalid fields.  It's a bit messy and imperative and probably best left to be implemented by the user.  I don't think you want to rely on the ordering of the keys in the `errors` object, as key ordering is generally unstable in javascript.

That said, we've recently published [react-register-nodes](https://github.com/palmerhq/react-register-nodes) which we think solves this problem nicely using React Hooks.  There's an example in the Readme of that repo that illustrates scrolling to first error.

Let me know if that helps!

**Comment by sarahsmo** [comment]
@nathanforce Yes that helps!! Thank you!

**Comment by MontoyaAndres** [comment]
One way I could resolve the problem to catch the first error and show it on its input, instead of using react-register-nodes' solution was this one (In my case):

```
const ErrorFocus = ({
  name,
  formik: { isSubmitting, isValidating, errors }
}) => {
  const keys = Object.keys(errors);
  if (keys.length > 0 && isSubmitting && !isValidating) {
    document.querySelector(`[name="${keys[0]}"]`).focus();
  }

  return <ErrorMessage name={name} />;
};

const ConnectErrorFocus = connect(ErrorFocus);
```

The preview code shows the error and focus on that element, inspired by @bphrag's solution, so I only call this component in any other component, like this:

```
const field = ({ name, placeholder }) => (
  <div className="field">
    <div className="control">
      <Field
        name={name}
        placeholder={placeholder}
        className="input is-hovered"
        required
      />
    </div>
    <ConnectErrorFocus name={name} />
  </div>
);
```

But, there's one problem, when the API sends me an error and I want to show it on any input, for example if I typed a wrong password, I want to focus on the password input. The solution I could do was (In my case) adding the `document.querySelector(`[name="${keys[0]}"]`).focus();` function, something like this:

```
const response = await axios.post("http://localhost:8080/", {
  password: values.password
});

if (response.data.length > 0) {
  setErrors(normalizeErrors(response.data));
  document.querySelector(`[name="${response.data[0].path}"]`).focus();
}

setSubmitting(false);
```

The server sends this:

```
[
  {
    path: "password",
    message: "Wrong password."
  }
]
```

And the `normalizeErrors` function transform that array to `{ password: ['error 1', 'error 2'] }`.

If someone wants an example more imperative, [here you go](https://github.com/MontoyaAndres/FormikCatchErrors).

**Comment by danielberndt** [comment]
In case you're using v2.0 already, here's a hook version of focussing the field with the first error:

```jsx
const useFocusOnError = ({fieldRef, name}) => {
  const formik = useFormikContext();
  const prevSubmitCountRef = React.useRef(formik.submitCount);
  const firstErrorKey = Object.keys(formik.errors)[0];
  React.useEffect(() => {
    if (prevSubmitCountRef.current !== formik.submitCount && !formik.isValid) {
      if (fieldRef.current && firstErrorKey === name) fieldRef.current.focus();
    }
    prevSubmitCountRef.current = formik.submitCount;
  }, [formik.submitCount, formik.isValid, firstErrorKey]);
};
```

you can use it like this

```jsx
const Input = ({name, ...props}) => {
  const fieldRef = React.useRef();
  const [field] = useField(name);
  useFocusOnError({fieldRef, name});
  return <input ref={fieldRef} name={name} {...props} {...field} />;
};
```

**Comment by jacek213** [comment]
any working solutions for react-native?

**Comment by antoniojps** [comment]
Here's my solution, assuming this is a custom field component that receives the `form` props:

```js
  useEffect(() => {
    if (isValid || !isSubmitting) return;
    const firstErrorKey = Object.keys(errors)[0];
    if (!isValid && firstErrorKey === field.name) {
      fieldRef.current.focus();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isSubmitting, isValid]);
```

**Comment by element-root** [comment]
Assuming your form has an id, you can do without refs:

```js
  useEffect(() => {
    for (field of document.getElementById(form.id)) {
      if (touched[field.id] && errors[field.id]) {
        return field.focus();
      }
    }
  }, [touched, errors]);
```

**Comment by WestonThayer** [comment]
The `componentDidUpdate` approach worked fine for me, but I found doing a validation check in the submit button's `onClick` to be much cleaner. No need to add a non-rendering React element to the tree.

```jsx
{/* Inside of Formik render prop function... */}

<label>
  Email address:
  <Field id={EMAIL_KEY} name={EMAIL_KEY} />
</label>

<button
  type="submit"
  disabled={formikProps.isSubmitting}
  onClick={async () => {
    const curErrors = await formikProps.validateForm();
    const curErrorsKeys = Object.keys(curErrors);

    if (curErrorsKeys.length) {
      // Assuming curErrorsKeys[0] identifies the first failing field, use that to
      // find the correct DOM element to call .focus() on.
      //
      // Since I set the id attribute on all my form's <input>s to match the error
      // keys, I just use document.getElementById(), but of course you could use refs
      const el = document.getElementById(curErrorsKeys[0]);

      if (el) el.focus();
    }
  }
/>
```

[Demo Codesandbox](https://codesandbox.io/s/dreamy-ptolemy-e7tj2)

This doesn't prevent the default submit logic from running. I think the errored field is technically focused *before* Formik touches it, but it all happens so fast the user doesn't notice.

**Comment by alex198710** [comment]
To complete @Grsmto and @george-maged solution, I complete the script to handle Arrays
Here is the script: https://playcode.io/469441

Finally your componentDidUpdate will look like that:
```
public componentDidUpdate(prevProps: Props) {
  if (prevProps.submitCount !== this.props.submitCount && !this.props.isValid) {
    if (this.getFirstPath(errors).slice(1) === this.props.name) {
      (ReactDOM.findDOMNode(this.props.inputRef.current) as any).scrollIntoView({behavior: "smooth"});
    }
  }
}
```

**Comment by RemyMachado** [comment]
Does someone found a solution to scroll on an element outside the form ? A way to scroll to the header, showing server errors.

I would like to access the form errors inside a `useEffect()` to trigger a scroll targeting a `ref`erence to an element.

**Comment by jack482653** [comment]
I rewrite @dphrag and @george-maged code to support field array: 
https://gist.github.com/jack482653/ffd44e0b5c8776c0d12710e32ce69c65

**Comment by shashankrepo** [comment]
Hi @danielberndt, your code works well but there is one issue, when i click submit twice then it scroll up to first error. On first click, it just shows error. How can I fix this issue?

**Comment by bajajsu16** [comment]
@shashankrepo Were you able to make it on the first click?

> Hi @danielberndt, your code works well but there is one issue, when i click submit button twice then it scroll up to first error. On first click, it just shows error. How can I fix this issue?

**Comment by yrodriguezle** [comment]
```javascript
import { useEffect } from 'react';
import isObject from 'lodash/isObject';
import { useFormikContext } from 'formik';

const getFirstErrorKey = (object, keys = []) => {
  const firstErrorKey = Object.keys(object)[0];
  if (isObject(object[firstErrorKey])) {
    return getFirstErrorKey(object[firstErrorKey], [...keys, firstErrorKey]);
  }
  return [...keys, firstErrorKey].join('.');
};

const FormikOnError = ({ children }) => {
  const formik = useFormikContext();

  useEffect(() => {
    if (!formik.isValid && formik.submitCount > 0) {
      const firstErrorKey = getFirstErrorKey(formik.errors);
      if (global.window.document.getElementsByName(firstErrorKey).length) {
        global.window.document.getElementsByName(firstErrorKey)[0].focus();
      }
    }
  }, [formik.submitCount, formik.isValid, formik.errors]);
  return children;
};

export default FormikOnError;
```

After:
```javascript
<Formik>
  <Form>
    <FormikOnError>
        {form stuff}
    </FormikOnError>
 </Form>
</Formik>
```

**Comment by stephenasamoah** [comment]
> ```js
> import { useEffect } from 'react';
> import isObject from 'lodash/isObject';
> import { useFormikContext } from 'formik';
> 
> const getFirstErrorKey = (object, keys = []) => {
>   const firstErrorKey = Object.keys(object)[0];
>   if (isObject(object[firstErrorKey])) {
>     return getFirstErrorKey(object[firstErrorKey], [...keys, firstErrorKey]);
>   }
>   return [...keys, firstErrorKey].join('.');
> };
> 
> const FormikOnError = ({ children }) => {
>   const formik = useFormikContext();
> 
>   useEffect(() => {
>     if (!formik.isValid && formik.submitCount > 0) {
>       const firstErrorKey = getFirstErrorKey(formik.errors);
>       if (global.window.document.getElementsByName(firstErrorKey).length) {
>         global.window.document.getElementsByName(firstErrorKey)[0].focus();
>       }
>     }
>   }, [formik.submitCount, formik.isValid, formik.errors]);
>   return children;
> };
> 
> export default FormikOnError;
> ```
> 
> After:
> 
> ```js
> <Formik>
>   <Form>
>     <FormikOnError>
>         {form stuff}
>     </FormikOnError>
>  </Form>
> </Formik>
> ```

@yrodriguezle This works fine at focusing the first error item, but once you start typing into the empty input, after one or two characters, it jumps prematurely to the next available error input.

**Comment by yrodriguezle** [comment]
@stephenasamoah I think that after focus you should call ```setTouched({})```

**Comment by nikugogoi** [comment]
@stephenasamoah when you type in the empty input the formilk error bag changes and so the useEffect in FormikOnError is called again. I used the `formik.submitCount` to stop auto focus to the first error text field. Here is the change in @yrodriguezle's  solution

```js
import { useEffect, useState } from 'react';
import isObject from 'lodash/isObject';
import { useFormikContext } from 'formik';

const getFirstErrorKey = (object, keys = []) => {
  const firstErrorKey = Object.keys(object)[0];
  if (isObject(object[firstErrorKey])) {
    return getFirstErrorKey(object[firstErrorKey], [...keys, firstErrorKey]);
  }
  return [...keys, firstErrorKey].join('.');
};

const FormikOnError = ({ children }) => {
  const formik = useFormikContext();
  const [submitCount, setSubmitCount] = useState(formik.submitCount)

  useEffect(() => {
    if (!formik.isValid && formik.submitCount > submitCount) {
      const firstErrorKey = getFirstErrorKey(formik.errors);
      if (global.window.document.getElementsByName(firstErrorKey).length) {
        global.window.document.getElementsByName(firstErrorKey)[0].focus();
      }
      setSubmitCount(formik.submitCount)
    }
  }, [formik.submitCount, formik.isValid, formik.errors]);
  return children;
};

export default FormikOnError;
```

After:
```jsx
<Formik>
  <Form>
    <FormikOnError>
        {form stuff}
    </FormikOnError>
 </Form>
</Formik>
```

**Comment by keremciu** [comment]
@nikugogoi I really like your example but I removed children to apply it easier

```
const FocusOnFirstError = () => {
  const formik = useFormikContext();
  const [submitCount, setSubmitCount] = useState(formik.submitCount)

  useEffect(() => {
    if (!formik.isValid && formik.submitCount > submitCount) {
      const firstErrorKey = getFirstErrorKey(formik.errors);
      if (global.window.document.getElementsByName(firstErrorKey).length) {
        global.window.document.getElementsByName(firstErrorKey)[0].focus();
      }
      setSubmitCount(formik.submitCount)
    }
  }, [formik.submitCount, formik.isValid, formik.errors]);
  return null;
};

export default FocusOnFirstError;
```

is there any reason to wrap the form that you could think of?

**Comment by builtbyjay** [comment]
Just wanted to add my solution to this, seeing as previous examples are getting references to elements by querying the document which doesn't feel right to me.

Here is my `useScrollToOnError()` hook:

```typescript
import { RefObject, useEffect, useRef } from "react";
import { useFormikContext } from "formik";

export const useScrollToOnError = (scrollable: RefObject<HTMLDivElement>, name: string) => {
  const formik = useFormikContext();
  const prevSubmitCountRef = useRef(formik.submitCount);
  const firstErrorKey = Object.keys(formik.errors)[0];

  useEffect(() => {
    if (prevSubmitCountRef.current !== formik.submitCount && !formik.isValid) {
      if (scrollable.current && firstErrorKey === name) {
        scrollable.current.scrollIntoView({
          behavior: "smooth",
          block: "start"
        });
      }
      prevSubmitCountRef.current = formik.submitCount;
    }
  }, [formik.submitCount, formik.isValid]);
};
```

I have created a small component called `ScrollToOnError` which uses the hook:

```typescript
import { FC, useRef } from "react";

import { useScrollToOnError } from "lib/form";

interface ScrollToOnErrorProps {
  name: string;
}

const ScrollToOnError: FC<ScrollToOnErrorProps> = ({ name, children }) => {
  const targetRef = useRef<HTMLDivElement>(null);
  useScrollToOnError(targetRef, name);

  return <div ref={targetRef}>{children}</div>;
};

export default ScrollToOnError;
```

Last step is to wrap whatever element you want to be the scroll target with the `ScrollToOnError` component. For me, the label of the form field makes most sense:

```typescript
<FormControl>
  <ScrollToOnError name="first_names">
    <FormLabel>First name(s)</FormLabel>
  </ScrollToOnError>
  <FastField as={Input} name="first_names" />
  <FormErrorMessage>{errors.first_names}</FormErrorMessage>
</FormControl>
```

Bare in mind that this scrolls to first error only - it doesn't focus the input. Which may or may not suit your needs.

I hope somebody finds this useful 😄

**Comment by fekajin** [comment]
actually there was pretty simple way to do that. 

On your submit buttons onClick Method you can define a method like this;

`<button onClick={() => scrollToErrors(errors)} > //errors param is formik's errors param. `
https://formik.org/docs/guides/validation#validationschema

```
const scrollToErrors = (errors) => {
    const errorKeys = Object.keys(errors);
    if (errorKeys.length > 0) {
      document.getElementsByName(errorKeys[0])[0].focus();
    }
  }
```

**Comment by maurosbu** [comment]
@fekajin it doesn't work when using FieldArray.

**Comment by christopherdevops** [comment]
i am using useFormik and it's a bit trick to set focus on invalid entries.
so, i added hook like this.
`
  useEffect(() => {
    if (Object.keys(formik.errors).length > 0) {
      document.getElementsByName(Object.keys(formik.errors)[0])[0].focus();
    }
  }, [formik]);`

and it works for me.

**Comment by sandwichsudo** [comment]
> i am using useFormik and it's a bit trick to set focus on invalid entries.
> so, i added hook like this.
> 
> ```
>   useEffect(() => {
>     if (Object.keys(formik.errors).length > 0) {
>       document.getElementsByName(Object.keys(formik.errors)[0])[0].focus();
>     }
>   }, [formik]);
> ```
> 
> and it works for me.

This is great thank you!

A small addition to reset the behaviour when the user submits the form:

```
                useEffect(() => {
                    if (Object.keys(errors).length > 0) {
                        document
                            .getElementsByName(Object.keys(errors)[0])[0]
                            .focus();
                    }
                }, [errors, isSubmitting]);
```

**Comment by tetchel** [comment]
I used the solution from [above](https://github.com/jaredpalmer/formik/issues/146#issuecomment-809328458) but had to wrap it in a short setTimeout or my submit button seemed to steal the focus.

```
const scrollToErrors = (errors: FormikErrors<any>) => {
  const errorKeys = Object.keys(errors)
  if (errorKeys.length > 0) {
    setTimeout(() => {
      document.getElementsByName(errorKeys[0])[0].focus()
    }, 10)
  }
}
```

**Comment by hanseonghye** [comment]
I use that.

```typescript


export const getFormikError = (errors: FormikErrors<any>) => {
  const key = Object.keys(errors)[0];
  let error: any = errors[key];

  while (error)
    if (typeof error === 'string') {
      break;
    } else if (typeof error === 'object') {
      const key2 = Object.keys(error)[0];
      error = error[key2];
    } else if (Array.isArray(error)) {
      error = error[0];
    } else {
      break;
    }

  return error || 'check the input value.';
};
```

**Comment by farulivan** [comment]
> actually there was pretty simple way to do that.
> 
> On your submit buttons onClick Method you can define a method like this;
> 
> `<button onClick={() => scrollToErrors(errors)} > //errors param is formik's errors param. ` https://formik.org/docs/guides/validation#validationschema
> 
> ```
> const scrollToErrors = (errors) => {
>     const errorKeys = Object.keys(errors);
>     if (errorKeys.length > 0) {
>       document.getElementsByName(errorKeys[0])[0].focus();
>     }
>   }
> ```

This one so far is my favorite! Thank you!
I try to put it into my `helper` functions so I can call it whenever I need it. 
I modified it a bit because I just want to scroll to the following field instead of focusing.

```
type FormErrors = {
    [key: string]: string | undefined;
};

export const scrollToErrors = (errors: FormErrors) => {
    const errorKeys = Object.keys(errors);
    if (errorKeys.length > 0) {
        const errorElement = document.getElementsByName(errorKeys[0])[0];
        errorElement?.scrollIntoView({
            behavior: "smooth",
            block: "center",
            inline: "center",
        });
    }
};
```
