### ISSUE TITLE
How to use Formik with a CDN

### ISSUE THREAD

**Issue by alqamabinsadiq** [jaredpalmer/formik#1463]
## ❓Question

I am trying to use Formik inside my Preact application. I am using a CDN for everything.
Have a look at: https://codepen.io/alqamabinsadiq/pen/XQyWme?editors=0010

**Comment by cryptic22** [comment]
Here is an example of Formik CDN with react: https://codepen.io/pankajJS/pen/xeQNqO?editors=1010. I hope it will work the same with Preact as well.

**Comment by alqamabinsadiq** [comment]
It's not working. kindly check your pen again.

**Comment by alqamabinsadiq** [comment]
> Here is an example of Formik CDN with react: https://codepen.io/pankajJS/pen/xeQNqO?editors=1010. I hope it will work the same with Preact as well.
It's not working. kindly check your pen again.

**Comment by cryptic22** [comment]
It is working now.

**Comment by alqamabinsadiq** [comment]
> It is working now.


Yeah I changed your code and it worked but the problem is it's not working with Preact.

**Comment by m1m6** [comment]
I see its working

**Comment by Douglasacost** [comment]
Its not working, give 404 from cdn link, any solution?

**Comment by kumar88kanishk** [comment]
What is CDN URI??

**Comment by Douglasacost** [comment]
@kumar88kanishk `<script src="https://unpkg.com/formik/dist/formik.umd.production.js"></script>` extracted from 

> https://jaredpalmer.com/formik/docs/overview

**Comment by kumar88kanishk** [comment]
Thanks @Douglasacost. Cheers!!

**Comment by kumar88kanishk** [comment]
> Cannot find "/dist/formik.umd.production.js" in formik@2.0.8

I get this when i visit the URI

**Comment by kumar88kanishk** [comment]
https://unpkg.com/formik@2.0.8/dist/formik.umd.production.min.js this is the correct uri but it gives me an error 

> connect.tsx:40 Uncaught TypeError: l is not a function

**Comment by YajanaRao** [comment]
I am getting the same issue with cdn
```
connect.tsx:40 Uncaught TypeError: s is not a function
    at x (connect.tsx:40)
    at FieldArray.tsx:374
    at formik.umd.production.min.js:1
    at formik.umd.production.min.js:1
```
