### ISSUE TITLE
Validation and showing errors.

### ISSUE THREAD

**Issue by domhede** [jaredpalmer/formik#147]
I would like to disable the submit button until all fields have been filled.  Once this has been done and the user clicks the enabled button I would then like to run the validation and display any errors. 

I have been trying to use the isValid prop to detect when the the form becomes valid but as the validation only runs on submit, I understand that the value won't update until then.  I could look into the values prop but as it is hard to distinguish what is a field I feel there must be an easier way.

Any help or ideas would be appreciated.  Thanks.

**Comment by domhede** [comment]
Update:
I found a temporary solution with a little lodash help.
const requiredKeys = ['firstName', 'lastName', 'emailAddress', 'phoneNumber'];
const formFilled = requiredKeys.every(key => keys(values).indexOf(key) !== -1);

Still not ideal..

**Comment by Andreyco** [comment]
I would do very similar...

```js
const requiredKeys = ['firstName', 'lastName', 'emailAddress', 'phoneNumber'];
const disabled = requiredKeys.some(key => !formValues[key])

<Button title="Submit" disabled={disabled} onPress={submitForm} />
```
`Array.prototype.some` iterates over array and stops as soon as first "truthy" value is returned.

Why is this and/or your's solution not ideal?
