### ISSUE TITLE
Creating a auto-save form

### ISSUE THREAD

**Issue by drydenwilliams** [jaredpalmer/formik#1472]
## ❓Question

I want to be able to use `withFormik` so I can use `mapPropsToValues` to build my form. When the user changes the form fields, I want to fire a debounced action to update these store values. How would I do this? The only thing I can see that runs `onChange` is the validate method.

I've seen the example of the `onChange` auto-save HOC for individual form fields. But just wondered why I would do this? Can I not just save the entire form after a debounce?

p.s I've tried asking on Spectrum an no luck so trying it on here 👍

**Comment by Andreyco** [comment]
You can use something like this.

```
class Autosave extends React.Component {
  saveInterval = undefined;

  componentDidMount() {
    saveInterval = window.saveInterval(this.saveValues);
  }

  componentWillUnmount() {
    window.clearInterval(this.saveInterval);
  }

  saveValues = values => {
    console.log(values);
    // save them
  };

  render() {
    return null;
  }
}
const FormPage = () => (
  <Formik initialValues={INITIAL_VALUES} onSubmit={onSubmit}>
    {formik => (
      <Form>
        <div>Form fields</div>
        <Autosave values={formik.values} interval={10000} />
      </Form>
    )}
  </Formik>
);
```

**Comment by drydenwilliams** [comment]
Thanks for this @Andreyco. Why is it better up update them at a field level rather than a form level?

**Comment by Andreyco** [comment]
I am not sure what you mean by "update at field level" so cannot give you proper answer.

**Comment by drydenwilliams** [comment]
Why is it better to wrap each field in an `AutoSave` HOC rather than doing it at form level?

**Comment by ar7casper** [comment]
@drydenwilliams 

The way I did it is adding `onBlur: autoSave`.
Where autoSave is - 
```
const autoSave = (e) => {
handleBlur(e);
submitForm();
}
```
Please note that doing so for inputs like checkbox is a bit problematic, the only way I found was - 
```
onChange: (list: string[]) => {
  form.setFieldValue('replies', e.target.checked, false);
  submitForm();
},
```

Please note the `false`, without it, this thing doesn't work, I don't know why, it fails on validation,  although there's none. 
Really confusing. 

But this should get you there.

**Comment by Andreyco** [comment]
@drydenwilliams in my example, there is auto save component at form level. It saves form data, not field data. Look closely ;)
