### ISSUE TITLE
How to call a function in onChange function along with the handleChange

### ISSUE THREAD

**Issue by abhiram5** [jaredpalmer/formik#1473]
**Here i want to call a function in onChange along with the handleChange is there any way call it.**                    

                     <Input type="select"
                                      name="test"
                                      id="test"
                                      valid={!errors.test}
                                      invalid={touched.test&& !!errors.test}
                                      required
                                      onChange={(e) => {
                                       handleChange;
                                        this.getAudioes(values)
                                      }}
                                      onBlur={handleBlur}
                                      value={values.test}  >
                  <Input type="select"
                                      name="test2"
                                      id="test2"
                                      valid={!errors.test2}
                                      invalid={touched.test2&& !!errors.test2}
                                      required
                                      onChange={(e) => {
                                       handleChange;
                                        this.getAudioes(values)
                                      }}
                                      onBlur={handleBlur}
                                      value={values.test2}  >

**Comment by riyueweiyi** [comment]
you can get handleChange in this.props, such as:
```ts
handleChange = (e) => {
    const { field: { onChange } } = this.props
    const promise = Promise.resolve(onChange(e))
    promise.then(() => console.log(this.props.form.values))
  }
```

**Comment by Andreyco** [comment]
```jsx
<Input
    onChange={(e) => {
        handleChange(e);
        this.getAudioes(values);
    }}
    ... 
/>
```

**Comment by rajeevbhosle** [comment]
how to do if we are using , {...formik.getFieldProps("abc")}

**Comment by johnrom** [comment]
You can wrap a function around onChange.

```jsx
const field = formik.getFieldProps('abc');
const onChange = React.useCallback(() => {
  console.log('other functionality');

  field.onChange(event);
}, [field.onChange]);

// override onChange from ...field
return <input {...field} onChange={onChange} />
```
