### ISSUE TITLE
Usage with semantic ui

### ISSUE THREAD

**Issue by tkvw** [jaredpalmer/formik#148]
Hello, 

I like to use formik, but I use Semantic ui which does not emit onChange=>(event), but onChange=(event,data). See this discussion: https://github.com/Semantic-Org/Semantic-UI-React/issues/638

Is it possible to support this?

**Comment by tkvw** [comment]
Btw, created a quick'n dirty hack for this: 
https://github.com/tkvw/formik/commit/d948afafb85b6ff6d2ed3598870aa41ac90d538d

**Comment by Andreyco** [comment]
You can create intermediate component which will handle these API inconsistencies for you.
It's very common to create wrapper component over base `input` component - makes refactoring, etc. very pleasant.

**Comment by tkvw** [comment]
That's correct, the event argument is of SyntheticEvent, but it does not have a target. So the default handleChange supplied by Formnik fails. I can't imagine how to create a Hoc for this, because it should overwrite behaviour of handleChange in the Formnik class. I can't update the state of this encapsulated component? 

The relevant quote from the discussion I've posted: 

> The event.target is a browser event property. However, many Semantic UI components, such as a Dropdown, Checkbox, and Radio do not work directly with native browser form controls such as input and select. They are built using stylized markup and custom internal state.

> Because of this, there are no native browser events available for certain callbacks. This is why all change events in Semantic-UI-React provide the event first (when available) but also a second argument which contains the data you need. You should never have to access the native browser event for most tasks.

So, the second argument contains all the relevant target data (actually, everything you are looking from in event.target).

**Comment by katpas** [comment]
Is there any further update on this? Semantic + Formik support would be great!

**Comment by jaredpalmer** [comment]
Use setFieldValue

**Comment by tkvw** [comment]
I am sorry, but I don't see how setFieldValue solves this issue?

**Comment by tkvw** [comment]
Actually, nevermind. I created a hoc for this: 
```
import React from 'react';
import {Formik} from 'formik';

export const semanticFormik = ({mapPropsToValues,...props}) => WrappedComponent => {
    let pristineValues;
    const keepPristineValues = (p)=>{
        pristineValues = mapPropsToValues(p);
        return pristineValues;
    }
    class Bridge extends React.Component{
        handleBlur(event,data){
            this.setValue(data);
        }
        handleChange(event,data){
            this.setValue(data);
        }
        setValue(data){
            if(data.name){
                this.props.setFieldValue(data.name,data.value);
                this.props.setFieldTouched(data.name,!this.isPristineValue(data.name,data.value));
            }
        }
        isPristineValue (fieldName,value){
            if(pristineValues[fieldName] === undefined){
                return value === '' || value === null || value === undefined;
            }
        }
        render(){
            const {handleChange,handleBlur,...props} = this.props;
            return <WrappedComponent 
                handleChange={this.handleChange.bind(this)} 
                handleBlur={this.handleBlur.bind(this)} 
                {...props}
            />;
        }
    }
    return Formik({mapPropsToValues:keepPristineValues,...props})(Bridge);
};
```

**Comment by katpas** [comment]
We wrote this change handler for the dropdown and then called it on change which worked. 
```javascript
const handleDropdownChange = (e, { name, value }) => setFieldValue(name, value)
```
Then called it: 
```jsx
          <FormikDropdown
            name="dueNumberOf"
            placeholder="2"
            value={values.dueNumberOf}
            onChange={handleDropdownChange}
            onBlur={handleBlur}
            errors={errors.dueNumberOf}
            options={createOptions(dueNumberOfValues)}
          />
```

**Comment by jaredpalmer** [comment]
nice!

**Comment by davidhenley** [comment]
Even with the above example and onBlur, I cannot get touched to call for the dropdown.
```
<Form.Dropdown
                    selection
                    name="type"
                    options={typeOptions}
                    value={values.type}
                    onBlur={handleBlur}
                    onChange={(e, { value }) => setFieldValue('type', value)}
                  />
```
Touched looks like:  { "": true }

**Comment by davidhenley** [comment]
@tkvw how do you use this wrapper? For example, how do I add an input and a dropdown while using this wrapper you wrote?

**Comment by tkvw** [comment]
@davidhenley : Sure, I created a simplified version at https://codesandbox.io/s/2022n8ol1r

**Comment by davidhenley** [comment]
@tkvw this doesn't account for touches. Dropdowns, Search, Inputs all have different ways they handle touches. With input onblur, you would need (e) => setFieldTouched(e.target.name, true), with dropdown onblur you need (e, { name }) => setFieldTouched(name, true), etc...

**Comment by davidhenley** [comment]
@tkvw neither of these take into account touches. On the first one it sets dirty and touched to false, when you set the value back to initial value. Touched should fire onBlur, which is different for Input, Dropdown, etc...

**Comment by davidhenley** [comment]
@tkvw both of these examples set touched and dirty back to false when you change back to initial values. Dirty and touched should stay true after you touch them.

**Comment by tkvw** [comment]
@davidhenley : this is just a pointer to a 'hocable' solution for using semantic ui with Formik. There's no magic, just implement (and extend) the logic as you wish and use the `withSemanticFormik` hoc on all your forms. And if you created a super-duper implementation, then please share 😄

**Comment by jaredpalmer** [comment]
just use `this.props.name` if  blur event doesn't provide `event.target.name` 👍

**Comment by misto** [comment]
There's one which implements some basic functionality: https://www.npmjs.com/package/formik-semantic-ui

**Comment by mvanlonden** [comment]
Created a simple `Field` wrapper
```
const SemanticField = ({ component, ...fieldProps }) => (
  <Field
    {...fieldProps}
    render={({
      field: { value, onBlur, ...field },
      form: { setFieldValue, setFieldTouched },
      ...props
    }) =>
      React.createElement(component, {
        ...fieldProps,
        ...field,
        ...props,
        ...(typeof value === 'boolean'
          ? {
              checked: value
            }
          : {
              value
            }),
        onChange: (e, { value: newValue, checked }) =>
          setFieldValue(fieldProps.name, newValue || checked),
        onBlur: (e, blurProps) =>
          blurProps ? setFieldTouched(fieldProps.name, blurProps.value) : onBlur(e)
      })
    }
  />
);
```
so you can just
```
<SemanticField
  name="name"
  component={Select}
  options={options}
/>
```
Should work for all semantic ui field components.

**Comment by gang89** [comment]
@mvanlonden how do you handle radio with the above wrapper? it cant seem to pass the value into the form state

**Comment by pixeltopic** [comment]
@mvanlonden For some reason if I backspace to the point where there is nothing on an input component, when using that wrapper I get a react [error.](https://media.discordapp.net/attachments/380509513863921674/529626640800546818/f0dc69cc1c0df3d89e65bc27dd8a3886.png)

`A component is changing a controlled input of type password to be uncontrolled.`

Otherwise, it works great. Do you know what might be the issue?

**Comment by Charchit26** [comment]
> @mvanlonden For some reason if I backspace to the point where there is nothing on an input component, when using that wrapper I get a react [error.](https://media.discordapp.net/attachments/380509513863921674/529626640800546818/f0dc69cc1c0df3d89e65bc27dd8a3886.png)
> 
> `A component is changing a controlled input of type password to be uncontrolled.`
> 
> Otherwise, it works great. Do you know what might be the issue?

@pixeltopic That happens when we do not give an initial value while specifying the `<Formik/>` tag.
Just specify the initial values as blank and it should work.
`<Formik  initialValues={{
            first_name: '',
            email_address: '',
            gender: ''
        }}  />`

**Comment by Charchit26** [comment]
> @mvanlonden For some reason if I backspace to the point where there is nothing on an input component, when using that wrapper I get a react [error.](https://media.discordapp.net/attachments/380509513863921674/529626640800546818/f0dc69cc1c0df3d89e65bc27dd8a3886.png)
> 
> `A component is changing a controlled input of type password to be uncontrolled.`
> 
> Otherwise, it works great. Do you know what might be the issue?

Replacing `value` in SemanticField wrapper with `value: value? value : ''` worked for me.

**Comment by boredchinese** [comment]
> > @mvanlonden For some reason if I backspace to the point where there is nothing on an input component, when using that wrapper I get a react [error.](https://media.discordapp.net/attachments/380509513863921674/529626640800546818/f0dc69cc1c0df3d89e65bc27dd8a3886.png)
> > `A component is changing a controlled input of type password to be uncontrolled.`
> > Otherwise, it works great. Do you know what might be the issue?
> 
> Replacing `value` in SemanticField wrapper with `value: value? value : ''` worked for me.

eslint didn't like it though `value: value || ''` seems to work fine

**Comment by eboutin** [comment]
For those who land here like I did a few days ago because they're struggling to make Formik and Semantic-UI React work together: I pieced together a working solution based on mvanlonden's solution:

[formik-with-semantic-ui-react-form](https://github.com/jabberbees/formik-with-semantic-ui-react-form)

Comments are welcome.

**Comment by mehrad77** [comment]
I don't want to use `withFormik`. isn't any other way of doing this?

**Comment by hoffmanilya** [comment]
@gang89 - based on the solutions from @mvanlonden and @eboutin I've come up with the following that seems to work with radio groups. I'm still testing this but so far, so good.

```
const SemanticField = ({ component, ...fieldProps }) => (
    <Field
        {...fieldProps}
        render={({
            field: { value, onBlur, ...field },
            form: { setFieldValue, submitCount, touched, errors, handleBlur },
            ...props
        }) =>
            React.createElement(component, {
                ...fieldProps,
                ...field,
                ...props,
                ...(component.name === 'FormRadio'
                    ? {
                        checked: fieldProps.value === value
                    }
                    : {
                        value: value ? value : ''
                    }
                ),
                ...((submitCount > 1 || touched[field.name]) && errors[field.name]
                    ? {
                        error: {
                            content: errors[field.name]
                        }
                    }
                    : {}
                ),
                onChange: (e, { value: newValue, checked }) =>
                    setFieldValue(fieldProps.name, newValue ? newValue : checked),
                onBlur: handleBlur
            })}
    />
);
```

```
<Form.Group grouped>
    <label>Role</label>
        <SemanticField name="role" value='admin' label='Admin' component={Form.Radio} />
        <SemanticField name="role" value='user' label='User' component={Form.Radio} />
</Form.Group>
```

**Comment by agrarian-systems** [comment]
@hoffmanilya thanks for your contribution. Just tried it today, it works great but one I check a Form.Checkbox, I can uncheck it but the value remains `true`. I'm sorry, I don't have enough experience to contribute on this but just wanted to mention it ;) Thanks to all of you.

**Comment by hoffmanilya** [comment]
@agrarian-systems - you can try the following. In my testing it works with both check boxes and radio groups.

```
const SemanticField = ({ component, ...fieldProps }) => {

    const { showErrorsInline, ...rest } = fieldProps

    return (<Field
        {...rest}
        render={({
            field: { value, onBlur, ...field },
            form: { setFieldValue, submitCount, touched, errors, handleBlur },
            ...props
        }) => {
            return React.createElement(component, {
                ...rest,
                ...field,
                ...props,
                ...(component === SemanticForm.Radio || component === SemanticForm.Checkbox
                    ? {
                        checked: component === SemanticForm.Radio ? fieldProps.value === value : value
                    }
                    : {
                        value: value || '' 
                    }
                ),
                ...((submitCount >= 1 || touched[field.name]) && errors[field.name]
                    ? {
                        error: showErrorsInline == false ? true : {
                            content: errors[field.name]
                        }
                    }
                    : {}
                ),
                onChange: (e, { value: newValue, checked }) =>
                    setFieldValue(fieldProps.name, newValue || checked),
                onBlur: handleBlur
            })
        }}
    />)
};
```

**Comment by agrarian-systems** [comment]
Works perfectly fine ! Even with Select and Dropdown.

**Comment by hoffmanilya** [comment]
@agrarian-systems - glad to hear it.

2. I don't use multiple drop-downs but you can probably create another condition that sets the field's value to an empty array if the component is a `Form.Dropdown` and `multiple` is set to true. From what I remember the default string value was necessary to properly handle `null` field values.

3. What kind of problems are you seeing with `FieldArray`?

**Comment by ghirlekar** [comment]
@agrarian-systems 

I made a slight change in your code. Any numerical field with initial value of 0 shows up as an empty string since value || '' captures 0 as a falsy value.
If you change `value: value || ''`, to `value: value ?? ''`, this fixes the issue.
