### ISSUE TITLE
Can statement "without the tears" be removed from the project description?

### ISSUE THREAD

**Issue by chachora** [jaredpalmer/formik#1485]
## ❓Question

Could you please edit the project description and remove "without the tears" statement in order not to give the false impression to the new users of the library? It's a joke, but seriously :)

**Comment by hedgerh** [comment]
If formik makes me cry, do i get my money back?

**Comment by kaueDM** [comment]
@hedgerh asking the real question here.

**Comment by selbekk** [comment]
Tears of joy amirite

**Comment by krazyjakee** [comment]
I vote for changing the word to "teers" as that is not currently a word afaik.

**Comment by ericaprieto** [comment]
what would be the false impression? 🤔
