### ISSUE TITLE
When is the V2 release planned? Can I use the V2 alpha version in the production environment?

### ISSUE THREAD

**Issue by Gzbox** [jaredpalmer/formik#1487]
Hi! Hello author, this is a great project, thank you very much. . May I ask if you plan to release the V2 version? Can I use the V2 alpha version in the production environment? Do you recommend this?

**Comment by Andreyco** [comment]
If I may speak up, v2 is in alpha stage as of now. What does it mean? v2 is not stable enough. Before releasing stable version, we will go thru beta stage.

**Should I use v2 in production?** Depends. If forms are mission critical to your product, don't. If you are in early stages where few bugs are okay and your development/deployment is lean enough, use it.

I would not use it in production where v1 is deployed already. I would use in alpha/beta stages of product though. 

**When will be stable v2 released?** Hard to tell, as soon as all known issues are resolved and v2 is tested enough.
