### ISSUE TITLE
Efficient way of using custom components

### ISSUE THREAD

**Issue by VladShcherbin** [jaredpalmer/formik#149]
Current way of passing props to custom form components is similar to this one:

```jsx
<Input
  name="username"
  label="Username or E-mail"
  errors={errors.username}
  touched={touched.username}
  onChange={handleChange}
  onBlur={handleBlur}
/>
<Input
  type="password"
  name="password"
  label="Password"
  errors={errors.password}
  touched={touched.password}
  onChange={handleChange}
  onBlur={handleBlur}
/>
```

This 2 inputs already need like 15 lines in editor. As you can see, we pass the same props to both of them -`errors`, `touched`, `handleChange` and `handleBlur`.

Is it somehow possible to automatically pass this props so we can reduce the code to something like this:

```jsx
<Input name="username" label="Username or E-mail" />
<Input type="password" name="password" label="Password" />
```

Same 2 inputs, but only 2 lines in editor. Maybe it's just me, but it's much easier to have small compact forms. 

One of possible solutions I can think of - a `Field` component, that gets all passed form props (via `context`?) and `Input` is a wrapper over this component.

Maybe there are other ideas/ways of solving this?

**Comment by VladShcherbin** [comment]
Seems like 0.9 (next) version will have this possibility, am I right?

**Comment by jaredpalmer** [comment]
@VladShcherbin Correct see the `<Field/>` component.

**Comment by VladShcherbin** [comment]
@jaredpalmer yeah, I'm trying the latest 0.9 alpha and it's working the way I wanted.

Thank you, will use 0.9 then.

**Comment by jaredpalmer** [comment]
@VladShcherbin Plan is to merge it to master next week.

**Comment by VladShcherbin** [comment]
@jaredpalmer great. Take all the time you need to polish it, I'm perfectly fine with using alpha for now.
