### ISSUE TITLE
More comprehensive examples of how to use Formik

### ISSUE THREAD

**Issue by tsongas** [jaredpalmer/formik#1496]
## 📖 Documentation
I don't think the official tutorial https://jaredpalmer.com/formik/docs/tutorial or demo https://codesandbox.io/s/zKrK5YLDZ show how to hide a form and display a thank you message upon successful submission. Of course I figured out one way to do this, but I have no idea whether there are best practices or a better pattern to follow. I'm curious about showing a thank you message in place of the form inside the current component, and/or redirecting the user and showing a Rails-style flash message.

Does anyone know if any of the resources https://jaredpalmer.com/formik/docs/resources show how to use Formik inside an app? Or can you suggest another resource?

**Comment by testinggithub1222** [comment]
I think so. I am trying to use formik but not sure much how should i use it properly. There is an example for onsubmit / handleonsubmit with withformik but there is not for onblur, onchange and so on. I am trying to use onblur and onchange but could not it working nor able to find any example out there.

**Comment by Andreyco** [comment]
Closing in favor of #1315 (and extending #1315)
