### ISSUE TITLE
Conditional required

### ISSUE THREAD

**Issue by Alecell** [jaredpalmer/formik#1498]
Hey guys, I try to figure out how to conditional required but I dont get how to do this and Im getting crazy, I have a form that have some inputs, but 2 of them is required only if the another isnt filled.

```
Yup.object().shape({
    Name: Yup.string()
      .min(3, "Quantidade de caracteres inválida.")
      .required("Este campo é obrigatório."),
    Email: Yup.string()
      .email("E-mail inválido")
      .required("Para prosseguir digite seu e-mail."),
    Telephone: Yup.string()
      .required("Este campo é obrigatório.")
      .min(14, "Quantidade de números inválida")
}),
```

The condition is on the telephone and e-mail, at least one of them should be filled, but not both required.

One important think is that I cant update the the yup repo and the formik. Im dealing with a pretty old project and if I update the dependencies so much think will break. The versions Im working on is Formik 0.11.11 and Yup 0.22.0.

**Comment by Steffi3rd** [comment]
Hi! I have the same problem. How did you solve that?

**Comment by Steffi3rd** [comment]
https://github.com/jaredpalmer/formik/issues/1512
