### ISSUE TITLE
ErrorMessage does not show validation error until lose focus

### ISSUE THREAD

**Issue by tonyhallett** [jaredpalmer/formik#1499]
### Current Behavior

My validation code is called, sets errors but ErrorMessage does not show the message

### Expected behavior

Is this by design ? ( can see that input has to be touched )

### Reproducible example

https://codesandbox.io/s/n1r51yk3om

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.4
| React            | 16.5
| TypeScript       | yes
| Browser          | any
| npm/Yarn         | what codesandbox uses
| Operating System | windows

**Comment by telenord** [comment]
in your code you can see error message only if type "error" in input, cause you validate like this: `     
   if (values.theError === "error") {
          errors.theError = "Houston....";
        }`

**Comment by tonyhallett** [comment]
@telenord That's right, it was intentional.  If I type 'error' then I validate that there is an error for theError value but the provided  error does not show in the ErrorMessage component until I tab away.  Is this by design ?

**Comment by telenord** [comment]
@telenord , i think,  cause `<ErrorMessage />` used touched prop of field, that fired after blur. You may use 
` {props.errors.theError ? <div>{props.errors.theError}</div> : null}` instead `<ErrorMessage />`

**Comment by tonyhallett** [comment]
@telenord by design then.  Thanks

**Comment by ctsstc** [comment]
This seems to also happen if you're using a promise for your validation (messages do not seem to come through until the blur event occurs on the input)(I whole different problem it seems, but same outcomes).

It would be nice if `ErrorMessage` supported a flag like `<ErrorMessage noTouch />`
