### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by naorye** [jaredpalmer/formik#1505]
### Current Behavior

I am using formik with redux. My submit is redux action that gets formikBag as a parameter and updates formik state (using redux-logic):
```
async function processFormikSubmit (deps, dispatch, done) {
    const { action } = deps;
    const { formikBag } = action.payload;

    formikBag.setSubmitting(true);
    try {
        const response = await doSubmit(deps, dispatch, done);
        dispatch(actions.setValue(response));
        formikBag.setStatus({ success: true });
    } catch (errors) {
        formikBag.setErrors(errors);
        formikBag.setStatus({ success: false });
    } finally {
        formikBag.setSubmitting(false);
    }

    done();
}
```
As a result to setValue action, the root component performs redirect to a different route. The redirect makes error in formik when `formikBag.setStatus({ success: true });` gets called:
```
index.js:1437 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Formik (at Login.js:58)
    in Login (created by ConnectFunction)
    in ConnectFunction (at Login.js:8)
    in Login (created by LoadableComponent)
    in LoadableComponent (at Router.js:63)
    in component (at ProtectedRoute.js:31)
```

### Expected behavior

Shouldn't show error.

### Reproducible example

https://codesandbox.io/s/ykyrqomkjz

### Suggested solution(s)

I beleive `formikBag.setStatus()` should check whether component is mounted before applying setState.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.4
| React            | 16.8.6
| TypeScript       | No
| Browser          | Chrome latest
| npm/Yarn         | npm
| Operating System | Mac

**Comment by armandooj** [comment]
Possibly a duplicate of #1449

**Comment by naorye** [comment]
@armandooj 
You right.. Didn't found it before.
Any idea what prevent this to be fixed? If I'll create a pull request, it will be approved?

**Comment by armandooj** [comment]
I've opened one (#1503) already!. I don't know how long it'll take for it to be reviewed, though.

**Comment by Andreyco** [comment]
Guys, closing this issue since it is duplicate.

**Comment by naorye** [comment]
@Andreyco  Any plans to merge #1503 ?

**Comment by Andreyco** [comment]
Sure, we need to do deep testing. Are you willing to test the PR in your project?

**Comment by naorye** [comment]
@Andreyco Currently my product is not running on production but I will definitely test this PR.
