### ISSUE TITLE
How to validate optional object, requiring all key?

### ISSUE THREAD

**Issue by Steffi3rd** [jaredpalmer/formik#1512]
Hello guys,

I have an object like this : 

```
 lastFunding={{
   year: "2000",
   amount: 22
}}
```

I would like to validate this with Formik and Yup.

this field `lastFunding` is optional, but If I filled of them (`lastFunding.year` or `lastFunding.amount`), I **the other one must be required**

`lastFunding.year` should be `string`
`lastFunding.amount` should be `number` 

How can I do that?

**Comment by Steffi3rd** [comment]
https://github.com/jaredpalmer/formik/issues/1498

**Comment by nicolas-besnard** [comment]
@Steffi3rd I think this is a `Yup` issue, not a `Formil` one 🤔

**Comment by jaredpalmer** [comment]
This is a Yup question. You can use .when or .test I believe. Going to close.
