### ISSUE TITLE
debounce in handleChange impossible?

### ISSUE THREAD

**Issue by xfishernet** [jaredpalmer/formik#1519]
## ❓Question

Seriously, for immediate help, just ask your question on the #formik channel on [Reactiflux](https://discordapp.com/invite/MbKwYuq).

**Comment by jaredpalmer** [comment]
Can you provide more information?

**Comment by xfishernet** [comment]
sorry already thought of a way: Formik -> Yup -> AddMethod -> lodash/debounce -> return Promise...

the code may have turned out a bit complicated, but it works.

**Comment by AbreezaSaleem** [comment]
it'll will be great if there was an example code for this.
