### ISSUE TITLE
Why the 1.4.4 version is the latest on NPM?

### ISSUE THREAD

**Issue by lourenci** [jaredpalmer/formik#1527]
## ❓Question

Hi, thanks for the library.

I've some questions about the formik versions that I didn't find out on the docs.

Why the 1.4.4 version is the latest version on NPM registry? It's the version installed when you add a library by `yarn add`.

Why both 1.4 and 1.5 are under development?

**Comment by jaredpalmer** [comment]
That’s weird. I issued a patch yesterday to 1.4 . It should not have been set to latest

**Comment by JayAndCatchFire** [comment]
1.4.4 and 1.5.6 (and probably a fair number of other versions) are being reported as "pre-release".  Not sure what that's all about.

**Comment by jaredpalmer** [comment]
Fixed

**Comment by jaredpalmer** [comment]
Fixed
