### ISSUE TITLE
[v2] enableReinitialize broken after 2.0.1-alpha.2

### ISSUE THREAD

**Issue by jaripekkala** [jaredpalmer/formik#1528]
### Current Behavior

`enableReinitialize` is not updating the `initialValues` anymore on change

### Expected behavior

2.0.1-alpha.2 https://codesandbox.io/s/formik-codesandbox-template-z5974

### Reproducible example

2.0.1-alpha.3 https://codesandbox.io/s/formik-codesandbox-template-scl9q
2.0.1-rc.0 https://codesandbox.io/s/formik-codesandbox-template-lgcrx

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.1-rc.0
| React            | 16.8.6

**Comment by Unrealman1** [comment]
can confirm I am experiencing the same issue

**Comment by jaripekkala** [comment]
I tried to figure this out after creating the issue and couldn't find anything obvious causing this issue. Could somebody else look into this who's more familiar with the codebase and recent changes?

However there is prior open issue that will block usage even if this gets fixed https://github.com/jaredpalmer/formik/issues/1523

**Comment by falldowngoboone** [comment]
#1523 is closed now.

**Comment by falldowngoboone** [comment]
Looks like the initial values ref (`initialValues.current`) is set as the default value for resetting the form on reinitialize. I'm thinking a new Formik state with the values set to `props.initialValues` should be passed to `resetForm` when the form is reinitialized.

**Comment by falldowngoboone** [comment]
Actually, `initialValues.current` should be set to `props.initialValues` before `resetForm` is set. Working on a fix right now.
