### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by TeoTN** [jaredpalmer/formik#1535]
### Current Behavior
When installing formik I get following warning:
```
warning formik > create-react-context > fbjs > core-js@1.2.7: core-js@<2.6.6 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
```
### Expected behavior
No warnings during installation

**Comment by Andreyco** [comment]
create-react-context was not updates in a while, not sure what should we do... probably fork and fix

**Comment by mvargeson** [comment]
It looks like some have started to not support above `create-react-context@0.2.2`.

https://github.com/FezVrasta/react-popper/commit/5c423ed2ee9d51511395cbbad734156d02541cbb
https://github.com/jamiebuilds/create-react-context/commit/a315c8c3ee2bd25538f5cc25d47e318f2dda5655
https://github.com/jamiebuilds/create-react-context/commit/392ef2b40a4a6239ff63131c03797b7607708040

I'm not sure I'd expect updates to this dependency anytime soon.

**Comment by Andreyco** [comment]
those PR's, lol

**Comment by gknapp** [comment]
[create-react-context](https://github.com/jamiebuilds/create-react-context) has recently been updated (0.3.0), removing the [fbjs dependency](https://github.com/jamiebuilds/create-react-context/commit/b04abbb240ad222abe30b58ef9a6242097aecdcb).

**Comment by noinkling** [comment]
The license was reverted to standard MIT in that version too, just so it's clear.

**Comment by ryansully** [comment]
This dependency was removed in https://github.com/jaredpalmer/formik/commit/e3876336aefa4ceb01e7f6f89cd12f8e133eb6ef, which is reflected in master currently as well as the next major release.

**Comment by sombreroEnPuntas** [comment]
Getting this with `"formik": "^1.5.2",`:
```warning formik > create-react-context > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

**Comment by mvargeson** [comment]
@sombreroEnPuntas Upgrading to the next major version (2.x) should fix that warning or at least it did for me. See [this comment](https://github.com/jaredpalmer/formik/issues/1535#issuecomment-519397011).

**Comment by sombreroEnPuntas** [comment]
@mvargeson but that's a major bump... Is it breaking the api? Or maybe the major bump on the version number does not follow standard version and it is still backward compatible? :)

**Comment by sombreroEnPuntas** [comment]
Indeed: https://github.com/jaredpalmer/formik/releases/tag/v2.0.1-rc.5  
It is nice to keep the majors alive for some time.  
But, can't fight progress! Will have to either drop the dependency or refactor.

**Comment by mvargeson** [comment]
@jaredpalmer and team do a pretty good job of tracking changes and keeping documentation up-to-date in my experience. They've even written a [guide for migrating from v1.x to v2.x](https://jaredpalmer.com/formik/docs/migrating-v2). It helped me to read through that to make the determination if I could and/or wanted to make the jump to v2.
