### ISSUE TITLE
initialValues not resetting the form to the same values twice

### ISSUE THREAD

**Issue by AndreiBru** [jaredpalmer/formik#1541]
### Current Behavior

Context: Inside a Form with `enableReinitialize` set to true.

Changing `initialValues` programatically will reset the form to the values you give it. Afterwards if you make manual changes to the form through the UI and try to reset `initialValues` to *the same* (this bit is important) values you set it last time, the form will not reinitialize with the given values.

### Expected behavior

The form should always reinitialize when `initialValues` changes, even if to the same thing as it was last time.

### Reproducible example

https://codesandbox.io/embed/formik-codesandbox-template-0yvh9

### Suggested solution(s)

Did not take much time to look at this, but I think an easy fix can be done by removing this condition `!isEqual(prevProps.initialValues, this.props.initialValues)` from `src/Formik.tsx line 114` might do the trick. Again, this is not properly researched.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.4.1
| React            | 16.6.1
| TypeScript       | -
| Browser          | Chrome Version 73.0.3683.103 (Official Build) (64-bit)
| npm/Yarn         | npm 6.4.1
| Operating System | macOS Mojave 10.14.2

**Comment by jaripekkala** [comment]
What's the use case for this? IMO the current behavior is correct.

**Comment by AndreiBru** [comment]
@jaripekkala Whenever you want to programatically reset a form to a specific (same) state more than one time.

**Comment by jaripekkala** [comment]
You can actually just reset the form programatically.

```jsx
<button
  type="button"
  onClick={() =>
    props.resetForm({
      a:
        "This only works for the first time, the 'Reinit' button will not act upon the field again"
    })
  }
>
  Reinit
</button>

```

**Comment by AndreiBru** [comment]
You're right, my bad... I may have been trying to use the wrong method for achieving my results. Closing for now until I test, will reopen if I'll need to.

Thanks @jaripekkala
