### ISSUE TITLE
Is it possible to perform more validation after validationSchema, Yup, is passed?

### ISSUE THREAD

**Issue by fetatefog** [jaredpalmer/formik#1544]
Currently, I am doing some validation such as min length, max length, required and so on using Yup in combination. I wonder if i could perform some more validation which need request and response from server side after Yup validation is passed?

For example, i need a valid phone number format to be input first and after validate is passed, then I want to request to my backend to check if this phone number is existed. In case if it is already existed, then just set errors.phone: "Phone number is already registered." and show it inside ui using `{touched.phone && errors.phone && <p>{errors.phone}</p>}`. Please help give me some idea how to solve this.

**Comment by Andreyco** [comment]
Sure, check async validations in docs

**Comment by fetatefog** [comment]
@Andreyco , i could not find a specific doc. Would you mind help give me the link?
