### ISSUE TITLE
touched arrays

### ISSUE THREAD

**Issue by marcstreeter** [jaredpalmer/formik#1545]
## 🐛 Bug report
Array fields are not appearing in the touched object.
### Current Behavior
when interacting with a selection of checkboxes, the `touched` object never reports any changes.

### Expected behavior

for `array().of()`  fields to appear in the `touched` object so that I can do stuff.

### Reproducible example

https://codesandbox.io/s/formik-checkbox-example-zcztz

### Suggested solution(s)

Not sure.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | ^1.3.1
| React             | ^16.8.6
| Yup                |  ^0.27.0
| Browser         | Brave
| npm/Yarn      | npm
| Operating System | Mojave

**Comment by marcstreeter** [comment]
I updated to 1.5.7 and the issue still persists.

**Comment by Andreyco** [comment]
How about v2?

**Comment by marcstreeter** [comment]
ooo I hadn't even thought of that.  I went to the codesandbox above and updated it with the changes necessary. Issue still persists 😭

**Comment by Andreyco** [comment]
See this updated example https://codesandbox.io/s/formik-checkbox-example-96miz
Yup was not working for me, I remove it altogether.
