### ISSUE TITLE
[v2] Implement registration via useLayoutEffect

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/formik#1547]
Ryan Florence shared a better way of doing parent-child registration via useLayoutEffect(). We can use this to register mounted fields more accurately. With concurrent mode, order is definitely not guaranteed at all, but knowing presence is possible.

**Comment by joepuzzo** [comment]
A better way to do this is in a use state 

```
  useState(()=> {  
    // Initial Register code here
  });
```

**Comment by joepuzzo** [comment]
Its like having your very own constructor but in a functional component :)

**Comment by jaredpalmer** [comment]
We don't use local state here. We need to register the descendant `<Field>` / `<useField>` with the parent

**Comment by joepuzzo** [comment]
Yes thats what im saying ! By putting a function into `useState` as the initial value you get a "constructor" that executes before render lol

**Comment by joepuzzo** [comment]
So not state! its just a neat trick to achieve registration before render.

**Comment by FredyC** [comment]
I agree with @joepuzzo. The `useLayoutEffect` is not intended for such hacks.

**Comment by viniciusdacal** [comment]
There's is the unregistering and also the "re-registering" cycles, which couldn't be covered by `useState(() => {})`. Splitting these logics between setState and useLayoutEffect could be confusing. 
I would sticky with `useLayoutEffect` in that case

**Comment by viniciusdacal** [comment]
btw, If there's an agreement, I could give it a shot.
