### ISSUE TITLE
[v2] useFormik returns undefined values

### ISSUE THREAD

**Issue by rafaelalmeidatk** [jaredpalmer/formik#1548]
### Current Behavior

`useFormik` is returning `undefined` for the values object:

```
const formik = useFormik({
  initialValues: { user: 'test' }
});

console.log(formik.values); //> logs undefined
```

But for some reason, it is not happening when this code is running in the server (SSR). When running on the server, the function returns the correct value but as soon as the code runs in the browser, `values` is set to `undefined` again.

![image](https://user-images.githubusercontent.com/11896398/58362084-a071f700-7e69-11e9-875b-f4d37ecf0cdd.png)

This was tested on CRA 3.0.1 and Next 8.1.0. I cannot reproduce this on CodeSandbox.

### Expected behavior

`formik.values` should be consistent and output `{ user: 'test' }`.

### Reproducible example

Live demo: https://formik-nextjs-jgkhfsskwe.now.sh/ (refresh the page and see the value coming from the server and then being overridden by the client)
Code: https://zeit.co/rafaelalmeidatk/formik-nextjs/jgkhfsskwe/source?f=pages/index.js&host=formik-nextjs-jgkhfsskwe.now.sh

### Suggested solution(s)

This started on version `2.0.1-alpha.51`, I suspect it was due to 902a40aeaab7de4f41d20e485f96bf1e215caf48. Version `2.0.1-alpha.5` works.
Maybe there is something going on the production build of the lib because it works fine if I try to run it locally in development mode or use the dev files instead of the production ones.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.1-rc.0
| React            | 8.1.0
| TypeScript       | -
| Browser          | Chrome 69.0.3497.100
| npm/Yarn         | yarn 1.15.2
| Operating System | 69.0.3497.100

**Comment by rafaelalmeidatk** [comment]
Oops duplicate of #1523, sorry 😅
I will add my info there

**Comment by klimashkin** [comment]
@rafaelalmeidatk Sorry for a sloppy question, but is there a place with 2.0 docs, where useFormik is described?

**Comment by rafaelalmeidatk** [comment]
@klimashkin not yet, as far as I know. I gathered some pieces of code from the comments here #1063, read the source code and tried different things until it worked. I don't know everything about v2 but I may try to create some documentation if I find some time.

**Comment by danielmainamwatha** [comment]
same thing bugging me.
