### ISSUE TITLE
Low priority validation causing problems

### ISSUE THREAD

**Issue by FredyC** [jaredpalmer/formik#1560]
### Current Behavior

Basically, when values are modified with `setValues`, it won't trigger the validation and causes inconsistent outcome - validation errors are still shown despite valid values entered.

### Expected behavior

Setting values imperatively should probably be a high priority validation.

### Reproducible example

https://codesandbox.io/s/zen-hoover-p66mv

* focus & blur one of the fields to show error
* click autofill button
* error is still shown despite the valid value

Downgrading to RC-1 fixes it.

**Comment by rohitkrai03** [comment]
I am facing this issue as well. @jaredpalmer Is there an ETA on this?

**Comment by FredyC** [comment]
The current workaround is to call `formik.validateForm` after the `formik.setValues` to execute high priority validation. Here is a modified example that shows it... https://codesandbox.io/s/elastic-poincare-6fr2l

**Comment by jaredpalmer** [comment]
I really wish I never added validation as a side effect of the setXXX methods.

The current workaround as @fredyc would be to avoid validation on setValues and trigger it imperatively. 

@FredyC what would the ideal API look like? Do we need to expose `validateFormWithLowPriority()` and `validateFormWithHighPriority()`? Also note, that we also have #1526 and could introduce `debouncedValidateForm()`

**Comment by jaredpalmer** [comment]
I've messaged some React team members about this and will report back with a suggested solution.

**Comment by FredyC** [comment]
@jaredpalmer I think I've found the culprit...

https://github.com/jaredpalmer/formik/blob/3c8658850f4cd5b26588a8b174da5bb39817ca03/src/Formik.tsx#L463

You are using `state.values` which is not up to date yet (React does that later). You need to use values you have in argument :)

Btw, `validateFormWithHighPriority` is already exposed as `validateForm`, but it's far from ideal because if you forget to pass new values, it's the same problem and validating against old values.

**Comment by jaredpalmer** [comment]
@FredyC that makes sense.

**Comment by jaredpalmer** [comment]
perhaps only handleChange and handleBlur should be low-priority.

**Comment by FredyC** [comment]
Well, I don't think it's a problem to have low priority here, it just needs to validate against new data.

**Comment by viniciusdacal** [comment]
Anyone working on this? I could give it a shot if you don't mind.

**Comment by frantic1048** [comment]
Encountered same issue  with `setFieldValue()`, and I found `setFieldValue()` also uses `validateFormWithLowPriority` to trigger validation :thinking: 

version: 2.0.1-rc.13
