### ISSUE TITLE
[v2] Could not found Formik.d.ts & Form.d.ts

### ISSUE THREAD

**Issue by otofu-square** [jaredpalmer/formik#1562]
### Current Behavior

Can't import `Formik`, `useFormik`, `Form` in formik@2.0.1-rc2 because It seems `Formik.d.ts` is not included in `dist` folder.

![image](https://user-images.githubusercontent.com/10118235/58610478-83647a80-82e6-11e9-8911-daf6d6a5d9e3.png)

![image](https://user-images.githubusercontent.com/10118235/58610501-9f681c00-82e6-11e9-9304-ae32187a6bed.png)

### Expected behavior

Can import them.

### Reproducible example

- `$ yarn add formik@next`
- see `node_modules/formik/dist`

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.1-rc2 |
| React            | 16.8.6 |
| TypeScript       | 3.5.1 |
| Browser          |  |
| npm/Yarn         | yarn |
| Operating System | MacOS |

**Comment by jaredpalmer** [comment]
Investigating

**Comment by jaredpalmer** [comment]
Try the latest releases

**Comment by otofu-square** [comment]
Thanks for your quick response!!
