### ISSUE TITLE
V2 Formik Provider not being updated with new values on reinitialize

### ISSUE THREAD

**Issue by outerlook** [jaredpalmer/formik#1565]
### Current Behavior

Hi! Passing different initialValues won`t update the provider even with enableReinitialize=true.
Am I missing something?

### Expected behavior
When I change initialValues, I expect a "dirty = false" with the new values, for example when I update a form then ask my server to refetch data.

### Reproducible example

[Here's the sandbox](https://codesandbox.io/s/formik-codesandbox-template-u5r5w)

Using variable name as state of my component.

Formik initiate with current state

I put a button that will directly update the state to a new name "John".

When the button triggers, the component updates with new state but formik props won't change.

Am I missing something simple? Sorry if I am. Thanks in advance

### Your environment

| Software         | Version(s) |
Reproduced on Sandbox with
![image](https://user-images.githubusercontent.com/12937160/58647781-a9861c80-82de-11e9-8831-f1302537dd19.png)

**Comment by falldowngoboone** [comment]
Possibly same as #1528

**Comment by outerlook** [comment]
Yes, it is. Missed this open issue, sorry 😅
