### ISSUE TITLE
calling `executeSubmit` on a ref of `Formik` does not increment the `form.submitCount`

### ISSUE THREAD

**Issue by mlg87** [jaredpalmer/formik#1568]
### Current Behavior

This is a weird edge case that I imagine most people don't come across, but I did since the form in question doesn't actually ever get _submitted_. When calling `form.current.executeSubmit()` on a ref of a form the `form.submitCount` passed as a render prop to `Field`s doesn't increment. However, calling `form.current.handleSubmit` on the same ref will increment the `submitCount`.

### Expected behavior

When calling `executeSubmit` on a ref of a `Formik` component, the `submitCount` will be incremented accordingly.

### Reproducible example

https://codesandbox.io/s/formik-codesandbox-template-vxfzk?fontsize=14

### Suggested solution(s)

Haven't looked at source for this, but make sure that `executeSubmit` calls the same methods as `handleSubmit`

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.7
| React            | 16.8.1
| TypeScript       | 3.4.5
| Browser          | Chome
| npm/Yarn         | Yarn 1.15.2
| Operating System | MacOS 10.14.5

**Comment by jaredpalmer** [comment]
This isn't part of the public API.

**Comment by jaredpalmer** [comment]
but anyways, I think you just want `ref.current.submitForm()`

https://codesandbox.io/s/formik-codesandbox-template-kkmkk

**Comment by jaredpalmer** [comment]
`executeSubmit` just handles actually passing values to your `onSubmit` fn. the actual logic for submission lives in `submitForm`.
