### ISSUE TITLE
FastField multiple rerenders of on official documentation code

### ISSUE THREAD

**Issue by bologer** [jaredpalmer/formik#1576]
### Current Behavior

FastField seems to be rerendering the whole form and items inside as I can see from React inspector "Highlight changes".

I have checked related isues, they were closed, but I copied example from documentation and it does not seem to be working as described. See [this codesandbox](https://codesandbox.io/s/hd0ir).

### Expected behavior

I expect that only field which I type in should be rerendered. 

### Reproducible example

https://codesandbox.io/s/hd0ir

I used example from official docs: https://jaredpalmer.com/formik/docs/api/fastfield#example

### Your environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.7 
| React            | 16.8.6
| TypeScript       | -
| Browser          | Chrome
| npm/Yarn         | npm
| Operating System | Ubuntu

**Comment by Andreyco** [comment]
duplicated of #1550
