### ISSUE TITLE
Use __DEV__ constant

### ISSUE THREAD

**Issue by Andreyco** [jaredpalmer/formik#1577]
## 🚀 Minor codebase update

Use `__DEV__` constant instead of `process.env.NODE_ENV === 'production'`

Do this change agains `next` branch

**Comment by jaredpalmer** [comment]
This broke React Storybook. I think we need to alter the webpack config?

**Comment by gunn4r** [comment]
I can do a PR to fix this. I got it working locally right now.

**Comment by gunn4r** [comment]
Opened and issue #1607 and a PR #1608.

👍 :)
