### ISSUE TITLE
Wizard - MultiStep form

### ISSUE THREAD

**Issue by arash87** [jaredpalmer/formik#1581]
## ❓Question
I use the wizard example and I have a question regarding the navigation to next page.
I think its great that Wizard component has a management responsibility and controls the steps.
The example works great as long as I need to have a Next button on each page, but how would I go about if one page consist of a single dropdown and I would like to move to the next page once user has selected a value? 

I could ofcourse pass down next() method to the specific Wizard.Page by doing a cloneElement of that particular child, but then i also must pass down current values so to use it in next()  as parameter.

**Wizard.js**
```javascript
 ....
 next = values => 
        this.setState(state => ({
            page: Math.min(state.page + 1, this.props.children.length - 1),
            values
 }))
 render(){
        const {children} = this.props
        const {page, values} = this.state
        const activePage = React.cloneElement(React.Children.toArray(children)[page], {onNext : this.next, values}) 
        const isLastPage = page === React.Children.count(children) - 1
        return (....)
```

**Wizard.page**
```javascript
const StepForm1 = props => {
   const onClick = () => props.onNext(props.values)
   return(
         <Wizard.Page>
            //a select element
         </Wizard.Page>
)
}
```

This just does not seem like a right way to do it - any suggestions on this topic?

**Comment by Andreyco** [comment]
1. This has been discussed several time before, please, go thru other issues.
2. New examples are in the making, multistep forms among theme

closing in favour of #1315
