### ISSUE TITLE
resetForm not triggering field onChange

### ISSUE THREAD

**Issue by aximili** [jaredpalmer/formik#1584]
## ❓Question

Apparently when you reset a form, it doesn't automatically trigger field onChange.

See this example:
https://codesandbox.io/s/formik-example-sgdfn
(Type in an email address then click Reset, as opposed to emptying the field using keyboard Backspace)

Is there any way to make resetForm call all field onChange?

**Comment by jaredpalmer** [comment]
You are storing form state (values) outside of Formik. In Formik, and in React in general, trying to store the same state in 2 places will not work. Instead, you should apply this value transformation prior on the string passed to setFieldValue. There is no need for name/setName.

**Comment by jaredpalmer** [comment]
Change handlers will not be called on reset but you can pass resetForm an object with new values to be used for the next initial values. You could apply any transformations on this object.

**Comment by aximili** [comment]
Thanks a lot @jaredpalmer for your reply.

Then how would you change a state outside Formik based on the form value? (Please forgive me if I didn't fully understand)

A real-life example is a credit card form, where the length of the CVV can be 3 or 4 depending on the card number, so the validation needs to be updated accordingly. 

So we could have a custom onChange event on the card number field, that determines the card type, and update the expected CVV length (or even showing the right card logo). But how do you reset these states on form reset?

**Comment by aximili** [comment]
Well I guess the answer is you can't, right? So you have to handle resetting the states separately. Ok that's fine, thanks again Jared!

**Comment by MaheshSuranga** [comment]
> ## ❓Question
> 
> Apparently when you reset a form, it doesn't automatically trigger field onChange.
> 
> See this example: https://codesandbox.io/s/formik-example-sgdfn (Type in an email address then click Reset, as opposed to emptying the field using keyboard Backspace)
> 
> Is there any way to make resetForm call all field onChange?

With the resetForm trigger you can set the state separately especially form values. then formik form will automatically trigger the validations. `resetForm: (nextState?: Partial<FormikState<Values>>) => void`

see the API reference here in [formik doc] (https://formik.org/docs/api/formik#resetform-nextstate-partialformikstatevalues--void)
