### ISSUE TITLE
EnableReinitialize doesn't reinitialize status

### ISSUE THREAD

**Issue by Unrealman1** [jaredpalmer/formik#1587]
### Current Behavior
prop EnableReinitialize  from FormikConfig doesn't reinitialize status 
even if wrapping component changes "intialStatus" passed to Formik;

### Expected behavior
if prop EnableReinitialize is true then Formik should update it's "status " prop passed to connected components on "initialStatus" prop change

### Reproducible example
https://codesandbox.io/s/formik-doesnt-reinitialize-status-6wk7i

### Additional context
Status is a very convenient way to pass Options to select fields or let's say form level "readOnly".
Maybe I am miss using Formik "status"?
well as of now there is a workaround like this one inside render method which of course breaks react rules of setState calls and produces as expected a warning "Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state."

`if (!isEqual(status, initialStatus)) {
             setStatus(initialStatus);
 }`

I am not sure if it is actually a bug or expected behavior?

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.7
| React            | 16.8.6
| TypeScript       | 3.5.1
| Browser          | firefox
| npm/Yarn         |
| Operating System | windows 10

**Comment by shulcsm** [comment]
Bump.
Encounting same issue on 2.0.1-rc.6

**Comment by niksya** [comment]
Facing same issue.

**Comment by Unrealman1** [comment]
https://codesandbox.io/s/twilight-glitter-62o9k
