### ISSUE TITLE
Empty field is not in 'values'

### ISSUE THREAD

**Issue by lroellin** [jaredpalmer/formik#1588]
## 🐛 Bug report

We have a field (text) that may be empty. When it is empty, it is not in the `values` state of Formik and therefore also not in the `values` argument to the `handleSubmit` function.

### Current Behavior

With value: 
![image](https://user-images.githubusercontent.com/3150983/59118756-4127e280-8951-11e9-91b3-5b38d5c8fe5e.png)

With empty value:

![image](https://user-images.githubusercontent.com/3150983/59118868-93690380-8951-11e9-96fe-db88baa7ba1a.png)

### Expected behavior

The field is included (with an empty value).

### Reproducible example

No time yet, if this is required to understand the issue, I'll gladly provide it.

### Suggested solution(s)

The field is included (with an empty value).

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.2
| React            | 16.8.6
| TypeScript       | 3.3.3
| Browser          | Chrome Version 74.0.3729.169 (Official Build) (64-bit)
| npm/Yarn         | Yarn 1.16.0
| Operating System | macOS 10.14.4

**Comment by johnrom** [comment]
did you provide this empty value to `initialValues`?

**Comment by lroellin** [comment]
This form is used for creating and editing.

* When creating, the value is in `initialValues` but empty
* When editing, the value is in `initialValues`, either empty or the last set value

So in both cases, the value is in `initialValues`.

**Comment by johnrom** [comment]
I'm signing off, but creating a sandbox will help us to see the issue more quickly. The default sandbox template has an empty string where the value comes through the props. Are you able to replicate the issue there?

https://codesandbox.io/s/91q6rxmmrp

If you set it to `undefined`, it will _not_ be in the prop. Is that the issue you're seeing?

**Comment by lroellin** [comment]
Ok I've managed to *not* replicate it: https://codesandbox.io/s/formik-codesandbox-template-yp9uu

I'll check if any of our onChange code does something weird.

**Comment by jaredpalmer** [comment]
What’s the bug? Here? You have to initialize all fields in initialValues

**Comment by lroellin** [comment]
Yes, it works now. I'm just curious why our onChange handler let the value disappear. I now see that this could evaluate to undefined in certain situations, so the bug is fixed.
