### ISSUE TITLE
handleBlur('name') ignoring 'name' and giving warning

### ISSUE THREAD

**Issue by brunolemos** [jaredpalmer/formik#1592]
### Current Behavior

```
formik.esm.js:747 Warning: Formik called `handleBlur`, but you forgot to pass an `id` or `name` attribute to your input:

    <input placeholder="Your Name" autocapitalize="sentences" autocomplete="on" autocorrect="on" dir="auto" spellcheck="true" type="text" data-focusable="true" class="css-textinput-1cwyjr8 r-backgroundColor-14lw9ot r-borderColor-11u4nky r-borderWidth-rs99b7 r-height-1iud8zs r-paddingHorizontal-1pn2ns4 r-width-13qz1uu" value="aa">

    Formik cannot determine which value to update. For more info see https://github.com/jaredpalmer/formik#handleblur-e-reactfocuseventany--void
```

Also, I notice the `touched` object gets a `undefined` field:

```json
"touched": {
  "undefined": true
},
```

### Reproducible example

Official RN example: https://snack.expo.io/@jaredpalmer/basic-formik-x-react-native-example

```jsx
<TextInput
  onBlur={formikProps.handleBlur('xxx')}
  ...
/>
```

### Suggested solution(s)

Investigate regression, release a patch fix to npm

### Additional context

React Native Web

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.7
| React             | 16.8.6
| React Native  | 0.59.8
| TypeScript       | 3.5.1
| Browser          | Chrome latest
| npm/Yarn         | Latest
| Operating System | macOS

**Comment by jaredpalmer** [comment]
Yah am for the big report.

**Comment by jaredpalmer** [comment]
I'm struggling to reproduce this one on expo snack. I wonder if this has to do with React Native Web. Any chance you can take a screen recording of this bug?

**Comment by brunolemos** [comment]
> I wonder if this has to do with React Native Web.

Maybe. Copied the example to this CodeSandbox, you can see the console: https://codesandbox.io/s/issue-react-native-for-web-6s9zd?fontsize=14

Good news is that it seems to work correctly on v2.

**Comment by jaredpalmer** [comment]
fixed in v2

**Comment by johnneuland** [comment]
I still got this error today when I tried to fix this problem by replacing onBlur like this: ```onBlur={(fieldType)=>handleChange(fieldType)}``` https://stackoverflow.com/questions/63686646/stop-handleblur-from-doing-anything. Relevant codesandbox: https://snack.expo.io/@nhammad/jealous-beef-jerky
