### ISSUE TITLE
Allow handleSubmit to optionally return a promise and call setSubmitting automagically

### ISSUE THREAD

**Issue by amankkg** [jaredpalmer/formik#160]
Simple example from docs:
```javascript
  err => {
    setSubmitting(false);
    setErrors(err);
  }
```
For now we have few _separate_ setter functions (like `setErrors`, `setStatus`, etc.), each with simple notation `f(params) => void`. API docs says that it is an imperative way to manage _formik's inner state_. And I think of them as a set of _setState callbacks_ where each one updates it's own _portion of formik state_. This **way of thinking** conflicts with example above - when you have to call multiple _setter callbacks_ in a row (finally, we're not executing React's setState this way).

More idiomatic api may look like this:
```javascript
    setSubmitting(false)
      .then(() => setErrors(err));
```
Or React-way callback:
```javascript
    setSubmitting(false, () => setErrors(err))
```
But the simplest one still would be a plain `f(params) => void` function for the whole state:
```javascript
    setFormikState({ isSubmitting: false, errors: err })
```
Also, this way we can skip extra re-render.

**Comment by Andreyco** [comment]
Hi there.

First of all, API you proposed exposes Formik's internals - you have to know state keys (`isSubmitting`, `errors`, etc.) precisely. Typos in state keys would just "break" Formik's functionality.

Encapsulating those state keys into setter methods makes code less error prone. Also, Typescript and/or Flow help you those APIs.

Personally, I prefer using existing self describing setter methods over universal state setter. 

What's yout use case for async, promise-like, setters?

**Comment by VladShcherbin** [comment]
I like this idea, not sure about the method name though:

```js
setSubmitFinished(errors?)

setSubmitFinished() // update isSubmitting to false, remove submit errors
setSubmitFinished({ name: 'Required'}) // update isSubmitting to false, add provided errors
```

It'll be also great if there was a way to work with promises like this:

```jsx
handleSubmit(values) {
  return doApiCall(values)
    .then(response => console.log('success'))
    .catch(e => transformErrors(e))
}
```

**Comment by Andreyco** [comment]
> ```js
> setSubmitFinished(errors?)
> 
> setSubmitFinished() // update isSubmitting to false, remove submit errors
> setSubmitFinished({ name: 'Required'}) // update isSubmitting to false, add provided errors
> ```

I find setter name and its functionality bit confusing.
How about two method instead?

```jsx
handleSubmit = async (values) => {  
  try {
    await doApiCall(values);
    setSubmitFinished()
  } catch (errors) {
    setSubmitFinishedWithErrors(errors)
  }
}
```

**Comment by VladShcherbin** [comment]
@Andreyco yes, I'm also confused with a function name. I'd prefer `stopSubmit` or similar.

As per two methods - I don't think this separation is necessary since in both examples it's used for exactly the same thing (set `isSubmitting` flag, set submit `errors`).

The only difference is the errors object - empty when no errors or not empty with provided errors. See:

```js
handleSubmit = async (values, { setSubmitFinished }) => {  
  try {
    await doApiCall(values);
    setSubmitFinished() // isSubmitting = false, errors = {}
  } catch (errors) {
    setSubmitFinished(errors) // isSubmitting = false, errors = {...errors}
  }
}
```

**Comment by amankkg** [comment]
@Andreyco 
> What's yout use case for async, promise-like, setters?

Just to convey a concept, not real case. Since current api feels too imperative.

> API you proposed exposes Formik's internals

Fair point. But still, we can validate passed object's shape and with TS/Flow it would be easier too. If so, new api will be just very similar to (but not exposing 😉) Formik's internal state.

Tbf, when I first read api docs I thought that this is what `setStatus` is for.

@VladShcherbin 

`setSubmitFinished(errors?)` or `stopSubmit(errors?)` seems pretty practical... but still kinda incomplete, inconsistent with rest of FormikBag api.

**Comment by jaredpalmer** [comment]
@eonwhite and I have discussed this multiple times offline. `setFormikState(state: any)` is too big of an escape hatch in our opinion. Think about it: `<Child setThingState={this.setState} />` is a code smell.

**Comment by jaredpalmer** [comment]
I think I have a way for us to automatically call setSubmitting. Stay tuned

**Comment by dudunato** [comment]
Any idea on how to achieve this?

**Comment by jaredpalmer** [comment]
i think this is a good idea. will explore next week

**Comment by abumalick** [comment]
Did you have the change to explore the idea @jaredpalmer ?

The bad bot is trying to close the issue 🔨

**Comment by sgrannan** [comment]
@jaredpalmer any update on this?

I was really looking for something to solve this issue and the flow of this seems logical: `async (values) => { if (good) return; else throw errors; }`

Please advise.

**Comment by n9** [comment]
... just to remove stale.

**Comment by mahatosourav91** [comment]
... just to remove stale.

**Comment by jaredpalmer** [comment]
This exists in v2
