### ISSUE TITLE
[v2]  <Formik /> `ref` prop

### ISSUE THREAD

**Issue by peterwiebe** [jaredpalmer/formik#1603]
### Current Behavior

Since switching `<Formik />` to a function component if you try to attach a ref to it as such:
```js
<Formik ref={myRef} /> 
```
you will get the following error:
`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

### Desired Behavior

The desired behaviour is for there to be no error and the ref to provide a set of APIs to programmatically interact with `<Formik />`.

### Suggested Solution

To enable the functionality it seems that the hook `useImperativeHandle` will be needed to wrap `<Formik/>` and expose the available methods.

```
export const Formik = forwardRef((props, ref) => {
  const formikRef = useRef()
  useImperativeHandle(ref, () => ({
    submitForm: () => handleSumbit()
  })
  
  return (
    <FormikProvider ref={formikRef} value={formikbag}>
      {...}
    </FormikProvider>
  )
})
```

An example per the [docs](https://reactjs.org/docs/hooks-reference.html#useimperativehandle)

### Who does this impact? Who is this for?

This is for anyone who needs to implement any programmatic functionality on <Formik />.

### Describe alternatives you've considered

Use the prior version where <Formik /> is a class component.

### Additional context

I was trying to implement the debounced autosave that was handled by the parent component, without the need for a specific component that is a child of <Formik />.

**Comment by ComLock** [comment]
I guess this applies to withFormik aswell?

I have two forms similar to:
https://codesandbox.io/s/formik-multiple-form-in-one-submission-kbf1w?fontsize=14

I would like to make a reset button that runs formik.resetForm() on both forms.

I can get a reference to the withFormik react node, but not child which is the actual Formik react node (which I'm guessing provides the formikBag API I need).

Ideas?

**Comment by tsuby** [comment]
Have you made any progress with this? I'm facing a similar problem.

**Comment by sky-fin** [comment]
I managed to get this to work by passing in the ref as a propery.
`  const formikForm = useRef(null); //in parent`
`<RfpForm  formikFormRef={formikFormRef} ></RfpForm> // in parent`


```
const RfpForm = (withFormik({ enableReinitialize: true})((props, values) => {
  useImperativeHandle(props.formikFormRef, () => ({
    autoSave: () => {
      console.log('xxx');
    }
  }));

```

Now I can call this from the parent with:

```
  useEffect(() => {
        setInterval(() => {
          formikFormRef.current.autoSave()
        }, 3000);
      });
  });

```

**Comment by chris-gunawardena** [comment]
I managed to get this to work by passing in the ref as a propery.
`  const formikForm = useRef(null); //in parent`
`<RfpForm  formikFormRef={formikFormRef} ></RfpForm> // in parent`


```
const RfpForm = (withFormik({ enableReinitialize: true})((props, values) => {
  useImperativeHandle(props.formikFormRef, () => ({
    autoSave: () => {
      console.log('xxx');
    }
  }));

```

Now I can call this from the parent with:

```
  useEffect(() => {
        setInterval(() => {
          formikFormRef.current.autoSave()
        }, 3000);
      });
  });

```

**Comment by brunohkbx** [comment]
Any updates?

**Comment by elkinjosetm** [comment]
Any updates on this, I can't upgrade to v2 because I have to reset some forms in my app using the reference from outside the form itself

**Comment by jaredpalmer** [comment]
PR's welcome.

**Comment by brunohkbx** [comment]
I would like to be able to implement this, but I don't know how to fix the interface `FormikConfig` to handle the type of the ref using forwardRef :disappointed:

**Comment by chris-gunawardena** [comment]
Do we really need this? While you can't do `<Formik ref={myRef} /> ` passing it as `<Formik myRef={myRef} /> ` works. Then you can subscribe to it using `useImperativeHandle(props.formikFormRef, () => {})` from within the form and call it from outside as  `formikFormRef.current.fooBar()`. See my previous post for full example.

**Comment by brunohkbx** [comment]
Hey guys. Do you have any thoughts on @johnrom suggestion? 
Please, check this PR: https://github.com/jaredpalmer/formik/pull/1972

**Comment by Crownie** [comment]
Here is a workaround that works for me in v2.

* I created a component; FormikWithRef
* The component forwards all the props to the original Formik component.
* It then exposes the formikProps using ```useImperativeHandle``` 
```
// FormikWithRef.tsx

import React, {forwardRef, useImperativeHandle} from 'react';
import {Formik, FormikProps, FormikConfig} from 'formik';

function FormikWithRef(props: FormikConfig<any>, ref) {
    let _formikProps: FormikProps<any>;

    useImperativeHandle(ref, () => (_formikProps));

    return (
        <Formik {...props}>
            {(formikProps) => {
                _formikProps = formikProps;
                if (typeof props.children === 'function') {
                    return props.children(formikProps);
                }
                return props.children;
            }}
        </Formik>
    );
}

export default forwardRef(FormikWithRef)

```

Then I use the new component; FormikWithRef instead of Formik;
```
// LoginPage.tsx

import {useRef} from 'react';
import {FormikProps} from 'formik';

export default function LoginPage() {
    const myFormRef = useRef<FormikProps<any>>(null);

    return <FormikWithRef ref={myFormRef}>
        {({
              values,
              errors,
              touched,
              handleChange,
              handleBlur,
              handleSubmit,
              isSubmitting,
          }) => (
            <form onSubmit={handleSubmit}>
                // ...
            </form>
        )}
    </FormikWithRef>
}

```

**Comment by drivasperez** [comment]
Is there any progress on this? It would make my life easier and I don't mind taking it on, but I don't want to swoop in if it's being worked on.

**Comment by danimbrogno-pml** [comment]
What's the status of this? I see this was closed, and I can see useImperativeHandle in the codebase in 2.1.2, but I can't pass a ref into the <Formik> component. 

I get the TS error: `Property 'ref' does not exist on type 'IntrinsicAttributes & FormikConfig<...>`

**Comment by johnrom** [comment]
You can get a ref to `formikBag` via `innerRef` prop.

```jsx
const bagRef = useRef();

<Formik innerRef={bagRef} />
```

**Comment by TeoTN** [comment]
To me this looks like an undocumented breaking change that should be included in "Migrating to v2" of docs

**Comment by johnrom** [comment]
@teotn it is quite poorly typed 👎 . We're discussing a real implementation here: #1807

**Comment by diosney** [comment]
@johnrom What would be the classes equivalent?

 I'm trying with `useRef` but it seems that it is intended only for function hooks, and `createRef` with `ref` doesn't work either.

For Formik slug being "without tears", I already have dropped a lot :(

**Comment by johnrom** [comment]
@diosney useRef is specific to functional "React hooks". functional components are generally considered preferable to classes in many scenarios except some very complex use cases that functional components cannot be used for. however, for backwards compatibility the class-based ref method is 

```jsx
class MyClass = {
  public constructor(props) {
    super(props);
    this.myRef = React.createRef();
  }
  render() {
    return (
      <Formik innerRef={this.myRef />
    );
  }
}
```

Note this has nothing to do with Formik, and those are just plain ol' React tears.

**Comment by diosney** [comment]
@johnrom Thanks for your answer and sorry for my grunt, but I have several rounds on this already and tested lot of things without making it working as it should, I'm really just about pulling my off my hair.

I already tried your solution with `createRef`, even repeated using `constructor` since I do not do it like that (using typescript sugar classes) but it keeping outputing:

```
{"current": null}
```

and any call to `this.myRef.errors` or `this.myRef.current.errors` or any other Formik "bag" property gives an error.

The only way I could get some partial success was by something like:

```
 {(formikProps) => {
                self.formSubmit  = formikProps.handleSubmit;
                self.formIsValid = formikProps.isValid;
                self.formErrors  = formikProps.errors;
                ....
```

but for some wicked reason it only works if I made some change in the code while developing and having Hot Reload enabled.

Have any other suggestions? Really don't know why it is not working, I updated Formik to 2.1.4 from 2.1.1 and all remains the same.

**Comment by johnrom** [comment]
@diosney if you open a new issue someone may be able to help you there. during issue creation, you should try and reproduce your issue in a CodeSandbox (link to the sandbox starter is in the new issue creation template). You might figure out where the issue is during reproduction (happens a lot!), or if you are able to reproduce we'll be able to look immediately and see where the problem is.

**Comment by diosney** [comment]
@johnrom OK, I understand the purpose of that, lol, thanks for your time.

**Comment by mstoil** [comment]
Hi @johnrom 

> Note: this isn't a reference to the Formik component, but to the "bag" of formik tools. like `handleSubmit` et all. I think using `ref` prop was avoided so that in the future if there's a reason to add a real ref, we can.

I've tried using the `innerRef` to get to the `resetForm`. I'm doing:

```
import React, { useRef } from 'react';
...
const form1Ref = useRef(null);

<Formik 	innerRef={form1Ref} ...
```
then when trying to use it for a reset, the correct values are present but the reset (even that it passes the new values when debbuged inside formik resetForm fn.) doesn't take effect
```
form1Ref.current.resetForm({ values: { ...form1Ref.current.values }})
```
I guess it has to be combined as some suggestions with `useimperativehandle`

**Comment by Evaldoes** [comment]
To access formik by reference, you can do like this:

`const formRef = useRef<FormikProps<FormProps>>(null);`

`<Formik  innerRef={formRef} />`

- `FormProps` iis the model of the data that you will use in the form

![image](https://github.com/jaredpalmer/formik/assets/12403914/adf5f555-fb5e-4bba-a45a-72f7c8957690)

![image](https://github.com/jaredpalmer/formik/assets/12403914/3ed5896c-939d-4786-b1a8-65cdb1991234)

If you print the reference `console.log(formRef.current)` you will see something like this:

![image](https://github.com/jaredpalmer/formik/assets/12403914/1c621560-e1f6-49b0-9926-4d526208df66)

**This way it is possible to manipulate formik from anywhere** :smile:  :sunglasses:  that's it
