### ISSUE TITLE
2.0.5-rc.5 and getFieldProps

### ISSUE THREAD

**Issue by atoy40** [jaredpalmer/formik#1606]
## 🐛 Bug report

The object returned by getFieldProps has a name key, but instead of the name string, it contains itself an object with a name and a type keys. Probably due to the new getFieldProps prototype which get an object as first param (where it was the name string until rc.4)

I imagine this objet {name, type } has to be expanded directly in the object returned by the getFieldProps function ?

Anthony.

### Current Behavior
```js
[fieldProps] = getFieldProps({name: "name", type: "text"});
```
fieldProps is :
```js
{
  name : {
    name: "name",
    type: "text"
  },
  onChange: ...,
  onBlur: ...,
  ...
}
```

### Expected behavior

fieldProps must be :
```js
{
  name: "name",
  type: "text"
  onChange: ...,
  onBlur: ...,
  ...
}
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.1-rc.5
| React            | 16.8.6
| TypeScript       |
| Browser          |
| npm/Yarn         |
| Operating System |

**Comment by jaredpalmer** [comment]
Can you submit a PR? That should be a quick fix.

**Comment by atoy40** [comment]
@jaredpalmer when checking the formik code, I've seen the code is correct .. it was a problem on my side. I upgraded formik, so typescript give me the new getFieldsProps prototype ... but the running instance of my apps didn't reload using the upgraded version ! so no problem, it's working nice :) Sorry !
