### ISSUE TITLE
Pristine values

### ISSUE THREAD

**Issue by tkvw** [jaredpalmer/formik#161]
I think it would be nice to remember the pristine(initial) values of the form and allow dirty to check if the new value is changed compared to this pristine value. Currently dirty is actually isTouched. Or is this a to complicated use case for formik?

**Comment by jaredpalmer** [comment]
yeah i think this is a good idea. I would keep this outside of state in a class property like `this.initialValues`

**Comment by Magellol** [comment]
We've actually enhanced Formik and provided a different version of dirty for our use cases.
We're using `componentWillReceiveProps` and we're comparing `props.values` with a property like `this.initialValues`. Then, once the form has been submitted, we're overring initialValues with the latest values.

**Comment by jaredpalmer** [comment]
@Magellol this is going to be built into Formik now with #181

**Comment by Magellol** [comment]
@jaredpalmer with the change in `componentWillReceivedProps`, does that mean the `dirty` prop will be updated correctly?

**Comment by NamPNQ** [comment]
I think https://github.com/jaredpalmer/formik-persist is what u want
