### ISSUE TITLE
Form submits on any button click

### ISSUE THREAD

**Issue by antgonzales** [jaredpalmer/formik#1610]
### Current Behavior

https://cl.ly/1ae43a21c4e2

### Expected behavior

I don't expect the form to submit when I click any button that does not have `type="submit"` or has the submit handler explicitly set on the button.

### Reproducible example

Formik template: https://codesandbox.io/s/formik-example-rfj49 

### Suggested solution(s)

Only bind the submission handler to buttons with `type="submit"` and don't bind to all buttons rendered in the form.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.7
| React            | 16.8.6
| TypeScript       |
| Browser          | Chrome
| npm/Yarn         | npm
| Operating System | macOS

**Comment by antgonzales** [comment]
Closing this as this is not a Formik issue. After reading MDN docs, it's actually normal form element behavior to submit any buttons that do not have the `type="button"` attribute listed. See the below example:

https://codesandbox.io/embed/formik-example-rfj49

**Comment by vmajsuk** [comment]
@antgonzales Could you please provide and MDN link? Actually on the <button /> article it is pointed out that button has no default browser behaviour. Here's the [link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button), here's a screenshot:
![Screenshot from 2019-09-09 19-53-11](https://user-images.githubusercontent.com/11076829/64550372-7cb0bf00-d33b-11e9-8ae4-c3f71163ae6f.png)

Here's a link to the codesandbox that demonstrates buttons behaviour:
https://codesandbox.io/s/winter-violet-rme7d

**Comment by vmajsuk** [comment]
Ok so the thing with this issue is you need to explicitly pass `type="button"`, since `type="submit"` is the default HTML value, as you can see on the screenshot above.
