### ISSUE TITLE
dynamically add field to form

### ISSUE THREAD

**Issue by MareoRaft** [jaredpalmer/formik#1622]
## ❓Question

This is related to issue #228.  I would like to dynamically add a new field to the bottom of the form when the user hits a button, without any of their current inputs being erased.

I can think of a few possible solutions:

  1. I can track the state of the form in my redux store at all times.  If the user does as much as type a single letter into a field, the store would get updated.  To do this, would I need to plug in a custom `handleChange` function?

  2. I could create my own onChange event handler that somehow grabs the latest form `values`.  I don't know how to grab the latest values other than in the `onSubmit` function.  I am using class syntax for my component and they are not connected to props.

Do either of these sound right?

**Comment by MareoRaft** [comment]
I am generating a form field for each key-value pair in an object.  That object becomes the `values` object when formik is initialized.  So I'm wondering if there may be a third option

  3. Use some builtin `insertKey` function or similar.  I can see in the [Array example](https://github.com/jaredpalmer/formik/blob/next/examples/Arrays.js) that there is a builtin `insert` and `push` function for arrays.  Is there an analagous function for adding a key to an object?

**Comment by buglessir** [comment]
@MareoRaft 

I've this case too, I've handled this feature with component states and stored additional inputs into and array and show those with a simple array.map()

Consider it, you should store a num to add inputs with different names !

**Comment by MareoRaft** [comment]
I ended up going with option (2).  By using the `withFormik()` wrapper function instead of `<Formik>`, my component was able to access the latest form `values` at any time with `this.props.values`.
