### ISSUE TITLE
Internal `submitForm` implementation does not throw errors

### ISSUE THREAD

**Issue by andrewMuntyan** [jaredpalmer/formik#1636]
## 🚀 Feature request
Catch errors thrown  from `onSubmit` inside of form/fields components

### Current Behavior
Formik Internal implementation of `submitForm` does not throw any errors.
It is not possible to get in `catch` hook with the following example:
```javascript
const onSaveButtonClick = async () => {
        // submitForm - formik internal method. It invokes `onSubmit` method
        //which is passed with props to formik
        const { submitForm } = props.formikActions;
        return submitForm()
          .then(promise => {
           // i'm always getting here
          })
          .catch((e: any) => {
           //cant get here
          });
      };
```
[Here is a sandbox exaple](https://codesandbox.io/s/formik-201-rc7-async-submitform-issue-k7fl9?fontsize=14)
### Desired Behavior
Have the ability to catch errors which are thrown from `onSubmit` method passed to formik as a prop

### Suggested Solution
```javascript
const submitForm = useEventCallback(() => {
    // ...some code here
    return validateFormWithHighPriority().then(
        // ...some code here
          return Promise.resolve(executeSubmit())
            .then(() => {
              if (!!isMounted.current) {
                dispatch({ type: 'SUBMIT_SUCCESS' });
              }
            })
            .catch(_errors => {
              if (!!isMounted.current) {
                dispatch({ type: 'SUBMIT_FAILURE' });
              }
            // THROW ERROR HERE
            });
        // ...some code here
        return;
      }
    );
  }, [executeSubmit, validateFormWithHighPriority]);
```

### Who does this impact? Who is this for?
This is a cool additional feature for all users. In this way, internal `submitForm` method (which could be used inside <Field /> component ) will completely implement Promise interface.

**Comment by slorber** [comment]
would also expect to work this way and be able to catch submit failures with `formik.submitForm().catch()`

**Comment by jaredpalmer** [comment]
Can u submit a pr?

**Comment by slorber** [comment]
@andrewMuntyan you want to contribute or I'll do it? (more likely next week)

**Comment by andrewMuntyan** [comment]
@slorber I'll try to make it faster. Check this issue next week. If there is no PR, pls make it happen :)

**Comment by andrewMuntyan** [comment]
i've made related PR - https://github.com/jaredpalmer/formik/pull/1637

Also, my CodeSandBox example was not correct, so I've fixed it.
