### ISSUE TITLE
Material UI Checkbox does not work with Formik 2.x

### ISSUE THREAD

**Issue by nareshbhatia** [jaredpalmer/formik#1646]
### Current Behavior

Setting the `onChange` property of MUI checkbox to Formik's `field.onChange` handler does not work. Toggling the checkbox does not toggle Formik's boolean field.

### Expected behavior

Toggling the checkbox should toggle Formik's boolean field.

### Reproducible example

https://codesandbox.io/embed/mui-checkbox-with-formik-smqej

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.1-rc.7
| Material UI           | 4.1.3
| React            | 16.8.6
| TypeScript       | 3.4.5
| Browser          | Chrome
| npm/Yarn         | 1.16.0
| Operating System |

**Comment by nareshbhatia** [comment]
Thanks to @stunaz, this is resolved. See  https://github.com/mui-org/material-ui/issues/16434

**Comment by deepaksingh007** [comment]
code sandbox example does not work.
Not changing the checkbox on click.
@nareshbhatia 
@stunaz

**Comment by nareshbhatia** [comment]
@deepaksingh007, here's my latest [working version](https://github.com/nareshbhatia/react-force/blob/master/packages/formik-mui/src/CheckboxField/CheckboxField.tsx).
