### ISSUE TITLE
Field-level validation not working when using `useField` hook

### ISSUE THREAD

**Issue by bummey** [jaredpalmer/formik#1650]
### Current Behavior

When using the `useField` hook, field-level validation using the `validate` property doesn't work.
```ts
const [field] = useField({ name, validate: () => 'not good' });
```

### Expected behavior

The validate prop should work just like its `Field` counterpart.

### Reproducible example

https://codesandbox.io/embed/formik-codesandbox-template-p5zc1

### Suggested solution(s)

Manually registering the validate function does the trick for me:
```ts
useEffect(() => {
  registerField(name, {
    validate: () => 'not good'
  });

  return () => unregisterField(name);
}, [name, registerField, unregisterField]);
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.1-rc.9
| React            | 16.8.6
| TypeScript       | 3.5.2
| Browser          | Chrome 75
| npm/Yarn         | npm
| Operating System | Ubuntu 19.04

**Comment by jaredpalmer** [comment]
Ahh yes, good catch

**Comment by FredyC** [comment]
On that point, I think it makes sense to register field only if `validate` function is specified. Or is there some other plan for a field registry besides validation?

**Comment by gaelduplessix** [comment]
This is fixed by https://github.com/jaredpalmer/formik/pull/1699, released in `v2.0.1-rc.13`

**Comment by avetisk** [comment]
> This is fixed by #1699, released in `v2.0.1-rc.13`

Doesn't seem to be fixed still in `2.1.4` :'(

**Comment by johnrom** [comment]
@avetisk this works fine for me. Are you able to reproduce in CodeSandbox?

**Comment by avetisk** [comment]
> @avetisk this works fine for me in v2.1.4. Are you able to reproduce in CodeSandbox?

I moved back to RFF, but I still tried to recreate the issue on CodeSandbox and couldn't, so I guess I missed something there in my code.

So no worries, it works fine! :)

**Comment by johnrom** [comment]
Awesome, @bummey please have a look and see if this fixes your issue. Thanks!

**Comment by bummey** [comment]
Works fine now, thanks!

**Comment by mordechaim** [comment]
Why is this behavior not documented [here](https://jaredpalmer.com/formik/docs/api/useField)?

I ran into this page by searching how to do field-level validation using hooks.

**Comment by johnrom** [comment]
@mordechaim you're free to open a PR to update the documentation

**Comment by paillave** [comment]
This issue happens if the form is make using withFormik whereas everything goes fine within a Formik tag.
I reproduced the bug by show the two versions of the form (withFormik and Formik tag): https://codesandbox.io/s/morning-violet-ednp3

Can somebody tell me what I'm doing wrong in the withFormik version? If nothing is wrong, it would be good to reopen this bug.
