### ISSUE TITLE
How to handle the typical use case of the navigation to Terms or Privacy Policy without losing form data

### ISSUE THREAD

**Issue by desmap** [jaredpalmer/formik#1652]
## 📖 Documentation

I understood from Jared's talks and docs that forms data should be ephemeral. But what is the reference design for the case where a user filled out the form, clicks then on eg Privacy Policy before submitting and comes back and sees that his form is again empty? 

Possible Solutions:

1. I could save the stuff with React Context but then the data would be saved infinitely and not just for the moment when he comes back from the Privacy Policy.

2. I could show the Privacy Policy in a Pop-up instead of a dedicated Page. But this is super clumsy on mobile.

Is there any better option IDK of?

**Comment by po35** [comment]
Oh man, I need just to open legal documents in a new tab, that was not my day. Can anyone close this issue pls?
