### ISSUE TITLE
Consider using react-tracked

### ISSUE THREAD

**Issue by FredyC** [jaredpalmer/formik#1676]
## 🚀 Feature request

Nice and concise article here https://blog.axlight.com/posts/super-performant-global-state-with-react-context-and-hooks/.

The obvious downside - it relies on Proxies (not polyfill-able) which means no IE11. Although I haven't really found information if Formik wants to support IE11. Besides, Windows 7 will be a goner in Q1 2020, so it might not be such a big problem.

On the plus side, there is close to none modification to existing code, just replace one hook for another. Could be worth at least like an experiment. Thoughts?

**Comment by bricejar** [comment]
IE 11 support is important to a lot of users.

**Comment by FredyC** [comment]
Well ... Considering that [Windows 7 official support ends Q1 2020](https://www.microsoft.com/en-us/microsoft-365/windows/end-of-windows-7-support) it won't be important for a long :) It could be Formik V3 that drops IE11 support. Just an idea.

**Comment by bricejar** [comment]
@FredyC  Windows 7 official support ends does not mean IE11 support end. You can still use IE11 on Windows 10.

**Comment by FredyC** [comment]
Have you read what I just said? Windows 10 **does not** have IE11 installed by default. There is only the Edge. A user would need to deliberately decide to install a less secure browser.

This isn't placed for a discussion like that. As I said, just an idea toward the future.

**Comment by bricejar** [comment]
https://support.microsoft.com/en-ca/help/4026136/windows-10-use-internet-explorer

**Comment by FredyC** [comment]
https://whenwillie11die.com/

I am sorry, I had the wrong information. In that case, it's probably a bad idea. But once again, it's not stated anywhere I could find what browsers Formik supports. If Jared decides he doesn't want to support IE11, well then... :)

**Comment by bricejar** [comment]
I would be willing to participate on a LTS of Formik 2 if there is a need to end IE11 support for Formik 3.
