### ISSUE TITLE
Why after handleSubmit form is resets itself internally?

### ISSUE THREAD

**Issue by RIP21** [jaredpalmer/formik#170]
I use withFormik HoC.
I call handleSubmit with Redux action it passes prop to the form which actually isn't used in the fields.
All my fields still there in inputs.
When I try to resubmit form immediately without touching anything it doesn't do so cause it's not valid, while it's valid. (I have only isRequired validations on each field)
I'm looking at the Formik state, and I see that for some reason after form submission all values inside are gone. But they are still on the view.

I removed this props passing to the form. Same result. 

Calling empty handleSubmit (with console.log() but no Redux func) keeps values etc.
WTF?

Thanks.

**Comment by jaredpalmer** [comment]
Are you using initialValues? Sounds like the result of uncontrolled submit

--
Jared
________________________________

**Comment by jaredpalmer** [comment]
**mapPropToValues sorry.

**Comment by RIP21** [comment]
I have no any. So default, I assume.

Also quite weird for me (no offense ;)) (at least after Redux-forms and manually written solutions) is if you have errors looking like `errors: { username: "" }`
It thinks that it's a non-valid form. So I had to write helper which will do `delete errors[field]` from `errors` if they are `''` - empty strings. Cause I just don't want to do it in one go like in the Readme. Because I created helpers like `errors.email = isEmail(values.email)` which are return error message or an empty string. So if there are no errors I end up with a format that I described higher.
Maybe it will be different behavior if I set them `false` or something different instead?

Thanks :)

**Comment by jaredpalmer** [comment]
Sorry for the frustration. I’m having difficulty understanding the issue. Can you make a sandbox?

**Comment by RIP21** [comment]
I will later on.

**Comment by RIP21** [comment]
@jaredpalmer 
[![Edit Broken Formik](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n3wp4k81l0)
Here we go. Exactly the same code as I have. Take a look at all of the code, plus helpers. Maybe there is something wrong with them.

**Comment by RIP21** [comment]
Want to mention. That with Formik render prop component (we need to find some handy shortcut word as HoC for it :D) everything works just fine. With HoC it messed up.

**Comment by jaredpalmer** [comment]
You need to use `mapPropsToValues` to initialize your forms values when you setup your HoC. Otherwise your inputs will switch from an uncontrolled to a controlled input resulting in an error thrown by React.

**Comment by RIP21** [comment]
@jaredpalmer point it out somewhere in the Readme. Possibly with a link to this issue, so people will not get mad or disappointed. I lost a lot of time figuring out what is the problem.
Thanks.

**Comment by jaredpalmer** [comment]
Good idea. Sorry about that. It used to be in the example. 

Glad that solved the problem though!
