### ISSUE TITLE
How to manipulate the nested objects

### ISSUE THREAD

**Issue by l-i-x-u** [jaredpalmer/formik#1706]
version: formik 1.5.8

my `initialValues` looks like this:
```
const initiaValues = {
  fruits: {}
}
```
I would like to use a button which dynamically adds some fields to each fruit, e.g.
```
{
  fruits: {
    apple: {
      quantity: 5,
      producer: abc
    },
    orange: {
      quantity: 4
      producer: cba
    }
  }
}
```
I know `<FormikArray />` provide `add` and other methods to manipulate the arrays, but is there something similar to manipulate the objects?

**Comment by Granipouss** [comment]
Hi,

`<FormikArray />` provides a very complete API for lists but I don't think anything similar exist for Objects. You can make it yourself, taking inspiration from `FormikArray` source code, if you really need it.

Another solution is to manipulate lists in the form
```
{
    fruits: [
        {
            name: 'apple',
            quantity: 5,
            producer: abc
        },
        {
            name: 'orange',
            quantity: 4
            producer: cba
        }
    ]
}
```
Then convert the list into an object when you specifically need an object. [Lodash.mapKeys](https://lodash.com/docs/4.17.14#mapKeys or something similar can do the trick.

Hope it somehow helped.

Cheers,

**Comment by l-i-x-u** [comment]
Hi @Granipouss That looks good, thanks
