### ISSUE TITLE
Get touched and errors props into Wizard.Page from Formik Multistep example

### ISSUE THREAD

**Issue by po35** [jaredpalmer/formik#1714]
## 📖 Documentation

I think the Multistep example is one of most used use cases for Formik and quite elegant. Before I rewrite the whole thing, probably somebody can help: I wrapping my head around how to get the touched and errors props from Formik into the Wizard page. I don't want to use the ErrorMessage Component because one of my own components within Wizard.Page relies on touched and errors from `<Formik />`.

What I tried: Adding touched and errors as args in Formik render prop in line 62: https://github.com/jaredpalmer/formik/blob/344b846bc25865dc02b6304e7c9f447b5b1552fd/examples/MultistepWizard.js#L62 but I don't know how to access it within Wizard.Page, e.g. like this:
```
<Wizard.Page>
  {props => (
    <MyCustomField errors={props.error} touched={props.touched} />
  ...
```

**Comment by johnrom** [comment]
I don't see a way to do this in the example that was created for multi-step form. However, in Hooks (v2) you can easily consume the Formik Context from your MyCustomField.

```
const MyCustomField = props => {
  const { errors, touched } = useFormikContext();

  return <input className={errors.myCustomField ? "input-error" : ""} />;
}
```

I think pre-v2 you'd have to modify `Wizard` to achieve the same functionality. I unfortunately can't provide an example of this at this time.

**Comment by po35** [comment]
I found a way: It is actually very simple: Field exposes via render props touched and errors. So It;'t rather an issue for the example to extend Field with render props.

**Comment by johnrom** [comment]
Yep, that's the same as using `useFormikContext`, except Field does it for you. You can also use (for thoroughness' sake): ```

const MyCustomField = props => {
    const [field, meta] = useField(props.name);`

    return <input name={field.name} className={meta.error ? "input-error" : ""} />;
}
```

**Comment by po35** [comment]
wow super nice, didn't know this, thanks

**Comment by johnrom** [comment]
Np, I'm closing this in favor of #1725
