### ISSUE TITLE
Dynamic Forms using Formik

### ISSUE THREAD

**Issue by Reddhi** [jaredpalmer/formik#173]
What is the best practice when i need the form to be dynamic? I mean I need to add/remove rows of form elements. Is there any example form that you can link me to which is using such a feature?

**Comment by jaredpalmer** [comment]
Definitely something that should be improved on and documented. You would use either setValues or setFieldValue() to add and remove keys to `values` or manage the dynamic part of your form in a custom <Field /> or component so you can keep the array structure and can avoid flattening.

**Comment by jaredpalmer** [comment]
Open issue to add a guide, but the resources have been gathered here. https://github.com/jaredpalmer/formik/issues/155
