### ISSUE TITLE
`onSubmit` handler not being called

### ISSUE THREAD

**Issue by ameernormie** [jaredpalmer/formik#1733]
### Current Behavior
On form submission `onSubmit` is not being called in <Formik onSubmit={... } > .... </Formik>

### Expected behavior
`onSubmit` should be called with the form values

### Reproducible example

Codesandbox link:
Formik template: https://codesandbox.io/s/cocky-mcnulty-dyx26

### Suggested solution(s)

I don't know why `onSubmit` is not being called.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.8
| React            | 16.8.6
| TypeScript       | 3.5.3
| Browser          |  chrome
| npm/Yarn         | 6.9.0/1.17.0
| Operating System | macOS Mojave

**Comment by tommedema** [comment]
You're missing an inner `<form>` element and `handleSubmit` should be attached to that form element, not the submit button.

See https://jaredpalmer.com/formik/docs/overview#the-gist

**Comment by ameernormie** [comment]
Found the issue. `onSubmit` will be called if the form is valid. I wasn't entering a valid email.

**Comment by alex-drocks** [comment]
> Found the issue. `onSubmit` will be called if the form is valid. I wasn't entering a valid email.

Thanks for the hint. I was having the same problem. I had invalid data but no visuals to indicate something was wrong. I checked my validationSchema and indeed I had a field name that was changed and so the validation failed silently - preventing the on submit call()
