### ISSUE TITLE
Prevent blur event when setting values through form.setFieldValue()

### ISSUE THREAD

**Issue by jsonbaozi** [jaredpalmer/formik#1735]
I'm using Formik alongside React-Select, and the blur event that is triggered through Formik's setFieldValue is closing my Select Menu, despite having "closeMenuOnSelect" set to false.

```
<Field
    component={({ field, form }) => (
        <Select
            isMulti={true} //
            options={roleOptions}
            value={field.value.roles}
            closeMenuOnSelect={false}
            onChange={(values, action) => form.setFieldValue('roles', values)}
            onBlur={() => form.setFieldTouched('roles', true)}
        />
    )}
/>
```

At least, I think it's the blur that's closing the menu. It's definitely something caused by form.setFieldValue().

**Comment by chevin99** [comment]
@jsonbaozi did you figure out what was wrong, and if so, would you be willing to share what you did to fix it?  I'm having a very similar problem ☹️

**Comment by chevin99** [comment]
Ah, I figured it out.  If anyone else stumbles on this I'd suggest checking out this issue: https://github.com/jaredpalmer/formik/issues/882#issuecomment-492380526
