### ISSUE TITLE
[v2] State being updated after component unmount

### ISSUE THREAD

**Issue by Ericnr** [jaredpalmer/formik#1741]
Calling `closeModal()` in `onSubmit` before `setSubmitting(false)` throws the error `Can't perform a React state update on an unmounted component.`

Does not happen in the current stable version.
[CodeSandbox Link](https://codesandbox.io/s/react-modal-form-pop-up-k0u0p)

**Comment by shulcsm** [comment]
You get similar issue if you return promise in submit handler (#1730) and form gets unmounted.

**Comment by Ericnr** [comment]
yea, seems like it is the same problem. Will close this issue then.

**Comment by shulcsm** [comment]
> yea, seems like it is the same problem. Will close this issue then.

I don't think it's the same issue, just pointing out they might be related
