### ISSUE TITLE
Ability to extend Field component

### ISSUE THREAD

**Issue by jackHedaya** [jaredpalmer/formik#1743]
## 🚀 Feature request

```jsx
function CustomField(props) {
   return (
       <>
          <div>My Custom Title</div>
          ...
          <Field {...props} />
       </>
   )
}
```

### Current Behavior

Field will not register correctly and will throw the controlled/uncontrolled input error from React.

### Desired Behavior

The Field should work as expected.

### Suggested Solution

Even if it is not possible to do this with functional components, it should be possible by extending Field in a class component. 

### Who does this impact? Who is this for?

All users.

### Describe alternatives you've considered

I've considered creating the form in the less elegant way by creating the fields manually but the other way seems a lot more efficient.

**Comment by arianitu** [comment]
@jackHedaya ran into this, is there an easy way to do this?

**Comment by jackHedaya** [comment]
I discovered that my original problem wasn’t really a problem because I didn’t set default string values.
