### ISSUE TITLE
FormikSharedConfig.validate missing second parameter Props

### ISSUE THREAD

**Issue by meteor91** [jaredpalmer/formik#175]
It's looks like interface FormikSharedConfig validate signature left second parameter Props, as it written in documentation. There also some mistake in code, when Formik call validate, it's not send Props.

**Comment by topas** [comment]
Good question and +1 because I need a way how to get validation rules from props.

**Comment by menscrem** [comment]
+ 1

**Comment by topas** [comment]
I found a workaround: Don't use `withFormik` but instead create wrapping component around `<Formik />` than you can get props from the wrapping component.

**Comment by jaredpalmer** [comment]
Fixed in #180
