### ISSUE TITLE
onError Function

### ISSUE THREAD

**Issue by haThaiHoang** [jaredpalmer/formik#1750]
## 🚀 Feature request

I think we should have a callback function like onError pass into Formik to call after validate failed.

Thanks for a great library.

**Comment by jaredpalmer** [comment]
Can you show an example of how this would be beneficial?

**Comment by AnotherHermit** [comment]
I have an example of where this would be useful. I am currently implementing Analytics in our web app and was just looking for some way of sending an event with information about which fields the user failed to fill in correctly to know which parts of our forms that could use improvement. 

I am not sure if there is a simple workaround but a callback after validation failed would be very handy.

**Comment by haThaiHoang** [comment]
> Can you show an example of how this would be beneficial?

I want to scroll up at the top of the window to see the error messages when the form validate failed

**Comment by johnrom** [comment]
I think this could be pretty useful, but everyone will likely want errors to trigger a different way. Maybe a userland component would be good for this:

```
export const ErrorListener = ({onErrorChange, shouldTriggerErrors}) => {
    const shouldTriggerErrors = shouldTriggerErrors || 
        (errors, nextErrors) => !deepEquals(errors, nextErrors);
    const formik = useFormikContext();
    const [errors, updateErrors] = React.useState(formik.errors);

    React.useEffect(() => {
        if (shouldTriggerErrors(errors, formik.errors) {
            onErrorChange(formik.errors);

            updateErrors(errors);
        }
    }, [formik.errors]);

    return null;
}

export const MyForm = () => (
    <Formik>
        <ErrorListener onErrorChange={scrollToTop} />
    </Formik>
);
```

**Comment by jaredpalmer** [comment]
This behavior is really straightforward  with useEffect() as you just showed

**Comment by haThaiHoang** [comment]
> I think this could be pretty useful, but I think there are different use cases for triggering errors based on different criteria. Maybe a component would be good for this:
> 
> ```js-jsx
> // I'm not sure if errors are memoized by default
> const defaultShouldTriggerErrors = (errors, nextErrors) => !deepEquals(errors, nextErrors);
> 
> export const ErrorListener = ({onError, shouldTriggerErrors}) => {
>     const shouldTriggerErrors = shouldTriggerErrors || defaultShouldTriggerErrors;
>     const formik = useFormikContext();
>     const [errors, updateErrors] = React.useState(formik.errors);
> 
>     React.useEffect(() => {
>         if (shouldTriggerErrors(errors, formik.errors) {
>             onError(formik.errors);
> 
>             updateErrors(errors);
>         }
>     }, [formik.errors]);
> 
>     return null;
> }
> 
> export const MyForm = () => (
>     <Formik>
>         <ErrorListener onError={scrollToTop} />
>     </Formik>
> );
> ```

This helped me. Thank you guy very much!

**Comment by johnrom** [comment]
@haThaiHoang awesome! please close this issue out if it's resolved

**Comment by SNPR** [comment]
> I think this could be pretty useful, but I think there are different use cases for triggering errors based on different criteria. Maybe a component would be good for this:
> 
> ```js-jsx
> // I'm not sure if errors are memoized by default
> const defaultShouldTriggerErrors = (errors, nextErrors) => !deepEquals(errors, nextErrors);
> 
> export const ErrorListener = ({onError, shouldTriggerErrors}) => {
>     const shouldTriggerErrors = shouldTriggerErrors || defaultShouldTriggerErrors;
>     const formik = useFormikContext();
>     const [errors, updateErrors] = React.useState(formik.errors);
> 
>     React.useEffect(() => {
>         if (shouldTriggerErrors(errors, formik.errors) {
>             onError(formik.errors);
> 
>             updateErrors(errors);
>         }
>     }, [formik.errors]);
> 
>     return null;
> }
> 
> export const MyForm = () => (
>     <Formik>
>         <ErrorListener onError={scrollToTop} />
>     </Formik>
> );
> ```

Can I somehow use this functionality without using hooks?

**Comment by tomhicks** [comment]
Is this the state of the art for formik onError?

Doesn't seem like a component, where you have to do your own diffing between current and previous errors, is a good solution.

**Comment by johnrom** [comment]
There are two problems here, 

1. this is a pretty niche use of the api which already has a very concise solution, above (though it will need some modification for v3), and doesn't necessarily warrant expanding the maintenance surface of the API.
2. what two different devs want to use it for means they might need different diffing algorithms.

Ultimately, it's not that there isn't a way to provide this functionality on behalf of devs, but we would have to codify a general `on*` callback API which Formik does not currently have, and I don't think it's clear whether an API like that is more flexible or usable than suggesting how to combine the Formik API with hooks.

I've suggested the possibility of adding on* hooks in another issue, but I'm on mobile so I don't know if I can find it.

**Comment by tomhicks** [comment]
For some more background... I started with your example above, and tried some other stuff, then realised that it was triggering these changes as you type, not as you submit. I ended up with this monstrosity:

```
function ErrorListener({
  isSubmitting,
  errors,
  values,
}: {
  isSubmitting: boolean
  errors: FormikErrors<FormValues>
  values: FormValues
}) {
  const [wasSubmitting, setWasSubmitting] = React.useState(isSubmitting)
  React.useEffect(() => {
    if (isSubmitting === false && wasSubmitting === true) {
      // serialize errors and send to analytics endpoint
    }
  }, [isSubmitting, wasSubmitting, errors, values])

  React.useEffect(() => {
    setWasSubmitting(isSubmitting)
  }, [isSubmitting])

  return null
}
```

Am I missing something? Is there a less awful way to do this?

**Comment by tomhicks** [comment]
Seems nasty to have to dig around and listen to changes in the other thing's state to raise what is essentially an event.

**Comment by johnrom** [comment]
You're asking for something slightly different than my solution, which is a great example of why a single API-codified callback won't work for everyone without a lot of planning.

To answer your question, what you have looks pretty good, and concise. Adjectives like "awful", "monstrosity" etc strike me as odd given you've achieved a pretty complex thing in like 10 lines of code. I agree that it is odd to use a custom component for this functionality, but wouldn't describe it in such strong terms.

You can accomplish the same thing without a second component by using useFormik + FormikProvider, basically replacing the Formik component with a slightly more advanced component which has these effects.

This is not an html event, and Formik tries to avoid creating "new events" when possible to conform to the expectations of html and emphasize the use of React hooks. Like I mentioned above, I've floated the idea of adding Plugins where someone could decorate Formik's functionality with something we're not comfortable supporting in the core API (like custom events) and take responsibility for that functionality.

**Comment by tomhicks** [comment]
I suppose my calling it awful and a monstrosity is that it feels like incredibly fragile code. Nothing to do with number of lines. Also, I would never have been able to write this if I were reasonably new to React and hadn’t learned a lot about “simulating” raising events based off state changes with useEffect.

Observing the value of one thing (isSubmitting) over time in order to then check the value of two related things at (hopefully) the correct instant is what feels bad. Feels like there are *a lot* of gaps you could fall down and make a mistake.

I kind of get not wanting to create new events and bloat the API. Having said that, there are definite “event-like” things that happen internally that it would be nice to know about as a consumer. I don’t like having to recreate events by cobbling together observing state changes!

**Comment by nandorojo** [comment]
My use-case is that, on error, I want to scroll to the first input that errored. 

```tsx
<Formik 
  onSubmissionError={({ errors }) => scrollTo(Object.keys(errors[0]))}
/>
```

Is there a way I can do this in the `onSubmit` step?

**Comment by sm3sher** [comment]
My use case would be a snackbar I would show in case of submission errors. Still waiting for a solution...

**Comment by farrukhabbas** [comment]
> I think this could be pretty useful, but I think there are different use cases for triggering errors based on different criteria. Maybe a component would be good for this:
> 
> ```js
> // I'm not sure if errors are memoized by default
> const defaultShouldTriggerErrors = (errors, nextErrors) => !deepEquals(errors, nextErrors);
> 
> export const ErrorListener = ({onError, shouldTriggerErrors}) => {
>     const shouldTriggerErrors = shouldTriggerErrors || defaultShouldTriggerErrors;
>     const formik = useFormikContext();
>     const [errors, updateErrors] = React.useState(formik.errors);
> 
>     React.useEffect(() => {
>         if (shouldTriggerErrors(errors, formik.errors) {
>             onError(formik.errors);
> 
>             updateErrors(errors);
>         }
>     }, [formik.errors]);
> 
>     return null;
> }
> 
> export const MyForm = () => (
>     <Formik>
>         <ErrorListener onError={scrollToTop} />
>     </Formik>
> );
> ```

The follow adaptation of the above code works in my use case of scrolling the form to top if there is a validation error, but just simple callbacks to the form would be super helpful. 

`const ErrorListener = ({ onError }) => {
  const formik = useFormikContext();
  const [submitCount, setSubmitCount] = useState(formik.submitCount);

  useEffect(() => {
    if (
      !formik.isValidating &&
      !formik.isSubmitting &&
      formik.errors &&
      formik.submitCount > submitCount
    ) {
      onError(formik.errors);

      setSubmitCount(formik.submitCount);
    }
  }, [
    formik.errors,
    formik.isSubmitting,
    formik.isValidating,
    formik.submitCount,
    onError,
    submitCount,
  ]);

  return null;
};`

**Comment by oskarhertzman** [comment]
useEffect is a terribly overused, misused and misunderstood hook, effects are an escape hatch. They should primarily be used to synchronise your components with external API, the DOM etc. that you don't have control over directly via in the react api. 

To use an effect here to listen to Formik errors seems pretty bad and anti pattern. Its not an external system and the API is fully controllable. Its also clearly a request that people seem benefiting a lot from. My use-case is that i have a multi step form that i need to navigate in-between depending on where the errors are located. 

Like others have pointed out, a error callback like this would be suffice:

`onSubmissionError={({ errors }) => scrollTo(Object.keys(errors[0]))}`
