### ISSUE TITLE
Add mapFormikBagToProps to withFormik HOC

### ISSUE THREAD

**Issue by janhesters** [jaredpalmer/formik#1752]
### Current Behavior

Currently, when using the `withFormik` HOC you either have to 1. define your component in a way that it matches Formik's FormikBag API, or 2. wrap your component in an additional layer.

1. E.g. your form has to expect `values` so that you can add `values.email` to an input.
2. E.g. you have to write `mapFormikBagToProps` yourself.

```js
import MyForm from './my-form';

const mapFormikBagToProps = ({ values }) => <MyForm email={values.email} />;

export default withFormik(formikConfig)(mapFormikBagToProps);
```

### Desired Behavior

It would be nice, if you could configure these mappings in the `withFormik` HOC's config, similar to `mapPropsToValues`.

```jsx
const mapFormikBagToProps = ({ values }) => ({ email: values.email })

const formikConfig = {
  mapFormikBagToProps,
  // more keys
};

export default withFormik(formikConfig)(mapFormikBagToProps);
```

### Suggested Solution

I'm not very familiar with TypeScript, so I'll leave out types. But what you could do, is extend `WithFormikConfig` with `mapFormikBagToProps` and use this method in the HOC's render method.

```jsx
renderFormComponent = (formikProps: FormikProps<Values>) => {
  return <Component {...this.props} {...config.mapFormikBagToProps(formikProps)} />;
};
```

For this to have backwards compatability, `mapFormikBagToProps` should be the identity function by default.

```jsx
const mapFormikBagToProps = x => x;
```

### Who does this impact? Who is this for?

This is for people using `withFormik` and who have forms that weren't made with Formik in mind. Using this method Formik would allow you to map its values to the user's choice / what the existing forms expect.

### Describe alternatives you've considered

I've described what the user is currently forced to do above.

**Comment by janhesters** [comment]
**BTW** Here is the workaround and how I currently use it:

```js
import { withFormik } from 'formik';
import React from 'react';
import { connect } from 'react-redux';
import { compose } from 'redux';

import LoginForm from './login-form-component';
import { getLoginFormLoading } from './login-form-reducer';
import validationSchema from './validation-schema';

const mapStateToProps = state => ({
  loading: getLoginFormLoading(state),
});

const initialFormValues = { email: '', password: '' };

const formikConfig = {
  handleSubmit: (values, { props }) => {
    console.log(values);
    console.log(props);
  },
  // TODO: Compose withFormik with Redux' connect and
  // pass an action creator here that navigates to the forgot password
  // screen.
  // Also, get loading state from Redux and pass it here to the form.
  mapPropsToValues: () => initialFormValues,
  validationSchema,
};

const mapFormikBagToProps = ({
  errors,
  handleSubmit,
  isValid,
  loading,
  setFieldTouched,
  setFieldValue,
  touched,
  values: { password, email },
  ...rest
}) => ({
  disabled: loading || !isValid,
  email,
  emailError: touched.email ? errors.email : '',
  loading,
  onBlurEmail: () => setFieldTouched('email'),
  onBlurPassword: () => setFieldTouched('password'),
  onChangePassword: value => setFieldValue('password', value),
  onChangeEmail: value => setFieldValue('email', value),
  onFocusEmail: () => setFieldTouched('email', false),
  onFocusPassword: () => setFieldTouched('password', false),
  onSubmit: handleSubmit,
  password,
  passwordError: touched.password ? errors.password : '',
  ...rest,
});

export default compose(
  connect(mapStateToProps),
  withFormik(formikConfig)
)(props => <LoginForm {...mapFormikBagToProps(props)} />);
```

**Comment by jaredpalmer** [comment]
Hey! Thanks for the write up. While this is an interesting idea, it’s not how I envision formik to be used. One of the key value propositions of formik is not having to give names to every single event handler, but rather reuse existing ones. This allows you to reuse more of your form components as your application grows and reduces cognitive load (because of standardization). Additionally, as @janhesters showed, you can already accomplish what you want in userland. Thus, I don’t think it makes sense to add this to the API.

**Comment by janhesters** [comment]
@jaredpalmer That's unfortunate. I think this is an obstacle to integrating Formik into existing large projects. But you are the owner, so you call the shots.
