### ISSUE TITLE
Rewrite `useEventCallback()`

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/formik#1762]
`useEventCallback()` can be written as

```typescript
function useEventCallback<T extends (...args: any[]) => any>(
  fn: T
): T {
  const ref: any = React.useRef();

  // we copy a ref to the callback scoped to the current state/props on each render
  React.useLayoutEffect(() => {
    ref.current = fn;
  });

  return React.useCallback((...args) => ref.current.apply(void 0, args), []) as T;
}
```

as per https://github.com/facebook/react/issues/14099#issuecomment-440172008

To me this would make it more clear that `useEventCallback()` is essentially a hack to have a callback which has the entire current state/props, and not only the deps, but the identity of the callback itself doesn't change, making it safe to send downstream and not cause rerenders.

That is to say, even the current version does essentially this, but `useLayoutEffect()` makes it more explicit than `useEffect()` + deps + `throw on incomplete render`.

*Edit* Another thing that falls off from this change is, now whenever `useEventCallback()` is used, it looks weird, because it has no deps. And, I think it's good to look weird, because it /is/ weird. It makes it more clear that this isn't a normal hook.

_Originally posted by @VanTanev in https://github.com/jaredpalmer/formik/pull/1566#issuecomment-497933241_

**Comment by timbotnik** [comment]
@jaredpalmer in our app we're seeing a steady flow of errors that seem to happen in this code: 

https://github.com/formium/formik/blob/b4ea17140c280187297d4e079b3ca02677b11bcc/packages/formik/src/Formik.tsx#L1222

The errors make it look like `ref.current` sometimes ends up being `undefined` - any clues as to why this might be happening?  Bug?

![image](https://user-images.githubusercontent.com/1831709/93540248-7580b000-f996-11ea-9156-10a6227b608f.png)

**Comment by jaredpalmer** [comment]
What version of react are you using?

**Comment by timbotnik** [comment]
Versions here.  I'm going to update to the latest `formik` as a first pass, but not sure that code path has changed at all since then.
```
"react": "16.10.2",
"formik": "2.0.1-rc.13"
```
