### ISSUE TITLE
Untouching a field on focus

### ISSUE THREAD

**Issue by blocka** [jaredpalmer/formik#177]
I would like my validation messages to disappear once the user focusing on the field. It's bad UX when the user goes to the email field he left out, and then after typing, he's now told the email is invalid. To me it makes sense that once a field has been focused, it is no longer "touched".
Or perhaps there is another way to accomplish this, right now?

**Comment by jaredpalmer** [comment]
You can make custom input components / fields that call `props.setFieldTouched(name, false)`  within a custom onChange handler if you really want to i guess.
