### ISSUE TITLE
Cannot create a third party library with connected components

### ISSUE THREAD

**Issue by Lory1990** [jaredpalmer/formik#1778]
## ❓Cannot create a third party library with connected components

Hi guys, 
we have created a third party library with connected components, coded this way

```
[...]
import {connect} from 'formik'

class MyComponent extends React.Component{

    render(){
         return (<div>[....]<div>)
    }
}

export default connect(MyComponent )
```

When i use my librby in my other projects the object `this.props.formik` is empty.... WHY?

thanks!

**Comment by johnrom** [comment]
@Lory1990 the code sample above looks to me like it would work. Can you create a code sandbox with a minimal reproduction of your issue? https://codesandbox.io/s/91q6rxmmrp

**Comment by Lory1990** [comment]
Hi!
We just resolved changing the way we where coding our library. We have used [create-react-library](https://www.npmjs.com/package/create-react-library)  and it has not work.

Now we are developing our library following [this hackernoon article](https://hackernoon.com/creating-a-library-of-react-components-using-create-react-app-without-ejecting-d182df690c6b) an all works well!

Thanks!
