### ISSUE TITLE
<Field> should respect value as an initialValue

### ISSUE THREAD

**Issue by derek-adair** [jaredpalmer/formik#1780]
## 🚀 Feature request
It would be intuitive for formik to respect a fields `value` attribute as an initial value
### Current Behavior
Formik does not submit this as part of the forms `values` array.

### Desired Behavior
Formik to recognize when a <Field> has its value set, and submit it

### Suggested Solution
1. Read any <Field>'s value attribute and have Formik recognize it as an initialValue
2. Ignore if the field has an "initialValue" configured... maybe throw a warning somewhere if both are set.

### Who does this impact? Who is this for?
Newer Formik Users that don't know you need to use initialValues.

### Describe alternatives you've considered
Straight up dropping initialValues and letting users set these like they do in normal html forms, with a fields value attribute.

**Comment by johnrom** [comment]
`initialValues` is a required field. we can really only enforce that via TypeScript, but it should be present for every single documented use of Formik.

Setting a Field's value manually means Formik doesn't know it changed until `onChange`, and then you have to figure out how to change the value via the method used to set it. Here's an example:

```jsx
const MyForm = () => {
    const value = "John Doe";

    return (
        <Formik 
            initialValues={{}}
            onSubmit={(values) => { console.log(values); }}
        >
            <Form>
                // once changed, how is value ever going to reflect FormikState.name?
                <Field name="name" value={value} /> 
            </Form>
        </Formik>
    );
};
```

```jsx
const MyForm = () => {

    return (
        <Formik 
            initialValues={{
                name: "John Doe",
            }}
            onSubmit={(values) => { console.log(values); }}
        >
            <Form>
                // Field is automatically set with Formik.values[name]
                <Field name="name" /> 
            </Form>
        </Formik>
    );
};
```
