### ISSUE TITLE
Value submit adapter

### ISSUE THREAD

**Issue by mehrdad-shokri** [jaredpalmer/formik#1795]
## ❓Question

Suppose I have a date picker which is a custom component in my form.
Its value is the selected date/time timestap, and the onChange method of it gets called with the selected timestamp.
Everything works fine except 1 thing: The API expects the value in ``YYYY-MM-DD THH:mm:ss``  format  

The only solution I can think of is ``setFieldValue('startDate', moment(values.startDateMask).format('YYYY-MM-DD THH:mm:ss'))``  

But I don't like this approach. It required customizing ``onSubmit`` of my form and I guess there should be a better way.  
Does Formik offer some kind of adapter/serializer which essentially bends the input format according to my needs and then submit it?

**Comment by johnrom** [comment]
There are a few other issues about this. 

#1525

If it's okay, I'd like to close this as a duplicate of those because that's where we'll likely track this feature.

**Comment by mehrdad-shokri** [comment]
Done thanks
