### ISSUE TITLE
Example with handleChangeValue and custom input

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/formik#18]

**Comment by jaredpalmer** [comment]
Should probably use either react-autocomplete react-autosuggest

**Comment by eonwhite** [comment]
I dig `react-autosuggest`, could use that. I might have a real example we could adapt actually.

**Comment by richarddd** [comment]
@eonwhite could you share this sample of yours? 😊

**Comment by llermaly** [comment]
@eonwhite yeah, example please
