### ISSUE TITLE
"dirty" gets applied to all instances with the same custom component

### ISSUE THREAD

**Issue by Shaker-Hamdi** [jaredpalmer/formik#1803]
### Current Behavior
When I create a custom input component and try to add a className based on if the input is "dirty" or not, the class gets applied to all the inputs that use this component.

Here's a simple example I created ...
https://codesandbox.io/s/hello-world-h60hj

You'll notice that both inputs use the same custom component "InputComponent", and when you start typing in any one of them, the class gets applied to both of them.

I think the "isValid" is also behaving the same way.

### Expected behavior
The class should be applied to only the dirty input that I'm typing inside.

Am I doing something wrong here?

**Comment by johnrom** [comment]
Hi @Shaker-Hamdi ,

`dirty` means that the form itself is dirty, so all components will read as dirty. I believe the prop you're looking for is `field.meta.touched`. `isValid` also refers to the entire form. Instead, you should check `field.meta.error` is empty.
