### ISSUE TITLE
EnableReinitialize only uses deep equals

### ISSUE THREAD

**Issue by dfmartin** [jaredpalmer/formik#1808]
### Current Behavior

related to issue #1541 (but it is currently closed, and would like to avoid the workaround if possible)

Using v2 latest so this deals with the hooks and we are utilizing hooks as well (e.g. useContext, useReducer)

useEffect for EnableReinitialization is using a deep equal between `initialValues.current` and `props.initialValues`.    In our scenario we are doing the following:

Values are loaded into context and then used as the initial values in the `<Formik />` element.  We provide the user with a reload functionality.  This causes the values to be reloaded from the database.  At this point, the values may be the same or not.  But it is guaranteed to be a different object.  This reload takes place outside of the `<Formik />` element, so we don't have direct access to `resetForm()` without doing some magical lifting out from within the formik render.

### Expected behavior

If the initial values are not the same (i.e. reference equality) **or** not deep equal then the reinitialization would take place.

### Suggested solution(s)

```ts

// current
React.useEffect(() => {
    if (
      enableReinitialize &&
      isMounted.current === true &&
      !isEqual(initialValues.current, props.initialValues)
    ) {
      initialValues.current = props.initialValues;
      resetForm();
    }
  }, [enableReinitialize, props.initialValues, resetForm]);


// proposed
React.useEffect(() => {
    if (
      enableReinitialize &&
      isMounted.current === true &&
      (initialValues.current !== props.initialValues ||
       !isEqual(initialValues.current, props.initialValues))
    ) {
      initialValues.current = props.initialValues;
      resetForm();
    }
  }, [enableReinitialize, props.initialValues, resetForm]);
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | formik@2.0.1-rc.13
| React            | 16.8.6
| TypeScript       | 3.4.5
| Browser          | Chrome 76
| npm/Yarn         | npm - 6.9.0
| Operating System | windows 10

**Comment by johnrom** [comment]
@dfmartin I don't think we should reinitialize on every reference change, because reinitializing formik is _expensive_! However, I do think it'd be pretty nice if we could keep initialValues.current up-to-date in the event that you want to trigger a reset based on a custom Effect of your own.

My proposal:

```jsx
// I think resetForm needs initialValues to have been updated, so this is a bit more verbose than I'd like
React.useEffect(() => {
    let needsReset = enableReinitialize &&
      isMounted.current === true &&
      (
        initialValues.current !== props.initialValues ||
        !isEqual(initialValues.current, props.initialValues)
      );
    initialValues.current = props.initialValues;
    // maybe resetForm can happen before initialValues.current assignment, but Idk. will need testing.
    if (needsReset) {
      resetForm();
    }
  }, [enableReinitialize, props.initialValues, resetForm]);
```
