### ISSUE TITLE
submitForm promise not rejected when form is invalid

### ISSUE THREAD

**Issue by MajronMan** [jaredpalmer/formik#1810]
### Current Behavior

`submitForm` returns a promise that is resolved even when the validation fails.

### Expected behavior

According to documentation,
> Trigger a form submission. The promise will be rejected if form is invalid.

### Reproducible example

https://codesandbox.io/embed/formik-codesandbox-template-230c0

### Suggested solution(s)

Reject the promise if the form is invalid.

### Your environment
 
| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.7 |
| React            | 16.8.6 | 
| Browser          | Google Chrome version 76.0.3809.132 |
| npm/Yarn         | yarn version 1.17.3 |
| Operating System | macOS Mojave version 10.14.6 (18G95) |

**Comment by jsilvax** [comment]
I have the same issue. Any update on reviewing / merging (6daef57)
