### ISSUE TITLE
Allow handling of non-native inputs

### ISSUE THREAD

**Issue by akomm** [jaredpalmer/formik#1818]
## 🚀 Feature request
It should be possible to handle inputs, which are not backed by native input (input, textarea, select).

### Current Behavior
Both formik 1.5.x and 2.x define:

```ts
// excerpt interface FormikHandlers
interface FormikHandlers {
  /** Classic React change handler, keyed by input name */
  handleChange(e: React.ChangeEvent<any>): void;
  /** Preact-like linkState. Will return a handleChange function.  */
  handleChange<T = string | React.ChangeEvent<any>>(
    field: T
  ): T extends React.ChangeEvent<any>
    ? void
    : ((e: string | React.ChangeEvent<any>) => void);
}
```

This requires me to either provide signal in preact linkstate style or as native dom change event. I can not create a pure JS element without linkstate or native dom input, which simply notifies value change passing it to `onChange` (aka `handleChange` API).

### Desired Behavior

It should be possible to notify `onChange` with pure updated value.

### Suggested Solution

Typing:
AFAIK it can be tricky to make this BC to preact API, because of the `T` generic part in :
```ts
interface FormikHandlers {
  handleChange<T = string | React.ChangeEvent<any>>(
    field: T
  ): T extends React.ChangeEvent<any>
    ? void
    : ((e: string | React.ChangeEvent<any>) => void);
}
```

1. add overload like this:
```ts
interface FormikHandlers {
  handleChange<T>(value: T, pure: true): void;
}
```
2. or this:
```ts
interface FormikHandlers {
  handleChange<T>(data: {value: T, field: string}): void;
}
```
Here, the T generic is not needed, however not sure due to the other overloads if it is valid to omit it.

Runtime:
1. Similar, checking the second argument (boolean) to handle the pure value case.
2. check for `{value, field}` structure.

### Who does this impact? Who is this for?

Evenryone who wants to create a pure JS input, which is not backed by DOM and does not want to use linkstate. 

### Describe alternatives you've considered

There is a solution to this I missed? Checked docs and code for both 1.5.x and 2.x and could not find any...

**Comment by akomm** [comment]
So you can fake [this](
https://github.com/jaredpalmer/formik/blob/v1.5.8/src/Formik.tsx#L320-L339):
```ts
// depending on type of input you want to make some props are optional
onChange({target: {name, type, id, value, checked}})
```
However it feels a bit weird.

**Comment by jlefebure** [comment]
+1, this is the last feature that I need to switch from Formsy to Formik.

**Comment by akomm** [comment]
This is one of things, that would make formik not only good, but perfect.
Currently there are a few issues:
1. this one, currently it is to native-html-input-centric
2. files handled incorrectly, value is just some fake name, because that is how file input handles it. So need to handle files out of form or make a custom component, which has to workaround 1.
3. hooks are great. but Formik is still required for context. Really don't like that children render semantic and all the nesting. It sometimes requires me to hoist `Formik` heigher, than its useful semantically to get access to its props (submit, etc.). Or make remote submit which adds noise too. I see the issues behind changing it though.

**Comment by johnrom** [comment]
I'm not really sure what the issue is here. What benefit does `handleChange(value, true)` provide over `handleChange(fieldName)(value)` (and where is the field name?!)? Preact linkState is not required, it's just using the same style that Preact likes to use by creating the event handler with `onChange={handleChange(fieldName)}`.

```
export const MyNonField = () => {
  const [field] = useField("lastRendered");
  React.useEffect(() => {
      field.handleChange("lastRendered", Date.now());
  });
}
```

**Comment by akomm** [comment]
@johnrom 

1. field (at least from TS perspective) does not have `handleChange`.
2. if I consider you meant `field.onChange`:
2.1. `field.handleChange("lastRendered")(Date.now())` fails at runtime with `TypeError: eventOrTextValue is undefined`. I already inspected the related [source](https://github.com/jaredpalmer/formik/blob/d4049f2da7e2e8811b498ea8013b77af063c6c8a/packages/formik/src/Formik.tsx#L601-L667), before posting this issue. 
2.2. It still types value as `string` which is quite html-input-centric as mentioned before.

I did not assume 2.1 to be a bug, but judging by your post, either there is some misunderstanding, or you know it **should** work like you'v posten, then it is a bug.
In any case, 2.2 remains an issue (TS).

**Comment by akomm** [comment]
@johnrom I actually checked the related [source](https://github.com/jaredpalmer/formik/blob/d4049f2da7e2e8811b498ea8013b77af063c6c8a/packages/formik/src/Formik.tsx#L601-L667), before posting the issue. The problem here is that `field.handleChange("lastRendered")(Date.now())` will not work and fail both at runtime and typecheck (TS), because `Date.now()` is not a string. 

Specifically this part is responsible:
```ts
const handleChange = useEventCallback(
  (
    eventOrPath: string | React.ChangeEvent<any>
  ): void | ((eventOrTextValue: string | React.ChangeEvent<any>) => void) => {
    if (isString(eventOrPath)) {
      return event => executeChange(event, eventOrPath);
    } else {
      executeChange(eventOrPath);
    }
  }
);
```

**Comment by johnrom** [comment]
OK, I understand now. You're looking for a change handler that can accept the already-parsed value, for example string converted to int, but still trigger normal side effects like validation and setTouched?

I think that's fine, especially since we'll be expanding parse capabilities here: #2255

**Comment by akomm** [comment]
@johnrom Thanks. `setFieldValue` is only available on `FormikProps`. Its not available from `useField` or `Field`, so in this case not solving the issue. When using `useField` it does not seem like I have access to helpers, which has `setValue` either. The #2255 looks good. It looks like its also removing the currying, probably for similar reasons.

**Comment by johnrom** [comment]
The value can't be type safe, due to limitations with typescript (no way to type `setFieldValue('myField.mySubfield', value);`). With `true` as the third parameter, it will validate. It will not set touched, because that only happens onBlur, but you can also call `setFieldTouched`.

**Comment by akomm** [comment]
Thanks.

As said before, `setFieldValue` is not accessible in component used by `Field` or `useField`. However `useField` has `FormikHelpers` which provides `setValue`, `setTouched` and `setError`. Validation does not work either and error has to be set via the `setError`. However the validation for the input on form level will not work. It has to be handled in the component and the error set there.

So its a workaround with many many drawbacks. But the PR you'v linked looks like a solution to the problem.

**Comment by johnrom** [comment]
You can use `useFormikContext().setFieldValue` within any functional component descendent of Formik / FormikProvider (if using useFormik). If you're within the render callback of Formik, you can use setFieldValue from the parameters.

If you're using class components, you'll have to pass a prop to your component because hooks are not supported in classes.

**Comment by akomm** [comment]
@johnrom thanks. It works. Btw. I had to `setFieldTouched` before `setFieldValue`, otherwise the errors would reset. Not sure if it is a desired behavior.

**Comment by akomm** [comment]
Going to close this, as the feature is being on a PR currently and there is a workaround until its up. Thanks.
