### ISSUE TITLE
`component` instead of `as`

### ISSUE THREAD

**Issue by vigneshwaran-chandrasekaran** [jaredpalmer/formik#1823]
https://github.com/jaredpalmer/formik/blob/master/examples/CustomInputs.js

change as="select" to component="selecd" as shows error while running

**Comment by johnrom** [comment]
@vigneshwaran-chandrasekaran that documentation is for v2, which is currently in beta. In v2, `as` is the correct prop (component will log a warning in development):

https://codesandbox.io/s/formik-2-sx8tc

v1 examples are here: https://github.com/jaredpalmer/formik/tree/v1.5.8

**Comment by vigneshwaran-chandrasekaran** [comment]
Thanks its working now
