### ISSUE TITLE
What stops us from pushing 2.0.1 from pushing it stable?

### ISSUE THREAD

**Issue by AM-NiceDay** [jaredpalmer/formik#1835]
Hey there, Formik useField hook would dramatically simplify the component system on my project. What can we (people, who also need it) do to push the latest release "live"?

**Comment by jaredpalmer** [comment]
Revamp the tutorial, update documentation, examples, and migration guide.

**Comment by johnrom** [comment]
Also probably double checking [these](https://github.com/jaredpalmer/formik/issues?q=is%3Aopen+is%3Aissue+label%3Av2) and triaging [these](https://github.com/jaredpalmer/formik/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+v2) and [these](https://github.com/jaredpalmer/formik/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+2.0) to see if there are any showstoppers.

**Comment by AM-NiceDay** [comment]
Does it make sense to create a todo list on missing documentation units?

**Comment by johnrom** [comment]
I think it makes sense to create an issue for documentation (if there isn't one already) and add it to the [v2.0 milestone](https://github.com/jaredpalmer/formik/milestone/3), as well as adding any items from the above triage that are required before 2.0 is released. The v2.0 milestone should reflect everything that needs to be done before 2.0 is released, and when everything _is done_, we should be able to set a release date.

In terms of actually itemizing the documentation, I'm not sure that would be super helpful as I think it would take almost as much time as actually modifying the documentation. But you're free to make a list if you want!

**Comment by AM-NiceDay** [comment]
That absolutely makes sense
