### ISSUE TITLE
v2 Documentation

### ISSUE THREAD

**Issue by johnrom** [jaredpalmer/formik#1836]
## 📖 Documenting v2

Getting Started

- [ ] Overview
- [ ] Quickstart
- [ ] Thinking in Formik
- [ ] Resources

Guides

- [ ] Validation
- [ ] Arrays and Nested Objects
- [ ] TypeScript
- [ ] React Native
- [ ] Form Submission

API Reference

- [ ] `<Formik />`
- [ ] `withFormik()`
- [ ] `<Field />`
- [ ] `useField()`
- [ ] `useFormikContext()`
- [ ] `<FieldArray />`
- [ ] `<Form />`
- [ ] `<ErrorMessage />`
- [ ] `connect()`
- [ ] `<FastField />`

**Comment by LukeSugiura** [comment]
It would be great if the v2 documentation has more advanced React Native examples such as field-level validation.
I was a bit confused at first since the current documentation only describes how to use with FormikConfig (e.g. handleChange)

I'm imagining like...

```
function ReaxtNativeFieldValidationExample() {
  return (
    <Formik
      initialState={{email: ''}}
      onSubmit={console.log}
    >
      <>
        <TextField
          name='email'
          validate={value => value === '' ? 'Require' : undefined}
        >
      </>
    </Formik>
  )
}

interface ITextFieldProps extends TextInputProps {
  name: string
  validate?: FieldValidator
}

function TextField({name, validate, ...textInputProps}: ITextFieldProps) {
  const [field, meta] = useField({name, validate})
  return (
    <View>
      <TextInput
        {...textInputProps}
        onBlur={field.onBlur(name)}
        onChangeText={field.onChange(name)}
        value={field.value}
      />
      {meta.touched && meta.error ? (
        <Text>{meta.error}</Text>
      ) : null}
    </View>
  )
}
```

**Comment by gustaff-weldon** [comment]
@johnrom @jaredpalmer is v2 fairly stable? I do not mind waiting for documentation as long as the API is stabilised. I'm starting a new project with formik and need to decide whether I can use v2 or I need to stick to 1.5.8 and deal with the upgrade later?

**Comment by koverg70** [comment]
There are a few typos on /docs/api/useFormikContext.md example:
1. formik.values.token.length => values.token.length
2. formik.submitForm(); => submitForm();
3. the ending tag for <Formik> is mistyped as </Form> instead of </Formik>

**Comment by jaredpalmer** [comment]
Can people submit PR’s with typo corrections?
