### ISSUE TITLE
Formik as a controlled component

### ISSUE THREAD

**Issue by julienvincent** [jaredpalmer/formik#184]
It would be nice to be able to use Formik as a controlled component, perhaps as an 'advanced' API. This will allow more control over the forms state and allow triggers for submitting the form outside of Formik's render.

For this to be possible it would probably be necessary to also expose any validation tools used internally when `handleSubmit` is called.

Thoughts?

**Comment by jaredpalmer** [comment]
Just use vanilla React if you need more control

**Comment by julienvincent** [comment]
Perhaps this could have a little more discussion around it, even if just to give future people reading an understanding of why or why not the decision was made.

IMO this would add significant value to the library with minimal code changes required - which I say with little knowledge of the architecture of the library so the latter may not be true.

What are your objections to using `<Formik />` as a controlled component?

**Comment by jaredpalmer** [comment]
Are you suggesting something like:  `<Formik values={} touched={} errors={} />` ?

**Comment by julienvincent** [comment]
Yes.

I may have over complicated the initial request/proposal a bit by mentioning exposing validation tools and submitting outside of Formik. The simplest form of the proposal would just be to introduce `values`, `touched`, `errors` and some `onChange` handler.

**Comment by jpdesigndev** [comment]
@julienvincent @jaredpalmer I'm evaluating this lib now. Is this not currently possible/feasible?

**Comment by julienvincent** [comment]
Only when the submit handler is fired (unless there is another way I missed?).
