### ISSUE TITLE
Optimize <Field />

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/formik#185]
Pretty much did all the leg work...just need add TypeScript and decide if we can get away with shallow comparison on non-string components or if we need to use isEqual.

For those who are here... This version of <Field> will optimize string components (i.e. `component="input" component="select" but NOT component={MyField}`) such that they will only update if their respective `values[name]`  changes where `name` is `<Field name="..."/>`.

```js

import React from 'react';
import PropTypes from 'prop-types';
import isEqual from 'lodash.isequal';

class Field extends React.Component {
  static contextTypes = {
    formik: PropTypes.object,
  };

  shouldComponentUpdate(nextProps, nextState, { formik }) {
    const { name, component } = this.props;

    if (typeof component === 'string') {
      if (formik.values[name] !== this.context.formik.values[name]) {
        return true;
      }
      const nextPropsKeys = Object.keys(nextProps);

      return (
        nextPropsKeys.length !== Object.keys(this.props).length ||
        nextPropsKeys.some(prop => {
          return !isEqual(this.props[prop], nextProps[prop]);
        })
      );
    }

    // const nextFormikKeys = Object.keys(formik);
    // return nextFormikKeys.some(prop => {
    //   return !isequal(this.context.formik[prop], formik[prop]);
    // });

    return formik !== this.context.formik;
  }

  render() {
    const { name, type, value, component, ...props } = this.props;
    const { formik } = this.context;
    const field = {
      value:
        type === 'radio' || type === 'checkbox' ? value : formik.values[name],
      name,
      onChange: formik.handleChange,
      onBlur: formik.handleBlur,
    };
    const bag =
      typeof component === 'string'
        ? field
        : {
            field,
            form: formik,
          };
    return React.createElement(component, {
      ...props,
      ...bag,
    });
  }
}```

**Comment by sibelius** [comment]
What about this https://gist.github.com/sibelius/bd2fcb5b64168150d7b24000268fd6d9?

```jsx
import * as React from 'react';
import PropTypes from 'prop-types';

import type { FormikContext } from 'formik';

type Props = {
  name: string,
} & FormikContext;
export default class FormikReactNativeTextInput extends React.Component<Props> {
  static contextTypes = {
    formik: PropTypes.object,
  };

  handleChange = value => {
    this.context.formik.setFieldValue(this.props.name, value);
  };

  handleBlur = () => {
    this.context.formik.setFieldTouched(this.props.name, true);
  };

  render() {
    // we want to pass through all the props except for onChangeText
    const { onChangeText, ...otherProps } = this.props;
    const { name } = this.props;
    const { formik } = this.context;

    const wasTouched = formik.dirty ? formik.touched[name] : false;
    const fieldError = wasTouched && formik.errors[name];

    return (
      <TextInput
        value={formik.values[name]}
        onChangeText={this.handleChange}
        onBlur={this.handleBlur}
        {...otherProps}
      />
    );
  }
}
```

**Comment by ajinathidhate** [comment]
import { Field, Form, Formik } from "formik";
import * as React from "react";
import * as ReactDOM from "react-dom";
import { connect } from "react-redux";
import { Link, RouteComponentProps } from "react-router-dom";
import Input from "react-validation/build/input";
import { error } from "util";
import Yup from "yup";
class KzForm extends React.Component<RouteComponentProps<{}>, {}> {
    constructor(props: any) {
        super(props);
        this.state = {
            email: "",
            password: "",
        };
    }
    public handleSubmit(e) {
        e.preventDefault();
        // tslint:disable-next-line:no-console
        console.log(this.state.email);
        // tslint:disable-next-line:no-console
        console.log(this.state.password);
    }
    public handleChange(e) {
        // tslint:disable-next-line:no-console
        console.log(e.target.value);
        // tslint:disable-next-line:no-console
        console.log(e.target.name);
        const returnObj = {};
        returnObj[e.target.name] = e.target.value;
        this.setState(returnObj);
    }
    public handleBlur(e) {
        const a = e.target.name;
        // alert(a);
    }
    public render() {
        return (
            <Formik
                validationSchema={Yup.object().shape({
                    email: Yup.string().email("Invalid email address").required("Email is required!"),
                })}
                initialValues={{
                    email: " ",
                    password: " ",
                }}
                onSubmit={(values, actions) => {
                    setTimeout(() => {
                        alert(JSON.stringify(values, null, 2));
                        actions.setSubmitting(false);
                    }, 1000);
                }}
                render={({ values, touched, errors, dirty, isSubmitting }) => (
                    <form className="p-5" onSubmit={this.handleSubmit}>
                        <div className="form-group">
                            <label>Email</label>
                            <input name="email" type="text"

                                className={`form-control ${Error.email && Touch.email && "is-invalid"}`}
                                onChange={this.handleChange}
                                onBlur={this.handleBlur} />
                            {Error.email && Touch.email &&
                                <div className="invalid-feedback">
                                    {Error.email}
                                </div>}
                        </div>
                        <div className="form-group">
                            <label>Password</label>
                            <input name="password" type="password"
                                className={`form-control ${Error.password && Touch.password && "is-invalid"}`}
                                onChange={this.handleChange}
                                onBlur={this.handleBlur} />
                            {Error.password && Touch.password &&
                                <div className="invalid-feedback">
                                    {Error.password}
                                </div>}
                        </div>
                        <button type="submit" className="btn btn-outline-primary"
                            {isSubmitting ? 'Loading' : 'Submit'}>
                            Submit
                          </button>
                    </form>
                )}
            />
        );
    }
    // tslint:disable-next-line:align
} export default KzForm;

**Comment by ajinathidhate** [comment]
i am working with this KzFrom..but i got error while validation.please help me out.how to export two class and validate.
