### ISSUE TITLE
Form type doesn't support ref

### ISSUE THREAD

**Issue by ulitiy** [jaredpalmer/formik#1851]
### Current Behavior

FormikFormProps doesn't have ref.

### Expected behavior

FormikFormProps should pass ref through to the `<form/>` (without TypeScript typization issues).

### Suggested solution(s)

`<form/>` is `React.DetailedHTMLProps<React.FormHTMLAttributes<HTMLFormElement>, HTMLFormElement>`, not `React.FormHTMLAttributes<HTMLFormElement>`

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.8
| React            | 16.8.22
| TypeScript       | 3.5.2

**Comment by gzzo** [comment]
See https://github.com/jaredpalmer/formik/pull/1056

**Comment by ulitiy** [comment]
@gzzo yeah... Seems the author is irresponsive though. Not the first issue/PR ignored.

**Comment by elkinjosetm** [comment]
Any workaround for this issue?

**Comment by ulitiy** [comment]
@elkinjosetm Implement your own Form component and use it instead of the default one.

**Comment by elkinjosetm** [comment]
> @elkinjosetm Implement your own Form component and use it instead of the default one.

Yeah that's a possibility, but I don't I already have quite a few logic around Formik v1. Actually, this is the only thing that is preventing me to upgrade to v2. I'll wait a little more without upgrading, to see if the official support is introduced back again.

**Comment by jaredpalmer** [comment]
Upgrade to 2.0.3. Form now accepts forward ref.

**Comment by ulitiy** [comment]
@jaredpalmer sorry for being toxic
