### ISSUE TITLE
Important License clash. This is not a pure MIT license

### ISSUE THREAD

**Issue by Nomeasmo** [jaredpalmer/formik#1883]
## 📖 Documentation
Since Formik in version 1.5.8 uses create-react-context in version 0.2.3 we either need to replace that module version or expose the limitations mentioned there also for this package.

License for version 0.2.3 needs to be exposed for Formik as well:
https://github.com/jamiebuilds/create-react-context/blob/v0.2.3/LICENSE

License for version 0.3.0 is a pure MIT license
https://github.com/jamiebuilds/create-react-context/blob/v0.3.0/LICENSE

Recommendation is left up to the Formik team of cause...

**Comment by batusai513** [comment]
https://github.com/StringEpsilon/mini-create-react-context
