### ISSUE TITLE
isInitialValid with Yup

### ISSUE THREAD

**Issue by eric-basley** [jaredpalmer/formik#189]
I'm using Yup has schema validator, but cannot find a way to use isInitialValid with Yup!
Yup schema validation is asynchronous, isInitialValid synchrone

How can we plug all together to check validation of initialValues ?

Why don't you check validation of initialValues at mount time ?

Regards.

Thanks for your work.

Eric

**Comment by jaredpalmer** [comment]
`isInitialValid` needs to be sync to support SSR so that limits what we can do here. See #94  #97

**Comment by rosskevin** [comment]
@ctavan forked yup so he could move forward sync. https://github.com/ctavan/jupp

Perhaps that helps?

**Comment by frank-west-iii** [comment]
@jaredpalmer, this was closed with the comments that `isInitialValid` needs to be sync and then the comment that yup is now sync. However it is not clear to me how to make `isInitialValid` use my `validationSchema` to set it's value. Any direction would be awesome. Cheers.

**Comment by Sarvarr** [comment]
> For anyone stumbling across this issue, I was able to make something like the following work:
> 
> ```js
> const validationSchema = (props)=>{ 
return Yup.object().shape({
...
})
 }
> const mapPropsToValues = (props)=>{
return {

}
}
> 
> export const Form = withFormik({
>   isInitialValid: props => validationSchema(props).isValidSync(mapPropsToValues(props)),
>   mapPropsToValues,
>   validationSchema,
>   ...otherFormikOptions
> })(MyForm);
> ```
