### ISSUE TITLE
Simplified validation (Declarative Validation)

### ISSUE THREAD

**Issue by kuzmycz** [jaredpalmer/formik#1906]
## 🚀 Feature request
I propose providing a simplified validation that would support 80% of the validations. The aim is to reduce the amount of boilerplate

### Current Behavior
For Field Level validation you provide a validation expression or function
```
const isRequired = message => value => (!!value ? undefined : message);
...

<label htmlFor="username">Username</label>
    <div>
            <Field
                  name="username"
                  validate={isRequired('This field is required')}**
                  type="text"
                  placeholder="Username"
            />
            <ErrorMessage name="username" />
      </div>
      <br />
      <div>
            <Field
              name="email"
              validate={isRequired('This field is required')}
              type="text"
              placeholder="Email"
            />
            <ErrorMessage name="email" />
      </div>
```
### Desired Behavior
The aim is to provide a set of props that perform the majority of validations that you need
e.g. 
```
<label htmlFor="username">Username</label>
    <div>
            <Field
                  name="username"
                  required
                  type="text"
                  placeholder="Username"
            />
            <ErrorMessage name="username" />
      </div>
      <br />
      <div>
            <Field
                  name="email"
                   required
                  minLength={8}
                  type="text"
                  placeholder="Email"
            />
            <ErrorMessage name="email" />
      </div>

```
Note:
You can also reference other fields 
e.g. <Field required={!!values.someOtheField} .../>  
This would mean that the field is required if someOtherField has a value.

### Suggested Solution

I have a working version which I can make available.

The solution looks like 
Field.txs
```
...
function createValidator(required: boolean, minLength: number, maxLength: number, validate: (value: any) => string) {
  return((value: any) => {
  
    if (required  && !(!!value)) {
      return('The field is required');
    }
    if(minLength != undefined && value != undefined && value.length < minLength) {
      return(`The field must be at least ${minLength} characters long.`);
    }
    if(maxLength != undefined && value != undefined && value.length < minLength) {
      return(`The field must be no more than ${maxLength} characters long.`);
    }

    if(validate) {
      return validate(value);
    }

    return undefined;
  })
}

...

  React.useEffect(() => {
    registerField(name, {
      validate: createValidator(required, minLength, maxLength, validate),
    });
    return () => {
      unregisterField(name);
    };
  }, [registerField, unregisterField, name, required, minLength, maxLength, validate]);
```

Note: these are just a sample. We can add 
- min, max, (for numbers)
- isEmail
- matches (for some pattern)

### Who does this impact? Who is this for?

Anyone interested in reducing boilerplate for validations

### Describe alternatives you've considered

N/A

### Additional context

If approved, I would be happy to do the work...

**Comment by gustavopch** [comment]
@kuzmycz There's Yup (https://github.com/jquense/yup), and it's pretty good at validation (not only for forms, but also for backend and wherever else you may want to use it).

IMHO any energy spent replicating what's already solved by other lib would be better spent solving new problems, adding news features, fixing bugs, improving the integration between this lib and the other one etc.

**Comment by kuzmycz** [comment]
Hi @gustavopch ,

Not everyone wants to add yup to their project. Yup adds complexity, if you don't need the advanced validations then using field constraints (as I am calling now) may be better suited. I think that, for the customer, field constraints is simpler and requires less coding to implement. 

Another advantage is that field constraints are closer to the field (actually right on them). This improves readability. 

Is it a replacement for Yup? No. The proposal is for something simple that takes away some complexity and reduces coding.

I have completed the work. The pull is called "Field Constraints". If you want it great, if not that is ok too. I thought it would be something that was useful to formic an its customers.

**Comment by BilyachenkoOY** [comment]
What about messages localization?

**Comment by gustavopch** [comment]
> What about messages localization?

@kuzmycz See what I mean? I'm afraid Formik would have to reinvent what can already be done with Yup (https://github.com/jquense/yup#using-a-custom-locale-dictionary).

Of course you can also use the `validate` prop to plug your own validation functions. I'm afraid bringing validation logic to Formik will add complexity, room for bugs, more API surface, extra bundle size, but after all not enough flexibility to be usable in most cases.

I disagree that it will improve the readability as something like `<Field name="email" validate={validateEmail} />` or `<Field name="email" validate={combineValidators(isRequired, isEmail)} />` are already pretty readable, flexible and easy to code in userland.

**Comment by kuzmycz** [comment]
Hello @gustavopch &  @BilyachenkoOY,
Localization is a valid requirement. It was recommended by @jaredpalmer to optionally provide a message that could be localized.

For example,

```
<Field name="username"
                  required={[true, 'User name is required']}
                  maxLength={[50, 'The user name can be no longer than 50 characters long']} 
                  type="text"
                  placeholder="Username"></Field>

```
My view of a library is that its intent is to make the user's life easier. However, there may be complex code under the hood to achieve this. Is a change like this worth it? It depends on the value it gives users. I wouldn't base it on potential to create bugs or whether it makes the library harder to maintain (this is more of an implementation issue).

For me, all my fields across all of my projects are validated and the majority of validations are shape related. That is, isRequired, minLength and maxLength.

This proposal would have value to me. The question is, does it add value for the larger Formik community?

**Comment by gustavopch** [comment]
@kuzmycz 

- What if I need one field to depend on the value of another? E.g. `endDate` must be after `startDate`.
- What if I have a custom `validate` that also needs a localized message? Will it follow a completely different logic in order to get localization to work?
- In case I decide to go with Yup or custom validation functions, will I get extra size in my bundle for nothing? If so, how many extra KBs?

I think all these questions, especially the latter, must be taken into account.

**Comment by kuzmycz** [comment]
Hello @gustavopch,
1. Dependent fields is supported. It's just standard react. If you specify another field in a constraint value then it will be used.

This is a silly example, but it gives you and idea of what you can do,
```
           <Field
                  name="paymentType"
                  required
                  type="text"
                  placeholder="Payment Type"
            />
           <Field
                  name="cardNumber"
                  required={values.paymentType == 'cc'}
                  numeric
                  type="text"
                  placeholder="Credit Card Number"
            />
```
2. The current implementation is rudimentary and the localized message is prebuilt and delivered to the field. If there was a need, it wouldn't take much to allow a function to be passed for dynamic messages. The overhead to do this would be minimal.

3. The size increase is about 4K before compression or 1.2K after compression.

**Comment by gustavopch** [comment]
@kuzmycz Interesting. Perhaps using a different component like `ValidatedField` would be enough to let those extra KBs out of the bundles of those who won't use this feature.

**Comment by jaredpalmer** [comment]
This can be implemented in user land and published as a custom kind of Field.
