### ISSUE TITLE
Is there a way to deliver additional props with the render/component props? 

### ISSUE THREAD

**Issue by kwhitaker** [jaredpalmer/formik#194]
Our org is looking at Formik to replace redux-form.  Some of our forms are fairly complex, and rely on some redux store states to enable/disable or display/hide certain elements within a form.  Is there a way (or what is the "official" pattern) to accomplish this in Formik - that is to pass these additional objects down into the Formik component?

Thanks.

**Comment by jaredpalmer** [comment]
Where did this logic live before? Within the redux-form hoc?

**Comment by jaredpalmer** [comment]
## `<Formik/>`

I know that lots of ppl from Redux-land love the HoC approach. However, the <Formik /> component is actually more powerful because you have full access to React state, props, and lifecycle methods directly. It's just plain React! 

```js
<Formik
    initialValues={...}
    validate={...}
    onSubmit={ ... }
    render={formikProps => 
       <Component  {...formikProps} {...whatever you need} /> 
    } 
/>
```

## HoC

if you are using redux: 

```js

export default connect({...})(withFormik({ .. })(Comp))

// or with recompose 

export default compose (
   connect({ ... })
   withFormik({ ... })
)(Component)

```

Also FYI, `withFormik()` is calls`<Formik render />` under the hood anyways. 😎

**Comment by kwhitaker** [comment]
Nice! The first code block i what I was looking for. Thanks so much :D

**Comment by mdekrey** [comment]
Thanks for responding so quickly, @jaredpalmer!

**Comment by sarimj-cc** [comment]
Can't you guys write a good easy code for demonstrating something as an example because there are many users who are beginners..

**Comment by josoroma** [comment]
Hi!

Sorry, but I don't get how to connect Formik with the following Container, and what should I do with the handleSubmit method inside mapDispatchToProps?

**The Container:**

```
import { connect } from 'react-redux';
import { loginRequest } from '../redux/actions';
import SignInForm from './SignInForm.component';

const mapDispatchToProps = dispatch => {
  const handleClickShowPassword = () => {
    this.setState({ showPassword: !this.state.showPassword });
  }

  const handleSubmit = e => {
    e.preventDefault();

    const payload = {
      username: 'pablo.orozco@gorillalogic.com', // this.state.username,
      password: 'EasyToGuess$135', // this.state.password,
    }

    try {
      dispatch(loginRequest(payload));
    } catch (err) {
      // TODO - Replace with a react logger or with a direct message to the user.
      console.error('===> Singin - handleSubmit - err', err);
    }
  };

  return {
    handleClickShowPassword,
    handleSubmit,
  }
};

const mapStateToProps = state => {
  const { isLoading } = state.user;
  const showPassword = false;

  return {
    isLoading,
    showPassword,
  }
};

export default connect(mapStateToProps, mapDispatchToProps)(SignInForm);
```

**the presentational component:**

```
import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import { withStyles } from '@material-ui/core/styles';
import Button from '@material-ui/core/Button';
import IconButton from '@material-ui/core/IconButton';
import Input from '@material-ui/core/Input';
import InputLabel from '@material-ui/core/InputLabel';
import InputAdornment from '@material-ui/core/InputAdornment';
import FormControl from '@material-ui/core/FormControl';
import TextField from '@material-ui/core/TextField';
import Visibility from '@material-ui/icons/Visibility';
import VisibilityOff from '@material-ui/icons/VisibilityOff';

const styles = theme => ({
  root: {
    display: 'flex',
    flexWrap: 'wrap',
  },
  margin: {
    margin: theme.spacing.unit,
  },
  withoutLabel: {
    marginTop: theme.spacing.unit * 3,
  },
  textField: {
    flexBasis: 200,
  },
});

const SignInForm = ({
  classes,
  handleClickShowPassword,
  handleSubmit,
  isLoading,
  showPassword,
}) => {
  if (isLoading) return null;

  return(
    <form
      noValidate
      autoComplete="off"
      onSubmit={(e) => { handleSubmit(e) } }
    >
      <TextField
        id="username"
        label="Username"
        margin="normal"
      />
      <FormControl className={classNames(classes.margin, classes.textField)}>
        <InputLabel htmlFor="password">Password</InputLabel>
        <Input
          id="password"
          type={showPassword ? 'text' : 'password'}
          endAdornment={
            <InputAdornment position="end">
              <IconButton
                onClick={handleClickShowPassword}
              >
                {showPassword ? <VisibilityOff /> : <Visibility />}
              </IconButton>
            </InputAdornment>
          }
        />
      </FormControl>
      <Button
        variant="contained"
        color="primary"
        type="submit"
        label="Submit"
        className={classes.button}
      >
        Login
      </Button>
    </form>
  );
};

SignInForm.propTypes = {
  classes: PropTypes.object.isRequired,
  handleClickShowPassword: PropTypes.func.isRequired,
  handleSubmit: PropTypes.func.isRequired,
  isLoading: PropTypes.bool.isRequired,
  showPassword: PropTypes.bool.isRequired,
};

export default withStyles(styles)(SignInForm);
```

Thank you!

**Comment by KeweiCodes** [comment]
As a beginner to Formik, I took to HoC approach purely because it was the number one approach listed on home docs. Perhaps we can swap that around and make using render number one? :)

**Comment by marth00165** [comment]
where do i import compose from?

**Comment by johnrom** [comment]
@marth00165 if you're looking for `recompose` documentation, I'd check out https://github.com/acdlite/recompose

**Comment by mdekrey** [comment]
@marth00165, we were using https://ramdajs.com/docs/#compose.

**Comment by nilamsavani91** [comment]
I am passing prop from one component to its child component and in my child component I want to use withFormik() hook. How can I get the values sent by my parent component in child component?

**Comment by nesibeyyubov** [comment]
> I am passing prop from one component to its child component and in my child component I want to use withFormik() hook. How can I get the values sent by my parent component in child component?

You can get it in handleSubmit function (inside withFormik object) as a parametr (in formikBag provides this for you)

**Comment by Cuantico** [comment]
> I am passing prop from one component to its child component and in my child component I want to use withFormik() hook. How can I get the values sent by my parent component in child component?

const MyComponent = props => {
    function handleSubmit(values, { setSubmitting }) {
        // handle
    }

    return (
        <CreateForm handleSubmit={ handleSubmit }/>
    )
}

const CreateForm = props => {
    const { handleSubmit } = props;

    const MyFormWithFormik = withFormik({
        // ...,
        handleSubmit: handleSubmit,
    })(MyForm);

    return <MyFormWithFormik/>
}

**Comment by haseebanwar** [comment]
Formik `render` prop has been deprecated and will be removed in future versions of Formik. 
### Deprecated:

``` jsx
<Formik
  initialValues={{ foo: 'bar' }}
  onSubmit={() => console.log('submit')}
  render={(formikProps) => <NewComponent {...props} {...formikProps} />}
/>
```

### New way:

Now, to pass props to the child component, use a child callback function instead like this:

``` jsx
<Formik
  initialValues={{ foo: 'bar' }}
  onSubmit={() => console.log('submit')}
>
    {(formikProps) => <NewComponent {...props} {...formikProps} />}
</Formik>
```
