### ISSUE TITLE
Dirty handling workflow

### ISSUE THREAD

**Issue by slightlytyler** [jaredpalmer/formik#195]
Trying to implement a workflow as follows:

Users sees a pristine form, save button is hidden => user begins typing in input, form becomes dirty, save button is shown => user saves, form becomes pristine, save button is hidden

Is this currently possible in formik? `dirty` is remaining as false for me up until the form submitted and is never reset afterwards

**Comment by jaredpalmer** [comment]
Is save supposed to actually submit the `<form>`?

**Comment by slightlytyler** [comment]
yes "save" is either clicking the submit button or hitting enter from an appropriate form

**Comment by slightlytyler** [comment]
Second part of this (returning to "pristine" after save) seems to be accomplished by calling `resetForm(values)`. Is that the intended API?

**Comment by slightlytyler** [comment]
Here's my config for reference:

```js
const container = withFormik({
  handleSubmit: (values, { props, resetForm }) =>
    props
      .handleSubmit(omit(['httpProxy', 'httpsProxy'], values))
      .then(() => resetForm(values))
      .catch(resetForm),
  mapPropsToValues: get('data'),
  validateOnBlur: false,
  validateOnChange: true,
  validationSchema: yup.object({
    dtrHost: yup.string().required(),
    webTlsCA: yup.string().required(),
    webTlsCert: yup.string().required(),
  }),
});
```

**Comment by jaredpalmer** [comment]
Yes that's what happens when you pass values to `resetForm(values)` is for.

**Comment by jaredpalmer** [comment]
I think this is what you want. https://codesandbox.io/s/0qr1wkp49w

**Comment by slightlytyler** [comment]
Very close but I actually need `dirty` to toggle `onChange` rather than `onSubmit`. is that possible?

**Comment by jaredpalmer** [comment]
hmmm....

I think we should mutate `this.initialValues` if someone passes values to `resetForm(values)`. That would allow you to check if `values` are different

**Comment by slightlytyler** [comment]
Does that fix the issue with dirty not toggling `onChange`? Or is #197 solving a different problem?

**Comment by slightlytyler** [comment]
I had assumed on first use that `validateOnChange` we also cause dirty checking to happen then as well

**Comment by jaredpalmer** [comment]
Formik `validateOnChange` and `validateOnBlur` are true by default in 0.9.2 

This change would allow you to check the equality of initialValues with current values, while not making a breaking change. 

I want to have a larger conversation about meanings of `pristine` and `dirty`, but this patch would let you ship this today..

```
// if values is flat
{props.values !== props.initialValues &&
  <button type="submit">Save</button>
}

// otherwise
{!isEqual(props.values, props.initialValues) &&
  <button type="submit">Save</button>
}
```

**Comment by slightlytyler** [comment]
Thank you, looks like this is going to work fine (just have to do a shallow equal check sine `props.values` ref changes). Would love to be a part of that conversation. My quick two cents:

`dirty` and `pristine` to me are the inverse of each other so they could be represented by the same prop. If a form's current values match the initial values it's pristine, if not it's dirty. I think your change in #197 actually works towards this as `initialValues` should be set to a new value on `resetForm(values)`

**Comment by jaredpalmer** [comment]
Released in 0.9.4

**Comment by paramjitkaur** [comment]
How do we test dirty in HOC withFormik. In the documentation I see that isDirty is there in the Render formik but I didnt see it being there with withFormik use.Just wanted to know if we can use isInitialValid for the same dirty check there

**Comment by insidewhy** [comment]
Was really surprised to learn that `dirty` means "different to initial values" rather than "different to submitted values" as in every other form library I've used. I tried to `resetValues` to the submitted values, and that cleared every single input in my form. Argh.

**Comment by JaredDahlke** [comment]
has anyone figured out a solution to this? I have a form that brings in initial values from props dynamically, the user changes the values, and after that the form is always dirty. if i resetForm then it goes back to initial values. I'm using mapPropsToValues

**Comment by filipkowal** [comment]
[#197](https://github.com/formium/formik/pull/197) fixed the issue. To have the buttons disabled when they should:

```js
<Button
    disabled={!dirty || isSubmitting}
    type="submit"
    onClick={() => {
      resetForm({ values });
      submitForm();
    }}
>
```
