### ISSUE TITLE
[v2] onChange handlers should accept values in addition to events like they did in V1

### ISSUE THREAD

**Issue by connor-odoherty** [jaredpalmer/formik#1958]
### Current Behavior

The handler returned by calling onChange('myfieldname') returns a new onChange handler that only accepts events as input:

```
func ƒ (event) {
        return executeChange(event, eventOrPath);
      }
```

### Desired Behavior

The onChange handler should accept an event OR value, as it did in v1:

```
func ƒ (eventOrValue) {
            return executeChange(eventOrValue, path_1);
          }
```

### Suggested Solution

Generate a change event with the proper attributes when this method is passed a value instead of an event

### Who does this impact? Who is this for?

This is useful for anyone who wraps third-party/custom input components with Formik Fields. In my case, I use Antd to style my form fields and render errors. The onChange handler of Antd inputs only passes back the new field value, and not an actual event object.

While this is less than ideal (and honestly a shortcoming of Antd), a large number of projects in the React community use Antd, along with other design languages that may not pass back an actual event.

### Describe alternatives you've considered

1. Artificially generate a React.ChangeEvent (seems like a bad idea)
2. Using a different library for input components (would prefer not to do that, of course)
3. Staying on Formik v1 (which would be a shame because a lot of the new functionality is pretty cool, and vital to some future features we have planned)
4. Use setFieldValue instead (feels wrong, but it works)

### Additional context

If possible, could you explain the motivation behind moving to event-only handlers? Does forcing these handlers to only accept events enable some of the new functionality?

**Comment by skimi** [comment]
Looking at the code it looks possible to pass non event to handleChange because `executeChange` behind it allows it. https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L552
You'd need to prep your own field `handleChange` by doing `const myTrueHandleChange = handleChange(fieldName)` and `myTrueHandleChange` would accept values.

I'm looking at this too because I was expecting the `<Field />` component to already do that for you.

**Comment by connor-odoherty** [comment]
@skimi The signatures I listed in the ticket are the result of `handleChange(fieldName)`, so the equivalent of your `myTrueHandleChange`.

That result used to accept a value or event, but now it only accepts an event

**Comment by maktarsis** [comment]
I think it works as expected.
Event handlers are supposed to be event handlers, and field setters to be setters.

What do I mean is event handlers accept events and setters - values.

**Comment by connor-odoherty** [comment]
@maktarsis What would you recommend then for cases where we need to wrap third party components that emit values and not events? Is there any way to manually create an event in between?

**Comment by maktarsis** [comment]
@connor-odoherty 
why do you focus on creating events?
Let's focus on technical requirements.

If your 3-rd party component emits value, then do `setFieldValue`
If you want to track the "touched" state, then do `setFieldTouched`

This way is appropriate because formik has few event handlers:
1. onChange - uses to propagate new values in the form state from events
2. onBlur - tracks touched state of the field. It's useful to show error messages when field is touched but not valid.

**Comment by jaredpalmer** [comment]
@maktarsis is correct, setFieldValue is for values. The only wrinkle is if you are in react native land. You can use the curried version of handleChange/handleBlur

**Comment by connor-odoherty** [comment]
@maktarsis That's what I'm doing now as a stopgap. So if it's an accepted design, totally cool rolling with. However, are there side effects of onChange that we miss out on by using `setFieldValue`? 

For example, will validations run and update the same when using `onChange` vs `setFieldValue`? Will the `touched` property change the same? Just want to be sure I don't miss any part of the picture by treating `onChange` and `setFieldValue` as interchangeable

@jaredpalmer The curried version returns with a signature that only accepts the event:

```
func ƒ (event) {
        return executeChange(event, eventOrPath);
      }
```

Might you be mistaken? And if so, could you explain the reasoning behind moving from `eventOrValue` in V1 to just `event` in V2?

Also, thanks a ton for all your work here! Formik has been incredible

**Comment by maktarsis** [comment]
@connor-odoherty no reason to worry! It looks like a stopgap but it isn't. 

As I said before, you should focus on your requirements, not tech stuff.
The second half of my last response explains that.

So yeah, you won't miss anything if you do `onChange` manually via `setFieldValue`
And you won't miss anything else if you do `onBlur` manually via `setFieldTouched`
