### ISSUE TITLE
useField typecheck problem

### ISSUE THREAD

**Issue by avg206** [jaredpalmer/formik#1961]
### Current Behavior

When you use `useField` hook inside the component with a field value type, you've got an error

```
const [field] = useField<string[]>({ name, validate })
```

```
Error:(28, 38) TS2345: Argument of type '{ name: string; validate: Validator | undefined; }' is not assignable to parameter of type 'string | (ClassAttributes<HTMLInputElement> & InputHTMLAttributes<HTMLInputElement> & FieldConfig & string[] & { name: string; }) | (ClassAttributes<HTMLSelectElement> & SelectHTMLAttributes<...> & FieldConfig & string[] & { ...; }) | (ClassAttributes<...> & ... 3 more ... & { ...; })'.
  Type '{ name: string; validate: Validator | undefined; }' is not assignable to type 'string'.
```

### Expected behavior

Not having typescript error and just setting type to the field value

### Reproducible example

https://codesandbox.io/s/forms-with-formik-typescript-yd6lr?fontsize=14

Check `components/InputField.tsx` file 

### Suggested solution(s)

Change `FieldAttributes` type in `Field.d.ts`

From:
```
export declare type FieldAttributes<T> = GenericFieldHTMLAttributes & FieldConfig & T & {
    name: string;
};
```
To:
```
export declare type FieldAttributes<T> = GenericFieldHTMLAttributes & FieldConfig & {
    name: string;
};
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.3
| React            | 16.8.3
| TypeScript       | 3.5.2
| Browser          |
| npm/Yarn         | 6.11.3
| Operating System |

**Comment by patrykkarny** [comment]
I would suggest changing `FieldConfig` to be:

```
export interface FieldConfig<T> {
    component?: keyof JSX.IntrinsicElements | React.ComponentType<FieldProps<T>> | React.ComponentType;
    as?: React.ComponentType<FieldProps<T>['field']> | keyof JSX.IntrinsicElements | React.ComponentType;
    render?: (props: FieldProps<T>) => React.ReactNode;
    children?: ((props: FieldProps<T>) => React.ReactNode) | React.ReactNode;
    validate?: FieldValidator;
    name: string;
    type?: string;
    value?: T;
    innerRef?: (instance: any) => void;
}

export declare type FieldAttributes<T> = GenericFieldHTMLAttributes & FieldConfig<T>;
```

**Comment by davidroeca** [comment]
Encountering this as well. I think the ` & T` as part of field attributes is definitely a bug though, unless I'm missing a use case where you'd pass the `value` alone to `useField`.

On top of what @patrykkarny mentions, I think `FieldValidator` could also be defined as a generic, in which case it could also take a type parameter here.

**Comment by UberMouse** [comment]
I'm running into this problem as well. I've investigated removing the `& T &` from the `FieldAttributes` type, while it does fix the problem with `useField`, `<Field />` is broken with `& T &` removed.

For now I'm just casting the custom input I'm wrapping to `any` in my Formik wrapper around the input, which is not ideal, but not a huge problem.

**Comment by kharann** [comment]
Im also running into this problem as well!

**Comment by lightwave** [comment]
I have an PR open to fix this issue. Trying to fix FieldAttributes will break lots of stuff. It's better to decouple useField's parameter type from FieldAttributes which is meant for the Field component anyway. If someone can take a look at the PR, that'd be great.  This issue has been causing me much grief for days.

**Comment by mkdudeja** [comment]
Hi Team, @jaredpalmer @lightwave

Still facing the issue.

I have latest version of formik installed.

My Type look like this:
```
type MyInputProps = FieldHookConfig<string> & {
    id: string,
    label: string
};
```
But, getting the same typescript error.
![image](https://user-images.githubusercontent.com/5337500/80834665-c4f45880-8c0e-11ea-9e63-9782be761236.png)

Any help would be appreciated.

Thanks

**Comment by johnrom** [comment]
Field Attributes does not have a strongly typed value. The T is meant to express ExtraProps.

`FieldAttributes<{ myProp: boolean} >` would be `<Field name="myField" value={anyValueType} myProp={true} />`

There are some PRs available to strongly type fields which do something closer to what the above changes are using to accomplish. Search Strongly Typed Fields in the issues (I'm on mobile).

I assume useField is the same way. But I thought it also had a value type. I'll try to take a look on Monday.

**Comment by johnrom** [comment]
@mkdudeja one of your definitions is expecting an `<input />` while the other expects a `<select />`. It's a different issue than this one. Please open a new issue with a codesandbox reproduction and I'll try and help you out.

**Comment by lukaszkalemba** [comment]
@mkdudeja I have the same problem. Have you found any solution?

**Comment by johnrom** [comment]
@lukaszkalemba the error you're that I responded to was one where a component was accepting Field Props for a Select and passing those props to an Input. If you're having the same error, it has the same solution - - check any places you defined something with HTMLSelectElement or HTMLInputElement and make sure it matches the element ultimately being used.

If you can't identify the issue, try making a codesandbox repro and I'll take a look.

**Comment by batbrain9392** [comment]
If you break down the given types inside Formik, you can always form your custom types like so -

![code](https://user-images.githubusercontent.com/16289648/195855784-f9b75627-be5a-4a71-ae39-e90f52aaf3e3.png)
