### ISSUE TITLE
[v2] calling resetForm({values}) with nested objects won't reset dirty and isValid state to false

### ISSUE THREAD

**Issue by simmco** [jaredpalmer/formik#1976]
### Current Behavior

If you are calling ```resetForm({values})``` with values of nested objects the ```dirty``` and ```isValid``` state is still true.

### Expected behavior

As in v1 ```dirty``` and ```isValid``` state should be false after calling ```resetForm({values})``` with the new values.

### Reproducible example

v1.5.8: https://codesandbox.io/s/formik-codesandbox-template-tkqcc
v2.0.3: https://codesandbox.io/s/formik-codesandbox-template-076j5

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.3
| React            | 16.11.0

**Comment by Tigge** [comment]
Does the sandbox show the `isValid` issue as well? I wasn't sure how to reproduce it. I've create the merge request #1986 to solve the `dirty` part at least.

**Comment by simmco** [comment]
I just noticed that the ```isValid``` state is also true. And in v1 it is false. The sandbox should show it. Don't know if it is intended so?
Thanks for your work! 👏

**Comment by jsilvax** [comment]
I'm also experiencing this issue. I tested the PR @Tigge has open, and can verify it fixes the issue.

**Comment by Tigge** [comment]
@simmco for `isValid` I think this is to be expected in version 2. The `isInitialValid` (which defaulted to `false`) is now deprecated, and replaced with `initialErrors` (which defaults to `{}`, meaning no errors).

This is a good change, and while `isInitialValid` is deprecated but still usable in version 2, so you can get the same behaviour by setting it to `false`. But if you want to start with an invalid form it is better to set `initialErrors` instead.

**Comment by sahlouls** [comment]
Any updates on this one ?
