### ISSUE TITLE
Destructuring single object field breaks useFormikContext

### ISSUE THREAD

**Issue by tsujp** [jaredpalmer/formik#1980]
### Current Behavior

```typescript
// won't let you destructure a single field
const { values } = useFormikContext()
```

Yields

```
TypeError: _useFormikContext is undefined
```

Yet if I get _any_ other field member it works fine

```typescript
// this will work.. because 2 fields?
const { values, submitForm } = useFormikContext()
```

### Expected behavior

To have a destructured values field

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.3 |
| React            | 16.9.0 |
| TypeScript       | 3.5.3 |
| Browser          | Firefox 70.0.1 |
| npm/Yarn         | 6.12.1 |
| Operating System | macOS Mojave |

**Comment by tsujp** [comment]
It appears I was calling the component in the wrong place, whoops. Nothing is wrong.

**Comment by devforey** [comment]
Great that you solved it. Can you indicate which place you hate to put it for it to work?
