### ISSUE TITLE
dynamically change a value without an event

### ISSUE THREAD

**Issue by MareoRaft** [jaredpalmer/formik#1984]
## 🐛 Bug report

I have a dropdown which fires off an `onChange` function.

```
onChange = (event, e2, key) => {
      const new_type = event.target.value;
      // force-update the value
      this.props.values[key] = new_type;
      // let formik do its regular thing
      this.props.handleChange(event);
}
```

As you can see, I am programmatically/dynamically changing the value in formik's `this.props.values` (i am using `withFormik` on the component).

This seems to work.  Although I wish I fully understood why.

Now I have a *similar* situation where an uncontrolled dropdown-like component fires of an `onChange` function.  Unfortunately (sadly, disenchantingly), this component does not provide an `event` object to the onChange function.  So I tried making a fake one:

```
onChange = (key, new_type) => {
      // force-update the value
      this.props.values[key] = new_type;
      // let formik do its regular thing
      const event = {target: {name: key, value: new_type}};
      this.props.handleChange(event);
}
```

but Formik didn't buy the counterfeit.  Can I make better counterfeit?  Does formik not support dynamically updating values?  (I feel that it should support this)  (I don't see why handleChange should be necessary or why it needs an event object).

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.8
| React            | 16.8.4
| TypeScript       | none?
| Browser          | Firefox 70.0
| npm/Yarn         | npm 6.11.3
| Operating System | macOS 10.15

**Comment by Tigge** [comment]
It is not necessary to force-update the value using `this.props.values[...] = ...`. Just call formiks `handleChange` in the first scenario. In the second scenario use the `setFieldValue` function instead. See documentation here: https://jaredpalmer.com/formik/docs/api/formik#setfieldvalue-field-string-value-any-shouldvalidate-boolean-void

```javascript
<CustomSelect
  {...props.getFieldProps('color')}
  onChange={(name, value) => props.setFieldValue(name, value)}
/>
```

`getFieldProps` is a new function in Formik 2, but I guess you are already familiar with how to inject field props.

**Comment by MareoRaft** [comment]
@Tigge Thank you!!  Worked like a charm!
