### ISSUE TITLE
Re-Add submitForm to onSubmit's formikHelpers

### ISSUE THREAD

**Issue by fabb** [jaredpalmer/formik#1989]
### v1 Behavior

In v1 I used this pattern to allow retry-behavior with user interaction:

```
onSubmit={async (values, formikActions: FormikActions<MyFormData>) => {
    props.onSendMessage(values, formikActions.submitForm)
    formikActions.setSubmitting(false)
}}
```

The code in `onSendMessage` would store the `submitForm` function, and in case of an API error, show the error to the user and allow him to retry the submit. The clou was that the user can still tweak the form inputs while seeing the error message, because we want to avoid blocking user input as much as possible. Therefore when the user clickes the "retry" button, we really want Formik's `submitForm`/`onSubmit` to be triggered again and send the current values of the form.

### Current Behavior

In v2 this is no longer possible because `submitForm` was removed from the `FormikActions` (which have been renamed to `FormikHelpers`).

### Desired Behavior

I'd like to reinstate the behavior of Formik v1 and have `submitForm` as part of the `onSubmit` parameters in any way.

### Suggested Solution

Either add `submitForm` to the `FormikHelpers`, or as third argument to `onSubmit`, or introduce a new type that extends `FormikHelpers` with `submitForm` and use that for the second argument to `onSubmit`.

### Who does this impact? Who is this for?

This is for people who want to use clean retry behavior that is triggerable by a user.

### Describe alternatives you've considered

An alternative would be to have some helper prop that allows the parent component of the form that contains Formik to trigger the submit action from the outside. This is rather unwieldy and not very nice encapsulation-wise.

**Comment by danpantry** [comment]
`setSubmitting` is still present in `FormikHelpers`. 

https://github.com/jaredpalmer/formik/blob/360db2ca6a4f8f12b997b272c9256d71e52d5b60/src/types.tsx#L83

**Comment by fabb** [comment]
`setSubmitting` does not submit the form, but just sets the "submitting" state (which can be used for showing loading spinners or similar)

**Comment by danpantry** [comment]
Oh wow, I completely misread your post, for some reason. My bad!

**Comment by danpantry** [comment]
Oh wow, I completely misread your post, for some reason. My bad!

**Comment by jaredpalmer** [comment]
Feel free to make PR

**Comment by fabb** [comment]
allright, here we go: #2185

I went for the first of my suggested solutions.
