### ISSUE TITLE
What is the purpose of the 'payload' concept in Formik?

### ISSUE THREAD

**Issue by Martaver** [jaredpalmer/formik#199]
Thanks for the great library, it's refreshing to have a lighter alternative to redux-forms.

I noticed that in props there's properties such as mapValuesToPayload. Is this deprecated or does it serve some undocumented purpose?

**Comment by jaredpalmer** [comment]
Initially, the thinking was a to make a pure function to transform form values into a payload for handleSubmit to consume. It was redundant and thus deprecated. It’s kept for TypeScript backwards compat but will be removed in 0.10/1.0
