### ISSUE TITLE
In formik, getFieldProps() is not working

### ISSUE THREAD

**Issue by wanegain3** [jaredpalmer/formik#1992]
## 🐛 Bug report

In Formik, I try to use {...formik.getFieldProps('email')} on my input field instead of using value, onChange, and onBlur. But it's not working.

This works :

`<input id="email" name="email" type="text" value={formik.values.email} onChange={formik.handleChange} onBlur={formik.handleBlur} />`

But this doesn't :
`
<input id="email" type="text" {...formik.getFieldProps("email")} />`

Any ideas ? Thanks !

### Reproducible example

Code is here : https://codesandbox.io/s/formik-pb-with-getfieldprops-83tze?fontsize=14

**Comment by MappingSteve** [comment]
"it's not working" isn't enough information to help you. Describe exactly what you did, what you expected to happen, and what did happen.

**Comment by wanegain3** [comment]
Sorry about that. Turns out the code I've put here works fine with chrome but not with firefox. https://codesandbox.io/s/formik-pb-with-getfieldprops-83tze?fontsize=14

How is that possible given it is an online editor ? Do you guys also have also on firefox ? I am wondering if it is wise to use getFieldProps() if it is not working everywhere.

**Comment by jaredpalmer** [comment]
Seems fine in Firefox with 2.0.7 https://codesandbox.io/s/formik-pb-with-getfieldprops-htuc8
