### ISSUE TITLE
How does Formik best support field-level validation?

### ISSUE THREAD

**Issue by Martaver** [jaredpalmer/formik#200]
I'm using the yup validationSchema for field validation at the moment and, unfortunately, I'm finding the current validation set up a little inflexible regarding field-level validation. It might just be my lack of knowledge, and I can't find anything in the docs about it, so I thought I'd ask here.

Consider a basic login form... username/password.
With a simple yup schema, I can make username `email` and `required` and password also `required`.
Yup is evaluating the whole form, so (with default settings) on any input value change, both validations trigger, and I get validation errors appear on both fields.

Not nice, for the user to get big red error messages as soon as they start typing. So I switch to validate on blur only. This works nicely for the first field, but again as soon as I blur out of username and focus on password, I've got a big bad error message again on password.

In an ideal world, only the fields that a user have touched would get validated onChange/onBlur, and then the whole form at once on handleSubmit.

I know there are some more complex yup features, maybe they would help this case?

Unless I'm mistaken, I couldn't even custom code these kinds of validations, because the validator isn't aware of field-level `dirty`.

What approach would you recommend in this case?

**Comment by Martaver** [comment]
Updating my own question here with a partial answer, so that others can benefit... but I'd also like to hear the opinions from the experts :)

I got some inspiration from #167 and saw how to use `form.touched.myField`.

So in my fields now I can add logic for when to display validation messages such as: `p.form.touched.Password && p.form.errors.Password`

For custom component fields, this is still tricky though, since `name` isn't passed along with FieldProps, but I guess #167 will take care of that quite nicely.

This works... but I also end up in a situation where I have to write validation `display` logic at the field level. I'm okay with that, but in principle, shouldn't this kind of logic be closer to where we defined the validation schema, at the form level?

It might also be that I have to update my thinking on the issue and separate `validation` logic from `validation display` logic.

**Comment by Martaver** [comment]
One more useful thing I found! For fields that are custom components, Formik will pass any extra props on the Field component to the customer field component. This solves much of our 'per-field' problem. It's just not obvious for Typescript users (like me), who are spoiled by intellisense.

e.g. given the `Field` using my custom component `PasswordField`:

    <Field name={"Password"} component={PasswordField} />

I can get the name of the field like so:

```
export const PasswordField: React.SFC<FieldProps> = p => (
    <TextField
        {...p.field}
        type="password"
        hintText="Enter your password"
        floatingLabelText="Password"
        errorText={(p.form.touched[p.field.name] || p.form.isSubmitting) && p.form.errors[p.field.name]}
    />
);
```

For Typescript users, this will complain because `name` doesn't exist on FieldProps.field, but we can make our own interface, defining any of the props we want to pass along with it in `field`:

```
export interface CustomFieldProps<T> {
    field: {
        name: string;
        onChange: (e: React.ChangeEvent<any>) => void;
        onBlur: (e: any) => void;
        value: any;
    };
    form: FormikProps<T>;
}
```

and use it in place of FieldProps in our custom field component.

Again, I think this is something that #167 will take care of nicely!

**Comment by jaredpalmer** [comment]
- validation and validation display are purposely separate concepts in Formik.
- I am thinking about publishing a recipe for `<ErrorMesssage name="thing" render={msg => ...}/>`

**Comment by Martaver** [comment]
Now that I've got it straight in my head, I really like the distinction between validation and validation display. It makes a lot of sense. Once #167 hits, it would make sense to update the docs with an example of the common use cases for field-level validations. Maybe that will be a good place to add your recipe too!
