### ISSUE TITLE
Unable to uncheck checkbox field when no value prop is provided

### ISSUE THREAD

**Issue by emjaksa** [jaredpalmer/formik#2002]
### Current Behavior

When you do not supply a value prop to Field type="checkbox" you cannot uncheck the checkbox after has been checked.

According to the [migration guide](https://jaredpalmer.com/formik/docs/migrating-v2) you do not need to pass a value prop if you want to show/hide fields. 

### Expected behavior

You can uncheck the checkbox with no value prop

### Reproducible example

https://codesandbox.io/s/formik-checkbox-bug-84e4q

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |2.0.3
| React            |16.11.0
| TypeScript       |
| Browser          |Chrome
| npm/Yarn         |
| Operating System |OSX

**Comment by Kexin-Li** [comment]
@emjaksa @jaredpalmer Hey guys, I've made a PR to solve this problem, please check it out, thanks! :)
