### ISSUE TITLE
Submits form on button[type="button"] click when conditionally rendered in same dom structure as an upcoming submit-button.

### ISSUE THREAD

**Issue by kluplau** [jaredpalmer/formik#2004]
### Current Behavior

Submits form on button[type="button"] click when conditionally rendered in same dom structure as an upcoming submit-button.

### Expected behavior

Only type=submit buttons should submit. Not normal type=button buttons.

### Reproducible example

https://codesandbox.io/s/formik-submits-form-on-typebutton-odiyl

#### Env 1
| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.7
| React            | 16.8.6
| Browser          | Chrome 78.0.3904.87
| Operating System | Windows 7

#### Env 2
| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.8
| React            | 16.11.0
| Browser          | Chrome 78.0.3904.87
| Operating System | Windows 7

**Comment by emjaksa** [comment]
I think it has something to do with how react is updating the dom. If you add a different key to each of the buttons it works.

https://codesandbox.io/s/formik-submits-form-on-typebutton-ygdud

**Comment by kluplau** [comment]
> I think it has something to do with how react is updating the dom. If you add a different key to each of the buttons it works.

Oh, seems you're right. [I've made a non-Formik version](https://codesandbox.io/s/formik-submits-form-on-typebutton-non-formik-version-1enj0); which in hindsight should have done prior to addressing the issue here.
