### ISSUE TITLE
[v2] Validation schema for dates with setFieldValue

### ISSUE THREAD

**Issue by maktarsis** [jaredpalmer/formik#2008]
## 🐛 Bug report

Basically, I'm using **formik** 1.5.8 and I wanna have the latest **formik**  which provides useful api.
When I upgraded **formik** in my app to the 2.0.3 I made some small changes and it was working fine until I realized that my datepickers don't work as they supposed to.

### Current Behavior

1. Validation schema. 
```typescript
 DATE: date().required('Please select a date date'),
```
2. setFieldValue
```typescript
setFieldValue('DATE', someDate);
```
3. The date is correct and I can check it before and after the change.

4. **Yup** gets this `{}`. 
That's why **Yup** returns an error 
```typescript
DATE must be a `date` type, but the final value was: `Invalid Date` (cast from the value `{}`).
```
5. After debugging I was proved that value inside .test() is really `{}`.

### Expected behavior

validationSchema should work as before with date validation

### Additional context

All other fields are fine (number and string).
The issue is related to Yup.date in the schema

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |  2.0.3 |
| React            | 16.11 |
| TypeScript       | 3.7.2 |
| Browser          | Chrome (latest) |
| npm/Yarn         | 6.12.1 |
| Operating System | Windows |

**Comment by k1462015** [comment]
Also facing the same issue, specifically just with date validation

**Comment by cescoferraro** [comment]
same issue here

**Comment by maktarsis** [comment]
@cescoferraro set Yup.object instead Yup.date which is terrible
I think we should not look for workarounds because it will make our forms unmaintainable.

The only right thing here is a bug fix.

**Comment by k1462015** [comment]
Personally stuck to v1 for now, seems like v2 has quite a few issues and these changes require pretty hefty changes.

**Comment by AaronMcCloskey** [comment]
Also getting this issue.

It seems to be on [2.0.1-rc.14](https://github.com/jaredpalmer/formik/releases/tag/v2.0.1-rc.14) and above from what I can see. Not sure what caused it from looking at the commits from that release.

[CodeSandbox](https://codesandbox.io/embed/formik-react-datepicker-demo-8bc6y) here for anyone who wants to check it out, or even use it to find a solution

I suppose a temporary fix is to revert to [2.0.1-rc.13](https://github.com/jaredpalmer/formik/releases/tag/v2.0.1-rc.13) or before until it gets fixed.

**Comment by mariohdez** [comment]
Facing the issue here with validating a date via Yup.
Here is the validation error I get from Yup:

> myDate must be a `date` type, but the final value was: `Invalid Date` (cast from the value `{}`).

Using:
Formik v2.0.3
Yup v0.27.0

Any word on work arounds or if this is a bug?

Thanks,
Mario.

**Comment by SpudNyk** [comment]
This might be related to #1945 this was fixed in #1949 currently this is not released, hopefully it will be soon.

**Comment by maktarsis** [comment]
@SpudNyk 🔥

**Comment by k1462015** [comment]
@SpudNyk At least from my own usage, I've used `moment().toDate()`, which means it shouldn't have anything to do with `moment.js`?

**Comment by SpudNyk** [comment]
@k1462015 If you look at the pull request it mentions instances, it isn't moment specific.From looking at the source in v2.0.3 `prepareDataForValidation` make a deep clone, but did not take into account object instances vs raw objects. The implementation would clone Date instances to be an empty object (`{}`), this leads to the Invalid Date validation message. This behavior for plain javascript Dates is mentioned in the comments of #1945 and the pull request #1949 fixes it.

**Comment by austincrft** [comment]
I just ran into this issue as well. It looks like the fix was released 20 hours ago in v2.0.4. Updating to this version fixed it for me!

**Comment by maktarsis** [comment]
confirm, it's works!
congratulate everyone

I am switching to the second version 🥳🎉

**Comment by listiani13** [comment]
Hi guys, I just ran into this issue on Formik v2.1.5 & yup v0.29.6. The initial value of my date field is null. Is there anyone that face the same issue?
