### ISSUE TITLE
Yum number validation issue

### ISSUE THREAD

**Issue by klis87** [jaredpalmer/formik#201]
I have a following schema:
```javascript
const schema = yup.object().shape({,
  minimumAge: yup.number().required().min(0).integer(),
});
```
And in the following:
```javascript
schema.isValid({ minimumAge: '11aaa' }); // returns true
schema.validate({ minimumAge: '11aaa' });  // returns { minimumAge: 11 }
``` 
I guess this is because `parseInt('11aaa') => 11`.

The problem is that in `onSubmit` handler in `Formik` component, `values.minimumAge` is equal to `11aaa`, which means it is not cleaned. This is because we don't use `schema.validate` response in [https://github.com/jaredpalmer/formik/blob/master/src/formik.tsx#L334](https://github.com/jaredpalmer/formik/blob/master/src/formik.tsx#L334) . What do you think about overwriting values with those from `schema.validate` when form is valid?

Anyway, thank you very much for this library, the best of all form libraries and the first one written in React way 👍

**Comment by jaredpalmer** [comment]
The way we handle this is to use a custom field for the numeric that does the transformation before calling `setFieldValue(this.props.name, parseInt(this.props.field.value, 10))`.

**Comment by klis87** [comment]
Thanks, I will close this issue once I try it
