### ISSUE TITLE
Radio values must be strings, can't be numbers or booleans

### ISSUE THREAD

**Issue by WestonThayer** [jaredpalmer/formik#2044]
## 🐛 Bug report

![recording of two radio buttons](https://user-images.githubusercontent.com/709153/69018180-ef53a180-095f-11ea-8c84-3ca03d2f0119.gif)

Using a number or boolean to represent the selection of a radio group doesn't work — any attempt to switch between radio options results in neither option selected. Numbers are an especially common pattern for multiple choices, and are the default in Typescript `enum`. 

1. Provide `initialValues={{ someField: 1 }}` to Formik
2. Create some Formik-connected radio inputs with `value={1}`, `value={2}`, and `name="someField"`

```jsx
<Formik initialValues={{ choice: 1 }}>
  {formikProps => (
    <form>
      <label>
        <Field name="choice" type="radio" value={1} />
        Choice 1
      </label>
      <label>
        <Field name="choice" type="radio" value={2} />
        Choice 2
      </label>
    </form>
  )}
</Formik>
```

### Current Behavior

On initial render, the first radio is correctly checked, but attempting to select Choice 2 results in neither being checked.

Under the hood, Formik has stringified `initialValues.choice`. It then compares to the value, which is still a number, `"1" === 1` fails.

### Expected behavior

Choice 2 should be checkable, just like if I'd used string values.

### Reproducible example

https://codesandbox.io/s/black-platform-8reop

### Suggested solution(s)

- Don't stringify initialValues
- Document that initialValues can only be strings and update the types to reflect that
- Also stringify input values for comparison

### Additional context

Does not work with booleans either.

Likely related:

- https://github.com/jaredpalmer/formik/issues/1613
- https://github.com/jaredpalmer/formik/issues/1614

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.4
| React            | 16.8.6
| TypeScript       |
| Browser          | Chrome 78
| npm/Yarn         |
| Operating System | macOS Mojave

**Comment by alanrubin** [comment]
I'm seeing the same behaviour with booleans

**Comment by dgarciamuria** [comment]
Same for me after bumping to `2.0.4`. Won't take booleans

![image](https://user-images.githubusercontent.com/8144333/69351557-46a48b00-0c5a-11ea-9c50-2673da9e8841.png)

**Comment by jaredpalmer** [comment]
Seems like this should be a straight forward tweak? Can someone submit a PR?

**Comment by WestonThayer** [comment]
After working on a PR, I discovered that it isn't Formik that's converting the number to a string, it's just a limitation of the DOM Event.

Although you can set `<input value={1} />` or `value={false}` in JSX (even with Typescript), it's stored as a string attribute on the `<input>` element in the real DOM. So when Formik gets the `onChange(event)` callback, `event.target.value` will be `"1"` or `"false"`. I don't see any way to get at the original value supplied via a prop, so I think the only solution is to stick to strings.

I've added an example to https://github.com/jaredpalmer/formik/issues/1315#issuecomment-557704404.

Feel free to close this issue or repurpose it.

**Comment by dgarciamuria** [comment]
Mmmhh, weird. I was getting an error in react native. I'll take a look at it tomorrow

**Comment by boxfoot** [comment]
This may be messy, but what about an optional prop that provides a function which is used to transform the raw `event.target.value` into what's captured by Formik?

Something like:

```jsx
<Formik initialValues={{ choice: 1 }}>
  {formikProps => (
    <form>
      <label>
        <Field name="choice" type="radio" value={1} parse={parseInt} />
        Choice 1
      </label>
      <label>
        <Field name="choice" type="radio" value={2} parse={parseInt} />
        Choice 2
      </label>
    </form>
  )}
</Formik>
```

**Comment by NicoleEtLui** [comment]
Isn't the problem related to [these lines](https://github.com/jaredpalmer/formik/blob/83b2bca9995c0dfc40dc9b9519690fbb80f670d6/packages/formik/src/Formik.tsx#L571-L581) ?

![image](https://user-images.githubusercontent.com/17101004/71368357-06616100-25a8-11ea-95a0-9f4ff2c4cb54.png)

Why do we exclusively accept `String` as first parameters, could'nt we accept any raw value to transfer to the input (which was the actual behavior of formik before v2 i think). Has it changed for a precise reason ? 
![image](https://user-images.githubusercontent.com/17101004/71368333-f5b0eb00-25a7-11ea-80f8-bcd97c0843c6.png)

**Comment by jaredpalmer** [comment]
I think we should go back to v1 change behavior and revert the v2 tweaks. Closing this as this is a dom limitation.

**Comment by ankurpata** [comment]
Is this resolved ?

**Comment by johnrom** [comment]
It will be fixed by #2255 

You'll be able to format from any internal Formik value to a string, then parse the string back to number, boolean, etc, circumventing the issue.

**Comment by douglasrcjames** [comment]
Bump

**Comment by johnrom** [comment]
Also tracked in #3122 for alternate proposed state handling in v3.
