### ISSUE TITLE
useFormik 2.0.5's onSubmit signature changed return type

### ISSUE THREAD

**Issue by JasonEtco** [jaredpalmer/formik#2054]
### Current Behavior

In `formik@2.0.4`, the return type (talkin' HypeScript here) of `useFormik`'s `onSubmit` supported code like this:

```ts
async onSubmit () {
  return doSomethingAsync()
}
```

However, in `formik@2.0.5`, we need to return `void | Promise<void>` - which makes this code a little awkward (because then `doSomethingAsync` needs to return `void`, or `onSubmit` can't return anything):

```ts
async onSubmit () {
  await doSomethingAsync()
}
```

Possible that this is intended (if it is I'd say I still prefer the first) but the [release notes](https://github.com/jaredpalmer/formik/releases/tag/v2.0.5) don't mention this kind of breaking change so I figured I'd mention it!

### Reproducible example

N/A - I think I was descriptive enough above but feel free to tell me otherwise and I can drum up an example!

### Suggested solution(s)

It looks like this change was introduced in https://github.com/jaredpalmer/formik/pull/1987, and judging the before/after diff, it wasn't intended to work in the first place. Maybe changing the return type of `onSubmit` to `unknown`? That'd let consumers be a bit more flexible, and Formik wouldn't care what the value is.

### Additional context

In my real code, I'm using [`urql`](https://formidable.com/open-source/urql/)'s [`executeMutation`](https://formidable.com/open-source/urql/docs/getting-started/#using-hooks-1) pattern in `onSubmit`.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.5 |
| React            | |
| TypeScript       | |
| Browser          | |
| npm/Yarn         | |
| Operating System | |

**Comment by jaredpalmer** [comment]
Oh shoot. I shouldn't have specified `Promise<void>`. Should have been like `Promise<unknown>`?

**Comment by jaredpalmer** [comment]
or `Promise<any>`

**Comment by jaredpalmer** [comment]
patching meow

**Comment by jaredpalmer** [comment]
Fixed in 2.0.6

**Comment by JasonEtco** [comment]
✨ thanks for the quick fix! I think either `any` or `unknown` does the trick, aside from semantics.

**Comment by jaredpalmer** [comment]
I think it should be `unknown` but whatevs I shipped `any`
