### ISSUE TITLE
What's the best way to make a submit button outside the Form?

### ISSUE THREAD

**Issue by Yartro** [jaredpalmer/formik#2066]
## ❓Question
I know this has been asked multiple times, but I can't get a good solution. React Ref's don't seem to do it, and giving the button & form the same id only seem to submit the form via url, which is buggy in a SPA.

**Comment by baorv** [comment]
Any solutions?

**Comment by jaredpalmer** [comment]
You can use a ref and call submitForm(). Otherwise you must lift `<Formik>` higher up your react tree

**Comment by arodik** [comment]
Another way that could be OK for some edge cases when you need to lift up the Formik state

1. Create a component that accesses the Formik object via `useFormikContext`.  
```jsx
const FormikStateLifter = () => {
  const parentState = useSomeParentState(); // some parent state that you need to update 
  const formik = useFormikContext();

  useEffect(() => {
    if (!formik) {
      return;
    }

    // Will be run on each formik update

    parentState.isValid = formik.isValid;
    parentState.submitForm = formik.submitForm;
  });

  return null;
}
```

2. Render the component inside Formik's render method
```jsx
const SomeForm = props => {
  return <Formik>
    {formik => {
      return <>
        <FormikStateLifter />
        {/** your form fields here **/}
      </>;
    }}
  </Formik>;
};
```
