### ISSUE TITLE
formik.values is undefined without initialValues with useFormik 

### ISSUE THREAD

**Issue by wanaryytel** [jaredpalmer/formik#2067]
### Current Behavior

When you initialise Formik with `useFormik()`, do not specify `initialValues` and call `formik.setFieldValue()`, Formik will crash with `Uncaught TypeError: Cannot read property 'x' of undefined`.
If you specify an empty object as initialValues, this doesn't happen.

### Expected behavior

Not sure if this is a bug or desired behaviour, but the error message is lacking imo, I spent 30 minutes looking for the cause of this. The docs state 

> Even if your form is empty by default, you must initialize all fields with initial values otherwise React will throw an error saying that you have changed an input from uncontrolled to controlled.  

about the initialValues, but I did not get the input uncontrolled/controlled error. Also it works with an empty object as initialValues so maybe the default on initialValues should be an empty object?

### Reproducible example

```

import Select from "react-select";
import Form from "react-bootstrap/Form";
import {useFormik} from "formik";

const testFormSchema = yup.object({
    x: yup.object({
        value: yup.string().required(),
        label: yup.string().required(),
    }).required(),
});

const TestForm = React.memo(() => {
    const onSubmit = (values) => {
        console.log(values);
    };

    const formik = useFormik({
        validationSchema: testFormSchema,
        // initialValues: {},
        onSubmit,
    });

    return (
        <Form noValidate onSubmit={formik.handleSubmit}>
            <Form.Group controlId="test">
                <Select
                    options={[
                        {
                            label: 'x',
                            value: 'x',
                        },
                        {
                            label: 'y',
                            value: 'y',
                        },
                    ]}
                    onChange={value => formik.setFieldValue('x', value)}
                />
            </Form.Group>

            <Form.Group controlId="storyboardTitle-save">
                <Button type="submit">
                    Submit
                </Button>
            </Form.Group>
        </Form>
    );
});
```

The minimal example also includes react-select to showcase why this situation can happen in the first place

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.6
| React            | 16.8.6
| TypeScript       |
| Browser          | Chrome
| npm/Yarn         | 
| Operating System |

**Comment by mrowe009** [comment]
i believe this is a duplicate to my issue #1967 still haven't heard anything back on it

**Comment by wanaryytel** [comment]
Yup, I was looking but apparently failed to find it :) Will close this one, thanks
