### ISSUE TITLE
Can we combine validation schema of 2 components?

### ISSUE THREAD

**Issue by nilamsavani91** [jaredpalmer/formik#2074]
## ❓Question

I have 1 parent component and 2 child components in it. Both of y child components have form validation using withFormik() and there is no connection between those 2 child components.

What I want to do is, In one of my child components I have a submit button and I want to enable it only if form validation for that component and for other child components is valid/true?

**Comment by jaredpalmer** [comment]
You can move the schemas into their own variables and then share them. Composition like you described is not in the roadmap
