### ISSUE TITLE
Array manipulations do not trigger validation

### ISSUE THREAD

**Issue by patricknick** [jaredpalmer/formik#2077]
### Current Behavior
The validation is not triggered by FieldArray upon array mutation (push/pop/...). 

What I noticed is that is FieldArray, a callback is passed into
https://github.com/jaredpalmer/formik/blob/c93a6d4ad059bb8684f48c2d54524f417add2030/src/FieldArray.tsx#L140-L174

But this function actually doesn't accept a callback:
https://github.com/jaredpalmer/formik/blob/c93a6d4ad059bb8684f48c2d54524f417add2030/src/Formik.tsx#L662-L675

Am I getting something wrong? 🤔 

### Expected behavior
According to the documentation, this should happen by default:
https://jaredpalmer.com/formik/docs/api/fieldarray#validateonchange-boolean

### Reproducible example
https://codesandbox.io/s/nameless-dream-2jzcp?fontsize=14&hidenavigation=1&theme=dark

### Suggested solution(s)
Not sure. I suppose this worked once?

### Additional context
-

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.6 |
| React            | 16.8.4 |
| TypeScript       | 3.3.3 |
| Browser          | Chrome |
| npm/Yarn         | yarn |
| Operating System | macOS |

**Comment by jaredpalmer** [comment]
Fixed in 2.1

**Comment by gsaandy** [comment]
Still not working in 2.1.4

**Comment by bduffany** [comment]
My form doesn't seem to validate either on `push` or `remove`. I have to call `setTimeout(validateForm)` and it works.

**Comment by rlecellier** [comment]
Still not work in `2.2.9`
