### ISSUE TITLE
Examples use touched without onBlur

### ISSUE THREAD

**Issue by grough** [jaredpalmer/formik#208]
There are multiple examples in the main readme that show `touched` being used without applying `onBlur`.

For instance:
```
<input
  type="password"
  name="password"
  onChange={handleChange}
  value={values.password}
/>
{touched.password && errors.password && <div>{errors.password}</div>}
```

Is it possible to do this or are the examples misleading?

**Comment by jaredpalmer** [comment]
The are mistakes. onBlur should be there
