### ISSUE TITLE
Add documentation for `setError`... & others

### ISSUE THREAD

**Issue by thiskevinwang** [jaredpalmer/formik#2080]
### Missing `setError` ... & others

The documentation is missing descriptions for `setError` (singular) and some other formikBag values.
- https://jaredpalmer.com/formik/docs/api/withFormik#the-formikbag

### Repro

1. Formik `v1.5.8`

2. `console.log` the `formikBag` from withFormik - handleSubmit

```ts
withFormik({
  handleSubmit: (values, formikBag) => {
    console.log('formikBag', formikBag)
  },
})
```

What [DOCS](https://jaredpalmer.com/formik/docs/api/withFormik#the-formikbag) say | What I see
:-- | :--
![image](https://user-images.githubusercontent.com/26389321/69885926-aaa7fe80-12ad-11ea-9539-6af1b286781c.png) | ![image](https://user-images.githubusercontent.com/26389321/69885863-5b61ce00-12ad-11ea-90f8-b891a79b7e72.png)

I'm also curious when I should use `setErrors` vs `setError`, as I'm trying to track analytics for when a form has incomplete fields (this updates `errors`) but `setErrors` (internal choice) is used to set a generic API error, which overwrites `errors`.

**Comment by jaredpalmer** [comment]
setError was deprecated and thus no docs necessary.

**Comment by mernstackman** [comment]
> 
> 
> setError was deprecated and thus no docs necessary.

what about the setStatus?

**Comment by thiskevinwang** [comment]
Ah, thanks @jaredpalmer!

@mernstackman, yea I think `setStatus` will be he way to go 
- I just did the upgrade from `v0.11.11` (?) to `v1.5.8` not _too_ long ago, so setStatus didn't exist yet.
