### ISSUE TITLE
React date field is not validating on the second time of value change.

### ISSUE THREAD

**Issue by z3us94** [jaredpalmer/formik#2088]
## ❓Question

Hey everyone!, 
I have this form with a date field which im using fomik for.
```
<div className="form-date-container">
    <Form.Field required>
        <label className="form-label">Start date</label>
          <DatePicker
              dateFormat="DD/MM/YYYY"
               selected={values.startDate === "" ? null: values.startDate}
                onChange={(e) =>{
                   setFieldValue("startDate", e, true);
               }}
                todayButton={"Today"}
                placeholderText={moment().format('DD/MM/YYYY')}
                name="startDate"
        />
</Form.Field>
```
above is the sample of my form field. And imusing Yup for my validations, 
```
Yup.object().shape({
 startDate: Yup.date()
.required('Pick a start date.'),
});
```
above is how my validation schema looks like. I did a simple validation. My problem is when submitting the form for first time the validation works well and error message is also shown. But in a scenario where when i select a date from a picker and just clear it and try to submit the validations wont get fired. When this happens the selected value will be `null` according to my code above. 

Im not sure why this is not properly getting validated because apon handle submit all the fields are getting touched. But still no errors will be shown and avoid from submitting. Only the times where i select the date it works well. Not when i try to clear the input field manually. 

Is there something wrong im doing ? or Is this a bug? 

Im using, 
formik - ^1.3.2
react-datepicker - ^1.6.0
yup - 0.27.0

**Comment by jaredpalmer** [comment]
Can you create a codesandbox to reproduce this behavior?
