### ISSUE TITLE
Why is this checkbox not touched?

### ISSUE THREAD

**Issue by RomainGoncalves** [jaredpalmer/formik#2091]
## ❓Question

Sandbox: https://codesandbox.io/s/sad-sound-i60yb

On that sandbox I have a very simply checkbox, when I click the checkbox itself multiple times you can see that the `touched` value never gets updated. Click somewhere else on the page, and `touched` get updated and we see the error message.

Why is `touched` not updated upon click?

Thanks

**Comment by mstanielewicz** [comment]
Hello,
The touched prop set to true when you unfocus/blur the input. That's the way radio button works. It stays focused when you click it.

**Comment by RomainGoncalves** [comment]
@mstanielewicz thanks for your answer, however how am I suppose to have the error show right after unselecting the checkbox then? If `onBlur` is the method that triggers the  validation, it will only trigger when I click somewhere else on the page, which is not what I want.

I tried having `onBlur` in the `onChange` method, but on any click, it triggers before the value is changed and the error always appears.

**Comment by mstanielewicz** [comment]
Unfocus/blur triggers the touched value. The validation is triggered also after change event (check https://jaredpalmer.com/formik/docs/guides/validation). So you could just create a validation function for this specific field that runs after value is changed. But you just should not rely on touched prop.

**Comment by RomainGoncalves** [comment]
I see. Thanks for that. I guess I will have to use `setFieldTouched`
