### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by juji** [jaredpalmer/formik#2096]
## 📖 Documentation

It is very useful to search things...

Now that it's broken... we need to read the docs to search for something like `setFieldValue`.

Which is hard to find

**Comment by jaredpalmer** [comment]
I noticed this too. I am going to hunt down when this happened. It's powered by docsearch.

**Comment by jaredpalmer** [comment]
It looks like it is back up. My guess is that Algolia had an outage yesterday.

**Comment by jaredpalmer** [comment]
@juji thanks for taking the time to report. Much appreciated.

**Comment by tiagofilipe3** [comment]
Still broken :/ some props links are not working too.
