### ISSUE TITLE
Uncaught (in promise) using Field level validation

### ISSUE THREAD

**Issue by jamime** [jaredpalmer/formik#2099]
### Current Behavior

Using the `Field` with the `validate` prop throws an Uncaught exception when pressing submit.

![image](https://user-images.githubusercontent.com/2328042/70556223-58ea5880-1b78-11ea-96d8-eda9d267dac6.png)

### Expected behavior

There should be no exception thrown.

### Reproducible example

https://codesandbox.io/s/formik-codesandbox-template-3jld0

Please note, this is only displayed in the chrome console, not the code sandbox console.
### Suggested solution(s)
Investigate this area https://github.com/jaredpalmer/formik/blob/c5ec70956b4937313b914a1ee38dbeceb8d399e5/src/Formik.tsx#L738
### Additional context

The Field level validation example has the same behaviour https://jaredpalmer.com/formik/docs/guides/validation#field-level-validation

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.7
| React            |16.12.0
| TypeScript       | N/A
| Browser          | Chrome 78.0.3904.108
| npm/Yarn         | N/A
| Operating System | MacOS 10.14.6

**Comment by jamime** [comment]
Possibly fixed by #2103

**Comment by jaredpalmer** [comment]
Fixed in #2103
