### ISSUE TITLE
Property "touched" computed only on submit

### ISSUE THREAD

**Issue by senycorp** [jaredpalmer/formik#212]
Hi,

is it possible to update "touched" in "handleChange" similar to "errors". Actually it will be computed only on submits. Using a combination of "handleChange" and "setTouched" could be one manual option but brings a lot of boilerplate. A new parameter would be nice to make "touched" parameter holding the live state instead of getting computed on submits.

**Comment by jaredpalmer** [comment]
You can create a custom <Field> that does not pass `props.field.handleBlur` to your input's `onBlur` and (i think) that would work
