### ISSUE TITLE
Reset dirty property after submit

### ISSUE THREAD

**Issue by gregorybellencontre** [jaredpalmer/formik#2129]
Hello

I'm trying to reset the `dirty` property after my form is submitted.
I'm using it to know if users made changes in the form and alert them when they want to leave the page.

First question : is it the good property tu use for that ?
If yes, how could I reset the boolean to false, once the form is submitted ?

**Comment by ThomasWFord** [comment]
Something like `resetForm({ values: currentValues })` (where currentValues is the values that are now not "dirty") should work, that will set the initial values and compute the dirty property to false

**Comment by sw-yx** [comment]
documented in https://github.com/formium/formik/pull/2743

**Comment by inurlan** [comment]
add `enableReinitialize` to `Formik`

**Comment by erich0123** [comment]
@inurlan 

> add `enableReinitialize` to `Formik`

When I use `enableReinitialize` the `submitCount` resets to 0 for some reason and I need this to set a "saved" state on the form. Same happens when I use `resetForm({ values: {...} })`. I'm setting `submitCount` to 1 in `resetForm` as a workaround.

**Comment by gdSuhail** [comment]
Ref: https://stackoverflow.com/a/55803798/6613333
This worked for me
```
onSubmit={(values, { resetForm }) => {

      // do your stuff 
      resetForm();

}}
```
