### ISSUE TITLE
CreatableSelect create tag/option in multiselect with Formik

### ISSUE THREAD

**Issue by kahboom** [jaredpalmer/formik#2131]
## ❓Question

Hey everyone. I can't seem to figure out what I'm doing wrong, but I'm trying to use `CreatableSelect`  from react-select, where you can type in a new tag/option that doesn't already exist in a multiselect drop-down. The option to create doesn't appear when you type, just "No options".

Sandbox [here](https://codesandbox.io/s/amq-stream-selector-experimenting-ts-cdphx) - it's the last dropdown of the three.

Any help/pointers would greatly be appreciated. Thanks!

**Comment by maurofsc** [comment]
just change the import

import Select from "react-select"; to import Select from "react-select/creatable";

**Comment by kahboom** [comment]
@maurofsc Yes I noticed this mistake a few months ago and forgot about this issue completely. 😂 Thanks !
