### ISSUE TITLE
2 submit buttons

### ISSUE THREAD

**Issue by vasinl124** [jaredpalmer/formik#214]
Is there anyway to have 2 submit buttons in 1 form?

**Comment by cloud-walker** [comment]
It semantically correct to have 2 submit buttons in 1 form?

**Comment by vasinl124** [comment]
Hi @cloud-walker,
In my case, I want to have a save button and submit button both use the same data/form but implement differently at the end. Is there anyway to work around this use case?

**Comment by cloud-walker** [comment]
I have a similar case and for now I've done like that:

```javascript
<button type="submit">pay with credit card</button>
<button onClick={() => {doStuff(); submitForm()}}>pay with paypal</button>
```

`submitForm` comes from Formik, but its not documented, maybe @jaredpalmer may enlighten us on this

**Comment by vasinl124** [comment]
I want to validate the form before submit the form... If I do via `onClick` then it's not going called handleSubmit()

**Comment by jaredpalmer** [comment]
if you call submitForm() validations will be called.

**Comment by jaredpalmer** [comment]
@cloud-walker has it right.

**Comment by pavanmehta91** [comment]
@jaredpalmer is there a way to pass a flag to the handleSubmit action from the button and get it in the onSubmit function. I've the similar situation where I've two actions for the same form.

**Comment by joshgeller** [comment]
Has anyone found a way to pass the flag that @pavanmehta91 requested?

**Comment by pavanmehta91** [comment]
I've found a way I set a flag and use `setValue` and then execute the handleClick function. So on submit I get which button was clicked. It's plain JS 👍

**Comment by pavanmehta91** [comment]
If anybody wants the code I can share it here.

**Comment by joshgeller** [comment]
@pavanmehta91 yes, please 😀

**Comment by pavanmehta91** [comment]
`               initialValues={{
                      isSecondButton: false,
}}`

That's the initial value you provide..

`
onSubmit={values => {
if(values.isSecondButton){
do some action
} else {
do some other action
}
}
`


In Your renderProp
`
                                  <Button
                                    id="second-button"
                                      onClick={(e)=>{
                                          setFieldValue('isSecondButton',true)
                                          handleSubmit(e);
                                      }}
                                      variant="raised"
                                      color="primary"
                                    
                                  >
`

**Comment by Bundas** [comment]
@pavanmehta91 
`setFieldValue` is async function because it updates a state where are all the values stored therefore it's not guaranteed that there will be the most actual values in `onSubmit` handler..

**Comment by pavanmehta91** [comment]
@Bundas You're right and it should return a promise. But from my experience I've never faced an issue. We could also use setTimeout(()=> onSumbit(e),0). That'd run on the next tick.

**Comment by GonzalezAVictor** [comment]
You can do something like 
`<Button
   text='Enviar cotizac&iacute;on &#8594;'
   customProps={{ isSendEmailButton: 'true' }}
   onClick={(e) => {
      props.values.foo = true
      props.handleSubmit()
   }}
/>`

and in your submit function validate `foo`like
´onsubmit (values) {
   if foo doSomething()
   else doSomethingElse()
}`

**Comment by hertzg** [comment]
@GonzalezAVictor You should not mutation the props

**Comment by Funkyskank** [comment]
```jsx
<Button
  onClick={async () => {
    await setFieldValue('isSecondButton', true);
    submitForm();}
  }
/>
```

**Comment by sadi304** [comment]
@Funkyskank  setfieldvalue is not a promise, so await wouldn't do anything here. this is the main issue here, that its not a promise :P

**Comment by rovansteen** [comment]
Also, if you want different behavior on your first submit button only `onClick` isn't going to cut it as you can trigger that button by pressing enter in your form as well.

**Comment by Funkyskank** [comment]
But without `await` form won't submit at all.

**Comment by rovansteen** [comment]
Right now there isn't one without doing some `settimeout` hack.

**Comment by Andreyco** [comment]
There is now way to do it with vanilla JS so you must come with your own solution. Formik has no way to support it in current state.

What I do, if I remember correctly is this...

```jsx
class Sample extends React.Component {
  submitAction = undefined;

  render() {
    return;
    <Formik
      onSubmit={values => {
        if (this.submitAction === 'a') {
          // ...
        }

        if (this.submitAction === 'b') {
          // ...
        }

        this.submitAction = undefined;
      }}
    >
      {formikProps => (
        <React.Fragment>
          <Form>
            <button
              type="button"
              onClick={() => {
                this.submitAction = 'a';
                formikProps.submitForm();
              }}
            >
              Action A
            </button>
            <button
              type="button"
              onClick={() => {
                this.submitAction = 'v';
                formikProps.submitForm();
              }}
            >
              Action B
            </button>
          </Form>
        </React.Fragment>
      )}
    </Formik>;
  }
}
```

**Comment by dexiouz** [comment]
@Andreyco  Where do you get formikProps from. I can't seem to access it, I've seen FormikProps but not formikProps... capital and small letter f

**Comment by eeriee** [comment]
I don't have to call submitForm() or handleSubmit() if i setFieldValue and call functions correspondingly in onSubmit

**Comment by lonewolfffffff** [comment]
@Funkyskank @rovansteen you need to set the third parameter of setFieldValue to **false**

[from the doc](https://jaredpalmer.com/formik/docs/api/formik#setfieldvalue-field-string-value-any-shouldvalidate-boolean-void)

```
<Formik onSubmit={(values, { setSubmitting }) => {this.handleSave(values)}} >
{ ({handleSubmit}) => (    
    <Form onSubmit={handleSubmit}>

        <Button type='button' onClick={() => {
            setFieldValue('publish', 1, false)
            handleSubmit()
        }}>Save and Publish</Button>

        <Button type='button' onClick={() => {
            setFieldValue('publish', 0, false)
            handleSubmit()
        }}>Save as draft</Button>

    </Form>
) }
</Formik>
```

**Comment by skoch-tf** [comment]
it's not easy for our cases we use this approach:

`<Formik onSubmit={(typeForm)=>(values, actions) => {
if (typeForm === 'publish' ) {
return actions.validateForm(validatePublish).then(submitPublishToApi);
}
if (typeForm === 'draft' ) {
return actions.validateForm(validateDraft).then(submitDraftToApi);
}
} >
{ ({setFieldValue, handleSubmit}) => (    
    <Form onSubmit={handleSubmit}>

        <Button type='button' onClick={() => {
            handleSubmit('publish')()
        }}>Save and Publish</Button>

        <Button type='button' onClick={() => {
            handleSubmit('draft')()
        }}>Save as draft</Button>

    </Form>
) }
</Formik>`

**Comment by skoch-tf** [comment]
I use this approach:

```
function FormContainer(props) {
  const [formType, setFormType] = useState(DEFAULT_FORM_TYPE);

  const handlerSubmit = (methodX, methodY) => async values => {
    if (formType === FORM_TYPE_X) {
      return await methodX(values);
    }
    return await methodY(values);
  };

  const submitFormType = (formTypeSubmited, handleSumitType) => () => {
    setFormType(formTypeSubmited, () => handlerSubmit());
  };

  return (
    <Formik
      onSubmit={handlerSubmit(props.saveToApiMethodX, props.saveToApiMethodY)}
      validate={values => props.validate(formType, values)}
    >
      {(values, handleSubmit, errors) => (
        <>
        <button onClick={submitFormType(FORM_TYPE_X, handlerSubmit)}>
        Method X
        </button>
        <button onClick={submitFormType(FORM_TYPE_Y, handlerSubmit)}>
        Method Y
        </button>
        </>
        )}
    </Formik>
  );
}

```

**Comment by mateuszzdyb** [comment]
@cloud-walker 
Thanks for your snippet. any idea how to pass onclick dosfuff() from div to formik tag?, just like onSubmit? or formik accepts only predefined functions?
<button onClick={() => {doStuff(); submitForm()}}>pay with paypal</button>
 ..................................................  ^-this doStuff.

**Comment by dmudro** [comment]
Most likely do not want to write any `setFieldValue()` stuff for majority of use cases. Among other reasons that would imply having some (hidden) field just for the sake of setting a flag for the (second) submit button to perform whatever the custom action is, e. g. the save / publish use case.

There is only one viable solution by @cloud-walker:
`<button type="button" onClick={() => {doStuff(); submitForm()}}>pay with paypal</button>`

...where `doStuff()` is most likely going to be a setting custom state flag as detailed by @skoch-tf. 

There is a PR #1792 which would remove the need to store anything in the state.

**Comment by HectorRicardo** [comment]
> I use this approach:
> 
> ```
> function FormContainer(props) {
>   const [formType, setFormType] = useState(DEFAULT_FORM_TYPE);
> 
>   const handlerSubmit = (methodX, methodY) => async values => {
>     if (formType === FORM_TYPE_X) {
>       return await methodX(values);
>     }
>     return await methodY(values);
>   };
> 
>   const submitFormType = (formTypeSubmited, handleSumitType) => () => {
>     setFormType(formTypeSubmited, () => handlerSubmit());
>   };
> 
>   return (
>     <Formik
>       onSubmit={handlerSubmit(props.saveToApiMethodX, props.saveToApiMethodY)}
>       validate={values => props.validate(formType, values)}
>     >
>       {(values, handleSubmit, errors) => (
>         <>
>         <button onClick={submitFormType(FORM_TYPE_X, handlerSubmit)}>
>         Method X
>         </button>
>         <button onClick={submitFormType(FORM_TYPE_Y, handlerSubmit)}>
>         Method Y
>         </button>
>         </>
>         )}
>     </Formik>
>   );
> }
> ```

I am not sure if I understood this solution. Regarding this line: `setFormType(formTypeSubmited, () => handlerSubmit());`

1) Does `setFormType` accept two arguments? Are you using [this](https://github.com/the-road-to-learn-react/use-state-with-callback)?
2) `() => handlerSubmit()` ? I think this should be replaced by `handleSumitType` (assuming that my first question was answered as I expected)

**Comment by vpontis** [comment]
You can access `window.event` in the `onSubmit` handler to see which button was clicked :)

**Comment by leonvdb** [comment]
Using `window.event` in the `onSubmit` handler as @vpontis described worked great for me. More specifically setting i.e. the `name` attribute on the different submit buttons and accessing it through `window.event.submitter.name`.

**Comment by johnrom** [comment]
@vpontis @leonvdb that's only for browsers, not React Native I suspect.

**Comment by vpontis** [comment]
> @vpontis @leonvdb that's only for browsers, not React Native I suspect.

Ya, I haven't tried it in React Native.

**Comment by viperfx** [comment]
Is event passed into onSubmit @leonvdb or are you accessing through window.event?

**Comment by MeLlamoPablo** [comment]
`window.event` works great but [is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Window/event). The correct, non hacky solution, would be to have Formik expose the native HTML event to `onSubmit` as the third parameter.

@jaredpalmer what do you think?

**Comment by ThomasChaf** [comment]
Hello everyone,

I was also facing a similar issue. I solved it using the dataset of the submit button.
```html
  <button type="submit" data-flag="action-1">Action 1</button>
  <button type="submit" data-flag="action-2">Action 2</button>
```

Then I'm able to retrieve the flag anywhere using `document.activeElement` 
https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement

```javascript
const onSubmit = (values) => {
  console.log('The flag is:', document.activeElement.dataset.flag);
}
````

Fun fact I discovered document.activeElement reading Formik code base. 😅

Hope it can help.

**Comment by MeLlamoPablo** [comment]
@ThomasChaf nice discovery!

> The activeElement read-only property of the Document interface returns the Element within the DOM that currently has focus.

Do you think it's possible for a submit button to not have focus after the form is submitted? My intuition tells me that this expectation doesn't necessarily have to be true but I could be wrong!

It'd be interesting to test this with alternative input methods, or by clicking submit buttons programatically.

**Comment by ThomasChaf** [comment]
@MeLlamoPablo I don't know so far I don't find any issue but I got a really simple form.

**Comment by halchester** [comment]
With formik, if you remove type = "submit" on <button></button>, it doesn't re render the whole page

**Comment by vijaychouhan-rails** [comment]
> Hello everyone,
> 
> I was also facing a similar issue. I solved it using the dataset of the submit button.
> 
> ```
>   <button type="submit" data-flag="action-1">Action 1</button>
>   <button type="submit" data-flag="action-2">Action 2</button>
> ```
> 
> Then I'm able to retrieve the flag anywhere using `document.activeElement`
> https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement
> 
> ```js
> const onSubmit = (values) => {
>   console.log('The flag is:', document.activeElement.dataset.flag);
> }
> ```
> 
> Fun fact I discovered document.activeElement reading Formik code base. 
> 
> Hope it can help.

Great work, 100% working

**Comment by EvanCoh** [comment]
> 
> 
> Hello everyone,
> 
> I was also facing a similar issue. I solved it using the dataset of the submit button.
> 
> ```
>   <button type="submit" data-flag="action-1">Action 1</button>
>   <button type="submit" data-flag="action-2">Action 2</button>
> ```
> 
> Then I'm able to retrieve the flag anywhere using `document.activeElement` https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement
> 
> ```js
> const onSubmit = (values) => {
>   console.log('The flag is:', document.activeElement.dataset.flag);
> }
> ```
> 
> Fun fact I discovered document.activeElement reading Formik code base. sweat_smile
> 
> Hope it can help.

Unfortunately it's not working on IOS WebView.

**Comment by Houndie** [comment]
I'm a novice react developer, but I think I have a solution for this?

A lot of people talked about having `setFieldValue` return a promise, which doesn't really make sense...deep in Formik's internals your values are react state, and changing react state causes the whole function to re-render.  What you want to do is do something after the re-render, because then you know the state has changed.

Luckily, effect hooks exist to do just that thing:

```
enum FormAction {
   first = "first",
   second = "second",
   none = "none",
}

const myForm = () => {
   <Formik
      initialValues={{
         action: FormAction.none
      }}
      onSubmit{(values, {setSubmitting, setFieldValue}) => {
         switch(values.action) {
         case FormAction.first:
            //Do the thing for button 1
         case FormAction.second:
            //Do the thing for button 2
         default:
            console.log("should never be called")
         }
         
         setFieldValue("action", FormAction.none)
         setSubmitting(false)
      }}
   >
      {({values, isSubmitting, submitForm, setFieldValue}) => {
         useEffect(() => {
            if(values.action != FormAction.none) {
               submitForm()
            }
         }, [values.action])
         
         return (
            <>
               <button disabled={isSubmitting} onClick={() => {
                  setFieldValue("action", FormAction.first)
               >First Button</button>
                  
               <button disabled={isSubmitting} onClick={() => {
                  setFieldValue("action", FormAction.second)
               >Second Button</button>
            </>
         )
      }}
   </Formik>
}
```

In this way, pressing the button sets the action to do, and when the action to do is set, the effect hook submits the form, then clears the action afterwards.
