### ISSUE TITLE
In material ui autocomplete, when i select options , usefomik value cannot update?

### ISSUE THREAD

**Issue by RonaldCY** [jaredpalmer/formik#2141]
As title, I'm using useFormik and material ui  "autocomplete"of course in react js
however when i select an option item in "autocomplete" component, i see in console the value is update in <input> but the useFormik value is not update, please check up what issue or any solution to help? thanks and Regards

some snippets

...
  const handleSubmit = async (
    values: DataInput,
    { setSubmitting }: FormikHelpers<DataInput>
  ) => {
    console.log(`in submission`);
    console.log(`form submit values: ${JSON.stringify(values)}`);
  };

  const formik = useFormik({
    initialValues,
    validationSchema,
    onSubmit: handleSubmit
  });

    <FormikProvider value={formik}>
      <Paper className={classes.paper}>
        <Box
          component={Form}
          display="flex"
          flexGrow={1}
          flexDirection="column"
        >
          <Grid container alignItems="center">
            <Grid item xs={2} sm={2} md={1}>
              <FormLabel htmlFor="Label">Label</FormLabel>
            </Grid>
            <Grid item xs={10} sm={10} md={3}>
              <Autocomplete
                options={Options}
                getOptionLabel={(option: optionType) => option.name}
                id="Label"
                autoComplete
                includeInputInList
                renderInput={(params: any) => (
                  <TextField {...params} name="Label" fullWidth />
                )}
              />
            </Grid>

        </Box>
      </Paper>
    </FormikProvider>
...

if i just write on the autocomplete the value can be shown, however, the value will not be shown when i select option in "auotcomplete"
by seeing result on console.log(`form submit values: ${JSON.stringify(values)}`); in the console on chrome

Please help!!! thanks

**Comment by sambrodriguez** [comment]
I actually ran into this issue myself a few weeks ago. The problem has to do with how the autocomplete handles its onChange functions, since they have a different function signature compared to other material fields. I had to override the default onChange with something like this:

```
export default function StateAutocomplete({field, form, ...props}) {
  return (
    <Autocomplete
      {...props}
      onChange={(event, newValue) => {
        form.setFieldValue(field.name, newValue);
      }}
      onBlur={field.onBlur}
      onInputChange={(event, newValue) => {
        form.setFieldValue(field.name, newValue);
      }}
      options={USStates.map(option => option.name)}
      renderInput={inputParams => (
        <TextField
          {...field}
          {...inputParams}
          name={field.name}
          variant="outlined"
          fullWidth
          inputProps={{...inputParams.inputProps, autoComplete: "address-level1"}}
        />
      )}
    />
  )
}
```

The important parts to note are the onChange, onBlur, and onInputChange functions. They're the ones that don't get mapped correctly automatically. Also note that the Autocomplete component is still in the lab so things could still change with it before its full release.

**Comment by dev-cyprium** [comment]
I'm facing the same issue on my project too. Thanks @sambrodriguez for the quick fix-up though, the `setFieldValue` solved my problem niecley. 

```tsx
export interface AutocompleteSelectProps
  extends Omit<AutocompleteProps, 'renderInput'> {
  name: string;
}

export const AutocompleteSelect = (props: AutocompleteSelectProps) => {
  const { values, setFieldValue } = useFormikContext<FormValues>();

  return (
    <Autocomplete
      options={props.options}
      getOptionLabel={props.getOptionLabel}
      onChange={(_, val) => setFieldValue(props.name, val)}
      value={values.autocompleteValue}
      renderInput={params => (
        <TextField
          {...params}
          label="My Label"
          variant="outlined"
          fullWidth
        />
      )}
    />
  );
};
```

Another sidenote that's related is that `value` is considered `any`. It would be nice to be able to type it inside the `setFieldValue<T>` or something if possible?

**Comment by RonaldCY** [comment]
thanks @sambrodriguez , the setfieldvalue can fix it nicely. I'm  just wondering userFormik it should update automatically, however, now in the autocomplete this case not possible?

**Comment by sambrodriguez** [comment]
> thanks @sambrodriguez , the setfieldvalue can fix it nicely. I'm just wondering userFormik it should update automatically, however, now in the autocomplete this case not possible?

In general I don't think the material UI components work with formik without some sort of wiring. You can use https://www.npmjs.com/package/formik-material-ui to make it easier, but they don't support the new Autocomplete component.

**Comment by jaredpalmer** [comment]
Use setFieldValue and setFieldTouched or the new helpers provided in useField.
