### ISSUE TITLE
Linkings in the table of contents should work

### ISSUE THREAD

**Issue by Lyfexu** [jaredpalmer/formik#2142]
#### Problem
Currently headings containing a `=>` are not correctly linked in the autogenerated table of contents due to a docusaurus bug.

#### Example
The `onReset` link at [Formik](https://jaredpalmer.com/formik/docs/api/formik) has an `href` attribute of
`#onreset-values-values-formikbag-formikbag-gt-void`
but should be
`#onreset-values-values-formikbag-formikbag-void`

#### Fix
Upgrade to the current Docusaurus version (1.14.3)

**Comment by jaredpalmer** [comment]
Can you submit a PR?
