### ISSUE TITLE
Why setFieldValue("entities", [ ]) delete the "entities" values of form in v2.0.7

### ISSUE THREAD

**Issue by aehp20** [jaredpalmer/formik#2143]
Hello,

I use an array in a field of my form. 
Like: form.setFieldValue("entities", [ {id: 1234, name: "toto"} ])
And I have, form = { "entities": [ {id: 1234, name: "toto"} ] }

I noticed that in the version 2.0.6 we can have a property with empty array.
Like: form = { "entities": Array(0) }

But in the version 2.0.7 and 2.0.8, if the property has an empty array, then the field is deleted.
Like: form.setFieldValue("entities", [ ]) is converted to form = { }

I see the changes in the function setIn in utils.ts file:
https://github.com/jaredpalmer/formik/blob/v2.0.6/src/utils.ts
https://github.com/jaredpalmer/formik/blob/v2.0.7/src/utils.ts

I want to know if this change is right for you ?

**Comment by viniciusdacal** [comment]
There's already another issue opened #2130. And there's a PR waiting for review :)

**Comment by aehp20** [comment]
Thanks for this information.

**Comment by viniciusdacal** [comment]
issue fixed at 2.0.11. I believe we can close it. @jaredpalmer
