### ISSUE TITLE
Prevent re-render on every change while using useField

### ISSUE THREAD

**Issue by hadiranjbar25** [jaredpalmer/formik#2149]
I am using useField instead of FastField. How can I prevent re-rendering on every change? Is there any way to make this re-rendering conditional based on a props?

**Comment by jaredpalmer** [comment]
This is not possible because there is no way to select slices of useContext, or bail out with sCU/memo on a custom hook

**Comment by brendanmoore** [comment]
I would say that this is not entirely true - it is definitely possible to conditionally render using shared state and custom hooks (see Jotai/Recoil) - however adding that feature to Formik it is certainly **non-trivial**.  IMO it should be a feature in React
