### ISSUE TITLE
Check what fields have changed in submit

### ISSUE THREAD

**Issue by goodmind** [jaredpalmer/formik#215]
How to check what fields changed in `handleSubmit`?

**Comment by prichodko** [comment]
Compared to what? Can you provide more details?

**Comment by goodmind** [comment]
I mean `touched` field in `handleSubmit`

**Comment by prichodko** [comment]
When submitting `Formik` sets all fields as touched https://github.com/jaredpalmer/formik/blob/master/src/formik.tsx#L475, so error messages can be shown properly.

**Comment by goodmind** [comment]
My case is that I want to only update fields that changed, because I have different API request for each field

**Comment by prichodko** [comment]
Then you can maybe check `values` inside `onSubmit` and if it's not empty, send a request?

**Comment by goodmind** [comment]
@prichodko I have default values from server

**Comment by mshibl** [comment]
I'm having a similiar issue -- I think the idea is to somehow add a `dirty` prop for each form field

**Comment by jaredpalmer** [comment]
You can compare initialValues and values within handleSubmit/onSubmit

**Comment by sbrichardson** [comment]
@goodmind, This lib is helpful:  [deep-object-diff](https://github.com/mattphillips/deep-object-diff)

**Comment by lkbr** [comment]
True. I'm fumbling around so could be something obvious I'm missing:

The data I get from the server is not always in the required shape of a field, thus I'm doing some transformations in `initialValues`. If I can't pass initialValues, I'd have to repeat the transforms in `onSubmit` so I'm comparing against the same thing. Maybe `initialValues` is the wrong place and I should just do transforms further up in the tree?

``` jsx
const Form = ({ post: { content } }) => (
  <Formik
    initialValues={{
      content:
        content && !isEmpty(content)
          ? new EditorState.createWithContent(convertFromRaw(content))
          : new EditorState.createEmpty()
    }}
    onSubmit={{}}
    render={{}}
  />
)
```

**Comment by jaredpalmer** [comment]
Yes, I think you need to transform in 2 places.

**Comment by lkbr** [comment]
Brilliant. Thank you for Formik - it's been a great experience.

**Comment by jaredpalmer** [comment]
Fun Fact: Formik initially had a prop called `mapValuesToPayload`. My idea was to centralize these sort of transforms in one place so you knew where to look. It was redundant because it can just go at the top of `handleSubmit`/`onSubmit`, but the idea was to keep things organized.

**Comment by lkbr** [comment]
I for one appreciate the narrow focus of Formik, you could easily end up recreating the world in utility functions. Just that when you're new to something its not always easy to know what the package has taken on and what they have deliberately left to the user (Not unique to Formik or a criticism).

**Comment by MelkorNemesis** [comment]
I wrote an article **How to check if Formik values have changed on submit**, this may help someone https://medium.com/@MelkorNemesis/how-to-check-if-formik-values-have-changed-on-submit-2c6ee89992ec

**Comment by vaibhavhrt** [comment]
Why not just check for `form.dirty` in onSubmit, like this:

```js
// useState for initialValues to keep updating it using an useEffect hook as data on server changes
const [initialValues, setInitialValues] = useState({foo: "bar"});

const form = useFormik({
  enableReinitialize: true, // required to have dynamic initialValues
  initialValues,
  onSubmit: async (values, { setErrors }) => {
    console.log({ values, dirty });
    if (!dirty) return Promise.resolve();
    // else do stuff
  },
});
const { errors, touched, getFieldProps, handleSubmit, dirty } = form;
```

Seems to be working fine for me, @jaredpalmer  let me know if this technique has any caveats I should be aware of.

**Comment by mateja176** [comment]
```tsx
import React from 'react'
import { useFormik } from 'formik' 

const Component: React.FC = () => {
  const { handleSubmit, dirty, getFieldProps } = useFormik({
    initialValues: { email: 'john@doe.com' },
    onSubmit: Promise.resolve,
    validationSchema: yup.string().email(),
    validateOnMount: true
  })

  return (
    <form submit={handleSubmit}>
      <input {...getFieldProps} />
      <button disabled={!dirty}>Submit</button>
    </form>
  )
} 

```

**Comment by devnasim** [comment]
Maybe that is helpful

Step - 1

` useEffect(() => {
    setFieldValue('initialValue', values);
  }, []);`
  
 Step 2
 ` handleSubmit: (values, { props }) => {
    const input = omit(values, 'initialValue');
    const finalValues = findDirtyFields(input, values.initialValue);
    props.onSubmit(finalValues);
  },;`
  
  here is findDirtyFields
  `import { transform, isEqual, isObject } from 'lodash';

function changes(object, base) {
  return transform(object, (result, value, key) => {
    if (!isEqual(value, base[key])) {
      result[key] =
        isObject(value) && isObject(base[key])
          ? changes(value, base[key])
          : value;
    }
  });
}

function findDirtyFields(object, base) {
  return changes(object, base);
}

export default findDirtyFields;
`

**Comment by Humed-Muhammad** [comment]
const {initialValues, values} = useFormikContext()
Inside your child component and compare the two
