### ISSUE TITLE
Is there a way to set InitialValues with a function ?

### ISSUE THREAD

**Issue by eranabir** [jaredpalmer/formik#2156]
i don't want to use the initialValues prop to init the default values for the form
i would expect a function let say setInitValues that i can use any where i want 

is there some thing like that ? 

thanks

**Comment by mrowe009** [comment]
this is a little bit related to my issue here https://github.com/jaredpalmer/formik/issues/2048 it hasn't gotten much feedback, but i would greatly appreciate if we did not even have to define the initialValues props

**Comment by realduolaf** [comment]
I'm curious about the reason, could you describe the specific scene? 

why not:

```ts
function generateInitialValues() {
  return {
    // whatever  
  }
}
const formik = useFormik({
  initialValues: generateInitialValues(),
  onSubmit: () => {}
})
```

Is there a problem with typescript type?

**Comment by eranabir** [comment]
i am not using useFormik
i am using <Formik>{children}</Formik>

**Comment by jaredpalmer** [comment]
You can do this with just JavaScript as long as the function returns an object.

**Comment by coderinblack08** [comment]
Its a bit late but I'm running into the same issue, @jaredpalmer can you show an example? Setting initialValues as a function makes the initialValues the variable name for me.

**Comment by lcampanis** [comment]
Here's a correct way to setup your initialValues using hooks:
```js
initialValues: useMemo(() => {
  let values = {};
  // ... do your logic in here and set values[yourKey] for each field as mentioned in docs https://formik.org/docs/api/formik#initialvalues-values
  return values;
}, []) // hook is called once and only once
```
