### ISSUE TITLE
Single checkboxes with a boolean value are not handled correctly

### ISSUE THREAD

**Issue by eliamaino-fp** [jaredpalmer/formik#2160]
### Current Behavior

In a form having a checkbox input with a boolean as initial value, when toggling the checkbox the value is not a boolean anymore. (it's either an Array or `undefined`)

### Expected behavior

A single checkbox input provided with a boolean initial value should keep having a boolean value when toggled.

### Reproducible example

https://codesandbox.io/embed/formik-checkbox-wrong-value-qbh64?fontsize=14&hidenavigation=1&theme=dark

### Suggested solution(s)

https://github.com/jaredpalmer/formik/pull/2159

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |2.0.10
| React            | 16.12.0
| TypeScript       | 3.7.2
| Browser          | any
| npm/Yarn         | yarn 1.19.1
| Operating System | macOS 10.14.6

**Comment by jaredpalmer** [comment]
Good catch
