### ISSUE TITLE
How to avoid the error: ...but you forgot to pass an `id` or `name`

### ISSUE THREAD

**Issue by dennisat** [jaredpalmer/formik#2164]
## ❓How can we have custom `<input>` without connected them to the output data.

Having `<input>` elements without `id` or `name` attrs, the Formik is complaining that `id` or `name` are required. For some custom components, the '<input>' elements are used internally only and their changes should not be part of the output data.

How can we avoid this console.warns?

**Comment by jaredpalmer** [comment]
You can use `setFieldValue` manually or the curried version of `handleChange`

**Comment by dennisat** [comment]
Thank you for your fast response.

There was missing a word from the description!
Could you please check it again?

The problem is that some Components in the form, are using some `<input>` elements that are helper elements and are not part of the form! Formik thinks that these  `<input>` elements are part of the form, but this is not true.

For example, a Component like this would be a Map component with a search bar. The search bar is not part of the form.

Thank you in advance.

**Comment by dennisat** [comment]
> You can use `setFieldValue` manually or the curried version of `handleChange`

Friendly reminder, are you aware of this comment? https://github.com/jaredpalmer/formik/issues/2164#issuecomment-570537828
