### ISSUE TITLE
Is there a way to soft validate using formik and yup

### ISSUE THREAD

**Issue by Rubyj** [jaredpalmer/formik#2169]
## ❓Question

@jaredpalmer 

I would like to soft validate a field using `formik` and `yup`. Meaning, the user would receive a validation "error message", but would also be able to proceed with the current value. Is there any way to do this using formik and yup?

**Comment by jaredpalmer** [comment]
Not at the moment. However, you can do this on your own either within render fn with a simple conditional on single value. Or you could create a custom component with useEffect or componentDidUodate that checked values against yup schema and kept these as warnings
