### ISSUE TITLE
Component wrapped with forwardRef cannot be used with Field component

### ISSUE THREAD

**Issue by jbojcic1** [jaredpalmer/formik#2182]
### Current Behavior

Currently `FieldConfig` has `as` properties of type `React.ComponentType<FieldProps<V>['field']> | keyof JSX.IntrinsicElements | React.ComponentType` and `component` property of type `keyof JSX.IntrinsicElements | React.ComponentType<FieldProps<V>> | React.ComponentType`, while component wrapped with forwardRef has `ForwardRefExoticComponent` type so you get the ts error if you try to use wrapped component.

### Desired Behavior

Field should accept ForwardRefExoticComponent type too.

### Suggested Solution

Extend the type to allow components wrapped with forwaredRef. So types would be something like:
as - `React.ComponentType<FieldProps<V>['field']> | keyof JSX.IntrinsicElements | React.ComponentType | ForwardRefExoticComponent<FieldProps<V>['field']>`

component - `keyof JSX.IntrinsicElements | React.ComponentType<FieldProps<V>> | React.ComponentType | ForwardRefExoticComponent<FieldProps<V>>`

### Who does this impact? Who is this for?

Typescript users.

**Comment by jaredpalmer** [comment]
Yep. Want to make a quick PR?

**Comment by jbojcic1** [comment]
Sure. I'll do it over the weekend

**Comment by jbojcic1** [comment]
You probably know this already but while working on this PR I noticed that CONTRIBUTING.md is a bit outdated and there are some lint issues in formik-native packages so I had to commit with --no-verify flag
