### ISSUE TITLE
Checkbox with undefined/null value results in an error

### ISSUE THREAD

**Issue by petrbela** [jaredpalmer/formik#2184]
### Current Behavior

When the initial value of a checkbox is `undefined` (or `null`), clicking the checkbox results in an error on [`indexOf`](https://github.com/jaredpalmer/formik/blame/e696e57c97a297b332be66515cbddfc8f4176321/packages/formik/src/Formik.tsx#L1148).

### Expected behavior

The checkbox should update without causing an error.

### Reproducible example

https://codesandbox.io/s/checkbox-with-an-undefined-value-triggers-an-error-jf53v

### Additional context

The exception is a by-product of #2159 that assumes that the value should always be an array and only deviate when it's a boolean. However, it doesn't address `undefined` and `null` values at all.

### Suggested solution(s)

I'm actually not sure what the behavior for `undefined`/`null` value should be. The HTML standard, obviously, doesn't support a boolean value for a checkbox at all and instead expects every checkbox's value to be an array. So we're in a bit of a gray area here.

My initial hunch was that we could leverage the `multiple` flag to determine whether the checkbox represents a single boolean value or an array of string values. However, since `multiple` isn't a supported attribute on a `<input type="checkbox" />` field, that would need to be explicitly documented as a non-standard behavior, plus it would break existing default behavior of array-value checkboxes (as they don't specify `multiple`). So that's probably off the table.

Option number two is to interpret `undefined` as the browser would, i.e. as an empty array value. This is a bit in contrast with `null` which should represent a singular empty value (not an array), though for consistency we could still treat it as an empty array. The drawback of this approach is you'd always have to specify a boolean initial value if you wanted the checkbox to behave as a single boolean.

The third option would treat `undefined` and `null` as a `false` boolean. If you wanted to have an array, you'd have to set the initial value to `[]`. This would be a bit inconsistent with the default checkbox behavior but (potentially) might be simpler to support booleans. But again, it probably goes against the spec more than it should.

Thoughts? cc @eliamaino-fp @jaredpalmer 

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.1.1
| React            | 16.12.0
| TypeScript       | N/A
| Browser          | N/A
| npm/Yarn         | N/A
| Operating System | N/A

**Comment by eliamaino-fp** [comment]
You're right, in the fix I made last week I forgot to change this line (https://github.com/jaredpalmer/formik/pull/2159/files#diff-13cb4898b838c74f25fbdd7bb44a139fR1135) to 
```js
const index = currentArrayOfValues.indexOf(valueProp);
```

The implementation I went for was to keep returning a `boolean` if the value was a `boolean` and to return an `array` otherwise. 

Not sure what are @jaredpalmer thoughts about that :)

**Comment by kyle-west** [comment]
I have been getting the same error for almost a week now. Looks like someone just release a fix for it a few minutes ago. #2188 should resolve it.

**Comment by zachintosh** [comment]
> I have been getting the same error for almost a week now. Looks like someone just release a fix for it a few minutes ago. #2188 should resolve it.

🎉

**Comment by petrbela** [comment]
Btw when the value is set to `'true'` or `'false'`, then it behaves like a boolean even for undefined/null initial value. Not sure if this is intended but it would be a solution for people who want to default to booleans. Just need to manually pass `checked`, too:

https://codesandbox.io/s/boolean-checkbox-with-an-undefinednull-value-ypykg

**Comment by petrbela** [comment]
As I'm switching to React Final Form for performance reasons, I found that they determine whether a checkbox is an array or a boolean simply by the presence of a `value`, which in retrospect seems like an amazingly easy an brilliant solution https://final-form.org/docs/react-final-form/types/FieldProps#without-value

**Comment by jaredpalmer** [comment]
Fixed in 2.1.2-canary
