### ISSUE TITLE
Reset Form after api response using redux

### ISSUE THREAD

**Issue by anilkumarmr** [jaredpalmer/formik#2194]
## ❓Question

Seriously, for immediate help, just ask your question on the #formik channel on [Reactiflux](https://discordapp.com/invite/MbKwYuq).

**Comment by anilkumarmr** [comment]
0


I am currently working on a React project which uses Redux and Redux-saga. I am wondering how to make the form reset after successfully completing the async api call. using redux and redux saga am I using the

`resetform({})`
but it immediately resets the form before api is successfully executed

**Comment by krvajal** [comment]
You can use the `enableReninitialize` prop as documented here https://jaredpalmer.com/formik/docs/api/formik#enablereinitialize-boolean. And update the `initialValues` of your form when the request finished, assuming they are connected to your redux store.

**Comment by anilkumarmr** [comment]
@krvajal  are you saying that we should keep the form values in redux?

**Comment by krvajal** [comment]
Nope, not at all. I am saying that __if__ you keep the `initialValues` data on redux, then you can, after successfully submitting the data, set the new data back into the store and this will make the form reinitialize with the new values. Hopefully this is what you want.

**Comment by jaredpalmer** [comment]
Going to close. My 2 cents/suggestion is to never ever try to sync interim form state outside of Formik.

**Comment by anilkumarmr** [comment]
@jaredpalmer then ho will we reset the form after async operation is executed..
i set `enableReinitialize` and then reset the state values on `componentDidUpdate()` but its not working

**Comment by maksymilian-majer** [comment]
@anilkumarmr, you can use `useFormukContext` hook for this purpose. I use it like this:
```
const ResetOnError = (props: { apiError: string }) => {
  const { resetForm } = useFormikContext()

  useEffect(() => {
    if (props.apiError) {
      resetForm()
    }
  }, [props.apiError, resetForm])
  return null
}
```

You need to put this component inside of the `Formik` element and pass the API error from your Redux store using props.
In my case, I have an MST store, but it's all the same  ;)
