### ISSUE TITLE
what's best way to update form fields without re rendering

### ISSUE THREAD

**Issue by paulopretoEI** [jaredpalmer/formik#2196]
## ❓Question

What is the best (correct way) to get the form to update some values, that are dependent on other form fields, without reseting the whole form?
i.e. I have a dropdown that `onChange` needs to call a function that gets values to others fields on the form. So I handle the values assignment on the validate of `Formik`, like this:

````
            <Formik<FormData>
                initialValues={{
                    ProductList: "",
                    AccountList: "",
                    Amount: "",
                    InitialDate: moment(),
                    AutoRenovate: this.state.productDetails.data && this.state.productDetails.data.RenewAuto,
                    InterestCapitalization: this.state.productDetails.data && this.state.productDetails.data.InterestRate
                }}
                validationSchema={newTermDepositSchema(t)}
                onSubmit={this.onSubmit}
                validate={values => {
                    if (selectedProductList !== values.ProductList) {
                        this.getProductDetails(values.ProductList);
                        const product: ITDProductDetail | null = productDetails.data
                        if (product) {
                            values.AutoRenovate = product.RenewAuto;
                            values.InterestCapitalization = product.InterestRate;
                        }
                    }
                }}
            >

````

But the problem is that the values of `AutoRenovate` and `InterestCapitalization` won't update immediately after the assignment. For the values to update I have to run the `onBlur` on other field of the form.

So what I'm suppose to do is: `select drop -> call the function that gets the details -> assign values to form fields`

I'm using `formik: 2.0.8` and `react: 16.12.0`

**Comment by jaredpalmer** [comment]
`values` are read-only React state and can't be mutated directly. You can set them using `setValues` or `setFieldValue`. To get the behavior you want, you likely want to use `React.useEffect(() => { /* check values and then set them */ }, [values])` in a custom component or hook beneath your `<Formik>` component.

**Comment by cawel** [comment]
If you're calling `setValues()` inside your effect which depends on `values`, wouldn't you create an infinite loop?

```js
const BusinessLogic = () => {
  const { values, setValues } = useFormikContext();
  useEffect(() => {
    setValues({ someField: "other" });
  }, [values]);
  return null;
};

<Formik initialValues={{ someField: "x" }}>
  <Form>
    <Field name="someField" type="text" />
    <BusinessLogic />
  </Form>
</Formik>
```

**Comment by cawel** [comment]
Something like this makes it possible to have a centralized place where one can have some business logic with the context of all form field values:

```js
const BusinessLogic = () => {
  const { values } = useFormikContext();
  useEffect(() => {
   values.firstName = values.firstName.toUpperCase();
   values.lastName = values.lastName.toUpperCase();
   // virtual field
   values.fullName = values.firstName + ' ' + values.lastName;
  }, [values]);
  return null;
};

export const FormExample = () => (
  <Formik initialValues={{ firstName: '', lastName: '' }}>
    <Form>
      <Field name="firstName" type="text" />
      <Field name="lastName" type="text" />
      <BusinessLogic />
    </Form>
  </Formik>
);
```

**Comment by johnrom** [comment]
@cawel modifying the values object directly is not supported. For example, if you had another useEffect or other dependency that would run only when one of those values changed, it wouldn't be triggered after you make your changes. It's recommended to always use one of the formik helpers `field.setValue` or `form.setValues`.

We're working on implementing a `parse` prop that would help with capitalizing values on change.

**Comment by cawel** [comment]
I was trying out what @jaredpalmer was suggesting, as an attempt to have a sort of global `onChange` for the form. And hitting the "submit" button would actually do what we expect from the code. 

And in order to test what you described, I added another component after `<BusinessLogic />` in which I also put a `useEffect()` and it worked as expected: I could make another transformation (appending a few chars) to one of the values for which I already applied a transformation (uppercasing). Maybe I did not understand what you meant when you wrote I could not add another `useEffect`?

However, calling `setValues()` from within the effect created (without a surprise) an infinite loop, because the effect itself depends on `values`.

**Comment by johnrom** [comment]
@cawel did you try moving the other component _before_ BusinessLogic? It will (or should theoretically) trigger during the initial change, receive the changed values, then never trigger a second time after you've changed the values in your `useEffect`. The solution won't necessarily work for a broad audience, so I wanted to point out possible issues that might occur, and point to the new #2255 format and parse solutions that will help in the future.

**Comment by cawel** [comment]
@johnrom so what would you recommend if I would like to make changes to some arbitrary field values, when some other field values change. I'm looking for a sort of form-level `onChange()` callback.

If I call `setValues()` from within a `useEffect` which depends on `values`, it will create an infinite loop.

**Comment by johnrom** [comment]
You should check if the useEffect actually causes a change. If it doesn't, don't call setValues. Infinite loop averted. You can also make useEffect dependencies more specific, which I always recommend. Assuming you parsed uppercase using a custom onChange function instead, your initial full name function would then be:

```
  useEffect(() => {
    setValues({
        ...values, 
        fullName: `${values.firstName} ${values.lastName}`
    });
  }, [values.firstName, values.lastName, setValues]);
```

This could technically be subject to race conditions, so it might be good to keep an eye on #1255 which will let you do `setValues(values => ({...values, fullName });`.

**Comment by exaucae** [comment]
I went with [flushSync ](https://beta.reactjs.org/apis/react-dom/flushSync). Although the change was fired in `setFieldValue`, `dopething `state was still holding previous value: 

````js
const DopeForm = ({ onSubmit }: DopeFormProps) => {
  const { initialValues, validationSchema, credentialTypeOptions } = useDopeForm();


  return (
    <Formik
      validateOnMount
      initialValues={initialValues}
      validationSchema={validationSchema}
      onSubmit={onSubmit}
    >
      {({
        handleChange,
        handleBlur,
        handleSubmit,
        setFieldValue,
        values,
        isSubmitting,
        errors,
        touched,
        isValid,
      }) => {

        const handleChange = (option: readonly Option[]) => {
          flushSync(() => {
            setFieldValue('credentialTypes', option, true);
          });
        };

        return (
    <div>
{ /* many things skipped */ }
                <ReactSelect
                  options={dopethingOptions}
                  onBlur={handleBlur('dopething')}
                  onChange={handleCredentialTypeChange}
                  placeholder="Select dope thing"
                  value={values.dopething}
                  isMulti
                  width="263px"
                  errorText={touched.dopething && errors.dopething}
                />
{ /* many things skipped */ }
          </div>
        );
      }}
    </Formik>

````
