### ISSUE TITLE
setValues and values

### ISSUE THREAD

**Issue by dorkblue** [jaredpalmer/formik#220]
If I have props.values as below

```
const {
 values,
 setValues
} = props

const {
 names
} = values
```

where names equals to the following object
```
{
  user1: 'jon',
  user2: 'darrell'
}
```

how do I use setValues to change names.user1 to 'Louisa' for example?

Do I have to pass the entire mutated values object into setValues? IE:
```
values.names.user1 = 'Louisa'
setValues(values)
```

**Comment by 6ewis** [comment]
@dorkblue How did you end up handling that case?

**Comment by jaredpalmer** [comment]
setFieldValue 

in 0.11.0-alpha, you could use the new array path syntax for `name="names.user1"`

**Comment by 6ewis** [comment]
I noticed it. I was about to tell you the same :)

**Comment by dorkblue** [comment]
Can I do this then?
@6ewis @jaredpalmer 

```setFieldValue('names.user1', 'Louisa)```

**Comment by doconix** [comment]
This thread is old, but if you've gotten here late, one solution is using the immer library:
```
form.setValues(
    produce(form.values, draft => {
        draft.foo = "bar"
    })
)
```

**Comment by mossa-Sammer** [comment]
> This thread is old, but if you've gotten here late, one solution is using the immer library:
> 
> ```
> form.setValues(
>     produce(form.values, draft => {
>         draft.foo = "bar"
>     })
> )
> ```

just clone the object without a new library
