### ISSUE TITLE
Nesting arrays shows "invalid value" for first level

### ISSUE THREAD

**Issue by Aeyos** [jaredpalmer/formik#2213]
**"formik": "^2.0.6",**

Hello, I was trying to make a validation for my data structure but I'm having issues.

It goes like this: I have a matrix of objects from formik:

```jsx
[
  [
    { a: '123', b: 456 },
    { a: '789', b: 999 },
  ], [
    { a: 'abc', b: 0 },
    { a: 'def', b: 1 },
  ]
]
```

so my validation schema is:

```jsx
const schema = object().shape({
  myField: array().of(
    array().of(
      object().shape({
        a: string().required(),
        b: number().required(),
      }).required(),
    ).required(),
  ).required(),
});
```

But when I pass validation, on:

```jsx
{
  myField: [
    [
      { a: '123', b: 456 }
    ]
  ]
}
```

all I get is:

```jsx
{
  errors: {
    myField: "myField[0] must be a `array` type, but the final value was: `null` (cast from the value `{
      "0": {
        "a": "\"123\"",
        "b": 456
      }
    }`).
    If "null" is intended as an empty value be sure to mark the schema as `.nullable()`"
  }
}

```

Even when I pass in the whole structure as initialValue for formik.

Removing a sinle level from the nesting, makes it work again...

```jsx
const schema = object().shape({
  myField: array().of(
    object().shape({
      a: string().required(),
      b: number().required(),
    }).required(),
  ).required(),
});
```

**Comment by esvyridov** [comment]
Your example works for me in sandbox. How do you import Yup?
https://codesandbox.io/s/yup-playground-qq56u

**Comment by Aeyos** [comment]
@esvyridov I'm using CRA, importing yup like this:

```
import {
  object, string, mixed, array, number, boolean, date,
} from 'yup';
```

That's just it, yup seems to be doing fine but something must've gone wrong with the integration.

I created a minimal sandbox to show the error:

https://codesandbox.io/s/elastic-matsumoto-c4bmi

**Comment by jamesremuscat** [comment]
I've been experiencing the same issue, and I've poked around in the Chrome debugger.

It looks like the `prepareDataForValidation` method is sometimes converting an array into an object whose keys are string representations of the integer indices of the original array, e.g. in some circumstances `"foo": ["bar", "baz"]` is becoming `"foo": { "0": "bar", "1": "baz" }`.

Chrome dev tools seem to be interpreting it as an array, which is extremely confusing, but `JSON.stringify` claims it's a (non-array) object...

![Selection_004](https://user-images.githubusercontent.com/3471844/73612062-53d9e080-45e0-11ea-984d-f4d041a68a18.png)

**Comment by Aeyos** [comment]
@jamesremuscat You are correct, it seems that at some point the array was converted into an object, the error message points to this

{"myField":["myField[0] must be a `array` type, but the final value was: `null` (
**cast from the value `{
 "0": {
 "a": "abc",
 "b": "123"
 }
}**`
) If \"null\" is intended as an empty value be sure to mark the schema as `.nullable()`"]}

If I could take a blind guess at what happened, I'd say maybe some logic converted the array into object by using the spread operator (...) to create a new object when it should've created a new array

```
{...[
  { a: '123', b: 456 }
]}
```
equals
```
{"0":{"a":"123","b":456}}
```

**Comment by jamesremuscat** [comment]
I think I see the problem. I'll try and draw up a PR later.
