### ISSUE TITLE
Migration guide: please mention that `ref` prop doesn't work in v2 and how to replace it with the `innerRef`

### ISSUE THREAD

**Issue by asologor** [jaredpalmer/formik#2234]
## 📖 Documentation

So I tried to migrate to v2. Luckily I tested it on a form with the `ref` and some pre-submit code.

**Comment by johnrom** [comment]
FYI we're testing out a ref implementation here: #2208 . Hopefully we can get somewhere with Ref. In the meantime, it would be ideal to have some language related to the current situation.

**Comment by asologor** [comment]
Thanks, guys!
