### ISSUE TITLE
Is the project dead

### ISSUE THREAD

**Issue by sexualmaniac** [jaredpalmer/formik#224]
I like the project and the speed it was developed. After 0.9.4 there are no changes except fixing typos in the docs.

There are several useful PRs I'm waiting for to be merged and several features are still missing (arrays and nested values). I'm afraid if the author lost his interest in this project or doesn't have time for it.

So, what's the status, maybe another maintainers needed?

**Comment by jaredpalmer** [comment]
Happy that you're excited about Formik. The project is alive and well, and most importantly, _gaining stability_. I am extremely passionate about this project and am thankful to everyone who continues contributes time and effort. 

We still need to test the perf impact of #207 before moving forward.  I started building out a benchmarking / e2e test harness locally, but this has been more time consuming than I initially expected. I will push out my WIP into user land, so the rest of the community can help out.

As for the rest of your comment, please feel free to submit PR's with your suggestions and I will be more than happy to review.

**Comment by pleunv** [comment]
Why the need for the cheeky thumbs-down? @jaredpalmer is building and maintaining an awesome form library in his spare time, meanwhile providing us with regular updates, support and clear communication, all for free. The premise of Formik was simple, easy and fast forms, and that's still true today. I for one am glad new features are given thought and careful consideration before being implemented.

Threads like this one and the [others](https://github.com/jaredpalmer/formik/issues?utf8=%E2%9C%93&q=author%3Asexualmaniac) you made here are simply toxic and the main cause of smaller OSS projects being abandoned.

**Comment by jaredpalmer** [comment]
@pleunv Thanks for the love.
