### ISSUE TITLE
Unable to uncheck the checkbox after selection and value is set to an array

### ISSUE THREAD

**Issue by emjaksa** [jaredpalmer/formik#2240]
## 🐛 Bug report

After updating formik from v2.1.0 to v2.1.2 the checkbox type sets value to an empty array instead of a boolean. As a result you cannot uncheck the checkbox. 

### Current Behavior

Unable to uncheck the checkbox after selection and value is an array

### Expected behavior

Can check and uncheck the checkbox and the form value is a boolean.

### Reproducible example

v2.1.0
https://codesandbox.io/s/formik-checkbox-v210-bl4we

v2.1.2
https://codesandbox.io/s/formik-checkbox-v212-7bwh7

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.1.2
| React            | 16.12.0
| TypeScript       |
| Browser          | Chrome 79.0.3945.130
| npm/Yarn         |
| Operating System | OSX

**Comment by emjaksa** [comment]
Looks like this was resolved in version 2.1.3

**Comment by shadowfoxish** [comment]
Note: It will still behave this way if you initialize the checkbox value to 1 or 0, so make sure to use true or false

**Comment by ScottEnock** [comment]
Experiencing the same issue. Can we reopen this please? @emjaksa

**Comment by johnrom** [comment]
This is fixed in #2255 which will land in v3.
