### ISSUE TITLE
Unable to compile formik.

### ISSUE THREAD

**Issue by radulfr96** [jaredpalmer/formik#2246]
### Current Behavior

Upon compilation the user interface loads but quickly shows the error:
![image](https://user-images.githubusercontent.com/20983472/73132962-7e72e900-4076-11ea-81fe-34f317ff255e.png)

### Expected behavior

The module compiles with no problems.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.1.2
| React            | 16.12.0
| TypeScript       | 3.7.4
| Browser          | Chrome 79.0.3945.130 64bit
| npm/Yarn         |  12.14.1
| Operating System | Windows 10 ver 1903

**Comment by jaredpalmer** [comment]
Upgrade @types/react.

**Comment by radulfr96** [comment]
That did it thanks mate.
