### ISSUE TITLE
FieldArray with radio input

### ISSUE THREAD

**Issue by Shaker-Hamdi** [jaredpalmer/formik#2247]
## ❓Question

I'm using `formik 1.5.8` the version right before version 2, and I'm trying to use `<FieldArray />` to generate multiple nested choices for the user (questions and MCQ answers).

Everything works great, but the thing is I want to generate a `radio button` input with each answer to flag this answer as the correct one.

The nested `<FieldArray />` generating fine, but as you know in order to make the `Radio Button` work, you have to give them all the same name with different values, so in this scenario, I'm giving them the name of the first answer option, so when I change them only the first answer option changes its value.

How can I do such a thing where the selected radio button changes its correct field value to `true` and the others to `false`?

Here's a `Codesandbox` to demonstarate ...

https://codesandbox.io/s/formik-yup-fieldarray-with-radio-inputs-r5yxl

**Comment by johnrom** [comment]
Radio inputs only have one value, which you need to represent singularly in Formik (as opposed to answers[0].correct). There is only one correct answer, so you want to represent it outside of the array.

You can make your method with answer[0].correct work, but I'd recommend against it unless you were planning to support multiple correct answers, at which point you could not use radio inputs anyway.

```jsx
<Formik initialValues={{
        payload: [
            {
                question: "Question One.",
                answers: [
                    "Answer One.",
                    "Answer Two."
                ],
                correctAnswer: 0,
            },
    ]}}>
        <FieldArray
            name={`payload[${index}].answers`}
        >
            {arrayHelpers2 => (
                values.payload[
                    index
                ].answers.map(
                    (
                        _,
                        index2
                    ) => {
                        return (
                            <>
                                <Field
                                    label="Answer"
                                    name={
                                        `payload[${index}].answers[${index2}]`
                                    }
                                    component={
                                        InputText
                                    }
                                />
                                <Field
                                    label="Mark As Correct"
                                    id={`payload[${index}].correctAnswer[${index2}]`}
                                    name={
                                        `payload[${index}].correctAnswer`
                                    }
                                    value={index2} // important addition
                                    component={
                                        InputRadio
                                    }
                                />
                            </>
                        );
                    }
                )
            )}
        </FieldArray>
</Formik>
```

I skipped over the irrelevant parts. If you wanted to support re-ordering, you could make the signature of the radio look more like this:

```jsx
let answers = [
    {
        value: 0, // first answer created
        priority: 1, // second answer printed
        answer: "Answer Two.",
    },
    {
        value: 1, // second answer created,
        priority: 0, // first answer printed
        answer: "Answer One.",
    }
];

// then:
answers.sort(a => a.priority).map(a => (
    <>
        <Field name={/* ... */[${index2}].value" type="hidden" />
        {/* ...other fields... */
    </>
));
```

**Comment by Shaker-Hamdi** [comment]
@johnrom Thank you for your solution, I managed to solve this in another way, I ditched the radio button altogether and just used a regular normal `button` element to set the answer correct flag to `true` and set others answers' flag in the same question to `false` ...

    <button
    	type="button"
    	className={ values.payload[index].answers[index2].correct
    			? "active"
    			: ""}
    	onClick={() => {
    		values.payload[index].answers.map(
    			(tem3, index3) => {
    				setFieldValue(`payload[${index}].answers[${index3}].correct`,false);
    			}
    		);
    		setFieldValue(flagName, true);
    	}}
    >
    	{values.payload[index].answers[index2].correct
    		? "Correct Answer"
    		: "Mark As Correct"
        }
    </button>

Here's the `Codesandbox` link for my solution.
https://codesandbox.io/s/formik-yup-fieldarray-with-buttons-instead-of-radio-inputs-0ek59

It's not as elegant as your solution, but it works for my case, as I have to send the request in that shape (each answer is an object with "correct" flag), so that would save me time as I would get the `payload` values as is and send it.

But now that you mentioned the `multiple` correct answers, that got me thinking, how would I make something like that work? with Checkboxes?
If you have an example somewhere it would be great if you can share it.

**Comment by johnrom** [comment]
Yeah, checkboxes would be a great way to represent multiple correct answers, and you could still use your `.correct = true` shape. I don't have an example, but it'd be similar to what you were initially doing with type="checkbox". You could have a checkbox for `question.HasMultipleAnswers` and if it is checked, switch between your current button technique and a normal checkbox field.

If you need your exact shape, radio button won't work so I think you're on the right path.
