### ISSUE TITLE
Store all form element values in store before submit 

### ISSUE THREAD

**Issue by cybercoder** [jaredpalmer/formik#2248]
## ❓Question

I did create a form wizard using ```react-navigation-stack``` in react-native.
When going back in the stack previous screen will unmount (natural pop from the stack). So i need a way to save current form element values (not validated and not submitted) when push back. I can't find how i can do it using ```formik```.

Sorry for the question.

**Comment by mrmuhammadali** [comment]
One recommended way would be to save values while validating, you can validateOnMount, validateOnChange and validateOnBlur.
If you don't want to validate then you can use `innerRef` prop in formik v2.1.2 or `ref` in v1, to extract the state of values while changing the screens.

**Comment by jaredpalmer** [comment]
@mrmuhammadali this is a good way to do it!
