### ISSUE TITLE
JsDoc for mapPropsToErrors function uses description of mapPropsToTouched

### ISSUE THREAD

**Issue by harrison-symes** [jaredpalmer/formik#2257]
## 📖 Documentation
![image](https://user-images.githubusercontent.com/19971385/73412197-bc208c00-436c-11ea-89b0-aab6e6756bc1.png)

As seen above, the jsdoc description for `mapPropsToErrors` is a duplicate of the description for `mapPropsToTouched`

**Comment by jaredpalmer** [comment]
Thanks!
