### ISSUE TITLE
How to pass props though the <Formik /> component?

### ISSUE THREAD

**Issue by timothyjlaurent** [jaredpalmer/formik#226]
I really like the render prop pattern. 1 thing I'm having difficulty figuring out is how to pass props through to the inner component.

I am getting dynamic choices passed in as props (from redux) and would like to pass them through to the  Formik form . I can easily do this with the `withFormik` HOC but I'd like to be able to use the `<Formik />` component and access these extra props.

**Comment by timothyjlaurent** [comment]
Solved here: https://github.com/jaredpalmer/formik/issues/194

**Comment by haseebanwar** [comment]
To pass props to child Formik component use use a child callback function:

``` jsx
<Formik
  initialValues={{ foo: 'bar' }}
  onSubmit={() => console.log('submit')}
>
    {(formikProps) => <NewComponent {...props} {...formikProps} />}
</Formik>
```

**Comment by juandiii** [comment]
You can pass props to Component using callback props
```js
 <Formik
    initialValues={{
        id: 1,
        name: 'Juan'
    }}
    component={(props) => <NewComponent newProp={`Hi`} {...props} />}
    onSubmit={onSubmit}
/>
```
