### ISSUE TITLE
setFieldValue automatically nests value that includes dot

### ISSUE THREAD

**Issue by danielnmai** [jaredpalmer/formik#2262]
### Current Behavior

When setting field value, if the value contains a "." character, it will output a nested object in `values` prop.

### Expected behavior

If the key contains a special character like "." and it is not intended to be used as an object notation, formik should not nest it.

### Reproducible example

```
onLineItemSelected =() => {
  const { setFieldValue, values } = this.props;
  setFieldValue('test.dot', true);  // values prop is { test: { dot: true}}
};

// ....
export default withFormik({
    mapPropsToValues: props => {
      const formValue = {};
      props.lineItems.forEach(lineItem => {
        formValue[lineItem.name] = false;
      });
      return formValue;
    },
  })(Component);
```

### Environment

Formik: ^1.5.8
React: 16.8.3
npm: 6.9.0
OS: Mac OS

**Comment by jaredpalmer** [comment]
This is a feature not a bug. It allows you to set nested value using lodash’s path syntax.

**Comment by danielnmai** [comment]
So is there a way to disable this nesting behavior? I'm working with items name that sometimes have dot character in them. Currently my fix is not using the `setFieldValue` method at all, instead I use `setValues`

```
onLineItemSelected = (key, data) => {
+    const { values, setValues } = this.props;
+    setValues({ ...values, [key]: data });
   };
```

**Comment by dimylik** [comment]
Feature with nested fields is still actual.
I made a workaround, works for me:

onChange={event => {
       if (field.includes('.')) {
                const splitPath = field.split('.')
                const path = splitPath[0]
                let temp = {...values[path]}
                temp[splitPath[1]] = event.target.value
                setFieldValue(path, temp)
              } else {
                setFieldValue(field, event.target.value)
              }
}}

**Comment by tpettrov** [comment]
Will be a good idea to make the nesting optionable.
