### ISSUE TITLE
Why formik is dependent on lodash and lodash-es?

### ISSUE THREAD

**Issue by latuszek** [jaredpalmer/formik#2267]
## ❓Question
Why formik is dependent on lodash and lodash-es? Shouldn't it utilize only one of the dependencies?

**Comment by ranisalt** [comment]
It not only depends on both, it apparently simply does not use -es version.

**Comment by nikitaindik** [comment]
It's surely better to fix it in Formik, but in the meantime we can use a Webpack alias to drop "lodash-es" from the bundle: https://github.com/GoogleChromeLabs/webpack-libs-optimizations#alias-lodash-es-to-lodash

**Comment by TrySound** [comment]
There is nothing to fix in formik. lodash-es is used by esm bundle. You better to alias commonjs version because webpack wraps each commonjs module with function. So you end with bigger bundle size.
https://unpkg.com/browse/formik@2.1.4/dist/formik.esm.js

The recommendation is wrong.

**Comment by latuszek** [comment]
Maybe it would be better to use a single dependency in a way described [here](https://www.blazemeter.com/blog/the-correct-way-to-import-lodash-libraries-a-benchmark).

**Comment by TrySound** [comment]
Single dependency is used. But different for node and for bundler. All packages should follow same (or just avoid using lodash).

**Comment by mfilar** [comment]
I don't know why this was closed, version 2.4.6 still depends on lodash and lodash-es

<img width="725" alt="Screenshot 2024-07-24 at 14 41 18" src="https://github.com/user-attachments/assets/5fa71a35-8392-46ce-84d8-d23e1bfa76a9">
