### ISSUE TITLE
How to required field using react-number-format?

### ISSUE THREAD

**Issue by duongynguyen** [jaredpalmer/formik#2270]
Hi everyone,

I have an issue when using react-number-format with Yup to validation. When I validation for the NumberFormat field, It works well with Yup when that field is required field until I refresh the page and type something in the input field then remove all and submit. The message error does not appear although It still is a required field. This issue works well when I refresh the page. I have a little code in codesanbox, you can try it with the link is below

https://codesandbox.io/s/yup-with-react-number-format-l4cdw

My platform:
Node 8.11.3
Yup ^0.27.0
Formik ^2.0.3
React ^16.8.6
React-number-format ^4.3.1

Could you help me, please? Thank you so much.

**Comment by johnrom** [comment]
@duongynguyen the issue is that if onValueChange returns a non-number ("" isn't cast to anything), you'll still need to return a value. Using an undefined value actually removes the field from the `values` object.

**Comment by duongynguyen** [comment]
@johnrom thank you, John.
My code works well when I implement it to follow your way. So great!!!
