### ISSUE TITLE
[Question] Dynamic form fields

### ISSUE THREAD

**Issue by metsavaht** [jaredpalmer/formik#228]
I have a dynamic form where last field is empty and would like to add new empty field after user fills current  last field.

How would one achieve this with `formik`? I tried `setFieldValue` and `setValues` but it seems after values are initialized, I cannot change form fields.

What I ended up with is a parent component which remembers fields from the form. So I wandered if that is the only way, or am I missing something.

**Comment by jaredpalmer** [comment]
Depending on validation requirements, you can Yup has some extension / lazy validation helpers. 

You should use setValue or setFieldValue.

**Comment by metsavaht** [comment]
Ok, I think the issue was were I tried to call setFieldValue.

Thanks for your input.
