### ISSUE TITLE
Gatsby Building static HTML failed: Cannot read property 'getFieldProps' of undefined

### ISSUE THREAD

**Issue by sakhmedbayev** [jaredpalmer/formik#2281]
## 🐛 Bug report

Getting this error on gatsby.js' build command

```
error Building static HTML failed for path "/"

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html

  1287 | function useField(propsOrFieldName) {
  1288 |   var formik = useFormikContext();
> 1289 |   var getFieldProps = formik.getFieldProps,
       | ^
  1290 |       getFieldMeta = formik.getFieldMeta,
  1291 |       getFieldHelpers = formik.getFieldHelpers,
  1292 |       registerField = formik.registerField,


  WebpackError: TypeError: Cannot read property 'getFieldProps' of undefined
  
  - formik.esm.js:1289 useField
    [lib]/[formik]/dist/formik.esm.js:1289:1
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | ^2.1.4
| React            | ^16.8.6
| TypeScript       | n/a
| Browser          | latest Chrome
| npm/Yarn         | Yarn
| Operating System | iOS

**Comment by johnrom** [comment]
Can you make sure you're using `useField` underneath a `<Formik />` or `withFormik`  in the component hierarchy?

This would happen if you did something like:

```
const MyForm = () => {
    // error: there is no parent Formik context
    const [props] = useField("myField");

    return <Formik initialValues={{ myField: "" }}>
        { /* 
           * useField and useFormikContext hooks are only available to components in here. 
           * note, they cannot be used within this render area, but only within child components 
           */ }
    </Formik>;
}
```

**Comment by sakhmedbayev** [comment]
@johnrom here is how I am using it:

```
<Formik
        initialValues={{
          name: "",
        }}
        onSubmit={async (values, { setSubmitting, resetForm }) => {
          console.log(values)
        }}
        validationSchema={schemaValidation}
        validateOnBlur={false}
      >
        {({ isSubmitting, errors, touched, setFieldValue }) => (
          <Form>
            <CustomInput
              name="name"
              labelText="Your Name"
              id="float"
              formControlProps={{
                fullWidth: true
              }}
            />
</ Form>
</ Formik>
```

and then in `CustomInput`

```
export default function CustomInput(props) {
  const [field, { error }] = useField(props);

  const {
    formControlProps,
    labelText,
    id,
    labelProps,
    inputProps,
    white,
    inputRootCustomClasses,
    success
  } = props;
...
```
Interesting enought that whiel in gatsby's dev environment everything works.

**Comment by sakhmedbayev** [comment]
My bad... :-( found another place where `CustomInput` was used outside Formik's context

**Comment by johnrom** [comment]
Awesome! Glad it was as simple as that, and glad I could help!

**Comment by rajat-arora084** [comment]
Is there a way to conditionally use useField hook.
I am asking as i have a couple of components which I want to use wit/without formik based on the complexity.

I can also copy the component & create a new copy without formik. But thats what i do not want to do.
Is there any way?

**Comment by johnrom** [comment]
> is there a way to conditionally use - any - hook?

No, because conditionally calling a hook violates the rules of React. You can, however, call a different component. You could create a variant of a component which is "Formik connected", and a variant which is not.

Theoretically, we could make it so that a component continues working whenever these hooks are called outside of context; however, I think that would add more questions than answers. Devs who forget to create the context (by using <Formik />, etc) would have no idea why their fields and forms aren't working because there was no error.

**Comment by rajat-arora084** [comment]
This is something that we can do & it works just fine. But the only drawback it has is that it will lead to duplicating the components.
What i was looking for is something like a _register_ _boolean_ which when passed to the _useField_ props wont read the _Formik_ Context. If that can be done, it will solve the problem & will also save the duplication.

**Comment by rajat-arora084** [comment]
> > is there a way to conditionally use - any - hook?
> 
> No, because conditionally calling a hook violates the rules of React. You can, however, call a different component. You could create a variant of a component which is "Formik connected", and a variant which is not.
> 
> ```tsx
> const RawInput = (props: HTMLInputAttributes<HTMLInputElement>) => {
>   return <a {...props>;
> }
> const FormikInput = (props: HTMLInputAttributes<HTMLInputElement>) => {
>   const [field, meta, helpers] = useField(props.name);
>   const inputProps = {
>     ...props,
>     // override default props with Formik props, like `onChange`
>     ...field,
>   };
> 
>   return <Input {...inputProps} />
> }
> 
> const ConditionalInput = ({
>   formik = true
>   ...props
> }: HTMLInputAttributes<HTMLInputElement> & { formik: boolean }) => {
>   return formik 
>     ? <FormikInput {....props} /> 
>     : <RawInput {...props} />;
> }
> 
> const MyForm = () => {
>   return <div>
>     <Formik {...formikProps}>
>       <ConditionalInput name="hello" />
>     </Formik>
>     <ConditionalInput name="world" formik={false} />
>   </div>
> }
> ```
> 
> Theoretically, we could make it so that a component continues working whenever these hooks are called outside of context; however, I think that would add more questions than answers. Devs who forget to create the context (by using , etc) would have no idea why their fields and forms aren't working because there was no error.



This is something that we can do & it works just fine. But the only drawback it has is that it will lead to duplicating the components.
What i was looking for is something like a register boolean which when passed to the useField props wont read the Formik Context. If that can be done, it will solve the problem & will also save the duplication.

**Comment by johnrom** [comment]
You are correct that the hooks should not throw an error, but the Field and other components should throw an error.

```tsx
const Field = (props) => {
  const [props, meta, helpers] = useField();

  if (!props || !meta || !helpers) {
    throw "bad use of Field component";
  }

  return <input {...props} />
}
```
