### ISSUE TITLE
Set the value of an input based on something outside of the form?

### ISSUE THREAD

**Issue by kwhitaker** [jaredpalmer/formik#229]
I looked in the documentation, and didn't find an answer to this, so I apologize if it's covered and I missed.

Our app has some fields which are linked to each other. Imagine they look like this:

```
<input name="input-a" onChange={e => {props.handleChange(e); props.updateParentStuff(e)}} />
<input name="input-b" onChange={e => {props.handleChange(e); props.updateParentStuff(e)}} />
```

When one of the inputs is updated, the parent hits an API to get some kind of value back, and then the _other_ input needs to be updated, or vis-a-versa.  So the flow looks like this:

```
Update input-a => pass value to parent => call api => return value => update input b
OR
Update input-b => pass value to parent => call api => return value => update input a
```

The issue is I can't find a way to force an input in the `Formik` form to have a certain value, outside of setting the `initialValue` parameter (we're using the `render` prop).  I'm hacking around this problem right now by taking a state variable in the parent, and merging it with the values which get submitted when the form is.  I'd like to just have the values represent the actual data to be submitted, though.

Thanks!

**Comment by prichodko** [comment]
Hey @kwhitaker!

I believe there is nothing wrong with `initialValues` being dynamic. As you can see here https://github.com/jaredpalmer/formik/blob/master/src/formik.tsx#L256, when `initialValues` changes and does not equal, the form is being reset with the new value.

**Comment by kwhitaker** [comment]
Thanks. I'll take a look and try it again - maybe I[m missing something.

**Comment by prichodko** [comment]
Probably you also want to use - https://github.com/jaredpalmer/formik#enablereinitialize-boolean, which is `false`by default.

**Comment by jaredpalmer** [comment]
My suggestion is to make a class component that uses `componentWillReceiveProps` and pass it outside props. You can also pass it whatever formik props and methods it needs. Within cWRP you can compare changes and then safely call any Formik method. Although it uses context instead of passing formik props directly, this is essentiallyhow [formik-persist](https://github.com/jaredpalmer/formik-persist/blob/master/src/formik-persist.tsx#L25) works.

**Comment by jaredpalmer** [comment]
You can use this concept to make plugins/addons.

```js
const SuperFormik = ({custom, ...props}) => 
  <Formik {...props} 
     render={(p) => [
       props.render(p), 
      <Persist />, 
      <CheckProfanity customThing={custom} />,
      <SomethingElse/>
     ] // imagine that these all do stuff in cWRP and cDU but render `null`
    }
  />
```

**Comment by ganpats** [comment]
`setFieldValue` is also useful, for e.g.:
`props.setFieldValue('birth_date', selectedDate);`

**Comment by Igor2122** [comment]
> `setFieldValue` is also useful, for e.g.:
> `props.setFieldValue('birth_date', selectedDate);`

as an option we can pass `setFieldValue` as props

```typescript
const handleIcoFrom = (
    setFieldValue: (field: string, value: any, shouldValidate?: boolean) => void
  ) => {
    setFieldValue("accNumber", 55555555);
  };
onClick={() => handleIcoFrom(setFieldValue)}
```
