### ISSUE TITLE
onFieldsChange event at Formik level?

### ISSUE THREAD

**Issue by cloud-walker** [jaredpalmer/formik#231]
Hi, in my project I need to invalidate a certain state flag if the form has been updated in some way, for now, I've done my self-augmenting the `setFieldValue` and `handleChange` formik functions:

```javascript
<Formik ...>
  {({handleChange, setFieldValue, ...otherStuff}) => {
     handleChange = (...args) => {/* doing stuff... */; return handleChange(...args)}
     setFieldValue = (...args) => {/* doing stuff... */; return setFieldValue(...args)}

    return <form>awesome form full of fields</form>
  }}
</Formik>
```

But I think its a buggy way of doing it, because for example, what if formik's API changes?

**Comment by jaredpalmer** [comment]
You should probably move this work to a fn that calls `componentWillReceiveProps`. Checkout how I do this in [Formik Persist](https://github.com/jaredpalmer/formik-persist/blob/master/src/formik-persist.tsx#L25)
