### ISSUE TITLE
Impossible to use custom props in Field component

### ISSUE THREAD

**Issue by Grmiade** [jaredpalmer/formik#232]
When we use custom props in Field component, we have this error.

`[ts] Property 'leftIconName' does not exist on type '(IntrinsicAttributes & IntrinsicClassAttributes<Field<FieldAttributes>> & Readonly<{ children?: R...'.`

```typescript
public renderForm = props => (
  <form onSubmit={props.handleSubmit}>
    <Field
      required
      component={TextInput}
      leftIconName="user"
      name="email"
      placeholder="example@payfit.fr"
      type="email"
    />
    <Field
      required
      component={TextInput}
      leftIconName="lock"
      name="password"
      placeholder="Your password"
      type="password"
    />
    <Button
      className="pt-fill"
      iconName="log-in"
      intent={Intent.PRIMARY}
      loading={props.isSubmitting}
      type="submit"
    >
      Sign in
    </Button>
  </form>
)
```

**Comment by jaredpalmer** [comment]
Ahh you're totally right. I was trying to make Field types a tiny bit more restrictive. 

Basically, we need an interface that's like "you need at least a `name: string` & whatever props you want to define.", but AFAICT that's not really possible with React right now because there are no generics on JSX components. Ughhhhh. Will patch.

https://github.com/jaredpalmer/formik/blob/master/src/Field.tsx#L74

**Comment by alexhoo** [comment]
Same error for me when i try to use Fabric components. 
`const renderCombobox:any = ({input, label, options, ...custom}):any => (
    <ComboBox label={label}
              ariaLabel={label}
              allowFreeform={false}
              required={true}
              autoComplete="on"
              onChanged={params => input.onChange(params.text)}
              useComboBoxAsMenuWidth={true}
              options={options}
        />
);``
`<Field name="audienceCB"
                       component={ renderCombobox }
                       label="Audience"
                       options={audienceOptions} // error TS2339: Property 'options' does not exist on type '(IntrinsicAttributes & IntrinsicClassAttributes<Field<GenericFieldHTMLAttributes>> & Readonly<{ c...'.
                      />`

**Comment by Divsalar** [comment]
I am having same issue as you @alexhoo, have you found any solution for this? 
Many thanks

**Comment by jaredpalmer** [comment]
This is fixed in 11.rc2 .

**Comment by rifler** [comment]
but `leftIconName` now is untyped. For example
```jsx
<Field
    name="name"
    component={YourComponent}
    yourComponentProp="lihgt" // oops typo
/>
```

TS doesn't print any errors. In `redux-form` I made such wrappers:

```tsx
import { MyTextInput, MyTextInputProps } from './MyTextInputComponent';
import { WrappedFieldProps, GenericField, Field } from 'redux-form';

type FormTextInputProps = MyTextInputProps & WrappedFieldProps;

export const FormTextInput: React.SFC<FormTextInputProps> = (props) => {
        const {
            input: { value, onChange },
            meta: { error, invalid, touched },
            ...myTextInputProps // TS infers type here
        } = props;
        return <div>
              <MyTextInput {...myTextInputProps} />
              {invalid && touched && Boolean(error) && <div className="">{error}</div>}
        </div>;
}

export const FormTextField = Field as new () => GenericField<TextInputProps>;
```

and usage:
```jsx
<FormTextField
     name="name" // prop from 'redux-form'
     component={FormTextInput} // prop from 'redux-form'
     size="s" // prop from my component, it is a union 'xs' | 's' | 'm', and I can't make a typo here
     theme="normal" // similarly, union, I can't make a typo here too
/>
```
