### ISSUE TITLE
FieldArray push/remove does not trigger onChange in parent form

### ISSUE THREAD

**Issue by brian-kane521** [jaredpalmer/formik#2328]
### Current Behavior

I have an array of text fields. Typing in any one of those fields triggers onChange in my form, but adding/removing fields does not.

### Expected behavior

I would expect onChange to trigger when push/remove is called in a FieldArray

### Reproducible example

The following sandbox will show an alert when onChange is called (e.g. when text is typed)
https://codesandbox.io/s/formik-codesandbox-template-5o8kz

### Suggested solution(s)

Hook in a synthetic event to push/remove?

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.8
| React            | 16.8.6
| Browser          | multiple/Chrome
| npm/Yarn         | 6.9.0
| Operating System | Win10 Pro

**Comment by brian-kane521** [comment]
Is there any simple workaround for this? Is this intended behavior?

**Comment by Nelias** [comment]
This is still an issue!

**Comment by firattale** [comment]
I still have this problem, any opinions?

**Comment by johnrom** [comment]
Formik does not support form-level `onChange` 

#2244
#2486
