### ISSUE TITLE
How to change the touched field in handleChange instead of onBlur？

### ISSUE THREAD

**Issue by Iixianjie** [jaredpalmer/formik#2333]
## ❓Question

By default, touched can only be changed when the input triggers the onBlur event, thereby displaying a validation error message, how to show the verification results in onChange

**Comment by FilmCoder** [comment]
Maybe attach handleBlur instead of handleChange to onChange of your inputs?

onChange = e => {
  formik.handleBlur(e)
}

**Comment by FilmCoder** [comment]
actually it would just be like

<input onChange=formik.handleChange .../>

I think

**Comment by FilmCoder** [comment]
OH, or you can have the onChange call formik.onChange(e) as per normal, and then imperatively set the field as touched with SetTouched

**Comment by Iixianjie** [comment]
> Maybe attach handleBlur instead of handleChange to onChange of your inputs?
> 
> onChange = e => {
> formik.handleBlur(e)
> }

It's a very good idea. 👍👍
