### ISSUE TITLE
onSubmit handler typing issue

### ISSUE THREAD

**Issue by Magellol** [jaredpalmer/formik#234]
Hey there 👋 

I've been using `formik` for quite some time but recently I've been using it with Typescript for the first time and I've came across some issue (I think) regarding the `onSubmit` handler typing.

https://github.com/jaredpalmer/formik/blob/b50e2ce19dcbe38bffcd12bfe8d5407be98e3022/src/formik.tsx#L138-L141

Because of `value: object`, I'm not able to know what's going to be the shape of my value object in TS. I've tried abstracting _a_ type  such as:

```typescript
type FormikSubmitHandler<V> = (value: V, actions: FormikActions<V>) => void;
```

Although, once done that, I get a signature mismatch when I pass the function to formik. I'm not sure what's the right fix atm but to get TS (and autocomplete) not complaining anymore I had a workaround by doing a type assertion. Here's a complete example that illustrates the issue:

```typescript
type FormikSubmitHandler<V> = (value: object, actions: FormikActions<V>) => void;

interface FormValues {
  foo: string;
  bar: number
}

// At this point, I don't know what's in `value` since it's type is `object`.
const myHandler: FormikSubmitHandler<FormValues> = (value, actions) => {
  const typedValue = value as FormValues;
  value.foo; // string
  value.bar; // number
}

render() {
  return <Formik onSubmit={myHandler} />
}
```

I'd be happy to provide a PR but I'm not sure what's to do to get it fixed (if needs be).

Thanks.

**Comment by jaredpalmer** [comment]
Yeah i just ran into this when upgrading to TS 2.6.1

**Comment by jaredpalmer** [comment]
The React types are all messed up right now. I feel your pain. I suggest bumping down to 2.5.1 until silliness settles down or removing "strict" from your ts-config temporarily.

**Comment by Magellol** [comment]
Gotcha. I'm good with the type assertions right now then.
I wasn't sure it was a react typing issue though, I thought we could update the Formik typing to pass around our own values.

Such as the suggested
```ts
type FormikSubmitHandler<V> = (value: V, actions: FormikActions<V>) => void;
```

**Comment by jaredpalmer** [comment]
I didn't bother updating to TS 2.6.1, but this generic ^^ should do the trick.

**Comment by Magellol** [comment]
Cool, that should do it :) — Thanks!
