### ISSUE TITLE
How can I trigger handlesubmit or submitForm from Outside of <Formik>

### ISSUE THREAD

**Issue by nawfalhaddi** [jaredpalmer/formik#2389]
Hello , Please i need help .. i'm working with Formik and i need to trigger handleSubmit or submitForm from outside <Formik></Formfik>

**Comment by nawfalhaddi** [comment]
I want to submit my form by using a button in header

**Comment by dennisoelkers** [comment]
Your button needs to be a subcomponent of your `Formik` component that you want to submit. If it is, you can use [`useFormikContext`](https://jaredpalmer.com/formik/docs/api/useFormikContext) in a functional component or [`connect`](https://jaredpalmer.com/formik/docs/api/connect) for any other component to get access to `handleSubmit`.

**Comment by nawfalhaddi** [comment]
useFormikContext is exactly what i've been looking for , thank you so mcuh

**Comment by rohmanhm** [comment]
@nawfalhaddi So you should put your button from outside of <Formik/> into inside of <Formik/> then?
