### ISSUE TITLE
[QUESTION] mapValuesToPayload and Network requests

### ISSUE THREAD

**Issue by AshCoolman** [jaredpalmer/formik#239]
1. What does `mapValuesToPayload` do? I can't find any docs
https://codesandbox.io/s/pgD4DLypy
https://github.com/jaredpalmer/formik/issues/77

2. Whats the/a correct way to "wait for API data" in formik e.g. when editing?
Currently I set `enableReinitialize: true`, `mapPropsToValues: ({data = {email: ''} }) => data`. This causes a "double value set", which feels like avoidable

**Comment by cesarp** [comment]
`mapValuesToPayload` is a deprecated method.

https://github.com/jaredpalmer/formik/blob/master/src/withFormik.tsx#L56
