### ISSUE TITLE
[Proposal] - resetField/resetFields

### ISSUE THREAD

**Issue by httpete-ire** [jaredpalmer/formik#240]
Hey I have been using `Formik` to create an address form. Based on the country the form fields change (US addresses have states, UK addresses dont). When the country select changes we need to reset the address fields (see example below). 

```
<CountryDropdown
  targetCurrency={targetCurrency}
  onSelect={(country: SupportedCountries) => {
    this.selectCountry(country);
    setFieldValue("addressLine1", "");
    setFieldTouched("addressLine1", false);
    setFieldValue("addressLine2", "");
    setFieldTouched("addressLine2", false);
    setFieldValue("city", "");
    setFieldTouched("city", false);
    setFieldValue("postalCode", "");
    setFieldTouched("postalCode", false);
    setFieldValue("state", "");
    setFieldTouched("state", false);
  }}
/>;
```

As you can see this is quite verbose. It would be much nicer to have a method that resets a fields properties (similar to how `resetForm` work but only for a specific field).

```
resetField("addressLine1");
resetField("addressLine2");
resetField("city");
resetField("postalCode");
resetField("state");
```

For convenience you could expose a method that takes in an array of field names and resets each field. 

```
resetFields(["addressLine1", "addressLine2", "city", "postalCode", "state"]);
```

I am happy to pick this up if you think it would be useful 🐼

**Comment by jaredpalmer** [comment]
if it's just an address form you could just do:

```js
resetForm({...values, addressLine1: '', addressLine2: '', city: '', postalCode: '', state: ''})
```

if you pass resetForm an object it will set that to `values`, but then also untouch all fields and wipe errors. Obviously not perfect for every use case, but if your form is _just_ an address form, it would accomplish almost the same thing as the above (would also wipe any errors).
