### ISSUE TITLE
[Q] Custom errors with yup validation

### ISSUE THREAD

**Issue by prichodko** [jaredpalmer/formik#241]
Right now I consider it a question, which can alter to potential proposal.

Although there could be potentially more scenarios, I think this one explains it well. Here is a minimal example: https://codesandbox.io/s/3k0lqyq3qp.

When we leave all fields empty and submit the form all errors coming from `yup` will be shown. And error which belongs to specific input disappears when onChange is called. Then we write something to both inputs, so they pass validation, and submit the form. Now we get some error from API and set those errors accordingly (line 24). Problem happens when we start editing one input, then validation is run, which returns no errors (they pass yup) and custom errors are overwritten (https://github.com/jaredpalmer/formik/blob/master/src/formik.tsx#L345), which makes overall behaviour inconsistent.

Do you have an idea how to handle this? Would it make sense to merge those errors somehow?

Thanks for your time.

**Comment by prichodko** [comment]
That is exactly what I am looking for! Thank you @jaredpalmer.
Feedback: for some reason, even if I went through the API table of contents and source code couple of times, I associate it with API errors   🤔. Maybe we should add it to the guides section?

**Comment by jaredpalmer** [comment]
Submit a PR?

**Comment by prichodko** [comment]
Will do 👍
