### ISSUE TITLE
ReadMe and Release Notes disagree on `validateOnBlur`'s default value

### ISSUE THREAD

**Issue by samvk** [jaredpalmer/formik#242]
**From the ReadMe:**

> **validateOnBlur?: boolean**
> Default is true.

From the most recent mention of "validateOnBlur" in the Release Notes:

> **Potentially breaking changes**
> validateOnBlur now defaults to false

---

Apologies if I'm misreading: but it seems the latest documented change states it's intended to be `Default: true`, while the ReadMe says `Default: false`.

**Comment by jaredpalmer** [comment]
Oooops. Yeah i messed that up. 

In 0.9.0 is what set to `false` mistakenly, then correct 0.9.1 and set back to `true`. However, it looks like i brain farted on the release note and wrote `validateOnChange`. The readme is correct:

https://github.com/jaredpalmer/formik/blob/master/src/formik.tsx#L184
