### ISSUE TITLE
Allow specification of id prop on ErrorMessage

### ISSUE THREAD

**Issue by krichter722** [jaredpalmer/formik#2427]
### Current Behavior

The type `ErrorMessage` doesn't have an id property.

### Desired Behavior

It'd be nice `id?: string` would be added to the type `ErrorMessage` and set on the outermost component that serves as error message.

### Suggested Solution

Add `id={this.props.id}` to the outer component in `ErrorMessage`.

### Who does this impact? Who is this for?

This improves handling of error messages in e2e tests. It doesn't impact users in any way as the prop can still be omitted.

### Describe alternatives you've considered

Wrapping `ErrorMessage` in a `div` which has the sole purpose of providing the id which is not nice.

### Additional context

./.

**Comment by lapstjup** [comment]
Let's say we have <ErrorMessage id="sample-id"/> after suggested change.(Ignore other props for now)
There are three ways the outer component can serve as an error message in ErrorMessage:-
1) Using render props, so the id given to ErrorMessage can't be used inside render props.
2) Using children function, so the id given to ErrorMessage can't be used inside the children function.
3) Using component prop of ErrorMessage, so the id given to ErrorMessage will work because of the way it's implemented in the code.

So giving ErrorMessage an id prop will work for 1 out of 3 scenarios.
I might be wrong here but let me know if this interpretation of suggested change was valid or not.

**Comment by canh6524** [comment]
Hoang van canh

**Comment by canh6524** [comment]
84364196659

**Comment by canh6524** [comment]
Canhductu111@mail.ru

**Comment by canh6524** [comment]
Canhductu111@gmail.com

**Comment by canh6524** [comment]
[#1 Financial market participants - Bank of Lithuania.pdf](https://github.com/formium/formik/files/5358877/1.Financial.market.participants.-.Bank.of.Lithuania.pdf)

**Comment by DouglasPds** [comment]
I will try to implement this.

**Comment by DouglasPds** [comment]
The id passed to ErrorMessage need to be rendered inside the element in children `{msg => <div>{msg}</div>}`, and in element in render function `render={msg => <div>{msg}</div>}` ??

**Comment by zeotuan** [comment]
Hi i want to take on this issue. If no one is working on it.

**Comment by imadityadi** [comment]
this is still open?

**Comment by Rajat-patel19** [comment]
Hey , I am a beginner caan anyone help me out .

**Comment by ZainGulbaz** [comment]
@krichter722  Can you please assign this to me? Thanks.

**Comment by krichter722** [comment]
@ZainGulbaz No, I can't assign users to issues. There seem to be no assignments to issues in this project.

**Comment by ZainGulbaz** [comment]
@krichter722 Thanks for the clarification. I will make a pull request then.

**Comment by udaysai1311** [comment]
Can I work on this?

**Comment by krichter722** [comment]
A property `id?: string` has been added to `ErrorMessageProps` in #3825. Afaik the id is passed to the DOM element rendered by `ErrorMessage` if `render` and `children` are not specified, according to this spaghetti code:

````
    return !!touch && !!error
      ? render
        ? isFunction(render)
          ? render(error)
          : null
        : children
        ? isFunction(children)
          ? children(error)
          : null
        : component
        ? React.createElement(component, rest as any, error)
        : error
      : null;
