### ISSUE TITLE
access field value in validationSchema of Yup

### ISSUE THREAD

**Issue by tanveersingh926** [jaredpalmer/formik#2444]
I need to apply validation on the basis of the field value user enters age is 25 then the value of the next field should be 25+1.  If the user enters the value in the 2nd field first then it gets an error after entering a higher value in the first value

**Comment by serusko** [comment]
```
Yup
  .number()
  .test('customTest', 'Number should be more than prev field', function testPrev(value) { 
    return this.parent.prevField < value;
  })
```

@tanveersingh926  please close its question not issue, go to stackowerflow next time

**Comment by tanveersingh926** [comment]
I raised a question only
