### ISSUE TITLE
Form don't submit on first time submit click 

### ISSUE THREAD

**Issue by nueq22** [jaredpalmer/formik#2448]
I am using formik in my nextjs app, I created a very simple form with 1 field without any validations and button with submit type. When I click on the submit button first-time form doesn't trigger submit an event. But on the second click submit calling. I think that my issue depends on touched status of the field but I'm not sure.

**Comment by johnrom** [comment]
@nueq22 it's a bit hard to envision what is happening here, can you please provide a codesandbox reproduction? I can take a look at that and confirm your issue.

**Comment by nueq22** [comment]
@johnrom, I found a solution, I use a custom <Button/> component in my app for buttons, that just renders button component with some classnames, and passing all props to target native button. I wrapped my Button to React.memo and now it works. I think that issue depends on re-rendering and losing event listeners, some context, etc. BTW native buttons work fine.

**Comment by johnrom** [comment]
awesome, feel free to close then!

**Comment by nueq22** [comment]
exactly, thank you

**Comment by SyedJamal030** [comment]
@nueq22 Hi there, I am also doing the same thing (using html button with customize props) and unable to get it work with type=submit, i.e. Formik onSubmit. Same problem which you were facing, submit triggers on 2nd click. Kindly, can you share your code here? How you made it work?? I am unable to understand how to use React.Memo hook here. 

Kindly guide me, thank you!
