### ISSUE TITLE
Formik errors

### ISSUE THREAD

**Issue by MinZhang9220** [jaredpalmer/formik#2465]
## ❓Question
The error is undefined when **first time** touched a input field and this field has **"required"** validation.

how to show this problem:
step1: click this link go to codesandbox: https://codesandbox.io/s/loving-shape-ye5u5?file=/src/App.tsx
step2: touch the firstName field but do not type anything,then click other place, you will get the alert information.

![image](https://user-images.githubusercontent.com/29219861/81399602-5ddf2280-917f-11ea-82eb-ad6673765278.png)

**Comment by johnrom** [comment]
Is that the right codesandbox link? I'm seeing a default React App.

You can probably pass `validateOnMount={true}` if you want the error to be populated by the first time the user clicks. Note, it will still be undefined for one or more renders, until the useEffect hook is called and validation completes.

**Comment by MinZhang9220** [comment]
@johnrom thanks so much. Add validateOnMount={true} worked for me.

**Comment by MinZhang9220** [comment]
@johnrom could you please explain what is the meaning of "undefined" for formik error? It's meaning there is no error or other meanings?
