### ISSUE TITLE
File input files

### ISSUE THREAD

**Issue by goodmind** [jaredpalmer/formik#247]
Can formik use `event.currentTarget.files` as field value after submitting form in `values`? Not the `value` property of input itself

**Comment by jaredpalmer** [comment]
As stated in #45 , we don't keep files in Formik, just the path returned by our API's. However, I think you could just do:

```
handleUpload = (e) => {
  this.props.setFieldValue('avatar', e.currentTarget.files)
}
```

**Comment by sebmor** [comment]
Would be very useful if we could submit files.
I just finished migrating a project from redux-forms to formik, and kind of disappointed to find out it doesn't support file input and I have to kind of hack around it.
