### ISSUE TITLE
Final-Result, on tutorial is crashing.

### ISSUE THREAD

**Issue by Marcelovv2** [jaredpalmer/formik#2480]
## 🐛 Bug report
The link for the final result in formik tutorial: https://codesandbox.io/s/formik-v2-tutorial-final-bq0li. 
crashes, I have tried it for one week now and it doesn't load on chrome or Firefox, in both cases the browser stops working, when the page is loaded. I used other sandboxes and the problem is no there. 
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |
| React            |
| TypeScript       |
| Browser          |
| npm/Yarn         |
| Operating System |

**Comment by johnrom** [comment]
It's true. I'm not sure why there is a useEffect to set all the text values to "lol" on that sandbox, but it is creating an infinite loop. The documentation should link to [Jared's Final Codesandbox Result](https://codesandbox.io/s/formik-v2-tutorial-final-t5fe0) and not the one it links to currently.
