### ISSUE TITLE
 `onSubmit` or `handleSubmit` swallows all errors.

### ISSUE THREAD

**Issue by adamerose** [jaredpalmer/formik#2490]
### Current Behavior

- Any errors occurring inside `onSubmit` get automatically caught and replaced with a nondescript console warning.  

![image](https://user-images.githubusercontent.com/10884874/82859446-bf73f080-9ee4-11ea-8e01-19e3b80df344.png)

### Expected behavior

- Errors should be thrown normally and propagated up

### Reproducible example

- https://codesandbox.io/s/formik-example-mkfcp?file=/src/App.js

### Additional context

- Only happens in versions `2.0.9` and onward
- This is the code causing it https://github.com/jaredpalmer/formik/blob/f117c04738ed218b5eb8916d7189e0849962d50d/packages/formik/src/Formik.tsx#L841
- This breaks global error handlers or anything that tries catching errors outside the `onSubmit` method itself

### Suggested solution(s)

- Revert that change. I don't think Formik should silently swallow errors, or at least there should be an option to make it not do that.

**Comment by johnrom** [comment]
As described on the linked PR, this is a non-issue. `handleSubmit` is meant as an event handler that catches errors and doesn't interrupt the user in the case of catastrophic failure.

If you want to handle errors in some custom way, you should use the `submitForm` method instead, as demonstrated in the sandbox I linked in the PR.

**Comment by adamerose** [comment]
> As described on the linked PR, I think this is a non-issue. `handleSubmit` is meant as an event handler that catches errors and doesn't interrupt the user in the case of catastrophic failure.
> 
> If you want to handle errors in some custom way, you should use the `submitForm` method instead, as demonstrated in the sandbox I linked in the PR.
> 
> Custom error handling is possible like this:
> 
> https://codesandbox.io/s/formik-example-sqyxe?file=/src/App.js

After considering your alternative and the problems with my pull I agree, thanks for taking a look at this.
