### ISSUE TITLE
Add ability to modify errors to the API

### ISSUE THREAD

**Issue by PupoSDC** [jaredpalmer/formik#2496]
### Current Behavior

When using Yup, [they recommend that the validation schema returns objects in case you want to post process them with translation libraries](https://github.com/jquense/yup#using-a-custom-locale-dictionary). This means that according to yup API, returning "any" as an `error` response is A-ok. 

Unfortunately Formik does not handle this well since the `error` value is used directly as a child in the `ErrorMessage` component. This behaviour propagates to other libraries as well such as `formik-antd`.

### Desired Behavior

I want to be able to process the error message between the validation step and being consumed by formik fields.

### Suggested Solution

Provide an API to alter error messages to formik. Example:

```js

// a yup configuration that returns objects as errors
Yup.setLocale({
  string: {
    email: 'email',
    min: ({min}) => ({key: 'minLength', options: {count: min}}),
    max: ({max}) => ({key: 'maxLength', options: {count: max}}),
  },
});

// Formik usage with the new API
<Formik 
   initialValues={new UserCredentials()} 
   onSubmit={onSubmit} 
   validationSchema={yupSchema} 
  processError={(error) => t(error)}
>
``` 

Signature of processError would be

```js
processError: (error: any) => string
```

Now consumers of the `getIn` API could use the error as a string with no problem

### Who does this impact? Who is this for?

Formik users who are using Yup. Specially Formik users who are using third party integrations (i.e.: `antd-formik`) and can't easily intercept these values themselves

### Describe alternatives you've considered

There are a lot of ways to get around this, but none of them are very elegant  pr come with severe limitations

- If you are working with vanilla formik, you can write your own `ErrorMEssage` component. For this user case this improvement is very minimal but since we all <3 Yup here, we should try to embrace it's API as much as possible
- You can add your translations to each yup parameter but this becomes very repetitive and decentralized when you have multiple schemas in your project
- You can `Yup.setLocale` with the translations already in place. But the Yup team does not recommend this since you will loose the ability to change the languages dynamically. 

### Additional comment

I'm interested in coding this into reality if you are open to the idea.

**Comment by PupoSDC** [comment]
I was able to work around this more or less "elegently". My final solution does not relate to formik at all so I will be closing the issue and leaving this comment here just in case someone googles the same problem I had. 

For starters, change your yup i18n initialization to use functions, instead of computing the values once. Like this:

```js
Yup.setLocale({
  mixed: {
    required: () => i18n.t('errors:required'),
  },
  string: {
    email: () => i18n.t('errors:email'),
    min: ({min}) => i18n.t('errors:minLength', {count: min}),
    max: ({max}) => i18n.t('errors:maxLength', {count: max}),
  },
});
``` 

This will make sure that on every validation you will get the most up to date translation.
Then I created the following "component":

```js
const RefreshOnLanguageChange = (): null => {
  // plug in whatever mechanism you have to keep track of language,
  // For me its a hook that is reading user preferences from local storage
  // don't use i18n.language directly since that value is not hooked
  const [{language}] = useCurrentUser(); the current 
  const {validateForm} = useFormikContext<unknown>();
  useEffect(() => {
    validateForm();
  }, [preferredLanguage, validateForm]);
  return null;
};
```

I can now add this snippet to my Formik forms and every time a language change occurs the form will revalidate.

**Comment by damianon** [comment]
I find this solution to be not so elegant, as calling the t() function inside the target component has more benefits.
Also <ErrorMessage> the same issue with its children prop.
I think error should be any as proposed by OP
