### ISSUE TITLE
Field with multiple children

### ISSUE THREAD

**Issue by purge** [jaredpalmer/formik#250]
According to the documentation `<Field />` can take multiple children (such as for a select)
(https://github.com/jaredpalmer/formik#field-)
However, the Field component validates for receiving only a single child (https://github.com/jaredpalmer/formik/blob/master/src/Field.tsx#L149). 
Is this a bug or documentation error?

Many thanks for your work on this library.

**Comment by prichodko** [comment]
Hey @purge,

It doesn't seem to me that Formik states that it handles multiple children. Since example you are pointing to still uses single element `select`,  to which are then `children` passed as a prop. Then the interaction between `options` handles `select` element, which accepts `value` and `onChange` prop passed from Formik.

So the line you should be looking to is -
 https://github.com/jaredpalmer/formik/blob/master/src/Field.tsx#L152

**Comment by wub** [comment]
Yeah this doesn't work for me either (0.10.3). It worked with 0.9.4.

The release for 0.10.1 says "fully backwards compatible, no breaking changes", so maybe I'm doing something that wasn't technically correct in 0.9.4, but worked anyway.

```js
<Field
	required
	id="about"
	name="about"
	component="select"
	className="bg-white"
	disabled={props.isSubmitting}
>
	<option value="-1" disabled>Please select...</option>
	<option value="0">An audition or job opportunity</option>
	<option  value="1">Networking</option>
	<option value="3">Other</option>
</Field>
```
`Error: React.Children.only expected to receive a single React element child.`

**Comment by wub** [comment]
@jaredpalmer not sure why this was closed, sorry - should I make a separate issue? It's still not working.

**Comment by wub** [comment]
@jaredpalmer Ignore my (now deleted) comment, apparently I'm blind

**Comment by sebmor** [comment]
Im doing the following 
```
<Field component='select' name='accGender'>
  <option value='male'>Male</option>
  <option value='female'>Female</option>
</Field>
```
And still get the following error
```
Invariant Violation: React.Children.only expected to receive a single React element child.
```

Using formik 0.10.3. Is this actually solved?
