### ISSUE TITLE
Formik Validation Schema Empty String To Null

### ISSUE THREAD

**Issue by Kyle-Kerlew** [jaredpalmer/formik#2501]
## ❓Question

I've been struggling getting this implementation to work as I expect.
`accountingId: Yup.string().nullable(true).default(null).transform(( function(value, originalValue) { if (!value) { return null; } return originalValue; })),`

I am using this with Formik's Validation Schema with the expectation that it will transform on submit -- despite the validation running, it does not transform the empty string to null. 

expected response: null

actual response: ""

**Comment by VadimCeretean** [comment]
do you fix it?
