### ISSUE TITLE
Async validation status?

### ISSUE THREAD

**Issue by ekozhura** [jaredpalmer/formik#252]
I'm wondering if there is a way to mark a field as being validated (so i can add a loading icon nearby). I'm using remote endpoints to validate an email or phone number and it can take a while.

**Comment by prichodko** [comment]
Hey @ekozhura,

you may find this https://github.com/jaredpalmer/formik/#status-any helpful for this kind of situation.

**Comment by ekozhura** [comment]
@prichodko Thank you for the tip. Yes, using `status` was my only option. Unfortunately, that means, i can't use `validationSchema` anymore.

**Comment by prichodko** [comment]
Do you validate your fields immediately or on submit?

**Comment by ekozhura** [comment]
Validation is set on user's inputs (`validateOnChange`) and, of course, on submit.

**Comment by ekozhura** [comment]
i think, if there are no options except using `status` on submit, i can close an issue

**Comment by shamseerahammedm** [comment]
@ekozhura how did you solve this ? can you show an exmple or give a tip ?
