### ISSUE TITLE
Additional spaces in the Formik body break the component

### ISSUE THREAD

**Issue by keyoffecka** [jaredpalmer/formik#2526]
### Current Behavior

If I add an additional space inside the Formik tag body before a callback the component breaks.

### Expected behavior

I do not see any obvious reason why formatting (adding additional spaces) could break the component, so I expect using additional spaces before a callback function inside the Formik tag should also work.

### Reproducible example

This works just fine

```
<Formik initialValues={ {} } onSubmit={ () => null }>{ }</Formik>
```

This also works. Note the addional space after the opening div tag.

```
<div> { }</div>
```

This doesn't work

```
<Formik initialValues={ {} } onSubmit={ () => null }> { }</Formik>
```

Note the addional space.

In the browser console I get

```
react-dom.development.js:19527 The above error occurred in the <Formik> component:
    in Formik
    in Unknown
    in Route
    in Switch
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:19527
logError @ react-dom.development.js:19564
update.callback @ react-dom.development.js:20708
callCallback @ react-dom.development.js:12490
commitUpdateQueue @ react-dom.development.js:12511
commitLifeCycles @ react-dom.development.js:19883
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
scheduleUpdateOnFiber @ react-dom.development.js:21188
updateContainer @ react-dom.development.js:24373
(anonymous) @ react-dom.development.js:24758
unbatchedUpdates @ react-dom.development.js:21903
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24757
render @ react-dom.development.js:24840
main @ Application.tsx:14
(anonymous) @ index.ts:26
load (async)
./src/index.ts @ index.ts:25
__webpack_require__ @ bootstrap:788
fn @ bootstrap:99
0 @ Main.tsx:39
__webpack_require__ @ bootstrap:788
(anonymous) @ bootstrap:855
(anonymous) @ bootstrap:856
react.development.js:1251 Uncaught Error: React.Children.only expected to receive a single React element child.
    at Object.onlyChild [as only] (react.development.js:1251)
    at Formik (formik.esm.js:1104)
    at renderWithHooks (react-dom.development.js:14803)
    at mountIndeterminateComponent (react-dom.development.js:17482)
    at beginWork (react-dom.development.js:18596)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22154)
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | "formik": "^2.1.4",
| React            | "react": "^16.13.1",
| TypeScript       | "typescript": "^3.8.3",
| Browser          | Chrome Version 81.0.4044.138 (Official Build) unknown (64-bit)
| npm/Yarn         | 6.14.5
| Operating System | Linux eshke 4.13.12 #4 SMP PREEMPT Sun Mar 4 00:25:25 CLST 2018 x86_64 GNU/Linux

**Comment by johnrom** [comment]
This is because in React, you're technically adding a space there. It's the equivalent of doing: 

```jsx
<Formik initialValues={ {} } onSubmit={ () => null }>
  {' '}
  {}
</Formik>
```

Formik only accepts one child, a React node (for example, a space, or a `null` node like `{}`), or a function, as described here: https://jaredpalmer.com/formik/docs/api/formik#props

**Comment by keyoffecka** [comment]
My concern is that it's not obvious, it's not intuitive. I am pretty sure, there are explanations why it was implemented like that, but in my opinion it's a bad user experience. Even though it's translated as two child components, I think it would be more user friendly not to translate spaces or any other similar characters into components. Again, the experience is that spaces in HTML (unless it's not an unbreakable space) have no semantics and are just separators. Thus can be used for pretty formatting of the code as needed.
Apart from that it's not intuitive, it also looks very strange to me that a library forces users to follow some formatting rules, otherwise the library just breaks. In some languages spaces may have semantics, but this is JSX after all.

> I'd recommend putting the braces on the next line, which will not translate to a space.

I know the walkaround, I shared it in the report. I am concerned that I am forced to format the code not as I wish. Not only do you need to know the API, but you also need to know how to format the code. That is called abusive syntax.

**Comment by johnrom** [comment]
This has nothing to do with Formik and is just how React works. There isn't anything we can do on our end to support the formatting you desire.

> the experience is that spaces in HTML (unless it's not an unbreakable space) have no semantics and are just separators. Thus can be used for pretty formatting of the code as needed.

This is incorrect, a space in HTML is a real space when it is next to an inline element. That is why it exists like this in React -- React will never be able to tell whether your element is `display: inline` or not. For example, in HTML `<div><span>hello</span> <span>world</span></div>` will have a space in both HTML and React.

**Comment by keyoffecka** [comment]
Ok. My fault. Thank you for your the explanation about React and HTML in general.
