### ISSUE TITLE
How to take values from Formik inside a hook?

### ISSUE THREAD

**Issue by PritishSawant** [jaredpalmer/formik#2527]
I am using Formik in my app. I need to take values from Formik and use it inside my hook.
Currently I am doing it using useRef hook
Following is my custom hook code which requires Formik values

```
const { doRequest, errors } = useRequest({
    url: "my_url",
    method: "post",
    body: {
      mobileNumber: formikRef.current
        ? formikRef.current.values.mobileNumber
        : "",
      password: formikRef.current ? formikRef.current.values.password : "",
    },
    onSuccess: (response) => {
      console.log("Hi" + response.msg);
      Router.push("/");
    },
    onFailure: (response) => {
      console.log("Hi2" + response.msg);
    },
  });
```

In the body, the mobile number and password is always empty even though I enter values in my textfield. I am calling the doRequest method inside onSubmit of Formik

I am asking the ref using following

```
<Formik
            innerRef={formikRef}..
```

If I had used useState for all my fields It would have been extremely easy to pass those values to my custom hook but due to large form and validation , I am using Formik

**Comment by johnrom** [comment]
I don't know what `useRequest` is, but any request API that you are using should accept parameters at the moment it is called. So you would want something with an api like:

```jsx
const MyForm = () => {
  const { doRequest, errors } = useRequest(params => ({
    url: "my_url",
    method: "post",
    body: {
      mobileNumber: params.mobileNumber ?? "",
      password: params.password ?? "",
    },
    onSuccess: (response) => {
      console.log("Hi" + response.msg);
      Router.push("/");
    },
    onFailure: (response) => {
      console.log("Hi2" + response.msg);
    },
  }));

  return <Formik 
    onSubmit={({ values }) => { 
      doRequest({ 
        mobileNumber: values.mobileNumber, 
        password: values.password,
      }); 
    />;
};

**Comment by PritishSawant** [comment]
ok thanks

**Comment by PritishSawant** [comment]
I can't use the way you said @johnrom 
Here is my hook

import axios from "axios";
import { useState } from "react";

export default ({ url, method, body, onSuccess, onFailure }) => {
  const [errors, setErrors] = useState(null);
  const doRequest = async () => {
    try {
      setErrors(null);
      const response = await axios[method](url, body);
      if (response.data.status === 1) {
        onSuccess(response.data);
      } else {
        onFailure(response.data);
      }

      return response.data;
    } catch (err) {
      console.log(err.response);
      setErrors(<div>{err.response.data.error.message}</div>);
    }
  };

  return { doRequest, errors };
};

**Comment by johnrom** [comment]
@PritishSawant if you have control over that function, you can move the body parameter from the export to doRequest, or if you need backwards compatibility you can modify it to combine both options, like this:

```jsx
export default ({ url, method, body = {}, onSuccess, onFailure }) => {
  const [errors, setErrors] = useState(null);
  const doRequest = async (deferredBody = {}) => {
    try {
      setErrors(null);
      // if you want to be able to pass static _and_ deferred options
      const response = await axios[method](url, {
        ...body,
        ...deferredBody,
      });
      // OR if you want to be able to pass static _or_ deferred options
      const response = await axios[method](url, deferredBody ?? body);
      if (response.data.status === 1) {
        onSuccess(response.data);
      } else {
        onFailure(response.data);
      }

      return response.data;
    } catch (err) {
      console.log(err.response);
      setErrors(<div>{err.response.data.error.message}</div>);
    }
  };

  return { doRequest, errors };
};
```

I'd really recommend against using a pattern where the request body needs to be defined based on the render, because syncing state can be very error-prone.

**Comment by PritishSawant** [comment]
@johnrom  Thanks a lot
