### ISSUE TITLE
Add innerRef to Field

### ISSUE THREAD

**Issue by alexboots** [jaredpalmer/formik#253]
It works fine on a plain `<input />` inside a `<Form />` but if you try and use `<Field  />` there is no focus() method available. 

Following along with. 
https://reactjs.org/docs/refs-and-the-dom.html

```
componentDidMount = () => {
  this.usernameInput.focus()
}

// yada yada 

<Field
  ref={ (input) => { this.usernameInput = input }}
  name="username"
  type="input"
  placeholder="username"
/>
```
`Warning: Stateless function components cannot be given refs.`
`Uncaught TypeError: _this.usernameInput.focus is not a function`

I can take a stab at a PR if i'm not missing something.

**Comment by babsonmatt** [comment]
Looking to do the same thing here, should this be expected to work?

**Comment by alexboots** [comment]
@babsonmatt I think something needs to be added to `componentDidUpdate` if a ref prop is passed on `<Field />` (just glancing at the [code](https://github.com/jaredpalmer/formik/blob/master/src/Field.tsx)) but it works on plain html `<input />` wrapped in `<Form>` so I haven't dived into it too much yet

as in:
```
class SomeComponent extends React.Component {

  componentDidMount = () => {
    this.firstNameInput.focus();
  }

// yada yada 

  render() {
    const initialValues = { firstName: '' }

    return (
      <Formik
          initialValues={ initialValues }
          onSubmit={ this.handleSubmit }
          render={ formikProps => {
            const { 
              values, 
              handleChange, 
              handleBlur 
            } = formikProps;

            return(
              <Form>
                <input
                  ref={ (input) => { this.firstNameInput = input } }
                  type="text"
                  name="firstName"
                  value={ values.firstName }
                  onChange={ handleChange }
                  onBlur={ handleBlur }
                />
              </Form>
            )
          }
        }
      />
    )
  }
}

export default SomeComponent;
```

**Comment by jaredpalmer** [comment]
@alexboots I think we would call probably want to call it `inputRef` / `innerRef` so that it is not mistaken and then pass it in as a part of `props.field`

**Comment by alexboots** [comment]
@jaredpalmer something like this? https://github.com/alexboots/formik/commit/4048b43394d4c215d1219be730cfa6eaf6a15eeb#diff-bc78961df770c0df68f6cd758a6f2afd

(not familiar with Typescript so unsure if `innerref` in `interface FieldConfig` is correctly defined )
