### ISSUE TITLE
isValid only updates during onBlur for initial change

### ISSUE THREAD

**Issue by pswami** [jaredpalmer/formik#257]
The `isValid` prop doesn't update until blur for the initial change. The `errors` prop does seem to update though. Is this intended?

**Comment by Jacky-Lei** [comment]
It'd be nice if we can choose to only update `isValid` with onChange

**Comment by jaredpalmer** [comment]
This has to do with the meaning of `dirty`, which is the real issue here. Let's discuss this in #280
