### ISSUE TITLE
handleChange bug for empty number values: parseFloat('') is null

### ISSUE THREAD

**Issue by cloud-walker** [jaredpalmer/formik#258]
Input type number will be cast to `null` when cleared, because of this:

https://github.com/jaredpalmer/formik/blob/61a0869c121840fe7b69d9aba7442bdea409e425/src/formik.tsx#L389

Demo with the latest version of formik: https://codesandbox.io/s/m7268r7xoy

**Comment by jaredpalmer** [comment]
True true.

**Comment by jaredpalmer** [comment]
Should this be `parseFloat(val) !== null ? parseFloat(val) : ''`?

**Comment by DrewBe121212** [comment]
Related issue: 284. 

Also, for checking the value, what about this?

    Number.isNaN(Number.parseFloat(val)) ? '' : Number.parseFloat(val);

**Comment by jaredpalmer** [comment]
Submit a PR and with this change and a test if you get a chance

**Comment by victordidenko** [comment]
Didn't make test though...
