### ISSUE TITLE
Redux Formik Axios example

### ISSUE THREAD

**Issue by flying-falcon** [jaredpalmer/formik#2601]
## 📖 Documentation

Can someone add documentation for Redux + Formik + Axios integration.

**Comment by johnrom** [comment]
You'll have to be a bit more specific here. Redux and Axios are both outside of the scope of Formik's documentation. The documentation for submitting is here: https://formik.org/docs/api/formik#onsubmit-values-values-formikbag-formikbag--void--promiseany

you can use onSubmit to call redux or axios according to their documentation.
