### ISSUE TITLE
In demos, from the 3d demo, an error: process.nextTick is not a function

### ISSUE THREAD

**Issue by Aparus** [jaredpalmer/formik#262]
Hi. I tried to check all the demos in section Demos on main page of repo. And after 2d demo (from 3d) all causes the error: TypeError: process.nextTick is not a function

![screenshot_14](https://user-images.githubusercontent.com/1222611/33070146-17a53d08-cec8-11e7-92f7-109e791f0f62.png)

Two first demos are working fine.

**Comment by Magellol** [comment]
A possible issue with codesandbox, it loads properly now https://codesandbox.io/s/qJR4ykJk

Also process.nextTick is only available on node js so this issue is probably not related to Formik at all.

**Comment by jaredpalmer** [comment]
I updated deps. I think this was codesandbox
