### ISSUE TITLE
set submit flag to true for all Formik sub forms without the submit button

### ISSUE THREAD

**Issue by pradok** [jaredpalmer/formik#263]
Hi
I have a series of Formik sub forms as their own standalone component files and and external component for submit displayed as a footer to all those forms that just listens for a true flag in order to enable the submit.

Is there is a way to flag submit button to true without pressing it and firing onSubmit handler for all those Formik sub forms?

btw, like the new render props method over HOC, give a  lot of flexibilty.

Cheers

**Comment by jaredpalmer** [comment]
Not sure this is possible in React with out registering the child with parents.
