### ISSUE TITLE
preventDefault on handleSubmit using RN

### ISSUE THREAD

**Issue by outaTiME** [jaredpalmer/formik#264]
Hi guys, 

https://github.com/jaredpalmer/formik/blob/master/src/formik.tsx#L464
`e.preventDefault()` not required when running in RN why you handle that? sometimes the handleSubmit might be call in async function like:

```js
_onPressConfirm(e) {
  e.persist();
  this.setState({
    actionReject: false
  }, () => {
    this._form.handleSubmit(e);
  })
}
```

Any feedback will be appreciated, thanks !!

**Comment by jaredpalmer** [comment]
I would call `submitForm()` instead of `handleSumit` in RN

**Comment by outaTiME** [comment]
Awesome, thanks @jaredpalmer !!!

**Comment by renganatha10** [comment]
@jaredpalmer I get the same error in v0.11.11 is it valid?  In React Native section of Readme file it mentioned to use handleSubmit from props for onSubmit functionality ?
