### ISSUE TITLE
Type values of FormikErrors as any

### ISSUE THREAD

**Issue by wollnyst** [jaredpalmer/formik#266]
Hi, before starting to complain about small little details: kudos to the author: formik is the react form lib, I was searching for quite a lot of time.

Now the complain part: `FormikErrors` is typed as 

```
export declare type FormikErrors = {
    [field: string]: string;
};
```

I'm usually using `react-intl` for texts and therefore like to pass around `React.ReactNode` instead of string. It's working, since the error is usually rendered with something like `{touched.email && errors.email && <div>{errors.email}</div>}` (taken from the gist).

I don't see a reason why the type system make this restriction here.

**Comment by jaredpalmer** [comment]
This is a solid point. Feel free to change in a PR
