### ISSUE TITLE
Cascading drop down

### ISSUE THREAD

**Issue by okezieokpara** [jaredpalmer/formik#267]
I am new to Formik, and I think it is a great library. However, I am trying to implement a cascading dropdown scenario, where selecting a value from a select box with trigger some action (i.e load some data for the next select) using the selected data, but this seems impossible because, the `onChange` handler of the select is already set to the default Formik's handleChange handler.
for example 
` <select className="form-control" name={this.props.id} id={this.props.id} onChange={this.handleSelectChange} onBlur={this.handleBlur} value={this.props.value} {...this.props}>
          {
            this.props.options.map((opt, idx) =>
              (<option key={idx} value={opt.value} selected={opt.selected}>{opt.label}</option>)
            )
          }
        </select>`

**Comment by jaredpalmer** [comment]
Use setFieldValue and a prop to determine behavior instead

**Comment by okezieokpara** [comment]
of course, like this

` onChange={setFieldValue} `
but how do I get the updated values after each change?

**Comment by jaredpalmer** [comment]
Read them from `values`?

**Comment by okezieokpara** [comment]
Yes, but how?
