### ISSUE TITLE
How to capture success of submit?

### ISSUE THREAD

**Issue by bernatfortet** [jaredpalmer/formik#269]
I'm trying to understand what is a best practice to tell the InnerForm that the submitting of the form has been successful. 
This is useful to show feedback like in slack:
![image](https://user-images.githubusercontent.com/390010/33226036-284d0fcc-d149-11e7-9b5a-1f11de21347a.png)

Currently I've figured out this way:
```js
function handleSubmit( values, { setSubmitting, setErrors, setStatus } ){
  setStatus({ success: false })

  props.saveUserEmail( values.email )
    .then( () => {
      setSubmitting(false)
      setStatus({ success: true })
    })
}
```

but I was thinking that success means that isSubmitting has changed from true to false and there's no errors.

Do you guys have any idea of a clean, simple way to capture success?

Thanks

**Comment by jaredpalmer** [comment]
Status and setStatus is there exactly for this purpose 😎
