### ISSUE TITLE
How to prevent showing all errors?

### ISSUE THREAD

**Issue by taneba** [jaredpalmer/formik#270]
Please see my codesandbox: https://codesandbox.io/s/wyrppxo91l

First of all, thanks for this great library. I really enjoy using this.
I want to show error message only on the input that currently being input. But as you see my codesandbox, when I change one of inputs, all errors will be shown.

How can I fix this??

**Comment by prichodko** [comment]
Check if input is `touched` - https://github.com/jaredpalmer/formik#touched--field-string-boolean-

**Comment by taneba** [comment]
Thnaks! @prichodko
