### ISSUE TITLE
field-level value parsing/onChange

### ISSUE THREAD

**Issue by timoxley** [jaredpalmer/formik#272]
I'd like to be able to transform values as they are changed, e.g. coerce text field into a number. Seems the only option to do this with formik is to do all the value formatting in the form's onSubmit. Would be good if there were a way to inject a mapping function that's called each time an input value changes.

**Comment by prichodko** [comment]
You can pass your own `onChange` handler, do what you need and programmatically call `setFieldValue` provided from Formik.

**Comment by timoxley** [comment]
@prichodko this is a reasonable workaround.
