### ISSUE TITLE
Can't get submitted values

### ISSUE THREAD

**Issue by KhamatdinovRT** [jaredpalmer/formik#275]
I'm stucked. Following tree types of input seems to be same when they rendered to DOM. But I only get a changed value from this one `<Field type="text" id="password" />` in onSubmit function. Should i use it like so `<form onSubmit={props.onSubmit/>` and then get values from event.target. I kinda don't want to do it this way.
```javascript
         <Formik
            onSubmit={values => console.log(values)}
            initialValues={{ email: '', password: '' }}
          >
            {props => (
              <Form className="login-form">
                <Field type="text" id="password" />
                <input type="text" id="password" />
                <FormItem>
                  <Input
                    prefix={<Icon type="lock" />}
                    className="form-input"
                    type="password"
                  />
                </FormItem>
            </Form>
      </Formik>

**Comment by prichodko** [comment]
You are not passing `handleChange` to `input` elements. Field is special and takes it from the context itself. I also recommend using `name` rather than `id`, speaking of this `Input` component doesn't have it specified.
