### ISSUE TITLE
Formik form submission with enzyme

### ISSUE THREAD

**Issue by sepehr500** [jaredpalmer/formik#278]
I am trying to write a test where I fill out a formik form, then press the submit button and see if my yup schema is properly connected to my input fields. I am using this example https://github.com/jaredpalmer/formik/blob/f5d76609b222ce583663add279ac76e807e2d0ba/README.md#simulating-form-submission
but it uses the formik HOC. Is there a way to test formik using the formik component with a render prop? If so, can somebody please provide a small example? I don't know if there is a way to find the component that was passed into the render prop in enzyme?

**Comment by jaredpalmer** [comment]
If you just need to check props, you don't even need enzyme necessarily: https://github.com/jaredpalmer/formik/blob/master/test/Field.test.tsx#L66 .

If you need to simulate stuff, the formik.test.tsx tests pretty much covers all things you'd like to test: https://github.com/jaredpalmer/formik/blob/master/test/formik.test.tsx#L248

**Comment by sepehr500** [comment]
Thanks. I noticed you had documentation for this and then removed it. What was the reason for this?

**Comment by jaredpalmer** [comment]
It was wrong / produced false positives

**Comment by sepehr500** [comment]
Thanks!
