### ISSUE TITLE
Form validation using formik

### ISSUE THREAD

**Issue by ajinathidhate** [jaredpalmer/formik#282]
I am working on component..but i got issue while i am exporting the Formik and validation using Yup library.here is my code..How we export two components into one page.

import { Field, Form, Formik } from "formik";
import * as React from "react";
import * as ReactDOM from "react-dom";
import { connect } from "react-redux";
import { Link, RouteComponentProps } from "react-router-dom";
import Input from "react-validation/build/input";
import { error } from "util";
import Yup from "yup";
class KzForm extends React.Component<RouteComponentProps<{}>, {}> {
    constructor(props: any) {
        super(props);
        this.state = {
            email: "",
            password: "",
        };
    }
    public handleSubmit(e) {
        e.preventDefault();
        // tslint:disable-next-line:no-console
        console.log(this.state.email);
        // tslint:disable-next-line:no-console
        console.log(this.state.password);
    }
    public handleChange(e) {
        // tslint:disable-next-line:no-console
        console.log(e.target.value);
        // tslint:disable-next-line:no-console
        console.log(e.target.name);
        const returnObj = {};
        returnObj[e.target.name] = e.target.value;
        this.setState(returnObj);
    }
    public handleBlur(e) {
        const a = e.target.name;
        // alert(a);
    }
    public render() {
        return (
            <Formik
                validationSchema={Yup.object().shape({
                    email: Yup.string().email("Invalid email address").required("Email is required!"),
                })}
                initialValues={{
                    email: " ",
                    password: " ",
                }}
                onSubmit={(values, actions) => {
                    setTimeout(() => {
                        alert(JSON.stringify(values, null, 2));
                        actions.setSubmitting(false);
                    }, 1000);
                }}
                render={({ values, touched, errors, dirty, isSubmitting }) => (
                    <form className="p-5" onSubmit={this.handleSubmit}>
                        <div className="form-group">
                            <label>Email</label>
                            <input name="email" type="text"

                                className={`form-control ${Error.email && Touch.email && "is-invalid"}`}
                                onChange={this.handleChange}
                                onBlur={this.handleBlur} />
                            {Error.email && Touch.email &&
                                <div className="invalid-feedback">
                                    {Error.email}
                                </div>}
                        </div>
                        <div className="form-group">
                            <label>Password</label>
                            <input name="password" type="password"
                                className={`form-control ${Error.password && Touch.password && "is-invalid"}`}
                                onChange={this.handleChange}
                                onBlur={this.handleBlur} />
                            {Error.password && Touch.password &&
                                <div className="invalid-feedback">
                                    {Error.password}
                                </div>}
                        </div>
                        <button type="submit" className="btn btn-outline-primary"
                            {isSubmitting ? 'Loading' : 'Submit'}>
                            Submit
                          </button>
                    </form>
                )}
            />
        );
    }
    // tslint:disable-next-line:align
} export default KzForm;

**Comment by m1lk1way** [comment]
narkoman?
