### ISSUE TITLE
Empty input type=number results in NaN

### ISSUE THREAD

**Issue by vuhrmeister** [jaredpalmer/formik#284]
I'm using Formik with Yup Schema validation.

I have an input field of type "number". If I enter a value and empty the field this results in a `NaN`. This behavior might be as expected. For that I added a transform function to my schema like that:

```
yup
.number()
.transform(value => {
  console.log(value, Number.isNaN(value) ? 0 : value 
  return Number.isNaN(value) ? 0 : value
})
```

Should it respect the transform function? Or is the schema actually only be used for validation, not for "cleaning" the data? If so, is there a way how to solve that? Maybe I'm missing something.
Of course, I can check the value before attaching it to the input field. But the value in the global values object stays the same.

**Comment by sepehr500** [comment]
From what I understand, yup can only used for validation. Any kind of cleaning you try to do in yup will not effect the `values` object that `formik` manages internally.

**Comment by markuspelnens** [comment]
Hi @vuhrmeister, did you manage to solve it? I'm running into the same problem

**Comment by vuhrmeister** [comment]
@markuspelnens nope, used the same workaround (but checking for `Number.isNaN()`).

**Comment by timc13** [comment]
is there any reason for this?  It seems like we should be able to use replace the form values with the values returned by Yup `validate()`.  If we're allowing integration with Yup, why not integrate all the way?  Yup transforming is very powerful and it would be great if it "just worked"

**Comment by EmirGluhbegovic** [comment]
I am having the same issue, has this been fixed or is there some recommended way of dealing with this?

**Comment by noahjohn9259** [comment]
try to use setFieldValue
```javascript
onChange={e => setFieldValue('condition.operand', +e.target.value)}
```
