### ISSUE TITLE
"Soft Stop" Formik validation

### ISSUE THREAD

**Issue by sepehr500** [jaredpalmer/formik#285]
I have the need for a "Soft Stop" in my form. That means when the person tries to submit the form the first time, they get an error on fields that we recommend they fill out, but are not necessary. They second time they press submit regardless of if they have filled out the fields or not, they are allowed to continue. Is there a way to use  `yup` and `formik` to do this? Or do we need to manage the state outside of the frameworks?

**Comment by KhamatdinovRT** [comment]
You can add some react state like counter and perform checking if submit pressed second time in`handleSubmit`

**Comment by sepehr500** [comment]
This use case happens often, so I wanted to add a `softRequired` type to yup to make this reusable. Do you know if yup types can hold state?

**Comment by jaredpalmer** [comment]
I have a form like this too in one of our apps. I just used `status`. It was kind of gross. Would love to see what you come up with.

**Comment by sepehr500** [comment]
Do you think it should be a feature of formik? Or should the solution exist outside of Formik?

**Comment by sepehr500** [comment]
The way I ended up solving this problem was wrapping Formik to intercept the component to be rendered before it gets passed in as props to `Formik`, then we could make `onSubmit` do whatever we want. We might get a lot of benefit if we made a `beforeValidate` hook or something that would run before validation and determine weather validation needs to be run or not.

**Comment by juanpicado** [comment]
@sepehr500 could you share an example of your approach? would be really useful to see.
