### ISSUE TITLE
Dirty values in onSubmit

### ISSUE THREAD

**Issue by miguelocarvajal** [jaredpalmer/formik#286]
Hello all!

I am looking into using Formik for my next project and was looking to see if there was any way to have the onSubmit function receive only the values that changed (the dirty values).

Am looking to have a form that will submit only the fields that the user changed (instead of submitting the whole form).

I've looked for a way to do this in the docs and have not found anything.

Any ideas on how it can be done?

Thanks!

**Comment by prichodko** [comment]
You can probably combine `values` and `touched` fields.

**Comment by miguelocarvajal** [comment]
Thought about that and gave it a shot but as per the docs, touched is not available in onSubmit.

**Comment by ericchernuka** [comment]
Could you not just diff the `initialValues` against the `values` from onSubmit?

**Comment by miguelocarvajal** [comment]
@ericchernuka Sometimes the answer is right in front of you. You're right, that's all I had to do.

Thanks!
