### ISSUE TITLE
Initial validation or initialErrors prop

### ISSUE THREAD

**Issue by morgs32** [jaredpalmer/formik#288]
What if the user has set some field values, and we do store them somewhere, and when the user returns to the app those values are invalid. Is there no way to run `validate` on initialization?

**Comment by morgs32** [comment]
@jaredpalmer whaddya think?

**Comment by jaredpalmer** [comment]
The tricky thing is with keeping formik compatible with SSR. You can set the initial validity using [`isInitialValid`](https://github.com/jaredpalmer/formik#isinitialvalid-boolean--props-props--boolean)

**Comment by morgs32** [comment]
Can you explain that a little? If the form is invalid and you can SSR that, wouldn't you also want to SSR with the error validation on whichever fields have issues?

**Comment by jaredpalmer** [comment]
Formik can't run validations (esp. async ones) before mount because calling setState in componentWillMount is really bad and also inconsistent

**Comment by morgs32** [comment]
What about the `errors` equivalent of isInitialValid? Like `initialErrors`?

I guess I'm trying to ask you if you agree there is a use case. Because if there is, I'm sure there's a way to do it.

**Comment by anandaroop** [comment]
+1 for this use case. 

I would like to display validation errors & disable form submission for a record that is already persisted, and will now be _newly_ invalid based on some recent changes in the underlying business logic.

So I would like the initial form load to reflect this, but ran into the same issue where the validator function is not run until some field is touched. This has the effect of leaving the form's submit button initially _enabled_ for what we consider to be an invalid record.

For now I am working around this by moving logic out of the validator function and into various form components, which seems a shame given all the wins we've enjoyed by relying on Formik's awesome default behavior so far.

**Comment by Martaver** [comment]
I've also encountered a use-case for this, where a form is persisted, even in an invalid state, since it is shared between multiple users and takes time to complete.

I would like the form to be validated immediately on initialization, so that its `isValid` and `errors` are correctly populated at all times.

I really don't see why the form's 'validation state' shouldn't reflect its values at all times. 

If it's not appropriate to show validation errors for whatever reason, then I think of this a display problem, not a validation problem.

**Comment by peterkovacsvcc** [comment]
When you do only onBlur validation, having initialErrors would help also. 

I ran into this problem when you have an initially invalid form and you only validate onBlur, after the form becomes dirty (eg. typing in a field) the isValid key changes to true because it only checks the form's errors which is empty at that point. Even though the initial form was invalid and it doesn't run any validation yet.

**Comment by irrigator** [comment]
@anandaroop The workaround that I am using is to call `this.refs.formikForm.getFormikBag().validateForm()` in the parent's `componentDidMount` method.

**Comment by yanchith** [comment]
Hey all,

not sure of the state of this, but we also do have a usecase for `initialErrors` field. Our app uses `redux-saga` (ugh), meaning the async logic is detached from the form submission. We therefore have no way to call `setErrors`. Instead, `redux` will redraw our component and provides validation errors as props if any. There is no straightforward way to pass these errors on to the form at the moment. Just to be clear, I can imagine a lot of hacky ways to do it, but I'd rather not.

AFAIK the current `validateOnLoad` PR would not help us as the validation logic is performed in another layer of our app.

If the maintainers agree, I would be willing to implement the `initialErrors` feature. At first glance, it has nice symmetry with `initialValues` too, so it shouldn't hurt the API too much.

**Comment by jaredpalmer** [comment]
I think `initialErrors` makes a lot of sense. Feel free to submit a PR. It should be almost identical to `initialValues`.

**Comment by ianks** [comment]
Just echoing that this is an important use case for us as well. we SSR forms and would like to populate the formik form with server errors without resorting to custom API at this point

**Comment by iamdanthedev** [comment]
The solution to initial validation on load is quite simple:

in your form component, the one which is wrapped with `withFormik` or `Formik` (I tested with the latter) add:

```
  componentDidMount() {
    const { isValid, validateForm } = this.props;

    if (!isValid) {
      validateForm();
    }
  }
```

**Comment by ianks** [comment]
@iamdanthedev I realize this, but there are some errors that cannot be figured out on the client without API calls (i.e. database constraints, etc)

**Comment by jpserrett** [comment]
#622 Looks like pretty simple change to get this to work. Any update on when this might get merged in? Seems that a lot of people - myself included - could really use this functionality.

**Comment by morgs32** [comment]
K I'm on it

**Comment by morgs32** [comment]
Alright PR is fixed/updated: #622 waiting on the man.

**Comment by jpserrett** [comment]
Thank you! 👍

**Comment by morgs32** [comment]
@ianks So are you not using an API to validate fields on the client after page load (as in after SSR)? You make it sound like you're trying to avoid doing so.

To me, SSR/initialErrors seems like an unnecessary optimization... but only because I haven't done it perhaps. Have you figured out already how you would do it? Would you store errors in redux (which makes me cringe) in order to get them to nested components? Part of the appeal of formik is keeping form states out of redux.

**Comment by jaredpalmer** [comment]
Reviewing now. This is a large change, but understandable.

**Comment by 0xR** [comment]
I tried this and this seems to work fine:
```js
class FormSubmitter extends Component<{ submitForm: () => void}> {
  componentWillMount() {
    this.props.submitForm();
  }
  render() {
    return null;
  }
}
```

and use it like this:
```js
const MyForm = ({
  submitForm,
}: FormikProps<FormValues>) => (
  <Form>
    <FormSubmitter submitForm={submitForm}/>
    ...
```

**Comment by jaredpalmer** [comment]
@0xR to be safe with React master branch move that to componentDidMount

**Comment by jaredpalmer** [comment]
This or an equivalent will be in v2 btw.

**Comment by 0xR** [comment]
Interesting, I tried doing it inside the render loop and I got a suggestion for `componentWillMount`.

**Comment by jpserrett** [comment]
@jaredpalmer Does that mean that #622 won't be merged in prior to a v2 release? Do you have a recommended temp fix in the meantime? There are several options people have posted here but they haven't seemed to work for me so far... (there is a decent chance I'm doing something wrong though as well)

**Comment by ferc** [comment]
@jpserrett if you have the same values in the state as the `initialValues` prop, the `isValid` prop will be the `isInitialValid` prop, because `dirty` is `false` in that case: https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L563

So, it's not enough calling the `validateForm` prop to know if the form initial valid or not, you should call the `validateForm` and check the `errors` object instead of the `isValid` prop

```
async componentDidMount() {
  await this.props.validateForm()

  const isValid = Object.keys(this.props.errors).length === 0

  this.setState({ isValid })
}
```

**Comment by rborosak** [comment]
How would you fire initial validation when using <Formik> component which uses render props pattern?

**Comment by Andreyco** [comment]
@jaredpalmer is there a chance Formik will get this functionality in v1, or should we wait for v2?

Also, looked at the PR provided in this thread, unfortunately what it does is calling `validate` handler, thus not possible to "inject" errors from top. This can be achieved with refs.

If there is change of shipping with v1, I may create PR for this one.

**Comment by nnmrts** [comment]
For anyone coming from Google Search, until this functionality will be built in, use this:

```javascript
class ParentComponent extends Component {
    constructor(props) {
         super(props);
         this.form = React.createRef();
    }

    componentDidMount() {
        // runs "on load" and validates the form immediately with the initialValues
        this.form.current.validateForm();
    }

    render() {
        <Formik
            // other props...
            ref={this.form}
        >
            // children...
        </Formik>
    }
}
```

**Comment by jamesvclements** [comment]
If you're using React > 16.8, you can do the above with [useRef](https://reactjs.org/docs/hooks-reference.html#useref) and [useEffect](https://reactjs.org/docs/hooks-reference.html#useeffect):

```javascript
const form = useRef();
useEffect(() => {
  if (form.current) {
    form.current.getFormikActions().validateForm();
  }
});
return <Formik ref={form} ...
```

**Comment by maltintas86** [comment]
> If you're using React >= 16.8, you can do the above with [useRef](https://reactjs.org/docs/hooks-reference.html#useref) and [useEffect](https://reactjs.org/docs/hooks-reference.html#useeffect):
> 
> ```js
> const form = useRef();
> useEffect(() => {
>   if (form.current) {
>     form.current.getFormikActions().validateForm();
>   }
> });
> return <Formik ref={form} ...
> ```

React >= 16.8 [useEffect ](https://reactjs.org/docs/hooks-reference.html#useeffect)and useRef worked for me ...

**Comment by mjangir** [comment]
> The solution to initial validation on load is quite simple:
> 
> in your form component, the one which is wrapped into `withFormik` or `Formik` (I've tested with the latter) add:
> 
> ```
>   componentDidMount() {
>     const { isValid, validateForm } = this.props;
> 
>     if (!isValid) {
>       validateForm();
>     }
>   }
> ```

What about the update form where the initial values are loaded from redux state using `mapPropsToValues` and `enableReinitialize: true`?? How will you initially validate the form in that case?

**Comment by saschb2b** [comment]
@mjangir with the HOC? It injects the validateForm as Prop

```
  useEffect(() => {
    if (form.current) {
      this.props.validateForm();
    }
  }, [form]);
```

**Comment by sarneeh** [comment]
You can also pass a function to `isInitialValid`:
```js
isInitialValid={formik => {
    const errors = formik.validate(formik.initialValues);
    return isEmptyObject(errors);
}}
```

**Comment by jaredpalmer** [comment]
Added initialErrors v2 #1626

**Comment by kelly-tock** [comment]
calling `validateForm` on mount is not working for me at all. tried `setFieldTouched` as well. 

validate is called when validateForm is called, and it's returning the errors object. do I just need to set the error manually as well?

**Comment by Kailash23** [comment]
```
 <Formik
      initialValues={{text: '', password: '', active: ''}}
      onSubmit={values => {
        console.log(values);
      }}
      validateOnMount={true}
      validationSchema={signInSchema}>
```
Use this for validating initial values

` validateOnMount={true}`

**Comment by Aakash-Shrivastava** [comment]
validateOnMount={true} still doesn't work for me. I have updated to version 2.1.5.

**Use case:**
I have some initial values for the form, but the form is not validated on mount.
So the isValid is false for this case and I have disabled the submit button, but since the errors are not shown for the initial values on the field unless onBlur() is triggered on each field the user doesn't know why the submit button is disabled.

A work around for this (for eg the phone number field is):
useEffect(() => {
    values.phone && setFieldTouched("phone");
  }, []);
But I don't want to do it for all the fields.
Does anyone know how to fix this?

**Comment by andressspinetti** [comment]
> validateOnMount={true} still doesn't work for me. I have updated to version 2.1.5.
> 
> **Use case:**
> I have some initial values for the form, but the form is not validated on mount.
> So the isValid is false for this case and I have disabled the submit button, but since the errors are not shown for the initial values on the field unless onBlur() is triggered on each field the user doesn't know why the submit button is disabled.
> 
> A work around for this (for eg the phone number field is):
> useEffect(() => {
> values.phone && setFieldTouched("phone");
> }, []);
> But I don't want to do it for all the fields.
> Does anyone know how to fix this?

I had the same issue. I downgrade from `2.1.5` to `2.1.4` along with `validateOnMount={true}` and it worked fine without the use of any `useEffect`.

**Comment by irzum-intangible-solutions** [comment]
> If you're using React >= 16.8, you can do the above with [useRef](https://reactjs.org/docs/hooks-reference.html#useref) and [useEffect](https://reactjs.org/docs/hooks-reference.html#useeffect):
> 
> ```js
> const form = useRef();
> useEffect(() => {
>   if (form.current) {
>     form.current.getFormikActions().validateForm();
>   }
> });
> return <Formik ref={form} ...
> ```

Nice solution but by just doing `formikRef.current.validateForm();` will do the work too no need to get the actions.

**Comment by izumshahid** [comment]
you just need to call the `validateForm` function in useEffect

useEffect(() => {
    formikRef.current.validateForm();
  }, []);

**Comment by rajprakash00** [comment]
> you just need to call the `validateForm` function in useEffect
> 
> ```
> useEffect(() => {
>     formikRef.current.validateForm();
>   }, []);
> ```

Didn't work for me(using class based component currently), also formikRef.current  value is coming null.
Can you help me out @izumshahid ?

**Comment by rajprakash00** [comment]
> validateOnMount={true} still doesn't work for me. I have updated to version 2.1.5.
> 
> **Use case:** I have some initial values for the form, but the form is not validated on mount. So the isValid is false for this case and I have disabled the submit button, but since the errors are not shown for the initial values on the field unless onBlur() is triggered on each field the user doesn't know why the submit button is disabled.
> 
> A work around for this (for eg the phone number field is): useEffect(() => { values.phone && setFieldTouched("phone"); }, []); But I don't want to do it for all the fields. Does anyone know how to fix this?

How setFIeldTouched() will work inside useRef(), since this is available only inside Formik component not the parent component.
Btw currently using formik version <b>2.2.9</b>

**Comment by izumshahid** [comment]
> > you just need to call the `validateForm` function in useEffect
> > ```
> > useEffect(() => {
> >     formikRef.current.validateForm();
> >   }, []);
> > ```
> 
> Didn't work for me(using class based component currently), also formikRef.current value is coming null. Can you help me out @izumshahid ?

@rajprakash00 
did you assign a innerRef to formik
[here's](https://reactjs.org/docs/refs-and-the-dom.html#creating-refs) how you can use a refHook in class component.

here's an example fo you input field

` <CInput
  onBlur={handleBlur}
  invalid={!!errors.first_name}
  valid={!errors.first_name}
  placeholder="Jessica"
  type="text"
  id="first_name"
  name="first_name"
  onChange={handleChange}
  value={values.first_name}
/>`

Note: You need to assign values to you initialValues Obj before running the validation 
![image](https://user-images.githubusercontent.com/55345694/161919144-34840754-a75a-4f78-b5ae-fe84c133b7e9.png)

**Comment by rajprakash00** [comment]
Yes I have done the same steps,still getting null value for `this.formikRef.current` inside componentDIdMount().
Btw could you tell me what is the object you are getting from `formikRef.current`?

**Comment by izumshahid** [comment]
@rajprakash00 i get the complete object of formik 

`{
    "values": {
        "id": 1,
        "email": "irzumshahid@gmail.com",
        "first_name": "irzum",
        "last_name": "acntMngr"
    },
    "errors": {},
    "touched": {},
    "isSubmitting": false,
    "isValidating": false,
    "submitCount": 0,
    "initialValues": {
        "id": 1,
        "email": "irzumshahid@gmail.com",
        "first_name": "irzum",
        "last_name": "acntMngr"
    },
    "initialErrors": {},
    "initialTouched": {},
    "isValid": true,
    "dirty": false,
    "validateOnBlur": true,
    "validateOnChange": true,
    "validateOnMount": false
}`

**Comment by MosheHM** [comment]
you need to use the prop of initialTouched like this

<img width="1109" height="404" alt="Image" src="https://github.com/user-attachments/assets/bfc7d5ea-95f7-4f46-90b7-30fa9506516d" />
