### ISSUE TITLE
Can't access component state from handleSubmit

### ISSUE THREAD

**Issue by brucem1976** [jaredpalmer/formik#294]
Hi there - I have a form that opens in a Modal. When the user clicks Submit, and a DB write succeeds, I need to change the form state to close the Modal. But Formik's handlesubmit happens outside of the class. How do I get access to setState for the form class?

**Comment by brucem1976** [comment]
Figured it out - added my own onClick handler which call's Formik's handleSubmit and then changes state depending on return value﻿

**Comment by stefensuhat** [comment]
hi

can you give an example for this? I need to take my state value on handleSubmit.

Thanks

**Comment by matyushen** [comment]
Hey @brucem1976, would you mind sharing your solution? Thanks!

**Comment by brucem1976** [comment]
I'm afraid it's been a long time and I can't remember exactly - but I do describe above what I did (roughly): "Figured it out - added my own onClick handler which call's Formik's handleSubmit and then changes state depending on return value﻿"

**Comment by matyushen** [comment]
Thanks. I saw your comment, not exactly sure how to call Formik's handleSubmit from custom handler. So I was hoping for a more specific example. Thanks anyway!
