### ISSUE TITLE
How to compare the values of 2 fields?

### ISSUE THREAD

**Issue by tcrosen** [jaredpalmer/formik#295]
Hi @jaredpalmer thanks for this great library.  I've poured through the docs here and in the Yup repo but I can't seem to figure out how to compare two fields for equality during validation.  Eg. passwords match.  

Any ideas?

Cheers.

**Comment by tcrosen** [comment]
I should mention, I'm using Yup and supplying a `validationSchema`. I'm aware this would be trivial using the `validate` function.

**Comment by tcrosen** [comment]
Okay I finally found [this answer](https://github.com/jquense/yup/issues/97#issuecomment-306547261) in the old closed issues for Yup.

**Comment by qodehub-kingsley** [comment]
https://github.com/jquense/yup/issues/97#issuecomment-450151975 has a solution
