### ISSUE TITLE
How to redirect the page using withRouter HOC after handleSubmit is successful?

### ISSUE THREAD

**Issue by sivadass** [jaredpalmer/formik#299]
Can I have an example/snippet which is using r**eact-router-v4** to redirect after successful  submission? I am not sure how to use **withRouter HOC** with **withFormik HOC**?

If I could get **props.history** inside handleSubmit, then i can redirect the user to new page using **props.history.push('/any-new-page')**

```
const EnhancedForm = withFormik({
  mapPropsToValues: () => ({ 
    surveyTitle: '',
    surveyCategory: ''
 }),
  validationSchema: Yup.object().shape({
    surveyTitle: Yup.string().required('Survey name is required'),
    surveyCategory: Yup.string().required('Survey category is required')
  }),
  handleSubmit: (values, { setSubmitting }, history) => {
    setTimeout(() => {
      alert(JSON.stringify(values, null, 2));
      setSubmitting(false);
      // How to get history props from withRouter HOC to here
      history.push('/any-new-page');
    }, 1000);
  },
})(MyInnerForm);
```

**Comment by prichodko** [comment]
Second argument in `handleSubmit` has props. You should be able to get history from there.

**Comment by sivadass** [comment]
May I know how to connect **withRouter** HOC with **MyInnerForm** component which is already connected with **withFormik** HOC?

**Comment by prichodko** [comment]
There are two ways how to do that:
Manually:
```js
const InnerForm = () => {...}

const Form = withRouter(withFormik(InnerForm))
```

Or you can use `compose` utility provided from various libraries (redux, recompose, ramda...) and use it:

```js
const Form = compose(
   withRouter,
   withFormik,
)(InnerForm)
```
which is useful when you have multiple HOCs.

One important note - it is important in which order they are composed, since you need `Router` props to be available in the `formik`.

**Comment by syntactical** [comment]
I struggled with this for days and I'd like to share my solution.  I'm using Formik with render props, so this is what I do instead, for a contrived example of a form with one field:

```class InnerForm extends React.Component {
    handleSubmit = (values, formikBag) => {
        const { history } = this.props;

        axiosClient.post('/endpoint', {data})
            .then(function (response) {
                history.push("/redirect_url");
            })
            .catch(function (error) {
                console.log(error);
            });
    }

    render() {
        return (
            <div>
                <h1>Your form!</h1>
                <Formik
                    initialValues={{
                        username: ''
                    }}
                    onSubmit={this.handleSubmit}
                    render={({
                        values,
                        errors,
                        touched,
                        handleChange,
                        handleBlur,
                        handleSubmit,
                        isSubmitting
                    }) => (
                        <form onSubmit={handleSubmit}>
                            <div>
                                <label>Your Username</label>
                                <input name="username" type="text"
                                    className={`form-control ${errors.username && touched.username && 'is-invalid'}`}
                                    value={values.username}
                                    onChange={handleChange}
                                    onBlur={handleBlur} />
                                {errors.username && touched.username && <div className="invalid-feedback">{errors.username}</div>}
                            </div>
                            <button type="submit" disabled={isSubmitting}>
                                Submit
                            </button>
                        </form>
                    )}
                />
            </div>
        )
    }
}

const MyForm = withRouter(InnerForm);

export default MyForm;```

It's also not true what @prichodko says above about `handleSubmit`'s second argument including `props`, or at least it's not true anymore, as you can see [here](https://github.com/jaredpalmer/formik/blob/952a084d88d36bce25af5423913eb4fd43206bcf/src/Formik.tsx#L573). `getFormikActions()` returns a list which does not include `props`.

**Comment by jaredpalmer** [comment]
It depends on if you use the hoc or render prop. The hoc includes props

**Comment by jay-jlm** [comment]
This is what worked for me: 
```
<WrappedFormComp {...props} />
```
Now that you passed history via prop drilling, you can write:

```
const formEnhancer = withFormik({
   [...]
    handleSubmit(values, { props }) {
      props.history.push('/some/funky/path')
    }
  })
```

**Comment by diegolamanno** [comment]
I spent some time dealing with this as well. Thanks, @syntactical for your suggestion. I am using render props as well and reading the docs made it a bit more confusing. I was expecting to get `props` with `formikBag`. 

@jaredpalmer I think would be good to add that differentiation between hoc and render prop in the docs

**Comment by olejka91** [comment]
@jay-jlm man, what if user gets an error message as a response from server ?  in your case he will be redirected anyway even if he entered wrong credentials

**Comment by vinyoliver** [comment]
Thanks @converge for your code. I don't know why... for some reason if I just access `this.props.history...` inside the handle method does not work. I had to extract with `const { history } = this.props;` to get work.

**Comment by filozofer** [comment]
I want to share here my solution to deal with handleSubmit functions which are outside of your component context.
In this case, you cannot access directly the route variable from your props'component inside the handleSubmit function.

But you can achieve this by using these two methods :

- On your Formik form change the onSubmit attribute like this:
 `onSubmit={(formData, formMethods) => handleSubmit(props.route, formData, formMethods)}`

- Or inside your component render method use a bind call:
`handleSubmit = handleSubmit.bind(this, route);`
Then the prototype of your handleSubmit method become:
`function handleSubmit(route, formData, formMethods) {`

**Comment by waghcwb** [comment]
None of those solutions worked for me. So I dropped `withFormik` and now I'm using `useFormik` method.

```
import { useFormik } from 'formik';

export default function Form(props) {
	const formik = useFormik({
    initialValues: { email: '' },
    validationSchema: {}, // you can use Yup
    onSubmit: async (values) => {
      props.navigation.navigate('my-route')
    },
  });
  return (
    <View style={styles.container}>
      <TextInput
        label="Email"
        value={formik.values.email}
      />

      <Button onPress={formik.handleSubmit}>
      	Confirm
      </Button>
    </View>
  );
}
```

**Comment by shabbirumrali** [comment]
I'm trying to redirect my form page in formik but unable to do so can some one show me how to redirect after form login
