### ISSUE TITLE
Element name attribute to have nested value

### ISSUE THREAD

**Issue by grezxune** [jaredpalmer/formik#302]
It seems as though the latest published version does not support names on elements like so:

`<Field type="email" name="contact.email" placeholder="Email" />`

However, if I clone the repository and use the dist folder produced by that inside my main project, I get the expected result and all is kosher.

When will this behavior be available through NPM/Yarn so I can deploy with this feature? It is way nicer this way than flattening my data out like I've found everywhere else, or using setFieldValue. Having the name attribute take care of it is the easiest and works with the latest repo code.

Thanks!

**Comment by jaredpalmer** [comment]
npm i formik@next gets you to the alpha release
