### ISSUE TITLE
[Next] Array Helpers not showing touched correctly

### ISSUE THREAD

**Issue by davidhenley** [jaredpalmer/formik#303]
@jaredpalmer

I still can't get validation to work with FieldArrays. The touched[field.name] is coming back as undefined even though it's showing in my touched object.

I noticed that after handleSubmit, it changes touched.products to an object. Is this an error?

It also doesn't reset the field array values when calling resetForm but everything else resets.

My touched and errors before submitting:
```
{
  "errors": {
    "customer": "Required",
    "manager": "Required",
    "reason": "Required",
    "deliveredBy": "Required",
    "date": "Required",
    "location": "Required",
    "products": [
      {
        "cases": "Required",
        "bottles": "Required"
      }
    ]
  },
  "touched": {
    "products": [
      {
        "cases": true
      }
    ]
  }
}
```
touched[`products.0.cases`] is showing as undefined.
errors[`products.0.cases`] is showing correctly though as Required.

This isn't a setFieldTouched issue, because I am using this input elsewhere not in an array and it works fine.

**Comment by bogdansoare** [comment]
how do you validate a *FieldArray* with Yup, something like this would work?
```javascript
validationSchema={Yup.object().shape({
  products: Yup.array().of(Yup.object().shape({
    name: Yup.string().required()
  })),
})}
```
