### ISSUE TITLE
Custom component without <input />

### ISSUE THREAD

**Issue by ancashoria** [jaredpalmer/formik#306]
Is it possible to use Formik for react components that don't rely on html `<input />` field?

My component is a custom selector that relies only on `<div>` and `<span>` elements.
Right now Formik event handler assumes the presence of `event.name`, which is fine for `input` components, but for `div` elements I can't set `name` on them because it's not valid.

Formik is really great for us, but this is quite a blocker right now.
How should we handle this?

Thanks

**Comment by ancashoria** [comment]
So far I have managed to work around it, but it's really hackish.
Here's my solution:
```javascript
(e) => {
            e.target.name = this.props.name
            e.target.value = child.props.value
            this.props.handleChange(e)
```

**Comment by jaredpalmer** [comment]
Use setFieldValue, it’s built just for this

**Comment by ancashoria** [comment]
Thank you so much. 
Formik is great
