### ISSUE TITLE
[Next] Memoization

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/formik#308]
Thoughts?

**Comment by cmswalker** [comment]
👍  As in for re-rendering forms? If so, I was thinking of this the other day and the only snag I can think of is providing an API returning function that knows when to rebuild itself. Formik already has the concept of `values` as its state scope inside the form, so maybe there could be a similar requirement for a cached form. If the "values" (interpolated args) are constant return the cache, if one is different, rebuild the form.
