### ISSUE TITLE
Implementing a foldable input field that opens when 'other' option is selected

### ISSUE THREAD

**Issue by anasshad** [jaredpalmer/formik#309]
Hi, Jared. First of all thanks for Formik. I'm trying to create a survey and I'm using Formik to implement the forms. My question is that I want to show the options as a set of radio buttons. One of these options is 'Other' which when selected should open a form. On submit, the form should submit the content entered in the input form (only when the other radio is checked). How should I go about implementing this? Thanks.

**Comment by jaredpalmer** [comment]
I would manage this through React state directly and outside of Formik
