### ISSUE TITLE
Compute withFormik's displayName from the wrapped component's displayName.

### ISSUE THREAD

**Issue by alisabzevari** [jaredpalmer/formik#310]
If you generate the `displayName` of the `withFormik` result from the wrapped component, this HOC can create nicer names in jest snapshots and react dev tools.

I think it can be easily done by adding the following line of code [here](https://github.com/jaredpalmer/formik/blob/1b02ae4b775864535e9f69e7a3903910e6712143/src/withFormik.tsx#L155):

``` js
C.displayName = `WithFormik(${Component.name || Component.displayName})`;
```

Would be my pleasure to create a PR for that :smiley:.

**Comment by jaredpalmer** [comment]
Feel free to submit a PR
