### ISSUE TITLE
FormikConfig has a generic type of an empty object

### ISSUE THREAD

**Issue by corydeppen** [jaredpalmer/formik#314]
I'm running into the following issue using Formik 0.11.0-beta.1, TypeScript 2.6.2, and `strict: true` in `tsconfig.json`. I can't see why `FormikConfig` has a generic type of `{}`.

```ts
interface Values {
  subject: string;
}

<Formik
  initialValues={{ subject: '' }}
  onSubmit={(values: Values) => alert(JSON.stringify(values))}
  // ...
/>
```

```bash
Type '{ initialValues: { subject: string; }; onSubmit: (values: Values) => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Formik<FormikConfig<{}>, FormikValues>> & Readonly...'.
  Type '{ initialValues: { subject: string; }; onSubmit: (values: Values) => void; }' is not assignable to type 'Readonly<FormikConfig<{}>>'.
    Types of property 'onSubmit' are incompatible.
      Type '(values: Values) => void' is not assignable to type '(values: {}) => void'.
        Types of parameters 'values' and 'values' are incompatible.
          Type '{}' is not assignable to type 'Values'.
            Property 'subject' is missing in type '{}'.
```

**Comment by corydeppen** [comment]
This doesn't appear to be an issue using TS 2.5.3, but I see it using TS >= 2.6.1. I also see it using either latest or next tags of Formik.

**Comment by jaredpalmer** [comment]
Don’t have access to my computer today. Can you submit a PR?

**Comment by corydeppen** [comment]
I'd be happy to, though I spent time last night and this morning looking over the Formik types and haven't been able to determine why TS is inferring an empty object for `FormikConfig`. Not sure what changed between TS 2.5.3 and 2.6.1 that would cause the issue.

Actually, the same thing was reported in #283, which is what originally led me to install `formik@next` with the hope your PR to upgrade React and TS might help. Unfortunately, I still see the problem after the upgrade.

If you think of anything that might point me in a specific direction, I don't mind digging some more.

**Comment by DanielRosenwasser** [comment]
This is possibly a TypeScript 2.6 bug. See https://github.com/Microsoft/TypeScript/issues/20891.
