### ISSUE TITLE
Could not find a declaration file for module 'prop-types'

### ISSUE THREAD

**Issue by corydeppen** [jaredpalmer/formik#316]
I've created a new project using [create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript) and added the simple [Formik example](https://github.com/jaredpalmer/formik#render-props-formik--and-field) from the readme but I got a compile error right away:

`error TS7016: Could not find a declaration file for module 'prop-types'.`

I think this is due to the `@types/prop-types` package being included in Formik's `devDependencies` and not `dependencies`. Based on the [TypeScript publishing doc](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies), it seems like including the dependency in `dependencies` would be an appropriate way to manage it and should resolve this issue. Unfortunately, non-TS projects would bring down the dependency, but the alternative is requiring TS projects to manage a dependency their code doesn't depend on.

**Comment by oneillsp96** [comment]
Same issue here...

**Comment by sjsingh85** [comment]
Same issue here

**Comment by corydeppen** [comment]
@jaredpalmer Would you accept a PR for this, or are you opposed to adding `@types/prop-types` to `dependencies`?

**Comment by jaredpalmer** [comment]
I guess i'd rather document it in master (right after the install instructions), and then just spend our energy moving to `create-react-context` so we can drop prop-types all together.

**Comment by Robinfr** [comment]
This is still happening.

**Comment by pnoonan91** [comment]
I was able to resolve this by installing `@types/prop-types`

**Comment by HamidTanhaei** [comment]
same issue
