### ISSUE TITLE
handleBlur not firing

### ISSUE THREAD

**Issue by viktorbergehall** [jaredpalmer/formik#32]
I'm trying to build a validation process where errors don't show up before the first blur for each input (i.e no visible errors when the user is typing for the first time). But I'm not able to fire handleBlur on the blur event.

Example: https://codesandbox.io/s/nZ6nZnvQR

**Comment by eonwhite** [comment]
Formik does not have an option for `handleBlur`, so your alert will never fire. The built-in Formik `handleBlur` will set the field's `touched` state, which is probably what you want to happen:

https://github.com/jaredpalmer/formik/blob/master/src/index.tsx#L270-L276

You can check the field's touched state when deciding whether to display an error or not. So you'd change `errors.email &&` to `errors.email && touched.email &&` in the form render.

If for some reason you don't like the Formik `handleBlur` and want to write your own, of course, you could always implement your own function, and perhaps call Formik's `setTouched` from it. But passing handleBlur to the Formik options will do nothing.
