### ISSUE TITLE
React-Native Picker

### ISSUE THREAD

**Issue by JTrembl1** [jaredpalmer/formik#322]
My basic forms work fine, however, as there are some caveats with react-native, I could use some help in knowing if the issue is how I am using formik, or using it with react-native.  When I attempt to fill in a picker in react-native using formik, the form resets the picker to the original value immediately after I select an option. I have stripped the code down, as I feel someone should have the answer without a lot of code.

The reason that I post here, as well as SO, is that I see very few examples either here or elsewhere for formik examples with react-native...  I think that this tool is great, but it could use a few more react-native examples.  Thus, I address the team directly stating that as my issue.  As I am still learning formik, I do not feel that I am the person to handle this.

If you feel this is not the case, let me know and I will be happy to address this elsewhere.

Thank you for all your hard work, as I said, this is a great tool.
```
<Formik
      onSubmit={
        props.onSubmit(props.values)
      }

      mapPropsToValues = {(props) => ({
        id: props.id,
        status: props.status
      })}

      validate={values => {
        // same as above
        let errors = {};
        return errors;
      }}

      onValueChange={ (itemIndex) => {
        this.props.values.status = itemIndex
      }}

      render= { props => (
        const { id, status } = this.props
        <View>
          <Text style={styles.textResultsHeaderStyle}>Job: {id}</Text>
          <Picker
            selectedValue={status}
            onValueChange={itemIndex => this.onValueChange}>
            <Picker.Item label="New" value="0" />
            <Picker.Item label="Requested" value="1" />
            <Picker.Item label="Responded" value="2" />
            <Picker.Item label="Closed" value="3" />
          </Picker>
          <RoundedButton disabled={props.isSubmitting} onPress={props.handleSubmit} text="SUBMIT" />
        </View>
      )}
    />
  </View>
```

**Comment by JTrembl1** [comment]
Is anyone able to create a tag in S.O. for formik?  I do not have the reputation...

**Comment by jaredpalmer** [comment]
MapPeopToValues is not used in the Formik component, only in the hoc. Use initialValues instead

**Comment by jaredpalmer** [comment]
Sorry for typos. On my phone

**Comment by JTrembl1** [comment]
Thanks.  That helps for the initial values...

**Comment by jaredpalmer** [comment]
should fix `onValueChange` to be  `onValueChange={this.onValueChange}`

**Comment by derekcrosslu** [comment]
My picker is able to change the initial value but for some reason I don't fully understand yet, the picker thing,  goes back....any suggestions?  Thanks!!

`
<Formik
        initialValues={{ name: '', agree: false, status: '' }}
        onSubmit={(values, actions) => {
          alert(JSON.stringify(values))
          setTimeout(() => {
            actions.setSubmitting(false)
          }, 1000)
          console.log(values);>
        {
              props => (

          <React.Fragment>
            <TextInput
              style={{
                borderWidth: 1,
                borderColor: 'black',
                padding: 10,
                marginBottom: 3,
              }}
              onChangeText={props.handleChange("name")}
            />
            <Switch
              label="My Switch!!"
              value={props.values['agree']}
              onValueChange={value => {
                props.setFieldValue('agree', value)
              }}
            >
            </Switch>
            <Picker
              value={props.values['status']}
              selectedValue={'1'}
              onValueChange={value => {
                props.setFieldValue('status', value)
              }}
            >
              <Picker.Item label="New" value="0" />
              <Picker.Item label="Requested" value="1" />
              <Picker.Item label="Responded" value="2" />
              <Picker.Item label="Closed" value="3" />
            </Picker>


            <Button title="Submit" onPress={props.handleSubmit} />

          </React.Fragment>
        )}
      </Formik>`

**Comment by derekcrosslu** [comment]
never mind..I found my answer, I just needed to assign   selectedValue={props.values.status}
