### ISSUE TITLE
Calling resetForm in onSubmit when validateOnMount is on will cause an infinite loop

### ISSUE THREAD

**Issue by hyakt** [jaredpalmer/formik#3259]
### Current Behavior

In the case of a formik object with parameters like the code below, changing any value in the form and submitting it will cause an infinite loop and the browser will hang.

```js
 const formik = useFormik({
    validateOnMount: true,
    onSubmit: (values, { resetForm }) => {
      resetForm({ values });
    }
  });
```

### Expected behavior

Expect that calling resetForm during onSubmit will not result in an infinite loop.

### Reproducible example

https://codesandbox.io/s/formk-infinite-loop-bug-example-ocqmw

1. Open the page.
2. Enter a value into some form.
2. Click the submit button.
4. Confirm that the preview screen hangs...

### Additional context
Only happened with formik version 2.2.5 or later.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.5 |
| React            | 17.0.2 |
| TypeScript       | - |
| Browser          | Google Chrome	91.0.4472.106 (Official Build) （x86_64) |
| npm/Yarn         | yarn version v1.22.10 |
| Operating System | macOS 10.14.6 |

**Comment by SirwanAfifi** [comment]
Because you're passing the same values to `resetForm`. This will fix the issue if you don't pass anything to it:

```ts
resetForm();

// OR
resetForm({
  values: {
    firstName: "",
    lastName: ""
  }
});
```
