### ISSUE TITLE
Formik doesn't check if event is present before calling preventDefault in handleSubmit

### ISSUE THREAD

**Issue by jaccohub** [jaredpalmer/formik#326]
## Current Behavior
When calling handleSubmit outside of innerForm without passing an event, you get an error because it tries to call preventDefault on the non existing event.

## Desired Behavior
Before calling handleSubmit; check if event is passed, and only then try to call preventDefault

## Suggested Solutions
https://github.com/jaredpalmer/formik/blob/master/src/formik.tsx#L443
Add a check if e exists before calling preventDefault

## Info
Bug occured for me when trying to submit a formik form from a child component by passing its handleSubmit to the child and calling it manually.

I had to bypass the formik behaviour by calling handleSubmit with a mocked event, not very clean...
 

- Formik Version: 0.10.5
- OS: macOS Sierra v10.12.6
- Node Version: 8.6.0
- Package Manager and version: npm 5.3.0

**Comment by jaredpalmer** [comment]
You should use submitForm for this use case

--
Jared
________________________________
