### ISSUE TITLE
Is touched prop run on react native?

### ISSUE THREAD

**Issue by aligos** [jaredpalmer/formik#329]
Questions:
Is touched prop run on react native?

**Comment by artem-romanov** [comment]
@aligos I guess that code should do the work:

```
<TextInput
  onChangeText={(text) => setFieldValue('email', text)}
  value={values.email}
  onBlur={() => setFieldTouched('email')}
/>
{errors.email && touched.email &&
  <Text>Error!</Text>
}
```

**Comment by 5ervant** [comment]
@artem-romanov But doing `onBlur={() => props.setFieldTouched('fieldName')}` makes my `onSubmitEditing={props.handleSubmit}` not working. On the web, upon pressing _"Enter"_ while I'm typing on the `<Input />` field does submit the form no more with that `onBlur`.
