### ISSUE TITLE
Provide a full TS-example for React Native

### ISSUE THREAD

**Issue by marcmo** [jaredpalmer/formik#332]
## Current Behavior
While getting something running on React Native works, it is not easy to get going without a full example. The example-snippets for RN clarify some pitfalls, but do not outline a running example that can be used to get started.

## Desired Behavior

Have an easy way for RN devs to integrate formik into their app.

## Suggested Solutions

* Provide a couple of RN-examples that make use of the formik API
* point out the differences in existing examples to enable devs to use them in RN
* include a RN-Typescript example (that type-checks)

## Info
 

- Formik Version: 0.10.5
- OS: Mac OS 10.13.2
- Node Version: v8.9.1
- Package Manager and version: yarn 1.3.2

**Comment by JeremyBradshaw7** [comment]
+1

**Comment by jaredpalmer** [comment]
@marcmo definitely. Would it be better to use expo and add that TS tweak or microsoft's react native starter?

**Comment by marcmo** [comment]
@jaredpalmer personally I'd go with the microsoft starter but actually I don't think it matters.
what keeps me from using formik (for my react native development using typescript) is that I had trouble getting the most important formik features to work. I think providing one full fledged example (no snippets) would go a loooooooong way ;)

**Comment by marcmo** [comment]
any updates on this? now since the 1.0 release is out that would be a good time. Just one file with one nice example that could be used as an easy starter. :)

**Comment by FilipMaslovaric** [comment]
Still waiting...
