### ISSUE TITLE
[Next] Changing array item value changes initialValues

### ISSUE THREAD

**Issue by sarics** [jaredpalmer/formik#336]
## Bug, Feature, or Question?
Bug.

## Current Behavior
https://codesandbox.io/s/zrx7lxxn5l

If you type anything in the list item input, the the initialValues prop is changing too.

## Suggested Solutions
Formik's values state should be set with the recursive clone of the initialValues. By default react gives you the shallow clone of the properties, so you need to do it manually (with lodash's cloneDeep for example).

## Info
 - Formik Version: 0.11.0-beta.1

**Comment by sarics** [comment]
Closing, as it is fixed in the stable 0.11.0 version.

Thank you.

**Comment by amadeogallardo** [comment]
@sarics I'm actually able to reproduce the same behavior on the current 1.3.2 version.

The `initialValues` prop contains an array with a nested property. When updating that property from within the form, not only the `values` property is changed, but also the `initialValues`.

@jaredpalmer Could this be a regression?
