### ISSUE TITLE
Dynamic <Fields/>?

### ISSUE THREAD

**Issue by chbdetta** [jaredpalmer/formik#338]
## Question
Could we have a more generic solution for dynamic forms? The `FieldArray` is useful only for Array/List data, but what about situations like this: 

an radio input toggles some optional field `A`. When the radio input is checked, `A` should be included in the form and has validation states in it. And when the radio input is unchecked, `A` should be removed from the form along with its validation states.

Is there any solution for this kind of usage? Maybe I missed. But if there weren't, I thinks it's a common feature for form managements.

 

- Formik Version: 0.11.0-beta.1
- OS: MacOS
- Node Version: v8.9.1
- Package Manager and version: yarn@1.3.2

**Comment by jaredpalmer** [comment]
This kind of behavior is usually highly specific. I would suggest using custom components

**Comment by ls-matheo-jaouen** [comment]
It's a pretty common behavior no?
