### ISSUE TITLE
FieldArray documentation specifies component prop, but doesn't implement.

### ISSUE THREAD

**Issue by teevans** [jaredpalmer/formik#340]
## Bug, Feature, or Question?
Bug
## Current Behavior
When using the component prop of FieldArray, component does not render.
## Desired Behavior
When using the component prop of FieldArray, component should render.
## Suggested Solutions
Render the component, I'd submit a PR, but I'm not entirely sure what the graceful solution is.

## Info
 

- Formik Version: 11.0-beta.1
- OS: OSX
- Node Version: 6.11.4
- Package Manager and version: NPM 3.10.10

**Comment by Graham42** [comment]
I think this is fixed by #341
