### ISSUE TITLE
Displaying overall form error message

### ISSUE THREAD

**Issue by Dremora** [jaredpalmer/formik#345]
## Question

I need to figure out whether there's at least one field in the form which has an error *and* has been touched, and if so, display the error message above the form. Currently the only way to do so is to cross-reference every entry from `errors` with a corresponding entry in `touched` on each `onChange`. This becomes more complicated and computationally expensive in a deeply nested form.

Do you think there's a place for this functionality in the library? Or maybe there's already a trivial way of doing this?

**Comment by jaredpalmer** [comment]
Check if the form is dirty and there’s at least one key in touched.

**Comment by Dremora** [comment]
This won't work. Imagine there are two string fields, both empty by default, and both are required to be at least 1 character long. The user enters something in the first field. As a result, the whole form gets validated. The first field is touched and passes validation. The second field is not touched but fails validation. So the form is dirty, has errors and there is at least one field touched. However, I don't want to display the error message in such case since the user hasn't touched fields which result in errors.

**Comment by jaredpalmer** [comment]
I would keep the logic the same as you would for showing individual errors but just group the display visually together.
