### ISSUE TITLE
Dirty prop not changing when deeply nested field is changed

### ISSUE THREAD

**Issue by ChapterSevenSeeds** [jaredpalmer/formik#3459]
So, lets say I have this:

`<Formik initialValues={{ items: [{ name: "Stick" }] }} ...`

I then do this:
`formikProps.values.items[0].name = "Bat";`
`formikProps.setFieldValue('items', [...formikProps.values.items]);`

After the above, the dirty prop stays as false where it should be true.

Visit https://codesandbox.io/s/formik-example-forked-yds3k?file=/index.js to see an example of this happening. In that fiddle, just click the 'submit' button to perform essentially exactly what I did just above. The dirty prop remains false. Can anyone see what I am doing wrong?

**Comment by johnrom** [comment]
@ChapterSevenSeeds Formik's state is immutable, so you cannot actually update the item in place like this:

```ts
// this is bad
formikProps.values.items[0].name = "Bat";
```

You should instead set the value directly:

```js
formikProps.setFieldValue("items[0].name", "Bat");
```

https://codesandbox.io/s/formik-example-forked-6h4d3?file=/index.js

**Comment by ChapterSevenSeeds** [comment]
@johnrom That was my bad. Thank you for the correction. It worked wonders in my specific use case.
