### ISSUE TITLE
setFieldValue is turning an array into an object

### ISSUE THREAD

**Issue by Monte47** [jaredpalmer/formik#3463]
I have Formik set up with this schema

```
{
  test1: {
    field1: some boolean,
    field2: some array of type <User>,
  },
  test2: some array of type <User>,
}
```

And in both a form for test1 and test2 I have two instances where I use `setFieldValue`

in instance 1 I do `setFieldValue('test1.field1', [...newUsers])` and it works correctly

But in instance 2 I do `setFieldValue('test2', [...newUsers])` and it breaks my application. It seems to coerce the value to an object. So instead of test2 being an array. It is now an object where each key is a `<User>`.

**Comment by fhollermayer** [comment]
Hey Monte,
I tried to reproduce the issue, but I guess I'm missing something.
Have a look at my codesandbox; Can you tell what is different from your approach?

https://codesandbox.io/s/clever-chaplygin-9qbrv?file=/src/App.tsx

**Comment by Monte47** [comment]
Apologies, this error was happening because of a higher level specific implementation in my code.

My solution was just to further nest that array in `test2` similarly to 1.
