### ISSUE TITLE
Allow calling handleSubmit without requiring the event argument

### ISSUE THREAD

**Issue by spruce-bruce** [jaredpalmer/formik#347]
## Feature
I want to call `handleSubmit()` myself as part of an auto-save feature. `handleSubmit` calls `e.preventDefault()` so right now I'm doing this `this.props.handleSubmit({preventDefault: () => null})` which is goofy, but works.

## Current Behavior
`handleSubmit()` throws an error when you don't provide an event argument.

## Desired Behavior
`handleSubmit()` gracefully handles the lack of an event parameter and submits the form.

## Suggested Solutions
Is this as simple as `e && e.preventDefault()`? I can submit a PR for this later today, but wanted to get some feedback first.

## Info
 

- Formik Version: 0.10.5
- OS: IOS and Android
- Node Version: 8.9.3
- Package Manager and version: npm 5.6.0

**Comment by jaredpalmer** [comment]
Use submitForm() to trigger this behavior
