### ISSUE TITLE
Updating one field clears all errors from all fields

### ISSUE THREAD

**Issue by Asghwor** [jaredpalmer/formik#3472]
## Bug report

Form clears all errors when just one of the items is updated.

### Current Behavior

Whenever multiple fields have an error set, changing any fields result in all errors being removed.

### Expected behavior

Only the errors on the updated fields get removed.

### Reproducible example

https://codesandbox.io/s/formik-codesandbox-template-forked-5cess?file=/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.1.5
| React            | 16.13.0
| TypeScript       | 3.9.7
| Browser          | Firefox
| npm/Yarn         | npm 6.13.4
| Operating System | Ubuntu 18.04

**Comment by Asghwor** [comment]
Error disappeared by itself.

**Comment by orionivv** [comment]
Same with me
In the example it is not fixed
Any idea why it happens?
