### ISSUE TITLE
[Discussion] Whole form validation

### ISSUE THREAD

**Issue by rostero1** [jaredpalmer/formik#35]
I really enjoy this library.  Yup works great and I haven't experienced any performance issues validating the entire form when an individual field changes.  I did experience an interesting side effect of validating the entire form on field change:  `setErrors`.  Let's say my backend returns `{username: 'already taken', field1: 'other error', field2: 'another'}`.  I use `setErrors` to add those to the individual fields, but when someone changes the username then all of the errors clear because there is no definitions for them in yup, as they were returned in the response.  The result is a loss of error visibility.

For now, I'm just going to collect these errors and present them in one giant error box at the top of the form using `setError`.

**Comment by jaredpalmer** [comment]
Thanks for your kind words. Do you know the keys of `field1` and `field2` ahead of time? Also can you share the code of what you are trying to do by any chance?

**Comment by jaredpalmer** [comment]
I discovered a Yup method [Yup.reach()](https://github.com/jquense/yup#yupreachschema-schema-path-string-value-object-context-object-schema) that would allow (in theory) for independent field-level validation. Formik currently validates against the entire schema. This has pros and cons. Validating the entire schema allows you to build forms with interdependent fields and conditional validations with just Yup schemas, validating against a field (on the deltas) may be faster (depending on how fast `reach` actually is). Regardless, Formik would still validate the whole schema on `handleSubmit`, so interdependent schemas would still see their day in court. Error messages could get weird though. Hmmm....

Thoughts?

**Naive implementation**
```tsx

handleChange = (e: React.ChangeEvent<any>) => {
   e.persist()
   this.setState(state => ({ ... })
   if (validateOnChange) {
      Yup.reach(schema, e.target.name).validate({ ... })
        .then( 
          // ... process errors
        )
   }
}
```

**Comment by jaredpalmer** [comment]
see #61
