### ISSUE TITLE
Access form `onSubmit` event data?

### ISSUE THREAD

**Issue by Tailzip** [jaredpalmer/formik#350]
## Question?

I'm using `withFormik` and I currently have 2 separate submit buttons in my form, and I need to identify which one has been clicked in my `handleSubmit` function, but `event` data isn't passed along. Any ideas how I could do that? 

Thanks!

**Comment by nmaves** [comment]
Funny, I just ran into this issue with Redux-Form so I thought I would take a look at this library to see how they handled it.

**Comment by jaredpalmer** [comment]
You can make your own handler that calls submitForm instead of using handleSubmit

**Comment by tannera** [comment]
Getting the event object inside of handleSubmit would be useful in some cases.

**Comment by jaredpalmer** [comment]
These tend to be edge cases where you should call your own handler and submitForm

**Comment by victordidenko** [comment]
Why not pass event object as a third argument to `onSubmit` (`handleSubmit`)?

Let me give an example:
There is non-standard feature in Chrome, called "Credentials API", which allows developer to save and use passwords to/from browser. One of constructors for `PasswordCredential` [(docs)](https://developer.mozilla.org/en-US/docs/Web/API/PasswordCredential/PasswordCredential) accepts HTMLFormElement. So I need to pass HTML form to it, in case authorisation was successful and I want to save credentials. So how am I supposed to write my own handler, if I need HTML form _inside_ submitForm, to pass it to my API/service call/action?

I can make PR for that

**Comment by jetamartin** [comment]
I too needed access to event in the standard on submit handler...seems like a nice feature to add...not so sure it is an "edge case". FYI, I have a list of "cards" with embedded forms in each card and need a way to determine which card has submitted the form (i.e., id is stored on the submit button).

**Comment by RavenHursT** [comment]
Wow.. this is excruciatingly frustrating.  Why would you change the signature of a submit handler?  Why not be consistent and just include the `FormEvent` that you're passed in `handleSubmit(e)`?

I'm not even sure how to get ahold of the `FormEvent` inside of `onSubmit`?  Has anyone figured that out? Or better yet, have an example?

**Comment by RavenHursT** [comment]
Well.. for anyone else struggling w/ this... Here's how I've hacked around this problem:

https://stackblitz.com/edit/formik-get-event-hack?file=index.tsx

**Comment by niksumeiko** [comment]
@RavenHursT's hack involves an intermediate state for event data. It would be useful to make this work without it.

**Comment by AnoplexAdmin** [comment]
Not edge case.  Many developers have complex forms with multiple submits.  I was hoping I could use Formik to simplify the forms in my application, but I don't have much confidence at this point. The fact that the owner dismisses good ideas with terse comments such as "You can make your own handler that calls submitForm instead of using handleSubmit" is not helping the situation.

**Comment by opena854** [comment]
Hi, 

I solved this issue for me as follows:

https://stackblitz.com/edit/formik-get-event-hack-nvkyg1?file=index.tsx

``` jsx
    <Formik initialValues={{ name: '' }} onSubmit={onSubmit}>
      {({ handleSubmit, setFieldValue }) => (
        <form
          onSubmit={(e) => {
            const submitter = e.nativeEvent?.submitter;

            if (submitter && submitter.name && submitter.value) {
              setFieldValue(submitter.name, submitter.value);
            }

            handleSubmit(e);
          }}
        >
          <InputField
            {...{
              type: 'text',
              name: 'name',
            }}
          />
          <button
            {...{
              type: 'submit',
              name: 'buttonClicked',
              value: 'A',
            }}
          >
            Button A
          </button>
          <button
            {...{
              type: 'submit',
              name: 'buttonClicked',
              value: 'B',
            }}
          >
            Button B
          </button>
        </form>
      )}
    </Formik>
```

**Comment by kendallroth** [comment]
> You can make your own handler that calls submitForm instead of using handleSubmit

@jaredpalmer I have come across this a couple times, and was curious if you would be willing to provide an example of this, as it does seem to come up every so often 🤷?
