### ISSUE TITLE
setFieldValue does set the dirty flag as expected

### ISSUE THREAD

**Issue by justengland** [jaredpalmer/formik#353]
I have been trying to use uncontrolled form inputs and custom elements, however when I use setFieldValue, the value get set but the dirty flag does not. Perhaps, I am missing something, but I thought we could use setFieldValue, but it does work as expected.

![image](https://user-images.githubusercontent.com/507350/35102826-4bd651a8-fc21-11e7-8f7c-cf85a0ae679b.png)

**Comment by justengland** [comment]
It seems to work if I call both setTouched and setFieldValue, is that the best way?

  setFieldValue = (name, value) => {
    console.log('Formik.setFieldValue:', name, value)
    this.props.setTouched(name)
    return this.props.setFieldValue(name, value)
  }

**Comment by prichodko** [comment]
`setFieldValue` just sets the value imperatively, no side-effects. For setting a flag I rather recommend using `setFieldTouched`.

**Comment by justengland** [comment]
That is what I ended up doing, it seems to work fine.

**Comment by jaredpalmer** [comment]
Fixed

**Comment by zhGio** [comment]
Is it possible to control whether the setFieldValue was set to dirty or not?
My usecase: i load some data from the API and pre-load form with the response using setFieldValue, but then I get dirty as true and my validation triggers straight up

**Comment by johnrom** [comment]
@zhGio you should use `initialValues` with `enableReinitialize={true}` instead of `setFieldValue`.

Dirty means that values on the form do not match the values the form was populated with, which is true once you use setFieldValue with a different value than initialValues.

enableReinitialize has other side effects, so if those are an issue you should follow #2026

**Comment by insidewhy** [comment]
Using setFieldTouched doesn't help for us at all, we just can't tell whether an input has been dirtied when using `setFieldValue` or `helpers.setValue`. We also are very confused as to why formik considers a form dirty when it's "different to initial values" and not "different to submitted values".

**Comment by johnrom** [comment]
@insidewhy please provide a codesandbox with your setFieldTouched issue and I'll see if I can help work around it. setFieldValue should set the form as dirty if anything has changed from the initialValues.

In terms of how dirty works, according to documentation this is also how [Redux Form](https://redux-form.com/6.0.0-rc.5/docs/api/selectors.md/) works, and [React Final Form](https://final-form.org/docs/react-final-form/types/FieldRenderProps) actually provides a separate prop -- `dirtySinceLastSubmit`. If you're interested in something like that, I'd open a new issue as a Feature Request.
