### ISSUE TITLE
React Hook "useFormikContext" cannot be called at the top level

### ISSUE THREAD

**Issue by 12sam12** [jaredpalmer/formik#3536]
## Bug report
How to set value of forms when using react-dropzone

React Hook "useFormikContext" cannot be called at the top level. React Hooks must be called in a React function component or a custom React Hook function react-hooks/rules-of-hooks

### Current Behavior
Lets assume I have a form file-drop field. I drop a file. But as my project is complex I have defined my onDrop method in another file. Now once the file is dropped I need to set one form fields to be this file. How do I go about structuring it? I tried useFormikContext hook. But it errored out. Any ideas??

### Expected behavior

Should work fine without errors.

### Reproducible example
Im just showing some relevant portion of the code of an app generated through create-react-app. Pls just identify the structural issue here:
```javascript
//Main file
import { FileUploadSection } from "./FileUploadSection.js";
const FileUploadContainer = ({ files = [] }) => {
const formikProps = {
    initialValues: {
      toUploadFile: null,
    },
    onSubmit: (values, { setSubmitting }) => {
      console.log("submitting the form");
      setSubmitting(true);
      setSubmitting(false);
    },
  };
return (
    <Formik {...formikProps}>
      {(props) => (
        <form className={cx("form", "filedrop")} onSubmit={props.handleSubmit}>
<FileUploadSection /></form>
      )}
    </Formik>
);
};

export { FileUploadContainer };


//Imported FileUploadSection function component file
import { useDropzone } from "react-dropzone";
import { useFormikContext } from "formik";
const FileUploadSection = () => {
  const formikProps = useFormikContext();
  const onFileDrop = (e) => {
    formikProps.setFieldValue("number", 5);
  };
const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop: onFileDrop,
  });
return (
<FileUpload
      {...getRootProps()}
      isDragging={isDragActive}
    >
      {isDragActive ? (
        <span>Drop files here</span>
      ) : (
        <span>Choose a file or drag and drop here</span>
      )}
      <Input
        {...getInputProps()}
      />
    </FileUpload>
);
};

export { FileUploadSection };
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | "^2.2.9"
| React            | "^17.0.2"
| TypeScript       |
| Browser          | Firefox 96.0 (64-bit)
| npm/Yarn         | 8.5.3
| Operating System | Linux

**Comment by 12sam12** [comment]
Reproducible. In problems section you would find the formik related error.
https://codesandbox.io/s/aged-river-81vff1?file=/src/index.js

**Comment by adam-thomas-privitar** [comment]
This is isnt a formik bug, its a misunderstanding of how hooks work. In your codesandbox, `useFormikContext` is called outside of a react component. Thats not valid React.

> But as my project is complex I have defined my onDrop method in another file.

The answer is to break this out as a shared hook. not a plain function. So:

```
const useOnDropHandler = () => {
  const formikProps = useFormikContext()
  return (e) => {
      formikProps.setFieldValue("number", 5);
  }
}

```

Then in your use case, you can call this hook inside your component, and pass the result to the `onDrop` prop.

**Comment by johnrom** [comment]
It looks like you already solved the issue by moving the code into your component:

```jsx
const FileUploadSection = () => {
  const formikProps = useFormikContext();
  const onFileDrop = (e) => {
    formikProps.setFieldValue("number", 5);
  };
  // ...
```

But you left the unused hook in your FileUpload.Logic.js:

```js
// delete the below, it's not used since you rewrote this in the component above
const formikProps = useFormikContext();

const onFileDrop = (e) => {
  console.log(e);
  console.log(e);
  formikProps.setFieldValue("number", 5);
};
```

**Comment by 12sam12** [comment]
They work fine. Thanks.
