### ISSUE TITLE
Remix js and formik?

### ISSUE THREAD

**Issue by danielefinocchiaro** [jaredpalmer/formik#3538]
### Discussed in https://github.com/jaredpalmer/formik/discussions/3537

<div type='discussions-op-text'>

<sup>Originally posted by **danielefinocchiaro** April  5, 2022</sup>
Hi, I am following both the official docs and various tutorials on the web but my formik doesn't work. If I follow the instructions of the docs with create-react-app it's ok, but in my project i would use remix js. If I do a copy an paste of my code with remix doesn't work. Anyone have used both libraries?

In particular the code below doesn't update initial values when I do a change. 

My code

import React, { useEffect } from "react";
import ReactDOM from "react-dom";
import { Formik, Form, useField, useFormikContext, useFormik } from "formik";

export default function SignupForm() {
  const formik = useFormik({
    initialValues: { firstName: "", lastName: "", email: "" },
    onSubmit: (values) => {
      console.log(values, "values");
    },
    enableReinitialize: true,
  });

  console.log(formik.values, "formik.values");

  return (
    <>
      <h1>Subscribe!</h1>

      <form>
        <input
          name="firstName"
          id="firstName"
          type="text"
          onChange={formik.handleChange}
          value={formik.values.firstName}
          placeholder="Jane"
        />
        <input
          name="lastName"
          type="text"
          onChange={formik.handleChange}
          value={formik.values.lastName}
          placeholder="Doe"
        />
        <input
          name="email"
          type="email"
          onChange={formik.handleChange}
          value={formik.values.email}
          placeholder="jane@formik.com"
        />

        <button type="submit">Submit</button>
      </form>
    </>
  );
}
</div>

**Comment by johnrom** [comment]
Please create only an issue or discussion, not both. If you can reproduce your issue in a codesandbox, I'll take a look and see if I can help.

I've never used remixjs, but if it is React and uses React >= 16.8.3 then it should be compatible with Formik. But since it's newer, it's possible there are incompatibilities.

**Comment by danielefinocchiaro** [comment]
@johnrom Sorry, I'm new in this world. I link to you my public repository https://github.com/danielefinocchiaro/mymessanger
Let me know if you can help me. Thx

**Comment by johnrom** [comment]
@danielefinocchiaro 

Setting up a sandbox reproduction is a great way to learn, and there's always a chance you can figure out your issue while trying to reproduce in a new environment. Please try reproducing the issue before asking others to look at it.

**Comment by danielefinocchiaro** [comment]
Hi to everyone, I close this topic because after a long period of test and try I find my error. Remix docs say that "<Scripts /> Renders the <script> tags needed for the initial render. Bundles for additional routes are loaded later as needed.". Without this in the root pag, the app will not load any JS client side.
