### ISSUE TITLE
Demos in TypeScript

### ISSUE THREAD

**Issue by DevanB** [jaredpalmer/formik#355]
## Bug, Feature, or Question?
Question

## Info
Will the demos (currently in JS) be converted and offered in TypeScript?

I ask because I am trying to figure out how to use a third-party library (react-select) in addition with TypeScript and make an input component.

- Formik Version: 0.10.5
- OS: macOS 10.12
- Node Version: v8.9.3
- Package Manager and version: yarn!

**Comment by tsriram** [comment]
Here's my shot at the react-select example - https://codesandbox.io/s/mzkv3mr7x (may not be 100% typed though). Wonder if I should create a PR to add this example to this repo, @jaredpalmer? 

TS error that you see in line 143 should be gone once DefinitelyTyped/DefinitelyTyped#23054

**Comment by jaredpalmer** [comment]
Are we talking about the new docs site? Yes, I have plans to have a toggle between JS and TS in the examples.

**Comment by DevanB** [comment]
Any and all documentation, meaning the current and the new.

**Comment by djdu** [comment]
I get following error:

> color must be a `array` type, but the final value was: `null` (cast from the value `"red"`). If "null" is intended as an empty value be sure to mark the schema as `.nullable()`

When I try to do the select without the multiple select. Even with the multi select on the above sample code gives error when you delete the selection.

Any solution for this?

**Comment by lukephills** [comment]
The React Native example doesn't compile using Typescript because `onChangeText` and `onBlur` are incompatible. What's the recommended typescript way to pass the input name?

```
<TextInput
      onChangeText={props.handleChange('email')}
      onBlur={props.handleBlur('email')}
      value={props.values.email}
    />
```

**Comment by bschnelle** [comment]
I'm also running into this issue. Any advice here?

**Comment by brortao** [comment]
As long as this bug exists, you can hack your way around it by
```
<TextInput
  onChangeText={props.handleChange('email')}
  onBlur={props.handleBlur('email') as undefined}
  value={props.values.email}
/>
```
