### ISSUE TITLE
setting multiple values while leaving the rest as-is

### ISSUE THREAD

**Issue by twelve17** [jaredpalmer/formik#356]
## Question

Does `setValues` only change the given values, or does it create a new state altogether, with only the given values, erasing other values altogether?

## Current Behavior

`setValues` appears to [replace entire state, only leaving the ones specified](https://github.com/jaredpalmer/formik/blob/89c67ff6dd75d51bdca0d1cf9b09a68ef6d13176/src/formik.tsx#L308).

## Desired Behavior

Clarify documentation that `setValues` replaces the entire state, as opposed to only setting the given values and leaving any other existing ones as-is.

## Suggested Solutions

I can do multiple calls to `setFieldValue`, but I believe that will cause a refresh of the component on each, no?

I can provide a PR for the docs, if desired.

## Info
 
- Formik Version: 0.10.5
- OS:  Mac OS X sierra
- Node Version: 8.9.4
- Package Manager and version: npm 5.3.0

**Comment by GyCtaB** [comment]
Yes. `setValues` replace current values with the new one. If you want to preserve your old values and set only new one you can do something like this`setValues({
  ...prevValues,
  newKey: newValue
})
`
