### ISSUE TITLE
Cannot get Formik 2.2.9 to work with MUI 5.8.1 Checkbox

### ISSUE THREAD

**Issue by bmueller-alp** [jaredpalmer/formik#3575]
## Bug report

I'm having trouble getting Formik and MUI 5 checkboxes to work together. In the Codesandbox below, you'll see a form with two unchecked checkboxes: "with MUI" and "without MUI". 

The "without MUI" checkbox behaves as expected: I can check and uncheck it, and if I submit, I see `withoutMui` in the console with a value of `true` or `false`.

However, the "With MUI" checkbox exhibits different behavior. Rather than setting `true` or `false`, it creates an array of data. I get that this is done to handle multiple checkboxes grouped together. However, what I don't see is anywhere I can transform that array value into `true` or `false` before handing it off to the MUI checkbox. it looks like typescript expects `field.checked` that comes back from `useField` to be a boolean rather than an array, so I'm not able to do any manipulation on that value without getting a typescript error.

Interestingly, if I check the "with MUI" checkbox once, I see an array with 1 value (`on`). If I click the checkbox again, then I get an array with no values in it, but the checkbox UI does not update. So it looks like the checkbox data is getting properly updated, but the MUI checkbox can't deal with array data. 

I feel like I'm doing something stupid here, and would appreciate being shown the error of my ways.

Thanks in advance!

### Reproducible example

https://codesandbox.io/s/wizardly-https-bb7up6

And in case this isn't the right forum for this question/issue, I've also posted it to StackOverflow:
https://stackoverflow.com/questions/72393191/struggling-to-get-materialui-5-checkbox-to-work-with-formik-2

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.9
| React            | 17.0.2
| TypeScript       | 4.5.5
| Browser          | Chrome (Mac) 101.0.4951.64
| npm/Yarn         | 8.5.0
| Operating System | macOS 12.4

**Comment by saurabhcoded** [comment]
Is this bug resolved?
