### ISSUE TITLE
Whenever I try to update the value of an array of objects using useFormik, initialValues also gets updated.

### ISSUE THREAD

**Issue by shiraazAh** [jaredpalmer/formik#3582]
## Bug report

Whenever a user tries to update an array of objects using formik, both `formik.values` & `formik.initialValues` gets updated even though `enableReinitialize` is set to `false` .  To properly analyze and show the issue, I have created a codesandbox link : https://codesandbox.io/s/blissful-easley-iri3mr

### Current Behavior

When an array of objects is updated using formik, `formik.values` & `fomik.initialValues` gets updated.

### Expected behavior

When an array of objects is updated using formik, only `formik.values` should be updated  & `fomik.initialValues` shouldn't be updated.

### Reproducible example

https://codesandbox.io/s/blissful-easley-iri3mr

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.9
| React            | 18.0.0
| TypeScript       | -
| Browser          | any
| npm/Yarn         | 8.1.2
| Operating System | Windows

**Comment by JayKania** [comment]
Probably it's not an issue with formik. It's the way we are changing the values

`let newValue = [...formik.values.users];`

The above line will surely destructure the users array. However, objects inside the users array are still the same, meaning the new and old values point to the same objects (have the same reference).

Change it to

`let newValue = formik.values.users.map((user) => {
            return { ...user };
          });;`

**Comment by shiraazAh** [comment]
Oh okay, that answers the problem. Thanks, closing the issue.
