### ISSUE TITLE
Changing single input value as a user makes all inputs dirty (setting errors messages)

### ISSUE THREAD

**Issue by santospatrick** [jaredpalmer/formik#36]

**Comment by lewisblackwood** [comment]
+1 here.

Ideally, I'd like for `handleChange` to only validate and return errors for the field that's been changed. I'd then like all the form's values to be validated and any errors returned before `handleSubmit` is called.

**Comment by eonwhite** [comment]
To ensure you don't see error messages displayed on untouched fields, you want to check the `touched` value for that field when deciding whether to display the error message or not.

For example:

```
{errors.email && touched.email && <div>{errors.email}</div>}
```

@jaredpalmer I think it'd be good if we updated the examples to show the proper use of `touched`.

**Comment by lewisblackwood** [comment]
Oh rad, thanks @eonwhite!

**Comment by santospatrick** [comment]
touched helper is not working properly, or i am using it wrong?
```
const ContactForm = ({
  values,
  touched,
  handleChange,
  handleSubmit,
  isSubmitting,
  errors
})
...
<input id="nome" type="text" name="nome" value={values.nome} onChange={handleChange} placeholder="Nome *"/>
{errors.nome && touched.nome && <div>{errors.nome}</div>}
```

**Comment by eonwhite** [comment]
Be sure to add `onBlur={handleBlur}`, so that touched will get set when you lose focus on the input.
