### ISSUE TITLE
How to populate array with checkboxes?

### ISSUE THREAD

**Issue by Woile** [jaredpalmer/formik#360]
## How to populate array with checkboxes?

Hi, I'm wondering if it's possible to do this. 
I have 2 check-boxes, and every time one is checked, an array should be populated. I've been playing around, even tried the latest `FieldArray`, but I'm not sure I understand well how to use it, or even if it's for that purpose.

## Info
 
I am using `Formik` component with `render` method.
Something like:
```js
import React from 'react';
import { render } from 'react-dom';
import { Formik } from 'formik';


const App = () => (
  <div>
    <h1>My Form</h1>
    <Formik
      initialValues={{
        groups: [],
      }}
      onSubmit={values =>
        console.log(values)
        // Expected output would be something like:
        // {groups: ['admin', 'normal']}
      }
      render={props => (
        <form onSubmit={props.handleSubmit}>
          <input
            type="checkbox"
            name="groups.0"
            value="admin"
            onChange={props.handleChange}
            onBlur={props.handleBlur}
            checked={props.values.groups === 'admin'}
          />
          Admin
          <br/>
          <input
            type="checkbox"
            name="groups.1"
            value="normal"
            onChange={props.handleChange}
            onBlur={props.handleBlur}
            checked={props.values.groups === 'normal'}
          />
          Normal
          <br />

          <button type="submit" >
            Submit
          </button>
        </form>
      )}
    />
  </div>
);

render(<App />, document.getElementById('root'));
```

Here is an example: https://codesandbox.io/s/03pmmoo0kp

But what I really want is to have this as a result:
```js
{
  groups: ['admin', 'normal']
}
```
Is it possible doing something like that? What am I missing?

- Formik Version: `0.11-beta`
- OS: Debian unstable
- Node Version: ` node@v8.6.0`
- Package Manager and version: `yarn@1.3.2`

**Comment by Woile** [comment]
Okay, found a solution. I'm still wondering if it's the way to go:

```js
import React from 'react';
import { render } from 'react-dom';
import { Formik } from 'formik';


const App = () => (
  <div>
    <h1>My Form</h1>
    <Formik
      initialValues={{
        groups: [],
      }}
      onSubmit={values =>
        console.log(values)
        // Expected output would be something like:
        // {groups: ['admin', 'normal']}
      }
      render={props => (
        <form onSubmit={props.handleSubmit}>
          <input
            type="checkbox"
            onChange={(event) => {
              const value = event.target.checked ? 'admin' : ''
              props.setFieldValue('groups.0', value)
            }}
            checked={props.values.groups.includes('admin')}
          />
          Admin
          <br/>
          <input
            type="checkbox"
            onChange={(event) => {
              const value = event.target.checked ? 'normal' : ''
              props.setFieldValue('groups.1', value)
            }}
            checked={props.values.groups.includes('normal')}
          />
          Normal
          <br />

          <button type="submit" >
            Submit
          </button>
        </form>
      )}
    />
  </div>
);

render(<App />, document.getElementById('root'));
```

I don't like the idea of having an array with null elements as a result like `[null, 'normal']`

https://codesandbox.io/s/6wnxzvlo0r

**Comment by adamduncan** [comment]
Hey @Woile - I've dropped a demo of checkboxes and radio buttons over on another issue: https://github.com/jaredpalmer/formik/issues/363#issuecomment-359806276

Hopefully that helps with your use case

**Comment by Woile** [comment]
@adamduncan thanks! 
Looks like a great solution, I would've expect it to be a bit more straightforward, but it looks good

**Comment by adamduncan** [comment]
Yeah, agreed 🤞 Glad it's doable, but hopefully there's a simpler way to achieve it

**Comment by adamduncan** [comment]
@jaredpalmer - now v0.11 is released and `FieldArray`'s stable, is it possible to add examples of creating fieldsets of multiple radio and checkbox inputs please? Seems such a common feature of forms, but yet to see a definitive example in the docs. Thanks!

**Comment by davidrossjones** [comment]
@jaredpalmer Great library! 

I'm also trying to build a multi checkbox input linked to an array in values. What is the best way to do this with FieldArray? I have it working as a custom component but FieldArray feels like it should be the built-in way to achieve it.

I'm having difficulty with FieldArray since it doesn't pass children as a prop here: https://github.com/jaredpalmer/formik/blob/b72cf00cb218336f62a181eaef7d04a3ed4becab/src/FieldArray.tsx#L233

**Comment by elado** [comment]
I wrote an example for a checkbox array: https://codesandbox.io/s/o5pw1vx916

Which leads me to ask for `arrayHelpers.removeItem<T>(item: T)` that removes by item equality, not index.

**Comment by haris-aqeel** [comment]
I would like to do the same populate array using both Formik and Material UI
How it is possible

**Comment by Suryakaran1234** [comment]
> I would like to do the same populate array using both Formik and Material UI How it is possible

Have you found the Solution for doing this??? Please Tell me Too, I am facing the same issue. I have made a custom component (CheckBoxGroup) which renders a bunch of checkboxes. I am having trouble in setting them in checked state after I have fetched data from database.
Please anyone help me out.
I am using Formik and Material UI v5.

**Comment by johnrom** [comment]
@Suryakaran1234 there is an example of using Formik's Field component to manage checkboxes here:

https://codesandbox.io/s/intelligent-dirac-94hdnf?file=/index.js

To integrate with Material UI you would create a wrapper component which would map Formik's field props to Material UI, as demonstrated in the sandbox above.

Read more here: 

[Formik Docs: Checkboxes](https://formik.org/docs/examples/checkboxes)
[Formik Docs: Material UI](https://formik.org/docs/examples/with-material-ui)

**Comment by Suryakaran1234** [comment]
> @Suryakaran1234 there is an example of using Formik's Field component to manage checkboxes here:
> 
> https://codesandbox.io/s/intelligent-dirac-94hdnf?file=/index.js
> 
> To integrate with Material UI you would create a wrapper component which would map Formik's field props to Material UI, as demonstrated in the sandbox above.
> 
> Read more here:
> 
> [Formik Docs: Checkboxes](https://formik.org/docs/examples/checkboxes) [Formik Docs: Material UI](https://formik.org/docs/examples/with-material-ui)

Thank you so much, You Saved my life🤗
