### ISSUE TITLE
Is Formik still in active development?

### ISSUE THREAD

**Issue by derweili** [jaredpalmer/formik#3601]
I have not seen any new releases for one year.
The blog post anouncing the next version formik 3 alpha is about two years old. No update since then. 

So I'm wondering if formik is still in active development?

Are there any maintainers working at formik?

I liked using formik in the past but I don't want to build a new project on a abandoned library.

**Comment by javierguzman** [comment]
I was wondering about the same as I ran into this error "https://github.com/jaredpalmer/formik/issues/3252" and saw it was already around one year old. A pity.

**Comment by kelly-tock** [comment]
Same, am starting fresh on a project was have enjoyed formik. React hook form it is I guess

**Comment by Polyhistor** [comment]
I wouldn't use a library that has accepted to type it's values like this  and pushed to production:

```
export declare type FormikTouched<Values> = {
    [K in keyof Values]?: Values[K] extends any[] ? Values[K][number] extends object ? FormikTouched<Values[K][number]>[] : boolean : Values[K] extends object ? FormikTouched<Values[K]> : boolean;
};
```

It also rerenders unnecessarily  a lot of times! we've got Formik into production for over two years now and maintaining it has never been easy.

**Comment by carlosbensant** [comment]
Not even an update on Twitter:
- https://twitter.com/tyteen4a03/status/1549711931476512769
- https://twitter.com/drag137/status/1514968995883061248
- https://twitter.com/KasleyNorman/status/1529578674961645568
- https://twitter.com/dolfbarr/status/1521163088237674496
- https://twitter.com/sseraphini/status/1557040724209799171
- https://twitter.com/Astro_Nate_/status/1507368846235156483

**Comment by nikhilag** [comment]
We built https://github.com/witbybit/react-recoil-form to maintain the simplicity of controlled components while rendering only the fields that actually change. We use it for our internal projects and we open sourced it in the hope that others might find it useful too. Personally, I found formik API to be nicer than react-hook-form. I switched to react-hook-form but was unable to use it beyond a certain point - react-recoil-form so far has proven to be a good decision for us in terms of simplicity and flexibility.

**Comment by crutchcorn** [comment]
In light of Formik's lack of development updates, I started writing my own form library that I just launched a v1 of:

https://github.com/crutchcorn/houseform

https://houseform.dev

I'd love to hear anyone's feedback on it (in the project's GitHub issues) good or bad.

**Comment by probablyup** [comment]
Yes it's alive

**Comment by tyteen4a03** [comment]
Looks like this project has once again become dead.

**Comment by quantizor** [comment]
Just busy and juggling many things, I typically do less OSS in the summer months
  
  
  
  
  
  
  

  
  
>
