### ISSUE TITLE
Re-run validations on `resetForm`

### ISSUE THREAD

**Issue by rpowelll** [jaredpalmer/formik#361]
## Bug, Feature, or Question?

When `resetForm` is called, it should be possible to also re-run the form's validations. Whether this should be an optional argument to `resetForm`, or some automatic behaviour tied to `isInitialValid` I'm not sure.

## Current Behavior

Upon resetting my form, there's no way to run validations against the new values./

## Desired Behavior

I can run validations against the form's new values.

## Suggested Solutions

There's a few possible solutions:

- Allow `resetForm` to take an optional second argument to indicate whether to run validations
- Expose a `performValidation` function or something similar as an escape hatch
- If `isInitialValid` is false, resetting the form should should also cause validations to be re-run

## Info
 

- Formik Version: 0.11.0.beta.1
- OS: macOS 10.13.2
- Node Version: 9.3.0
- Package Manager and version: npm 5.6.0

**Comment by jaredpalmer** [comment]
I think this make sense. Fn should be called validate() and exposed via props.

**Comment by jaredpalmer** [comment]
This has been shipped in v0.11. You can now call `validateForm()`

**Comment by phuongthuan** [comment]
@jaredpalmer 
I'm caring about this issue.
Could you please give me some example? 

I want to reset validation after form was submitted.

```
onSubmit={async (values, { setSubmitting, setStatus, setErrors, resetForm }) => {
            const { title, achievement, plan, description, comment } = values;

            let issues = [];
            if (isEmpty(values.issues)) {
              issues = []
            } else {
              issues = values.issues.map(issue => ({ id: issue }));
            }

            try {
              await createDailyReport({
                variables: {
                  title,
                  achievement,
                  issues,
                  plan,
                  description,
                  comment
                }
              });

              resetForm({});
              setStatus({success: true})
            } catch (error) {
              setStatus({success: false});
              setSubmitting(false);
              setErrors({submit: error.message})
            }
          }}
```

**Comment by phuongthuan** [comment]
@jaredpalmer This is exactly the issue that I'm facing.
My code like this:

```

         onSubmit={async (values, { setSubmitting, setStatus, setErrors, resetForm }) => {
            const { title, achievement, plan, description, comment } = values;

            let issues = [];
            if (isEmpty(values.issues)) {
              issues = []
            } else {
              issues = values.issues.map(issue => ({ id: issue }));
            }

            try {
              await createDailyReport({
                variables: {
                  title,
                  achievement,
                  issues,
                  plan,
                  description,
                  comment
                }
              });

              resetForm({});
              setStatus({success: true});

            } catch (error) {
              setStatus({success: false});
              setSubmitting(false);
              setErrors({submit: error.message})
            }
          }}
```

I want to re-run validations after submitting the form. How can we do that?

Could you please give me an example?

**Comment by andrewctdev** [comment]
Not sure whether I'm doing this wrong, but `validateForm` doesn't capture the state of the form right after reset. So you cannot do chained reset & validate in one method. Also, reseting the form doesn't trigger the validation defined by default with `validateOnChange` and `validateOnMount`.
