### ISSUE TITLE
Checkbox group

### ISSUE THREAD

**Issue by hanspoo** [jaredpalmer/formik#363]
Thanks for the project, ¿ Do you have some sample code or component to handle a checkbox group ?

Thanks,
Hans

**Comment by adamduncan** [comment]
Would be super helpful to see an example of a radio group documented also 👌

**Comment by adamduncan** [comment]
Here's my take on how to get single checkbox, checkbox group and radio group inputs working with the current version:
https://codesandbox.io/s/q4qx876j

They're designed to be super generic primitives that could be reworked for other components. These components use a mix of `children` and `component` props, but could be reworked to use `render` props if preferred.

Hope this helps! 👍

**Comment by hanspoo** [comment]
Really cool, i tried it at sandbox, and works very good, thank you, by the way, i came from java frameworks background and its normal to see libraries of widgets to help developers, here in JS it seems that everything must be done manually, with some bare bones primitives.

**Comment by pgrekovich** [comment]
@hanspoo in Formik v11 will be added component [FieldArray](https://github.com/jaredpalmer/formik/blob/next/README.md#fieldarray), it seems like it will solve this problem

**Comment by hanspoo** [comment]
It seems the solution, thank you, i will close the issue and will move to 1.1.

**Comment by elado** [comment]
I wrote an example for a checkbox array using FieldArray: https://codesandbox.io/s/o5pw1vx916

**Comment by nicoqh** [comment]
@adamduncan Your example mutates the initial values, so the form can never be dirty. Here's one way to fix it:

```
let valueArray = [...this.props.value] || []
```

@elado I think you forgot to add the `onBlur` prop to your `<input>`.

Thank you both for the examples! Really helpful.

**Comment by adamduncan** [comment]
Good point @nicoqh - updated my old example in case anyone stumbles across it in future. @elado's FieldArray approach is great 👌

**Comment by chead2344** [comment]
I wrote a simple example using hooks and context that works well in my project https://codesandbox.io/s/formik-checkbox-group-40w0y
