### ISSUE TITLE
setDeep changes two-level deep objects in-place

### ISSUE THREAD

**Issue by bxt** [jaredpalmer/formik#364]
## Bug

React state is changed in-place if you change deeply (more than 2 levels) nested values.

## Current Behavior

A call like this:

    const obj = { x: 'y', twofoldly: { nested: { value: 'a' } } };
    setDeep('twofoldly.nested.value', 'b', obj)`

changes the object at `obj.twofoldly.nested` in-place. This means the react state is changed in-place if you have a field with a name like `twofoldly.nested.value`.

In my case I have an equality check in `componentWillReceiveProps` of the form component with `isEqual(nextProps.values, this.props.values)` which now always returns `true`.

Add a test case to `test/utils.test.tsx` like this

    it('updates twofoldly nested value', () => {
      const obj = { x: 'y', twofoldly: { nested: { value: 'a' } } };
      const newObj = setDeep('twofoldly.nested.value', 'b', obj);
      expect(obj.twofoldly.nested === newObj.twofoldly.nested).toEqual(false); // fails, same object still
      expect(obj).toEqual({ x: 'y', twofoldly: { nested: { value: 'a' } } }); // fails, it's b here, too
      expect(newObj).toEqual({ x: 'y', twofoldly: { nested: { value: 'b' } } }); // works ofc
    });

to see the problem.

(CCing @klis87, thank you for adding the nesting feature ☺️🎉  it is really helpful)

## Desired Behavior

There should be a new object in the nested state instead of the old nested object with a changed value. The above unit test should pass.

## Suggested Solutions

Create a proper copy of the objects.

## Info
 
- Formik Version: v0.11.0-beta.1 (`setDeep` was added in 3a8e620dc56f0ac14dd9796795fd5da17853fb40 / #207)
- OS: macOS 10.13.2
- Node Version: v8.1.4
- Package Manager and version: yarn 1.3.2

**Comment by ecoleman** [comment]
If your cool using lodash cloneDeep method, I can submit a tiny pull request with the above test and the code fixed

**Comment by bxt** [comment]
Thank you for the fix @ecoleman ! 🎉
