### ISSUE TITLE
The best Form Library for react is abandoned?

### ISSUE THREAD

**Issue by v3ss0n** [jaredpalmer/formik#3663]
I was surprised with the popularity of react  and formik i thought this would be well maintained but  this got abandoned.
Can someone step-up and maintain? Would be nice if there are sponsors too.

**Comment by v3ss0n** [comment]
Thanks a lot, I was looking around, now our form code is getting messy

**Comment by Farooqkhanderghami** [comment]
Farmik with yup is the best validation

**Comment by crutchcorn** [comment]
In light of Formik's lack of development updates, I started writing my own form library that I just launched a v1 of:

https://github.com/crutchcorn/houseform

https://houseform.dev

I'd love to hear anyone's feedback on it (in the project's GitHub issues) good or bad.

**Comment by crutchcorn** [comment]
Related issues: #3601, #3613

**Comment by sagarrajak** [comment]
Hey i am working on fork, will be ready in few months.

**Comment by v3ss0n** [comment]
sounds good

**Comment by probablyup** [comment]
Not dead, many improvements coming

**Comment by dvins** [comment]
> Not dead, many improvements coming

Interesting, but too little too late? As with others migrated from Formik to React Hook Form (and similarly off of [TSDX](https://github.com/jaredpalmer/tsdx) after nearly two years with literally no communication or even patches.  :-(

**Comment by probablyup** [comment]
All I can do is tell you I have added formik to my maintainer roster and my employer has gifted me the time to improve the library as part of my workload. 

Take a look at my track record ¯\_(ツ)_/¯ 

Not going to try to convince anyone to stay or return, judge the work on its own and do what you will.

**Comment by dvins** [comment]
@probablyup Welcome news certainly for those who have not yet migrated to other alternatives. Love your work, we're big fans here of [Styled Components](https://github.com/styled-components/styled-components)!
