### ISSUE TITLE
Navigation Bug on documentation website

### ISSUE THREAD

**Issue by J5kinner** [jaredpalmer/formik#3673]
### Current Behavior

When navigating away from https://formik.org/docs/guides/typescript using the left hand side menu the website redirects to the NPM package website. 
Meaning that once you open the typescript link, you can't access the other formik guides or examples without manually resetting the URL to the home formik website.

### Expected behavior

Once you click on the typescript guide you should be able to click on the next guide or example in the dropdown menu's on the left.

### Reproducible example

Attempt to click any other guide or example from this [https://formik.org/docs/guides/typescript](https://formik.org/docs/guides/typescript ) brings you to the NPM package site.

### Suggested solution(s)

Fix the broken navigation from the typescript guide site which is currently defaulting to the NPM package website at the moment.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |
| React            |
| TypeScript       |
| Browser          | FireFox (latest), Chrome (latest)
| npm/Yarn         |
| Operating System | MacOS

**Comment by vennilamahalingam** [comment]
This is not reproducible. Please attach a video reference.

**Comment by J5kinner** [comment]
Seems like they must've fixed it in the last year or so 👍
