### ISSUE TITLE
allow dot path & bracket path for setFieldValue, setFieldTouched, & setFieldError

### ISSUE THREAD

**Issue by timc13** [jaredpalmer/formik#368]
## Bug
The exposed interface for `setFieldValue`, `setFieldTouched`, & `setFieldError` do not allow dot path names
## Current Behavior
only first level field names can be set.
## Desired Behavior
allow field names that contain dot path as well as bracket path.
## Suggested Solutions
change the `keyof Values` type for the field argument to `string`
## Info
 

- Formik Version: 0.11.0-beta.1
- OS: MacOS High Sierra 10.13.2
- Node Version: 8.9.4
- Package Manager and version: npm 5.6.0

**Comment by timc13** [comment]
along the same vein, the values in type `FormikTouched` should not be typed to boolean, as this only allows us to access top level touched fields.
(e.g. `touched.parent`, but not `touched.parent.child`)

**Comment by sergii-azizov** [comment]
Hello, guys when do you plan to do it ?

**Comment by sergii-azizov** [comment]
actually, this is resolved and this improvement can be closed :)

<img width="817" alt="screen shot 2018-01-29 at 8 52 30 pm" src="https://user-images.githubusercontent.com/33128587/35528389-601a3454-0536-11e8-84ea-2d16587f705b.png">

<img width="891" alt="screen shot 2018-01-29 at 8 48 38 pm" src="https://user-images.githubusercontent.com/33128587/35528219-de4e8f74-0535-11e8-82c5-26dbcb3962d8.png">

**Comment by timc13** [comment]
This has been working in javascript, but not Typescript.  In Typescript, we have to cast to any:

`setFieldTouched('property.child' as any)`

I'm just proposing that we change the signature of `FormikActions<Values>` from:
```
setFieldValue: (field: keyof Values, value: any) => void;
setFieldError: (field: keyof Values, message: string) => void;
setFieldTouched: (field: keyof Values, isTouched?: boolean) => void;
```
to:
```
setFieldValue: (field: string, value: any) => void;
setFieldError: (field: string, message: string) => void;
setFieldTouched: (field: string, isTouched?: boolean) => void;
```

**Comment by jaredpalmer** [comment]
@weswigham is there is good way to do other than just a string?

**Comment by weswigham** [comment]
I'd just add a second overload that takes a string argument for when you pass something that isn't a direct key. There's no way in the typesystem today to concatenate strings, so there's no way to represent a full object path string as a type.

**Comment by timc13** [comment]
please do the same for `FormikTouched<Values>`.  same problem - we can't access anything beyond top level values in `touched`
