### ISSUE TITLE
Yup validation dependency has no typings

### ISSUE THREAD

**Issue by alex-sherwin** [jaredpalmer/formik#37]
Formik is written in TS (great), but your only validation option is `yup`, which has no typings in the main repo and there is no externally provided `@types/yup` package either.

Makes it difficult to try and adopt Formik while staying purely TS.

**Comment by jaredpalmer** [comment]
correct. I have already raised this issue. https://github.com/jquense/yup/issues/91

**Comment by jaredpalmer** [comment]
Yup is no longer required. FYI

**Comment by Andreyco** [comment]
How? @jaredpalmer could you please elaborate on your last statement? Is it possible to inject validation lib of choice?

**Comment by jaredpalmer** [comment]
Since 0.8, `validationSchema` is optional. You can now use [`validate`](https://github.com/jaredpalmer/formik#validate-values-values-props-props--formikerrorvalues--promiseany) option for custom async and sync validation.

**Comment by Andreyco** [comment]
Awesome! Nothing stopping me from using Formik at all!
