### ISSUE TITLE
Initial values are reinitialized only once.

### ISSUE THREAD

**Issue by Helios69** [jaredpalmer/formik#3712]
## Bug report
I have a form, and the when I enter the screen, the data is fetched and the formik initialState is reinitialized. But if I make changes and exit the page, and then come back, the initialState is not reinitialized, even though the API request is made.

### Expected behavior

The form should be reinitialized every time when the initialValue state (stored in useState state) changes.
P.S. I'm using react native

### Additional context

```
const [initialValues, setInitialValues] = useState({
    consultationDuration: null,
    break: {
      enabled: false,
      start: '',
      end: ''
    },
    workingDays: defaultWeekdays,
    offlineConsultation: {
      enabled: false,
      isFree: false,
      price: 0
    },
    videoConsultation: {
      enabled: false,
      realtime: false,
      price: 0
    },
    iban: null,
    allowEmailNotifications: false,
    allowSmsNotifications: false
  });

  const _getUserDetails = useGetRequest({
    url: USER_DETAILS,
    headers: { Authorization: `Bearer ${token}` }
  });

  useEffect(() => {
    const getUserDetails = async () => {
      try {
        const { response } = await _getUserDetails.request({});
        const { clinics, allowEmailNotifications, allowSmsNotifications, iban } = response;
        const activeClinic = clinics.find(({ doctorClinicId }) => doctorClinicId === doctorId);
        if (activeClinic) {
          const {
            consultationDuration,
            lunchFrom,
            lunchTo,
            days,
            offlineConsultation,
            videoConsultation
          } = activeClinic;
          setInitialValues({
            consultationDuration: `${consultationDuration} min`,
            break: { enabled: !!lunchFrom && !!lunchTo, start: lunchFrom, end: lunchTo },
            workingDays: days,
            iban,
            allowEmailNotifications,
            allowSmsNotifications,
            offlineConsultation,
            videoConsultation
          });
        }
      } catch (error) {
        console.log(error);
      }
    };

    if (isFocused) {
      getUserDetails();
    }
  }, [isFocused]);

  const { values, setFieldValue, getFieldProps } = useFormik({
    initialValues,
    enableReinitialize: true,
    validationSchema,
    onSubmit: (values) => {
      console.log(values);
    }
  });
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.9
| React  Native         | 0.68.2
| TypeScript       | no
| Browser          | iOS device
| npm/Yarn         | npm
| Operating System | MacOS

**Comment by pachuka** [comment]
@Helios69 - this is not a bug AFAIK. The `onSubmit` has the `formikBag` which includes the `resetForm` callback that you can invoke at the end of your submission logic -> https://formik.org/docs/api/formik#onsubmit-values-values-formikbag-formikbag--void--promiseany.

Details on what happens during submission - https://formik.org/docs/guides/form-submission

**Comment by probablyup** [comment]
You can also remount the form component using `key` tied to the most recent version of the backing code. It's an easy shortcut.
