### ISSUE TITLE
Formik failed on build

### ISSUE THREAD

**Issue by Leyksnal** [jaredpalmer/formik#3727]
### Error
> react-app-rewired build

```
Creating an optimized production build...
Failed to compile.

Attempted import error: 'LowPriority' is not exported from 'scheduler' (imported as 'LowPriority').
```
`package.json
`  
```
"scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "eject": "react-scripts eject"
  }
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |"^2.1.4"
| React            |"^16.13.1"
| TypeScript       |
| Browser          |
| npm/Yarn         |Yarn&npm
| Operating System |macOS

**Comment by probablyup** [comment]
This appears to be an issue with out of sync versions of React dependencies

**Comment by erassynathingo** [comment]
> 

was this solved?
