### ISSUE TITLE
Incorrect dirty handling

### ISSUE THREAD

**Issue by probablyup** [jaredpalmer/formik#3728]
At the moment `dirty` is a memoized field that compares the current values to the initial values. The thing is if someone ticks a checkbox and then unticks it, the form is still dirty but the dirty flag would reset to `false` because the values now match again.

**Comment by Jittojoyes98** [comment]
Anyways of fixing this.Can we have a work around for Onchange ?

**Comment by olzhas-kalikhan** [comment]
have you considered "touched" state, I think the logic that if initialValues = currentValues  then isDirty =true is correct

https://formik.org/docs/api/formik#touched--field-string-boolean-

**Comment by probablyup** [comment]
> have you considered "touched" state, I think the logic that if initialValues = currentValues then isDirty =true is correct
> 
> https://formik.org/docs/api/formik#touched--field-string-boolean-

Hmm, you might be right. As long as it resets with `enableReinitialize` that would work.
