### ISSUE TITLE
Cannot find "/dist/formik.umd.production.min.js" in formik@2.2.9

### ISSUE THREAD

**Issue by JacobWeisenburger** [jaredpalmer/formik#3751]
the cdn method of getting started from the docs is not working:

https://formik.org/docs/overview#cdn
```html
<script src="https://unpkg.com/formik/dist/formik.umd.production.min.js"></script>
```

1. go to: https://unpkg.com/formik@2.2.9/dist/formik.umd.production.min.js
2. see: `Cannot find "/dist/formik.umd.production.min.js" in formik@2.2.9`

**Comment by probablyup** [comment]
Resolved via https://github.com/jaredpalmer/formik/pull/3523
