### ISSUE TITLE
TypeError when calling handleSubmit in react-native

### ISSUE THREAD

**Issue by Shurelia** [jaredpalmer/formik#376]
## Current Behavior
The recommended usage of formik in react native is: `<Button onPress={props.handleSubmit} />`. However, when using typescript, the type of event that `handleSubmit` accepts is different than what react-native's `onPress` generates.

## Desired Behavior
Formik's `handleSubmit` should take a `GestureResponderEvent` in addition to `React.FormEvent<HTMLFormElement>`.

## Suggested Solutions
This branch fixes this issue: https://github.com/Shurelia/formik/tree/handleSubmit-fix
Unfortunately, there is a typings conflict between `@types/node` and `@types/react-native` which prevents the build. Since the only type used from node was `process`, I've manually declared that as any and removed `@types/node`. Not an elegant solution, and I'd be open to working on it more if the maintainers are okay with removing `@types/node` from the project (and perhaps manually declaring `process`?).

## Info
- Formik Version: 0.10.5
- OS: Windows 10
- Node Version: 9.3.0
- Package Manager and version: yarn 1.3.2
- Typescript: 2.6.2
- react: 16.2.0
- react-native: 0.51.0

**Comment by jaredpalmer** [comment]
Yeah this is legit. Hmmmmm. I think it may be time for Formik-native. In the mean time you can call submitForm()

**Comment by jaredpalmer** [comment]
I got stuck there too when trying to support React Native and TypeScript. I’m cool with dropping types/node if this works.

**Comment by Shurelia** [comment]
Thanks for the tip on `submitForm()`! I put in a PR anyways (#379), as it seemed an easier fix than writing new documentation to explain why submitForm should be called instead.

As a side note, I'm really digging this library. Thanks for all the hard work! This has solved a lot of the issues I was having with redux-form, and the ease of integration with react native has made it a joy to work with.

**Comment by brianjd** [comment]
I see #379 was backed out (Re: #421).  What is the current solution?

**Comment by wsdt** [comment]
For all coming here: The issue seems to be still open. 
If you simply want to remove the warning you can cast your object. It's by far not the cleanest solution, but it's better than nothing. 

`onPress={handleSubmit as any}`

**Comment by vitalyiegorov** [comment]
Any valid solution to this issue? @jaredpalmer

**Comment by vitalyiegorov** [comment]
@jaredpalmer Any valid solution for correct typing in react-native?

**Comment by ianmartorell** [comment]
TypeScript is supported and React Native is supported but both at the same time aren't? 🤔

**Comment by patgoley-tts** [comment]
Any update on this issue? This makes it feel like React Native was largely an afterthought for Formik and not officially supported. Casting things to `any` is not a solution and can easily lead to bugs in the future.

**Comment by Alek5andr** [comment]
Still is the issue.
"formik": "^2.2.9",
"react-native": "0.70.5"

**Comment by macszl** [comment]
I can confirm that this is still an issue.
