### ISSUE TITLE
useFormik enableReinitialize  prop emits infinite loop

### ISSUE THREAD

**Issue by cayolegal1** [jaredpalmer/formik#3778]
## Bug report

Enable reinitialize prop provoque infinite loop

### Current Behavior
When I put an initial values initializer enter into infinite loop

The function that set the initial values
<img width="573" alt="Screenshot 2023-05-23 at 13 25 26" src="https://github.com/jaredpalmer/formik/assets/73796018/9ef2cff5-cb15-40f8-807e-af4e9fe0c3bf">

### Expected behavior
It should accept an initializer to set the initial values

### Reproducible example
Video example
https://github.com/jaredpalmer/formik/assets/73796018/8262314b-95af-4338-b875-b497dc486b01

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | ^2.2.9
| React            | 18.2.0
| TypeScript       | x
| Browser          | Google Chrome
| npm/Yarn         | npm
| Operating System | MAC OS

**Comment by probablyup** [comment]
I think this is fixed now in latest?
