### ISSUE TITLE
[Next] Nested FieldArrays and setTouched not working together

### ISSUE THREAD

**Issue by rovansteen** [jaredpalmer/formik#378]
## Bug, Feature, or Question?
Bug

## Current Behavior
When you have nested `FieldArrays`, let's say the following path: `questions.0.values.0.label` where `questions` and `values` are the arrays and `label` is a regular input field. When `onBlur` is invoked on label, it wants to touch the path. But at that point (due to changing the `values` array) the current touched state is:
```js
questions: 0: {form_question_type_id: true, values: true}
```

which causes the following error in `setDeep`:
```
Uncaught TypeError: Cannot create property '0' on boolean 'true'
```
which happens on the last line of this method:
https://github.com/jaredpalmer/formik/blob/next/src/utils.ts#L69

## Desired Behavior
It should update the touched state to a deep nested state like this:
```js
questions: 0: {form_question_type_id: true, values: { label: true }}
```

## Suggested Solutions
I'm not sure I understand the current implementation of `setDeep`. Why not just clone the object and use something like https://github.com/kalmbach/bury?

## Info
 

- Formik Version: 0.11.0-beta.1 
- OS: Mac OS High Sierra
- Node Version: v9.4.0
- Package Manager and version: Yarn v1.3.2

**Comment by davidhenley** [comment]
I opened this same issue a while ago. Still no response. My one problem with Formik@next right now.

**Comment by jaredpalmer** [comment]
Damn wish I knew about bury earlier. Will have to check this out more detail

**Comment by timc13** [comment]
why not stick with lodash and use [set](https://lodash.com/docs/4.17.4#set)  which works for bracket notation AND dot notation...

**Comment by timc13** [comment]
i believe this is a result of using dot notation to access array items.

i am using bracket notation, and the array field gets completely replaced with a boolean.
See https://github.com/jaredpalmer/formik/pull/362

**Comment by timc13** [comment]
awww, what was wrong with my PR? =X

**Comment by jaredpalmer** [comment]
Awww I'm sorry man. I was on a grind and just missed this. Agh.

**Comment by a-tarasyuk** [comment]
@jaredpalmer Hi. 

I noticed that `torched` and `errors` has a different data structure and after remove an item from `values` in `touched` property is not deleted. There is [`commit`](https://github.com/jaredpalmer/formik/commit/b32ebfd3f294996f88634bdaa9574f158274bb49#diff-7d037a4310f1022dee96554929bd14b3L64) where was removed `setFieldTouched`.

```
"values": {
    "email": "",
    "firstName": "",
    "lastName": "",
    "emails": [
      "test",
      ""
    ]
  },
  "errors": {
    "firstName": "First name is required.",
    "lastName": "Last name is required.",
    "emails": [
      null,
      "emails[1] is a required field"
    ],
    "email": "Email is required!"
},
"touched": {
    "email": true,
    "firstName": true,
    "lastName": true,
    "emails": {
      "0": true,
      "1": true,
      "2": true
    }
}
```

There are two elements in `values` and `errors` and three in `touched`. [**Fiddle**](https://codesandbox.io/s/qkplkkw6q9)  

1. Add several items 
2. Click Submit 
3. Remove one of them
4. Add new item

You will see that new item has an error due to `touched`. Is there any way to avoid this?

**Comment by jaredpalmer** [comment]
Working on a fix now.

**Comment by davidhenley** [comment]
This makes me happy. I can wait to merge my form branch into master!!

**Comment by jaredpalmer** [comment]
I figured it out! Will open a PR

**Comment by eferrervaughn** [comment]
I still get the error, when I leave the text box. Do I have to do something in code to dodge this error:

formik.es6.js:5556 Uncaught TypeError: Cannot create property '0' on boolean 'true'

Here is a code snippet:

`        <FieldArray
          name="friends"
          render={arrayHelpers => (
            <Form>
              <h3>Name</h3>
              <input
                name="name"
                type="text"
                value={values.name}
                onChange={handleChange}
                onBlur={handleBlur}
              />
              {values.friends && values.friends.length > 0 ? (
                values.friends.map((friend, index) => (
                  <div>
                    <MySelect
                      name={`friends.${index}.type`}
                      value={`friends.${index}.type`}
                      onChange={setFieldValue}
                      current={{ curVal: values.friends, index }}
                      options={[
                        { value: "single_text", label: "Single Line Text" },
                        { value: "multi_select", label: "Multi Select" }
                      ]}
                      onBlur={setFieldTouched}
                    />

                    {
                      values.friends[index] &&
                      <Field name={`friends.${index}.name`} />`

**Comment by sadi304** [comment]
@eferrervaughn any update? this issue is still occurring

**Comment by eferrervaughn** [comment]
It's good for me feel free to close

**Comment by sadi304** [comment]
@eferrervaughn no, what i meant is that this is also happening in my code, did you solve it? :p

**Comment by johncmunson** [comment]
I'm also running into this error. Any updates?

**Comment by slightlytyler** [comment]
Running into this as well on v1 and v2 and I'm noting using a `FieldArray`, just an array value. Thinking this unsolved @jaredpalmer

**Comment by slightlytyler** [comment]
Not sure how to handle this situation tbh, maybe just encourage using `resetForm` in these cases rather than `setFieldValue`? The error that occurs is useless atm

**Comment by slightlytyler** [comment]
For those looking for a solution I was doing something like:
```js
// base on some condition I either
setFieldValue('text', '');
// or
setFieldValue('text', { default: '', keys: [] });
```
I was changing the shape of a field value which was causing the `touched` functionality to bork. After filling out `text` as a string and toggling it to the the object shaped formik's `values` and `touched` shape no longer match. 

The solution is to use `resetForm` instead
```js
resetForm(prevValues => ({ ...prevValues, text: '' });
// or
resetForm(prevValues => ({ ...prevValues, text: { default: '', keys: [] } });
```

**Comment by jaredpalmer** [comment]
@slightlytyler yes. Formik assumes that you keep you shape identical with respect to the path names. So in a nested situation if you go from a array to a value touched behavior could be off. you should indeed reset the form.

**Comment by jaredpalmer** [comment]
I don’t think this is a bug, but it is a contract that we should document more explicitly.

**Comment by elvisguillen** [comment]
I was getting this error as well when using a custom slider input with setFieldValue and then typing and click out of a seperate empty Field or FastField component. Seems like the touched values were definitely off between array and value. 

I fixed the issue and eliminated the error on my end by using a custom input component instead of Formik's Field or FastField components alongside my custom slider.

Old Input:
```
<FastField
  name={`result[${index}].value[0]`}
  className='form-control'
  onChange={handleChange}
/>
```

New Input:

```
<input
  name={`result[${index}].value[0]`}
  className='form-control'
  onChange={handleChange}
  type='text'
  value={values.result[index].value[0]}
/>
```

**Comment by arvinsim** [comment]
@elvisguillen So is your structure an array of array items? Trying to understand why you put `value[0]`.

@jaredpalmer Is the documentation updated? Trying to find out how touched is being handled for an array of objects.
