### ISSUE TITLE
The type of `setFieldValue` seems incorrect.

### ISSUE THREAD

**Issue by NagaiKoki** [jaredpalmer/formik#3807]
## Bug report
The following Eslint error appeared in the `setFieldValue` function when updating to [version 2.3.2](https://github.com/jaredpalmer/formik/releases/tag/formik%402.3.2) of formik.

````
Avoid referencing unbound methods which may cause unintentional scoping of `this`.
If your function does not access `this`, you can annotate it with `this: void`, or consider using an arrow function instead.eslint@typescript-eslint/ unbound-method
````

When I look at the `FormikHelpers` types, though, they were defined as follows,
```ts
setFieldValue(field: string, value: any, shouldValidate?: boolean): Promise<void | FormikErrors<Values>>;.
```

However, looking at the implementation, I think the correct type is

```ts
setFieldValue: (field: string, value: any, shouldValidate?: boolean) => Promise<void | FormikErrors<Values>>;
````

Is this type correct?

### Current Behavior
![スクリーンショット 2023-05-29 14 32 11](https://github.com/jaredpalmer/formik/assets/50698194/731f7f04-0282-457c-855b-ae2b4f54a093)

```ts
export interface FormikHelpers<Values> {
    // ...
    setFieldValue(field: string, value: any, shouldValidate?: boolean): Promise<void | FormikErrors<Values>>;
     // ...
}
```

### Expected behavior

```ts
export interface FormikHelpers<Values> {
    // ...
    setFieldValue: (field: string, value: any, shouldValidate?: boolean) => Promise<void | FormikErrors<Values>>;
  // ...
}
```

### Reproducible example
* access `formik.setFieldError` and eslint [@typescript-eslint/unbound-method](https://typescript-eslint.io/rules/unbound-method) get enabled

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.4.0
| React            | 18.2.0
| TypeScript       | 5.0.0
| Browser          |
| npm/Yarn         | yarn
| Operating System |

**Comment by probablyup** [comment]
We can fix this, but it's probably also better to not check types that aren't yours with https://www.typescriptlang.org/tsconfig#skipLibCheck

**Comment by klarstrup** [comment]
I face this issue with `skipLibCheck` enabled.

**Comment by probablyup** [comment]
Fixed in https://github.com/jaredpalmer/formik/releases/tag/formik%402.4.1, thanks for contributing!

**Comment by NagaiKoki** [comment]
@probablyup Thank you!
