### ISSUE TITLE
FieldArray regression due to shouldComponentUpdate changes

### ISSUE THREAD

**Issue by xconverge** [jaredpalmer/formik#3812]
### Current Behavior

Parts of fieldarray don't update correctly after https://github.com/jaredpalmer/formik/pull/3784

### Expected behavior

Fields update correctly

### Reproducible example

https://codesandbox.io/s/formik-example-forked-zffjus

### Additional context

For now I just added this to use the same behavior from previous versions

```
shouldUpdate={() => true}
```

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.2.10+
| React            |
| TypeScript       |
| Browser          |
| npm/Yarn         |
| Operating System |

**Comment by probablyup** [comment]
Fixing this in the next release, sorry about that.

**Comment by lancemcmuffin** [comment]
@probablyup any ETA on this? Unfortunately both this and #3796 broke multiple forms within our apps

**Comment by xconverge** [comment]
> @probablyup any ETA on this? Unfortunately both this and #3796 broke multiple forms within our apps
You can see the status here, it looks all in progress and moving quickly
https://github.com/jaredpalmer/formik/pull/3814

**Comment by probablyup** [comment]
https://github.com/jaredpalmer/formik/releases/tag/formik%402.4.1
