### ISSUE TITLE
broken website links

### ISSUE THREAD

**Issue by adjenks** [jaredpalmer/formik#3827]
These links are broken in the docs:

Page: All pages
Link Text: Edit this page on GitHub
href: https://github.com/formik/formik/edit/master/docs/api/field.md

Page: https://formik.org/docs/api/field
Link Text: FieldInputProps
href: https://formik.org/docs/api/field#fieldinputprops

Page: https://formik.org/docs/api/field
Link Text: FieldMetaProps
href: https://formik.org/docs/api/field#fieldmetaprops

**Comment by probablyup** [comment]
Care to submit a fix PR? The first one is probably because the primary branch is `main` now

Second one should now point to → https://formik.org/docs/api/useField#fieldinputpropsvalue
Third one should now point to → https://formik.org/docs/api/useField#fieldmetapropsvalue

**Comment by shouldnt** [comment]
can I submit a PR for this?

**Comment by probablyup** [comment]
Please do
