### ISSUE TITLE
Add a getFieldValueSetter props to avoid React Native boilerplate

### ISSUE THREAD

**Issue by jay1337** [jaredpalmer/formik#385]
## Bug, Feature, or Question?
Feature

## Current Behavior
To use formik properly with React Native we need to define a custom Component and use setFieldValue in a wrapping function (to avoid arrow functions). This is a lot of boilerplate.

Cf https://github.com/jaredpalmer/formik#avoiding-new-functions-in-render

## Desired Behavior
Enable this use of formik:

```
// Formik x React Native example
import React from 'react';
import { Button, TextInput, View } from 'react-native';
import { withFormik } from 'formik';

const enhancer = withFormik({
  /*...*/
});

const MyReactNativeForm = props => (
  <View>
    <TextInput
      onChangeText={this.props.getFieldValueSetter('email')}
      value={props.values.email}
    />
    <Button onPress={props.handleSubmit} title="Submit" /> //
  </View>
);

export default enhancer(MyReactNativeForm);
```

## Suggested Solutions

`withFormik` could pass a new prop called `getFieldValueSetter` to the React component.
This would be a function that takes a field name and return a function, a value setter for this field. A setter would be created during the first call and saved in a cache map by formik. Next calls would return the cached function. It would be something like that:

```
getFieldValueSetter = (fieldName) => {
    if (!this.valueSetterCacheMap) valueSetterCacheMap = {};
    return valueSetterCacheMap[fieldName] || (valueSetterCacheMap[fieldName] = (value) => {
        this.setFieldValue(fieldName, value);
    });
}
```

Doc should be updated.

## Info
 

- Formik Version: not relevant
- OS: not relevant
- Node Version: not relevant
- Package Manager and version: not relevant

**Comment by jaredpalmer** [comment]
getFieldValueSetter is pretty long to type, but very explicit.

i wonder if we just overload handleChange and handleBlur like this:
```js
handleChange = (maybeStringOrEvent: 'string' | React.ChangeEvent<any>) => {
  const actualHandleChange = (e: React.ChangeEvent<any>) => {
    // our exisitng fn as it is npw
  }

  if (isString(maybeStringOrEvent)) {
    // we could cache these handlers too by key like Preact's linkState does for perf boost
    if (this.handleCache[maybeStringOrEvent]) {
      return this.handleCache[maybeStringOrEvent];
    } else {
      this.handleCache[maybeStringOrEvent] = (e: React.ChangeEvent<any>) => actualHandleChange(e);
      return this.handleCache[maybeStringOrEvent]
    }
  } else {
    actualHandleChange(e)
  }
}```

**Comment by jaredpalmer** [comment]
cc @slightlytyler what do you think?

**Comment by slightlytyler** [comment]
It would be nice if this could be handled without a new API for sure, are there any downsides to overloading the handlers in that fashion?
