### ISSUE TITLE
Code from npm and from github is different

### ISSUE THREAD

**Issue by sergii-azizov** [jaredpalmer/formik#386]
## Bug
npm version of formik not the same as code in master

## Current Behavior (the code from npm)

<img width="915" alt="screen shot 2018-01-29 at 9 11 43 pm" src="https://user-images.githubusercontent.com/33128587/35529246-26c20b02-0539-11e8-8388-2cfb94440627.png">

## Desired Behavior (the code from github master branch)

<img width="959" alt="screen shot 2018-01-29 at 9 12 20 pm" src="https://user-images.githubusercontent.com/33128587/35529253-29bc5a2e-0539-11e8-9bfa-16cc7d248bf6.png">

## Suggested Solutions
update code

- Formik Version: 0.10.5

**Comment by jaredpalmer** [comment]
Correct. I made an error and merged 1 array helper into master that's not yet been released. Will be releasing v11 hopefully today/tomorrow.
