### ISSUE TITLE
formik don't detect values change when i use radio buttons

### ISSUE THREAD

**Issue by Horion6102** [jaredpalmer/formik#3863]
### Current Behavior

The issue it's my formik don't detect values change when i use radio buttons.

How to reproduce : if you click on radio button nothing happen, like if nothing change in the `values`, but if click 2 time on the same check box and next to that you change radio button value, you will be able to see the button reload appear, that means formik changes `dirty` property to true.

Video of issue :
https://github.com/jaredpalmer/formik/assets/97897215/dad533ed-d79d-407f-8a7f-d6ea82d9fc2a

### Reproducible example

https://codesandbox.io/s/formik-dont-react-r462dq

### Suggested solution(s)

We saw that `initialValues` change at same time as `values`, it seems to be the origin of the problem because then Formik doesn't see any difference between the two objects.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.4.3
| React            | 17
| TypeScript       | 5.0.4
| Browser          | Chrome Version 115.0.5790.170 (Build officiel) (arm64)
| npm/Yarn         | 6.14.17/1.22.18
| Operating System | macOs Monterey, version 12.1

**Comment by yazaldefilimonepinto** [comment]
Let me try fix it

**Comment by probablyup** [comment]
`enableReinitialize` is probably the issue, every time `initialValues` is regenerated it resets the form state.
