### ISSUE TITLE
return a Promise from handleSubmit

### ISSUE THREAD

**Issue by testerez** [jaredpalmer/formik#39]
If I return a promise from `handleSubmit` I'd like  `setSubmitting(false)` to be called for me. So the example from the doc could be:

```js
  handleSubmit: (payload, { props, setError }) => {
    return CallMyApi(props.user.id, payload)
      .then(
        res => {
          // do something to show success
          // MyToaster.showSuccess({ message: 'Success!' })
        },
        err => {
          setError(err)
          // do something to show a rejected api submission
          // MyToaster.showError({ message: 'Shit!', error: err })
        }
      )
  },
```

If the returned `Promise` is rejected, you could also consider calling `setError(promiseError)`

**Comment by jaredpalmer** [comment]
Going to close this as there are several situations when form submissions should be sync. (e.g. Like when you are faking a submission in a search interface and just navigating to a different url).

**Comment by testerez** [comment]
In my suggestion, returning a promise would be optinal...
