### ISSUE TITLE
[Next] What's the best way to handle FieldArray validation?

### ISSUE THREAD

**Issue by davidhenley** [jaredpalmer/formik#391]
## Bug, Feature, or Question?

Question

## Info

Since you need to have no errors on the array does this make the most sense for validating Arrays or am I making this too difficult? If you don't return undefined for the array, the submit will not work.

products is an array with each object having a name, cases, and bottles.

```
export const validate = values => {
  const errors = {};

  if (!values.customer) errors.customer = 'Required';
  if (!values.date) errors.date = 'Required';

  const productErrors = [];
  values.products.forEach(product => {
    let errors = {};

    if (!product.name) errors.name = 'Required';
    if (!product.cases && !product.bottles) {
      errors.cases = 'Required';
      errors.bottles = 'Required';
    }

    productErrors.push(errors);
  });

  if (productErrors.some(errorObject => !isEmpty(errorObject))) {
    errors.product = productErrors;
  } else {
    errors.product = undefined;
  }

  return errors;
};
```
 

- Formik Version: 0.11.0-rc2

**Comment by jaredpalmer** [comment]
You could maybs make it less imperative with like map and reduce but this seems fine to me. Tbh, I’m still exlloring “best practices” with arrays too

**Comment by jaredpalmer** [comment]
Check out the latest version.

**Comment by davidhenley** [comment]
I noticed that pop() touches the array, while push() doesn't. Are you getting this as well?

**Comment by davidhenley** [comment]
So this is what I found and it works. But it's ugly.

const error = (touched[name] && errors[name]) || getNested(touched, name) && getNested(errors, name);

```
function getNested (theObject, path, separator) {
    try {
        separator = separator || '.';
    
        return path.
                replace('[', separator).replace(']','').
                split(separator).
                reduce(
                    function (obj, property) { 
                        return obj[property];
                    }, theObject
                );
                    
    } catch (err) {
        return undefined;
    }   
}
```

**Comment by jaredpalmer** [comment]
Should I just export `dlv` as `get` from the internals?

**Comment by davidhenley** [comment]
Spoke too soon. Even with this object, handleSubmit will not work. The errors object is empty, so why wouldn't handleSubmit work?

```
{
  "values": {
    "customer": {
      "id": "1545",
      "description": "FRUGAL MACDOOGAL"
    },
    "date": "2018-02-09",
    "notes": "",
    "followup": "",
    "products": [
      {
        "name": {
          "id": "11810",
          "description": "FIREBALL (100M)"
        }
      }
    ]
  },
  "errors": {},
  "touched": {
    "customer": {
      "id": true,
      "description": true
    },
    "date": true,
    "notes": true,
    "followup": true,
    "products": [
      {
        "name": {
          "id": true,
          "description": true
        }
      }
    ]
  }
}
```

**Comment by davidhenley** [comment]
Oops, can you reopen? I accidentally closed.

**Comment by davidhenley** [comment]
@jaredpalmer  Under Formik's _this.submitForm, isValid = Object.keys(maybePromisedErrors).length === 0 is showing isValid as false, and maybePromisedErrors = {products: undefined}

Shouldn't undefined make isValid = true?

**Comment by davidhenley** [comment]
@jaredpalmer also wanted to add I just used nested fieldarrays and they work fine.

<Field name={`products[${i}].formats[${j}].qpc`} label="QPC" component={Form.Input} />

**Comment by marcosjuniorzup** [comment]
I have the same problem, I can not set the fieldarray as touched, setFieldTouched creates as object and not as array. And when I push he also does not arrow as touched.
