### ISSUE TITLE
onSubmit is not triggered if multiple buttons present in the form

### ISSUE THREAD

**Issue by hashedalgorithm** [jaredpalmer/formik#3915]
### Current Behavior

`<SheetFooter className="my-4">
                <div
                  className={cn("flex gap-4 items-center", {
                    "justify-between": currentSection === 1,
                    "justify-end": currentSection === 0,
                  })}
                >
                  {currentSection === 1 && (
                    <Button variant="outline" onClick={handleOnClickBack}>
                      Back
                    </Button>
                  )}
                  <div className="flex gap-4 justify-end items-center">
                    {currentSection === 1 ? (
                      <SheetClose asChild onClick={handleOnClickSheetClose}>
                        <Button
                          type="submit"
                        >
                          Create
                        </Button>
                      </SheetClose>
                    ) : (
                      <Button type="button" onClick={handleOnClickNext}>
                        Next
                      </Button>
                    )}
                    <SheetClose asChild onClick={handleOnClickSheetClose}>
                      <Button type="reset" variant={"secondary"}>
                        Cancel
                      </Button>
                    </SheetClose>
                  </div>
                </div>
              </SheetFooter>`
              
I am using Shadcn Component. So, I have these buttons in my form. I need to trigger onsubmit only on certain button(Create Button). But it does'nt trigger onsubmit. I even disabled validation. nothing works.

### Aditional Context
If i explicitly mention onClick for that button it works. like this
`onClick={() => props.handleSubmit()}`

### Expected behavior

I have explicitly mentioned the button type as "submit" for the submission button and "button" for others. It should trigger onsubmit onclicking create button.

### Reproducible example
Use multiple buttons in form. 

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           |      2.4.5
| React            |      latest
| TypeScript       |   latest
| Browser          |    Brave [Version 1.60.118 Chromium: 119.0.6045.163 (Official Build) (64-bit)](https://brave.com/latest/)
| npm/Yarn         |    1.22.19
| Operating System | Windows 11 Home

**Comment by karfau** [comment]
I have no idea why I was mentioned as part of this.
