### ISSUE TITLE
Page reloads on submit if form is inside drawer component

### ISSUE THREAD

**Issue by MYSIVMAKARII** [jaredpalmer/formik#3934]
### Current Behavior

Submit btn reloads page if Formik is inside callable component like aside drawer. Any variations of prevent default doesn't solve this problem. If I click on submit btn, page reloads, validation doesn't work and it looks like GET request, because I see query in url.

![Screenshot 2024-01-02 at 10 59 48 AM](https://github.com/jaredpalmer/formik/assets/77324079/45339b0d-0e2b-4a1b-a735-012019ba8743)

### Suggested solution(s)

How could I solve this?

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.4.5
| React            | 18.2.0
| TypeScript       | 4.9.5
| Browser          | Chrome
| npm/Yarn         | NPM

**Comment by juvpengele** [comment]
Can you add more details of the code you have written so that it can be reproduced ?

**Comment by MYSIVMAKARII** [comment]
> Can you add more details of the code you have written so that it can be reproduced ?

Sure! Thank you!

Page with carriers and drawer toggling:

<img width="811" alt="Screenshot 2024-01-03 at 12 13 15 PM" src="https://github.com/jaredpalmer/formik/assets/77324079/a6165148-3476-4032-916e-fd908c1312f5">

CreateCarrierForm component:

<img width="1007" alt="Screenshot 2024-01-03 at 12 11 33 PM" src="https://github.com/jaredpalmer/formik/assets/77324079/2aa77e9c-acb8-4cda-aff3-8a9d04daf2fd">

Drawer is quite simple. It contains {children} and toggling by isOpened boolean value. 
**If I separate form from the Drawer - everything working as expected.** It looks like submit button inside the drawer calls nothing. Changing { Form } from Formik to plain <form onSubmit='...'> has no result too, same as dealing with Formik prop on Submit.

**Comment by juvpengele** [comment]
- Is `console.log`  displayed ?
- Can you try
```jsx
   <Formik
       initialValues={initialValues}}
       validationSchema={createCarrierSchema}
       onSubmit={(values, actions) => {
            actions.setSubmitting(false);
       }}
     >
     ....
   </Formik>
```

**Comment by MYSIVMAKARII** [comment]
> * Is `console.log`  displayed ?
> * Can you try
> 
> ```js
>    <Formik
>        initialValues={initialValues}}
>        validationSchema={createCarrierSchema}
>        onSubmit={(values, actions) => {
>             actions.setSubmitting(false);
>        }}
>      >
>      ....
>    </Formik>
> ```

That's the point. This part doesn't work because if I click on 'submit' btn the whole page reloads.

**Comment by MYSIVMAKARII** [comment]
@juvpengele I found the solution. Thank you for your response.

In case anyone needed:

<img width="988" alt="Screenshot 2024-01-03 at 2 17 45 PM" src="https://github.com/jaredpalmer/formik/assets/77324079/87063208-a314-445f-bffa-0b40d93f278a">
