### ISSUE TITLE
formik file upload handling

### ISSUE THREAD

**Issue by KyuubiTila** [jaredpalmer/formik#3943]
## Bug report

import React from 'react';
import { Formik, Form, Field, ErrorMessage } from 'formik';

const CreateProductCard = ({ addProduct, initialValues, validationSchema }) => {
  return (
    <Formik
      initialValues={initialValues}
      onSubmit={(data, params) => {
        console.log(data);
        // addProduct(data);
        // params.resetForm();
      }}
      validationSchema={validationSchema}
    >
      <Form>
        <div className="mb-6">
          <label
            htmlFor="email"
            className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
          >
            NAME
          </label>
          <Field
            autoComplete="off"
            type="text"
            name="name"
            placeholder="enter name"
            className="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light"
            required
          />
          <span className="text-red-500">
            <ErrorMessage name="name" component="span" />
          </span>
        </div>
        <div className="mb-6">
          <label
            htmlFor="password"
            className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
          >
            DESCRIPTION
          </label>
          <Field
            autoComplete="off"
            type="text"
            name="description"
            placeholder="enter description"
            className="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light"
            required
          />
          <span className="text-red-500">
            <ErrorMessage name="description" component="span" />
          </span>
        </div>
        <div className="mb-6">
          <label
            htmlFor="repeat-password"
            className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
          >
            BRAND
          </label>

          <Field
            autoComplete="off"
            type="text"
            name="brand"
            placeholder="enter brand"
            className="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light"
            required
          />
          <span className="text-red-500">
            <ErrorMessage name="brand" component="span" />
          </span>
        </div>
        <div className="mb-6">
          <label
            htmlFor="repeat-password"
            className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
          >
            CATEGORY
          </label>

          <Field
            autoComplete="off"
            type="text"
            name="category"
            placeholder="enter category"
            className="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light"
            required
          />
          <span className="text-red-500">
            <ErrorMessage name="category" component="span" />
          </span>
        </div>
        <div className="mb-6">
          <label
            htmlFor="repeat-password"
            className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
          >
            PRICE
          </label>

          <Field
            autoComplete="off"
            type="number"
            name="price"
            placeholder="enter price"
            className="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light"
            required
          />
          <span className="text-red-500">
            <ErrorMessage name="price" component="span" />
          </span>
        </div>
        <div className="mb-6">
          <label
            htmlFor="image"
            className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
          >
            IMAGE
          </label>
          <Field
            type="file"
            name="image"
            accept=".jpg, .jpeg, .png, .gif"
            className="block w-full"
          />
          <ErrorMessage name="image" component="div" className="text-red-500" />
        </div>
        <button
          type="submit"
          className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
        >
          CREATE PRODUCT
        </button>
      </Form>
    </Formik>
  );
};

export default CreateProductCard;

### Current Behavior

the image isn't returning the image field as a file object rather it returns just a string of text

### Expected behavior

I ought to have a file object for the uploaded image

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.4.3
| React            | 18.2.0
| TypeScript       | javascript
| Browser          | chrome
| npm/Yarn         | npm
| Operating System | mac os high sierra

**Comment by Janelaxagh** [comment]
@KyuubiTila 
To fix this issue and correctly handle file uploads, you can make use of the `onFileChange` function provided by Formik. Here's how you can modify your `CreateProductCard` component to handle file uploads correctly:

```javascript
import React from 'react';
import { Formik, Form, Field, ErrorMessage } from 'formik';

const CreateProductCard = ({ addProduct, initialValues, validationSchema }) => {
  return (
    <Formik
      initialValues={initialValues}
      onSubmit={(data, params) => {
        console.log(data);
        // addProduct(data);
        // params.resetForm();
      }}
      validationSchema={validationSchema}
    >
      {({ setFieldValue }) => (
        <Form>
          {/* ... other form fields ... */}
          <div className="mb-6">
            <label
              htmlFor="image"
              className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
            >
              IMAGE
            </label>
            <input
              type="file"
              name="image"
              accept=".jpg, .jpeg, .png, .gif"
              className="block w-full"
              onChange={(event) => {
                // Set the field value to the selected file
                setFieldValue("image", event.currentTarget.files[0]);
              }}
            />
            <ErrorMessage name="image" component="div" className="text-red-500" />
          </div>
          <button
            type="submit"
            className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
          >
            CREATE PRODUCT
          </button>
        </Form>
      )}
    </Formik>
  );
};

export default CreateProductCard;
```

**Comment by KyuubiTila** [comment]
still no way out, formik seems to not be sending the image as a file object.

**Comment by KyuubiTila** [comment]
yeahhh so here is the solution that works. Just figured it out

FIRST THING TO DO
You can create one component like this, just a raw component.

import React from 'react';

function FileUpload(props) {
  const {field, form} = props;

  const handleChange = (e) => {
    const file  =  e.currentTarget.files[0];
    const reader = new FileReader();
    const imgTag = document.getElementById("myimage");
    imgTag.title = file.name;
    reader.onload = function(event) {
      imgTag.src = event.target.result;
    };
    reader.readAsDataURL(file);
    form.setFieldValue(field.name, file);
  };

  return (
    <div>
      <input type={'file'} onChange={(o) => handleChange(o)} className={'form-control'}/>
        <img src={''} alt="" id={'myimage'}/>
    </div>
  );
}

export default FileUpload;

SECONDLY, IMPORT IN YOUR FORMIK CONTROLLED FORM

And use this like this inside the form

 <Field
     name="image"
    component={FileUpload} // import from the component you just created above
   />


SOLUTION CREDIT : [Sonukr](https://github.com/Sonukr), on Apr 14, 2019

![Screen Shot 2024-02-11 at 19 08 57](https://github.com/jaredpalmer/formik/assets/114122136/e0b3cadc-c352-4771-9b10-b6480639be98)

**Comment by KyuubiTila** [comment]
Ths is what my code looks like 
'use client';
import React from 'react';
import { Formik, Form, Field } from 'formik';
import FileUpload from '@/components/fileupload';

const UpdateProfile = () => {
  const initialValues = {
    username: '',
    bio: '',
    profilePhoto: '',
  };

  const handleSubmit = (values) => {
    console.log('Form values:', values);
  };

  return (
    <section className="bg-white dark:bg-gray-900">
      <div className="container flex items-center justify-center min-h-screen px-6 mx-auto">
        <Formik initialValues={initialValues} onSubmit={handleSubmit}>
          {({ isSubmitting }) => (
            <Form className="w-full max-w-md">
              <div className="flex items-center justify-center">
                <a className="w-1/3 pb-4 font-medium text-center capitalize text-gray-800 dark:text-white">
                  Update Profile
                </a>
              </div>

              <div className="relative flex items-center mt-2">
                <Field
                  type="text"
                  name="username"
                  className="block w-full py-3 text-gray-700 bg-white border rounded-lg px-6 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-600 focus:border-blue-400 dark:focus:border-blue-300 focus:ring-blue-300 focus:outline-none focus:ring focus:ring-opacity-40"
                  placeholder="Username"
                />
              </div>

              <label
                htmlFor="profilePhoto"
                className="flex items-center px-3 py-3 mx-auto mt-6 text-center bg-white border-2 border-dashed rounded-lg cursor-pointer dark:border-gray-600 dark:bg-gray-900"
              >
                <h2 className="mx-3 text-gray-400">Profile Photo</h2>
                <Field name="image" component={FileUpload} />
              </label>

              <div className="relative flex items-center mt-6">
                <Field
                  as="textarea"
                  name="bio"
                  className="block w-full py-3 text-gray-700 bg-white border rounded-lg px-6 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-600 focus:border-blue-400 dark:focus:border-blue-300 focus:ring-blue-300 focus:outline-none focus:ring focus:ring-opacity-40"
                  placeholder="Bio"
                />
              </div>

              <div className="mt-6">
                <button
                  type="submit"
                  className="w-full px-6 py-3 text-sm font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-500 rounded-lg hover:bg-blue-400 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-50"
                  disabled={isSubmitting}
                >
                  {isSubmitting ? 'Updating...' : 'Update Profile'}
                </button>
              </div>
            </Form>
          )}
        </Formik>
      </div>
    </section>
  );
};

export default UpdateProfile;


and the component 



import React from 'react';

function FileUpload(props) {
  const { field, form } = props;

  const handleChange = (e) => {
    const file = e.currentTarget.files[0];
    const reader = new FileReader();
    const imgTag = document.getElementById('myimage');
    imgTag.title = file.name;
    reader.onload = function (event) {
      imgTag.src = event.target.result;
    };
    reader.readAsDataURL(file);
    form.setFieldValue(field.name, file);
  };

  return (
    <div>
      <input
        type={'file'}
        onChange={(o) => handleChange(o)}
        className={'form-control'}
      />
      <img src={''} alt="" id={'myimage'} />
    </div>
  );
}

export default FileUpload;

AND HERE IS THE RESULT:
![Screen Shot 2024-02-11 at 19 13 09](https://github.com/jaredpalmer/formik/assets/114122136/54837acd-6285-42a9-bd23-0b6509a5979f)
