### ISSUE TITLE
Formik.dirty is not reacting to nested changes

### ISSUE THREAD

**Issue by vladtopchu** [jaredpalmer/formik#3948]
### Current Behavior

I have an object with three-level nested object
When I change it formik values is changing but formik.dirty is not reacting except if i add/remove elements

### Expected behavior
formik.dirty should react to nested objects changes 

### Reproducible example

https://codesandbox.io/p/sandbox/nested-schema-bug-gy44pw?file=/index.js

### My environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.4.5 | 
| React            | nextjs 13.2.3 | 
| TypeScript       | no | 
| Browser          | arc 1.27.3| 
| npm/Yarn         | npm | 
| Operating System | macOS 13.5.1|

**Comment by DeveloperRaj** [comment]
I have created PR to solve this issue.
