### ISSUE TITLE
values not ready for evaluation right after setFieldValue

### ISSUE THREAD

**Issue by midnightcodr** [jaredpalmer/formik#395]
https://codesandbox.io/s/347208omo1

## Bug, Feature, or Question?
Question
## Current Behavior
Changing the checked/unchecked states of the checkboxes doesn't result in a timely result for the `feelings` field, the result is always one-step behind
## Desired Behavior
The value of `feelings` field should reflect the selections of the checkbox fields `hasIncome` and `hasHouse`
## Info
What I am trying to achieve is to determine the value of one field based on the outcome from the other two.

- Formik Version: 
- OS: macOS 10.13.1
- Node Version: 8.9.3
- Package Manager and version: 5.5.1

**Comment by midnightcodr** [comment]
My question is really about how to set a field's value that is dependent on other field(s). Suggestions?

**Comment by jaredpalmer** [comment]
Use a custom component or external React state.
