### ISSUE TITLE
enableReinitialize doesn't work anymore

### ISSUE THREAD

**Issue by Adem044** [jaredpalmer/formik#3974]
This PR https://github.com/jaredpalmer/formik/pull/3949 breaks the enableReinitialize functionality.
Now the `formik.values` object won't have the latest updates to the `formik.initialValues`.

before upgrading
https://codesandbox.io/p/sandbox/formik-forked-zn5nqt

after upgrading to 2.4.6
https://codesandbox.io/p/sandbox/formik-forked-c7xw7y

**Comment by quantizor** [comment]
It's working, you're just not using it correctly https://codesandbox.io/p/sandbox/formik-forked-c7xw7y?file=%2Fsrc%2FApp.js%3A15%2C1-16%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwv3fvaj00063b6ij6b3djhr%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwv3fvai00023b6ijbk5jltg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwv3fvaj00033b6i1n3mc6dc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwv3fvaj00053b6iwpq4s60q%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwv3fvai00023b6ijbk5jltg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwv3fvai00013b6i17ev0sno%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwv3jjl5003t3b6iy0hx3o5m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwv3fvai00023b6ijbk5jltg%2522%252C%2522activeTabId%2522%253A%2522clwv3jjl5003t3b6iy0hx3o5m%2522%257D%252C%2522clwv3fvaj00053b6iwpq4s60q%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwv3fvaj00043b6i2hadxemy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwv3fvaj00053b6iwpq4s60q%2522%252C%2522activeTabId%2522%253A%2522clwv3fvaj00043b6i2hadxemy%2522%257D%252C%2522clwv3fvaj00033b6i1n3mc6dc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwv3fvaj00033b6i1n3mc6dc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by Adem044** [comment]
@quantizor How's that?
