### ISSUE TITLE
Clean onBlur handling for React Native

### ISSUE THREAD

**Issue by jay1337** [jaredpalmer/formik#407]
## Bug, Feature, or Question?
Bug

## Current Behavior
The doc says that `setFieldTouched` must be used instead of `handleBlur` to handle `onBlur` event.
But it does not trigger form validation...

## Desired Behavior
Form validated.

## Suggested Solutions
Add a `handleBlurForField` function that takes a field name and do the same things that `handleBlur` does.

## Info
 

- Formik Version: not relevant
- OS: not relevant
- Node Version: not relevant
- Package Manager and version: not relevant

**Comment by jaredpalmer** [comment]
Yes this is the `linkState` approach. I guess it's possible we could overload `handleChange` and check if the first argument is a string (instead of an event). 

```
handleChange = (maybeStringOrEvent: 'string' | React.ChangeEvent<any>) => {
  const actualHandleChange = (e: React.ChangeEvent<any>) => {
    // our exisitng fn as it is npw
  }

  if (isString(maybeStringOrEvent)) {
    // we could cache these handlers too by key like Preact's linkState does for perf boost
    if (this.handleCache[maybeStringOrEvent]) {
      return this.handleCache[maybeStringOrEvent];
    } else {
      this.handleCache[maybeStringOrEvent] = (e: React.ChangeEvent<any>) => actualHandleChange(e);
      return this.handleCache[maybeStringOrEvent]
    }
  } else {
    actualHandleChange(e)
  }
}
```

**Comment by jaredpalmer** [comment]
@jay1337 `setFieldTouched` should trigger validation unless you have set `validateOnBlur` to `false`.

**Comment by jay1337** [comment]
@jaredpalmer thanks for your answer, you are right.
If you want to make life easier with React Native, you should implement getters instead of functions (cf my other issue https://github.com/jaredpalmer/formik/issues/385).
