### ISSUE TITLE
Conditional validation

### ISSUE THREAD

**Issue by anhldbk** [jaredpalmer/formik#41]
@jaredpalmer : Thanks for this great library. It's much better than `redux-form`.

Btw, I have one question for the following form:

![screenshot from 2017-07-09 22-05-17](https://user-images.githubusercontent.com/3270746/27995145-a813ad28-64f3-11e7-8e74-f37b32bd1787.png)

Each state has a name and a bool field named `no_cost`. If `no_cost` = true, there's no incurring cost.

I know `Yup` support conditional validation, but would you pls tell me how to apply it with `formik`?

**Comment by rostero1** [comment]
Untested:

```
validationSchema: Yup.object().shape({
  name: Yup.string().required(),
  no_cost: Yup.boolean(),
  cost: Yup.number().when('no_cost', {
    is: true,
    then: Yup.number()
      .required('cost is required'),
    otherwise: Yup.number(),
  })
})
```

**Comment by anhldbk** [comment]
@rostero1 : Thank you. Then we have to hook to `handleChange` to update `no_cost` accordingly, right?

**Comment by anhldbk** [comment]
Yes, we can solve the issue by hooking to `handleChange`. 

@jaredpalmer Btw, is it a good idea for `formik` to provide a callback named `onValuesChanged` to let parent containers to there're changes in data (without any form submission)?

**Comment by jaredpalmer** [comment]
> Btw, is it a good idea for formik to provide a callback named onValuesChanged to let parent 
> containers to there're changes in data (without any form submission)?

@anhldbk you can turn your inner form component into a class (instead of a stateless functional component) and then write your own change handler that calls whatever hooks you need before calling Formik's `handleChange`.

``` js   
handleChange = e => {
  this.props.notifyMyParent({ [e.target.name]: e.target.value })
  this.props.handleChange(e);
}
```

**Comment by anhldbk** [comment]
Thank you @jaredpalmer

**Comment by DavidCasillasRivero** [comment]
> you can turn your inner form component into a class (instead of a stateless functional component) and then write your own change handler that calls whatever hooks you need before calling Formik's handleChange.

@jaredpalmer  Why do you need to convert a stateless functional component into a class component to write a custom `handleChange` function? I can see no reason to this change. There is no need to hold state and no need to use lifecycle hooks.

**Comment by jaredpalmer** [comment]
@DavidCasillasRivero to avoid an arrow function debate 😄
