### ISSUE TITLE
When using Yup anyway to have a callback if the Yup validation comes back with errors?

### ISSUE THREAD

**Issue by FahdW** [jaredpalmer/formik#410]
Trying to scroll the window back to the top if there are validation errors found. However using the yup schema its a bit harder to put any middleman directions if i don't know if it errored or not.

**Comment by jozzhart** [comment]
Adding this feature would make things cleaner for my use-case.

**Comment by NishantDesai1306** [comment]
even imagine that if we want to show some sort of toast notification, notifying that form submission failed due to some validation errors

**Comment by yoonghan** [comment]
Would manually calling validateForm help? the idea

`
{
              ...
              handleSubmit,
              validateForm
            }) => (
<form onSubmit={
                (event)=>{
                  event.preventDefault()
                  validateForm().then((errors)=>{
                    if(errors && Object.keys(errors).length !== 0) {
                      window.scrollTo(0,0)
                    }
                    else {
                        handleSubmit()
                    }
                  })
                  return false
                }
              }>
`
