### ISSUE TITLE
11.6 rimraf command fails

### ISSUE THREAD

**Issue by arist0tl3** [jaredpalmer/formik#411]
## Current Behavior

Installation of 0.11.6 Fails

## Desired Behavior

Installation of 0.11.6 Succeeds

## Info

- Formik Version: 0.11.5 (attempting upgrade to 0.11.6)
- OS: Ubuntu 16.04
- Node Version: 8.4.0
- Package Manager and version: Tried with NPM 5.0.4 and Yarn 1.3.2

![image](https://user-images.githubusercontent.com/9328541/35942635-2a4f09f4-0c0b-11e8-90cb-8689483d9d90.png)

Note: Still failed even after I installed `rimraf` as a project dependency.

**Comment by arist0tl3** [comment]
Also thanks for looking at the setFieldError/setFieldTouched issue =)

**Comment by jaredpalmer** [comment]
weird. Im going to kill my yarn cache and reinstall

**Comment by jaredpalmer** [comment]
fixed. released a patch.
