### ISSUE TITLE
Use Boolean-Check for validation via validate

### ISSUE THREAD

**Issue by PutziSan** [jaredpalmer/formik#416]
## Bug, Feature, or Question?
Feature
## Current Behavior
validation-check on submitting when using the `validate`-flag (implicitly) for hasOwnProp, not for boolean-like values.
## Desired Behavior
Check for boolean-like values.
## Suggested Solutions
change [this line](https://github.com/jaredpalmer/formik/blob/master/src/formik.tsx#L491) to:
```javascript
const isValid = Object.keys(maybePromisedErrors).map(key =>maybePromisedErrors[key])
  .filter(Boolean).length === 0;
```
## Info
I would like to use the validate-function like this:
 ```javascript
withFormik({
  // ...
  validate: values => ({
    email: !isEmail(values.email) && 'Invalid email address',
  }),
})
```
[`Object.keys`](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) checks for `hasOwnProperty`, so that something like
 ```javascript
validate: values => ({
  email: !isEmail(values.email) ? 'Invalid email address' : undefined,
})
```
will not work.

- Formik Version: 0.11.7
- OS: windows
- Node Version: 6.10.3
- Package Manager and version: npm 5.6.0, yarn 1.3.2

**Comment by jaredpalmer** [comment]
If you can figure out how to make this backwards-compatible, I would be open to a PR.

**Comment by PutziSan** [comment]
I do not think that we can manage this in a backward-compatible-way. It is per definition a breaking-change, so maybe we could introduce it in the new alpha as breaking-change.
Most likely, 99% of users will not experience any change. Only those who rely on falsy values to be recognized as errors would have to adjust their code.

At the time I just use this workarround, which is pretty simple and nearly like my proposal (using ramdas [`pick`](http://ramdajs.com/docs/#pick)):
```javascript
const removeFalsyProps = obj => pick(Object.keys(obj).filter(key => obj[key]), obj);

withFormik({
 // ...
 validate: values => removeFalsyProps({
   email: !isEmail(values.email) && 'Invalid email address',
 }),
})
```
