### ISSUE TITLE
Exception when validating FieldArray

### ISSUE THREAD

**Issue by davidwandar** [jaredpalmer/formik#417]
## Bug?

Trying out FieldArray (in 0.11) but running in to issues with validation. The form does not revalidate when adding/removing objects in array, and it also throws exception in a certain scenario

https://codesandbox.io/s/ykr57mqm61

Validation sort of works, but an exception occurs when doning theese repro-steps:
1 Remove, 2. Remove, 3. Submit, 4. Add, 5. Remove

**Comment by jaredpalmer** [comment]
Thanks for taking the time to make a sandbox. Will take a look 👀 when I get to the office in ~1hr
