### ISSUE TITLE
How do you create multi-step forms?

### ISSUE THREAD

**Issue by sketchbuch** [jaredpalmer/formik#424]
I'm rendering a different form based on a "view" prop, but the second form seems to have merged it's initial state with the previous and the submit button is disabled on the second form even though only the first was submitted.

Are there examples of how to reset the form? So that when my components view changes a new form is displayed? At the moment it seems to just update the previous

**Comment by jaredpalmer** [comment]
There is a multi step example in the examples folder. You may also want to check out react-albus, which will make it easier to have a single reset button

**Comment by zouhairjabiri** [comment]
+1
