### ISSUE TITLE
Asynchronous initialValues

### ISSUE THREAD

**Issue by Gi972** [jaredpalmer/formik#427]
## Bug, Feature, or Question?
Hello,

I don't know if you have implemented this function but I don't see it on the doc and I make test but it doesn't work

it's possible to have asynchronous initialvalues?

demo here: https://codesandbox.io/s/ryqxlx7xvn

when i click on setdata for initialize the data

Thanks for your answer

**Comment by jaredpalmer** [comment]
You don't need Formik for this. Just use React!

https://codesandbox.io/s/j2kq8pnv2w

**Comment by SistemasSouza** [comment]
I have a form with formik, the data are of the api, o initialValues not working in with Asynchronous, the component is render before finish fetch. some possible solution to the problem
