### ISSUE TITLE
Set field values before posting, requires changing the props.values as well

### ISSUE THREAD

**Issue by andreasciamanna** [jaredpalmer/formik#428]
I have a `Field` element with `onChange` hooked to an arrow function.

The purpose of this is to post the form when the field is changed.

After a lot of fiddling, the only way to make this work was to write something like that in the event handler:

```javascript
const handleChange = (e) => {
	const {name, checked} = e.currentTarget;
	setFieldValue(name, checked);
	this.props.values[name] = checked;
	submitForm();
};
```

I don't understand why I need to do both `setFieldValue(name, checked);` and `this.props.values[name] = checked;`: if I miss any of them, the form is posted without the changed value.

I think the `this.props.values[name] = checked;` is wrong, as `setFieldValue` is meant to take care of this.

The field itself is quite simple:

```html
<Field
	type="checkbox"
	name="auto_adjust_ids"
	id="auto_adjust_ids"
	checked={!!values.auto_adjust_ids}
	value={!!values.auto_adjust_ids}
	onChange={handleChange}
/>
```

Values are mapped from props through `mapPropsToValues`.

What am I missing?

**Comment by jaredpalmer** [comment]
@slightlytyler has a autosave-onChange wrapper implemented. Will try to look for the relevant issue and post a link.
