### ISSUE TITLE
touched is always true for all fields

### ISSUE THREAD

**Issue by sketchbuch** [jaredpalmer/formik#429]
I have the following initial values:

{
      class: {
				id: '',
				label: '',
				pupilCount: 0,
			},
      pupil: {
				description: '',
				firstname: '',
				gender: 'm',
				id: '',
				lastname: '',
			},
      text: {
				bodytext: '',
				id: '',
				lang: '',
			},
    }

I'm showing only certain fields in three steps. touched for all fields ist true whether the fields has been shown, or even changed.

This means that when displaying the pupil fields, if a user focuses and blurs the frstname field an error appears, but also for the lastname field that has never been touched.
ow can I fix this? Or check if there is an error ? Currently I check in errors and touched, is this the orrect way?

**Comment by jaredpalmer** [comment]
Check if there is an error.

**Comment by sketchbuch** [comment]
How??? And why is everything true in touched?

**Comment by jaredpalmer** [comment]
My guess is  actually that the form is trying to submit by accident because you have not properly labelled the buttons in your forms.  Non-submit buttons should be `<button type="button>` while the submit button should be `<button type="submit>`. This is a common mistake. Formik sets touched to true for all fields during a submit attempt.

**Comment by sketchbuch** [comment]
Yes, I have subit on all step buttons, but in this example:

https://github.com/jaredpalmer/formik/blob/master/examples/MultistepWizard.js

When it's not the last page, the button is type submit.

I have I iss understood something with this example?

I don't have a previous button so my button is always like the "next" in the example.

I shall try changing the type and see what happens, but I'm sure it had to be sumbit or the next step never appeared.

**Comment by sketchbuch** [comment]
yes it is as I thought, the next step never happens if I make it type button. Do I need to put a click handler on the button? Thre is none in the wizard example.

**Comment by jaredpalmer** [comment]
The wizard example is technically 3 distinct forms.

**Comment by joshgeller** [comment]
@jaredpalmer Can you explain how the wizard example is 3 distinct forms? I was under the impression that it was one, since only one `Formik` instance is only rendering one `form` tag. I'm having the same problem as OP. As soon as I submit the first form in my wizard, the fields on all subsequent forms get touched.

**Comment by gracu-koduje** [comment]
I have fix for that. After clicked submit btn "next" on step 1 in step 2 you have to run in "componentDidMount" this.props.setTouched({}). Then you will get an empty "touched" object in step 2.

**Comment by timrombergjakobsson** [comment]
@gracu-koduje could you provide an example on how you solved it? I also have the same problem with "next" vs "submit". If make the next button of type ```"button"``` I cant proceed to the next step. Only if it is marked as ```type="submit"```.

**Comment by gracu-koduje** [comment]
@timrombergjakobsson  it's easy. Every click on submit button causes that Formik > touched object it's filled - it's mean that in next step u will get touched: true on every fields. If u want to change it u have to use "setTouched({})" in every step where u need it.

**Comment by timrombergjakobsson** [comment]
@gracu-koduje Im still not following. So I have to check for the page(1, 2 etc) in componentDidMount method? And then run ```this.props.setTouched({})```?
