### ISSUE TITLE
Using Formik Autosuggest component

### ISSUE THREAD

**Issue by pradok** [jaredpalmer/formik#43]
hi, I have autosuggest component that needs to be part of the form, Formik has no way of knowing it. 
So I got another text field that changes via state when auto suggest is selected, but since this Formik aware text field which also required has not been touched, Formik sees as invalid even though the field has value via state triggered by the autosuggest component. Any idea how can I make Formik aware of the field changes via state?

**Comment by eonwhite** [comment]
Build a controlled component that wraps your autosuggest library, accepts a value, and calls Formik's `handleChangeValue`. You should wind up with a component that you invoke like this in your Formik render:

```
<label>My Field Name</label>
<MyAutosuggest id="fieldname" value={values.fieldname} onChange={handleChangeValue} />
```

**Comment by pradok** [comment]
Thanks. I am using this component https://github.com/moroshko/react-autosuggest copied all what is said under 'Basic Usage' and wrapped into a component called AutoSuggest and use as below, location (values.location) field is required.

```
<AutoSuggest
            value={values.location}
            onChange={handleChangeValue}
            placeholder='Suburb/Postcode'
            handleSelect={this.handleAutoSelectCallback}
  />
```
I am unsure how to use handleChangeValue and how to hook it up with AutoSuggest, is this in Formik object along with mapPropsToValues, mapValuesToPayload etc.?

Even after filling the value from autosuggest, Formik still renders this field as required.

**Comment by jaredpalmer** [comment]
You can see an example of this approach in the [Working with 3rd party input components demo](https://codesandbox.io/s/jRzE53pqR). It uses react-select, but the approach to using a custom change handler and `handleChangeValue` is identical.

@pradok I am actually going to be working on a formik x react-autosuggest component today for work. will make another example when i am done.

**Comment by pradok** [comment]
@jaredpalmer Thanks! The 3rd party example doesn't validate the form after doing touch in color field even selecting at least one color. If I don't touch that field, then it works as expected.
It would be a shame if I have to discard Formik due this last niggle, otherwise it is a great plugin, better than Formsy and leaner.

**Comment by jaredpalmer** [comment]
I updated the example and fixed a typo related to handleBlur. Thanks for catching it.

**Comment by pradok** [comment]
@jaredpalmer That was awesome! Thanks for your quick response. Wish I had asked sooner.
