### ISSUE TITLE
Unneeded rerenders

### ISSUE THREAD

**Issue by jay1337** [jaredpalmer/formik#430]
## Bug, Feature, or Question?
Bug

## Current Behavior
With simple validation (not async), after setting a field value, the form is rendered, then values are validated and then there is another render. 2 renders for 1 change, the first one is useless.

## Desired Behavior
Only 1 render after validation.

## Suggested Solutions
Validate values just after setting values, not in setState callback.

**Comment by jaredpalmer** [comment]
See #422 

It's coming soon.

**Comment by jaredpalmer** [comment]
This has been released in Formik 1.0.0-alpha.1

**Comment by jay1337** [comment]
Thanks !
