### ISSUE TITLE
can "validate" and "validateSchema" be  used concurrently?

### ISSUE THREAD

**Issue by twelve17** [jaredpalmer/formik#431]
## Bug, Feature, or Question?

Question

## Current Behavior

Using the `withFormik` as a HOC, with both a `validate` function and a `validateSchema` function, seems to result in only  `validate` being called on a `handleSubmit`, whereas `onBlur` events trigger `validateSchema`.

## Desired Behavior

I'm not quite sure here. :)  Should both validation types be called upon `handleSubmit`?  I imagine if the answer is "yes", either the results of the `errors` created by each one would have to be merged (could be messy), or the first one that produces `errors` stops the other function from being called.

## Suggested Solutions

I had both validation types because I had not yet figured out how to handle a few use cases in `yup`.  I think this is a good time to hunker down and figure that out so I only have `validationSchema`. :) 

If both validation types concurrently are not supported, it should be documented, or at least have the library throw an error if it sees both defined in the `withFormik` call.

## Info
 

- Formik Version: 0.11.4
- OS:  OS X Sierra
- Node Version: 8.9.4
- Package Manager and version: 5.6.0

**Comment by jaredpalmer** [comment]
I never thought anyone would use both at the same time. Formik source code is probably inconsistent about precedence. I believe in most situations they would race each other resulting in tons of extra renders.

**Comment by iwarshak** [comment]
Yup is really nice (as is formik), but I have run into validation situations where it'd be nice to be able to use validateSchema as well as a custom validation function.

**Comment by twelve17** [comment]
Thanks @jaredpalmer for the info. In the end, I figured out how to handle the validation all in yup, which is much cleaner than what I would have done via the validation function.  I agree it could be quite problematic dealing with resolving validations between the two approaches.

**Comment by Grsmto** [comment]
You can fairly easily replicate what `validateSchema` does when you define your `validate` function.

However, I noticed a similar effect when applying the new `validate` prop of the `<Field>` component.
You can't have both `<Field>` and `<Form>` level validation, they override each other.
I think resolving one of these issue you resolve the other. @jaredpalmer is this something you would like to support? If yes I could work on a PR.

Thanks!

**Comment by Romasato** [comment]
I was actually looking into this same question today, trying to combine errors from both `validationSchema` and `validate()` methods. But only `validationSchema()` errors out the form onChange, whereas `validate()` does only if I then click again on submit button to trigger `formSubmit()`.

I have an ArrayField and I want to compare for value uniqueness between objects in the ArrayField.
Simple to implement in `validate(values)`, but not sure how to achieve the same with Yup schema?
Any suggestions?

Thanks!

**Comment by jaredpalmer** [comment]
To anyone coming to this, no they were never intended to be used concurrently.

**Comment by Romasato** [comment]
Fair enough, thanks for answering on that point @jaredpalmer.

Still, do you think it is viable to make results from both `validate()` and `validationSchema()` get combined into the `form.errors`? I mean, is there a strong technical hurdle blocking this?

Also I would still like some guidance on how to use just `validationSchema()` and `Yup` to check for duplication between form values - or any other cross-field checks. Anyone?
Thanks:)

**Comment by jaredpalmer** [comment]
I would rather not have to call 2 functions. You can just run Yup validation schema.validate on your own within validate and keep a single source of truth in regards to validation. Imho much better

**Comment by jaredpalmer** [comment]
Not documented but Formik exports some Yup helpers too. If you open an issue I can add docs later this week probs

**Comment by twelve17** [comment]
@Romasato Look into Yup's [array function](https://github.com/jquense/yup#array).

**Comment by jaredpalmer** [comment]
^^^Correct. This is how Yup / Formik deals with arrays. You can also show the `tags` error if you just check the type first: `{typeof errors.tags === 'string' && errors.tags}`

**Comment by Romasato** [comment]
Thanks @twelve17 - that was helpful!

Below is an example validation for a new table form where I had to validate for unique table and column names. 
The approach is relying on yup's `test()` method and the context it provides to access the array of columns (via `this.parent`) and to also throw Yup errors that Formik picks up nicely.

```jsx
import React, {PropTypes} from 'react';
import yup from 'yup';
import {Formik} from 'formik';

class DataTableEditForm extends React.Component {
    /* Other React component boilerplace etc goes here */

    /*
    * Returns default form values
    * */
    getDefaultFormValues = () => {
        const {tableID} = this.props;
        return {
            'tableName': '',
            'itemID': tableID || '', // Our table ID (if existing table)
            'tableColumns': []
        };
    };

    /**
     * Returns form validation schema
     * @return {*}
     * */
    getFormValidationSchema = () => {
        const {dataTables, tableID} = this.props;

        return yup.object().shape({
            'tableName': yup.string()
                .default('')
                .trim()
                .test('cannot-begin-with-number', 'Cannot beging with number', value => {
                    return value.search(/^[0-9]/i) === -1;
                })
                // Validate our table name uniqueness against external list of tables
                .test('unique-name-external-across-external-list', 'Another table has same name', ourTableName => {
                    // Immutable structure
                    return dataTables.find(otherTable => {
                        return otherTable.get('name', '').toLowerCase() === ourTableName.toLowerCase()
                            && otherTable.get('itemID') !== tableID;

                    }) === undefined;
                })
                .required('Please provide a name')
                .min(2, 'Name is too short'),
            // An array of table columns
            'tableColumns': yup.array().of(
                yup.object().shape({
                        'name': yup.string()
                            .trim()
                            .default('')
                            .min(2, 'Name is too short')
                            .required('Please provide a name')

                            // An example with regexp
                            .test('cannot-begin-with-number', 'Name cannot begin with number', value => {
                                return value.search(/^[0-9]/i) === -1;
                            })
                    })
                    // Array-level validation to make sure all tableColumns have unique names
                    // Here we are running the test on the tableColumn object itself (not the 'name' field)
                    // Make sure that function is not an arrow to retain Yup's `this` context.
                    .test('columns-no-duplicate-names', 'Name is not unique', function(tableColumn) {
                        // Skip validation of pre-existing tableColumns
                        // Or where name is still empty
                        if(tableColumn.ID !== undefined || tableColumn.name === '') {
                            return true;
                        }

                        const path = this.path; // YUP path to the array item (table column object) being validated
                        const tableColumns = this.parent; // YUP-way to reference the tableColumns array itself
                        const columnIdx = tableColumns.indexOf(tableColumn); // Figure out our column index in the array of columns

                        // Check for another column with duplicate name
                        const anotherDuplicateColumn = tableColumns.find((columnOther, otherIdx) => {
                            return otherIdx !== columnIdx && columnOther.name.toLowerCase() === tableColumn.name.toLowerCase();
                        });

                        // When duplication detected, throw YUP error (that Formik will pick up)
                        if(anotherDuplicateColumn) {
                            throw this.createError({
                                path: `${path}.name`, // Path to your table column name field that is invalidated
                                message: 'Looks like a duplicate name'
                            });
                        }
                        return true; // Make sure to return true when all is valid
                    })
                )
                .min(1, 'Table needs at least one column')
        });
    };


    render() {
        return (
            <div>
                <Formik
                    initialValues={this.getDefaultFormValues()}
                    validationSchema={this.getFormValidationSchema}
                >
                    {/* Your form and inputs etc... */}
                </Formik>
            </div>
        );
    }
}

export {DataTableEditForm};
```

**Comment by ralzinov** [comment]
Just in case someone needs to combine validation schema and validate. You can run validation schema manually and combine the result with your custom logic like follows:
```
import { useFormik, yupToFormErrors } from 'formik';
...
const formik = useFormik({
    ...
    validate: async (values) => {
        const additionalErrors = runCustomLogic(values);
        try {
            await validationSchema.validate(values, { abortEarly: false });
        } catch (e) {
            return {
                ...yupToFormErrors(e),
                ...additionalErrors,
            };
        }
        return additionalErrors;
    },
    ...
});
```

**Comment by Dami-js** [comment]
Yes, you can use both concurrently. You can declare Yup validation as well as a custom validation.
For example,

```javascript
const validationSchema = Yup.object().shape({
    first_name: Yup.string().required("First name is required"),
    last_name: Yup.string().required("Last name is required"),
    email: Yup.string().email().required("Email is required"),
});

async function validate(values: typeof initialValues) {
    if (values.phone.phone.length === 0)
        return { phone: "Phone number is required" };
    const res = regex.test(values.phone.phone);
    if (!res) return { phone: "Invalid phone number" };
}

const {
    touched,
    errors,
    values,
    handleSubmit,
    getFieldProps,
    handleBlur,
    setFieldValue,
} = useFormik({
    initialValues,
    validationSchema,
    validate,
    onSubmit,
});

```

**Comment by a-fortunato** [comment]
> Yes, you can use both concurrently. You can declare Yup validation as well as a custom validation. For example,
> 
> ```js
> const validationSchema = Yup.object().shape({
>     first_name: Yup.string().required("First name is required"),
>     last_name: Yup.string().required("Last name is required"),
>     email: Yup.string().email().required("Email is required"),
> });
> 
> async function validate(values: typeof initialValues) {
>     if (values.phone.phone.length === 0)
>         return { phone: "Phone number is required" };
>     const res = regex.test(values.phone.phone);
>     if (!res) return { phone: "Invalid phone number" };
> }
> 
> const {
>     touched,
>     errors,
>     values,
>     handleSubmit,
>     getFieldProps,
>     handleBlur,
>     setFieldValue,
> } = useFormik({
>     initialValues,
>     validationSchema,
>     validate,
>     onSubmit,
> });
> ```

How are you so sure about this? Nowhere else it's mentioned that it's fine to use both at the same time.

In fact, it's mostly mentioned that it is expected to use one _or_ the other:
[Docs](https://formik.org/docs/guides/validation#form-level-validation) – "There are 2 ways to do form-level validation with Formik" 
[API](https://formik.org/docs/api/formik#validate-values-values--formikerrorsvalues--promiseany) – "Note: I suggest using validationSchema and Yup for validation. However, validate is a dependency-free, straightforward way to validate your forms."

I know these don't suggest that it's impossible, but then there's @jaredpalmer (the author)'s https://github.com/jaredpalmer/formik/issues/431#issuecomment-377082443 on this thread:  "no they were never intended to be used concurrently.", and some suggestions in the next messages on how to deal with different validations if needed a more specific approach.

If there really has been an update that allows to use both functions at the same time, it'd be nice to see it directly on the docs...

**Comment by jarep** [comment]
The Formik [documentation on submission phases](https://formik.org/docs/guides/form-submission) states that the results from `validate` and `validationSchema` are merged during the validation phase.

> Run all field-level validations, validate, and validationSchema asynchronously and deeply merge results

However, I'm unsure what will happen if both validation methods  (the `validate` and `validationSchema`) return an error for the same field. From my observations, only one error message is returned. In my case, it seems that the `validate` method has precedence; the message from this method is displayed.

Could someone please confirm?
