### ISSUE TITLE
Validation for React-Native when using Formik

### ISSUE THREAD

**Issue by myhendry** [jaredpalmer/formik#432]
As we can use Yup or custom validators to validate input fields when using React and Formik, what are the validation libraries we can use with Formik and React-Native? Can we use tcomb or react native joi or validate.js?

I searched online but can't seem to find an answer for this so I tot posting this question will get a reply which will benefit other react native users using formik. Thanks in advance!

**Comment by jaredpalmer** [comment]
Did not know that Yup didn't work in RN. I'm not currently working on an RN app right now. We should def have a solution to this prior to v1

**Comment by jehartzog** [comment]
Yup works fine with Formik on RN. Added it in a few days ago, no issues.

**Comment by jaredpalmer** [comment]
Yup is recommended (because IMHO it's the best out there). However, Formik doesn't care what you use. You can pass in your own through the `validate` prop.
