### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/formik#436]
# Roadmap to Formik 1.0:

- #422 Merge / finish <FastField> and optimize renders
- Add `meta` prop to existing Field and FieldArray (this will be a breaking change if you have fields that spread props).
- #412 Merge tweaks handleChange and handleBlur to also optionally accept the field name as an argument instead of just the synthetic event. So you can write <TextInput onChangeText={handleChange('firstName'} value={values.firstName} /> or on web <input onChange={handleChange('firstName'} value={values.firstName} />.
- Add callback / handlers for each array method in <FieldArray> (e.g. handlePush) so ppl can avoid arrow functions
- Finish docs website
  - Homepage (this is the biggest missing piece)
  - Update tooling for versioned docs
  - Update tooling for CI deployment
  - Setup DNS
- (Maybe merge #423 (big internal churn that moves to create-react-context / React 16.3 compatible context API).

## 1.0 Release process
- There will only be patches to v0.11 issued from here on out and so it will be very stable.
- Cut canary / nightly releases of v0.12 to get us through to 1.0
- Cut multiple alpha's, beta's and then release candidates's for 1.0

## Post 1.0 Release process will follow strict semver
- Minor versions will go through alpha, beta, and rc rounds
- Patches may or may not have rc's
- Codemods will be shipped to mitigate breaking changes

UPDATE:
- All that's left is the website and ironing out kinks with Field.

**Comment by boshng95** [comment]
Is there any documentation that show how we can use "handlePush" on FieldArray? It sounds like we can call this function & perform something before pushing to the FieldArray. I wanted to push the Field dynamically & make some adjustment before showing out on the interface. (Maybe my interpretation is wrong)
