### ISSUE TITLE
setTouched type error with TypeScript

### ISSUE THREAD

**Issue by wfortin** [jaredpalmer/formik#439]
## Bug, Feature, or Question?
Bug

## Current Behavior
```ts
interface FormValues {
    amount: number
}

export class MyForm extends Component<Props & FormikProps<FormValues>, State> {

	componentWillMount() {
		this.props.setTouched({amount: true})
	}
}
```

TS Error:
```
Argument of type '{ amount: true; }' is not assignable to parameter of type 'FormikTouched<FormValues>'.
  Types of property 'amount' are incompatible.
    Type 'true' is not assignable to type '(true & number) | (false & number) | undefined'.
```

## Desired Behavior
```ts
this.props.setTouched({amount: true})
```
Should be valid

## Suggested Solutions

Seems like FormikTouched type should be:
```ts
export declare type FormikTouched<Values> = {
    [field in keyof Values]?: boolean | FormikTouched<Values[field]>;
};
```
or simply
```ts
export declare type FormikTouched<Values> = {
    [field in keyof Values]?: boolean
};
```

instead of:
```ts
export declare type FormikTouched<Values> = {
    [field in keyof Values]?: boolean & FormikTouched<Values[field]>;
};
```
It's impossible to be 'true' _and_ 'number' at the same time 😄 .

This simple change fixes the compilation error.
I'll be using 
```ts
this.props.setTouched({amount: true} as any)
````

for now.

BTW, thanks for such an amazing library 🙌 . We're slowly migrating away from redux-form v2 to Formik and loving it (especially the built in TS support!)

## Info
- Formik Version: 0.11.10
- OS: MacOS 10.13.2
- Node Version: v8.9.4
- Package Manager and version: yarn v1.3.2

**Comment by prichodko** [comment]
Can you submit PR? Otherwise I can do that.

**Comment by wfortin** [comment]
I'll submit a PR yes.
