### ISSUE TITLE
Auto touch on submit

### ISSUE THREAD

**Issue by fkrauthan** [jaredpalmer/formik#445]
## Bug, Feature, or Question?
Feature/Question

## Current Behavior
I only show error messages when a field is touched and has a error message. The problem when clicking submit it should show error messages for all fields but since they are not getting marked as touched no error shows up

## Desired Behavior
When emitting the handleSubmit event all fields in the form should be touched/there should be a flag that indicates if the form was submitted and not reseted.

- Formik Version: 0.11.10
- OS: Mac OS
- Node Version: v9.5.0
- Package Manager and version: Yarn 1.3.2

**Comment by jeffbski** [comment]
I agree. I just ran into this as well. 

When we are submitting, we want the invalid fields to display their errors, so they should automatically be touched.

**Comment by jeffbski** [comment]
Seems like even if I manually have called setFieldsTouched on the fields, then when handleSubmit is called it is clearing out the touched object so then the errors don't show.

**Comment by jeffbski** [comment]
It looks like the problem occurs when initialValues are not specified. 

So when handleSubmit calls setNestedObjectValues with the values, they are {} and so does an Object.keys(values) and comes up with none. 

So touched is returned as {}

When using yup schema it should get the fields to touch from the schema rather than the initialValues object.

**Comment by fkrauthan** [comment]
I think solutions could be as follow:

1. Use the error object keys to populate touched
1. Use the submitted value object keys to populate touched
1. Add a separate field to specify form fields (with API methods to dynamically add or remove fields)
1. Add a flag that is true when the form is submitted and gets reseted to false when form gets reseted

All 4 solutions would fix this issue. The last one is probably the easiest to implement.

**Comment by jaredpalmer** [comment]
This behavior exists in formik. All fields are set to touched before submit.

**Comment by jaredpalmer** [comment]
initialValues are required and should always be specified

**Comment by jaredpalmer** [comment]
It cannot depend on schema because not al users use schema validation

**Comment by jeffbski** [comment]
@jaredpalmer when a developer does use validationSchema then obviously that can allow formik to know the fields, so if that is supplied it could be used by formik. No it is not required, but frankly I appreciate the value of yup and even the special optional support by formik, so it wouldn't be wrong to use the schema if it is provided. 

formik + yup = fantastic

The fact that you provide this as an option gives it an advantage over the other competitors.

**Comment by fkrauthan** [comment]
@jaredpalmer The documentation only states that `initialValue` should be used to prevent possible form state management issues (which in my case do not exist as I use custom forms). Based on what you state you should make clear in the documentation that initialValue is REQUIRED regardless as there is logic (like form submit) based on it. I still think any of my four suggestions would work as well without breaking the current version of the library but give additional flexibility to developers.

**Comment by lucasbento** [comment]
> @jaredpalmer: initialValues are required and should always be specified

[The `README.md` states that it's optional](https://github.com/jaredpalmer/formik/blob/56dd5987955e61fa482989b4b0768d0d67b56677/README.md#initialvalues-values), is it a typo then?

**Comment by armand1m** [comment]
I'm using the `withFormik`  hoc, and there is no initialValues prop. I tried using `mapPropsToValues` but still it doesn't works as expected :/

**Comment by armand1m** [comment]
Well, after using `mapPropsToValues`  I got a quite different behavior:

- If none of the fields were touched, clicking on submit *dont* shows any errors. (which is wrong)
- If the fields were touched, but no values inserted, and error messages are already showing up, clicking on submit *clears* any errors  (which is wrong)
- If the fields were touched, values were inserted and cleaned up, and error messages are already showing up, clicking on submit *dont clears* any errors (which is ok)

Given that, it seems that the touched logic is quite misleading or wrong?

**Comment by johnculviner** [comment]
After digging into this one for a little bit I think the main reason this is an issue is because Formik doesn't know about the field to set as touched unless you set it on initialValues.

The only partial solution I can think of is to have ```<Field>``` (and not everyone uses field) tell Formik about it's self even though it has never set a value or have another mechanism in which to tell Formik about fields that haven't gone through setFieldValue yet.

 I'm just doing ```initialValues={{ohWell: '' }}``` and calling it a day for now.

**Comment by flybayer** [comment]
Yeah this is super confusing. I spent a good while wondering why validation on submit wasn't working before finding this thread.

**Comment by miketeix** [comment]
In my case I'm using material-ui Textfield which has the label as placeholder and animates it to the top of the input when a value is inserted. By using initialValues I lose all that.

It would be great if Formik could figure out which fields to touch other than using initialValues.

**Comment by charlax** [comment]
See #691 as well.

**Comment by AndyCrisan** [comment]
It's a little painful cause in react-native there is no support for <Field/> to have the fields touched onSubmit. Is there a workaround for react-native tho?

**Comment by Solavon** [comment]
Any updates regarding this issue?

**Comment by jaredpalmer** [comment]
initialValues are required.

**Comment by Solavon** [comment]
@jaredpalmer Thank you for the reply, after reading into it more, the behavior that I want given my situation can be achieved by checking the submitCount.
Have a nice day!

**Comment by RiccardoCampitelli** [comment]
I've been using this to set my fields to touched
```ts

  const getTouchedObj = (errors: any) => {
    const touched: any = {}
    Object.keys(errors).map(key => {
      if (Array.isArray(errors[key])) {
        errors[key].map((val: any, index: any) => {
          touched[key] = [];
          touched[key].push(getTouchedObj(val));
        });
      } else {
        touched[key] = true;
      }
    });

    return touched;
  };

```

so in my submit I just call 

```ts
setTouched(getTouchedObj(errors))
```

I'm pretty new to this so feedback or better ideas are very appreciated 👍

**Comment by AbdelhalimKhouas** [comment]
Fields that aren't in the initialValues (for exp dynamic fields) object won't be present in "touched" object, when you click submit the touched field will only contain fields that are present in initialValues, for example:
in the example below you will see the errors when submitting and if you check the touched object you will find {name: true, email: true} 
`<Formik
                enableReinitialize
                initialValues={{
                 name :"",
                 email: ""
               }}
                validationSchema={validationSchema}
                onSubmit={(values) => {
                    console.log('%c⧭', 'color: #731d6d', values);
                  }
                }        
            >`

but in this next example let's assume you will push fields into an array you don't know what fields will be in so the array is initially empty:
`
var myFields = []
<Formik
                enableReinitialize
                initialValues={{
                 fields: myFields
               }}
                validationSchema={validationSchema}
                onSubmit={(values) => {
                    console.log('%c⧭', 'color: #731d6d', values);
                  }
                }        
            >
`

after pushing fields for example name and email into myFields and click submit the fields won't be present in initial values and nor in touched that's why you won't see errors.
in that case you should use errors object

**Comment by Srikrishnan96** [comment]
> This behavior exists in formik. All fields are set to touched before submit.

Is there any way I can overwrite this behavior ... I have a case where I must validate only fields that are actually touched on submitting

**Comment by DinAlla** [comment]
> I've been using this to set my fields to touched
> 
> ```ts
>   const getTouchedObj = (errors: any) => {
>     const touched: any = {}
>     Object.keys(errors).map(key => {
>       if (Array.isArray(errors[key])) {
>         errors[key].map((val: any, index: any) => {
>           if(index == 0)  touched[key] = [];
>           touched[key].push(getTouchedObj(val));
>         });
>       } else {
>         touched[key] = true;
>       }
>     });
> 
>     return touched;
>   };
> ```
> 
> so in my submit I just call
> 
> ```ts
> setTouched(getTouchedObj(errors))
> ```
> 
> I'm pretty new to this so feedback or better ideas are very appreciated 👍

So, where you get error object? As I understand you call setTouched into function onSubmit, but I don't know where get this?

**Comment by RiccardoCampitelli** [comment]
@DinAlla 
If I remember correctly the errors are available inside the <Formik /> component like this: 

```js

<Formik
 initialValues={yourInitialValues}
onSubmit={yourHandleSubmitMethod}
>
    {({ errors, ...andLotsOfOtherStuff }) => (
          //form markup goes here
       )
    }
</Formik>


```

Hope this helps!

**Comment by StudioSpindle** [comment]
@DinAlla I guess what you can do is save the error in state, and then use it in that handler:

```
const getTouchedObj = (errors: any) => { ... }

const MyForm = () => {
  const [validationErrors, setValidationErrors] = useState();

  return (
    <Formik
      onSubmit={(values, formikBag) => {
        if (validationErrors) {
          formikBag.setTouched(getTouchedObj(validationErrors));
        }
        handleSubmit(values);
      }}
     >
     {(formik) => {
       const { errors } = formik;
       // set the errors here
       setValidationErrors(errors);
     }
   );
};
  >
)
```

But this is getting messy...

**Comment by linjj93** [comment]
> I'm using the `withFormik` hoc, and there is no initialValues prop. I tried using `mapPropsToValues` but still it doesn't works as expected :/

I am having the same issue as well. Anyone managed to get it to work while using `withFormik` hoc?

**Comment by petr-ujezdsky** [comment]
I just hit this 'issue' as well. To be honest, making initial values mandatory is a bit error-prone. You can forget to do it and no error is thrown to indicate your fault.

I have written my own validation library (without knowing `Formik` exists) and I actually used the same principles.

I have also hit the same problem - I did not know which fields the form has during `onSubmit` validation. **I have solved it by using 'proprietary' error field `all`**. Then eg. the field `firstName` is touched when `touched.firstName || touched.all` instead of just `touched.firstName`. You set `touched.all` to `true` on submit, making all the fields "touched" without knowing their names.

Next the `all` flag should be stored outside the `error` object to allow usage of `all` field if it exists (I did it for simplicity).

**Comment by konrad-garus** [comment]
Here's a patch that seems to achieve it:

```
import flatten from 'flat';
const FormikPatchTouched = () => {
  const { errors, setFieldTouched, isSubmitting, isValidating } = useFormikContext();
  useEffect(() => {
    if (isSubmitting && !isValidating) {
      for (const path of Object.keys(flatten(errors))) {
        setFieldTouched(path, true, false);
      }
    }
  }, [errors, isSubmitting, isValidating, setFieldTouched]);
  return null;
};
```

```
<Formik>
  {() => {
    return (
      <Form>
        <FormikPatchTouched />
        {/* ... */}
      </Form>
    )
  }}
</Formik>
```

**Comment by dvprrsh** [comment]
@konrad-garus Your solution seems to work for me also

**Comment by brockklein** [comment]
> Here's a patch that seems to achieve it:
> 
> ```
> import flatten from 'flat';
> const FormikPatchTouched = () => {
>   const { errors, setFieldTouched, isSubmitting, isValidating } = useFormikContext();
>   useEffect(() => {
>     if (isSubmitting && !isValidating) {
>       for (const path of Object.keys(flatten(errors))) {
>         setFieldTouched(path, true, false);
>       }
>     }
>   }, [errors, isSubmitting, isValidating, setFieldTouched]);
>   return null;
> };
> ```
> 
> ```
> <Formik>
>   {() => {
>     return (
>       <Form>
>         <FormikPatchTouched />
>         {/* ... */}
>       </Form>
>     )
>   }}
> </Formik>
> ```

This is a great "fix it all" solution. 

If you want to be a bit more targeted and only patch the fields without an initial value (e.g. dynamically added fields from a `<FieldArray />`), you can make use of `submitCount` and set `touched` for those fields equal to `submitCount > 0`.

**Comment by ShimiShimson** [comment]
> initialValues are required and should always be specified

If so it would be nice to update Formik docs, it's still marked as optional there

**Comment by yizumi1012xxx** [comment]
> > I've been using this to set my fields to touched
> > ```ts
> >   const getTouchedObj = (errors: any) => {
> >     const touched: any = {}
> >     Object.keys(errors).map(key => {
> >       if (Array.isArray(errors[key])) {
> >         errors[key].map((val: any, index: any) => {
> >           if(index == 0)  touched[key] = [];
> >           touched[key].push(getTouchedObj(val));
> >         });
> >       } else {
> >         touched[key] = true;
> >       }
> >     });
> > 
> >     return touched;
> >   };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so in my submit I just call
> > ```ts
> > setTouched(getTouchedObj(errors))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm pretty new to this so feedback or better ideas are very appreciated 👍
> 
> So, where you get error object? As I understand you call setTouched into function onSubmit, but I don't know where get this?

I try this code, and I encountered some error.
- cannot parse nest array structure (e.g. `formik.values = { xxx: { yyy: string }[][] }` )
- cannot parse nest object structure  (e.g. `formik.values = { xxx: { yyy: string } }` )

I fix `getTouchedObj()` function.

```diff
const getTouchedObj = (errors: any) => {
+  if (Array.isArray(errors)) {
+    const touched: any = []
+    errors.map((val: any) => {
+      touched.push(getTouchedObj(val))
+    })
+    return touched
+  }
  const touched: any = {}
  Object.keys(errors).map(key => {
    if (Array.isArray(errors[key])) {
      errors[key].map((val: any, index: any) => {
        if (index == 0) touched[key] = []
        const ret = getTouchedObj(val)
        touched[key].push(ret)
      })
+    } else if (typeof errors[key] !== 'string') {
+      touched[key] = getTouchedObj(errors[key])
    } else {
      touched[key] = true
    }
  })
  return touched
}
```

**Comment by cl-yklilich** [comment]
Maybe if you added required attribute or any default browser validation into an input, you have to add noValidate to the form tag
this actually solved my problem. @fkrauthan

**Comment by yassine-klilich** [comment]
If you are using required attribute or any default browser validation on an input, you have to add noValidate on the form tag, this actually solved my problem, when I submit without touching any input it validate and mark input as touched. @fkrauthan

**Comment by shahidcodes** [comment]
If you're wondering why validations are not working on submit, then you might be setting formik values to null or empty object

**Comment by furdzik** [comment]
Maybe it will help someone.

In my case (using yup for validation), I needed to define `initialValues` for separate fields like that:
```
initialValues: {
  name: null,
  surname: null,
  phone: null
};
```
And then it worked as I wanted.

I needed to automatically set all fields as touched when I tried to send field without required fields (to show required fields errors only when submitting without it or after blur on specific field).

**Comment by kanonirbrest** [comment]
Hey guys I found the source of this problem. When you push new arguments to array you should use for example (Use the `JSON.stringify()` and `JSON.parse())` to create copy of array and object after set it to formik. In case if you will create 
`const default = {name: 'name'};` and then do formik.setFieldValue('path', [default, ...formik.values.path]) 2 or 3 times, the touch will ignore last copy. As i understand there are incorrect comparison for objects the has the same source. Hope it will help you. For me `JSON.stringify()` and `JSON.parse())` resolved all problems with validation.
Let me know whether it helps you.

**Comment by thautinvio** [comment]
Thanks @kanonirbrest It's working

**Comment by buithanhnhan76** [comment]
In my case, the problem is that I not call the formik.submitForm() method

**Comment by wangjw219** [comment]
If a field's value  is set to be undefined, then it won't be marked as touched
