### ISSUE TITLE
[1.0] setX does not update FastField

### ISSUE THREAD

**Issue by AaronW9090** [jaredpalmer/formik#448]
## Bug, Feature, or Question?

Bug(s)

## Current Behavior

1. FastField's will not update their state when using imperative 'setX' functions or resetting the form to the initial state.

2. Whenever a FastField is blurred without having a validate function or when validateOnBlur is false it will set the error for that field on the Formik state to undefined, regardless of what the Formik error is. It also doesn't use the Formik validate function or validationSchema when validate isn't given as a prop.

## Desired Behavior

1. FastField's state should be kept in line the Formik state.

2. Error object shape should be the same as previous versions. Also the Formik validate function should be run on blur if a validate function isn't defined on the FastField but validateOnBlur is true. 

## Suggested Solutions

1. Putting a componentWillReceiveProps in FastField that listens for any change to the Formik state and sync's up the FastField state should work. This could be destructive of the field's state as the Formik state should be the source of truth for all values and errors (unless you are typing inside the field).

2. This issue will be half-fixed when the above issue is, although when the field doesn't have an error it will add the field to the Formik errors object with a value of 'undefined'. This could very well be desired behaviour but I have been assuming that if the key doesn't exist on the errors object then there is no error for that field, in line with how the logic was in previous versions. I imagine having the same logic as 'handleChange' when it comes to validating with the Formik validation and validationSchema will solve the rest of the issue as well.

## Info
 

- Formik Version: 1.0.0-alpha.1
- OS: Mac OSX High Sierra
- Node Version: 8.9.1
- Package Manager and version: Webpack

**Comment by jaredpalmer** [comment]
Thanks for the report. Will take a stab at this in a few hours

**Comment by jaredpalmer** [comment]
@AaronW9090 would this solve the problem?


```tsx

  componentWillReceiveProps(
    nextProps: Props,
    nextContext: { formik: FormikProps<any> }
  ) {
    const nextFieldValue = getIn(nextContext.formik.values, nextProps.name);
    const nextFieldError = getIn(nextContext.formik.errors, nextProps.name);

    let nextState: any;

    if (nextFieldValue !== this.state.value) {
      nextState = { value: nextFieldValue };
    }

    if (nextFieldError !== this.state.error) {
      nextState = { ...nextState, error: nextFieldError };
    }

    if (nextState) {
      this.setState(s => ({ ...s, ...nextState }));
    }
  }
```

**Comment by AaronW9090** [comment]
Yep I'd say so. This is exactly what I had in mind.

This will make FastField slower than Field when using setX or resetForm but I can't see any other way around that right now. I doubt it will matter much anyway.

**Comment by jaredpalmer** [comment]
@AaronW9090 Are you calling setValues or setFieldError? I wonder if FastField should pass it's own setFieldX

**Comment by jaredpalmer** [comment]
@AaronW9090 i'm pretty sure i can get rid of registerField now. CWRP will just update local state now.

**Comment by AaronW9090** [comment]
@jaredpalmer I'm using both setX and setFieldX. Yeah registerField will actually stop the FastField from getting it's correct initialValue back and instead always reset it to undefined.

What does FastField passing it's own setFieldX look like? I'm just not sure of the benefit you would get since you have to update Formik state at the same time anyway to keep the states synchronised since it's not guaranteed that the field will be focused when updating it's value imperatively. You could avoid a second re-render of just the FastField that is updated using a pattern similar to the current registerField but everything else re-renders anyway so the perf improvement is minimal.

Also I may have accidentally implied that this CWRP fix will fix the onBlur validation issue as well which is not the case, would you like me to open up a separate issue for that problem?

**Comment by jaredpalmer** [comment]
Yeah open a separate one
