### ISSUE TITLE
Overloaded methods break type safety

### ISSUE THREAD

**Issue by Shurelia** [jaredpalmer/formik#453]
## Bug, Feature, or Question?
Bug

## Current Behavior
Due to the overloaded function definitions for `setFieldValue` [here](https://github.com/jaredpalmer/formik/blob/fde20a6ef323f789a6cb591f081ef00cd91273bc/src/Formik.tsx#L100), when a strict match is not found it falls back to the unsafe overloaded definition, which will take any field string and any value. This can lead to difficult to debug logic errors.

## Desired Behavior
If the `field` passed to `setFieldValue` is not a key on `Values`, an error should be thrown. If the data type passed as the value does not match the data type defined for that key, an error should be thrown.

## Suggested Solutions
PR: https://github.com/jaredpalmer/formik/pull/454

- Formik Version: 0.11.11
- React Version: 16.0.0
- TypeScript Version:  2.7.2
- CodeSandbox Link: [https://codesandbox.io/s/3yx632on3q](https://codesandbox.io/s/3yx632on3q)
- OS: Win10
- Node Version: 8.9.4
- Package Manager and Version: yarn 1.3.2

**Comment by jaredpalmer** [comment]
Brilliant
