### ISSUE TITLE
[1.0]  <FastField/> value doesn't update if no errors are found from validationschema

### ISSUE THREAD

**Issue by STenorio99** [jaredpalmer/formik#455]
## Bug, Feature, or Question?
Bug

## Current Behavior
https://github.com/jaredpalmer/formik/blob/fde20a6ef323f789a6cb591f081ef00cd91273bc/src/FastField.tsx#L177-L180

I found that when using validationschema for a form, `<FastField/>` doesn't update if there are no validation errors. I don't think this is intended?

After extending FastField to a component and copying the functions it depends on over, I was able to pinpoint the issue to the code above. 

The value gets set in the catch block but not in the try block.

## Desired Behavior
  `<FastField/>` value state should update even when there are no validation errors

## Suggested Solutions
  Set the value state after `validateYupSchema(...)`

## Info

- Formik Version: 1.0.0-alpha.1
- React Version: 16.2.0
- Node Version: 9.5.0
- Package Manager and Version: Webpack 3

**Comment by jaredpalmer** [comment]
Can you submit a PR?

**Comment by pierre-H** [comment]
The FastField actually update the field error but not the form.isValid prop value.
Is it normal ?
