### ISSUE TITLE
Manually handle the `onChange`?

### ISSUE THREAD

**Issue by FezVrasta** [jaredpalmer/formik#456]
## Bug, Feature, or Question?
Question/Feature?

## Current Behavior

I have a custom dropdown component that returns on `onChange` just the array of selected options. I can't find a way to make it play nicely with Formik.

## Desired Behavior

I'd like to be able to manually handle the `onChange` call so that I can manually define which field is being modified and with what data.

## Suggested Solutions

Something like:

```
handleChangeManually({
  name: 'something',
  value: [1, 2, 3]
});
```

**Comment by jaredpalmer** [comment]
You can use `setFieldValue('something', [1,2,3])` and wrap your input in a custom component.

**Comment by FezVrasta** [comment]
Ah thanks!

**Comment by ez-dev** [comment]
setFieldValue nicely solved most of my problems except one. It doesn't mark the field as touched and so <ErrorMessage ... /> doesn't behave as expected.

**Comment by nidamunir** [comment]
use setFieldTouched after setFieldValue, if you want to mark the field as touched.

**Comment by Skand17** [comment]
Setfieldvalue will work but how we will manage yup validations ?

**Comment by stilllife00** [comment]
On my custom component I did:

```
onChange(val) {
    this.props.form.setFieldValue(this.props.name, val, true);
    this.props.form.setFieldTouched(this.props.name, true, false);
}
```

in order to trigger the change and also the validation, and the ErrorMessage shows up correctly

The `onChange` prop of the Form (Formik) though, does not seem to trigger

**Comment by nidamunir** [comment]
@stilllife00 try calling handleChange prop of formik in your onChange.

**Comment by tavareshenrique** [comment]
How do I use setFieldValue with Hooks?
