### ISSUE TITLE
I do not agree that validation should be initiated with setState callback

### ISSUE THREAD

**Issue by madebytilde** [jaredpalmer/formik#459]
I do not agree that validation should be initiated with setState callback (after the value is set to state), because it comes to the point where a field has neither value nor error, as in the following example, point two (II)… I think that state should be updated with new values only after we have validation results…

I. State before deleting the letter "a"
{
  value: "a",
  error: undefined,
}
II. State after deleting the letter "a"
{
  value: undefined,
  error: undefined,
}
III. State after deleting the letter "a"
{
  value: undefined,
  error: "Error message",
}

**Comment by jaredpalmer** [comment]
State 2 and 3 value is not undefined, but an empty string. The big problem is waiting for long running validation. Your argument makes sense as long as validation take less than ~50ms. Perhaps a compromise would be to race such a timer and validation. If timer wins, then set state with the value and use the callback for the error. If validation wins, setState as one.
