### ISSUE TITLE
[1.0] No validation onBlur when using FastField and not using validate prop

### ISSUE THREAD

**Issue by aaronnuu** [jaredpalmer/formik#460]
## Bug, Feature, or Question?
Bug

## Current Behavior
Whenever a FastField is blurred without having a validate function or when validateOnBlur is false it will set the error for that field on the Formik state to the field's current error state, which unless validateOnChange is true will always be undefined. It doesn't use the Formik validate function or validationSchema when validate isn't given as a prop to the FastField.

## Desired Behavior
The Formik validate function should be run on blur if a validate function isn't defined on the FastField but validateOnBlur is true.

## Suggested Solutions
The logic for validating on blur should be the same as when validating on change - by using the top level validate function or validation schema if a validate prop is not supplied to the FastField.

---

- Formik Version: 1.0.0-alpha.1
- React Version: 15.5
- TypeScript Version: N/A
- CodeSandbox Link: N/A
- OS: Mac OSX High Sierra
- Node Version: 8.9.1
- Package Manager and Version: Webpack

**Comment by gunn4r** [comment]
Well it DOES say it needs a refactor... haha..
But yeah, I am running into same issue.

`// @todo refactor
    if (validateOnBlur && validate) {
      const maybePromise = (validate as any)(this.state.value);
      if (isPromise(maybePromise)) {
        (maybePromise as Promise<any>).then(
          () =>
            setFormikState((prevState: any) => ({
              ...prevState,
              values: setIn(prevState.values, name, this.state.value),
              errors: setIn(prevState.errors, name, undefined),
              touched: setIn(prevState.touched, name, true),
            })),
          error =>
            setFormikState((prevState: any) => ({
              ...prevState,
              values: setIn(prevState.values, name, this.state.value),
              errors: setIn(prevState.errors, name, error),
              touched: setIn(prevState.touched, name, true),
            }))
        );
      } else {
        setFormikState((prevState: any) => ({
          ...prevState,
          values: setIn(prevState.values, name, this.state.value),
          errors: setIn(prevState.errors, name, maybePromise),
          touched: setIn(prevState.touched, name, true),
        }));
      }
    } else {
      setFormikState((prevState: any) => ({
        ...prevState,
        errors: setIn(prevState.errors, name, this.state.error),
        values: setIn(prevState.values, name, this.state.value),
        touched: setIn(prevState.touched, name, true),
      }));
    }
`
