### ISSUE TITLE
Update field values from outside and rerun validation

### ISSUE THREAD

**Issue by kennyx46** [jaredpalmer/formik#463]
## Bug, Feature, or Question?
Question

## Current Behavior
`mapPropsToValues` updates the form values only once if `enableReinitialize` is `false`. Is this correct behaviour? Should I always set it to true to make `mapPropsToValues` update form every time?

 Also updating props via `mapPropsToValues` does not run the validation. Is this expected behaviour?
How can I run the validation manually?

- Formik Version: 0.11.11
- React Version: 16.2.0
- OS: MacOS Sierra
- Node Version: v9.3.0
- Package Manager and Version: yarn 1.3.2

**Comment by jaredpalmer** [comment]
^^ correct, 

there is a PR open for a new onReinitialize prop. Would solve lots of use cases
