### ISSUE TITLE
setFieldTouched at React Native

### ISSUE THREAD

**Issue by giovanischiar** [jaredpalmer/formik#464]
## Bug, Feature, or Question?
Question

## Additional Information
I'd like to use setFieldTouched because handleBlur isn't supported at RN but I can't figure it out how to use properly, can please show me an example how to use?

---

- Formik Version: 0.11.11
- React Version: 16.2.0
- TypeScript Version: 2.7.1
- OS: Ubuntu: 16.04
- Node Version: 8.9.4
- Package Manager and Version: yarn 1.3.2

**Comment by Andreyco** [comment]
Basically like this

```
<Field name="email">
  {({ field, form }) => (
    <TextInput
      value={field.value}
      onChange={value => form.setFieldValue('email', value, true)}
      onBlur={() => form.setFieldTouched('email', true, true)}
    />
  )}
</Field>
```
