### ISSUE TITLE
what is the difference between using formik or just reactjs itself?

### ISSUE THREAD

**Issue by adamchenwei** [jaredpalmer/formik#465]
## Current Behavior
seems just as if I am writing the whole form.... nothing much less

## Suggested Solutions
Not really sure, what exactly is the difference by using formik makes?
What is the advantage for using this? Please be concrete with some example scenarios, if possible!
Thank you for writing a open source goodie!
## Additional Information

---

- Formik Version: latest
- React Version: latest
- TypeScript Version: n/a
- CodeSandbox Link: n/a
- OS: 
- Node Version:
- Package Manager and Version:

**Comment by pgrekovich** [comment]
@adamchenwei hi, can you write simple example like this - https://codesandbox.io/s/q8yRqQMp, on the pure react? and we will compare :)

**Comment by stefanwille** [comment]
The README says it nicely:

> Formik is a small library that helps you with the 3 most annoying parts:
>
> * Getting values in and out of form state
> * Validation and error messages
> * Handling form submission

Once you write even a simple example like a contact form in plain React and then in Formik, you will appreciate this library.

**Comment by adamchenwei** [comment]
I actually DO appreciate it now! VERY VERY VERY NICE way to abstract form evaluations from the form and extremely flexible. LOVING IT!!!

Thank you @jaredpalmer and contributors!
