### ISSUE TITLE
Linked selects: values not reflecting the view 

### ISSUE THREAD

**Issue by srosca** [jaredpalmer/formik#468]
## Question?
I have 2 linked selects. What that means is the options in the second one are depended on the values from the first one
https://codesandbox.io/s/x76v4x84kw

## Current Behavior
When I change the first select the values for the second one are not changed even if the options are no longer valid.
The view is updated but not the values. 
This can lead to strange behaviors since the values are not in sync with the view

## Desired Behavior
I would like the second select to change to empty or the first value like the view is working
The most important thing is to have sync between the view and the values

## Suggested Solutions

Not sure I might have the wrong setup

---
- Formik Version: 0.11.11
- React Version: 16.2.0
- CodeSandbox Link: https://codesandbox.io/s/x76v4x84kw

**Comment by latviancoder** [comment]
It's a guess, but I think formik has no idea about those dependencies.

What about trying something like this?

```
<select
        name="select1"
        value={values.select1}
        onChange={e => {
          setFieldValue('select2', '');
          handleChange(e);
        }}
        onBlur={handleBlur}
      >
```

**Comment by kkashou** [comment]
@srosca - Did you ever find a solution for this ? Since I am kind of trying to do the same thing base off the first selection to populate the next drop down data.

**Comment by srosca** [comment]
@kkashou We didn't useFormik in the end but you could handle the change manually like suggested: https://codesandbox.io/s/w7ry6kpqp8

**Comment by kkashou** [comment]
@srosca - Thank you! I was trying to find an example of ajax calls base on the initial selection.
