### ISSUE TITLE
Using yup schema with 'global' errors

### ISSUE THREAD

**Issue by jakow** [jaredpalmer/formik#469]
## Bug, Feature, or Question?
Feature

## Current Behavior
When you specify top level Yup schema using object().shape(...), Formik populates props using validation errors originating from the respective field name: `props.errors[fieldName]`. However, in some cases (e.g. when expressing interdependencies between fields: "this or that must be selected"), it is useful to supply a `.test()` function on the top level schema itself.

```
Example:
object().shape({
  foo: boolean(),
  bar: boolean(), 
}).test('example', 'Select either option', values => values.foo || values.bar); 
```

Currently, Formik does not understand those errors. This is because `props.errors` are bound to particular field name and as far as I know there is no 'form-level' errors. When Formik runs validation of the above schema, we get an object like:
```
{
"undefined": "Select either option"
}
```

## Desired Behavior
Top-level schema errors should be available on Formik props.

## Suggested Solutions

An example solution would be to expose form-level errors prop (`formErrors`) to catch those errors in a transparent and clean manner. 

## Additional Information
- Formik Version: 0.11.10
- React Version: 16.2.0
- TypeScript Version: 2.7.2
- OS: MacOS
- Node Version: 8.9.4
- Package Manager and Version: npm 5.6.0

**Comment by jaredpalmer** [comment]
I would use a custom validation function here. Yup is not meant to cover 100% of use cases. It's just for around ~80-90%.

**Comment by elijah-schow** [comment]
@jaredpalmer I have a similar need. Could I use both `validate` and `validationSchema` at the same time? Writing a custom validator function just isn't feasible. That would take hundreds if not a thousand lines of error-prone code. I don't have time for that, and I already wrote a working `yup` schema.

**Comment by eeriee** [comment]
Will this be fixed instead of using the `status`?
