### ISSUE TITLE
Question: FieldArray does not validate on focus out and handle submit when there is only one item

### ISSUE THREAD

**Issue by marcoroganovic** [jaredpalmer/formik#472]
## Bug, Feature or Question?
Question

## Current Behavior 
Hi there, has anyone encountered similar behavior? Could be because of misuse of library since I've started to use it only a couple days ago, but it's working perfectly when there is more than one item to be validated. Just to note, I'm using Yup for schema validation.

## Desired Behavior
To work on all fields, regardless of number.

## Suggested Solution

- Formik Version: 1.0.0-alpha.2
- React Version: 6.2.0
- TypeScript Version:
- CodeSandbox Link:
- OS: MacOS
- Node Version: 8.9.1
- Package Manager and Version: npm 5.6.0

**Comment by latviancoder** [comment]
I am also new to this library, and I am also currently working on an example with using `<FieldArray>`. I didn't experience any of the problems you mentioned.

Here is code for an example I am currently working on, it works just fine. Sorry, I don't have time to make a codesandbox example.

```
import React from 'react';
import { Form, Field, FieldArray, FormikProps, withFormik, getIn } from 'formik';
import { object, string, array } from 'yup';

interface Friend {
    what: string;
    age: string;
}

interface FormValues {
    friends: Array<Friend>;
}

interface ErrorMessageProps {
    name: string;
}

const ErrorMessage = ({name}: ErrorMessageProps) => (
    <Field
        name={name}
        render={({form}) => {
            const error = getIn(form.errors, name);
            const touch = getIn(form.touched, name);
            return touch && error ? error : null;
        }}
    />
);

const InnerForm = (props: FormikProps<FormValues>) => {
    const {
        values
    } = props;

    return <Form>
        <FieldArray
            name="friends"
            render={arrayHelpers => (
                <div>
                    {values.friends.map((friend, index) => (
                        <div key={index}>
                            <Field name={`friends.${index}.what`}/>
                            <ErrorMessage name={`friends.${index}.what`}/>
                            <Field name={`friends.${index}.age`}/>
                            <ErrorMessage name={`friends.${index}.age`}/>
                            <button
                                type="button"
                                onClick={() => arrayHelpers.remove(index)}
                            >
                                -
                            </button>
                        </div>
                    ))}
                    <button
                        type="button"
                        onClick={() => arrayHelpers.push({what: '', age: ''})}
                    >
                        +
                    </button>
                    <div>
                        <button type="submit">Submit</button>
                    </div>
                </div>
            )}
        />
    </Form>;
};

const ArrayFieldExample = withFormik({
    mapPropsToValues: (): FormValues => ({
        friends: [
            {what: 'Wuhuuu', age: '20'},
            {what: 'Albala', age: '30'},
        ]
    }),
    validationSchema: object().shape({
        friends: array().of(
            object().shape({
                what: string().required('what required'),
                age: string().required('age required')
            })
        )
    }),
    handleSubmit: (values) => {
        alert(JSON.stringify(values));
    },
})(InnerForm);

export default ArrayFieldExample;
```

**Comment by marcoroganovic** [comment]
Hey, thank you for reply, my code looks almost identical except that I've extracted JSX that you have in `map` method to separate component and passed necessary field names to it and it doesn't work, only after I pass actual `values` object as a prop it starts validating.

**Comment by marcoroganovic** [comment]
Just tried on CodeSandbox similar example and everything works, there is no problems that I've mentioned, I'm probably misusing it somehow. Never mind, thanks for response.

**Comment by jaredpalmer** [comment]
Can I close this?

**Comment by marcoroganovic** [comment]
Yes.

**Comment by abelkbil** [comment]
@latviancoder Thanks for sharing. Your code works perfect in typescript

**Comment by Nogaeman** [comment]
error message not work in array of string and array of object 
this is my code whats wrong of it ?

import React, { Component } from 'react';
import {Formik , Field , ErrorMessage , FieldArray} from 'formik';
import * as Yup from 'yup';
import './App.css';

class App extends Component {
  onSubmit = (values) =>{
    console.log(values);
  }

  renderfonrm= (probs) => {
   return <form onSubmit={probs.handleSubmit}>
     
    





    


    

     
     
      <FieldArray name="friends" render={arrayhelper=>(
        <div>
          {probs.values.friends.map((item,index)=>(
            <div key={index}>
                <Field name={"friends.${index}"} value={item}></Field>
                <button type="button" onClick={()=>arrayhelper.remove(index)}>-</button>
                <br></br>
                <span className="errorspan"><ErrorMessage name={'friends.${index}'}></ErrorMessage></span>
           </div>
          ))}
          <button type="button" onClick={()=>arrayhelper.push("")}>+</button>
        </div>
         
      )}></FieldArray>
     <br></br>

     <FieldArray name="Userdata" render={arrayhelper=>(
        <div>
          {probs.values.Userdata.map((item,index)=>(
            <div key={index}>
                ID : <Field name={"friends.${index}.id"} value={item.id}></Field>
                Name : <Field name={"friends.${index}.name"} value={item.name}></Field>
                <button type="button" onClick={()=>arrayhelper.remove(index)}>-</button>
                <br></br>
                 <ErrorMessage name={`friends.${index}.id`}/>
                 <ErrorMessage name={`friends.${index}.name`}/>
               
                <br></br>
                <span className="errorspan"><ErrorMessage name={'friends.${index}'}></ErrorMessage></span>
           </div>
          ))}
          <button type="button" onClick={()=>arrayhelper.push({id :'',name:''})}>+</button>
        </div>
         
      )}></FieldArray>
     <br></br>
     <button type='submit'>Send</button>
   </form>
  }

  
  schema = ()=>
  {    
      const schema = Yup.object().shape({    
        friends:Yup.array().of(
          Yup.string().required('Enter Friend name'),
        ),
        Userdata:Yup.array().of(
          Yup.string().required('Enter data'),
        )
      })
     return schema;
  }

  render() {
    return (
      <div className="App">
       <Formik
           initialValues={{       
              friends :["x","y","z","c","v"],
              Userdata : [
                {id : '1' , name : 'z'},
                {id : '2' , name : 'x'},
                {id : '3' , name : 'c'},
                {id : '4' , name : 'v'},
                {id : '5' , name : 'b'}
              ]
            }}
           onSubmit={this.onSubmit}
           render={this.renderfonrm}
           validationSchema={this.schema()}>
           </Formik>
      </div>
    );
  }
}

export default App;
