### ISSUE TITLE
Submitted values should be driven from DOM rather than internal Form state

### ISSUE THREAD

**Issue by sdoxsee** [jaredpalmer/formik#474]
## Bug, Feature, or Question?
Is there a way for formik to only submit what is currently in the DOM rather than just what's in its internal state?

## Current Behavior
If i initialize a Form with default values (say an edit with existing values) but then remove some of the inputs based on answers from earlier inputs, the removed field values are still submitted rather than being "nulled" out.

## Desired Behavior
I'd like to be able to have a field not to be submitted if I remove the DOM element for it (even if the Form's internal state might still have that value)

## Suggested Solutions
Perhaps a flag to indicate whether submission should re-gather values from DOM before submitting or whether it should just use internal Form state.

## Additional Information

---

- Formik Version: v0.11.10
- React Version: 16
- TypeScript Version: n/a
- CodeSandbox Link: n/a
- OS: mac
- Node Version: note sure
- Package Manager and Version: yarn (not sure)

**Comment by prichodko** [comment]
You can set values programatically - https://github.com/jaredpalmer/formik#setvalues-fields--field-string-any---void. So just delete them, when you are deleting an input.

**Comment by sdoxsee** [comment]
Thanks. That's what we've been discovering. It's a bit more tedious but it keeps it decoupled from the DOM which is important for react native (I think). We're going to try to defer the programmatic setting of values until the submit and then look at our component state to delete the values that shouldn't be there. Thanks for the suggestion.
