### ISSUE TITLE
Test for value change in a Field

### ISSUE THREAD

**Issue by goislimat** [jaredpalmer/formik#481]
## Bug, Feature, or Question?
**Question**

First of all, I'd like to apologize for my bad english.

I'm trying to write a test where I can verify if a button is enabled or not, but I'm not managing to make it work.

The component that I have: 

```javascript
// TodoForm.js
import React from 'react';
import { withFormik, Form, Field } from 'formik';
import yup from 'yup';

const TodoForm = ({ isValid }) => (
  <Form>
    <Field name="todo" type="text" placeholder="Type your todo here..." />
    <button disabled={!isValid}>Add ToDo</button>
  </Form>
);

const EnhancedTodoForm = withFormik({
  mapPropsToValues: () => ({ todo: '' }),
  validationSchema: yup.object().shape({
    todo: yup.string().required(),
  }),
  handleSubmit: (values, { props }) => {},
})(TodoForm);

export default EnhancedTodoForm;

```
I want to change the 'todo' value (preferably via simulate) and see if the button gets enabled, but I'm not even able to change the value of Field. 

Does anyone have any ideas? I'd love if it comes with an example <3.

## Additional Information

This is the piece of code that I tried without success until now.

```javascript
// TodoForm.test.js
import React from 'react';
import { shallow } from 'enzyme';

import TodoForm from './TodoForm';

describe('<TodoForm />', () => {
  let enhancedTodoForm;

  beforeEach(() => {
    enhancedTodoForm = shallow(<TodoForm />);
  });

  describe('interactions', () => {
    describe('user types something', () => {
      const newTodo = 'my new todo';

      it('`button` gets enabled', () => {
        const todoFormComponent = enhancedTodoForm.dive().dive();
        const field = todoFormComponent.find('Field');

        // this don't change the value, or at least i'm not figuring out how to access
        field.simulate('change', {
          persist: () => {},
          target: {
            name: 'todo',
            value: newTodo,
          },
        });
        // this also doesn't change the values prop inside the component
        enhancedTodoForm.dive().setProps({ values: { todo: newTodo } });

        expect(todoFormComponent.find('button').props().disabled).toBe(false);
      });
    });
  });
});
```

---

- Formik Version: 0.11.11
- React Version: 16.2.0
- OS: Ubuntu 16.04
- Node Version: 8.9.4
- Package Manager and Version: yarn 1.3.2

**Comment by goislimat** [comment]
For the people that could be facing the same problem, I managed to solve this by mounting my component instead of shallow rendering it. 

I also changed the Field component for an input with the formik functions.

[Part 7 of this article](https://semaphoreci.com/community/tutorials/getting-started-with-tdd-in-react) can explain better than me.

PS: If someone knows a better way of doing this, please share.

**Comment by bmakuh** [comment]
Hmm, I'm having a similar issue where the value of the Field isn't getting updated when I simulate a change event. I get this error in my terminal output:
```
Warning: `handleChange` has triggered and you forgot to pass an `id` or `name` attribute to your input:

          undefined

          Formik cannot determine which value to update. For more info see https://github.com/jaredpalmer/formik#handlechange-e-reactchangeeventany--void
```

But when I `console.log(component.find('.email-field').first().debug())` it shows the input field as haing a `name` attribute:
```jsx
<input value={[undefined]} name="email" onChange={[Function: onChange]} onBlur={[Function]} autoFocus={true} className="text-input" className="email-field" placeholder="my.contact@gmail.com" type="email" onKeyUp={[Function]} />
```

**Comment by bmakuh** [comment]
Haha, after typing that out I realized my problem: I had a `name` attribute on the element, but I was assuming Enzyme was going to pass that element along as the `event.target` like in the real DOM, but that's not true. Adding an explicit `event.target.name` in the simulated `onChange` fixed the problem.

**Comment by alexgorbatchev** [comment]
Fully mounting solved my issue. I'm guessing that `.find('Form').dive().find('form')` doesn't trigger whatever sets `context.formik`

**Comment by Ciaran0** [comment]
@bmakuh could you show what you did to get this working?

**Comment by bmakuh** [comment]
@Ciaran0 yep, sure. The reason it wasn't working for me was because I didn't realize that I needed to explicitly provide a `name` property on the event object I was passing in, like this:
```js
component.find('[data-test-id="email-field"]').simulate('change', {
  target: {
    name: 'email',
    value: 'aa@bb.cc'
  }
})
```
When your code runs in the browser, the native event will send the _actual_ element as the target, in which case the `name` will be set already.
