### ISSUE TITLE
Not passing through props to component?

### ISSUE THREAD

**Issue by mohadib** [jaredpalmer/formik#487]
## Bug, Feature, or Question?
Possible bug (more likely misunderstanding)

## Current Behavior
I am expecting cancelEdit to be available in Form components props, but its not
```
        <Formik
          validateOnChange={true}
          validateOnBlur={true}
          isInitialValid={true}
          initialValues={this.props.church}
          onReset={this.reset}
          onSubmit={this.submit}
          validate={this.validate}
          component={Form}
          cancelEdit={()=> alert('yay')}
        />
```

## Desired Behavior
Pass cancelEdit or any other random props through to component

## Additional Information

---

- Formik Version:
- React Version: 0.11.11
- TypeScript Version:
- CodeSandbox Link:
- OS: Linux
- Node Version: v8.9.4
- Package Manager and Version:

**Comment by jaredpalmer** [comment]
Use the render prop instead of component. Works just like React Router.

**Comment by mohadib** [comment]
Then maybe the docs need to be updated if the render prop is treated different than the component:

"Formik props

All three render methods will be passed the same props:"
