### ISSUE TITLE
Synchronous validation

### ISSUE THREAD

**Issue by marcoroganovic** [jaredpalmer/formik#489]
## Bug, Feature, or Question?
Question

## Current Behavior
Since Yup validations are async, components render twice as far as I've read in previous issues, and I have 150 input fields on one page and it's extremely noticeable when user starts to type, it basically becomes unusable. So, since there is boolean flag in `validateYupSchema` method for synchronous version is there a way to set it as prop on `Formik` component?

## Desired Behavior
To run Yup validations synchronously.

---

- Formik Version: 1.0.0-alpha.2
- React Version: 16.2.0
- OS: MacOS
- Node Version: 8.9.1
- Package Manager and Version: npm v5.6.0

**Comment by jaredpalmer** [comment]
So in FastField, I check if validations can be run synchronously. I think that logic can be moved into Formik as well.

**Comment by latviancoder** [comment]
@jaredpalmer that would be cool. I have to use custom UI components and can't use FastField because of it.

**Comment by marcoroganovic** [comment]
Hey, thanks for reply. Any idea how to achieve data-binding with FastField. I tried to wrap onChange handler in custom one, but that's not working.

**Comment by latviancoder** [comment]
By the way, this is how I did synchronous validation using `yup` and `validate` function:

```
validate: (values: FormValues) => {
    const validationSchema = object().shape({
        singleFriend: friendValidationSchema,
        hasOtherFriend: boolean(),
        otherFriend: object().when('hasOtherFriend', {
            is: true,
            then: friendValidationSchema
        }),
        friends: array().of(friendValidationSchema)
    });

    try {
        validateYupSchema<FormValues>(values, validationSchema, true);
    } catch (err) {
        return yupToFormErrors(err);
    }

    return {};
},
```

**Comment by pietmichal** [comment]
This is even more relevant now because async validation now triggers `act` errors in tests when using React Hooks.
