### ISSUE TITLE
Doubts about add/edit form, coming from redux-form.

### ISSUE THREAD

**Issue by johnunclesam** [jaredpalmer/formik#490]
#### Bug, Feature, or Question?
Question.

### Current Behavior

I'm coming from `redux-form` and usually I use the same form for edit/add operations. In redux-form I don't need to check for initialValues if object is present or not. In formik I think I have. I created a reproduction of my doubts here: https://codesandbox.io/s/x7pv9359zw.

**Is this the correct way to do it?**

Is also the below code correct?

```js
mapPropsToValues: props => {
    if (props.player) {
      return {
        ...props.player
      };
    } else {
      return {
        name: "",
        surname: "",
        age: "",
        skill: ""
      };
    }
  },
```

I'm wondering also about this code:

`...props.player`

Sorry, I'm newbie and I'm continuously learning...

**Is there a way to avoid this below DRY?**

```js
return {
  name: "",
  surname: "",
  age: "",
  skill: ""
};
```

**Comment by jaredpalmer** [comment]
you can use es6 parameter destructuring with default values

```
const defaultPlayer = {
        name: "",
        surname: "",
        age: "",
        skill: ""
      }
// ...
mapPropsToValues = ({ player }) => player || defaultPlayer

```

**Comment by johnunclesam** [comment]
@jaredpalmer so there isn't a way to not write everytime all the fields like this?

```js
defaultPlayer = {
  name: "",
  surname: "",
  age: "",
  skill: ""
}
```
