### ISSUE TITLE
after the empty form has been submitted... touched prototype doesn't look okay.

### ISSUE THREAD

**Issue by madebytilde** [jaredpalmer/formik#491]
after the empty form has been submitted... touched prototype doesn't look okay.
```
  touched: {
    title: true,
    description: true,
    categories: [{
      id: true,
      name: true,
    }, {
      id: true,
      name: true,
    }, {
      id: true,
      name: true,
    }],
    images: [{
      uri: true
    }, {
      uri: true
    }, {
      uri: true
    }, {
      uri: true
    }]
  },
```
it should be like the following code
```
  touched: {
    title: true,
    description: true,
    categories: true,
    images: true
  },
```

**Comment by prichodko** [comment]
Put your code inside backticks, so it's much easier for people to read it and help you. 
Example:
^^^js
code
^^^
Just substitute ^ for `.

**Comment by jaredpalmer** [comment]
Formik will match the shape of it's `values`, this means that nested complex arrays will look like the former while simple arrays will look like the latter before submission
