### ISSUE TITLE
Group values by field?

### ISSUE THREAD

**Issue by dferber90** [jaredpalmer/formik#493]
## Question
First of all: Thanks for Formik. It's a great library and very easy to work with. I'm curious about an architecture decision you made when developing Formik.

Formik groups the bag by the properties it supports. For a simple form which has `name` and `description` fields Formik would use a `formikBag` with something like this (actual values redacted):

```js
{
  values: { name, description },
  touched: { name }
  errors: { name },
  handleChange,
  setFieldValue,
  resetForm,
  // ...
}
```

I always assumed this grouping was to keep errors flexible and to support additional errors outside of defined fields. Then I stumbled upon this recommendation in the docs to keep the shape of `errors` and `values` the same:

> Form validation errors. Should match the shape of your form's values defined in initialValues.

Since Formik seems to embrace having errors in the same shape as the fields I'm curious why Formik doesn't group these properties by field in the first place, as in:

```js
{
  name: {
    value,
    touched,
    error,
    change,
  },
  description: {
    value,
    touched,
    error,
    change,
  },
  resetForm,
  // ..
}
```

## Upsides
- we would already know the field when setting
  - form fields wouldn't need the `name` attribute anymore (the event doesn't need it)
  - we wouldn't need `setFieldValue` anymore (can use `<field>.change`)
- easy to pass all values related to one field to a component rendering that field

## Downsides
- maybe no dynamic fields?
- less flexibility?
- would it work with arrays?

I'm not trying to argue to change to the outlined approach at all. I'm interested in why you decided to take the approach you took :)

**Comment by jaredpalmer** [comment]
how would nested fields work?

**Comment by dferber90** [comment]
Ah, good point 👍 I didn't know nested fields are supported by Formik (must have flown past it on the README, but I see it now).

Hmm, maybe it would be safe to assume that objects are never form values (pretty questionable already). Then we could add the bag-stuff based on the value type. This already feels non-straight-forward and limiting. Curiosity satisfied. Thanks for your response :)

---

Offtopic, but wanted to share since I found our [meteor-autoform](https://github.com/aldeed/meteor-autoform) inspired approach quite useful. We use a mapping function for the data on the way in, and another on the way out. We usually remove all nesting there (and convert values). That's why I haven't run into nested data yet either.

```js
const exampleData = { id, email, social: { facebook, twitter }  }

const docToFormValues = doc => ({
  id,
  age: String(doc.age), // it's easier for form inputs to work on strings
  email,
  facebook,
  twitter
})

const formValuesToDoc = formValues => ({
  id: formValues.id,
  email: formValues.
  age: parseInt(formValues.age, 10), // the validate fn must ensure that this never throws
  social: { twitter: formValues.twitter, facebook: formValues.facebook }
})

<Formik
  initialValues={docToFormValues(exampleData)}
  onSubmit={formValues => { updateUser(formValuesToDoc(formValues)) }}
/>
```

**Comment by jaredpalmer** [comment]
@dferber90 initial versions of Formik had a `mapValuesToPayload` function that did just this. My initial idea was to centralize/standardize transformations/flattening. Ultimately it felt redudant, so we deprecated it in 0.8 I think.
