### ISSUE TITLE
Data from top level fields with same name as nested fields is cloned

### ISSUE THREAD

**Issue by AxelRamiro** [jaredpalmer/formik#497]
## Bug, Feature, or Question?
Bug

## Current Behavior
When a nested field object with same name as a root one changes, all the properties from top level field are copied to the nested field.

Example:

```
<Form>
  <Field name="user[name]">
  <Field name="user[lastName]">
  <Field name="nested[user][moreData]">
</Form>
```
Result
```
{
  user: {
    name: 'John',
    lastName: 'Doe'
  },
  nested: {
    user: {
      name: 'John', // is copied from root on moreData change
      lastName: 'Doe', // is copied from root field on moreData change
      moreData: 123
    }
  }
}
```

## Desired Behavior
Data from top level fields with same name as nested fields should not be copied.

## Additional Information
I also tried with dot notation with same results.

---

- Formik Version: "^0.11.11"
- React Version: "^16.2.0"
- TypeScript Version:
- CodeSandbox Link: https://codesandbox.io/s/3vrk45xjzp
- OS: macOS Sierra 10.12.6
- Node Version: v8.4.0
- Package Manager and Version: yarn v1.3.2

**Comment by landonalder** [comment]
I am having this same issue with nested `<FieldArray>`s

**Comment by jaredpalmer** [comment]
Oof this is a bad bug!

**Comment by jaredpalmer** [comment]
Need to investigate fixes.

**Comment by ahmadalfy** [comment]
Having the same issue with nested

**Comment by davad** [comment]
@AxelRamiro I just tested your CodeSandbox example, changed to v1.0.2, and it seems to be working. Can you run a newer version?

https://codesandbox.io/s/xpl1lokjrp

**Comment by jaredpalmer** [comment]
This should be fixed with our new merge behavior

**Comment by AxelRamiro** [comment]
It works! Thanks!
