### ISSUE TITLE
Determine if submit was clicked and touched flag

### ISSUE THREAD

**Issue by deshiknaves** [jaredpalmer/formik#499]
## Question?
Is there a way to determine if the submit button has been clicked when it has validation errors. I don't want to show the errors unless the field has been `touched` — which is shown in the examples with `touched` and `errors` with an error for the field. However, if the user clicks the submit button, then I'd like to show all the errors on all the fields. This currently doesn't work because the `touched` check will prevent messages to be displayed.

## Current Behavior
`touched` is updated when the field is touched which is exactly what it should do. I can't seem to find another flag that will give let me know that the validation was triggered by the submit button.

## Desired Behavior
Some way of knowing that the form was submitted and there were errors.

## Suggested Solutions
Either a new flag or all the fields set to touched. I first one is better.

---

- Formik Version: ^0.11.11
- React Version: 16.2.0
- TypeScript Version: N/A
- CodeSandbox Link: N/A
- OS: MacOS
- Node Version: v8.10.0
- Package Manager and Version: 5.6.0

**Comment by prichodko** [comment]
`onSubmit` Formik sets all fields to be `touched` - https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L503

**Comment by deshiknaves** [comment]
Completely my mistake. I thought that's what it was supposed to do.
