### ISSUE TITLE
Odd setFieldTouched behavior

### ISSUE THREAD

**Issue by arist0tl3** [jaredpalmer/formik#504]
## Question?

Hitting something odd with `setFieldTouched` that I can't quite figure out. I'm passing down `setFieldTouched` from `withFormik` to some inputs, and then doing:

```
handleBlur = () => {
  const { name, setFieldTouched } = this.props;
  setFieldTouched(name, true); // name = 'start'
};
```

Oddly, in some instances, this call is setting an object instead of just setting a bool:

Here is the error:
![image](https://user-images.githubusercontent.com/9328541/37244943-a54eafd6-2445-11e8-811e-4666719e3f76.png)

And here is the value of `touched`:

![image](https://user-images.githubusercontent.com/9328541/37244952-c3879616-2445-11e8-9721-0ec75bf40400.png)

If I change the call to this:
```
handleBlur = () => {
  const { name, setFieldTouched } = this.props;
  setFieldTouched(name); // Note, no second arg
};
```

Then my touched looks correct:
![image](https://user-images.githubusercontent.com/9328541/37244967-f161a7c0-2445-11e8-9aa5-679d701fc7dc.png)

Just curious why the second argument of `setFieldTouched` could be creating an object instead of just setting the value?

- Formik Version: 1.0.0-alpha.1
- React Version: 16.2.0
- OS: Ubuntu 16.04
- Node Version: 8.4
- Package Manager and Version: yarn 1.5.1

**Comment by prichodko** [comment]
Do you know that `withFormik` passes you `handleBlur` as well, so you don't have to do it manually?

However, I wasn't been able to reproduce the error. Can you create a minimal example on codesandbox.io?

**Comment by arist0tl3** [comment]
Hey, sorry for the delay. Finally revisited this today.

Looks like this is unrelated to `setFieldTouched` and more related to what happens here: https://github.com/jaredpalmer/formik/blob/master/src/utils.ts#L57

The use case for me right now is having an address field with an object as a value. The display value is a formatted street address, and then there are additional properties that we want to store.

I've created a minimal repo here:

https://codesandbox.io/s/l69r9mvvz

Curious if I'm not implementing correctly, or if the `setNestedObjectValues` should not be following the values so closely in setting the touched values?

**Comment by jaredpalmer** [comment]
The second argument is if you want to set it to false (it’s true by default)

**Comment by arist0tl3** [comment]
Were you able to have a look at the sandbox repo? The touched values are following what is set in the initial `mapPropsToValues`:

![image](https://user-images.githubusercontent.com/9328541/38479621-4acea7d6-3b75-11e8-90b5-94632187d95a.png)

**Comment by arist0tl3** [comment]
Is that expected?

**Comment by murdink** [comment]
@arist0tl3 were you able to find a solution for this ?

**Comment by arist0tl3** [comment]
@murdink 

Not yet. I think that the inherent problem is passing an object to `mapPropsToValues`. Same goes for arrays. 

The idea of a transform/normalize is tricky. The author's suggestion is to handle those types of transformations outside of formik, but that implies that the transformation happens above formik, before the value hits `mapPropsToValues`, and after a submit. When you have a custom input type that always performs the same transforms, it would be more ideal for that transformation to happen below formik, but then you get into these types of situations. 

You can see what happens here, onSubmit: https://github.com/jaredpalmer/formik/blob/0b8346d302e71515b8cd987e528908003e0145f6/src/Formik.tsx#L532

This gets called, which follows the shape of the value: https://github.com/jaredpalmer/formik/blob/master/src/utils.ts#L57

Not sure what makes the most sense. It could be helpful to pass in a custom `setTouchedOnSubmit` function, because then we'd be able to target specific field names in each form, where we are performing transformations. 

Unfortunately, not too many others seem to be hitting this issue, so I'm not sure if this is too much of an edge case to warrant extending the API?

**Comment by arist0tl3** [comment]
Similar situation. I can work around the shape of the touched values, but the prop type errors add a lot of noise to the console.

**Comment by jaredpalmer** [comment]
We're getting rid of prop-types soon when i merge #594. So that will go away. I think this is an edge case. Am open to a PR.
