### ISSUE TITLE
Prevent simultaneous submission of multiple forms

### ISSUE THREAD

**Issue by migueloller** [jaredpalmer/formik#507]
## Bug, Feature, or Question?
Feature/Question

## Current Behavior
When there are two HTML `form`s present a submission will attempt to submit both forms. This causes validation to run on both even if it was desired to only submit one.

## Desired Behavior
Only the target of the even should be submitted.

## Suggested Solutions

This can be implemented in userland but it would be awesome if passing an `id` or `name` to the `form` element would prevent multiple form submission from happening. Formik could look at `event.target.name` or `event.target.id` and only call `this.executeSubmit` if if matches the element. **EDIT:** It can also be implemented using refs so that the user doesn't have to provide an `id` or `name`.

---

- Formik Version: v0.11.10
- React Version: v16.2.0

**Comment by migueloller** [comment]
This could also be achieved using refs and would not require the user to assign an `id` or `name` to the `form` element.

**Comment by migueloller** [comment]
Here is the userland implementation:

```es6
<form
  onSubmit={event => (event.target === this.form && handleSubmit(event))}
  ref={(form) => { this.form = form }}
>
```

**Comment by prichodko** [comment]
So, you have two `forms` inside one `Formik`?

**Comment by migueloller** [comment]
Two `Formik`s in the same page.

**Comment by migueloller** [comment]
The use case it a modal to recover the user's password. There's a `Formik` on the modal but there's also a `Formik` to log in below the modal.

**Comment by prichodko** [comment]
Alright, so the Login form is working as expected, but the form in the modal triggers the submission of itself + propagates the event up (which triggers the submission of Login form). So what I think you should do is to prevent the event from bubbling up in the Recover form. 

Also since it's a default behaviour and kinda edge case scenario, it should be handled by developer and not in Formik, in my opinion.

**Comment by migueloller** [comment]
@prichodko,

That's fair! Just thought I'd suggest it in case it was a QoL feature Formik would like to provide.

**Comment by klis87** [comment]
@migueloller Did you try `e.stopPropagation()`?

**Comment by migueloller** [comment]
@klis87, tried it just now and it works 😄 

This is better than using `ref`.

**Comment by prichodko** [comment]
@migueloller sorry if I wasn't clear enough - it was what I meant by `prevent the event from bubbling up`.

Let's close it then?

**Comment by migueloller** [comment]
@prichodko,

Yes, that was clear!

> Let's close it then?

Yup. Thanks for all your help fellas.
