### ISSUE TITLE
validate values method

### ISSUE THREAD

**Issue by jonstuebe** [jaredpalmer/formik#51]
Is it possible to expose a validate fields/values method that can be run within the hoc? Right now it looks like validation is run on all fields when a value changes or on submit and it would be nice to run it whenever.

**Comment by jaredpalmer** [comment]
Undocumented, but Formik also exports some helpers...

- [validateFormData: (values: any, validationSchema: any) => Promise<void>](https://github.com/jaredpalmer/formik/blob/master/src/formik.tsx#L31) (it will throw if invalid).
- [yupToFormErrors: (yupError: any) => FormikErrors](https://github.com/jaredpalmer/formik/blob/master/src/formik.tsx#L8) (will transform the caught Yup error in the shape of `props.errors`).

**Comment by jaredpalmer** [comment]
See #61
