### ISSUE TITLE
How to correctly organize array of objects form?

### ISSUE THREAD

**Issue by kolyasya** [jaredpalmer/formik#510]
## Bug, Feature, or Question?
Question

At the moment there is only one example of FieldArray which handles array of strings.
https://github.com/jaredpalmer/formik#fieldarray

Is it possible to implement an array of objects? In case each of `friends` has `firstName`, `lastName` and `age` for example.

What is a proper way to do it?

**Comment by latviancoder** [comment]
Here is what I used in my app:

```
<Form>
    <FieldArray
        name="friends"
        render={arrayHelpers => (
            <div>
                {values.friends.map((friend, index) => (
                    <div key={index}>
                        <Field name={`friends.${index}.name`}/>
                        <Field name={`friends.${index}.age`}/>
                        <button
                            type="button"
                            onClick={() => arrayHelpers.remove(index)}
                        >
                            -
                        </button>
                    </div>
                ))}
                <button
                    type="button"
                    onClick={() => arrayHelpers.push({ name: '', age: '' })}
                >
                    +
                </button>
            </div>
        )}
    />
</Form>
```

And here is an example validationSchema:

```
const friendValidationSchema = object().shape({
    name: string().required('name required'),
    age: number().required('age required').typeError('age must be a number')
});

const validationSchema = object().shape({
    friends: array().of(friendValidationSchema)
});
```

**Comment by kolyasya** [comment]
@latviancoder thank you very much, it works!

**Comment by mrchief** [comment]
@latviancoder Are you able to set `initialValues` using your approach? I'm currently using redux-form which doesn't seem to have support for initialValues + array of objects, so if Formik support it, I might as well move to Formik.

**Comment by latviancoder** [comment]
Yes you can, take a look at documentation :)

**Comment by mrchief** [comment]
The [documentation](https://github.com/jaredpalmer/formik#fieldarray) only has simple arrays but anyhow, I managed it with redux-forms. The trick was to not use `FieldArray` :smile:. Here's a [CodeSandbox](https://codesandbox.io/s/1vqqn68zx4), if anyone comes looking for a similar solution.

**Comment by KeweiCodes** [comment]
@latviancoder  how is it that `friends.${index}.age` should work as the input name when you pushed { name: '', age: '' } ? 

If this is how things are supposed to work, then this is clearly not in in docs.

**Comment by KeweiCodes** [comment]
@jaredpalmer help?

**Comment by jaredpalmer** [comment]
You can use dots or brackets for nested things. friends.0.name is the same as friends[0].name

**Comment by KeweiCodes** [comment]
@jaredpalmer that's awesome, I think it'd be good to include the above code snippet into README. I don't mind doing a PR on this today if needs be. What do you think?

**Comment by jaredpalmer** [comment]
Yeah sounds good.👌

**Comment by KeweiCodes** [comment]
@jaredpalmer thanks for your help! 😄

**Comment by Nemsae** [comment]
@latviancoder @jaredpalmer Is it possible to combine the creation of a new element with an existing`<FieldArray />`?

In the same example @latviancoder posted, the button to add a new element into the array has this handler `onClick={() => arrayHelpers.push({ name: '', age: '' })}` from below:
```
<Form>
    <FieldArray
        name="friends"
        render={arrayHelpers => (
            <div>
                {values.friends.map((friend, index) => (
                    <div key={index}>
                        <Field name={`friends.${index}.name`}/>
                        <Field name={`friends.${index}.age`}/>
                        <button
                            type="button"
                            onClick={() => arrayHelpers.remove(index)}
                        >
                            -
                        </button>
                    </div>
                ))}
                <button
                    type="button"
                    onClick={() => arrayHelpers.push({ name: '', age: '' })}
                >
                    +
                </button>
            </div>
        )}
    />
</Form>
```

In this example this would just push `{ name: '', age: '' }` element into the array of `friends`.

However, what if my form is a bit more complex, in that I want to render fields for the new element that I want to push into the array of `this.props.values.friends`.

The code that I imagine/hope for would be something like this (which I realize doesn't make much sense):
```
<Field name={`friends.${indexToBeAdded}.name`}/>
<Field name={`friends.${indexToBeAdded}.age`}/>
```

Currently what I have to do is create a separate set of fields for the new element.. 

```
<Field name={`new_friend_name`}/>
<Field name={`new_friend_age`}/>
```

Which means I have to have separate validation for those new fields `new_friend_name` and `new_friend_age`, and add a special handler that will add the new element into the existing `this.props.values.friends` using `this.props.setValues` upon successful validation.

Is there a more elegant way to accomplish this?

**Comment by ronyfhebrian** [comment]
What about arrays with useFormik?
I have already used useFormik and now kinda confused of how to make arrays of components from initialValues, the values are updating but the component doesn't.
Please help

**Comment by Eldho-Abraham-coder** [comment]
what if the array of objects is coming from a parent form using withFormik.  We cannot take "values.friends.map" right.Can anybody help.
