### ISSUE TITLE
submitForm seems to not work if validate is async

### ISSUE THREAD

**Issue by esperancaJS** [jaredpalmer/formik#511]
When calling `submitForm` and using `validate` with async validations `submitForm` never executes

---
- Formik Version: ^0.11.10

**Comment by esperancaJS** [comment]
would adding `FormikBag` to `validate` make sense ?

This way I could keep validate sync, but still have async validations in there by calling `setFieldError`

**Comment by prichodko** [comment]
This should not be true, because it's being called after `validate` successfully resolves. https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L517

**Comment by esperancaJS** [comment]
Perhaps the problem is with this example in the README:
![image](https://user-images.githubusercontent.com/1115163/37353052-70c6a1f4-26d6-11e8-84af-b5e04eb16eab.png)
it seems to only show how to `throw` errors`, what should it do in case of not having errors? nothing (that's what it does already and seems to not work)

**Comment by prichodko** [comment]
Do nothing, because then it successfully resolves. 

If you create a reproducible example on www.codesandbox.io, I can have a look.

**Comment by esperancaJS** [comment]
Thanks for your availability @prichodko.

I have replicated it [here](https://codesandbox.io/s/m7xk74r678?expanddevtools=1)

Based on the example on the README.md

**Comment by hudecsamuel** [comment]
Having the same problem here, the example is a bit confusing and might be incorrect actualy.
Tried to look at the source code and figure it out.

You have to return a promise (the example is resolving a promise and is either returning nothing or throwing an error)

Edited your codesandbox to have it working as expected [here](https://codesandbox.io/s/ql9p0x9qpw)

btw the example could be be something along the lines of (if you really have to return a Promise)

```js
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms))

const validate = (values, props) => sleep(2000)
    .then(() => new Promise((resolve, reject) => {
        const errors = {}
        if (['admin', 'null', 'god'].includes(values.username)) {
            errors.username = 'Nice try'
        }
        // ...
        if (Object.keys(errors).length) {
            reject(errors)
        } else {
            resolve()
        }
    }))
```

it doesn't really make sense, but it returns a promise in the end that is resolved inside formik. 

You can also resolve a Promise like that in the `validate` function and return the errors as object

```js
const validate = (values, props) => sleep(2000).then(() => {
    const errors = {}
    if (!values.email) {
        errors.email = 'Required'
    } else if (
        !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(values.email)
    ) {
        errors.email = 'Invalid email address'
    }
    return errors
})
```

Here is another example of using Promise as return value of `validate` function that works
```js
const validate = (values, props) => new Promise((resolve, reject) => {
    const errors = {}
    if (!values.email) {
        errors.email = 'Required'
    } else if (
        !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(values.email)
    ) {
        errors.email = 'Invalid email address'
    }

    if (Object.keys(errors).length) {
        reject(errors)
    } else {
        resolve()
    }
})
```

**Comment by jaredpalmer** [comment]
Let’s update the example with working code then
