### ISSUE TITLE
FastField : validationSchema issues

### ISSUE THREAD

**Issue by pierre-H** [jaredpalmer/formik#519]
## Bug, Feature, or Question?
Bug

## Current Behavior
When I change the value of a field, the validation with a schema is done only when I quit the field

## Desired Behavior
The validation should be done in real time

- Formik Version: 1 alpha 3
- React Version: 16
- TypeScript Version: 2.7.2
- OS: Windows 32b
- Node Version: 8.7.0
- Package Manager and Version: yarn 1.5.1

**Comment by jaredpalmer** [comment]
This wasn’t a bug, but a design decision. FastField is local until the field blurs. There are some cases with dynamic forms or when a value change impacts another field that will not work at the moment. The solution unfortunately is to degrade the perf to Field in these situations.
