### ISSUE TITLE
Dirty not working with mapPropsToValues as expected

### ISSUE THREAD

**Issue by benoj** [jaredpalmer/formik#523]
## Bug, Feature, or Question?

I have a form which is using the following `withFormik` decorator.

In the form the button is disabled when `!dirty`.

`onSubmit` writes to firebase which in turn  updates the form props  values. The dirty field is however still dirty. It looks like the `initialValues` are not being updated when the props are updated and mapped to values in the `mapPropsToValues`
```
export default withFormik({
  mapPropsToValues: ({ name, website, path, cname }) => {
    return {
      name,
      website
    }
  },
  validationSchema: (props) => {
    return yup.object().shape({
      name: yup.string().required("Name is required"),
      website: yup.string().url("Must be a valid URL")
    })
  },
  handleSubmit: (values, { props }) => {
    props.onSubmit(values)
  },
})(MyForm)
```

**Comment by benoj** [comment]
I was able to make this work by updating to this:

```
  handleSubmit: async (values, { props, setSubmitting, resetForm }) => {
    await props.onSubmit(values)
    setSubmitting(false)
    resetForm(values)
  },
```

Does this look reasonable?

**Comment by abelkbil** [comment]
Are you using bootstrap. how do the error message displayed
