### ISSUE TITLE
.min file webpack production

### ISSUE THREAD

**Issue by Jucesr** [jaredpalmer/formik#525]
## Current Behavior
I start using formik in a huge app where I tried to make the bundle.js small as posible. I am using webpack 3.1.1 as my bundler. When I run webpack with production config the size of formik module is 182kb. 

![image](https://user-images.githubusercontent.com/25498381/37621606-9dcaddfa-2b7c-11e8-9055-81531cf8043f.png)

## Desired Behavior
I am wondering if there is any .min file I can use instead when setting webpack to production.  

---

- Formik Version: ^0.11.11
- React Version: ^16.2.0
- TypeScript Version:
- CodeSandbox Link:
- OS: Windows
- Node Version: v8.1.3
- Package Manager and Version: 5.3.0

**Comment by jaredpalmer** [comment]
You can upgrade to formik@next

**Comment by sarneeh** [comment]
@jaredpalmer This answer is pretty lame :P Not everyone wants to use a beta version for their whatever-scale production app. I stumbled upon this issue myself and would like to know how can I get the `7.8 kB` size as the documentation states (not `~178kB` as I have right now). Any ideas? :)

**Comment by addamove** [comment]
Any docs on formik@next?
