### ISSUE TITLE
setFieldValue should return a Promise or receive a callback

### ISSUE THREAD

**Issue by today-** [jaredpalmer/formik#529]
## Current Behavior
setFieldValue() is async because it uses setState(), but it doesn't receive a callback or return anything.
That's why it's hard to get modified values right after that, for example if I want to run submitForm().

## Desired Behavior
setFieldValue() will return a promise, so I could await it and get changed values.

## Suggested Solutions
return a Promise from setFieldValue() OR add additional callback to function declaration

- Formik Version: 0.11.11
- React Version: 16.2.0
- CodeSandbox Link: https://codesandbox.io/s/x9445yl5lp

**Comment by prichodko** [comment]
Can you elaborate more on your use case? Submitting form after every single change seems really strange to me.

**Comment by latviancoder** [comment]
Temporary hacky workaround I am using - put submitForm into a `setTimeout`.

**Comment by today-** [comment]
Yes, setTimeout made this job, and even Promise.resolve works, but both looks like kludges

**Comment by zakangelle** [comment]
A common use case for this is when you have a form with a set of filters, and you want your new filter values to be applied each time a filter is changed. With a callback option, this would look something like this:

```
<Select
  value={values.city}
  onChange={value => setFieldValue('city', value, submitForm)}
>
  {options.map(option =>
    <Option key={option.id} value={option.value}>{option.name}</Option>
  )}
</Select>
```

As @today- said, since `setFieldValue` uses `setState` (which is async), having some kind of callback would be nice for this type of use case.

**Comment by gabriel-cliqz** [comment]
I also need the callback function.
In some cases is very handy

**Comment by timc13** [comment]
It would be nice if FastField & Field exposed this callback as a prop as well.

**Comment by FadiAboMsalam** [comment]
any update to this as i also need callback or promise or at least a way of doing this sync

**Comment by timc13** [comment]
This is pretty essential.  There are many cases after you update a value on a field, you want to have access to the value immediately, or perhaps the `errors` or `touched` state.

**Comment by mihkelmark** [comment]
I also found myself in dire need of this. 

I need to calculate a form's `total` value while others (`vat` and `sum`) are being typed: `calculatedTotal = sum * (vat / 100)`

Currently these two console logs log the same thing:

```
      console.log('values before', values)
      setFieldValue('total', calculatedTotal)
      console.log('values after', values)
```

**Comment by elmeerr** [comment]
I just came across the same problem...I need to get a value after `setFieldValue `but is not possible because `setState `is _async_ (as it was already mentioned). Nice feature to have

**Comment by ibolton336** [comment]
I have this issue also. I have a dynamic dropdown that needs updating requiring me to make an api call. This forces me to submit the form before rerender so values are updated.

**Comment by lpillonel** [comment]
I also need a callback for pretty much the same usecase than @zakangelle

**Comment by tpict** [comment]
My use case is a form that has two separate submit buttons for "Save draft" and "Publish"; they set an `is_draft` field to `true` or `false` and then submit the form (in theory).

**Comment by mlp73** [comment]
Exactly same use case with "Save draft". Missing a callback / promise :'(

**Comment by midnightcodr** [comment]
I believe it's a very common use case for feature like this. In my project I want to provide a "shortcut" button that will repopulate the form with preset values and submit the form right after. With the current implementation of setFieldValue this is impossible (without some workaround such as `setTimeout`).

**Comment by flybayer** [comment]
I've got the same problem. I'd love `setFieldValue` to return a promise.

**Comment by flybayer** [comment]
@rfabes21 here's my current workaround:
```jsx
  <button
    type="button"
    onClick={async () => {
      setFieldValue('signed', true)
      // Hack to wait for new value to be applied
      // Pending https://github.com/jaredpalmer/formik/issues/529
      await Promise.resolve()
      submitForm()
    }}>
    Sign
  </button>
```

**Comment by timc13** [comment]
can this get marked as an enhancement so it doesnt get lost?

**Comment by jaredpalmer** [comment]
Seems like there is a enough requests here. Let me look into this. 

To synthesize the above, the goal is to respond to a set value event inline (so as to use the updated state) somehow.

**Comment by latviancoder** [comment]
You could also consider enabling the same functionality for all set* methods.

**Comment by timc13** [comment]
yes, this would be very useful for `setTouched`, `setError`, etc. as well.

**Comment by midnightcodr** [comment]
@ZwaarContrast I don't think you need to use such a big timeout value for `setTimeout`. I am using 1ms just fine:
```
    setFieldValue('blah', 'somevalue')
    setTimeout(submitForm, 1)
```

**Comment by jordan-jarolim** [comment]
Callback function would be also handy in case you have giant structure of data you want to use in formik and setting any value takes some time. It would be possible to set loading state and show loading bar before setFormValue and then use callback to let user now operation is done.

**Comment by hieuhlc** [comment]
Hi everyone, I met this issue today and would like to ask if this feature is going to be released soon or not? Thank you for all your works.

**Comment by ThiagoMiranda** [comment]
That'll would help a lot here too!!

**Comment by Maxwell2022** [comment]
I want to run the validation once a specific value is set. With the current implementation it's either for every fields or at the form's submission.

**Comment by kino90** [comment]
Any update on this?

**Comment by gijo-varghese** [comment]
This is what I do:
```
onClick={async () => {
                  await setFieldValue("is_active", false);
                  submitForm();
                }}
```

**Comment by StefanoSGI** [comment]
+1 callback for `setSubmitting` and `resetForm`.

**Comment by kino90** [comment]
@junaidmanzur  I created a component similar to [this](https://github.com/jaredpalmer/formik-persist) to store the form values on change.. Not the ideal solution but it's working until this issue gets closed.

**Comment by hertzg** [comment]
@jaredpalmer This would also solve the situation with multiple submit buttons as you would wait for the promise to resolve and after that `submitForm`

**Comment by sunilb0575** [comment]
> Seems like there is a enough requests here. Let me look into this.
> 
> To synthesize the above, the goal is to respond to a set value event inline (so as to use the updated state) somehow.

Hi @jaredpalmer any updates on this feature?

**Comment by nzyoni** [comment]
I have added a PR, adding promise to the setFieldValue
 #1398 
@jaredpalmer can you take a look?
thanks

**Comment by oskvortsov** [comment]
I have met this problem today, I`m waiting for PR but now use that code below
`const asyncSetFieldValue = async (nameField, value) => {
    await setFieldValue(nameField, value);
    handleSubmit();
  };`

**Comment by leqnam** [comment]
> This is what I do:
> 
> ```
> onClick={async () => {
>                   await setFieldValue("is_active", false);
>                   submitForm();
>                 }}
> ```

FYI: use onClick is working fine on both Safari rather than using onFocus

**Comment by royzer** [comment]
Copying my answer from this SO question - https://stackoverflow.com/questions/56613496/issue-with-values-formik/57686391#57686391

* One way that worked for me is using `componentDidUpdate` (or any other comparable React Lifecycle method) and listening for change in the props.
* Formik exposes the field values in React component's props at `this.props.values`
* When you use `componentDidUpdate`, you just would need to compare the previous props to new props to check if something has changed.

Here is a minimal code to show what I mean.
```

    const _ = require('lodash');
    
    class Sample extends React.Component {
      componentDidUpdate(prevProps) {
        if(!_.isEqual(prevProps.values, this.props.values)) {
          // At least one of the Formik fields have changed. And this.props.values holds this newest data about of the fields.
          triggerWhateverWithNewValues(this.props.values);
        }
      }
    }

```
Think it would solve the problem core problem mentioned in this issue ?

**Comment by Philipp91** [comment]
@royzer I agree that it solves the problem as a workaround, but it doesn't resolve the underlying issue being tracked here. For a nice business logic implementation, one wants to write:

```
await setFieldValue('sendThisToServer', 42);
await submitForm();
```

This makes it obvious that the code does a form submit, as opposed to storing some magic values somewhere and then doing the form submission inside `componentDidUpdate`. Besides making the code shorter and more understandable, it also allows using the local variables before/after `submitForm` without worrying about transferring them into `componentDidUpdate`.

Furthermore, suppose the code between and around these two lines is actually quite complicated (looking up data, doing some validation, and so on) and you might expose it as a separate function to a unit test, whereby the unit test just injects mocks for `setFieldValue` and `submitForm` -- you couldn't do that if all of this depended on the React component lifecycle.

**Comment by geocine** [comment]
I came across this wondering why my wrapped component is not validating on change, even though the `touched` field has been set to `true`. this is what I came up with based on the answers here.

```jsx
import * as React from 'react';
import { Field, useFormikContext } from 'formik';
import { DatePicker } from 'antd';

const FormDatePicker = ({
  name,
  validate,
  onChange = () => {},
}) => {
  const { validateField } = useFormikContext();
  return (
    <Field name={name} validate={validate}>
      {({
        field: { value },
        form: { setFieldValue, setFieldTouched },
        meta
      }) => (
        <>
          <DatePicker
            value={value ? moment(value) : undefined}
            onChange={async (date, dateString) => {
              // workaround: https://github.com/jaredpalmer/formik/issues/529
              await setFieldValue(name, date);
              await setFieldTouched(name, true);
              onChange(date, dateString);
              validateField(name);
            }}
          />
          {meta.error && <p>{meta.error}</p>}
        </>
      )}
    </Field>
  );
};

export default FormDatePicker;
```

**Comment by ZeroDarkThirty** [comment]
@royzer I'm using typescript, where props are strongly typed in an interface and a functional component. So I'm not sure how I can listen for changes in formik props.

**Comment by ZeroDarkThirty** [comment]
> I have met this problem today, I`m waiting for PR but now use that code below
> 
> ```
> const asyncSetFieldValue = async (nameField, value) => {
>     await setFieldValue(nameField, value);
>     handleSubmit();
>   };
> ```

This doesn't make sense if you only want to udpate values and not submit the form.

**Comment by jaredpalmer** [comment]
Just as an update y’all, this is not possible with hooks since useState’s updated no longer accepts a 2nd argument callback anymore. The “correct” approach with hooks is do this with useEffect. This sucks, because you may not be able to figure out from where the change came from, but it is only way to do this.

**Comment by lukas1994** [comment]
could you give an example of how to do it with `useEffect`?

**Comment by MakhouT** [comment]
Would love an example too please.

**Comment by orta-sanz** [comment]
@lukas1994 @MakhouT minor example:

```javascript
import React, { useEffect } from 'react';
import { useFormikContext } from 'formik';

const { values, handleChange } = useFormikContext();

useEffect(() => {
 // At this point firstName it's updated with the lastest user input
}, [values.firstName]);

<input onChange={handleChange} name="firstName" ... />
```

It is less elegant than this (IMO):
```javascript
const { values, setFieldValue } = useFormikContext();

const onInputChange = ({ target: { name, value }}) => {
  // Input value here it's updated with the lastest user input
  setFieldValue(name, value);

  // values.firstName it'sn't updated thats why we need useEffect
  console.log(values.firstName)
}
```
I do not know if the example will serve you, even so, good luck! :rocket:

**Comment by johnrom** [comment]
If the functionality is really important to the Input instead of the form, I'd use a custom input for this purpose. I wonder if there's any value to expose this on `<Field />`.

(FYI, I'm still on v1 but I'm vaguely familiar with v2, so I may have some of the API wrong below)

```
const MyInput = (props) {
    React.useEffect(() => {
        if (props.onValueChanged) {
            props.onValueChanged(props.field.value);
        }
    }, [props.field.value, props.onValueChanged]);

    return <input 
        onChange={props.field.handleChange} 
        name={props.field.name} 
        // etc
        />
}
const MyForm = () =>
    <Formik initialValues={{ myValue: '' }}>
        <Field as={MyInput} name="myValue" /> 
    </Formik>
```

**Comment by ondrejpar** [comment]
This thread is confusing (for me). Looking at the code, `setFieldValues` actually does return a promise. Is this discussion related to v1 only? Can I now implement multiple submit buttons with

```
onClick={() => {
  await setFieldValue('buttonUsed', 'button1');
  submitForm();
}
```

or do I still need some setTimeout hacks? Thanks.

**Comment by johnrom** [comment]
@ondrejpar it's very complicated. Basically, setFieldValue will wait for any asynchronous actions to happen (I believe), but even if this happens, your version of submitForm may have stale values without a setTimeout because React may not commit the render which updates the underlying callback.

**Comment by nirvparekh** [comment]
This guy has awesome solution...
https://stackoverflow.com/a/57684307/4445575

**Comment by johnrom** [comment]
@nirvparekh I would not recommend using that method as the onKeyUp callback still has a reference to `values` which may or may not be updated with the value from the new render. It is still possible (if not now, maybe in the future) for the render not to complete by the time you call onKeyUp. However, when the app is performant enough, this probability is quite low and you may simply be putting off running into this issue until later.

The real answer is that Formik needs to provide access to future state like #2931

**Comment by nirvparekh** [comment]
@johnrom you cann't use useEffect() inside any function. Hooks must be at the top of the component.

**Comment by johnrom** [comment]
SubmitListener is a functional component which returns null, or an empty react node.

**Comment by Aravindhsiva** [comment]
> This guy has awesome solution...
> https://stackoverflow.com/a/57684307/4445575
Didn't Help me

**Comment by ogheneovo12** [comment]
in myUseEffect callback i am making an asynchronous call, and usually encounter memory leak, maybe when my component suddenly unmounts, haven't found a way of cleaning up

**Comment by drewkiimon** [comment]
Why is this closed? As far as I know, there is not a fix for this.

**Comment by johnrom** [comment]
@drewkiimon there is a workaround which I've documented multiple times above -- using effects. There is no way for us to "await" React's render reconciliation process, and even if we could, it would destroy the performance of setFieldValue and other callbacks which would use this method. And as Jared wrote when closing this, hooks do not accept callbacks as arguments, so that isn't a valid solution.

As also mentioned above, the _other_ workaround is for `Formik` to provide access to state outside of React, which I'm currently tracking here #2931 though I'll be opening a separate PR with just the state changes.

The only way to accomplish this is with the following, Redux-like API, which isn't implemented yet:

```tsx
const formik = useFormikApi();
formik.setFieldValue("myValue", "newValue");
// important, this is NOT the `FormikState` of the current render with an updated `myValue`, 
// instead it is the current latest version of Formik's internal state independent of React renders
// which would include the setFieldValue above.
const newState = formik.getState();
```

**Comment by andrew-aladev** [comment]
We can see here the following things:

- TODO comments (linking this issue) that will never be removed.
- `setTimeout` workarounds.
- `componentDidUpdate` code obfuscators.
- triple Brezhnev kisses with `touched` flag.
- this issue is closed.

Everything indicates that `formik` project is dead, we need to move away. Next step is [react-hook-form](https://github.com/react-hook-form/react-hook-form).

Thank you.

![bye bye](https://i.imgur.com/eaVD6AT.jpg)

**Comment by andrew-aladev** [comment]
![formik api today](https://i.imgur.com/b1c0svZ.jpg)

We can see how `formik` api looks like today from point of view of regular developer. Developer is trying to update field value and feels like he wants to do something wrong, something that `formik` is not compatible with.

Please consider handling of `setFieldValue`, `setFieldTouched` and everything else you need internaly in `formik` if you want to save this project. Developers want just single api call that will update field value, this api call should be compatible with any modern react use, react context, etc.

Thank you.

**Comment by deltaepsilon** [comment]
I think I've worked out a hook that solves this problem:

**Comment by durancu** [comment]
> useSetFieldValueWithCallback

Can you share an example please? Thanks!

**Comment by HarlesPilter** [comment]
This can now be done by using Reacts flushSync. It might not be the most performant way since it rerenders the whole app, but it's an option

**Comment by rgallison** [comment]
This needs to be open as it has not been addressed, as far as I can tell

**Comment by KlerKpn** [comment]
My solution in this case
`() => { \
  setFieldTouched('your_field', false); // off errors \
 // any code

  setTimeout(() => validateField('your_field'), 0) // should be call lastest
}`

we reset the field, then knowing that setTimeout will be called exactly last we recheck it for reliability and there will be no memory leak

**Comment by criscola** [comment]
TL:DR: This library is old, never did enough of a redesign to fix its issues, and now we end up with weird stuff (for today's React standards). It's not a bad library, and you might still want to use it for your use case, but it's probably better to stick with react hook form for new projects.

**Comment by ParallelUniv3rse** [comment]
For anyone still struggling with this especially after the state update changes shipped in react 18, I've put together this solution which works well enough for us. 

This custom hook enables us to submit after React's state has been flushed for this hook as well as the `setFieldValue` call. 
```
const useSubmitAfterUpdate = (formik: { submitForm: () => Promise<any> }) => {
    const [submitFlag, setSubmitFlag] = useState(false)
    
    useEffect(() => {
        if (submitFlag) formik.submitForm()
    }, [submitFlag])
    
    const submitFn = useCallback(() => setSubmitFlag(true), [setSubmitFlag])
    return submitFn
}
```

usage: 

```
const submitAfterUpdate = useSubmitAfterUpdate(formik)

<SomeComponent onChange={async (e) => {
    await formik.setFieldValue('key', e.target.value, false) // false is to not trigger validation, it will be validated in the submitForm anyway.
    submitAfterUpdate()
}} />
```

**Comment by tupham9506** [comment]
I faced the same problem.
setTimeout didn't work on react-native for Android because on android, everything is very slow.
I didn't know how many time that need to wait for timeout.
I though I need handle promise by myself. I wrote a custom hook for listen for the values is updated

```
import { useEffect, useRef } from 'react';
import { cloneDeep, isEqual } from 'lodash';

/**
 * Using when set asynchronious value then get setted from form.values
 */
export default function useAsyncFormListener({ form }: any) {
  const listeners = useRef<any>([]);
  const oldValues = useRef<any>(null);

  useEffect(() => {
    const tmpListener = [];
    if (!oldValues.current) return;

    for (let listener of listeners.current) {
      let matched = false;
      for (let key of listener.keyList) {
        if (!isEqual(form.values[key], oldValues.current[key])) {
          matched = true;
          listener.resolve(form.values);
          break;
        }
      }
      if (!matched) {
        tmpListener.push(listener);
      }
    }
    listeners.current = tmpListener;
  }, [form.values]);

  const setValues = async (values: any, shouldValidate: boolean = false) => {
    return new Promise((resolve: any) => {
      oldValues.current = cloneDeep(form.values);
      const keyList: string[] = [];

      for (let i in values) {
        if (values[i] !== oldValues.current[i]) keyList.push(i);
      }

      if (!keyList?.length) return resolve();
      listeners.current.push({
        resolve,
        keyList,
      });

      form.setValues((prev: any) => ({ ...prev, ...values }), shouldValidate);
    });
  };
  return { setValues };
}

```

Then import this custom hook to using:
```
const asyncFormListener = useAsyncFormListener({ form });
....
await asyncFormListener.setValues({
        value: value,
    ....
});

form.handleSubmit();

```
