### ISSUE TITLE
Control radioboxes with a boolean in <Formik initialValue={{}} />

### ISSUE THREAD

**Issue by SimoNonnis** [jaredpalmer/formik#532]
## Bug, Feature, or Question?
Using Formik, I am trying to set a value (inside initialValue={{}}) as a boolean that controls two radioboxes. At the moment I get it to work but with the value as a string only. I need the value to be a boolean not a string. Working demo https://codesandbox.io/s/9nk87l2jr

## Current Behavior
`initialValue={{
    present_at_home_visit: 'true'
}}`

`<Field
                    name="present_at_home_visit"
                    render={({ field }) => (
                      <RadioBox
                        {...field}
                        value="true"
                        id="present_at_home_visit-0"
                        checked={values.present_at_home_visit === "true"}
                        label="Yes"
                      />
                    )}
                  />
`

  `                <Field
                    name="present_at_home_visit"
                    render={({ field }) => (
                      <RadioBox
                        {...field}
                        value="false"
                        id="present_at_home_visit-1"
                        checked={values.present_at_home_visit === 'false'}
                        label="No"
                      />
                    )}
                  />`

## Desired Behavior
`initialValue={{
    present_at_home_visit: true
}}`

`<Field
                    name="present_at_home_visit"
                    render={({ field }) => (
                      <RadioBox
                        {...field}
                        value={true}
                        id="present_at_home_visit-0"
                        checked={values.present_at_home_visit === true}
                        label="Yes"
                      />
                    )}
                  />
`

  `                <Field
                    name="present_at_home_visit"
                    render={({ field }) => (
                      <RadioBox
                        {...field}
                        value={false}
                        id="present_at_home_visit-1"
                        checked={values.present_at_home_visit === false}
                        label="No"
                      />
                    )}
                  />`

## Additional Information

---

- Formik Version: 0.11.11
- React Version: 15.5.4
- CodeSandbox Link: https://codesandbox.io/s/9nk87l2jr
- OS: Mac

**Comment by sshmyg** [comment]
@SimoNonnis For input type radio you can match checked element by value. And input value is just always a string. Because you have one name for batch of fields and different values. You can rename values for your inputs and instead of `true, false` use for e.g. `yes, no` it depends on what server expected to get.

If you want to convert types automatically than use 'yup' with formik to validate and convert you inputs to appropriate type.

It's not a bug of formik. I think it's your misunderstanding of radio inputs workflow.
