### ISSUE TITLE
Prevent form from submitting if status prop is set

### ISSUE THREAD

**Issue by Toesmash** [jaredpalmer/formik#534]
QUESTION:
Is it possible to prevent form from submitting if status prop is not an empty array ?

My case: 
I am using `Field` with independent validation with `validate`. I am tracking error using `setStatus` and `status` props. This way I can either show Yup validation error, or my own error. However, if Yup validates the field correctly, form can be submitted. My goal is to submit form only if there is no Yup validation error nor error from my own validation. 

```
<Field
  validate={(value) => {
    let errorMessage;
    if (value !== authenticator.generateToken(this.state.secret).toString()) {
      errorMessage = 'error';
    }
    setStatus({
      qrVerify: errorMessage
    });
  }}
  name="qrVerify"
  placeholder="123 456"
  type="text"
  className="text-input"
/>
{
  status && status.qrVerify ? (
    status.qrVerify && <div className="text-input--feedback">{status.qrVerify}</div>
  ) : (
    errors.qrVerify && <div className="text-input--feedback">{errors.qrVerify}</div>
  )
}
```
If anyone gets better idea on how to validate input value and pass this information to Yup please do let me know. Thanks for advice.

**Comment by jaredpalmer** [comment]
Formik only submits if there are no errors (in errors). You would be better to extend and manipulate errors instead of status for this use case.
