### ISSUE TITLE
On initial value change, update props.value

### ISSUE THREAD

**Issue by abelkbil** [jaredpalmer/formik#536]
## Bug, Feature, or Question?
Question

## Current Behavior
How to update default values when the initial values change 

```
export default withFormik({
    mapPropsToValues: (props: Props) => {
        return (
            {
                id: props.initialData.id,
                name: props.initialData.name
            }
        );
    },
```

## Desired Behavior

Once the props value update re render the form
Any support is helpful. Thank you

## Additional Information
https://codesandbox.io/s/k5w5qn94z7

---

- Formik Version:0.11.11

**Comment by abelkbil** [comment]
https://stackoverflow.com/questions/49491110/withformik-on-initial-value-change-update-props-value

**Comment by jaredpalmer** [comment]
You can set enableReinitialize to true and then whenever you change props the form the form will reset

**Comment by abelkbil** [comment]
@jaredpalmer thanks

**Comment by vctormb** [comment]
@jaredpalmer is it possible to update the values without reseting the entire form? For example, imagine if I have a redux call and I want to wait to receive new props to populate some part of my form, but not reseting the another fields in the form.

**Comment by tomalexhughes** [comment]
@jaredpalmer @vctormb Interested in knowing if there is a solution to this, I have a similar use case.

**Comment by chodorowicz** [comment]
Yeah, same issue here. It'd very helpful if in `mapPropsToValues` we had access to potential previous values.

**Comment by ElagrebiAli** [comment]
@jaredpalmer  same issue here :/ 
I have a redux call and I want to wait to receive new props to populate some part of my form, but not reseting the another fields in the form.

**Comment by jaredpalmer** [comment]
Set `enableReinitialize` to `false`

https://jaredpalmer.com/formik/docs/api/formik#enablereinitialize-boolean

**Comment by ElagrebiAli** [comment]
well, this does not work :/ 
i have a redux call when i fire the handleSubmit , my state updated , i pass them to mapPropsToValues  and then my values updated , but the values inside my component didn't handle this change .
what i want , i want when my values updated , my component handle this chnage of values

**Comment by elmeerr** [comment]
I just face this issue. Inside my form I call redux to update a dropdown. The dropdown updates but the previous value is set to initial data (empty). Is there any way to avoid this behavior or to have access to previous value?

**Comment by ElagrebiAli** [comment]
did you use enableReinitialize and set it to true ? 
if yes , this will update you compoment but reinitialize it , and then the component will handle only the the store change .
try to give me a snippet or any thing of your code , may i can help you

**Comment by elmeerr** [comment]
I use `enableReinitialize` the problem is that I call the redux action in my form (child) but the store change is handled on my Parent (because I use for other things)...so this updates my component, then set form values to empty (because of the new state - that I pass down as props).

If I connect also my form component to redux, this should solve but I didn't really want to do that
