### ISSUE TITLE
Field's value = 0

### ISSUE THREAD

**Issue by cristianfraser** [jaredpalmer/formik#538]
## Bug, Feature, or Question?

Bug

## Current Behavior

Have a select input, with `options = [{ value, label }]`. One of the options has `value = 0`, but can't be selected. Trying to select it just clears the input

## Desired Behavior

To be able to select the option with `value = 0`

## Suggested Solutions

I'm guessing somewhere in the code, the `handleChange` (or `setFieldValue`) function is checking for `if (!newValue)`, and clearing the input (setting `value = ''`) if `!newValue === true`.

If that's what's happening, my suggestion would be changing `if (!newValue)` to `if (!newValue && newValue !== 0)`, so that `value = 0` is treated differently to `value = ''`.

## Additional Information

- Formik Version: 0.11.11
- React Version: 16.2

**Comment by jaredpalmer** [comment]
Will take a look at this.

**Comment by hoffmanilya** [comment]
Just ran into this myself. Are there any workarounds to use zero as the option's value? Thanks!

**Comment by johnrom** [comment]
Reopening because it looks like it was mistakenly marked stale.

**Comment by jojoucsd** [comment]
Hey just want to help out not sure if I understand it correctly. But it seems was working properly. 

"https://codesandbox.io/embed/formik-select-example-shgyt"

line 49
<option value={parseInt(0)} label="custom" />

**Comment by johnrom** [comment]
Yeah, it looks like it works in v2 and 1.5.8 as well: https://codesandbox.io/s/formik-select-example-t7qgd
