### ISSUE TITLE
validate call causes crash on Android (using react native)

### ISSUE THREAD

**Issue by maxaggedon** [jaredpalmer/formik#542]
## Bug, Feature, or Question?
Bug

## Current Behavior
When defining the `validate` prop, even just as `() => true`, I get the following error at the first `setFieldValue` call :

![capture d ecrans_20180328-120522](https://user-images.githubusercontent.com/17004545/38022937-353ad720-3281-11e8-9af6-233ce6c3f3ac.png)

Strange thing is, when I attach the debugger, I don't get it anymore...

---

- Formik Version: 0.11.11
- React Version: 16.3.0-alpha.1
- React Native Version: 0.54.2
- OS: Android 7.0
- Node Version: 6.9.4
- Package Manager and Version: yarn 1.5.1

**Comment by jaredpalmer** [comment]
Can you make snack that demos this? @browniefed has this happened to you?

**Comment by browniefed** [comment]
Nope, I am using Yup though so not the raw validate call also using alpha release of formik not .11.11

**Comment by jaredpalmer** [comment]
@maxaggedon `() => true` is not an acceptable fn to pass to validate. `() => {}` is. Whatever you return must be an object.

**Comment by maxaggedon** [comment]
@jaredpalmer sorry for that, the documentation is clear about it, it should return the errors and not a boolean. My mistake. Anyway I ended up using yup as it was suggested...
