### ISSUE TITLE
Custom onBlur on Field overrides default behavior

### ISSUE THREAD

**Issue by elado** [jaredpalmer/formik#545]
## Bug, Feature, or Question?
Bug/Feature

## Current Behavior
a `Field` with a custom `onBlur` removes the default validation/touched behavior

```jsx
<Field name="fname" onBlur={() => console.log("custom")} />
```

https://codesandbox.io/s/yk9mmj1kwx

## Desired Behavior

custom `onBlur` prop will be chained to the internal `handleBlur`

## Suggested Solutions

in [`handleBlur`](https://github.com/jaredpalmer/formik/blob/master/src/Field.tsx#L128)
```
if (this.props.onBlur) this.props.onBlur()
```

---

- Formik Version: 0.11.11
- React Version: 16.2
- CodeSandbox Link: https://codesandbox.io/s/yk9mmj1kwx

**Comment by jaredpalmer** [comment]
Hrmmm. Need to think about this one

**Comment by elado** [comment]
This is why I didn't want to make a PR first ;)
If it's too breaking, how about another `preserveBlurBehavior` boolean?

**Comment by vai0** [comment]
Here's my solution. Had to resort to a `setTimeout` as it seems `field.touched` and `field.errors` aren't immediately updated after formik's onBlur event is called:

```javascript

...
<Field name={name} id={name} component={CustomInputText} />
...

class CustomInputText extends React.PureComponent {
    handleBlur = e => {
        const {
            field: { name, onBlur },
        } = this.props;

        onBlur(e);

        // The latest touched and errors aren't available until after the
        // formik's onBlur handler has been called. Setting a timeout allows us
        // to access the proper touched and errors after onBlur event has
        // occurred.
        setTimeout(() => {
            const {
                form: { touched, errors },
            } = this.props;
            const isError = touched[name] && errors[name];
            const isSuccess = touched[name] && !errors[name];

            if (isError) {
                console.log('validation error');
            }

            if (isSuccess) {
                console.log('validation success');
            }
        }, 0);
    };

    render() {
        const { field, ...otherProps } = this.props;

        return (
            <input
                className="floating-field"
                type="text"
                {...field}
                {...otherProps}
                onBlur={this.handleBlur}
            />
        );
    }
}
```

**Comment by Andreyco** [comment]
How about this?

```
function formikOnBlur(evt) {
  // formiks default handler
}

function getFieldProps(props) {
  const _props = {
    onBlur: (...args) => {
      formikOnBlur(...args);
      props.onBlur && props.onBlur(...args);
    },
  };
}

<Field name="email">
  {field => (
    <input
      {...field.getFieldProps({
        onBlur: () => console.log('blur'),
      })}
    />
  )}
</Field>
```

`props` getter would chain "overrides" props while still keeps Formik work.

**Comment by maecapozzi** [comment]
This would be a really helpful feature for interactions like this one. 

![giphy](https://user-images.githubusercontent.com/11462208/55013181-00aa0100-4fbf-11e9-822e-fe4a6f5fa070.gif)

**Comment by seanders** [comment]
I'm a big fan of the approach outlined by @Andreyco. This would follow the 'prop getters' pattern as is outlined here: https://kentcdodds.com/blog/how-to-give-rendering-control-to-users-with-prop-getters

It's used to some great effect in https://github.com/downshift-js/downshift
