### ISSUE TITLE
Include `FormikState` in `FormikBag`

### ISSUE THREAD

**Issue by migueloller** [jaredpalmer/formik#546]
## Bug, Feature, or Question?
Question

## Current Behavior
`FormikBag` doesn't include `FormikState`.

## Desired Behavior
`FormikBag` includes `FormikState`.

## Suggested Solutions

When `handleSubmit` is called, the passed in `FormikBag` contains values such as `errors`, `touched`, and `status`.

## Additional Information
The reason I need to see this is because after the submission, if a certain field was touched (phone number in this case), I have to take the user to a new screen (so they can verify their phone via SMS).

---

- Formik Version: 0.11.11
- React Version: v16.2.0
- TypeScript Version: N/A
- CodeSandbox Link: N/A
- OS: macOS v10.13.3
- Node Version: v9.9.0
- Package Manager and Version: yarn v1.5.1

**Comment by sergeydevhub** [comment]
Still is desirable update
