### ISSUE TITLE
Formik Validation Yup error message: Change field name

### ISSUE THREAD

**Issue by EmirGluhbegovic** [jaredpalmer/formik#547]
## Bug, Feature, or Question?
Question

## Current Behavior
if id="maxInterest"
The error message will show the id name: maxInterest is required.

## Desired Behavior
if id="maxInterest"
The error message will show the id name: Max interest is required.
Some way to specify the field name in the error message.

## Suggested Solutions

In the validationSchema allowing a name to be specified for each input.

- Formik Version: formik": "^0.11.11",
- React Version: "react": "^16.2.0",
- OS: MacOS
- Node Version: v8
- Package Manager and Version: Yarn

**Comment by jaredpalmer** [comment]
Not sure, this is a Yup-related question so I would ask it there.
