### ISSUE TITLE
FieldArray - arrayHelpers - add removeItem

### ISSUE THREAD

**Issue by elado** [jaredpalmer/formik#548]
Feature request

`FieldArray` `arrayHelpers.remove` gets an index. I'm suggesting it will also expose `removeItem/removeValue` that gets a value, and will remove all instances of that value in the array.

This helps when working with checkbox list, for example. Currently the only way is to grab the `indexOf(value)` and use `remove`.

https://codesandbox.io/s/o5pw1vx916

---

- Formik Version: 0.11.11

**Comment by aashishnagpal** [comment]
@martavasconcelos @jaredpalmer

I guess somehow the code merge was missed. The related issue and PRs are closed but the code is not there anymore.

https://github.com/jaredpalmer/formik/blob/master/src/FieldArray.tsx - Doesn't contain removeValue and handleRemoveValue methods are missing entirely.

CC: @elado
