### ISSUE TITLE
onSubmit required for typescript

### ISSUE THREAD

**Issue by keithmichelson** [jaredpalmer/formik#552]
I'm using typescript and handling the form submit myself, passing props. However I get typescript errors when I don't include the onSubmit function. Everything works fine I just don't want to include that function being empty.
It doesn't apprear that onSubmit is actually firing either.

---

- Formik Version: v0.11.11
- React Version: 16.2
- TypeScript Version: 2.7.2
- OS: Mac

**Comment by ivanasetiawan** [comment]
+1 I have this problem as well, `onSubmit` is not firing but I cannot remove the function because it's required

**Comment by malcolm-kee** [comment]
Hmm... can you clarify what do you mean by handling submit yourself? If you mean you has a callback props that you call to submit the form, the recommended way to do in formik is to call your custom callback in the onSubmit function.

**Comment by jaredpalmer** [comment]
onSubmit is required

**Comment by Alebron23** [comment]
lkjlkjl

**Comment by negrolio** [comment]
What I did is pass null
`<Formik initialValues={initialValues} onSubmit={null}>`
