### ISSUE TITLE
Remove usage of unsafe lifecycle hooks (React 16.3)

### ISSUE THREAD

**Issue by saadq** [jaredpalmer/formik#553]
## Bug, Feature, or Question?
Feature?

## Current Behavior
Using Formik with React 16.3 with the [`<React.StrictMode></React.StrictMode>`](https://reactjs.org/blog/2018/03/29/react-v-16-3.html#strictmode-component) component will trigger some warnings.

## Desired Behavior
Different lifecycle hooks should be used.

## Suggested Solutions
The warning message states:

```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:

componentWillMount: Please update the following components to use componentDidMount instead: Field, Formik
componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Formik
```

The React team also made [`react-lifecycles-compat`](https://github.com/reactjs/react-lifecycles-compat) which should allow for backwards compatibility when using the new lifecycle hooks. 

## Additional Information
More details are in the recent React [blog post](https://reactjs.org/blog/2018/03/29/react-v-16-3.html).

**Comment by jaredpalmer** [comment]
There is a large rewrite required for 16.3. But the great news is that it will make Formik MUCH smaller, simplify tooling (microbundle), and no longer have prop-types as a peer dep.

**Comment by mikelax** [comment]
@jaredpalmer is the large rewrite you are talking about here PR #423 ?
We are happily using formik in a couple of projects, and would like to put a plan to get them moved to 16.3, but we want that to be coordinated with the new release of formik. 

Where should we "track progress", on that PR, or elsewhere? 
Let us know if there is any help needed once you have an RC, etc.

**Comment by jaredpalmer** [comment]
Yes that was my first attempt. Just need time to finish it up.

**Comment by colinrcummings** [comment]
:pushpin:
