### ISSUE TITLE
Yup.boolean() not working correctly

### ISSUE THREAD

**Issue by bpearce6942** [jaredpalmer/formik#555]
## Bug, Feature, or Question?
Bug

## Current Behavior
Setting a property in the validation schema to use Yup.boolean(), initial value is false.  Change other text input in form.  Form isValid = true.  

## Desired Behavior
Form isValid should be false in the above scenario.  The property value is still false and should not evaluate as passing the schema validation.

## Suggested Solutions
???

## Additional Information
I've verified that I can work around this by replacing Yup.boolean() with Yup.mixed().oneOf([true]).

---

- Formik Version: 0.11.11
- React Version: 16.2
- TypeScript Version:
- CodeSandbox Link:
- OS: Windows
- Node Version: 8.10
- Package Manager and Version: Yarn 1.3.2

**Comment by cagmz** [comment]
Thanks for the workaround!

**Comment by MincePie** [comment]
I tried this, but get an error that says: yup__WEBPACK_IMPORTED_MODULE_8__.mixed(...).oneOf(...) is not a function

**Comment by Masoom4874** [comment]
Getting same error as boolean not found
"ReferenceError: boolean is not defined"

export const SkillSchema = object({
	skillId: number().nullable(),
	image: string().nullable().trim(),
	skillName: string().required("Skill Name is required").trim(),
	skillScore: number().required("Required").typeError("Only number"),
	isKitEnabled: boolean().optional(),
	isProjectEnabled: boolean().optional()
})
