### ISSUE TITLE
Use `action` attribute on `form` element.

### ISSUE THREAD

**Issue by ankurkaushal360** [jaredpalmer/formik#556]
## Bug, Feature, or Question?

Question

Stupid question but is it possible to use `action='/api' method='POST'` instead of `ajax`? I am trying to use it but its not working for me. Is there a `prop` I have to supply?

- Formik Version: 0.11.11
- React Version: 16.2.0
- TypeScript Version: N/A
- CodeSandbox Link: N/A
- OS: Mac OS X 10.13.3
- Node Version: 8.0.0
- Package Manager and Version: NPM, 5.8.0

**Comment by ankurkaushal360** [comment]
Turns out I can just do this:

`<button type='submit' onClick={() => { submitForm() }}>Submit</button>`.

**Comment by ankurkaushal360** [comment]
I don't think I wanted that, if I do that, it `submits` without validation which is not what I expect.

**Comment by lisamartin00** [comment]
@ankurkaushal360 did you solve this?  I'd love to know how!

**Comment by rovansteen** [comment]
What’s the point in using Formik if you don’t want to submit your form data with JavaScript?

**Comment by lisamartin00** [comment]
Our team is working on some OAuth flows within a next.js app.  An XHR `POST` that responds with a redirect code (e.g. `302`) will cause the browser to initiate another XHR request but _will not_ cause the browser to redirect the user to a new location. On the other hand, a standard HTML form `POST` that responds with a redirect code _will_ cause the browser to redirect the user, so that's where we've landed.  Now our formik logic isn't working.  We may have to achieve this with another approach if it's not really doable via formik.

**Comment by rovansteen** [comment]
I still don't really understand what you are looking for. Formik puts your from values in memory so you can use them easily with JS/React. If you want to do a regular form POST action it will use the values that are in the DOM. These are two completely different things and you can't mix them together.

Why don't you use redirect manually in your XHR handler after you get a response from the server?

**Comment by andrewdang17** [comment]
I just spent the last few days building out this form only to realize the form won't submit with `action`. Like @rovansteen said, it seems like they are 2 completely different things but oddly enough you can't do a normal action post. Creating a regular form without Formik and submitting will reload the page as expected:

```
import React from 'react';

const Form = () => {
  return (
    <form>
        <input id="example" type="text" name="text" />
        <input type="submit" value="Send" />
    </form>
  )
}

export default
```

but with Formik, no reload happens. If you inspect the state you'll still see the submit count go up but the submission actually never happens. This is either a bug or needs to be stated in the docs or README cause I just spent a ton of time building this only to find out now it won't work. Also hate to @ you directly, but @jaredpalmer you think you can shed some light on this? 
```
const MyForm = props => {
  const { values, handleChange, handleBlur, handleSubmit } = props;

  return (
    <form onSubmit={handleSubmit}>
      <input
        type="text"
        onChange={handleChange}
        onBlur={handleBlur}
        value={values.name}
        name="name"
      />
      <button type="submit">Submit</button>
    </form>
  );
};

const MyEnhancedForm = withFormik({
  mapPropsToValues: () => ({ name: '' }),
  handleSubmit: (values, { setSubmitting }) => {
    setSubmitting(false);
  }
})(MyForm);
```

**Comment by rovansteen** [comment]
That’s because the Formik’s handleSubmit prevents the submit event’s default behavior. You could pass your own handler to the form element but then you lose out on a lot of the benefits of Formik. I really don’t understand why you want to combine vanilla HTML forms with Formik.

**Comment by andrewdang17** [comment]
@rovansteen not every thing has to be a single page app and there are plenty of reasons to use a regular forms with the action attribute. @lisamartin00 had a good one. In my case, I am using rails and can redirect with instance variables for the view I redirect to. Now I have to make multiple ajax calls to fetch data I could easily just get through a normal form post and redirect.

**Comment by rovansteen** [comment]
I totally get why you would want a normal form. But I don’t get why you want to use Formik then? If vanilla HTML forms does the job for your use case why are you complicating things by adding Formik to the mix?

**Comment by goldenshun** [comment]
> What’s the point in using Formik if you don’t want to submit your form data with JavaScript?

Glad you asked! Straight from Formik's README:
```
Formik is a small library that helps you with the 3 most annoying parts:
1. Getting values in and out of form state
2. Validation and error messages
3. Handling form submission
```

Even when using HTML forms, one can still draw value from Formik for 1 and 2.

> Formik puts your from values in memory so you can use them easily with JS/React. If you want to do a regular form POST action it will use the values that are in the DOM. These are two completely different things and you can't mix them together.

I disagree with your premise here. Formik is an extension of React and React is designed to control the DOM. Even the [React Forms](https://reactjs.org/docs/forms.html#controlled-components) docs show that React itself doesn't get in the way of initiating the default form submission event. Quite the opposite in fact, because you the developer need to explicitly call `e.preventDefault()` if you want to handle the form submission via `xhr`.

One reason why Formik prevents the default form submission is because Formik supports asynchronous validation via the `validate` function. If the form's `onSubmit` returns, then the default submission would occur before the async validation has a chance to run. Given that, the only way that I can see to use Formik with HTML form posts is to submit the form via javascript yourself:
```
const formEl = useRef(null);

...

 const handleSubmit = values => {
  formEl.current.submit();
};

...

<form action="/path" ref={formEl}> ...
```

Full demo here: https://codesandbox.io/s/826qv6lv7l

**Comment by rovansteen** [comment]
@goldenshun 
> I disagree with your premise here. Formik is an extension of React and React is designed to control the DOM. Even the React Forms docs show that React itself doesn't get in the way of initiating the default form submission event. Quite the opposite in fact, because you the developer need to explicitly call e.preventDefault() if you want to handle the form submission via xhr.

I'm not stating that React doesn't work well with vanilla HTML forms, I'm talking about Formik. They are fundamentally different as the values from Formik are in memory but the values from a HTML form are in the DOM.
```jsx
<Formik initialValues={{ first_name: 'John', last_name: 'Doe' }}>
  <form>
    <input name="first_name" />
  </form>
</Form>
```
If you would submit this form without Formik it would only contain a `first_name`, but if you submit it with Formik it has both `first_name` and `last_name`. 

@goldenshun 
> I'm not sure why you think a form using the action attribute should just use vanilla html.

I'm not saying that. React !== Formik. 

> How it is submitted should not matter since this is just a form builder.

This is not true, Formik isn't just a form builder it's more a form manager; it holds the values, it validates them etc.

Formik is a great library but it's opinionated in the fact that it expects you to use JavaScript to manage it completely. I'm sure there are other form libraries in React out there that do work well together with the HTML <form> element.

**Comment by goldenshun** [comment]
@rovansteen 
> the values from Formik are in memory

Except in the `withFormik` example, Formik is managing the DOM too: https://jaredpalmer.com/formik/docs/api/withformik

I also provided a full working demo that shows how you can use Formik with HTML forms. Is there a problem with that demo? It allows you to use Formik _and_ support an HTML form post. What am I missing?

**Comment by rovansteen** [comment]
@goldenshun no Formik doesn't manage the DOM, React does because you tell it to do so in *your* component. There's nothing wrong with your example, it's just a workaround. Personally I would use another form library that works better together with HTML forms.

**Comment by rovansteen** [comment]
@goldenshun look at this forked example, Formik has the `firstName` in it's values, even tho there is no actual input with that name. https://codesandbox.io/s/pkjp0rwmx0

**Comment by goldenshun** [comment]
I feel sorry for anyone who stumbles across this thread because they are in for a world of confusion. 

The answer to the original questions is **yes** you can use `action='/api' method='POST'` instead of ajax and the working demo is here: https://codesandbox.io/s/826qv6lv7l ✌️

**Comment by andrewdang17** [comment]
@goldenshun thanks for the workaround example! I still think this should be in the docs but hopefully someone can find this thread if they need to use the `action` attribute

**Comment by garfenter** [comment]
@goldenshun thank you! Very helpful.

**Comment by makstaks** [comment]
@goldenshun thanks for the example, super helpful! Not sure if you meant this, but your example code doesn't include `method='POST'` as your comment implies.  

> I feel sorry for anyone who stumbles across this thread because they are in for a world of confusion.
> 
> The answer to the original questions is **yes** you can use `action='/api' method='POST'` instead of ajax and the working demo is here: https://codesandbox.io/s/826qv6lv7l ✌️

**Comment by just4fun** [comment]
Went through the whole thread and also want to share my thoughts and my use case.

+++++

As you guys mentioned, basically we have two ways to submit the form.

1. Normal form submission (without JavaScript)

This one is pretty common, just need to add `action` and `method` to `form` element, that's it. With this approach, let's say we are using `express` as the server, it's easy to use `res.redirect` to redirect in the server-side (e.g. login form, redirect to home page after verification).

With the online examples above, we can use `ref` to invoke the normal form submission with `formRef.current.submit()`. Then to use `formik` here is only for frontend validation.

2. Frontend submission (with JavaScript)

This is what we are doing with `formik` in most cases, send an ajax call to the backend server, and get JSON response.

+++++

My case:

I'm using next.js to build login form. I can use both ways to submit, but I choose the 2nd one (actually I prefer 1st solution, which make the redirection happen in then server-side).

Regarding the 1st solution, the thing is in the `/login` route in express, if the account or password is incorrect, I need to render the login page again with keeping what users already key in, meanwhile I need to render the error as well. In normal server-side rendering app like Rails, it's easy. But with next.js, it will be a little bit hard (I will appreciate if you have good solution to handle this case in next.js).

With 2nd solution, which will return us JSON response, I can easily display according error in frontend bases on the JSON response. The only disadvantage is we can only do redirection in frontend, this is what I don't like.

**Comment by quangv** [comment]
In `jest` I believe this cause an infinite loop? I'm worried in other environments/browsers it could do the same. The [accepted answer](https://github.com/jaredpalmer/formik/issues/556#issuecomment-472158007) is a couple years old and has many 👍 so maybe not?

**Comment by smackfu** [comment]
We ran into the same issue with the infinite loop in tests.  I assume when it calls `submit` on the ref, that triggers the formik submit again.  Our "solution" was to use a state variable to see whether the form had been submitted already, to avoid double submitting:
```
  const [isSubmitted, setSubmitted] = useState(false);
  const handleSubmit = () => {
    if (!isSubmitted) {
      formRef.current.submit();
      setSubmitted(true);
    }
  };
```
This doesn't impact the real functionality, but fixes the test.  Not ideal since it's code added for tests but this whole thing is a bit of an edge case.
