### ISSUE TITLE
Maintain a changelog

### ISSUE THREAD

**Issue by hakib** [jaredpalmer/formik#557]
## Bug, Feature, or Question?

Feature

## Current Behavior

No changelog.

## Desired Behavior

Having a changelog will make it easier to upgrade from older versions of formik.

## Suggested Solutions

Maintaining a changelog.

## Additional Information

I've recently had to upgrade an older version of Formik and I found it difficult to identify what were the changes from my version to the last one. 

I think a changelog with the major changes (and possibly breaking changes) might be usefull.

---

- Formik Version:
- React Version:
- TypeScript Version:
- CodeSandbox Link:
- OS: 
- Node Version:
- Package Manager and Version:

**Comment by billdybas** [comment]
Changes are currently documented on the Releases page: https://github.com/jaredpalmer/formik/releases
