### ISSUE TITLE
Field validate and isValid

### ISSUE THREAD

**Issue by peterpetre** [jaredpalmer/formik#558]
## Bug, Feature, or Question?
Bug

## Current Behavior
isValid is false if errors: { email: undefined, password: undefined }

## Desired Behavior
isValid should be true if errors: { email: undefined, password: undefined }

## Suggested Solutions
other than checking only `this.state.errors && Object.keys(this.state.errors).length === 0`
should check `Object.values(this.state.errors).every(error => error === undefined)` too

## Additional Information
From docs - Field - validate : **Synchronous and if invalid, return a string containing the error message or return undefined.**

---

- Formik Version: 0.11.11
- React Version: 16.2.0
- TypeScript Version:
- CodeSandbox Link:
- OS: macOS High Sierra
- Node Version: 9.10.0
- Package Manager and Version: yarn 1.5.1

**Comment by jaredpalmer** [comment]
Feel free to submit a PR.

**Comment by peterpetre** [comment]
Sorry i dont have much time right now, even with the suggested solution i met more problems when using arrays or nested objects with field validate. So probably will need to deep check for undefined.
