### ISSUE TITLE
IE 11 Error: Object doesn't support property or method 'isNaN'

### ISSUE THREAD

**Issue by wkgalla** [jaredpalmer/formik#559]
## Bug, Feature, or Question?
Bug

## Current Behavior
Object doesn't support property or method 'isNaN' error in IE 11 when **input component type is number**.
And field value remains same.

## Desired Behavior
It should update value on typing new value

## Suggested Solutions
It might be due to this change https://github.com/jaredpalmer/formik/pull/437

- Formik Version: 0.11.11
- React Version: 15.6.2
- TypeScript Version: 2.6.2
- OS: windows 10
- Node Version: 8.4.0
- Package Manager and Version: npm 5.6

**Comment by Ciaran0** [comment]
Having the same issue as described above on ie11

**Comment by jaredpalmer** [comment]
Lets get a PR going

**Comment by Ciaran0** [comment]
For anyone that needs a solution asap, to solve this I included the Number.isNan from [core-js](https://github.com/zloirock/core-js).
I like the lodash.isnan solution from @ohbarye
