### ISSUE TITLE
Multiple select

### ISSUE THREAD

**Issue by Robinfr** [jaredpalmer/formik#566]
## Bug, Feature, or Question?
Question

## Current Behavior
I'm trying to create a multiple select field, but it seems empty out the array when I click on a item.

## Desired Behavior
Update the array when I change selection.

## Suggested Solutions
Maybe some specific behaviour for the `multiple` attribute?

## Additional Information

---

- Formik Version: 0.11.11
- React Version: 16.2
- TypeScript Version: 2.8.1
- CodeSandbox Link: https://codesandbox.io/s/mzpv1o7pm9
- OS: Linux
- Node Version: 8.11.1
- Package Manager and Version: NPM 5.8.0

**Comment by Robinfr** [comment]
@ricardobrandao that does seem to work but is not really the best way to do it for such a common case. Wouldn't it be better if something like this was built into Formik as perhaps a separate component?

**Comment by ricardobrandao** [comment]
I agree. It would be great if the multiple select "just work" - as for the simple select. 

However, I'm not sure on how to properly address this. I believe that having a separate component is not the best way to go. After a quick look at the code, it seems that we could do something on the Formik's [handleChange](https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L424) callback. Nevertheless, @jaredpalmer should be the right person to give you an answer.

I'm currently evaluating Formik - and some other options - to use in my companie's app. I've just started doing that yesterday so Formik is kinda new to me.

**Comment by Robinfr** [comment]
Yeah there probably needs to be an exception added for the `val` part to evaluate `select` cases or something.

**Comment by tonysepia** [comment]
I think the original poster has eventually solved this problem here:
https://codesandbox.io/s/n33qkoy64m

**Comment by seanbetts** [comment]
> I think the original poster has eventually solved this problem here:
> https://codesandbox.io/s/n33qkoy64m

This seems to work well but it based on v0.11.11 of Formik. Has anyone got a working example of implementing multiple select on an up-to-date version of Formik?
