### ISSUE TITLE
Form isValid property doesn't update with FastField

### ISSUE THREAD

**Issue by ricardobrandao** [jaredpalmer/formik#567]
## Bug, Feature, or Question?
Bug

## Current Behavior
When using ```<FastField>``` the ```isValid``` form property does not update.

## Desired Behavior
The ```isValid``` property should update on field blur.

## Additional Information
If we force the form validation (i.e. using ```validateForm()```) the ```isValid``` is properly updated.

---

- Formik Version: 1.0.0-alpha.4
- React Version: 16.3.1
- CodeSandbox Link: https://codesandbox.io/s/vq8l9708o5

**Comment by ricardobrandao** [comment]
Hi Jared,

Thanks for the quick reply :)

Sorry if I am missing something but a blur does happen. That is why the validation message is shown and the touched field is updated. However, the isValid field doesn’t change. If you can, please take a look at the codesandbox that shows that behavior.

**Comment by jaredpalmer** [comment]
Will examine tomorrow

**Comment by jaredpalmer** [comment]
Okay I think I understand what happening. Will take a stab in am

**Comment by harunurhan** [comment]
Having the same issue, actually `isValid` is not updated on a valid form even after blur, for some reason modifying random `ArrayField`, like `push` causes update on `isValid`

**Comment by ricardobrandao** [comment]
It is working properly at least since version 1.3.1.
