### ISSUE TITLE
Change form values based on other form siblings.

### ISSUE THREAD

**Issue by pradok** [jaredpalmer/formik#57]
Hi
I have a dropdown select where selecting one of its values changes the options for next sibling select. Both of the selects also have required validations. Not sure if there is a Formik way internally managing via its callbacks like handleChange or handleChangeValue?

Thanks

**Comment by eonwhite** [comment]
Just write your own change handler. You can call `setValues` directly to set the value of the field you're updating and its sibling's values. The set of available options for the sibling select can be kept in your component state, so just update that with `setState`.

Something like:

```
handleDropdownChange(e: React.ChangeEvent<HTMLSelectElement>) {
  const siblingOptions = e.target.value == 'foo' ? ['bar', 'baz'] : ['bap'];
  this.props.setValues( { ...this.props.values,
                          myDropdown: e.target.value,
                          mySibling: siblingOptions[0] });
  this.setState( { siblingOptions: siblingOptions });
}
```

**Comment by jaredpalmer** [comment]
@ian haven't pushed 0.8 so `setValues` above will be `handleChangeValue` fyi.
