### ISSUE TITLE
Async validation error handling

### ISSUE THREAD

**Issue by ricardobrandao** [jaredpalmer/formik#571]
## Bug, Feature, or Question?
Question/Suggestion

## Current Behavior
Async validation captures thrown exceptions.

## Desired Behavior
I believe that we should not drive the application flow using exceptions, but instead, we could use [Promise.reject](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject) to return the errors. Moreover, it is harder to reason about a function when one could return promises or throw exceptions (i.e. it is not clear that we should throw an exception inside the validation function). Some more regarding this discussion [can be seen here](http://2ality.com/2016/03/promise-rejections-vs-exceptions.html).

I know that this is a breaking change but since Formik is getting a major version soon, this could be the right time to do it.

## Suggested Solutions

Add a ```catch``` handler to the validation function.

## Additional Information

---

- Formik Version: 1.0.0-alpha.4
- React Version: 16.3.1

**Comment by lukas-zech-software** [comment]
As I stumbled upon this as well I want to add my 2 cents:

Exceptions  should be reserved for unexpected errors that break the control flow.

Validation errors on the other hand are something and is to be expected.

Also the [sync API](https://github.com/jaredpalmer/formik#validate-values-values--formikerrorvalues--promiseany) and the async API should behave the same (apart from being async)

The synch API expects a error object to be returned and not to be thrown, so the async API should expect the object to be returned via `Promise.resolve` as well, not being throw or via `Promise.reject`

Rejecting would signal, that the validation could not be completed, which is different from not yielding any errors.
Therefore validation errors should be resolved while errors during validation should be rejected

**Comment by erikcameron** [comment]
FWIW, I just spent 30 mins trying to debug a missing form validation ("why, nay, /how/ is this code not running?!?") before I realized the validator itself was crashing, but Formik was trapping the exception, presumably because it thought the validator was trying to return a form error asynchronously.
