### ISSUE TITLE
Update 'other' select tag display on component re-render

### ISSUE THREAD

**Issue by stuartmoir1** [jaredpalmer/formik#572]
## Bug, Feature, or Question?
Question

## Current Behavior
I have a container that passes props to a component. The component consists of two select HTML select tags, with the default value of each tag being set to different state property value via initialValues.

Selecting another value in one or other of the select tags (1) changes the value displayed in that tag via setFieldValue and (2) changes the state in the container, forcing a re-render of the component with the container’s new state property values.

However, although these values are passed to the appropriate component select tags (via initialValues) and set as ‘defaultValue’ the select that was not manually changed does not display with the new state value.

Using setValue and resetForm instead setFieldValue to change the value does not resolve this issue. The ‘other’ select value displayed can be overwritten by writing to the appropriate element in the DOM. However, the re-render with the updated state props still does not display the required value in the select tag that has not been previously manually changed.

## Desired Behavior
If one select tag value is updated allow the value to be displayed in the other tag to be updated by the new props on re-render.

## Suggested Solutions
?

## Additional Information

- Formik Version: 0.11.11
- React Version: 16.2
- OS: Ubuntu
- Node Version: 8.10.0
- Package Manager and Version: npm 5.6.0

**Comment by jaredpalmer** [comment]
Can you put together a codesandbox by any chance?

**Comment by latviancoder** [comment]
I am not sure I am understanding the problem correctly, but I'll try. 

Altough you pass your new values via props to the component using initialValues your component values aren't getting updated? I actually had the same problem and thought it was by design. 

I took a look at formiks code and I think what we both need is setting `enableReinitialize` flag to true.

**Comment by stuartmoir1** [comment]
I've created a stripped-down version of my code (that exhibits the same issues): https://codesandbox.io/s/4joz5q1oww. Thanks for the feedback @latviancoder. I played around with enableReinitialize (see below) but this setting did not resolve my problem.

On changing 'Org' or 'Agency' select values, hard-coded state change props (Dropdown.js: 66) are not causing a change in default (selected) value in select menus (1) despite these props being used to set initialValues and (2) regardless of the setting of enableReinitialize.

if enableReinitialize = false, changed state not passed to Select component. Select components defaultValues are values selected in drop-down menus.

if enableReinitialize = true, changed state passed to Select component ON FIRST CHANGE OF SELECT VALUES ONLY. In subsequent changes, behaviour is the same enableReinitialize = false.

Any help you can provide me regarding this issue would be appreciated. Thanks.

**Comment by stuartmoir1** [comment]
I've had a go at working around this issue by using Sematic UI Dropdown rather than HTML select - https://codesandbox.io/s/2o816vy17j. (I also developed the solution somewhat - dropdown options for Agency now change on changing Org). However, I had no success - the same behaviour is evident. Please find my notes below. 

No combination of setting enableReinitialize = true and using setFieldValue to set the value of Agency on changing the value of Org cause the value displayed in Agency to be updated.

Unless, the existing value is not an option of the updated Agency options available on changing the Org (Org: 2 Agency: 2 > Org: 3, Agency: no value, as Agency 2 is not an Option for Org 3). But this is not an appropriate workaround.

Also, setting enableReinitialize = false and commenting out all (Org and Agency) setFieldValue operations (ie setting Select component values by state only) does not resolve the issue.

--
enableReinitialize: false
setFieldValue for Agency on Org change: no
>Agency Select defaultValue not updated on Org change
>Displayed Agency value remains the same (as expected)
--
enableReinitialize: false
setFieldValue for Agency on Org change: yes
>Agency Select defaultValue set to empty string on Org Change
>Displayed Agency value remains the same
--
enableReinitialize: true
setFieldValue for Agency on Org change: no
>Agency Select defaultValue set to empty string on Org Change
>Displayed Agency value remains the same
--
enableReinitialize: true
setFieldValue for Agency on Org change: yes
>Agency Select defaultValue set to empty string on Org Change
>Displayed Agency value remains the same
