### ISSUE TITLE
Expose Formik element's `ref` to `withFormik`

### ISSUE THREAD

**Issue by cloudever** [jaredpalmer/formik#573]
## Bug, Feature, or Question?
Feature

## Current Behavior
`withFormik` does not expose `Formik` element ref to manipulate the form state using HOC

## Desired Behavior
I usually have use the Formik as a HOC for React components - it provides more clean code.
So it might be useful to expose `Formik` component's `ref` out of the `withFormik` HOC to provider access for field manipulation from top components like containers.

## Suggested Solutions
I thought about 2 possible solutions:
1) expose `innerRef` from `Formik` element to top
2) save `ref` of `Formik` element as a class property of `HOC`

## Additional Information
- Formik Version: latest
- React Version: 16.2
- TypeScript Version:
- CodeSandbox Link:
- OS: 
- Node Version:
- Package Manager and Version:

**Comment by prichodko** [comment]
Can you elaborate on the use-case more? It doesn't make much sense to me.

Regarding the implementation, I would go similar way as [React Router](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/withRouter.js#L28)

**Comment by KennySoh** [comment]
i was trying to trigger submit from an external button. 

The typical workaround seems to be either using an external ref. 
https://stackoverflow.com/questions/49525057/react-formik-use-submitform-outside-formik

But HOC withFormik does not expose ref.
