### ISSUE TITLE
Monorepo 

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/formik#574]
- Pull in Formik satellite components 
- Add formik-native
- Add the special new super secret thing 
- Move website directory

**Comment by prichodko** [comment]
Do you need any help with that?

**Comment by jaredpalmer** [comment]
Nah just gotta git it done. This Friday will have the whole day for Formik

**Comment by Andreyco** [comment]
My experience against monorepos is they are hard to use when it comes to forking project, fixing a bug or adding a feature and installing page from forked repository in order to test it... Not sure whether it's possible to install from sub directory. Is it?
