### ISSUE TITLE
Possible Unhandled Promise Rejection while typing in the fields on IE 11

### ISSUE THREAD

**Issue by ankurkaushal360** [jaredpalmer/formik#578]
## Bug, Feature, or Question?
Bug

## Current Behavior
Using `formik` with `yup` & I have been using `es6-promise` for support on IE 11.

While typing in the form fields on IE 11, I am getting warnings like this:

```
Possible Unhandled Promise Rejection: ValidationError: Required field
   "Possible Unhandled Promise Rejection:"
   {
      [functions]: ,
      __proto__: { },
      errors: [ ],
      inner: [ ],
      message: "Required field",
      name: "ValidationError",
      path: "firstName",
      stack: "ValidationError: Required field
   at Anonymous function (http://dev.io:8080/register/bundle.js:2356:24)
   at Anonymous function (https://cdn.jsdelivr.net/npm/promise-polyfill@7/dist/polyfill.min.js:1:577)",
      type: undefined,
      value: undefined
   }
```
When I try to submit the form, it would show validation error even if the fields have been filled in properly.

## Desired Behavior
The form should submit as expected.

## Suggested Solutions

N/A

## Additional Information
N/A

---

- Formik Version: 0.11.11
- React Version: 16.2.0
- TypeScript Version: N/A
- CodeSandbox Link: N/A
- OS: Windows 10 / IE 11
- Node Version: 8.0.0
- Package Manager and Version: NPM (5.8.0)

**Comment by andrewstaker** [comment]
@ankurkaushal360 Did you end up resolving this issue? We are seeing the same thing.

**Comment by erickbelfy** [comment]
@andrewstaker this is an yup issue, it's possibly because your validationSchema contains undefined or null values and we have errors on destructuring undefined or null values on IE 11. I guess in some point of the lib it tries to destructure an undefined value and it breaks.

**Comment by erickbelfy** [comment]
I also found that you need to implement a polyfill for Map() otherwise it will raise an error because IE11 has a partial implementation it and IE dont have support for  values method.

E.g 

```
const map = new Map()
map.values() // isn't work on IE 11
```
