### ISSUE TITLE
handleChangeValue doesn't handle array with object paths

### ISSUE THREAD

**Issue by pauloabmiranda** [jaredpalmer/formik#58]
Hi,
I have a field that is an array of objects that can have many items.
```javascript
facies: Yup.array()
      .required('Please fill the facies modeling table')
      .of(
        Yup.object().shape({
          LowerLimit: Yup.number().required('Please enter a low value.'),
          UpperLimit: Yup.number().required('Please enter a upper value.'),
        })
      ),
```
When i use 
```javascript
// just an example
handleChangeValue('facies[0].LowerLimit', event.currentTarget.value )
```
 to update the LowerLimit of the first item of facies
it creates a new property in values with this name "facies[0][LowerLimit]"
when it should have updated the LowerLimit property of the first element of facies.

I have seen the code of handleChangeValue and this is because
```javascript
handleChangeValue = (field: string, value: any) => {
        const { touched, values } = this.state;
        // Set touched and form fields by name
        this.setState(state => ({
          ...state,
          values: {
            ...values as object,
            [field]: value, // <--- in here
          },
          touched: {
            ...touched as object,
            [field]: true, // <--- in here
          },
        }));
       // Validate against schema
        validateFormData<Values>({ ...values as any, [field]: value /* <-- in here */}, validationSchema).then(
          () => this.setState({ errors: {} }),
          (err: any) => this.setState({ errors: yupToFormErrors(err) })
        );
      };
```
This can be resolve with something similar like the [set method from lodash](https://lodash.com/docs/4.17.4#set) from the FP package

Am i missing some other way to update values from arrays or deep nested object?

Thanks in advance for the help.

**Comment by jaredpalmer** [comment]
Right now you need to merge on your own. `field` does not equal `path` to the value at the moment. 

This is a really really good idea though.

**Comment by pauloabmiranda** [comment]
Thanks for the update.
Should i close or do you want it open?

**Comment by pauloabmiranda** [comment]
I made the merge on my side and then called handleChangeValue with the field and values merged and handleChangeValue updates well the values but the errors not. In the errors gives me
```javascript
errors: {
  "facies[0].LowerLimit": "Error message from lowerlimit",
  ...
}
```
Formik is handling well the values and touched update but not the errors.

Here it goes the code from my merge so you can see it.
`````javascript
const faciesArray = set('facies[0].LowerLimit', event.currentTarget.value, gridInstance.props.values);

    gridInstance.props.handleChangeValue('facies', faciesArray);
´´´´
