### ISSUE TITLE
setFieldValue with Object to set multiple values.

### ISSUE THREAD

**Issue by browniefed** [jaredpalmer/formik#581]
## Bug, Feature, or Question?
It would be great if `setFieldValue` took an object to allow for setting multiple values at the same time.

## Current Behavior

Takes string + value;

## Desired Behavior

```
setFieldValue({
 "path": value,
 "nested.path": value
})
```

**Comment by browniefed** [comment]
Oh `setValues` ha

**Comment by jaredpalmer** [comment]
yeah the mental model is just `setX` and `setFieldX`

**Comment by browniefed** [comment]
AH but `setValues` doesn't merge.

**Comment by jaredpalmer** [comment]
Formik exports `setIn(obj, path, value)` which is what you may want

**Comment by browniefed** [comment]
Just looking to set 3 top level values, so I can spread stuff in just a bit annoying.

Also noticed when calling `setValues` that destroys a value that has been filled in it isn't getting removed.

```
<Field
                name="quantity"
                render={({ field, form }) => {
                  return (
                    <Input
                      disabled={isSubmitting}
                      css={{ textAlign: "right" }}
                      {...field}
                      type="number"
                      pattern="[0-9]"
                      min="1"
                      step="1"
                    />
                  );
                }}
              />
```

Doing a `setValues({ other values except quantity})`, the quantity still has data filled in the field

**Comment by dzg** [comment]
> Formik exports `setIn(obj, path, value)` which is what you may want

Is there doc for this?

How would I set a value for a single property of a single object of an array of objects?

**Comment by Shahriar87** [comment]
A bit late, but I found this works:

```
/*
    formModel = {
        billingAddress: {
            postalCode: '',
            state: '',
            city: '',
            line1: '',
            line2: '',
            contact: {
                firstName: '',
                lastName: '',
                email: '',
            },
        }
    }
*/

address = {
    billingAddress: {
        postalCode: '',
        state: '',
        city: '',
        line1: '',
        line2: '',
        contact: {
            firstName: '',
            lastName: '',
            email: '',
        },
    }
}

setFieldValue('billingAddress', address);   // this works, if I want to change multiple fields with Object
```

**Comment by michaelpward** [comment]
You can also update the values in your `contact` property/fields by using dot notation in the name of the field you pass to `setFieldValue`.

const modifiedContact = {
     firstName: 'Other',
     lastName: 'Name',
     email: 'othername@gmail.com',
};

setFieldValue('billingAddress.contact', modifiedContactObject);

**Comment by amantiwari1** [comment]
hope it helps 
```js
setValues({
     ...formik.values,
     [`is${props.name}Valid`]: e.target.validity.valid,
     [props.name]: e.target.value,
 })
```

**Comment by navinrangar** [comment]
Thankyou so much man. You resolved my big prob! thanks a tonne

**Comment by samboylett** [comment]
I did this, using setIn:

```tsx
<Input
  onChange={(value) => {
    form.setValues(setIn(form.values, field.name, value));
  }}
/>
```
It was the only thing which worked for me, as my field name was already a sub field, e.g. `foo.bar`.

**Comment by rusicsemenov** [comment]
@amantiwari1 will be better to use `prev` state, and you can avoid using formik.values
Will looks as:
```js
setValues((prev)=>{
   ...prev,
   [`is${props.name}Valid`]: e.target.validity.valid,
   [props.name]: e.target.value,
})
```

**Comment by Gilblasse** [comment]
@browniefed  I suppose, for now, we can build our own hooks.

![Capture](https://user-images.githubusercontent.com/12989615/212179636-5c3f7307-226f-4425-bd26-348bd0814ebd.PNG)

`const formik = useFormikContext()`
`const setValue = useSetFormikFieldValue(formik)`
`setValue({
 "path": value,
 "nested.path": value,
 "deeply.nested[0].path": value
})`
or

`setValue("path", value})`

IT works :-)
