### ISSUE TITLE
Featuee Request: <Field/> Component react-native support

### ISSUE THREAD

**Issue by n1ru4l** [jaredpalmer/formik#582]
## Bug, Feature, or Question?

**Feature**

## Current Behavior

It seems like the current `<Field/>` component does not support react-native. I need per field validation for things like checking if a login is available or an email is valid (which both do network requests).

## Desired Behavior

The render prop object also has the properties `setFieldTouched` and `setFieldValue` which trigger the validate function declared on the `<Field />` component.

## Additional Information

---

- Formik Version: **0.11.11**
- React Version: **16.2.0**
- TypeScript Version: -
- CodeSandbox Link: -
- OS: **macOS**
- Node Version: **v8.9.4**
- Package Manager and Version: **yarn@1.5.1**

**Comment by jaredpalmer** [comment]
My plan is to move everything into a monorepo this week and then begin formik native which will contain exactly this component

**Comment by n1ru4l** [comment]
Awesome! Looking forward to migrating my forms to formik. 😇

**Comment by hkung77** [comment]
Is this still a thing? Progress?

**Comment by igimanaloto** [comment]
Hallo! Just checking if there are still plans to support React Native. Thanks!

**Comment by M1chaelChen** [comment]
I'm using `formik": "^2.0.1"` which still doesnt' support the `<Field />` component in React Native.
And then I decide to build my own using the `useField()` and `useFormikContext()` hooks:
```
const FormField = ({ label, component: Field, ...rest }) => {
  const [field, meta] = useField(rest);
  const { handleChange, handleBlur, setFieldTouched } = useFormikContext();

  const fieldName = field.name;

  return (
    <Container>
      {label && <Title>{label}</Title>}
      <Field
        {...field}
        {...rest}
        onChange={handleChange(fieldName)}
        onBlur={handleBlur(fieldName)}
        onTouch={() => setFieldTouched(fieldName)}
      />
      {meta.touched && meta.error ? <Text>{meta.error}</Text> : null}
    </Container>
  );
};

FormField.propTypes = {
  label: string.isRequired,
  component: oneOfType([node, elementType])
};

FormField.defaultProps = {
  component: Input
};
```
And then you can use it just like the `<Field />` component:
 ` <FormField label="Email" name="email" />`

It might not be perfect but works pretty well for me so far.
