### ISSUE TITLE
Values on prop approach are persistent

### ISSUE THREAD

**Issue by ivanasetiawan** [jaredpalmer/formik#586]
## Bug, Feature, or Question?
Question

## Current Behavior
When I open an overview page and switch back to `Create form`, the values on the form are prefilled with whatever the previous values were.

## Desired Behavior
Always reset when I go to `Create form`

## Suggested Solutions

`resetForm` on formik init? it works when I attach `resetForm` on a button inside render (which I can manually reset the form) but it'd be great if this can be done before render (which I don't know how to call because `resetForm` exists on render, not before)

## Additional Information

---

- Formik Version: 0.10.5
- React Version:15.5.4

**Comment by ivanasetiawan** [comment]
I also tried `enableReinitialize` with no success. :'(

**Comment by ivanasetiawan** [comment]
Solved with React approach!

**Comment by emilenriquez** [comment]
what do you mean by react approach @ivanasetiawan

**Comment by ivanasetiawan** [comment]
@emilenriquez By using `componentWillReceiveProps`. Something like:    
    
    componentWillReceiveProps(nextProps) {
        if (nextProps.users !== this.initialValues) {
            this.initialValues = nextProps.users
        }
      }
