### ISSUE TITLE
How to make touched object updated after submit?

### ISSUE THREAD

**Issue by aisensiy** [jaredpalmer/formik#587]
## Bug, Feature, or Question?

Question

## Current Behavior

Submit form without touch any field do not show the error messages in every field. An example shows [here](https://codesandbox.io/s/6y491r19qz).

## Desired Behavior

Should show error messages in every field.

## Additional Information

---

- Formik Version: 0.11.11
- React Version: 16.3.2
- TypeScript Version: not typescript
- CodeSandbox Link: https://codesandbox.io/s/6y491r19qz
- OS: Mac OS
- Node Version: v7.10.0
- Package Manager and Version: npm 5.8.0

**Comment by aisensiy** [comment]
Because of typo...

**Comment by kafein** [comment]
Hi @aisensiy. I have a similar problem. Can't distinguish your typo from the code you supplied. Where is the typo?

**Comment by jssisodiyaPG** [comment]
@aisensiy Facing the same issue. Did you figure out the problem ? I have proper `initialValues` passed to `Formik` component

**Comment by aisensiy** [comment]
@jssisodiyaPG @kafein I had wrong init values typo.
