### ISSUE TITLE
[TS types] The absent of 'prop-types' and an issue with using with `styled-components`

### ISSUE THREAD

**Issue by osenvosem** [jaredpalmer/formik#596]
If TS types depend on `prop-types` definitions, I suppose they should be installed automatically.

![screen shot 2018-04-23 at 09 43 17](https://user-images.githubusercontent.com/6762673/39110718-de74775c-46da-11e8-83cf-c9cefa7b9c3e.jpg)
___

I'm having an error trying to style the `Field` component with `styled-components`. Not sure on which side the problem is.

```ts
export const StyledField = styled(Field)`
/* styles */
`;
```

![screen shot 2018-04-23 at 09 48 55](https://user-images.githubusercontent.com/6762673/39110935-ba945932-46db-11e8-8678-a797a668f33e.jpg)

**Comment by yanchith** [comment]
I second the "prop-types" issue.

By default, shouldn't all type declarations for your dependencies be in "dependencies" section, not "devDependencies"?

**Comment by jaredpalmer** [comment]
1.0.0 beta no longer requires prop-types!
