### ISSUE TITLE
mapPropsToValues does not update values on propUpdate

### ISSUE THREAD

**Issue by benoj** [jaredpalmer/formik#600]
When I update a prop value after the form has been rendered already (e.g. someone updates a field value server side) then the value is not synced into the values - is this correct behaviour if so how do you suggest I achieve the desired functionality?

Cheers,

Ben

**Comment by latviancoder** [comment]
Have you tried `enableReinitialize`?

https://github.com/jaredpalmer/formik#enablereinitialize-boolean

**Comment by kylemellander** [comment]
I know this is closed, but `enableReinitialize` actually will reset ALL form values, which would require the context of the form to manage ALL the form fields that are initialized or none.  is there any option to only reinitialize one value?

**Comment by DmitryGG** [comment]
@latviancoder hallelujah

**Comment by Skillvendor** [comment]
I agree with @kylemellander . enableReinitialize makes you lose all your touched inputs. This is horrible.

**Comment by billel-boudchicha** [comment]
hey guys iam facing the same problem here . any update on this, enableReinitialize will reset all values

**Comment by simplypixi** [comment]
I have same issue ;) Any ideas?

**Comment by iamtchelo** [comment]
Have any prop that don't allows reset all values ​​when I using `enableReinitialize`?

**Comment by iamtchelo** [comment]
Have any prop that don't allows reset all values ​​when I use `enableReinitialize`?

**Comment by stormmuller** [comment]
> Have you tried `enableReinitialize`?
> 
> https://github.com/jaredpalmer/formik#enablereinitialize-boolean

Link is broken

**Comment by stormmuller** [comment]
Here's a working one: https://jaredpalmer.com/formik/docs/api/withformik#enablereinitialize-boolean

Still this doesn't actually solve the issue

**Comment by mtusk** [comment]
Above URL still didn't work for me... must be case-sensitive. This works for me: https://jaredpalmer.com/formik/docs/api/withFormik#enablereinitialize-boolean
