### ISSUE TITLE
Trim not working

### ISSUE THREAD

**Issue by sketchbuch** [jaredpalmer/formik#601]
As a follow on to https://github.com/jaredpalmer/formik/issues/473

Well here is an example:

https://codesandbox.io/s/2jo7vox1n0

I have strict set to false. The validation for firstname detects whitespace and show a message but I don't want that, I want it to just trim the string and not show any message.

**Comment by Jaikant** [comment]
It seems a few folks are facing this issue, including me.

**Comment by vleandersson** [comment]
The reason for this is that Formik will not use the transformed values from the validation, but rather the original ones. So, using any transform methods from Yup with Formik will not have any implications on the final submit body. You will need to manually handle this. One example of such an implementation can be found on https://github.com/jaredpalmer/formik/issues/473 

```
<Field
  name="name"
  render={({ field, form: { isSubmitting, handleBlur } }) => (
    <div className="field-section">
      <Label htmlFor="name">Name</Label>
      <input
        {...field}
        onBlur={(e) => {
          const val = (e.target.value || '').replace(/\s+/gi, ' ');
          setFieldValue(field.name, val.trim());
          handleBlur(e);
        }}
        id="name"
        disabled={isSubmitting}
        type="text"
        placeholder="Your name"
      />
      <ErrorMessage name="name" component={ValidationError} />
    </div>
  )}
/>
```

**Comment by johnrom** [comment]
Also, check out [format and parse](#2255).

**Comment by vleandersson** [comment]
Amazing update @johnrom 

Until that is in, I've created a small set of helpers to solve this issue outside of Yup and Formik: https://www.npmjs.com/package/formik-yup

**Comment by aj07mm** [comment]
Here: https://github.com/jaredpalmer/formik/issues/473#issuecomment-593587854

**Comment by wayneparkes** [comment]
@vleandersson, your answer got me closer to a solution but I found that the field validator was validating against the original input value - not the trimmed value.

What I discovered, is that you need to invoke `handleBlur(event)` before carrying out any modifications to the input value, otherwise Formik will disregard any value set via `setFieldValue` and use the original event value if `handleBlur(event)` is called after.

Example:
```
<input
  {...field}
  onBlur={(event) => {
    handleBlur(event);
    const trimmedValue = (event.target.value || '').replace(/\s+/g, '');
    setFieldValue(field.name, trimmedValue);
  }}
  id="name"
  disabled={isSubmitting}
  type="text"
  placeholder="Your name"
/>
```
