### ISSUE TITLE
Field validate prop doesn't set error

### ISSUE THREAD

**Issue by DenisFrezzato** [jaredpalmer/formik#604]
## Bug, Feature, or Question?
Bug

## Current Behavior
The `validate` prop of `<Field />` doesn't set the error to the Formik state. Furthermore, I can succesfully submit the form with invalid value.

## Desired Behavior
The Formik state should have the validation error (as with `validationSchema`) and the submission should be prevented when the value is invalid (as with `validationSchema`)

---
- Formik Version: 0.11.11
- React Version: 16.3.2
- CodeSandbox Link: https://codesandbox.io/s/l9kz659j29

**Comment by andrii-motsyk** [comment]
@DenisFrezzato, I have a temporary workaround

```lang=ts
validateForm = values => { // form level validation function
  const errors = {};

  // field level validation functions
  errors['pointsCost'] = this.validatePrice(values.pointsCost); 
  errors['title'] = this.validateTitle(values.title);

  return errors;
};
```

**Comment by andrii-motsyk** [comment]
@jaredpalmer, will there be some changes regarding this issue?

**Comment by Andreyco** [comment]
Fixed in beta 5
