### ISSUE TITLE
FieldArray's push/remove trigger form validation

### ISSUE THREAD

**Issue by gwendall** [jaredpalmer/formik#613]
`FieldArray` components trigger a schema validation when the `push` or `remove` methods are called, even though the parent `Formik` component has the `validateOnChange` prop to `false`. You have to manually set the `validateOnChange` prop to `false` on the `FieldArray` component so that the validation does not happen. It is not the case for `Field` components - you just have to set the prop on the parent `Formik` component. It would be worth clarifying this out.
Amazing package anyways !

**Comment by jketcham** [comment]
I just ran into this as well and thought it was very intuitive. Would be nice if either the docs were updated or this was fixed.

**Comment by firattale** [comment]
@gwendall you saved my hours, thanks :)
