### ISSUE TITLE
isValid is true even though all inputs are not valid

### ISSUE THREAD

**Issue by eahlberg** [jaredpalmer/formik#614]
**Describe the bug**
`isValid` is `true` even though all inputs are not valid

**To Reproduce**
1. Visit the code sandbox below
2. Open the development console
3. Fill in one of the fields with a valid value

**Expected behavior**
`isValid` to be `false` since all inputs are not valid

- Formik Version: 0.11.11
- React Version: 16.3.2
- TypeScript Version: -
- CodeSandbox Link: https://codesandbox.io/s/41xxv9529
- OS: macOS High Sierra
- Node Version: -
- Package Manager and Version: -

**Comment by jaredpalmer** [comment]
Upgrade to 1.0.0 alpha

**Comment by eahlberg** [comment]
🙇‍♂️

**Comment by devdpontes** [comment]
This is still a problem on v1.4.2.

**Comment by luskin** [comment]
We are still encountering this issue on `1.5.1`, any update?

**Comment by jaredpalmer** [comment]
This is fixed in v2 alpha
