### ISSUE TITLE
Form is not valid when validators pass but whole form is not dirty

### ISSUE THREAD

**Issue by krzkaczor** [jaredpalmer/formik#621]
**Describe the bug**
When the user edits text field we keep it "untouched" to hide validation errors until user unfocuses given input field (and thus marks given field as touched). The form is marked as invalid when it's not dirty. 

This prevents from submitting a form with one field without unfocusing it first. 

**To Reproduce**

I tweaked one of the formik's examples to ilustrate this behavior:
https://codesandbox.io/s/mylpzoqmp

1. Insert valid email
2. Submit button is still disabled b/c whole form is invalid

**Expected behavior**
The form should be marked as valid when all validators pass.

**Suggested solution(s)**
Ugly workaround is to check directly errors object instead of relying on isValid. I think proper solution would be to separate `isValid` and `dirty` values.

**Additional context**

---

- Formik Version: 0.9.0
- React Version: 15.5
- CodeSandbox Link: https://codesandbox.io/s/mylpzoqmp

**Comment by noinkling** [comment]
This is fixed in the more recent versions.
