### ISSUE TITLE
ArrayHelpers Remove Throws Type Error

### ISSUE THREAD

**Issue by eferrervaughn** [jaredpalmer/formik#623]
**Describe the bug**

Using the arrayHelpers.remove method and when I call it it says there is a TypeError. This was working for me earlier and now its not. (Same Day)

**To Reproduce**

I'm using the same code as the example.

              />
              {values.friends && values.friends.length > 0 ? (
                values.friends.map((friend, index) => (
                  <div>
                    <MySelect
                      name={`friends.${index}.type`}
                      value={`friends.${index}.type`}
                      onChange={setFieldValue}
                      current={{ curVal: values.friends, index }}
                      options={[
                        { value: "single_text", label: "Single Line Text" },
                        { value: "multi_select", label: "Multi Select" }
                      ]}
                      onBlur={setFieldTouched}
                    />

                    {values.friends[index] && (
                      <Field
                        name={`friends.${index}.name`}
                        onBlur={null}
                        type="text"
                        placeholder="Enter in Question Text"
                      />
                    )}

                    <button
                      type="button"
                      onClick={() => arrayHelpers.remove(index)} // remove a friend from the list
                    >
                      -
                    </button>
                    <button
                      type="button"
                      onClick={() => {
                        let nextIndex = index + 1;
                        arrayHelpers.insert(nextIndex, "");
                      }} // insert an empty string at a position
                    >
                      +
                    </button>
**Expected behavior**

**Suggested solution(s)**

**Additional context**

formik.es6.js:5836 Uncaught TypeError: array.slice is not a function
    at formik.es6.js:5836
    at Formik.<anonymous> (formik.es6.js:5802)
    at getStateFromUpdate (react-dom.development.js:6400)
    at processUpdateQueue (react-dom.development.js:6489)
    at updateClassInstance (react-dom.development.js:7143)
    at updateClassComponent (react-dom.development.js:8345)
    at beginWork (react-dom.development.js:8982)
    at performUnitOfWork (react-dom.development.js:11814)
    at workLoop (react-dom.development.js:11843)
    at renderRoot (react-dom.development.js:11874)
    at performWorkOnRoot (react-dom.development.js:12449)
    at performWork (react-dom.development.js:12370)
    at performSyncWork (react-dom.development.js:12347)
    at interactiveUpdates (react-dom.development.js:12597)
    at interactiveUpdates (react-dom.development.js:1958)
    at dispatchInteractiveEvent (react-dom.development.js:4259)

index.js:2178 The above error occurred in the <Formik> component:
    in Formik (at Dynamic.js:40)
    in div (at Dynamic.js:38)
    in FriendList (at App.js:23)
    in div (created by Row)
    in Row (at App.js:22)
    in div (created by Grid)
    in Grid (at App.js:15)
    in App (at index.js:7)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
---

- Formik Version: 0.11.11
- React Version: 16.3.2
- TypeScript Version:
- CodeSandbox Link:
- OS: Mac OSX
- Node Version: 8.12
- Package Manager and Version:

**Comment by L42y** [comment]
The same error occurred to me

**Comment by elderph** [comment]
Me too

**Comment by ForumT** [comment]
Ok i found out i was doing a very stupid mistake which was causing this error. sharing it as it might help others.

My fieldArray is like so:
 ```
<FieldArray
        name="attendee_types"
        label="Attendee Types"
        render={(props) => (
          <Fields
            name="attendee_types"
            label="Attendee Types"
            {...props}
            inLine
            required
          />
        )}
      />
```
and my validation function was:
```
errors.attendee_types = [];
    values.attendee_types.forEach((attendeeType, i) => {
      if (!attendeeType) {
        errors.attendee_types[i] = "attendee type can't be blank";
      }
    });
    if (!Object.keys(errors.attendee_types).length) {
      delete errors.attendee_types;
    }
```

Here I had written errors.attendee_types = {}.
So while debugging the remove function of formik, i found, it had taken errors.attendee_types also and since it was not an array, array.splice was giving errors. I changed it to array and my code works fine now.

**Comment by finneganh** [comment]
If anyone else comes across this, my problem was with using `handleBlur` in my `FieldArray`-controlled checkboxes.

**Comment by andrewbruno** [comment]
Thanks Fin!  I also had the same issue with onBlur

**Comment by charlax** [comment]
Another reason why this may happen: #1158 (non-array errors).
