### ISSUE TITLE
Is it possible to have non-field errors?

### ISSUE THREAD

**Issue by jmtoung** [jaredpalmer/formik#633]
**Is your feature request related to a problem? Please describe.**
My server returns errors that are not related to a particular field under the key '_error'. Currently when I try to set errors on formik, the errors are ignored because they do not match any keys in my values.

**Describe the solution you'd like**
I'd like for there to be the possibility of non-field errors stored in some sort of user specified key.

**Describe alternatives you've considered**
Alternatives would be...storing this in a values field, but that's hacky.

**Additional context**

**Comment by AaronW9090** [comment]
This is the kind of thing that status was meant to be used for.

When you get an error back from your server save it using `setStatus(yourError)` and access it from the status prop.

**Comment by rafalolszewski94** [comment]
> This is the kind of thing that status was meant to be used for.
> 
> When you get an error back from your server save it using `setStatus(yourError)` and access it from the status prop.

As an addition (because this helped me):
Use as mentioned:

```js
props.setStatus('Your error string')
```

But also access it in your template via `props.status` or if you prefer object destructuring:

```js
const { status } = props
console.log(status) // 'Your error string'
```

**Comment by tkrugg** [comment]
@jmtoung sounds like you're using Django :)
What I do is usually just add a field called `non_field_errors` to my initial Values.
Roughly 
```ts
const formik = useFormik<{
  email: string;
  password: string;
  non_field_errors?: string;
}}>({
   ...
   onSubmit: async (value, { setErrors }) => {
       try {
             ...
       } catch (errors) {
             setErrors(errors); // this more simple, especially if you're using TS
       }
   }
});
```
