### ISSUE TITLE
Beta: Erroneous warning about button having unspecified type when it is set to type="submit"

### ISSUE THREAD

**Issue by dylanmoz** [jaredpalmer/formik#635]
**Describe the bug**
When the active element is not a button in `<Formik />`'s handleSubmit, a warning is printed out in development saying:

```
Warning: You submitted a Formik form using a button with an unspecified type.  Most browsers default button elements to type="submit". If this is not a submit button please add type="button".
```

https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L274

**To Reproduce**
Submit a form without a button

**Expected behavior**
Warning should not be printed if document.activeElement is not an instance of HTMLButtonElement

**Suggested solution(s)**
In the code block linked above, check if document.activeElement is not a HTMLButtonElement, and if so, don't enter that if statement

**Additional context**
This is occurring when I am trying to run my tests on forms using jest and `react-testing-library`. Although I use a button in my forms with `type="submit"`, it looks like when I fire the event via `element.dispatchEvent()`, the `document.activeElement` is not set to the button, which causes the error to be printed.

---

- Formik Version: v1.0.0-beta.1
- React Version: 16.2
- TypeScript Version: N/A
- CodeSandbox Link:
- OS: 
- Node Version:
- Package Manager and Version:

**Comment by jaredpalmer** [comment]
Can you submit a PR?

**Comment by jaredpalmer** [comment]
cc @nathanforce

**Comment by nathanforce** [comment]
I'll check on this tomorrow morning.  My initial thoughts are 

1.  Yes, the check should be more explicit
2.  I wonder why `document.activeElement` is behaving this way in your test. I wonder if it could be some quirk of JSDom or something along those lines.

Anyhow, the check should be more explicit, so let's update that.

**Comment by lookfirst** [comment]
![image](https://user-images.githubusercontent.com/85355/40035121-67d0920a-582a-11e8-9c70-cc3152e1b1d8.png)
