### ISSUE TITLE
Support render prop rather than child function on new FormikConsumer

### ISSUE THREAD

**Issue by ericbiewener** [jaredpalmer/formik#636]
I generally go with `render` props rather than `child-as-function`, and Formik supports that on `Form`, `Field`, etc. Can we add this to the new `FormikConsumer` component?

**Comment by jaredpalmer** [comment]
FormikConsumer is just  the consumer from `const { Consumer } = React.createContext(...)`

**Comment by ericbiewener** [comment]
Ah, gotcha. Ignore me!
