### ISSUE TITLE
Formik + Material-UI <Select> do not play nice

### ISSUE THREAD

**Issue by cvburgess** [jaredpalmer/formik#640]
**Describe the bug**

When using formik with Material UI, the Select component doesnt update Formik like a native select should. That being said, the MUI folks said that final-form, redux-form, and other form libs don't seem to have the same issue.

**To Reproduce**

Create a small form with https://github.com/mui-org and formik. Watch the console explode.

**Expected behavior**

Seems like it should accept the values even if they aren't coming from a native select.

**Suggested solution(s)**

**Additional context**

See https://github.com/mui-org/material-ui/issues/10938

---

- Formik Version: 0.11.0
- React Version: 16.2.0
- TypeScript Version:
- CodeSandbox Link:
- OS: 
- Node Version:
- Package Manager and Version:

**Comment by cvburgess** [comment]
This workaround (from the linked issue) does fix the problem:

```jsx
<Select
    name="customerId"
    onBlur={event => {
        event.target.name = 'customerId';
        handleBlur(event);
    }}
/>
```

**Comment by jaredpalmer** [comment]
if you bump to the beta, you can do `onBlur={handleBlur('customerId')}` and get a curried version of handleBlur back. Same for handleChange.

**Comment by cvburgess** [comment]
thank you very much!

**Comment by renannobile** [comment]
How would this work with `<Field component={CustomSelect} />`?

**Comment by pljeskavica** [comment]
> if you bump to the beta, you can do `onBlur={handleBlur('customerId')}` and get a curried version of handleBlur back. Same for handleChange.

This needs better visibility in the docs.

**Comment by rodrigograca31** [comment]
For me changing from `onChange={handleChange()}` to `onChange={handleChange("image")}` on my `<Select>` fixed it

**Comment by AshishKapoor** [comment]
> For me changing from `onChange={handleChange()}` to `onChange={handleChange("field_name")}` on my `<Select>` fixed it

Worked thanks!

**Comment by michaelpward** [comment]
Very long but very helpful video on Formik + Material-UI (textfields and selects).
https://www.youtube.com/watch?v=ziWJ4k_3BLk

**Comment by codewithnazim** [comment]
> For me changing from `onChange={handleChange()}` to `onChange={handleChange("field_name")}` on my `<Select>` fixed it

man you save me..
thanks
