### ISSUE TITLE
context.formik is undefined

### ISSUE THREAD

**Issue by cvburgess** [jaredpalmer/formik#641]
**Describe the bug**

Upgraded to 1.0.0 beta 1 and noticing that for children of Formik and Form, context has a formik prop, but the value is undefined.

**To Reproduce**

**Expected behavior**

The below snippet works in 0.11.0 but not in 1.0.0 beta 1:

```
import React from "react";
import PropTypes from "prop-types";
import { Button } from "material-ui";

const SaveButton = (
  { label, validationSchema, ...props },
  { formik: { values, isSubmitting } }
) => {
  const disabled = isSubmitting || !validationSchema.isValidSync(values);
  return (
    <Button
      variant="raised"
      color="primary"
      type="submit"
      disabled={disabled}
      {...props}
    >
      {label}
    </Button>
  );
};

SaveButton.propTypes = {
  label: PropTypes.string.isRequired,
  validationSchema: PropTypes.object.isRequired // eslint-disable-line react/forbid-prop-types
};

SaveButton.contextTypes = {
  formik: PropTypes.object
};

export default SaveButton;
```

**Suggested solution(s)**

**Additional context**

---

- Formik Version: 1.0.0-beta.1
- React Version: 16.2.0
- TypeScript Version:
- CodeSandbox Link:
- OS: 
- Node Version:
- Package Manager and Version:

**Comment by jaredpalmer** [comment]
This shouuld have been polyfilled with create-react-context.

**Comment by cvburgess** [comment]
it doesnt seem to be so? i got all the deps according to npm but no dice :/

**Comment by pgrekovich** [comment]
I have the same problem, but i'm didn't update any packages :)
@jaredpalmer can you show example with `create-react-context`?

**Comment by ZwaarContrast** [comment]
Having the same issue when upgrading from 1.0.0-alpha.4 to 1.0.0-beta.2. 

Will be rolling back for now.

**Comment by jake-nz** [comment]
**Solved:** You should now use [`connect`](https://jaredpalmer.com/formik/docs/api/connect) instead of `contextTypes = { formik: PropTypes.object }`
