### ISSUE TITLE
Why do you collect code in a single bundle?

### ISSUE THREAD

**Issue by retyui** [jaredpalmer/formik#643]
**Is your feature request related to a problem? Please describe.**
I try reduce my bundels size. In my project I use one import:
```js
import { withFormik } from 'formik';
```
I would like to have the opportunity to do so:
```js
import withFormik from 'formik/withFormik';
```

**Describe the solution you'd like**
Why do you collect code in a single js bundle?
Use flatten struct!
Like as: `lodash-es`, `date-fns`, `react-router`, `ramda`, `recompose`

**Comment by retyui** [comment]
@jaredpalmer  do you mean `cp package.json dist/package.json && cd dist && npm run build`

**Comment by jaredpalmer** [comment]
Correct
