### ISSUE TITLE
Having onChange prop on FastField forces unnecessary updates

### ISSUE THREAD

**Issue by ernestopye** [jaredpalmer/formik#649]
**Describe the bug**
After adding an onChange prop on a FastField, the field seems to have lost its performance benefits. onChange is called on every keystroke, updating the form state right away and forcing all form fields to update.

**To Reproduce**
Open the code sandbox below.
[Code Sandbox](https://codesandbox.io/s/03vqq75xnw)

Type anything into the "name" text box. Note that the state of the form updates as you type. Not sure if this is intended?

**Expected behavior**
onChange is only called when the field value changes within form state, meaning on blur. Or perhaps this is called in real-time, but it shouldn't cause all other fields to update along with it.

**Suggested solution(s)**
Unsure what the solution is. Not that familiar with the source yet. I mentioned in a different thread that another option that would be nice to have is to have the ability to debounce/throttle the input, so that users don't have to wait until blur to see the form re-render.

**Additional context**
See my related issue: #648 Since this is doing changes on blur, I'm not sure onChange being called at all here makes sense. I may be oversimplifying this as I'm not that familiar with Formik's design. I feel like these are separate issues. Apologies if you'd rather have them together.

---
Formik Version: 1.0.0-beta2
React Version: 15.6.1 & 16.3.0
TypeScript Version: N/A
CodeSandbox Link: https://codesandbox.io/s/03vqq75xnw
OS: Windows
Node Version: 6.8.1 on my PC, but happens on the codesandbox sample linked.
Package Manager and Version: npm@5.8.0

**Comment by AaronW9090** [comment]
Using formiks `handleChange` function on a FastField will update the values object for the whole form, it's what is passed to `<Field />` by default.

To get custom onChange behaviour you can pass a custom input component to the `component` prop which will then receive the field information (including it's field specific onChange and onBlur functions) as a prop, or you can use the render prop to create your custom input which will then receive the field information as a parameter of that function.

**Comment by romainquellec** [comment]
can we get an example of that please ? Thanks.

**Comment by aaronnuu** [comment]
Sure

```js
const CustomInput = ({ handleChange, field }) => {
  <input
    value={field.value}
    onChange={(e) => {
      field.onChange(e);
      handleChange(e);
    }}
    onBlur={(e) => {
      field.onBlur(e);
    }}
  />
}

<FastField
  name='my_field'
  handleChange={(e) => { /* custom handle change */ }}
  component={CustomInput}
/>
```

I've modified the code sandbox to demonstrate the behaviour here https://codesandbox.io/s/r1w0xq5v6m

**Comment by jaredpalmer** [comment]
Neither FastField nor Field accept an `onChange` prop? Im confused here.

**Comment by aaronnuu** [comment]
Yes they do, only implicitly

```js
// From FastField

render() => {
  const {
    validate,
    name,
    render,
    children,
    component = 'input',
    formik,
    ...props // Could have onChange
  } = (this.props as FieldAttributes<Props> & {
    formik: FormikContext<Values>;
  }) as any;
  const {
    validate: _validate,
    validationSchema: _validationSchema,
    ...restOfFormik
  } = formik;
  const field = {
    value:
      props.type === 'radio' || props.type === 'checkbox'
        ? props.value // React uses checked={} for these inputs
        : getIn(formik.values, name),
    name,
    onChange: validate ? this.handleChange : formik.handleChange,
    onBlur: validate ? this.handleBlur : formik.handleBlur,
  };
  const bag = { field, form: restOfFormik };

  if (render) {
    return (render as any)(bag);
  }

  if (isFunction(children)) {
    return (children as (props: FieldProps<any>) => React.ReactNode)(bag);
  }

  if (typeof component === 'string') {
    const { innerRef, ...rest } = props;
    return React.createElement(component as any, {
      ref: innerRef,
      ...field,
      ...rest, // Spread onto the given 'string component' ('input' by default)
      children,
    });
  }

  return React.createElement(component as any, {
    ...bag,
    ...props, // Same here but for given react nodes ( etc. <input />)
    children,
});
```

**Comment by jaredpalmer** [comment]
These are not intended to be overridden in this manner.

**Comment by aaronnuu** [comment]
Yeah, I imagine my solution is the intended way to get custom onChange behaviour for whatever input?

What I do is create a custom wrapper for the `<Field />` component that takes that onChange and uses it in the pattern I described, however I think it's probably a common enough thing that it could be written into formik.

Keeping the onChange passed to the underlying input is a bit of a gotcha when using string components though. For all other instances you have to define the onChange onto the input yourself in some way. Maybe just swap the order that field and rest is spread?

```js
if (typeof component === 'string') {
    const { innerRef, ...rest } = props;
    return React.createElement(component as any, {
      ref: innerRef,
      ...field, // Swap
      ...rest, // these
      children,
    });
  }
```

**Comment by jaredpalmer** [comment]
Again, you’re not supposed to do this the way you’re doing it. It may work, but it may not in the future. If you want custom onChange behavior I suggest wrapping using a custom class component with Field

**Comment by yourfavorite** [comment]
I stumbled onto this thread as I'm doing something similar to @aaronnuu. Is there an example of using a custom class component with FastField in order to get the custom onChange behavior?

**Comment by jaredpalmer** [comment]
You can accomplish this the same way you would with a Field. 

I am closing this thread as the initial premise/technique is not intended. That inline function onChange will break shallow comparison thus forcing FastField  to rerender every time. You must use the FastField’s component or render props and then wire up your input accordingly.
