### ISSUE TITLE
Conditional Validation

### ISSUE THREAD

**Issue by zebulonj** [jaredpalmer/formik#652]
**Is your feature request related to a problem? Please describe.**
I've recently had need to support multiple actions on a form (specifically, "Submit" and "Save draft"), where each action had different validation requirements (you don't want to enforce required fields when saving as draft, but you may have need for validation to prevent field value lengths exceeding database limits). However, Formik doesn't even execute onSubmit unless validation passes.

**Describe the solution you'd like**
I'd like Formik to always execute the `onSubmit` handler when `handleSubmit()` or `submitForm()` are called... passing `errors` and `isValid` to the `onSubmit` handler and leaving it to the user what action to take. Recognizing that this would be a breaking change, I think it would be acceptable to add an option to enable this behavior (off be default).

**Describe alternatives you've considered**
Handling validation outside of Formik. 👎

**Additional context**
I've forked Formik and implemented this [here](https://github.com/zebulonj/formik/commit/82d8ce3596685077093deec3df766771fcb714f4). Related: in the linked fork I also added the [ability to pass flags](https://github.com/zebulonj/formik/commit/addfbab418ae5265db69cc96394e9c4724d24b66) to `onSubmit` via the `submitForm()` method.

**Comment by azangru** [comment]
I am struggling with a similar requirement at the moment and would love something like this very much! For submitting and saving as a draft, I decided to use a hidden input field that would be checked when clicking on the Submit button (as opposed to Save as draft) so that I could run different sets of custom validations depending on whether this field is checked or not.

I also have custom fields that consist of several inputs (e.g. a select box coupled with a text input), which will inevitably be in an invalid state while filling in the form (when one part of the field will be set while another part won't yet be touched), so it's probably a good idea to show errors for these fields right at submission, but the onSubmit handler won't execute if I validate these fields while the user fills in the form.

**Comment by zebulonj** [comment]
I attempted something similar (tried with both a hidden value and using the Formik `status`), but encountered a concurrency issue because both `setFieldValue` and `setStatus` return synchronously after making an asynchronous call to React’s `setState`. The consequence was that sometimes my status or value was not reflected in the subsequent execution of the `onSubmit` handler.

**Comment by azangru** [comment]
> but encountered a concurrency issue because both setFieldValue and setStatus return synchronously after making an asynchronous call to React’s setState.

Yep, this is exactly where I am at, concurrency issues :-) Although when I put `setFieldValue` in a `Promise.resolve`, and call `submitForm` inside the `then` clause, the value seems to be consistently set before the `onSubmit` handler is called. Perhaps making `validate` into an asynchronous function will also help also with concurrency. Don't know if this is going to bite me or not; it certainly looks fragile.

**Comment by latviancoder** [comment]
I have similar requirement in my app and ended up doing the same thing @azangru is describing - setting custom flag inside of `values` object and submitting the form afterwards, with custom `validate` function. And because `setFieldValue` is async and doesnt return a promise I used setTimeout hack.

**Comment by zebulonj** [comment]
To add some color to this... I ultimately forked (and abandoned approaches that involved setting a flag inside `values` or use of `status`) because I needed the validation to be run before the user attempted to "submit" or "save draft" so they would have immediate feedback. I implemented a validation function that ran all validations, but included metadata with the error messages to indicate the context in which it applied.

For example, if a field would be required for submission, but when saved as draft all you need to ensure is that it doesn't exceed the database column length, you might see an entry on `errors` that looked like this (where `subject` is the hypothetical field):

```js
{
  subject: [
    { message: "Value cannot exceed 255 characters.", context: ['draft', 'final'] },
    { message: "A value is required.", context: ['final'] }
  ]
}
```

The `onSubmit` handler could then decide which errors to ignore, depending on the calling context. It also meant that I had a lot of flexibility about how I displayed real-time validation cues to the user.

**Comment by wellyal** [comment]
@zebulonj PR?

**Comment by juliosampaio** [comment]
I think that is a good solution to corner cases where you want to show errors in a different fashion as with toasters notifications. @zebulonj why not open a PR?

**Comment by zebulonj** [comment]
Happy to open a PR. Just want some validation that maintainers are open to the change/feature before investing the time.

**Comment by Andreyco** [comment]
You can track "action" of button you press and pick validation rules base on the button. See this [codesanbox](https://codesandbox.io/s/1rxpp4k57l)

**Comment by rgallison** [comment]
Proposed solution doesn't really work in my case as I am using functional components and state apparently isn't updated in time
