### ISSUE TITLE
How to handle arrays in initialValues?

### ISSUE THREAD

**Issue by Mario-Eis** [jaredpalmer/formik#655]
```
initialValues={[
{
    "name": "superman",
    "realName": "clark"
},{
    "name": "batman",
    "realName": "bruce"
}]}
```
This will work for the initial render, but throws an error as soon as the value is changed:
`<Field name={[1].name}/>`
The reason is, that somehow `values` is transformed to 
```
{
"1": {
    "name": "superman",
    "realName": "clark"
}, ...
}
```

Is there something like `<Field name={$.[1].name}/>`?

**Comment by idesignpixels** [comment]
HI, could you explain the context of what your trying to do? is this a fieldArray?
could you do...
```
initialValues={
superHeros: [
  {
      "name": "superman",
      "realName": "clark"
  },
  {
      "name": "batman",
      "realName": "bruce"
  }
]
}
```

**Comment by aliscoder** [comment]
x
