### ISSUE TITLE
getFieldValue and related handlers

### ISSUE THREAD

**Issue by luminous3** [jaredpalmer/formik#657]
Just like we have `setFieldValue` for setting a field value, a reciprocal function, like `getFieldValue` should exist as well. There's been a number of cases where I've wanted to check the value for a certain field somewhere else in the form, and there's no way to do that in formik currently.

**Comment by latviancoder** [comment]
What about using `values` object directly? It contains all the form values.

**Comment by trungtin** [comment]
I think the point of `getFieldValue` is when we have a deep nested field (with array). I can use `get` from 'lodash' in a similar way though, but I think formik should provide that.

**Comment by kevinmiguet** [comment]
+ 1 on this. I had to rewrite a get function and felt formik should provide it

export function getObjectValue(obj, path) {
	var fullPath = path
		.replace(/\[/g, '.')
		.replace(/]/g, '')
		.split('.')
		.filter(Boolean);

	return fullPath.every(everyFunc) ? obj : null;

	function everyFunc(step) {
		return !(step && (obj = obj[step]) === undefined);
	}
}

**Comment by yossicahen** [comment]
+1

**Comment by richmeij** [comment]
I think I might have a usecase where I need to check a valueof a field inside a useEffect, but dont want to pass the entire `values` object to the dependency list. `getFieldValue` would be usefull here.
