### ISSUE TITLE
Dynamic Validation rules

### ISSUE THREAD

**Issue by amivag** [jaredpalmer/formik#658]
Some of my form's input fields, depend on other inputs for their values. So for example, **Field B**'s valid range of inputs, depends on what has been put into **Field A**.

Is this possible to accomplish in a Formik/Yup combination?

Thanks

**Comment by latviancoder** [comment]
This doesn't have much to do with formik, but yes, it is possible to accomplish with `yup`:

https://github.com/jquense/yup#mixedwhenkeys-string--arraystring-builder-object--value-schema-schema-schema

**Comment by makhnovskiy** [comment]
Yes as @latviancoder has mentioned, you would have to do with yup. See code snippet of my implementation on this. If identifyType is 'ssn', then validate the ssnNum field. Otherwise, skip validation: 

` mapPropsToValues() {
                return {
                    firstName: '',
                    lastName: '',
                    dateOfBirth: '',
                    identifyType: 'ssn' || '',
                    ssnNum: '',
                }
            },
            validationSchema: (values) => Yup.object().shape({
                firstName: Yup.string().required('First Name is required'),
                lastName: Yup.string().required('Last Name is required'),
                dateOfBirth: Yup.date().required('Date of Birth is required'),
                identifyType: Yup.string().required('Identify Type is required'),
                ssnNum: Yup.string().when('identifyType',
                    {
                        is: 'ssn',
                        then: Yup.string().min(9, 'Social Security Number must be up to 9 digits without dashes').required('Social Security Number is Required')
                    })
            }),`

**Comment by Andreyco** [comment]
Closing as correct suggestion is provided above and this is not Formik issue
