### ISSUE TITLE
Question about validation - Casting an input value to 'number'

### ISSUE THREAD

**Issue by Surreal9** [jaredpalmer/formik#67]
I have an input that is supposed to contain a number. If I set the validation schema for this field to be `yup.number().required()`, when I go to edit the field it complains, likely since it is treating the input value as a string. I see from the `yup` [docs](https://github.com/jquense/yup#mixedcastvalue-any-any) that they have a `cast` method, but I'm not sure how to have formik attempt to cast values before/during validation.

Is there something I'm missing? Am I meant to manually specify this cast in `mapValuesToPayload`?

**Comment by husa** [comment]
+1
Would be great to have `values` lifecycle methods similar to redux-form, something like `format/parse/normalize`. 
A use case I see, is to have input that accepts numbers only, or some custom formatting for dates, etc.

**Comment by Andreyco** [comment]
Solution I saw elsewhere...
Main idea is to have always async validation function. Resolve with (sanitised) data, reject with errors instead.

```
const formikConfig = {
  validate: async function(values) {
    try {
      const sanitizedValues = sanitizeValues(values);
      validate(values, rules, messages);
      return sanitizedValues;
    } catch (validationErrors) {
      throw transformErrors(validationErrors);
    }
  },
};
```

**Comment by jaredpalmer** [comment]
Do the transforms outside of Formik. It gets cast to a string no matter what as soon as you place it into `value={}` prop anyways.

**Comment by husa** [comment]
At the moment, Formik does not allow you to do anything to `values`, the only way to achieve custom formatting/sanitization is writing your own custom input, do the heavy lifting inside, and manually trigger `onChange(e)`.

**Comment by Moejoe90** [comment]
that is not the case currently you can just use `input` type `number`

**Comment by agos** [comment]
`input` type `number` works, but is not available for `select` and, in general, for custom inputs

**Comment by zachhale** [comment]
If you are getting this and just want to fix the error message you can chain `typeError('Something must be a number')` or similar to make the error prettier.

**Comment by kelly-tock** [comment]
this may be a different question, but I want to use the validation schema on an input that must be a number.  the inputs are strings, for now i'm doing a test, but is there a way to do a cast in the chain?

**Comment by kelly-tock** [comment]
```
priceCents: Yup.string()
    .required('Amount is required')
    .test('priceCents', 'Amount must be a positive number', (value) => _.toNumber(value) > 0 )
```

**Comment by kelly-tock** [comment]
is this the only way to do this in formik and yup?

**Comment by davidspiess** [comment]
I use custom inputs to cast select values to numbers:

```tsx
const SelectNumber: FunctionComponent<FormFieldProps> = ({
  field,
  children,
  form: { setFieldValue }
}) => {
  return (
    <select
      id={id}
      {...field}
      onChange={e => {
        setFieldValue(field.name, +e.currentTarget.value);
      }}
    >
      {children}
    </select>
  );
};

```

**Comment by johnrom** [comment]
I'd recommend doing something similar to @davidspiess above, except you can create a composable callback like this:

```
const stringToNumberConverter = stringValue => parseInt(stringValue, 10);
const parseAndHandleChange = (handleParse, handleChange) => event => {
    const value = handleParse(event.target.value);

    handleChange(event.target.name)(value);
}
const MyForm = () => {
    <Formik /* etc */>
        {(formikProps) => (
            <Field 
                name="myNumberField" 
                onChange={parseAndHandleChange(stringToNumberConverter, formikProps.handleChange)} 
            />
        )}
    </Formik>
}
```

FYI in v2 there are possible plans for an `onParse`-like API. Hopefully that will make things easier #1525

**Comment by Nditah** [comment]
```ts
  <TextInput 
    value={values.price} 
    onChange={value => setFieldValue('price', parseFloat(value))}
    onBlur={handleBlur('price')}
  />
```
