### ISSUE TITLE
How to use formik Field with reactstrap Input?

### ISSUE THREAD

**Issue by godmar** [jaredpalmer/formik#670]
I'm using reactstrap and its [form controls](https://reactstrap.github.io/components/form/).
I am able to use formik with reactstrap's Input component like so:

```
  <Input type='text' name="display_name"
     value={values.display_name}
     onChange={handleChange}
     onBlur={handleBlur} /> 
```

I am intrigued by the short-hand `Field` provides. For instance, this works for me:
```
     <Field name="display_name" type="text" />
```
however, it is rendered via a `<input>` component.

How do I render Fields via Input?  The documentation on [Field](https://github.com/jaredpalmer/formik#field-) is sparse on that, mentioning a `component` and a `render` property.  I tried:
```
    <Field name="display_name" component={Input} />
```
This renders an Input element, but formik doesn't pass the value and handleChange properties to it.
I reverse engineered the `render` method and found that it is passed a `field` and `form` property.
I tried:
```
    <Field name="display_name" render={({field}) => <Input {...field} /> }   />
```
which seems to work.

This makes me concerned that I don't know how to use formik in the intended way.  I've checked the [source code](https://github.com/jaredpalmer/formik/blob/master/src/Field.tsx#L193-L197) and formik passes a field/form bag object rather than the (flattened) properties of field to the rendered component.

Could you clarify the intended use/where I'm going wrong?

**Comment by artisologic** [comment]
I'm seeing the same thing trying to use `Field` with my custom `Input` component.
Following the source code (https://github.com/jaredpalmer/formik/blob/master/src/Field.tsx#L194) components get passed the formik bag, which mean they receive a prop `field` which contains the handlers (`onChange`, `onBlur`, etc).

In my opinion this is counter-intuitive as I would now have to adapt my own generic component an re-wire the handlers from `field`.

I would have expected `Field` to spread `...field` directly on the component.

**Comment by godmar** [comment]
I too would have expected `Field` to spread `...field` directly in the component, like @artisologic

**Comment by prichodko** [comment]
This will probably be tackled in V2.

**Comment by danielholmes** [comment]
I've got this working via the `tag` property:

```js
<Input
  tag={Field}
  name='name'
  type='text'
  component='input'
/>
```

**Comment by shoaibkhan94** [comment]
I have created an npm module for this. You can try it out here - https://www.npmjs.com/package/reactstrap-formik

**Comment by Salles-FA** [comment]
Thankyou @danielholmes 

This code worked fine for me!

```js
<Formik
	initialValues={{
		firstName: '',
	}}
	validationSchema={Yup.object().shape({
		firstName: Yup.string()
			.min(2, 'Too Short!')
			.max(5, 'Too Long!')
			.required('Required'),
	})}
	onSubmit={values => {
		// same shape as initial values
		console.log(values);
	}}>
	{({ errors, touched }) => (
		<Form>
			<FormGroup row>
				<Col md="2">
					<Label for="firstName">First Name</Label>
					<Input
						type="text"
						name="firstName"
						tag={Field}
						invalid={errors.firstName && touched.firstName}
					/>
					<FormFeedback tooltip>{errors.firstName}</FormFeedback>
				</Col>
			</FormGroup>
			<Button color="primary">Submit</Button>
		</Form>
	)}
</Formik>
```

**Comment by prichodko** [comment]
Thanks @danielholmes!

**Comment by zshannon** [comment]
@Salles-FA mind sharing your imports too?

**Comment by danlupascu** [comment]
I managed to make it working by wrapping it in a custom component and passing the component as the component prop to the Formik Field, as explained in the [documentation](https://jaredpalmer.com/formik/docs/api/field#field-render-props).

```javascript
import React from 'react';
import {
  Input,
  FormFeedback
} from 'reactstrap';
import {Field as FormikField} from 'formik';

/**
 * A custom bootstrap input component to use with a formik field
 * @param field
 * @param touched
 * @param errors
 * @param props
 * @returns {*}
 * @constructor
 */
const CustomBootstrapInputComponent = ({
   field,  // { name, value, onChange, onBlur }
   form: {touched, errors}, // also values, setXXXX, handleXXXX, dirty, isValid, status, etc.
   ...props
}) => (
    <div>
      <Input
          invalid={!!(touched[field.name] && errors[field.name])}
          {...field}
          {...props} />
      {touched[field.name] && errors[field.name] && <FormFeedback>{errors[field.name]}</FormFeedback>}
    </div>
);

/**
 * A Formik Field whose component is a custom bootstrap input
 * Usage: pass the same props to this component as you would pass to the Input field from reactstrap.
 * Example:
 *    <FormikFieldWithBootstrapInput
         name="email"
         placeholder='Email'
         bsSize='lg'
         className={'mb-2'}
         type={'email'} />

      //is equivalent with
      <FormikField name='email'>
         {({ field, form }) => (
          <Input
               placeholder='Email'
               bsSize='lg'
               className={'mb-2'}
               type={'email'}
               invalid={form.touched[field.name] && form.errors[field.name]}
                />
          )}
      </FormikField>
 * @param props
 * @returns {*}
 */
export default props => (
    <FormikField
        {...props}
        component={CustomBootstrapInputComponent}/>
);
```

And this is how I use it:
```javascript
import FormikFieldWithBootstrapInput from './components/FormikFieldWithBootstrapInput';
const LoginForm = (props) => (
    <Formik
        initialValues={{
          email: '',
          password: ''
        }}
        validationSchema={LoginSchema}
        onSubmit={values => props.login(values.email, values.password)}
    >
      {() => (
          <Form>
            <FormikFieldWithBootstrapInput
                name="email"
                placeholder={props.t('email')}
                bsSize='lg'
                className={'mb-2'}
                autoComplete={'email'}
                type={'email'}/>
            <FormikFieldWithBootstrapInput
                name="password"
                placeholder={props.t('password')}
                bsSize='lg'
                className={'mb-2'}
                autoComplete={'current-password'}
                type={'password'}/>
            <p className={'text text-center text-danger'}>{props.authenticationError}</p>
            <Button color={'primary'} size='lg' type={'submit'} block>{props.t('login')}</Button>
          </Form>
      )}
    </Formik>
);
```

You can just replace the `Input` from `CustomBootstrapInputComponent` with your own input and it should work fine. Just make sure that you set the `name` prop on the created formik field, otherwise it will not work.

**Comment by godmar** [comment]
> Therefore, if you're converting from Formik to Formik + Reactstrap, it is imperative that you continue to import Form from formik and NOT reactstrap.

I think you can and probably should combine both.  Reactstrap form has a [tag=](https://github.com/reactstrap/reactstrap/blob/master/src/Form.js) to that effect:

```
import { Form as FormikForm } from 'formik';
import { Form as RSForm } from 'reactstrap';

return <RSForm tag={FormikForm}> ... </RSForm>;
```

This way you should get the CSS from reactstrap and you get Formik's default submission handling.

Thoughts @wschmrdr ?

**Comment by wschmrdr** [comment]
It certainly works. The only benefit I'm seeing, after looking at the documentation, to using Reactstrap's form is the shortcut for form-inline, but that could be done with className since you're likely already bringing in the CSS file via other components in reactstrap (e.g. Button, Row, Col), and in my personal opinion, I don't think it's worth the memory cost of an additional import to get that. However, you're absolutely correct that it's possible to use both, and some may prefer that way.

**Comment by godmar** [comment]
What if, in the future, formik or reactstrap change their implementation?

**Comment by wschmrdr** [comment]
If we're going down that hyperbole, updating that line would be one step in a thousand that's going to need to happen on every form regardless of which way it gets implemented.

**Comment by cuhabaho** [comment]
Hi everyone, i am trying to use formik field with react-bootstrap but i could not make it work. Anyone has any idea what should i do?

```
import { Form } from "react-bootstrap";

<Form.Check
        tag={Field}
        className="mr-2 ml-4"
        required
        component='input'
        label="&nbsp;&nbsp;I Agree to all statement in"
        feedback="You must agree before submitting."
      />
```

**Comment by wschmrdr** [comment]
As was discussed previously, there is likely some mismatching between the Formik Form and the React-bootstrap Form that is causing weirdness. However, in this particular case, I would actually take the advice of @godmar and implement both forms using his method, as you'll likely be needing both of them. Then, when referencing Form for the purposes of Form.Check, make sure you're getting the react-bootstrap version. Give it a try and see if it works.

Interesting that there's another implementation... we'll see which one ends up being preferred after this goes to a final release version.

**Comment by shivenj** [comment]
> Thankyou @danielholmes
> 
> This code worked fine for me!
> 
> ```js
> <Formik
> 	initialValues={{
> 		firstName: '',
> 	}}
> 	validationSchema={Yup.object().shape({
> 		firstName: Yup.string()
> 			.min(2, 'Too Short!')
> 			.max(5, 'Too Long!')
> 			.required('Required'),
> 	})}
> 	onSubmit={values => {
> 		// same shape as initial values
> 		console.log(values);
> 	}}>
> 	{({ errors, touched }) => (
> 		<Form>
> 			<FormGroup row>
> 				<Col md="2">
> 					<Label for="firstName">First Name</Label>
> 					<Input
> 						type="text"
> 						name="firstName"
> 						tag={Field}
> 						invalid={errors.firstName && touched.firstName}
> 					/>
> 					<FormFeedback tooltip>{errors.firstName}</FormFeedback>
> 				</Col>
> 			</FormGroup>
> 			<Button color="primary">Submit</Button>
> 		</Form>
> 	)}
> </Formik>
> ```

For input it works fine. thank you for posting this solution. But for textarea it render it as input.

**Comment by wschmrdr** [comment]
> For input it works fine. thank you for posting this solution. But for textarea it render it as input.

Did you try putting component and type attributes of "textarea" on the Input tag? That should get the thing to show as a textarea. And a rows attribute will give you the number of rows.

**Comment by sametcodes** [comment]
> > For input it works fine. thank you for posting this solution. But for textarea it render it as input.
> 
> Did you try putting component and type attributes of "textarea" on the Input tag? That should get the thing to show as a textarea. And a rows attribute will give you the number of rows.

This way seems working:

```javascript
<Field id="contractDescription" name="contractDescription"
   render={({field}) => <Input {...field} type="textarea" /> } />
```

**Comment by custom-tag85** [comment]
> This will probably be tackled in V2.





https://reactdev.space/questions/reactstraps-dropdown-component-with-a-search-input
