### ISSUE TITLE
Easier typing with TS

### ISSUE THREAD

**Issue by zachrip** [jaredpalmer/formik#675]
Currently to use the types with the render prop class you have to manually [create the interfaces and use the generics](https://github.com/jaredpalmer/formik#render-props-formik--and-field-). I like the way that apollo has done this:
```
class WithUser extends Query<RESPONSE, VARIABLES> {}

const Comp = () => (
  <WithUser variables={/* is VARIABLES */}>
    {({ data }) => /* data is RESPONSE */}
  </WithUser>
);
```
This essentially allows you to use these types across all of the methods in the formik class so the user doesn't need to set any of their own types in places like `onsubmit` or the render prop.

**Comment by jaredpalmer** [comment]
TS 2.9 has jsx generics—specifically built to fix this.

**Comment by zachrip** [comment]
@jaredpalmer can you show an example of this usage? It doesn't seem to be working locally for me on ts 2.9.
