### ISSUE TITLE
Dot notation for fields 

### ISSUE THREAD

**Issue by 32teeths** [jaredpalmer/formik#676]
**Describe the bug**
When using formik where the form name have object notation , It breaks. mapPropsToValues builds an object like {'person.name':'Person Name'} , handleChange does not seem to work fine . 

I am using the <Field/> component  <Field id={path} value={values[path]} className={`form-control ${props.errors[column.index] && props.touched[column.index] ? 'is-invalid' : ''}`} type="text" placeholder={`Enter ${column.name}`} /> where column.path has a dot within , like 'menu.name' .

 I tried passing the onChange custom using handleChange with first argument as the field name and second with the value , But it did not work .  

---
- Formik Version: 0.11.11
- React Version:16.3.2
- Node Version:10.3.0
- Package Manager and Version:
npm : 6.1.0

**Comment by sshmyg** [comment]
@32teeths `mapPropsToValues ` in case of `object` yup type should includes within object.

```
mapPropsToValues = {
    person: { name: 'Person Name' }
}
```

**Comment by hoschi** [comment]
@sshmyg how comes yup into play here? If you want/need to separate keys which become HTML element ids you need some separator. E.g.: 
```js
{
  'billingInfo.firstName':'Max',
  'contactInfo.firstName':'Clementine',
}
```
While keeping the values object flat you are able to handle it the same way, no matter how the input/output should look like. This custom form fields are easier to implement as they don't need to handle different structures.

I hope this provides some details about the use case, at least mine.

**Comment by hoschi** [comment]
@jaredpalmer ?

**Comment by karbica** [comment]
@jaredpalmer ?

**Comment by hoschi** [comment]
@karbica How to handle nested objects are described here: https://jaredpalmer.com/formik/docs/guides/arrays

**Comment by italodeandra** [comment]
If anyone gets here while trying to do the opposite (having keys with dots instead of nesting) you should do like this:

```jsx
<Field
  name="['owner.username']"
  label="Owner user name'"
/>
```

This is not documented. But I'm creating a PR.

**Comment by lukejagodzinski** [comment]
Tbh it's a little bit weird solution for this problem. I would rather allow arrays as `name`, so something like this:

```jsx
<Field
  name={["owner.username"]}
  label="Owner user name'"
/>
```

so that you can also pass something like this, if you want nesting.

```jsx
<Field
  name={["owner", "username"]}
  label="Owner user name'"
/>
```

Internally the `"owner.username"` is still being split into array by `.` separator, so allowing arrays as name is imho elegant.

@italodeandra thanks for the info about this feature!

**Comment by italodeandra** [comment]
Hi @lukejagodzinski,

I don't use Formik anymore, but I think this behavior is not intentional. They use the same notation as Lodash, which is pretty old and they never implemented the way you described, so I'm not really sure why they didn't but I agree with you that is more elegant. Perhaps its a limitation.

**Comment by lukejagodzinski** [comment]
@italodeandra yep I've just checked source code and discovered that they are using lodash under the hood. Makes sense why it was done this way :).
What are you using this days? I'm not supre happy about Formik :)

**Comment by DD-UX** [comment]
I'm looking for a way to update dot notation objects with at least two levels of deepness programmatically (ie. `setFieldValue`).

There is a getter method called `getIn` that accept an array of strings (keys) so where `getIn(formikValues, ['the.key', 'the.nested.key'])`, the return value will come from `formikValues['the.key']['the.nested.key']`.

The setter counterpart (`setIn`) seems to not work the same way, nor `setFieldValue`.
Is there a way that doesn't involve a custom recursive function to update the `formikValues` in a shallow copy and reassign it all?

Thanks in advance

**Comment by DD-UX** [comment]
Welp, in the end I had to use 
```
import set from 'lodash/set';
...
...
// Get an updated version of the values where the deep key has been updated
const updatedFormikInstanceValues = set(formikInstance.values, getInKeyList), newValue);
// Apply new value through the first pointer so everything re-hooks (no validation is intentional)
formikInstance.setFieldValue(getInKeyList.shift() as string, updatedFormikValues, false);
```
<img width="600" alt="Thor sad" src="https://data.whicdn.com/images/335170950/original.gif" />
