### ISSUE TITLE
' ' as nextValue in reset  should work 

### ISSUE THREAD

**Issue by Sunshine168** [jaredpalmer/formik#678]
**Describe the bug**
 Sometime we want reset the form with '' , such as reset the textarea ~  but ```const values = nextValues ? nextValues : this.props.initialValues;``` so the nextValue must be  '[speace]',may de unreasonable  
https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L409

**To Reproduce**

**Expected behavior**

**Suggested solution(s)**

**Additional context**

---

- Formik Version:
- React Version:
- TypeScript Version:
- CodeSandbox Link:
- OS: 
- Node Version:
- Package Manager and Version:

**Comment by IgorJoergensen** [comment]
Values are an object as a key/value store where key is the name of the field in the form - and the value is... well the value for that field.

You wanna reset a form's initial values - well values - to be a single empty string?

Not gonna happen.

If your form contains a single textarea with the name "john" - then you need to send nextProps as

```
{ john: '' }
```
