### ISSUE TITLE
TS error, name not usable from FieldArray render props

### ISSUE THREAD

**Issue by draco** [jaredpalmer/formik#681]
**Describe the bug**

There is a `props.name` in https://github.com/jaredpalmer/formik/blob/4ac3cd171b521a92d4f41500049e3a477a0a71ad/src/FieldArray.tsx#L265 but the TS definition doesn't seem to include it (therefore cannot be used).

**To Reproduce**

```
    <FieldArray name="namename">
      {({ push, remove, name }) => {
        console.log(name);
        return <div />;
      }}
    </FieldArray>
```

The `name` argument is a TS warning although console logs `namename`.

![screen shot 2018-06-07 at 3 41 05 pm](https://user-images.githubusercontent.com/55601/41085319-38228620-6a69-11e8-9f94-e5a3f548355c.png)

**Expected behavior**

Expect `name` to be usable as a props without type error from TS.

---

- Formik Version: 0.11.11
- React Version: 16.3.2
- TypeScript Version: 2.8.3
- CodeSandbox Link: https://codesandbox.io/s/mmmo9ply5y
- OS: macOS 10.13.5
- Node Version: 8.9.3
- Package Manager and Version: yarn 1.7.0

**Comment by nzacca** [comment]
Affects v1.2.0 as well.

Here is the line referenced in master: https://github.com/jaredpalmer/formik/blob/master/src/FieldArray.tsx#L266

I believe the fix is to add `name` to the `SharedRenderProps` here:

https://github.com/jaredpalmer/formik/blob/master/src/FieldArray.tsx#L17

**Comment by jaredpalmer** [comment]
Can you submit a PR?

**Comment by nzacca** [comment]
No problem. I can get to it this weekend.

**Comment by nzacca** [comment]
PR submitted. Feedback welcome.
