### ISSUE TITLE
Async validation + less boilerplate

### ISSUE THREAD

**Issue by ankeetmaini** [jaredpalmer/formik#686]
**Is your feature request related to a problem? Please describe.**
- currently every field needs to handle onChange/onBlur/value
- validation is now handled via a big function for the entire form, not at individual field level

**Describe the solution you'd like**
- to remove boilerplate we can have a simpler API, where `fieldProps` will attach `onChange`, `onBlur`, `value` automatically.
- this will also be beneficial when people have to add their on `onChange` handler in fields maybe for fetching next set of dropdown data or updating the URL
```jsx
render={({
        values,
        fieldProps,
        handleSubmit,
        isSubmitting,
      }) => (
        <form onSubmit={handleSubmit}>
          <input
            {...fieldProps({
                id: email,
                type: 'email'
             })}
          />
```

- similarly we can break down validations at field level 
```jsx
const notEmpty = value => {
  if (!value) return { valid: false, message: 'Cannot be empty'}
  return true;
}

<input
            {...fieldProps({
                id: email,
                type: 'email',
                validators: [notEmpty, email]
             })}
          />
```
- validators will be an array of functions (sync, async) which will return {valid, message?} as an object and this can be used inside formSubmit to check whether the form is good to go or not.
- async validations will be extremely easy with this, e.g. username validator 
- we can implement this using an async await inside a reduce so that the validations are run in order

**Describe alternatives you've considered**

**Additional context**
I absolutely loved Formik's API and for learning purposes made something similar with the above mentioned features. https://github.com/ankeetmaini/simple-forms-react

Let me know if you like this then I can come up with a PR.

**Comment by jaredpalmer** [comment]
I'm not really a fan of prop getters. If you like them, you can make a small wrapper around Formik to give you that functionality.
