### ISSUE TITLE
handleReset performs submit, not reset

### ISSUE THREAD

**Issue by noliiva** [jaredpalmer/formik#69]
Hi :)
Thanks for all your work. I especially like the way Formik deals with form validation.
So I want to give it a try and implement your example and it works pretty well, except for the reset button. It performs a submit, and reset nothing. It works when preventDefault is called before handleReset, but I'm not sure it's the right way to do it.
I also tried resetForm, but it's the same.
Thanks for your help.

**Comment by jaredpalmer** [comment]
Double check that your reset button has `type="button` and **not** `type="submit`.

**Comment by noliiva** [comment]
It's exactly the code of your example.
<button onClick={handleReset} />Reset</button>
I tried to use type="reset", but it change nothing.
type="submit" is only on the submit button.
