### ISSUE TITLE
Using setFieldValue for one field, based on input of another

### ISSUE THREAD

**Issue by btmdave** [jaredpalmer/formik#692]
I'm not sure if this is not supported or if there's an alternative solution currently, but I'm trying to update one field, based on the `onChange` input of another.

For example:

```
const onEmailChange = (e, setFieldValue) => {
  const domain = e.target.value.replace(/.*@/, '')
  setFieldValue('mail.domain', domain, false)
}

const Form = ({ data }) => {
  return (
    <Formik
      initialValues={data}
      render={({
        values,
        errors,
        handleSubmit,
        handleChange,
        isSubmitting,
        setFieldValue
      }) => (
        <form onSubmit={handleSubmit}>
          <Input
            type="text"
            name="mail.email"
            value={values.mail.email}
            onChange={ev => onEmailChange(ev, setFieldValue)}
          />
          <Input
            type="text"
            name="mail.domain"
            value={values.mail.domain}
          />
        </form>
      )}
    />
  )
}
```

This is attempting to set the value of `mail.domain` based on the input of `mail.email`.  The problem is that when calling `setFieldValue`, it seems to stop updating the field as you type and just gets replaced with each new letter.

**Comment by IgorSzyporyn** [comment]
As for alternative solution - try this

```
const onEmailChange = (e, onChange, form) => {
  const domain = e.target.value.replace(/.*@/, '')
  onChange(e)
  form.setFieldValue('mail.domain', domain)
}

const Form = ({ data }) => {
  return (
    <Formik
      initialValues={data}
      render={({ values, handleSubmit, onChange }) => (
        <Form onSubmit={handleSubmit}>
          <Field
            name="mail.email"
            value={values.mail.mail}
            render={({ field, form }) => (
              <input
                name={field.name}
                value={field.value}
                onChange={e => {
                  onEmailChange(e, onChange, form)
                }}
              />
            )}
          />
          <input type="text" name="mail.domain" value={values.mail.domain} />
        </Form>
      )}
    />
  )
}
```

**Comment by msmaromi** [comment]
@btmdave you should set the value of the actual field
```
const onEmailChange = (e, setFieldValue) => {
  const domain = e.target.value.replace(/.*@/, '')
  setFieldValue('mail.email', e.target.value)
  setFieldValue('mail.domain', domain, false)
}
```

**Comment by akwasin** [comment]
This helped me solve a reset input field issue I've had for about 8h in a 3 level deep nested react component containing an input field while maintaining `dirty: true`. Thanks guys. 

So simple but so hard to find on the net.
`const resetField = name => {
    form.setFieldValue(name, '');
  };`

**Comment by seven7hell** [comment]
@msmaromi Thanks. You saved me from a disturbing day.

**Comment by ameyarumbleon** [comment]
this is for others who also find this issue you can reset the field by using "form.resetFields" this should go as the last line after all the calls.

**Comment by vahe-nikoghosyan** [comment]
when `setFieldValue` function' 3rd parameter is `false`, it doesn't validate that field

`setFieldValue: (field: string, value: any, shouldValidate?: boolean) => void`

as default 3rd parameter is `true`
