### ISSUE TITLE
Formik with @material-ui/core Select is warning?

### ISSUE THREAD

**Issue by Adherentman** [jaredpalmer/formik#694]
got this warning when i use @material-ui select component.
![wx20180614-152752](https://user-images.githubusercontent.com/26477346/41398327-93a4b164-6fe9-11e8-8b5f-1a973bcfa1bd.png)

This is my code

```typescript
function CustomSelect ({...props}: any) {
  // tslint:disable-next-line:max-line-length
  const { classes, formControlProps, LabelProps, labelText, id, selectProps, handleChange, handleBlur, values, children } = props;
  return (
    <FormControl
      {...formControlProps}
    >
    {labelText !== undefined ? (
      <InputLabel
        htmlFor={id}
        {...LabelProps}
      >
        {labelText}
      </InputLabel>
    ) : null }
      <Select
        // onBlur={handleBlur(id)}
        // onChange={handleChange(id)}
        {...selectProps}
      >
        {children}
      </Select>
    </FormControl>
  );
}
```

```typescript
<Field
   name="category"
   render={({ field }: FieldProps<FormValues>) => (
   <CustomSelect
       labelText="Select"
       htmlFor="test"
       formControlProps={{
       fullWidth: true
     }}
       selectProps={{
       autoWidth: true,
       ...field,
       input: <Input id="test" name="category"/>
       // inputProps: {
       //   id: 'test',
       //   name: 'category'
       // }
   }}
   >
      <MenuItem value=""><em>None</em></MenuItem>
      <MenuItem value={10}>Ten</MenuItem>
      <MenuItem value={20}>Twenty</MenuItem>
      <MenuItem value={30}>Thirty</MenuItem>
     </CustomSelect>
   )}
/>
```

**Comment by IgorJoergensen** [comment]
Yeah - also problems with
https://github.com/JedWatson/react-select

**Comment by ArvinH** [comment]
Is this still a problem that doesn't have workaround yet?

**Comment by metr1ckzu** [comment]
```
<Select
   value={roleId}
   onBlur={event => {
      event.target.name = 'roleId';
      handleBlur(event);
   }}
/>
```

But for it's a little bit sloppy. Formik returns error with a significant delay, don't know it's my code or some internal issue.

**Comment by Filson14** [comment]
@metr1ckzu - I tried Your workaround and it doesn't seem to make a difference. Maybe it's because Select component has no prop called onBlur according to the [docs](https://material-ui.com/api/select/)?
And You're right. First occurs list blur (what brings focus to select itself) and the the input "is blured".

**Comment by tonnenpinguin** [comment]
Seems like this issue still persists. We are using a slightly more generic version of @metr1ckzu 's workaround:

```js
const handleBlurWorkaround = value => event => {
  event.target.name = value;
  return event;
};
```

The `onBlur` prop of the `Select` component is then passed this little gem here:
```js
onBlur={R.compose(
    handleBlur,
    handleBlurWorkaround(field.name),
)}
```

**Comment by prichodko** [comment]
Whenever library doesn't call handlers with native events, you can use `setField***` to achieve same functionality, e.g.:

```js
onChange={value => setFieldValue(field.name, value)}
onBlur={() => setFieldTouched(field.name)
```

**Comment by tonnenpinguin** [comment]
Thanks @prichodko! This actually fixed the issue for me.

**Comment by Natansab** [comment]
> Whenever library doesn't call handlers with native events, you should use `setField***` to achieve the same functionality, e.g.:
> 
> ```js
> onChange={value => setFieldValue(field.name, value)}
> onBlur={() => setFieldTouched(field.name)
> ```

Thanks for the advice, for anyone who is still struggling, it will most probably work using:
`onChange={(e, { value }) => setFieldValue(field.name, value)}`

**Comment by amandakoster** [comment]
@Natansab Where/how did you define `setFieldValue` and `setFieldTouched`?

**Comment by johnrom** [comment]
@amandakoster setFieldValue and setFieldTouched come from `useFormikContext` or the props passed to Formik's child component, but you don't need to use them during normal handleChange / handleBlur usage.

Normal handleChange / handleBlur usage is:

```jsx
<YourCustomField
  // if your custom field passes an `Event` to callback:
  onChange={formik.handleChange}
  onBlur={formik.handleBlur}
  // if your custom field only passes a value to onChange, and doesn't pass an event to handleBlur:
  onChange={formik.handleChange("fieldName")}
  onBlur={formik.handleBlur("fieldName")}
/>
```

**Comment by amandakoster** [comment]
Here was our final fix for this issue in IE:
```
     onBlur={e => {
            e.target.name = name;
            field.onBlur(e);
          }}
```

**Comment by H36615** [comment]
If anyone's still having issues relating to this, my solution was to remove the `onBlur` from the `<Form/>` element which was causing the warning in OP:

`<Form onChange={handleChange}> onBlur={handleBlur} `
`<Form onChange={handleChange}>`
