### ISSUE TITLE
touched not set properly for some fields after submit

### ISSUE THREAD

**Issue by jKatt** [jaredpalmer/formik#695]
**Describe the bug**
When an unchanged form with multiple fields, which initial values are set to the same reference(object), is submitted only one field is marked as touched.

**To Reproduce**
I changed the basic example a bit to show the behavior:
https://codesandbox.io/s/oqmj77vnkq

**Expected behavior**
All fields should be marked as touched.

**Suggested solution(s)**
I haven't looked in the code yet but it might help to clone the initial value if it is an object.

**Additional context**

---
- Formik Version: 0.11.11 / 1.0.0-beta.2
- React Version: 16.3

**Comment by WesselKroos** [comment]
@jKatt I'm running into the same issue. Have you found a solution/workaround?
