### ISSUE TITLE
[Flow] Using `withFormik` with StatefulComponent `flow` don't show expected type errors

### ISSUE THREAD

**Issue by DTupalov** [jaredpalmer/formik#696]
**Describe the bug**
If I'm using `withFormik` with StatefulComponent, than `flow` don't show expected type errors for `OwnProps` in `EnhacedComponent` (if I don't set some required props, I mean). For `StatelessComponent` type errors shows as expected.

**To Reproduce**
Here the URL with live code example https://goo.gl/AJr5sN

There are two enhaced components:
- `EnhacedFormStateless` that wrapped `InnerFormStateless` component
- `EnhacedFormClass` that wrapped `InnerFormClass` component

For the first component shows type error (required `status` prop is not a string)
For the second - no errors at all, but should the same

**Expected behavior**
Should shows expected type errrors for the both type components: stateless and stateful.

---

- Formik Version: 0.11.11
- React Version: 16.2.0
- Flow try Link: https://goo.gl/AJr5sN
- OS: Microsoft Windows [Version 10.0.17134.112]
- Node Version: 8.9.4
- Package Manager and Version: 5.6.0

**Comment by vovanmix** [comment]
+1, facing the same problem!

**Comment by jaredpalmer** [comment]
Flow types are not shipped with Formik. Please make an issue in flowtyped.
