### ISSUE TITLE
Custom isInitialValid should actually run errors so that they are visible

### ISSUE THREAD

**Issue by togakangaroo** [jaredpalmer/formik#698]
I have a long form that is persisted to the backend as the user works through it. This form has only a couple validations and when the user goes to the page, I need them to see any errors they might have so that they don't try to submit it.

It would seem to me that if isInitialValid is overridden, it would make sense to run `validateForm` to populate errors so that they're available. Its rather strange to have it not be valid but to have zero errors

Currently I am solving this by implementing

    isInitialValid: ({validate, data})=> !Object.keys(validate(data)).length,

and adding in a higher order component

```
const validateFormInitially = (FormComponent) =>
  class ValidateFormInitially extends Component {
    doCheck = () => {
      if(!this.props.isValid && !Object.keys(this.props.errors).length)
        this.props.validateForm(this.props.values)
    }
    componentDidUpdate = () => this.doCheck()
    constructor(props) {
      super(props)
      this.doCheck()
    }
    render = () => React.createElement(FormComponent, {...this.props})
  }
```

but that is both a pain, and the sort of behavior that I would expect from `isInitialValid`.

Additionally, I feel like `values` should be available in that function, but I don't feel super strongly about that.

**Comment by mistadikay** [comment]
If validators are asynchronous, even that painful solution from @togakangaroo will not work. Would be nice to have an option to trigger validation on `componentDidMount` - whether it's synchronous or asynchronous.

**Comment by mistadikay** [comment]
also, folks in #189 have a similar problem

**Comment by mistadikay** [comment]
or even better: allow `isInitialValid` to return a Promise like `validate` does

**Comment by togakangaroo** [comment]
I do think this hasn't been addressed and the point by @mistadikay is valid and maybe should become an up for grabs task?

**Comment by DeClaessens** [comment]
Is there a certain issue to running `validateForm()` in `componentDidMount` that I am overlooking ? I came across the same issue and solved it that way.

**Comment by keddisa** [comment]
If you're using Yup for validationSchema, Yup has it's own validation method that you can run in your lifecycle methods pre form render

Something like:
const isInitialFormValid = await validationSchema.isValid(initialValues)
(that returns a boolean)

and then you can assign isInitialFormValid to Formik's isInitialValid

<Formik
              initialValues={initialValues}
              validationSchema={validationSchema}
              isInitialValid={isInitialFormValid}
              .
              .
/>

PS: validationSchema.isValid() returns a promise, so you need to take that into consideration
