### ISSUE TITLE
Add an Instant Form Validation Change Prop 

### ISSUE THREAD

**Issue by alidcastano** [jaredpalmer/formik#699]
Right now the `touched` property is only set on an `onBlur` event when the user focuses out of the field, but based on the name I would have imagined it was set on an `onChange` event.

I'd like to propose an `handleInstantChange` option, which along with firing the regular `handleChange` also updates the fields touch/error values.

Right now I have a wrapper around Formik that handles this:

```
export default function InstantFormik ({ render, ...formProps }) {
  const debounced = {}
  return (
    <Formik 
      {...formProps as any} 
      render={(renderProps: any) => {
        const { touched, handleChange, setFieldTouched } = renderProps 

       const handleInstantTouch = (field) => {
          if (debounced[field]) {
            clearTimeout(debounced[field])
          }
          const debouncedId = setTimeout(() => setFieldTouched(field, true, true) , 500)
          debounced[field] = debouncedId
        }
    
        renderProps.handleChange = (e) => {
           const field = e.target.name
          if (!touched[field]) handleInstantTouch(field)
          handleChange(e)
        }

        return render(renderProps)
      }}
    />
  )
}
```

Let me know if you'd be interested in integrating this into Formik! 

This is related to issue #237 but I'm not sure any changes have been made in this regard since issue was closed with @joelhooks deciding to maintain his own fork

**Comment by kevin-wolf** [comment]
@alidcastano I'd tried to implemented this and it doesn't work inside the `<Field />` component, if I try to log the `form` prop, the `handleChange` method isn't modified.

Are you using it with `<Field />` component?

**Comment by alidcastano** [comment]
I am not using the Field component currently
