### ISSUE TITLE
Problem with Yup & React Select Validation

### ISSUE THREAD

**Issue by chobo2** [jaredpalmer/formik#700]
Hi

Does anyone have an example of how to use reactjs select with Field Array. I am having trouble clearing the select box via code.

I am not sure if I am clearing the value that was created in the initialization or some other value.

**Comment by sshmyg** [comment]
@chobo2 Do you use multi select or not?

**Comment by reasoning-unhurried33** [comment]
@sshmyg https://firefox-headless-malcolm.github.io/drunken/
