### ISSUE TITLE
How do you render component that is in FieldArray?

### ISSUE THREAD

**Issue by chobo2** [jaredpalmer/formik#701]
Hi

how do you add component rendering in a FieldArray?

How would you take the example code and take out the form area into a component?

```
import React from 'react';
import { Formik, Form, Field, FieldArray } from 'formik';

// Here is an example of a form with an editable list.
// Next to each input are buttons for insert and remove.
// If the list is empty, there is a button to add an item.
export const FriendList = () => (
  <div>
    <h1>Friend List</h1>
    <Formik
      initialValues={{ friends: ['jared', 'ian', 'brent'] }}
      onSubmit={values =>
        setTimeout(() => {
          alert(JSON.stringify(values, null, 2));
        }, 500)
      }
      render={({ values }) => (
        <FieldArray
          name="friends"
          render={arrayHelpers => (
            <Form>
              {values.friends && values.friends.length > 0 ? (
                values.friends.map((friend, index) => (
                  <div>
                    <Field name={`friends.${index}`} />
                    <button
                      type="button"
                      onClick={() => arrayHelpers.remove(index)} // remove a friend from the list
                    >
                      -
                    </button>
                    <button
                      type="button"
                      onClick={() => arrayHelpers.insert(index, '')} // insert an empty string at a position
                    >
                      +
                    </button>
                  </div>
                ))
              ) : (
                <button type="button" onClick={() => arrayHelpers.push('')}>
                  {/* show this when user has removed all friends from the list */}
                  Add a friend
                </button>
              )}
              <div>
                <button type="submit">Submit</button>
              </div>
            </Form>
          )}
        />
      )}
    />
  </div>
);
```

**Comment by IgorJoergensen** [comment]
Why do you have a Form inside a Field?

**Comment by chobo2** [comment]
@IgorJoergensen 

I am not following, this literally is the example on the site: https://github.com/jaredpalmer/formik#fieldarray-

**Comment by greghaygood** [comment]
@chobo2 The example code is indeed a little messed up (I'm gonna submit a PR). Swap the <Form> and <FieldArray> order, then you should be able to separate the components however you need to.

**Comment by chobo2** [comment]
@greghaygood 

Ok, can you let me know when your pull request is accepted.

Thanks

**Comment by greghaygood** [comment]
@chobo2 it's been merged into master already so you can see the updated example on the README: https://github.com/jaredpalmer/formik#fieldarray- 

Good luck!

**Comment by chobo2** [comment]
@greghaygood 

So with way of format I can load a component up? I am still a bit confused as when I look deeper I see still examples of

```
import React from 'react';
import { Formik, Form, Field, FieldArray } from 'formik'


export const FriendList = () => (
  <div>
    <h1>Friend List</h1>
    <Formik
      initialValues={{ friends: ['jared', 'ian', 'brent'] }}
      onSubmit={...}
      render={formikProps => (
        <FieldArray
          name="friends"
          component={MyDynamicForm}
        />
    />
  </div>
);


// In addition to the array helpers, Formik state and helpers
// (values, touched, setXXX, etc) are provided through a `form`
// prop
export const MyDynamicForm = ({
  move, swap, push, insert, unshift, pop, form
}) => (
 <Form>
  {/**  whatever you need to do */}
 </Form>
);
```

**Comment by IgorJoergensen** [comment]
@chobo2 I did not know the example was messed up - just looked at it now and looks like ok

@jaredpalmer I am guessing my idea about array/object/null handling baked into formik was a no go?

For me it makes sense to normalise those as strings when used inside render prop of formik, and return as parsed when used outside.

No need to obscufate things with a special FieldArray... just my 2 cents

**Comment by jaredpalmer** [comment]
@IgorJoergensen not sure what you mean. 

FieldArray adds helper methods for manipulating arrays and arrays with nested objects. You can implement these in userland, but it is somewhat annoying to do. That's FieldArray exists. Where you actually place FieldArray above or below Form is completely inconsequential to the functionality you get--you just need it above the Field / inputs / buttons that need to call FieldArray's render prop methods.
