### ISSUE TITLE
setFieldError is overwritten when using the validation methods.

### ISSUE THREAD

**Issue by chuckconway** [jaredpalmer/formik#706]
I've been beating my head against the wall on this one. I dug into the formik source and finally figured out what was going on. I'm writing to document what I found. Hopefully it'll help someone else. This also might be a bug. If it is, then sweet. I found a bug. 

**Problem**
The problem was in a custom component I was using the `SetFieldValue` and `SetFieldError`. Each of these methods take a field name. SetFieldValue's second parameter is the value, SetFieldError's second parameter is the error message.

```javascript
setFieldValue('birth', value)
setFieldError('birth', value.error);
```

There are other elements on the form that are validated with yupjs. 

I found when using `setFieldError`, you can't use the `validate` or the `validateSchema`  functions defined in the `withFormik` method configuration. Both the `validate` and the `validateScheme` overwrite the error collection.

```javascript
  /**
   * Run validation against a Yup schema and optionally run a function if successful
   */
  runValidationSchema = (values: FormikValues, onSuccess?: Function) => {
    const { validationSchema } = this.props;
    const schema = isFunction(validationSchema)
      ? validationSchema()
      : validationSchema;
    validateYupSchema(values, schema).then(
      () => {
        this.setState({ errors: {} });
        if (onSuccess) {
          onSuccess();
        }
      },
      (err: any) =>
        this.setState({ errors: yupToFormErrors(err), isSubmitting: false })
    );
  };
```

It happens in the error function where the state is set: `this.setState({ errors: yupToFormErrors(err), isSubmitting: false })` .

For example, if I created a custom control called ImpreciseDateControl and wanted to set an error onBlur like below:

```javascript
<ImpreciseDateControl
    onChange={value => setFieldValue('birth', value)}
    onBlur={value => {
        setFieldTouched('birth', true);
        setFieldError('birth', value.error);
        }
    }
    label="Birth"
    value={values.birth || {}}
/>
```

Even though I set the setFieldError for the birth field, it will be wiped out by one of the validation methods.

A possible solution is to pass the error collection into the validate methods, but this would require a change to the Formik code. This way the consumer would have the option to preserve all or selected errors.

**Comment by jaredpalmer** [comment]
You can tell setFieldValue not to run validation by passing third parameter as `false`.

**Comment by MDornian** [comment]
Setting the third parameter of setFieldValue to false seems to have no effect.  There must be something else in play to make this work.

**Comment by jaredpalmer** [comment]
You cannot use `handleChange` or `handleBlur` to get this specific behavior. YOu need to manually handle both blur and change with setFieldValue and and setFieldTouched. You'll need to also pass the third argument (i.e. `shouldValidate`) to each as `false`.


```js
handleChangeSpecial = (e) {
   setFieldValue(props.name, e.target.value, false);
   setFieldError(props.name, 'shoot');
}

handleBlurSpecial = () => {
   setFieldTouched(props.name, true, false);
   setFieldError(props.name, 'shoot');
}```

YOu can also just pass in a `validateProp`

**Comment by ivona21** [comment]
If you use _validate_ property on field for validation (and not i.e. _onChange_), field validation won't be overwritten by validation schema.

**Comment by nilamsavani91** [comment]
@jaredpalmer

```
 const handleStartDateChange = date => {
 setFieldValue('startDate', date, false);
    if (date !== null && isNaN(Date.parse(date)) === true) {
      setFieldError('startDate', 'Invalid date');
    } 
  };

const handleStartDateBlurChange = date => {    
    setFieldTouched('startDate', true, false);
    if (date !== null && isNaN(Date.parse(date)) === true) {
      setFieldError('startDate', 'Invalid date');
    } 
  };
```

I am using KeyboardDatePicker of material-ui picker so I want to disable my submit button when user types date in the control. On change event, I am checking whether date is valid or not and then setting the error using setFieldError. 

The problem I am facing is that if user types incorrect date (i.e 99/99/9999) my button is disabled but after that user clears the date and type the correct date then also it is disabled as the error set by previous wrong input is still there. How can I clear/reset the error?

**Comment by kennylbj** [comment]
Maybe the acceptable workaound is to move the error validation function from custom component to formik's validate handler, As far as I know.

**Comment by Gregory-Canonne** [comment]
touched from form is best way, dont' use onBlur....

**Comment by asadkhalid305** [comment]
> You cannot use `handleChange` or `handleBlur` to get this specific behavior. YOu need to manually handle both blur and change with setFieldValue and and setFieldTouched. You'll need to also pass the third argument (i.e. `shouldValidate`) to each as `false`.
> 
> ```js
> handleChangeSpecial = (e) {
>    setFieldValue(props.name, e.target.value, false);
>    setFieldError(props.name, 'shoot');
> }
> 
> handleBlurSpecial = () => {
>    setFieldTouched(props.name, true, false);
>    setFieldError(props.name, 'shoot');
> }```
> 
> YOu can also just pass in a `validateProp`
> ```

Worked for me!

**Comment by rhdhvolschenk** [comment]
This is still an issue.

The original issue post specifically mentions two things:
* A field that is validated manually, and said error is added to `formik` through `setFieldError`.
* Other fields in the form which use the `validationSchema` through `yup`.

The issue can be reproduced as follows:
1. Type an invalid value in the field which is manually validated.
    1. Observe that said field now displays an error.
1. Type in any other field which is validated through the `validationSchema`.
    1. Observe that the manually validated field now shows no error as it is gone.

I have created a workaround where the error is manually stored
and then added to the list of errors created by `validationSchema`.

The reproduction (and workaround) can be seen here:
https://codesandbox.io/p/sandbox/formik-validation-manual-with-validationschema-mhjrk7
