### ISSUE TITLE
Error when using withFormik with enzyme

### ISSUE THREAD

**Issue by mtnori** [jaredpalmer/formik#719]
**Describe the bug**
Error when using withFormik with enzyme

**To Reproduce**
1. git clone https://github.com/mtnori/formik-enzyme-issue.git
1. cd formik-enzyme-issue
1. npm i
1. npm run test
1. Error is produced

**Expected behavior**
successful tests

---
- Formik Version: 1.0.0-beta.3
- React Version: 16.4.1
- OS: Windows 10
- Node Version: 8.11.1
- Package Manager and Version: npm 6.1.0

**Comment by JustusFT** [comment]
Hi, I also been ran into this issue. I get the error `Enzyme Internal Error: unknown node with tag 13`. It happens whenever I try `mount` a component that has formik in it. It seems that the current version of enzyme is missing a tag type that formik is using. See their issue https://github.com/airbnb/enzyme/issues/1509

There's a fix there but it isn't released yet. But you can add it now with https://github.com/airbnb/enzyme/pull/1513#issuecomment-397128309
```
yarn add --dev enzyme-adapter-react-16@npm:enzyme-react-adapter-future
```
After running this command, your example works fine for me. Hope this helps!

**Comment by mtnori** [comment]
@JustusFT It work fine with your solution, Thanks.
