### ISSUE TITLE
Question about (possibly?) redundant expression

### ISSUE THREAD

**Issue by zchsh** [jaredpalmer/formik#72]
Hey!

Just had a question about Boolean handling in one of your demos, the [Building your own input primitives](https://codesandbox.io/s/RgVMg8GnK).
This might be a more general Javascript question, but in the demo on line `117` you've got:

````jsx
error={errors.email && touched.email && errors.email}
````

Just wondering whether that's the same thing as this:

````jsx
error={touched.email && errors.email}
````

Seems like it is, [as far as I can tell](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators), but wanted to see what you thought?

**Comment by eonwhite** [comment]
Our mistake, will fix.
