### ISSUE TITLE
Typescript 2.9 generated declaration types have wrong import path

### ISSUE THREAD

**Issue by romainquellec** [jaredpalmer/formik#720]
With formik beta-3, got an error like this one : 
```
/frontend/node_modules/formik/dist/connect.d.ts
(3,59): Cannot find module '../node_modules/create-react-context/lib/index'.

/frontend/node_modules/formik/dist/connect.d.ts
(3,189): Cannot find module '../node_modules/create-react-context/lib/index'.
```
- Formik Version:1.0.0-beta.3
- React Version:16.4.1
- TypeScript Version:2.9.2
- OS: windows
- Node Version:10.5.0

**Comment by jaredpalmer** [comment]
Can you put together a code sandbox?

**Comment by romainquellec** [comment]
I can't reproduce on sandbox :(
https://codesandbox.io/s/pkqqm3yn80

You can see my current project here : https://github.com/CuistotduCoin/cuistot/tree/master/frontend

I never saw a bug like this. I'm going back to 0.11.11 temporarily.

**Comment by jaredpalmer** [comment]
Just tested 1.0.0-beta.4 in CodeSandbox. Seems fine. Perhaps nuke your node_modules and reinstall?

Reference 1.0.0-beta.4 sandbox here: https://codesandbox.io/s/pwo999nrqx

**Comment by ibrambe** [comment]
```
/projects/demo/node_modules/formik/dist/connect.d.ts
(3,59): Cannot find module '../node_modules/create-react-context/lib/index'.
```
Same issue here with beta 4. Deleted the node_modules as suggested and did a reinstall.

Switching back to 0.11.11 solved it.

**Comment by jaredpalmer** [comment]
What version of React, node, and TS were you using?

**Comment by ibrambe** [comment]
Application is bootstrapped with Facebook's create-react-app.

`node -v`
* v7.2.1

`npm -v`
* 5.6.0

`npm list --depth 0`
* @types/jest@23.1.4
* @types/node@10.5.1
* @types/react@16.4.6
* @types/react-dom@16.0.6
* @types/react-redux@6.0.3
* @types/react-router-dom@4.2.7
* @types/yup@0.24.7
* formik@1.0.0-beta.4
* json-server@0.14.0
* node-pre-gyp@0.10.2 extraneous
* npm-run-all@4.1.3
* react@16.4.1
* react-dom@16.4.1
* react-redux@5.0.7
* react-router-dom@4.3.1
* react-scripts-ts@2.16.0
* redux@4.0.0
* redux-saga@0.16.0
* typesafe-actions@2.0.4
* typescript@2.9.2
* yup@0.25.1

**Comment by mknapik** [comment]
I run into the same error.
React: `16.4.1`
TypeScript: `2.9.2`
Node: `9.11.1`
Formik: `1.0.0-beta.4`

**Comment by kimochg** [comment]
ran into the same issue.

-   typescript  2.9.2
-   node 8.1.1
-   npm 6.1.0
-  "formik": "^1.0.0-beta.5"
-  "react": "^16.4.1"

![image](https://user-images.githubusercontent.com/16147702/42450492-eb7bb6d6-83b6-11e8-9556-539648281320.png)

I can fix it by removing `../node_module/`, but I can hardly find where `connect.d.ts` comes from in this code base.

**Comment by jaredpalmer** [comment]
Hrmmm. Let me bump to TS 2.9.2 on master and see if i can reproduce?

**Comment by jaredpalmer** [comment]
Maybe this has to do with imported types?

**Comment by jaredpalmer** [comment]
It seems this is a typescript bug.

See https://github.com/Microsoft/TypeScript/issues/25511

Version 3.0 drops very soon. Hopefully, this fixes this bug.

**Comment by jaredpalmer** [comment]
Try 1.0.0-beta.8. This should be fixed now.

**Comment by romainquellec** [comment]
Fixed for me.

**Comment by vabhishek-me** [comment]
I'm getting the same error.
```
node_modules/formik/dist/connect.d.ts
(3,66): Cannot find module 'create-react-context'.
```

Using `typescript@3.2.1`, `formik@1.3.2`.

**Comment by jaredpalmer** [comment]
@mSpolsky what are you using to build? create react app?

**Comment by mSpolsky** [comment]
@jaredpalmer No, I am using tsc. Actually, it took me quite some time to find the source of the problem. In the end, it turned out that version 1.3.2 is not working for some other reason related to incorrect typedefs. I had to downgrade to make it work.

**Comment by jaredpalmer** [comment]
what version of TS are you using @mSpolsky ? There is one that broken formik

**Comment by flushentitypacket** [comment]
@gunn4r This fixed it for me as well. I'm baffled as to why.

**Comment by gunn4r** [comment]
I haven't look really but I would assume that the plan is to remove the need for this dep since reacts release version of the context api has been out for awhile now.

**Comment by menix** [comment]
Got this one time to time when app run

```
/home/....../node_modules/formik/dist/connect.d.ts
(3,66): Cannot find module 'create-react-context'.
```
Formik 1.5.1, Typescript: 3.3.4000, React 16.8.5, Create React App on Ubuntu 18.04.2

**Comment by kaueDM** [comment]
@mSpolsky you saved my day. I'm trying to build without `create-react-app` and your comment solved the problem.

Thanks.

**Comment by taygrave** [comment]
Still having a problem, not using typescript, see: https://github.com/jaredpalmer/formik/issues/1337#issuecomment-486864870
