### ISSUE TITLE
iOS Chrome email autofill isn't working

### ISSUE THREAD

**Issue by melanieseltzer** [jaredpalmer/formik#721]
**Describe the bug**
In Chrome on iPhone, nothing happens when tapping the suggested email and the validation error returns (invalid email address).

It's working fine in Chrome on Macbook, bug is only happening on phone. Don't have Android so unsure if it carries over there.

**To Reproduce**
Open this in Chrome on iPhone, and trigger an email to show an autofill suggestion: https://stoic-jang-75a2ec.netlify.com/

**Expected behavior**
Autofill should work and the address should be appended to the input.

**Suggested solution(s)**
Not sure

**Additional context**
[Repo](https://github.com/melanieseltzer/grabatar)

GIF of bug:
![bug](https://user-images.githubusercontent.com/17421347/42127884-f8535760-7c54-11e8-9d43-251f194024af.gif)

---

- Formik Version: 0.11.11
- React Version: 16.4.1
- TypeScript Version: n/a
- CodeSandbox Link: Let me know if I need to provide this
- OS: iOS 11.4
- Node Version: v9.6.1
- Package Manager and Version: npm v6.1.0

**Comment by weyert** [comment]
I am wondering if using `autocomplete`-attribute as listed here: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill

Would improve the behaviour?

**Comment by weyert** [comment]
You might want to check whether `touched`-state of that field changes after selecting the email address or whether it triggers an onChange so that the form gets validated again

**Comment by jaredpalmer** [comment]
Similar to #725

**Comment by crosscompile** [comment]
I think this might be related to https://github.com/facebook/react/issues/1159.  There are a couple workarounds mentioned in that thread depending on your use case.

**Comment by jaredpalmer** [comment]
This is a manifestation of [facebook/react#1159](https://github.com/facebook/react/issues/1159).
