### ISSUE TITLE
Chrome autofill on password input issue

### ISSUE THREAD

**Issue by Sklico** [jaredpalmer/formik#725]
Hi, I have a problem with autofill on my password input. I use HOC withFormik. When I access the page, chrome fills my last login e-mail and password. This is completely fine. But, when I try to edit password input and start typing, after first change the input value is reset to the remembered password. There are exactly two change events, one with my new value and the second one with the old autofilled value and it rewrites my change. After that, any change is fine, there is only one change event and I can edit the input value. Could anyone help me with this?

**Comment by jaredpalmer** [comment]
Are you using mapPropsToValues in your form?

**Comment by Sklico** [comment]
Yeah, of course.
`mapPropsToValues: () => ({ email: '', password: '', showPassword: false }),`

I'm not really sure if this issue is duplicate to the iOS Chrome autofill issue. I think I have little bit different problem, which has nothing common with iOS or that autofill doesn't work. Chrome autofill works in my form, but for unknown reason, there are two change events in first attempt of change my password input value. The only common thing is Chrome autofill. If it is the reason for duplicate label, then ok, I'm sorry for create duplicity.

**Comment by jaredpalmer** [comment]
The reason for double events is the change (values) and validation (touched) are firing off. Can you create a codesandbox so I can take a look?

**Comment by Sklico** [comment]
Yeah, sure - https://codesandbox.io/s/yp8wwrvq1z

I have the same problem in codesandbox, so hopefully, you can see the issue.

**Comment by Sklico** [comment]
@jaredpalmer Hi, can I ask you, if there is any progress in this issue ? Thanks

**Comment by chamupathiBlimpIT** [comment]
+1 any updates on this?

**Comment by dVenturousDani** [comment]
Is this a problem with the HOC implementation only?

**Comment by Sklico** [comment]
@jaredpalmer hey man, I think that "stale" label is a mistake here, because I'm still waiting for your response to my issue. I still have this issue and I still need help with that. Thanks

**Comment by intelligentspark** [comment]
+1 this issue!

**Comment by daveycakes** [comment]
I think I'm seeing the same issue when LastPass is used to generate a password in an editing form.

**Comment by jaredpalmer** [comment]
We fixed this internally on one of our forms. Will get our hacky workaround out of source now.

**Comment by jaredpalmer** [comment]
This is unfortunately an upstream React issue: https://github.com/facebook/react/issues/1159

FWIW our hacky workaround solution adds an event listener to the each ref. Also note, that we actually are not even using Formik on this form.  

```js
 email = React.createRef<HTMLInputElement>();
 password = React.createRef<HTMLInputElement>();

 componentDidMount() {
    // Temporary fix for https://github.com/facebook/react/issues/1159
    this.email.current!.addEventListener('change', this.handleChange);
    this.password.current!.addEventListener('change', this.handleChange);
  }
``

**Comment by jaredpalmer** [comment]
Going to close this this issue as this is not a Formik bug.

**Comment by nrsdnitin** [comment]
use below code as a prop to <Field component

`inputProps={{

autocomplete: 'password',

form: {

autocomplete: 'off',

},

}}`

**Comment by tripolskypetr** [comment]
Looks like all these methods with `autofill` prop are simple ignored by Google Chrome since 2022. I suggest a different method: using `readOnly={true}` until focus event

> Keep in mind that on mobile safari keyboard will not shown if input field change readonly state after focus event, so you need to process `onTouchStart` too. Heres the link to [the source code of `usePreventAutofill` hook](https://github.com/react-declarative/react-declarative/blob/51f4c29897297233e5c958de782b6af4e7b41cf5/src/hooks/usePreventAutofill.ts#L19)

```tsx
import { usePreventAutofill } from 'react-declarative';

...

const preventAutofill = usePreventAutofill();

...

return (
  <InputBase

      ...

      {...preventAutofill}
  />   
);
 
```

**Comment by YakovSPb** [comment]
Почему при переключение isPasswordVisible в chome пустое поле если автозаполнение?

                    
                    
                    <TextField
                                autoComplete="on"
                                data-testid="password"
                                formik={formik}
                                name='password'
                                id='password'
                                placeholder={t.passwordLabel}
                                type={isPasswordVisible ? 'text' : 'password'}
                                variant="outlined"
                                className={clsx(classes.inputStyle, formik.errors.password && classes.inputStyleError)}
                                showClearButton={false}
                                errorProps={{
                                  className: 'absolute -bottom-6 whitespace-nowrap'
                                }}
                                InputProps={{
                                  className: classes.textField,
                                  endAdornment:
                                      formik.errors.password  ? (
                                          <MuiBox className={classes.errorIcon}>
                                            <img src={ErrorIcon} alt="ErrorIcon" />
                                          </MuiBox>
                                      ) : (
                                          formik.values.password && (
                                              <MuiInputAdornment position="end">
                                                <MuiIconButton
                                                    aria-label="toggle password visibility"
                                                    disabled={isLoading}
                                                    onClick={() =>
                                                        setPasswordVisible(
                                                            !isPasswordVisible,
                                                        )
                                                    }
                                                    // onMouseDown={(e) =>
                                                    //     e.preventDefault()
                                                    // }
                                                    className={classes.buttonIconBlock}
                                                >
                                                  <PasswordIcon
                                                      className={classes.passwordIcon}
                                                  />
                                                </MuiIconButton>
                                              </MuiInputAdornment>
                                          )
                                      ),
                                }}
                            />
