### ISSUE TITLE
`isSubmitting` always true

### ISSUE THREAD

**Issue by Andreyco** [jaredpalmer/formik#739]
## Current Behavior
After form is submitted, `isSubmitting` is not set to false

## Steps to Reproduce
Submit form

## Expected behavior
`isSubmitting` should be set to false

**CodeSandbox Link**:
https://codesandbox.io/s/vqjmnkvjn7

## Note
This should be already fixed in #736, this issue is a placeholder so that I don't forget about it

---

- Formik Version: 1.0.0-beta.4

**Comment by jaredpalmer** [comment]
Will cut a release

**Comment by jaredpalmer** [comment]
Fixed in beta.5

**Comment by Andreyco** [comment]
Awesome!

**Comment by kerwynrg** [comment]
Still an issue
Formik Version: 1.4.2

**Comment by ckreiling** [comment]
+1 here, seeing the same issue

Formik version: 1.4.0

**Comment by Badbreaddead** [comment]
+1 here, seeing the same issue

Formik version: 1.5.0

**Comment by stephane-r** [comment]
Same on last version

**Comment by jaredpalmer** [comment]
????? https://codesandbox.io/s/5238o7633l

**Comment by ls-chloe-schoreisz** [comment]
+1 still an issue. Had to add a prop to check how many errors did I receive

**Comment by ahtashamabbasse** [comment]
+1 still an issue Hotfix
```
onSubmit={(values, actions) => {
        setTimeout(() => {
          alert(JSON.stringify(values));
          // you have to clean up 
          actions.setSubmitting(false);
        }, 500);
      }}
```

**Comment by johnrom** [comment]
@ahtashamabbasse `setSubmitting(false)` is required when not using async/promises. If you don't want to use setSubmitting, you can return a promise or use an async function. Without this requirement, Formik would never know when your timeout was complete, and would `setSubmitting(false)` immediately.

```tsx
<Formik onSubmit={values => 
    new Promise(resolve => 
        setTimeout(() => {
            alert(JSON.stringify(values));
            resolve();
        }, 500);
} />
```

**Comment by dpikt** [comment]
This seems like a surprising default- I would've expected it to set `isSubmitting` to `false` immediately if supplying a synchronous function.

**Comment by johnrom** [comment]
@dpikt agreed, should probably change it in a future major version. It seems like a backwards compatibility thing.

**Comment by adarshaacharya** [comment]
Still problem in version 2.1.4.

It works when I use async await.

```
  onSubmit={async values => {
        await new Promise(resolve => setTimeout(resolve, 500));
        console.log(values)
      }}
```

but doesn't work on callback.

```
      onSubmit={values => {
        setTimeout(() => {
          console.log(values)
        }, 500);
      }}
```

**Comment by linhtv97** [comment]
+1 version 2.1.5

**Comment by marcustut** [comment]
+1 version 2.2.6

when I use async await, it works just fine.

when I use callbacks such as .then(), it doesn't.

**Comment by johnrom** [comment]
@marcustut you have to return your Promise

```
// submit will complete after ~4 seconds with isSubmitting true the whole time
const onSubmit = () => {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, 2000);
  }).then(() => {
    return new Promise((resolve, reject) => {
      setTimeout(resolve, 2000);
    }
  });
}
```

**Comment by spanwair** [comment]
with React and Typescript
```
const handleSubmit = (
    values: Values,
    { setSubmitting }: { setSubmitting: (isSubmitting: boolean) => void },
  ): void => {
    .... // any logic
    setSubmitting(false);
  };
 ```
