### ISSUE TITLE
Improve form-level along with field-level validators

### ISSUE THREAD

**Issue by stomvi** [jaredpalmer/formik#748]
## Current Behavior
Async validators will overwrite the sync validation result. This make it hard to mix sync, async form-level and field-level validators.

## Desired Behavior
Sync and async validation results will be merged in order to to display the final errors. Or somehow we can get the current validation cycle result whether it's from the form-level or field-level. Let user decide to go further validating or not.

## Suggested Solution
Respectively, auto merge the errors or pass the validation results as one of the arguments to the validation functions.

## Who does this impact? Who is this for?
All users.

## Describe alternatives you've considered
Like the `redux-form`, use selectors to get `syncErrors`, `asyncErrors`, `submitErrors` or just use the errors prop to get all the merged errors. Passing errors, e.g. `formErrors` and `fieldErros`, as props into the `Formik` wrapped component is an alternative solution.

## Additional context
Fields in any registration form like `username`, `email` always needs to be checked sync and async. In the context of the current limitation: a form or field `validate` only accept function that returns either errors or a promise and no easy way to get onBlur info to determine where to do async check which `redux-form` solved this by `asyncBlurFields`, it's likely the async uniqueness check of a `username` field has to be run on every keystroke using `Formik`.

https://github.com/jaredpalmer/formik/blob/master/docs/api.md#validate-values-values--formikerrorsvalues--promiseany
https://github.com/jaredpalmer/formik/blob/master/docs/api.md#validate-value-any--undefined--string--promiseany

**Comment by Virgomax** [comment]
I think it would be useful if in the documentation had a section especially for people who come with a redux-form background. Maybe an equivalency table of the components and props.

**Comment by jasonlimantoro** [comment]
This is a must-have feature for Formik.

I find it hard to do asynchronous validation *only* after the synchronous validation passes without creating a separate Component state, which is nothing but to keep track whether or not the synchronous validation passes (and therefore the asynchronous validation should start)
