### ISSUE TITLE
withFormik initialValues not working

### ISSUE THREAD

**Issue by pmonty** [jaredpalmer/formik#749]
**Current Behavior**
My form loads but the `mapPropsToValues` (or initialValues) don't appear despite my console.log actually showing that the profile object is filled out (some values are null which is fine).

![image](https://user-images.githubusercontent.com/7111292/42432138-801cc95e-838c-11e8-8997-1769607e591c.png)

Not to sure if it is my props typings that is the issue? 

**Expected behavior**
Basically the form should look like so:
![image](https://user-images.githubusercontent.com/7111292/42432130-7353c9fc-838c-11e8-9ae7-aebcceca638c.png)

**Additional context**
[My gist (withFormik.tsx)](https://gist.github.com/pmonty/7950616c541a2069b6252d01565e1996)

- Formik Version: 0.11.11
- React Version: 16.2
- TypeScript Version: 2.7.2
- Browser and Version: Chrome@latest
- OS: MacOS
- Node Version: 10.4.1
- Package Manager and Version: yarn 1.7.0

**Comment by jaredpalmer** [comment]
I think so. You need to be careful with enableReinitialize and mobx/redux and make sure you are only supplying exactly the props formik needs. Otherwise, your form will reset when an unwanted prop changes (even if you are not using it in your form).

**Comment by pmonty** [comment]
Yeh sounds like I might need to only render the form once my mobx store is loaded with data so the initialValues are set then I am using the <Formik component /> which is a little more verbose in ways but works well. Will give it a shot thanks.
