### ISSUE TITLE
Displaying all error at the same time for one field

### ISSUE THREAD

**Issue by ScreamZ** [jaredpalmer/formik#750]
Hello
I'm having an error field in my form with yup validation scheme.
Currently i'm getting only one validation error at time of my 3 rules for my field.
I would like to know if there is a way to get each validation state of my fields state at the same time
I need to design an interface which shows three checkmarks when condition is met

```js
password: Yup.string()
    .min(8, 'At least 8 chars required')
    .required('Field is required')
    .test('is-matching-password-requirements', 'Should match requirements (one number and one letter)', value => {
      if (!value) return false
      // at least one number but not only numbers
      return /\d/.test(value) && /\D/.test(value)
    }),
```
I need to display validation errors for each of those rules at the same time
Anyone knows ? Thank you in advance

**Comment by Andreyco** [comment]
Change yup-errors-to-formik transform function and return array of error messages. Then render them for each affected field. 

If you post similar issues it is always good idea to create codesanbox sample

**Comment by ScreamZ** [comment]
@Andreyco You mean I must override the library ? I don't get it where I'm supposed to do this ?

**Comment by ScreamZ** [comment]
@Andreyco I get that this is related to, seems already… : https://github.com/jaredpalmer/formik/blob/f3c3157f8aef3996ec081418d2ab28d95b7bd573/src/Formik.tsx#L618

The thing is that this is scoped internally, there is no way to override, am I wrong ?

**Comment by jaredpalmer** [comment]
Not particularly. I forgot why we did this. I think to make things easier. If you want to keep all your yup errors, you can do so with just `validate`

**Comment by ScreamZ** [comment]
@jaredpalmer That's what I've done, thanks.

Seems it was related to Yup following parameter.

```js
{
            abortEarly: false
}
```

That stop validation upon encountering the first mismatch.

Thanks for answering.
Have a nice day,
Regards

**Comment by gaspardip** [comment]
In my opinion, the `errors` prop in `render()` should not be `string[]` but `{ [string]: string; }`, so I could check for each error individually, kinda like how Angular does it with [Reactive Forms](https://angular.io/guide/form-validation). Each object key would be equal to Yup's method name, e.g. Yup's `min()` should produce an `errors.min` key in Formik's `errors`.

@jaredpalmer thoughts on this?

**Comment by foucdeg** [comment]
@gaspardip I have multiple `.matches()` constraints on my field, so that format wouldn't work in my case. However it could be an array of errors in the same order as the criteria.
