### ISSUE TITLE
Access FieldArray imperatively

### ISSUE THREAD

**Issue by casperOne** [jaredpalmer/formik#754]
Is there a way to get the API object exposed by the render method of the `FieldArray` component imperatively?

I have an adapter on top of Formik which exposes array helpers as well, so I don't want to rely on provider specific components as a prerequisite.

**Comment by jaredpalmer** [comment]
If I understand correctly, you want FieldArray to pass down its [`updateArrayField` method](https://github.com/jaredpalmer/formik/blob/master/src/FieldArray.tsx#L97-L124) which takes a function, runs it, and then orchestrates the validation?

**Comment by casperOne** [comment]
@jaredpalmer Thanks for the response, apologies though, I don't think I explained what I am looking for correctly.

Currently, if I want to access [the `ahttps://github.com/jaredpalmer/formik#render-arrayhelpers-arrayhelpers--reactreactnoderrayHelpers` exposed by the `render` prop of the `FieldArray` imperatively.](url).

So instead of doing this:

````
<FieldArray
    name='arrayProperty'
    render={
        arrayHelpers => {
            // arrayHelpers is a set of helpers on the array exposed by 
            // 'arrayProperty' in the data model.
        }
    }
/>
````

Instead, I'd like to call some sort of function (maybe something off the `render` property exposed by the `Formik` component, or a global function) which will give me the helper exposed above in `arrayHelper`.

For example:

````
<Formik
    ...
    render={
        formApi => {
            // Render stuff.
            ...

            // Get array helper from global function...
            const arrayPropertyHelper = getArrayHelper('arrayProperty')
           
            // or something hanging off formApi
            const arrayPropertyHelper = formApi.getArrayHelper('arrayProperty')

            // Call methods on arrayPropertyHelper
            arrayPropertyHelper.insert(0, 'hello')
            arrayPropertyHelper.remove(0)
        }
    }
/>
````
Ultimately, I have an adapter over `formApi`  above which is exposed by a context (to prevent excessive prop drilling); the adapter interface has array operations as well.  I'd like to prevent provider-specific constructs (in this case, the `FieldArray` component) from being used.

**Comment by jaredpalmer** [comment]
Yeah FieldArray is kind of useless I guess. We could curry like you described. Hrmmm.

**Comment by jaredpalmer** [comment]
Need to think about this one for a bit. I like this a lot.

**Comment by casperOne** [comment]
@jaredpalmer A curried option would work, but if it's simpler to expose the object returned in the `render` property of the `FieldArray` component, that would certainly be a solid base, IMO.

**Comment by olivergrimes** [comment]
Hello, was anything done to make the following example possible?  Or is it safe to simply expand the scope of `FieldArray` to expose `arrayHelpers` to the desired components - even if it eats up existing non-array fields?

Desired functionality taken from @casperOne 's example:
```
<Formik
    ...
    render={
        formApi => {
            // Render stuff.
            ...

            // Get array helper from global function...
            const arrayPropertyHelper = getArrayHelper('arrayProperty')
           
            // or something hanging off formApi
            const arrayPropertyHelper = formApi.getArrayHelper('arrayProperty')

            // Call methods on arrayPropertyHelper
            arrayPropertyHelper.insert(0, 'hello')
            arrayPropertyHelper.remove(0)
        }
    }
/>
```

**Comment by olivergrimes** [comment]
Just coming back to this and expanding the scope isn't suitable for my use case - would be great if we could access `arrayHelpers` from `FormikProps`.
