### ISSUE TITLE
isSubmitting value doesn't change when submitting

### ISSUE THREAD

**Issue by rwinzhang** [jaredpalmer/formik#755]
## Current Behavior

isSubmitting value doesn't change when submitting
## Steps to Reproduce

Just normal setup, the behavior is ok on version 1.0.0-beta.4
## Expected behavior

isSubmitting value should change to true when submitting

**CodeSandbox Link**:
https://codesandbox.io/s/mmy2j3vo78
---

- Formik Version: 1.0.0-beta.5
- React Version: 16.4.1
- TypeScript Version:
- Browser and Version:
- OS: 
- Node Version: 8.11.3
- Package Manager and Version: yarn 1.7.0

**Comment by jaredpalmer** [comment]
Thanks. I saw this yesterday and forgot to patch. Thanks!

**Comment by jlurena** [comment]
I'm seeing this issue in 1.5.8
