### ISSUE TITLE
add set ou update validation schema on formikBag

### ISSUE THREAD

**Issue by itelo** [jaredpalmer/formik#758]
## Current Behavior
validationSchema can be defined only in the beginning 

## Desired Behavior
I want to add new rules to validation schemas, currently, I am using Yup. I want this feature to make sure that the user changed the input. For example, in the signup page the email validation is:

`yup.string().email("Invalid Email Address").required("Required"),`

then, if the user tried to sign up but the email has already taken, will give a message error like "email address already taken", so I set this message with setErrors, but with the user just delete one character and put them again, the message will disappear. What I want is to update the validationSchema to: 

`yup.string().email("Invalid Email Address").required("Required").string.matches(someRegex, message: "email address already taken")`

## Suggested Solution
put a method in formikBag to set validationSchema, then we can use it at handleSubmit, A possible function below:

```js
const email = yup
    .string()
    .email("Invalid Email Address")
    .required("Required")
const schema = {
  email
};
const SignUpSchema = yup.object().shape(schema)

// inside withFormik
handleSubmit: (values, formikBag) => {
  const { updateValidationSchema } = formikBag;
  const newSignUpSchema({
     ...schema,
      email: 
        email..string.matches(someRegex, message: "email address already taken") 
  }); 
  updateValidationSchema(newSignUpSchema);
}
```

## Who does this impact? Who is this for?
Everyone who uses validationSchema

And finally, thanks to everyone involved in this project.

**Comment by stelioschar** [comment]
@itelo did you finally manage to find a good solution to handle this case?

**Comment by itelo** [comment]
Hey @stelioschar, In my case I ended up saving the email in an array inside the state, and before submitting again checking if the email changed or if it is in the array I mentioned before.
