### ISSUE TITLE
`isSubmitting` doesn't reset when there are validation errors

### ISSUE THREAD

**Issue by taktran** [jaredpalmer/formik#759]
## Current Behavior

Trying out the basic formik form at https://codesandbox.io/s/x3x26mw4kz, and when you submit the form with errors, the button stays disabled. There is no way to recover from this apart from refreshing the page.

<img width="961" alt="screen shot 2018-07-12 at 16 28 24" src="https://user-images.githubusercontent.com/79451/42643375-e59c3c9a-85f0-11e8-8779-c57b0db15e21.png">

Trying on the latest formik (`1.0.0-beta.9`). This seems to work on `0.10.5`, on the original link from the readme (https://codesandbox.io/s/zKrK5YLDZ)

## Steps to Reproduce

1. Go to https://codesandbox.io/s/x3x26mw4kz
1. Click on the Submit button
1. Email error is shown and submit button is disabled

## Expected behavior

Submit button should be enabled after submission with error, ie, `isSubmitting` is false after submitting when there are errors

## Suggested solution(s)

After validation, `isSubmitting` should be set to false again ie, `setSubmitting(false);`

## Additional context

**CodeSandbox Link**: https://codesandbox.io/s/x3x26mw4kz, based on the basic form from the readme at https://codesandbox.io/s/zKrK5YLDZ, but with version of formik changed to `1.0.0-beta.9`

---

- Formik Version: `1.0.0-beta.9`
- React Version: `15.6.1`
- TypeScript Version:
- Browser and Version: Chrome 67.0.3396.99
- OS: MacOSX 
- Node Version:
- Package Manager and Version:

**Comment by jaredpalmer** [comment]
Just fixed this. Thanks for the catch. I would cut a release, but NPM is down right now. WHAT A DAY!

**Comment by zachhale** [comment]
Thanks for the quick fix on this!
