### ISSUE TITLE
handleSubmit is never called in React native app

### ISSUE THREAD

**Issue by wbasmi** [jaredpalmer/formik#761]
## Current Behavior
withFormik handleSubmit is never called in React native project
## Steps to Reproduce

This is the button that triggers the handleSubmit (a wrapper of TouchableOpacity)
```js
<Button
   style={styles.submit(isSubmitting && !isValidating)}
   text="ANMELDEN"
   disabled={isSubmitting && !isValidating}
   onClick={handleSubmit}
/>
```

This is my form:
```js
const FormikSignin = withFormik({
  handleSubmit: (values, { setSubmitting }) => {
    alert('should be triggered');
  },
  mapPropsToValues: (props) => ({ email: 'something@mail.com', password: 'password' }),
  validate,
})(Signin);

export default class SigninScreen extends React.Component {
  
  static navigationOptions = {
    headerTitle: <TitleHeader title="ANMELDUNG" />,
    headerRight: <View />
  };

  render() {
    return (
      <FormikSignin />
    );
  }
}

```
## Expected behavior
an alert box should appear containing "should be triggered".

---

- Formik Version: 1.0.0-beta-10
- React Version: 16.3.1
- TypeScript Version:
- Browser and Version:
- OS: 
- Node Version: 8.10.0
- Package Manager and Version: npm 5.6.0

**Comment by wbasmi** [comment]
I solved the issue, in fact, I was always returning an errors object like this when there are no errors:
```js
{ username: {}, password: {} }
```
Whereas the errors object should be an empty object:
```js
{}
```
I suggest to update the documentation, thank you for the wonderful library.

**Comment by ali-hassnain** [comment]
onPress={handleSubmit}

use onPress instead of onClick.
