### ISSUE TITLE
Field Typescript type definitions incorrect

### ISSUE THREAD

**Issue by danielwong2268** [jaredpalmer/formik#768]
## Current Behavior
Field props has any type.
```
export declare const Field: React.ComponentClass<any> & {
    WrappedComponent: React.ComponentClass<any>;
};
```

## Expected behavior
Field props should have FieldAttributes type.

---

- Formik Version: 1.0.1
- React Version: 16.4.1
- TypeScript Version: 2.9.2
- Browser and Version: Chrome 67
- OS: OSX
- Node Version: v8.7
- Package Manager and Version: yarn 1.6

**Comment by tgriesser** [comment]
@jaredpalmer I don't believe that TS JSX generics need to be used to get these type definitions correct in the output d.ts though. Using a wrapper component rather than connect as I started doing in #735 should do the trick.
