### ISSUE TITLE
Is <FastField> fully supported now? i don't see documentation for it.

### ISSUE THREAD

**Issue by lvdang** [jaredpalmer/formik#769]
Seriously, for immediate help, just ask your question on the #formik channel on [Reactiflux](https://discordapp.com/invite/MbKwYuq).

**Comment by lvdang** [comment]
@thanks got it

**Comment by yourfavorite** [comment]
Did you end up finding documentation for FastField?

**Comment by lvdang** [comment]
Casey,
 Thanks, I did. I read somewhere that FastField is Field. Appreciate you getting back to me.
- Luan   On Sunday, August 26, 2018, 7:12:28 PM PDT, Casey Britt <notifications@github.com> wrote:  
 
 
Did you end up finding documentation for FastField?
