### ISSUE TITLE
Is it possible to access FieldArray arrayHelpers outside FieldArray render method?

### ISSUE THREAD

**Issue by Okami92** [jaredpalmer/formik#770]
Is it possible to access FieldArray arrayHelpers outside FieldArray render method?

I have a dynamic list of form fields, which can be added and deleted. I implemented it with FieldArray, works as expected, but the button for adding new fields must be outside of render method of this particular FieldArray.

is there a possibility to programmatically get access to the methods of this FieldArray by name for example from outside of FieldArray render method?

I read through documentation, but seems like there is no such use case described. Thank you in advance.

**Comment by yourfavorite** [comment]
@Okami92 I see you closed the issue. I'm having a similar issue. Did you find a solution for this?

**Comment by Okami92** [comment]
Hey. Just render FieldArray inside another FieldArray. Here is example: https://codesandbox.io/s/4z5nkq3ol9

Hope it helps.

**Comment by charlax** [comment]
@Okami92 not sure to understand... You are indeed inside the `FieldArray` `render` method, and you are using the `arrayHelpers` object. 

I'm looking at a similar issue. I presume this is not really possible with formik.

cc @jaredpalmer what would you recommend here?

**Comment by mjbertenburg** [comment]
I am facing this issue as well at the moment. I have got a table with input fields in the rows and I would like to push new items from an api request, but allowing to dismiss them via 
Is there any news on the problem?

**Comment by yh54321** [comment]
> @Okami92 not sure to understand... You are indeed inside the `FieldArray` `render` method, and you are using the `arrayHelpers` object.
> 
> I'm looking at a similar issue. I presume this is not really possible with formik.
> 
> cc @jaredpalmer what would you recommend here?

Ever resolve this?

**Comment by yh54321** [comment]
I faced a similar issue when I wanted a button outside of my FieldArray to add a field to into the FieldArray.
Resolved in the following way:
`onClick={() => {values.MYFIELDARRAY.push({MYFIELDNAME: ""}); setValues(values)}}`

Perhaps there are many good reasons not to resolve in this way, but I don't know about them, so I'll pretend they don't exist.

**Comment by j0b0sapi3n** [comment]
Was this ever solved? I'm trying to use arrayHelpers.insert outside of FieldArray render method but not exactly sure how to

**Comment by Eldoza** [comment]
@yh54321 approach worked for me. I was able to gain access to the Field Array helpers. There did not appear to be any performance issues with this approach.

**Comment by brendengifford** [comment]
I was able to do this by using a binding method inside the FieldArray render.

Something like this:

    function demo() {
      let boundArrayHelpers;

      const bindArrayHelpers = (arrayHelpers) => {
        boundArrayHelpers = arrayHelpers
      }

      return (
        <Form>
          <FieldArray
            name="friends"
            render={arrayHelpers => {
              bindArrayHelpers(arrayHelpers);
              return (
                <div>
                  {values.friends.map((friend, index) => (
                    <div key={index}>
                      <Field name={`friends[${index}].name`} />
                      <Field name={`friends.${index}.age`} />
                      <button type="button" onClick={() => arrayHelpers.remove(index)}>
                        -
                      </button>
                    </div>
                  ))}
                </div>
              )}
            }
          />
          
          <button
            type="button"
            onClick={() => boundArrayHelpers.push({ name: '', age: '' })}
          >
            +
          </button>
        </Form>
      )
    }

**Comment by boshng95** [comment]
I had tested the suggested solution given by @yh54321  & @brendengifford . I do appreciate the solution but it triggers the error of **_"Uncaught Error: Too many re-renders. React limits the number of renders to prevent an infinite loop."_** . Just wonder, is there any better solution for this? Or what I had missed out?

**Comment by wondering639** [comment]
> I had tested the suggested solution given by @yh54321 & @brendengifford . I do appreciate the solution but it triggers the error of **_"Uncaught Error: Too many re-renders. React limits the number of renders to prevent an infinite loop."_** . Just wonder, is there any better solution for this? Or what I had missed out?

Solution from @brendengifford works fine for me. @boshng95  could you fix your issue? guess your rootcause was somewhere else? are you using the react key atteribute for preventing unnecessary re-renders?

**Comment by angelgarzz** [comment]
I found a really simple solution using the useRef hook,

**Comment by angelgarzz** [comment]
I found a really simple solution using `useRef`. Just by creating a ref of the button inside `FieldArray` we can access it imperatively from outside the `FieldArray`, then we hide the one inside with some css and it's done.

Here's an example:

`const FriendList = () => {
  const pushButton = useRef(null);

  return (
    <Form>
      <FieldArray
        name="friends"
        render={(arrayHelpers) => (
          <div>
            {values.friends.map((friend, index) => (
              <div key={index}>
                <Field name={`friends[${index}].name`} />
                <Field name={`friends.${index}.age`} />
                <button
                  type="button"
                  onClick={() => arrayHelpers.remove(index)}
                >
                  -
                </button>
              </div>
            ))}

            <button
              type="button"
              style={{ display: "none" }} //Lets hide the button
              onClick={() => arrayHelpers.push({ name: "", age: "" })}
            ></button>
          </div>
        )}
      />
      {/* Remember to specify the type "button" so the form doesn't get submitted */}
      <button type="button" onClick={() => pushButton.current.click()}>
        +
      </button>
    </Form>
  );
};`

**Comment by angelgarzz** [comment]
I found a really simple solution using `useRef`. Just by creating a ref of the button inside `FieldArray` we can access it imperatively from outside the `FieldArray`, then we hide the one inside with some css and it's done.

Here's an example:

```const FriendList = () => {
  const pushButton = useRef(null);

  return (
    <Form>
      <FieldArray
        name="friends"
        render={(arrayHelpers) => (
          <div>
            {values.friends.map((friend, index) => (
              <div key={index}>
                <Field name={`friends[${index}].name`} />
                <Field name={`friends.${index}.age`} />
                <button
                  type="button"
                  onClick={() => arrayHelpers.remove(index)}
                >
                  -
                </button>
              </div>
            ))}

            <button
              type="button"
              style={{ display: "none" }} //Lets hide the button
              onClick={() => arrayHelpers.push({ name: "", age: "" })}
            ></button>
          </div>
        )}
      />
      {/* Remember to specify the type "button" so the form doesn't get submitted */}
      <button type="button" onClick={() => pushButton.current.click()}>
        +
      </button>
    </Form>
  );
};```

**Comment by killmenot** [comment]
Modified the solution above a little because I don't like to have hidden button

```jsx
const FriendList = () => {
  const arrayHelpersRef = useRef(null);

  return (
    <Form>
      <FieldArray
        name="friends"
        render={(arrayHelpers) => {
          arrayHelpersRef.current = arrayHelpers;

          return (
            <div>
              {values.friends.map((friend, index) => (
                <div key={index}>
                  <Field name={`friends[${index}].name`} />
                  <Field name={`friends.${index}.age`} />
                  <button
                    type="button"
                    onClick={() => arrayHelpers.remove(index)}
                  >
                    -
                  </button>
                </div>
              ))}
            </div>
          )
        }}
      />
      <button type="button" onClick={() => arrayHelpersRef.current.push({ name: "", age: "" })}>
        +
      </button>
    </Form>
  );
};
```

**Comment by heanfig** [comment]
I have created a hook to handle the helpers making an abstraction of the useRef

```ts

export interface FormikArrayHelpers<T> {
    push: (obj: T) => void;
    remove?: (index: number) => void;
}

interface FormikArrayHelpersProps<U> {
    arrayHelpersRef: MutableRefObject<FormikArrayHelpers<U>>;
    addItem: (data: U) => void;
    setCurrentHelpers: (arrayHelpers: FormikArrayHelpers<U>) => void;
}

const useFormArray = <T>(): FormikArrayHelpersProps<T> => {
    const arrayHelpersRef = useRef<FormikArrayHelpers<T>>(null);
    const addItem = (data: T): void => {
        arrayHelpersRef.current.push(data);
    };
    const setCurrentHelpers = (arrayHelpers: FormikArrayHelpers<T>): void => {
        arrayHelpersRef.current = arrayHelpers;
    }
    return {
        arrayHelpersRef,
        addItem,
        setCurrentHelpers
    }
};

export default useFormArray;
```

how to use

```ts
const { setCurrentHelpers, addItem } = useFormArray<LineItem>();
```

**Comment by Irshad-ideabits** [comment]
I came across teh same issue. You can refer to the field array values as `arrayHelpers.form.values`
