### ISSUE TITLE
Field Level Validation: Name Bug

### ISSUE THREAD

**Issue by jared-ross** [jaredpalmer/formik#773]
# Introduction

First of all I really like your library, it has helped me out a lot.

So I found this bug because I wanted to use php style input names with '['  and ']'.
But then as a result formik turned my values into a structure as it uses lodash's toPath feature.

The HTML spec specifies that an input name attribute can be pretty much any character so I would call it a bug. I didn't really mind it, it helped me out in this case. 

So this was in 0.11.11 as an undocumented (except for some issues/pull requests mentioning it) feature/bug.

Then I found some problems and updated to 1.0.1 and a lot of them got fixed :)

This is where I found this validation bug.

## Current Behavior

Particularly when validating the whole form:

Field level validation doesn't work with lodash "path"-ed names.
`runSingleLevelFieldValidation` does not receive a value from `runFieldLevelValidations`.

## Steps to Reproduce

1. Use a field with a lodash path string like 'user[email]'
2. Have a field level validator on it.
3. See how the field level validator doesn't receive the field value.

Example code:

Run this code: https://codesandbox.io/s/vmm30o7ny0

Here is the code mostly embedded.

```jsx
// Helper styles for demo
import "./helper.css";

import React from "react";
import { render } from "react-dom";
import { Formik, Form, Field } from "formik";
import _ from "lodash";

export const DisplayFormikState = props => (
  <div style={{ margin: "1rem 0" }}>
    <h3 style={{ fontFamily: "monospace" }} />
    <pre
      style={{
        background: "#f6f8fa",
        fontSize: ".65rem",
        padding: ".5rem"
      }}
    >
      <strong>props</strong> = {JSON.stringify(props, null, 2)}
    </pre>
  </div>
);

const App = () => (
  <div className="app">
    <h1>Formik Field Level Bug</h1>

    <Formik
      onSubmit={(values, { setSubmitting }) => {
        setTimeout(() => {
          alert(JSON.stringify(values, null, 2));
          setSubmitting(false);
        }, 1000);
      }}
    >
      <Form>
        <label> Email </label>
        <Field
          name="user[email]"
          validate={val => (!!val ? true : `Field is required. Given "${val}"`)}
        />
        <Field
          render={({ field, form }) => (
            <div className="input-feedback">
              {form.errors && _.get(form.errors, "user[email]")}
            </div>
          )}
        />
        <button type="submit">Submit</button>

        <Field render={props => <DisplayFormikState {...props} />} />
      </Form>
    </Formik>
  </div>
);

render(<App />, document.getElementById("root"));
```

## Suggested solution(s)
One line change, a pull request to follow shortly.

Additionally I found a related bug with validateYupSchema which is a bit more involved.
I will link some commented code for it here. 

**CodeSandbox Link**:

https://codesandbox.io/s/vmm30o7ny0

---

- Formik Version: 1.0.1
- React Version: 16.4.1
- TypeScript Version:
- Browser and Version: Chrome
- OS: OSX
- Node Version:
- Package Manager and Version:

**Comment by jared-ross** [comment]
Sorry I didn't realise just pushing commits to my fork on github would reference them here, the correct commit is d09df4c.

**Comment by jared-ross** [comment]
This is the related problem code:
https://github.com/jaredpalmer/formik/blob/d74445f55b558599d6e7174b0573868055e36a5e/src/Formik.tsx#L663-L668

It sets empty strings to undefined for Yup.
I am not sure why this is necessary.

Whatever it is for it just happens to work for deep
values structures - only because it doesn't do anything. 

It needs to map over the leaves of the tree for it to do what it is supposed to do.

**Comment by jaredpalmer** [comment]
Can you make a PR?
