### ISSUE TITLE
How to create a dynamic Form

### ISSUE THREAD

**Issue by bhupesh-sf** [jaredpalmer/formik#779]
I need to create a dynamic form kind of a query builder. Please see the attached screenshot for the exact requirement.
![dynamic form to be created](https://user-images.githubusercontent.com/6471510/42996109-347d3194-8c30-11e8-918d-f2eaea487a19.png)

**Comment by ematipico** [comment]
That's business logic, it will be up to you to create it :)

**Comment by bhupesh-sf** [comment]
@ematipico Business logic I can implement. Just looking for the way by which I can implement that :)

**Comment by ematipico** [comment]
I created something similar, but at the end I didn't anything special from formik. I mean, it gives me already what's needed to create something powerful and dynamic. Maybe you have some different and special requirement
