### ISSUE TITLE
Add Flow definitions to flow-typed repository

### ISSUE THREAD

**Issue by nickdecooman** [jaredpalmer/formik#78]
Even though Formik is using Typescript, it would still be great to have Flow type definitions added to the [Flow-typed](https://github.com/flowtype/flow-typed) repository. By just adding a description of the Formik interface using Flow in this repository, Formik functions could be type checked in Flow projects also.

**Comment by Andreyco** [comment]
Automatic conversion could help with take off https://github.com/joarwilk/flowgen

**Comment by jdelStrother** [comment]
FWIW, I generated a definition with flowgen and manually tweaked it to get things sort-of working here https://gist.github.com/jdelStrother/8227ce99250e366cd9963686f515278a
It successfully checks the call to `Formik()` - eg something like this would fail: 
```js
export default Formik({
})(SignupForm)
```
because `handleSubmit` wasn't defined.

However, it doesn't typecheck the component being wrapped - I can't figure out how to express something like this:

```js
type SignupProps = {bannerMessage: string} & FormikProps
const SignupForm = ({bannerMessage, values, errors, etc}: SignupProps) => <div />
export default Formik({...})(SignupForm)
```

such that it would warn about missing `bannerMessage` in props.

**Comment by Andreyco** [comment]
HOCs with Flow are kinda issue right now. Will try to dig into this. Awesome work :)

**Comment by Andreyco** [comment]
Making some progress on this field, stay tuned  🎉

**Comment by Andreyco** [comment]
Having a problem with typing main function.

My Typescript knowledge is very basic, what I understand this is possible

```typescript
function Formik<Props, Values>(config: any) {
  return b;
}

// you can specify those generics at call site
interface P {
  email: string,
  otherProp: number
}

interface V {
  email: string
} 

const enhancer = Formik<P, V>({/*...*/})
```

Unfortunately, you cannot specify generic at call site for Flow. Instead, they are inherited from params.

```js
function Formik<Props, Values>(config: any) {
  return b;
}

interface P {
  email: string,
  otherProp: number
}

interface V {
  email: string
} 

const enhancer = Formik(props: P, values: V)
```

As you can see, there is need for 2 params in Flow (at least, it looks like).
Does anyone have idea how to solve this?

**Comment by Andreyco** [comment]
Stopping work on flow typings until new API is released as stable

**Comment by sibelius** [comment]
@jdelStrother do you have an example of using this flow-typed in a code?

**Comment by jdelStrother** [comment]
@sibelius I'm not sure what you're asking - there's this example, does that help?
```js
type SignupProps = {bannerMessage: string} & FormikProps
const SignupForm = ({bannerMessage, values, errors, etc}: SignupProps) => <div />
export default Formik({...})(SignupForm)
```

**Comment by sibelius** [comment]
there is no `FormikProps` in your flow-typed example

**Comment by istarkov** [comment]
Guys I did good (I think) flow library definitions for `formik`

Here is it:
```javascript
declare module 'formik' {
  declare type UnaryFn<A, R> = (a: A) => R;
  declare type Component<A> = React$ComponentType<A>;

  declare export type HOC<Base, Enhanced> = UnaryFn<
    Component<Base>,
    Component<Enhanced>,
  >;

  declare export function Formik<Enhanced, Values>(
    // Formik configuration options
    options: {
      displayName?: string,
      mapPropsToValues?: (props: Enhanced) => Values,
      handleSubmit?: (
        values: Values,
        formikBag: {
          props: Enhanced,
          setValues: (values: Values) => void,
          setFieldValue: (field: $Keys<Values>, value: any) => void,
          setErrors: (errors: $ObjMap<Values, <K>(k: K) => boolean>) => void,
          setFieldError: (field: $Keys<Values>, message: string) => void,
          setTouched: (touched: $ObjMap<Values, <K>(k: K) => boolean>) => void,
          setFieldTouched: (field: $Keys<Values>, isTouched?: boolean) => void,
          setSubmitting: (isSubmitting: boolean) => void,
          setStatus: (status: any) => void,
          resetForm: (nextProps?: Enhanced) => void,
          submitForm: () => void,
        },
      ) => void,
      validate?: (
        values: Values,
        props: Enhanced,
      ) =>
        | void
        | $ObjMap<Values, <K>(k: K) => boolean>
        | Promise<void | $ObjMap<Values, <K>(k: K) => boolean>>,
      validationSchema?: ((props: Enhanced) => any) | any,
      validateOnChange?: boolean,
      validateOnBlur?: boolean,
      isInitialValid?: boolean | ((props: Enhanced) => boolean | void),
    },
  ): HOC<
    {
      ...$Exact<Enhanced>,
      // FormikComputedProps
      dirty: boolean,
      isValid: boolean,
      // Formik state and state helpers
      values: Values,
      setValues: (values: Values) => void,
      setFieldValue: (field: $Keys<Values>, value: any) => void,

      errors: $ObjMap<Values, <K>(k: K) => boolean>,
      setErrors: (errors: $ObjMap<Values, <K>(k: K) => boolean>) => void,
      setFieldError: (field: $Keys<Values>, message: string) => void,

      touched: $ObjMap<Values, <K>(k: K) => boolean>,
      setTouched: (touched: $ObjMap<Values, <K>(k: K) => boolean>) => void,
      setFieldTouched: (field: $Keys<Values>, isTouched?: boolean) => void,

      isSubmitting: boolean,
      setSubmitting: (isSubmitting: boolean) => void,

      status?: any,
      setStatus: (status: any) => void,

      resetForm: (nextProps?: Enhanced) => void,
      submitForm: () => void,

      // FormikHandlers

      handleSubmit: (e: SyntheticEvent<EventTarget>) => void,
      handleChange: (e: SyntheticEvent<EventTarget>) => void,
      handleChangeValue: (name: string, value: any) => void,
      handleBlur: (e: SyntheticEvent<EventTarget>) => void,
      handleReset: () => void,
    },
    Enhanced,
  >;
}
```

It works well in combination with `recompose` HOCs, and uses the same usage idea 
as described [here](https://github.com/acdlite/recompose/tree/master/types) and [at medium article](https://medium.com/flow-type/flow-support-in-recompose-1b76f58f4cfc)

So all you need to use it is to import HOC type and to declare formik enhancer with it

```javascript
/* @flow */

import * as React from 'react';
import { Formik } from 'formik';
import type { HOC } from 'formik';

const myForm = ({
  values,
  errors,
  handleChange,
  setFieldError,
  handleSubmit,
}) => (
  <form onSubmit={handleSubmit}>
    <input id="name" value={values.name} onChange={handleChange} />
    <input id="age" value={values.age} onChange={handleChange} />
    <div onClick={() => setFieldError('age', 'bad age')}>
      {errors.name} {errors.age}
    </div>
  </form>
);

// The only type you need to define
type MyProps = {
  someObj: {
    name: string,
    age: number,
  },
};

const formikEnhancer: HOC<*, MyProps> = Formik({
  mapPropsToValues: ({ someObj }) => ({
    name: someObj.name,
    age: someObj.age,
    someStrangeValue: {
      id: someObj.age,
    },
  }),
  handleSubmit: (values, { props, setSubmitting, setFieldError }) => {
    setSubmitting(true);
    setFieldError('age', 'bad bad');
  },
});

export default formikEnhancer(myForm);
```

Type inference work well see image

![image](https://user-images.githubusercontent.com/5077042/30516711-724e0944-9b4f-11e7-8c0c-c3c941c4d7e5.png)

Errors detected well

![image](https://user-images.githubusercontent.com/5077042/30516719-a7d48e3a-9b4f-11e7-9115-042e4dd3ed25.png)

Feel free to add this into flowtyped and contact me if you have any questions

**Comment by VladShcherbin** [comment]
@istarkov hey, you might be interested in following [this one](https://github.com/jaredpalmer/formik/pull/130) 😉

**Comment by Andreyco** [comment]
How about exporting types with "namespace", to prevent name collisions.
E.g. `HOC` => `FormikHOC`

**Comment by sibelius** [comment]
@istarkov looks good

are you gonna send a PR do flow-typed repo?

I think `FormikHOC` would be a good name

**Comment by istarkov** [comment]
Sorry guys have no time for PR, please make it

**Comment by istarkov** [comment]
There will be no collision with names, u can change name on import

**Comment by istarkov** [comment]
I also have version with typed status, but found it useless in current realisation (no ability to merge with prev) so decided not to provide it here

**Comment by Andreyco** [comment]
> There will be no collision with names, u can change name on import

While that's true, would be explicit name better?
Can take care of PR if you're not against

**Comment by istarkov** [comment]
@Andreyco thank you it will be great!

**Comment by stunaz** [comment]
@Andreyco any updates?

**Comment by aaronjensen** [comment]
I've started this here: https://github.com/flowtype/flow-typed/pull/1395

**Comment by DTupalov** [comment]
@aaronjensen could you take a look to this issue #696 ? Thanks!

**Comment by aaronjensen** [comment]
@DTupalov sorry, I'm no longer using Formik nor Flow. Typing HoCs is way too challenging in flow (or at least it used to be, I'm not too interested in finding out if it's easier now...) Sorry, but good luck!

**Comment by DTupalov** [comment]
@aaronjensen sadly :(

@istarkov maybe you can help with advice in #696 issue?
