### ISSUE TITLE
"Cannot read property 'type' of undefined" with react-select

### ISSUE THREAD

**Issue by danivivriti** [jaredpalmer/formik#789]
## Current Behavior
While using with react-select, changing the select results "Uncaught TypeError: Cannot read property 'type' of undefined"
![Error](https://i.imgur.com/Yj925vI.png)
## Steps to Reproduce
```
<Formik
            initialValues={{
                assignedTo: task.assignedTo,
            }}
            onSubmit={(values) => {
                const updatedTask = { ...task, ...values };
                editTask(updatedTask);
            }}
            render={({ handleSubmit, handleChange, values }) => (
                <form>
                    <Select type="text" name="assignedTo" options={options} onChange={handleChange} value={{ value: task.assignedTo, label: task.assignedTo }} />
                </form>
            })
/>
```

---

- Formik Version: 1.0.1
- React Version: 16.4.1
- TypeScript Version:
- Browser and Version: Chrome 67.0.3396.99
- OS: Mac OS High Sierra v10.13.5
- Node Version: 8.11.3
- Package Manager and Version: npm 5.6.0

**Comment by prichodko** [comment]
`react-select` seems to call `handleChange` with something different than native DOM `event`. Use [setFieldValue](https://github.com/jaredpalmer/formik#setfieldvalue-field-string-value-any-shouldvalidate-boolean--void).

**Comment by hugofovargue** [comment]
Hi @prichodko, I've adapted the react-select example by Jared, although I'm implementing a custom input, I'm running into the same issue. I've set up handlers for the `onChange` and `onBlur` events using `setFieldValue` and `setFieldTouched` from the `form` param. 

```javascript
const CustomSelect = ({ name, label, ...rest }) => (
  <Field
    name={name}
    render={({ field, form }) => {

      const handleChange = (value) => 
        form.setFieldValue(name, value);

      const handleBlur = () => 
        form.setFieldTouched(name, true);

      return (
        <div className={classes}>
          <label htmlFor={name}>{label}</label>
          <Select 
            id={name}
            name={name}
            onChange={handleChange}
            onBlur={handleBlur}
            {...field}
            {...rest}
          />
        </div>
      );
    }}
  />
);

// CustomSelect component within the <Formik> render prop
<CustomSelect 
  name="gender" 
  label="Gender" 
  type="text" 
  options={[
    { value: 'male', label: 'Male' },
    { value: 'female', label: 'Female' },
    { value: 'notspec', label: 'Not Specified' },
  ]}
/>
```

Debugging the formik handle change event I can see the `eventOrPath` object is just my value object, so I'm definitely handling this wrongly. 

![screen shot 2018-07-26 at 16 30 39](https://user-images.githubusercontent.com/8467936/43272361-b367f078-90f1-11e8-93b7-ac20ffbb82d9.png)

What would be the correct of implementing this?

**Comment by romant37** [comment]
I have same problem with implement Select from Ant Design
"formik": "^1.0.0-beta.10"

Console error:
formik.esm.js:241 Uncaught TypeError: Cannot read property 'type' of undefined

```javascript
import React, { Component } from 'react'
import { Form, Select } from 'antd'


class SelectPicker extends Component {
  onValueChange = value => {
    const { field, form } = this.props
    form.setFieldValue(field.name, value)
  }
  onBlur = () => {
    const { form, field } = this.props
    form.setFieldTouched(field.name, true)
  }
  render() {
    const { form, field, label, placeholder, disabled, items, className, valueName, helperText, size } = this.props
    const fieldError = form.errors[field.name]
    const isTouched = form.touched[field.name]
    const isShowError = !!(fieldError && isTouched)

    return (
      <Form.Item
        label={label}
        validateStatus={fieldError && isTouched && "error"}
        help={isShowError ? fieldError : helperText}
      >
        <Select
          {...field}
          size={size || 'large'}
          className={className}
          label={fieldError && isTouched ? fieldError : label}
          defaultValue={field.value || ''}
          disabled={disabled}
          onSelect={this.onValueChange}
          onBlur={this.onBlur}
        >
          <Select.Option value=''>{label || placeholder}</Select.Option>
            {items && items.map(item => (
              <Select.Option value={item.id} key={item.id}>{item[valueName]}</Select.Option>
            ))}
        </Select>
      </Form.Item>
    )
  }
}

export default SelectPicker
```

**Comment by tobiascarson** [comment]
asd

**Comment by barrychapman** [comment]
I am getting this error also

**Comment by barrychapman** [comment]
Mine looks like this:

`export const NewSelect = ({name, label, ...rest}) => (
    <>
        <div className="col-sm-1 text-right">
            <Label className="col-form-label" htmlFor={rest.name || rest.name}>{label}</Label>
        </div>
        <Field
            name={name}
            render={({field, form}) => {
                const handleChange = (value) => form.setFieldValue(name, value);
                const handleBlur   = () => form.setFieldTouched(name, true);

                return (
                    <div className={sizer(rest.size)}>
                        <Select
                            id={name}
                            name={name}
                            className="react-select primary"
                            classNamePrefix="react-select"
                            onChange={alert}
                            onBlur={handleBlur}
                            {...field}
                            {...rest}
                        />
                    </div>
                )
            }}
        />
    </>
);`

Stacktrace:

formik.esm.js:763 Uncaught TypeError: Cannot read property 'type' of undefined
    at formik.esm.js:763
    at formik.esm.js:797
    at Object.<anonymous> (formik.esm.js:1302)
    at StateManager.callProp (stateManager-04f734a2.browser.esm.js:130)
    at StateManager._this.onChange (stateManager-04f734a2.browser.esm.js:70)
    at Select._this.onChange (Select-9fdb8cd0.browser.esm.js:1226)
    at Select._this.setValue (Select-9fdb8cd0.browser.esm.js:1253)
    at Select._this.selectOption (Select-9fdb8cd0.browser.esm.js:1302)
    at onSelect (Select-9fdb8cd0.browser.esm.js:1879)
    at HTMLUnknownElement.callCallback (react-dom.development.js:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:238)
    at invokeGuardedCallback (react-dom.development.js:291)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:306)
    at executeDispatch (react-dom.development.js:391)
    at executeDispatchesInOrder (react-dom.development.js:416)
    at executeDispatchesAndRelease (react-dom.development.js:3301)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:3310)

**Comment by flora8984461** [comment]
I'm still getting the same error even I have tried all the solutions above. just checking any more updates on this issue?

**Comment by WolfyUK** [comment]
You could also forward your own `React.ChangeEvent`, although it feels very hacky:

```tsx
function Selector({ name }: { name: string }) {
  const [field] = useField(name);
  const options = [{ value: "Value 1", label: "Label 1" }];

  const handleChange = (value: OptionsType<OptionTypeBase>) => {
    const e: React.ChangeEvent<any> = {
      target: {
        id: field.name,
        name: field.name,
        value,
      },
    } as any; // Formik doesn't seem to care about the other event props
    field.onChange(e);
  };

  return (
    <Select
      options={options}
      name={field.name}
      value={field.value}
      onChange={handleChange}
      onBlur={field.onBlur}
    />
  );
}
```

**Comment by athenawisdoms** [comment]
@ozergul @prichodko Where can we find `setFieldValue` in order to use your solution? 

I am using functional components, thank you!!!

```js
import { Formik, FormikHelpers } from 'formik';
import Select from 'react-select';
import { Form } from 'react-bootstrap';

function AddData() {
    const locationTypeOptions = [
        { value: 'train', label: 'Train Station'}
    ];

    return (
        <Formik
            initialValues={{ locationType: 'train', locationName: '', segmentName: '' }}
            onSubmit={(
                values: Values,
                { setSubmitting }: FormikHelpers<Values>
            ) => {
                setSubmitting(true);
                console.log('Submitting form:', values)
                setSubmitting(false);
            }}
        >
            {( {values, errors, touched, handleChange, handleBlur, handleSubmit, isSubmitting }) => (
                <Form id="addLocationForm" onSubmit={handleSubmit}>
                    <Form.Group controlId="formLocation">
                        <Form.Label>Location Type</Form.Label>
                        <Select 
                            name="locationType" 
                            options={locationTypeOptions} 
                            onChange={option => setFieldValue("locationType", option)}   // <=== How to get setFieldValue?
                            onBlur={handleBlur} 
                            values={values.locationType} 
                        />
                    </Form.Group>
            )}
        </Formik>
    )
}
```

**Comment by ozergul** [comment]
@athenawisdoms here:
```js
import { Formik, FormikHelpers } from 'formik';
import Select from 'react-select';
import { Form } from 'react-bootstrap';

function AddData() {
    const locationTypeOptions = [
        { value: 'train', label: 'Train Station'}
    ];

    return (
        <Formik
            initialValues={{ locationType: 'train', locationName: '', segmentName: '' }}
            onSubmit={(
                values: Values,
                { setSubmitting }: FormikHelpers<Values>
            ) => {
                setSubmitting(true);
                console.log('Submitting form:', values)
                setSubmitting(false);
            }}
        >
            {( {values, errors, touched, handleChange, handleBlur, handleSubmit, isSubmitting, setFieldValue }) => (   // <=== 
                <Form id="addLocationForm" onSubmit={handleSubmit}>
                    <Form.Group controlId="formLocation">
                        <Form.Label>Location Type</Form.Label>
                        <Select 
                            name="locationType" 
                            options={locationTypeOptions} 
                            onChange={option => setFieldValue("locationType", option)}   // <=== How to get setFieldValue?
                            onBlur={handleBlur} 
                            values={values.locationType} 
                        />
                    </Form.Group>
            )}
        </Formik>
    )
}
```

**Comment by SyedWajihUlHassan** [comment]
HI!
I had the same error but found a solution

try this

`onChange={e => formik.setFieldValue('language', e[0].value)}`

**.setFieldValue** is a **Formik** method that needs two arguments, first is the **field** name which's the value you want to update, and second, is the **value** 

**e** will be an array with one or multiple selected objects, in my case, there was only one so I accessed the only object using **e[0]** and then bind the required property from the object, which in my case was **e[0].value**
