### ISSUE TITLE
Touched state of multi value field

### ISSUE THREAD

**Issue by dferber90** [jaredpalmer/formik#793]
Whenever a field holds an array of values and when one item was removed from that list, then the touched state for that field ends up being an empty array.

Are empty arrays supposed to represent a list from which the touched element has disappeared?

Example with `FieldArray`: https://codesandbox.io/s/x77o7v4kxz?expanddevtools=1
Full with `<select multiple />`: https://codesandbox.io/s/qq429w4n4q?expanddevtools=1

**Comment by dferber90** [comment]
I ended up writing some code which treats empty arrays as touched. It’s fine to keep it closed but this is pretty weird behavior, especially since it’s undocumented.

**Comment by kylemh** [comment]
@dferber90 care to share that code?

I'm running into the same issue.

**Comment by kylemh** [comment]
@dferber90 I’m having this issue as well. Are you able to share your solution?

**Comment by dferber90** [comment]
@kylemh What we ended up doing was to treat an empty array as touched. We would only treat it as untouched when the value is `undefined` or the key does not exist.

We wrote a helper function like `isTouched` which checks for it. 

See https://github.com/commercetools/ui-kit/blob/08a6045381d633e44c3494b41c7d6763104366fb/src/components/inputs/select-input/select-input.js#L27-L29
