### ISSUE TITLE
Idea for a different API to get better static typing and drop other API constructs/concepts

### ISSUE THREAD

**Issue by donaldpipowitch** [jaredpalmer/formik#794]
First of all, thank you for the lib!

## Current Behavior

The current API is constructed around a selector concept where fields of a form are "selected" with a string-based name. I can have a name like `"social.facebook"`, but TypeScript is not able to tell me if this is a valid name or not.

Another concept in the current API is that values, errors and so on are different objects. E.g. I check `values.social.facebook`, `errors.social.facebook` (and `touched.facebook` according to the README - is this correct?). So when a new field is created for example I need to pass in multiple objects (`values`, `errors`, `touched`...) _or_ use a helper which does that for me based on the name of the field.

Besides having to pass multiple objects around as props they can make type checks harder as well. E.g. in this example from the README the correct types can't be inferred from TypeScript.

```ts
const validate = (values, props) => {
  const errors = {};            // You would need to explicitly write `const errors: FormikErrors<typeof values> = {};`
  if (!values.email) {
    errors.email = 'Required';  // throws in TypeScript, because `email` does not exist on `{}`
  }
  return errors;
};
```

(By the way, according to the [`types.tsx`](https://github.com/jaredpalmer/formik/blob/e0ab364959f7c27d6a6e727bc705cc5f9c926825/src/types.tsx#L205) there is no `props` param in `validate`.)

Also I think by using multiple objects we could get into strange edge cases, if nested data structures are nullable. (E.g. you have the name `social.facebook`, but `social` was set to `null`.)

## Desired Behavior

It would be nice to get rid of the string-based name to get better type checks and to reduce the amount of props which need to be passed to a custom field/component without the need of using a helper function/component/context.

## Suggested Solution

We have a custom build form library which uses an API like this and are quite happy with that. Maybe this could be useful for Formik and others as well? If that was discussed before and rejected feel free to close this issue immediately :)

Given a render function like `children?: ((props: FormikProps<Values>) => React.ReactNode) | React.ReactNode;` as we currently have a rewritten interface for `FormikProps<Values>` could look like this:

```ts
// this needs to be set by the user
type Values = {
  email: string,
  social: {
    facebook: string,
    twitter: string
   }
};

// this represents a single "field"
type FormValue<T, Values> = {
  value: T,
  error: null | string,
  touched: boolean,
  formik: FormikProps<Values>, // a reference to the form where this field is used
  parent: null | FormValue<any>,  // a reference to the parent form value (in a nested structure), if we need this
  name: string, // could be readonly and computed automatically, if we still need this
  field: { /* ... */ }, // maybe all the props we need for a normal field as a shorthand
  // ...other properties and methods relevant to _this_ field
};


type FormikProps<Values> = {
  handleSubmit: Function,
  handleReset: Function,
  errors: FormValue[], // a readonly property which collects all fields which have an error currently
  touched: FormValue[], // a readonly property which collects all fields which have been touched currently
  values: FormValues<Values>,
  toRawValues: () => Values, // we need a function to "unbox" our data, typically before the submit when everything is valid
  // ...other properties and methods relevant to the whole form
} 
```

In this snippet I used `FormValues` which "basically" boxes a single property from our _raw_ `Values` inside a `FormValue`. With conditional types this would work for nested data structures and array (I hope I haven't made a typo 😄):

```ts
type FormValues<Values> = { [P in keyof Values]: FormValuesWrapper<Values[P]> };

type FormValuesWrapper<Values> = Values extends Array<infer U>
  ? FormValue<FormValuesArray<U>>
  : T extends object ? FormValue<FormValuesObject<Values>> : FormValue<Values>;

type FormValuesWrapperFlat<Values> = Values extends Array<infer U>
  ? FormValue<FormValuesArray<U>>
  : T extends object ? FormValues<Values> : FormValue<Values>;

type FormValuesObject<Values> = { [P in keyof Values]: FormValuesWrapper<Values[P]> };

interface FormValuesArray<T> extends Array<FormValuesWrapperFlat<T>> {}
```

So this can look a little bit complicated on the type level, but the usage is really nice.

**previously (example from README)**

```ts
import * as React from 'react';
import { Formik, FormikProps, Form, Field, FieldProps } from 'formik';

interface MyFormValues {
  firstName: string;
}

export const MyApp: React.SFC<{} /* whatever */> = () => {
  return (
    <div>
      <h1>My Example</h1>
      <Formik
        initialValues={{ firstName: '' }}
        onSubmit={(values: MyFormValues) => alert(JSON.stringify(values))}
        render={(formikBag: FormikProps<MyFormValues>) => (
          <Form>
            <Field
              name="firstName"
              render={({ field, form }: FieldProps<MyFormValues>) => (
                <div>
                  <input type="text" {...field} placeholder="First Name" />
                  {form.touched.firstName &&
                    form.errors.firstName &&
                    form.errors.firstName}
                </div>
              )}
            />
          </Form>
        )}
      />
    </div>
  );
};
```

**now (example from README)**

```ts
import * as React from 'react';
import { Formik, FormikProps, Form, Field, FieldProps } from 'formik';

interface MyFormValues {
  firstName: string;
}

export const MyApp: React.SFC<{} /* whatever */> = () => {
  return (
    <div>
      <h1>My Example</h1>
      <Formik<MyFormValues>
        initialValues={{ firstName: '' }}
        onSubmit={(values: MyFormValues) => alert(JSON.stringify(values))}
        render={({ values: { firstName }}) => (  // <-- firstName is type checked, not possible to use a "name" which isn't available
          <Form>
           {/* Maybe <Field/> isn't needed anymore? */}
            <div>
              <input type="text" {...firstName.field} placeholder="First Name" />
              {firstName.touched && firstName.error}
            </div>
          </Form>
        )}
      />
    </div>
  );
};
```

**previously (validation example from above)**

```ts
const validate = (values, props) => {
  const errors = {};
  if (!values.email) {
    errors.email = 'Required';  // throws in TypeScript, because `email` does not exist on `{}`
  }
  return errors;
};
```

**now (validation example from above)**

```ts
const validate = (values) => {
  // I'm not totally familiar with Formiks validation logic here, but I'd expect that Formik resets all current errors to null, before `validate` is invoked
  if (!values.email.value) {
    values.email.error = 'Required';  // works in TypeScript, because `error` can be `null | string`
  }
  return values; // return is optional, because `values` is still the same object
  // Formik can now traverse `values` to collect all `.error !== null`
};
```

Potentially nullable fields are a little bit more easier to handle as well (imho):

```ts
interface MyFormValues {
  social: { twitter: string } | null;
}

export const MyApp: React.SFC<{} /* whatever */> = () => {
  return (
    <div>
      <h1>My Example</h1>
      <Formik<MyFormValues>
        initialValues={{ social: null }}
        onSubmit={(values: MyFormValues) => alert(JSON.stringify(values))}
        render={({ values: { social }}) => (
          <Form>
          {/* You couldn't access social.value.twitter.error here with strictNullChecks enabled */}
          {social 
            ? <>Render a field like above and you can now access "social.value.twitter" safely...</>
            : <>Render a button to add some social metadata</>}       
          </Form>
        )}
      />
    </div>
  );
};
```

In a similar way like `<Field/>` maybe becomes obsolete I think `<FieldArray/>` and its `arrayHelpers` could become obsolete as we could add a specific `ArrayFormValue` (which is like `FormValue` , but with arrayHelpers in case our property on `Values` is an array - thank you conditional types!) to add new items to the array which are automatically boxed with `FormValues themselves`.

## Who does this impact? Who is this for?

- Type checks for TypeScript users
- simplified props passing for all users who write custom fields or components in general

## Describe alternatives you've considered

I only know two possible ways:
- Select fields via string based names (the current way).
- Select fields directly via JavaScript object notation and/or destructing.

## Additional context

- We used this concept in our company quite successfully. (But made other problematic design choices which is why we currently look into Formik.)

---

Disclaimer: I'm not really familiar with Formik. I just started using it. I probably miss a lot of things, but I hope I can show the idea behind boxing `Values` with `FormValues` in a different structure which could help to get rid of string based APIs.

Thank you for taking the time :)

**Comment by jlogar** [comment]
Anything to enforce better typing support and less room for errors (like entering the wrong name for a field) seems like the right direction to me. Especially given Formik's Typescript support.
