### ISSUE TITLE
Submitting form should set all fields as touched

### ISSUE THREAD

**Issue by donysukardi** [jaredpalmer/formik#795]
## Current Behavior

Currently submitting form will only set touched: true for fields registered in `values` instead of all fields

https://github.com/jaredpalmer/formik/blob/1e130295614b9d4228307ded78548ca1daff4f82/src/Formik.tsx#L416-L425

## Steps to Reproduce

If we don't assign `initialValues` and try submitting the form, submission will fail without flipping the touched flags for all the fields

## Expected behavior

`touched` flags should be set for all fields upon submission, not just fields with values, so that we can display error accordingly

## Suggested solution(s)

Use combination of keys in both `this.fields` and `prevState.values` to get the list of all fields.

## Additional context

**CodeSandbox Link**: https://codesandbox.io/s/3q8wn41lm6

---

- Formik Version: 1.0.2

**Comment by donysukardi** [comment]
Found a workaround for this. We could use `submitCount` on top of `touched` to determine if a field has been touched.

Updated the codesandbox with the workaround solution.

**Comment by elijah-schow** [comment]
@donysukardi The workaround doesn't seem to work.`submitCount` doesn't increment if the form is invalid.

**Comment by Mykybo** [comment]
I just run into this. This really needs to be fixed.

**Comment by charlax** [comment]
See #445 for a longer conversation about this.

**Comment by toqeertahir-tekhqs** [comment]
I want auto focus into Formik with yup validation error on field using isValidation function can you please help me.
