### ISSUE TITLE
Create a composable form error component

### ISSUE THREAD

**Issue by samjbmason** [jaredpalmer/formik#80]
What would be the best way of creating a simple error component that checks if a value has a error and has been touched and then displays the appropriate form element error. Would I need to pass in the whole errors object as a prop and the input name and then select those out of the object inside the component?

**Comment by eonwhite** [comment]
Yes, the easiest way to do this is to take two props: the field name and the Formik state, and check errors and touched against the field name.

Here's a simple component we use to show feedback using Reactstrap (I guess I got lazy and used an `any`, but that should be a `FormikState` I believe)

```
import * as React from 'react';

import { FormFeedback } from 'reactstrap';

export interface FormErrorFeedbackProps {
  field: string;
  form: any;
}
export const FormErrorFeedback: React.SFC<FormErrorFeedbackProps> = props => {
  if (!props.form.errors[props.field] || !props.form.touched[props.field]) {
    return <small><FormFeedback>&nbsp;</FormFeedback></small>;
  }
  return <small><FormFeedback>{props.form.errors[props.field]}</FormFeedback></small>;
};
```

**Comment by samjbmason** [comment]
That's interesting I'm getting an issue where if I set something up like that as soon as I type something into one of the form fields all the others show there errors and it looks as though touched is an empty object

________________________________

**Comment by samjbmason** [comment]
I realised I was not running the latest version which solved any odd issues
