### ISSUE TITLE
Flickering on input field with secureTextEntry on iOS

### ISSUE THREAD

**Issue by SvetlinStaev** [jaredpalmer/formik#804]
## Current Behavior
I have a very simple login form with username and password. All works great but on iOS when I type in the password field there is a bit of a flickering on each keystroke the dot representing the character of the password becomes smaller and then gets back to the original size. When the same input is not managed by Formik the password input does not introduce flickering.

## Steps to Reproduce
On iOS 11 - set a regular TextInput field with a secureTextEntry property to have it as a password field. Try to type in the field, notice the dots flickering.

## Expected behavior
The password field should not flicker while trying to enter a password.

## Suggested solution(s)
I believe it is something related to the validation of the field. It might be a good idea to have a per-field `validateOnChange` to disable validation on each key stroke for the password even though I have tried to set `validateOnChange` to false for the whole form but it continues to flicker.

## Additional context

**CodeSandbox Link**:

---

- Formik Version: 1.0.2
- React Version: 0.55
- TypeScript Version: N/A
- Browser and Version: N/A
- OS: iOS 11.1
- Node Version: 10.6
- Package Manager and Version: npm 6.1

**Comment by Andreyco** [comment]
Guys, is this still relevant? I see some fixes mentioned related to flickering input in RN’s release logs

**Comment by SvetlinStaev** [comment]
In the most recent version of the RN and Formik I no longer notice that.
