### ISSUE TITLE
react-navigation + loading data

### ISSUE THREAD

**Issue by tresheffron** [jaredpalmer/formik#808]
I've spent many hours trying to research a solution to my problem, and no matter how I go at it, it seems like a chicken and egg problem. Likely there is something I'm missing given my relative newness to react-native and formik, but I just can't see a way out.

TL;DR: if I want to run form submission from the navigation header, i need to wrap my whole component in withFormik (ala #268). But then the initialValues are set up front and I can't find a way to change them from, say, componentDidMount.

**History**
I was able to hook up a formik form successfully and everything worked beautifully using the Formik component. As long as I was using a submit button within the form. When I decided to move my "Save" button up into the navigation bar, I was able to hook it up using withFormik but then my fields values were no longer updating after pulling data from the database.

After some research, this appeared to be a props problem. As long as I could hook up my state to props, I could get it to refresh using [enableReinitialize](https://github.com/jaredpalmer/formik#enablereinitialize-boolean-1). To do this, I had to turn my form into a component, so I could wrap it inside an HOC and pass down props from state.

```
import Form from '../layouts/program'
...
render() {
  return (
    <Form data={this.state.data} />
  )
}
```

and inside the program layout

```
import _defaults from 'lodash/defaults'

const enhancer = withFormik({
  enableReinitialize: true,
  mapPropsToValues: props => {
    return _defaults({}, props.data)
  },
...
```

This worked beautifully. But in order to get my navigation bar button back, I had to move the navigationOptions out of the layout and into the HOC. This broke what #268 solved and now I no longer have access to formik's props.handleSubmit. This feels like a chicken and egg problem to me. In order to be able to add "data" to props so I can change it later, I have to push formik down the chain. But then I lose the ability to drive submit from the navigation bar unless I push formik up the chain.

**Summary**
I'm assuming it's possible to both drive formik from an external source (like a navigation button) AND to be able to load the form data later in the react-native lifecycle (like in componentDidMount). So I'm also assuming that I'm missing something about how you hook both of these up to work. All of the examples that show the former always use hardcoded data in mapPropsToValues. And all of the examples that show the latter always drive the form submit from a button inside the form.

Does anyone have examples for driving formik from the navigation bar and loading data from an outside source (database or api)?

**More complete code**
_layout/program.js_
```
import { withFormik } from 'formik'
import * as Yup from 'yup'
import _defaults from 'lodash/defaults'
import { FormInput } from 'react-native-elements'

const enhancer = withFormik({
  enableReinitialize: true,
  mapPropsToValues: props => {
    return _defaults({}, props.data)
  },
  validationSchema: Yup.object().shape({
    name: Yup.string().required("Name is required")
  }),
  handleSubmit: (values, bag) => {
    _submission stuff_
  },
})

const form = props => {
  const {
    values,
    _etc_
  } = props;
  
  return (

    <View style={styles.container}>
            <FormInput
              name='name'
              label='Name'
              placeholder='Enter name'
              value={values.name} 
              onChangeText={setFieldValue} 
              onBur={setFieldTouched}
            />
    </View>
  )
}

export default enhancer(form)

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center'
  }
})
```

_program.js_

```
import Form from '../layouts/program'

export default class Program extends Component {  
  static navigationOptions = ({navigation}) => {
    return {
      title: 'Program',
      headerRight: navigation.state.params && navigation.state.params.headerRight
    }
  }

  constructor(props) {
    super(props);

    let id = this.props.navigation.getParam('id', null)
    let data = _defaults({}, programDefaults, { editable: false }) //setup empty data structure

    this.state = {
      id: id,
      data: data
    }
  }

  componentDidMount() {
    this._loadData(); //load from the database into this.state.data
    this.props.navigation.setParams({ headerRight: <HeaderButton
      onPress={this.handleSubmit} //this doesn't work b/c Program props, not formik props
      title='Save'
    /> 
    });
  }

```

**Sidenote**
Is there a reason that Formik has submit and reset handlers but withFormik only has a submit handler and not a reset handler? I have another question related to driving a form reset from the navigation bar as well, but it's moot if I can't solve this issue first.

**Comment by jdhorner** [comment]
I have this same problem. Some of my code is below, and shortened for legibility. 

Here are the `withFormik()` options: 
```jsx
const validationSchema = yup.object().shape({
  selectedStaffId: yup.mixed().required('Please choose an option from the list.'),
  name: yup.string(),
  startDate: yup.date().required('Please provide a start date.'),
  endDate: yup.date().required('Please provide an end date.'),
});

const formikEnhance = withFormik({
  // Had to put this otherwise it got LOTS of props from other places
  mapPropsToValues: ({ selectedStaffId }) => ({
    selectedStaffId,
    name: '',
    startDate: '',
    endDate: '',
  }),
  validationSchema, // from above
  // this never fires either
  handleSubmit: (values, { props, setSubmitting }) => {
    console.log(values);
    alert(JSON.stringify(values));
  },
});
```

These are the navigation options set on the component: 
```jsx
  static navigationOptions = ({ navigation }) => {
    const { params = {
      onTapSave: () => { },
    } } = navigation.state;

    return {
      headerRight: (
        <Button title="Save" onPress={() => { params.onTapSave(); }} />
      ),
    };
  };
```

The relevant CDM lines. 
```jsx
  componentDidMount() {
    this.props.navigation.setParams({
      // onTapSave: this._prepareSaveData (works when a class member)
      onTapSave: this.props.handleSubmit,  // doesn't work when from Formik
    });
  }
```

And the beginning of the form part inside the component's render method: 
```jsx
<Formik
  initialValues={{
    selectedStaffId,
    name,
    startDate,
    endDate,
  }}
  onSubmit={values => alert(JSON.stringify(values))} // does this even need to be here?
  validationSchema={validationSchema}
>
  {(formikProps) => { /* lots of form stuff */ }}
</Formik>
```

When I press the save button in my navigation header, nothing ever happens. No alert box with values, or no console log with values. Form _validation_ works great, so I know that at least that part of `withFormik()` is fine. since that's what's passing in my `validationSchema`. 

Is there a better way to get the Save button in a navigation header to call a custom method that connects to Formik?
