### ISSUE TITLE
Reference on initialValue

### ISSUE THREAD

**Issue by kserjey** [jaredpalmer/formik#809]
## Intro

I'm not sure if it is a bug, but I think it would be cool to mention in README. So I marked it as a question.

## Current Behavior

If we call `push` with object reference it will cause some problems with `values`.

## Steps to Reproduce

[CodeSandbox](https://codesandbox.io/s/vq7n25m3o3)

Click plus button multiple times and try to input some data. It will be copied to all inputs.

## Suggested solution

Deep clone? Or just mention it in the docs :3

---
- Formik Version: 0.11.11
- React Version: 16.3.2

**Comment by Ridermansb** [comment]
You are using the same object to push into array..

try clone instead ..  line 28

```
push({ name: '' })
```

**Comment by kserjey** [comment]
I know that, I just want it to be mentioned in README or somewhere
