### ISSUE TITLE
Show compatible version of typescript in README

### ISSUE THREAD

**Issue by naffiq** [jaredpalmer/formik#819]
## Current Behavior
I've stumbled upon troubles on compiling Formik definitions with typescript 2.8. Turns out, it's new `import` syntax for definitions, that was introduced this may (2018):

```
node_modules/formik/dist/Form.d.ts(5,23): error TS1005: ';' expected.
node_modules/formik/dist/Form.d.ts(5,24): error TS1003: Identifier expected.
node_modules/formik/dist/Form.d.ts(5,34): error TS1005: ';' expected.
node_modules/formik/dist/Form.d.ts(5,49): error TS1005: '>' expected.
node_modules/formik/dist/Form.d.ts(5,51): error TS1005: ',' expected.
node_modules/formik/dist/Form.d.ts(5,52): error TS1109: Expression expected.
node_modules/formik/dist/Form.d.ts(6,5): error TS1128: Declaration or statement expected.
node_modules/formik/dist/Form.d.ts(6,6): error TS1109: Expression expected.
node_modules/formik/dist/Form.d.ts(6,7): error TS1109: Expression expected.
node_modules/formik/dist/Form.d.ts(7,1): error TS1128: Declaration or statement expected.
node_modules/formik/dist/connect.d.ts(3,59): error TS1005: '>' expected.
node_modules/formik/dist/connect.d.ts(3,124): error TS1109: Expression expected.
node_modules/formik/dist/connect.d.ts(3,140): error TS1005: ';' expected.
node_modules/formik/dist/connect.d.ts(3,228): error TS1109: Expression expected.
```

## Desired Behavior
I'd like to be aware of what version of typescript I have to use to be able to compile my project with Formik.

## Suggested Solution
Add typescript version info to readme section.

## Who does this impact? Who is this for?
Every typescript developer, who started their project before 2.9 was out and trying to adopt Formik

## Describe alternatives you've considered
Maybe it's even better to put typescript ^2.9 as a `peerDependency` to package.json

## Additional context
Finally getting rid of `redux-form` (no offense, it's just too slow for our form-heavy react-native app).

**Comment by naffiq** [comment]
Nevermind, there's a large badge under the typescript section header, which I somehow missed.

**Comment by kbiedrzycki** [comment]
@naffiq can you share the page with typescript instructions? I am facing same issues.
