### ISSUE TITLE
When built with webpack in production mode

### ISSUE THREAD

**Issue by pavliha** [jaredpalmer/formik#820]
## Current Behavior
![image](https://user-images.githubusercontent.com/10353006/43989781-3e36a76c-9d59-11e8-8f19-0ca2e5eaa94c.png)

## Steps to Reproduce
1) build with webpack --mode production
2) click any of the formik inputs 
3) get error above
## Expected behavior
Should not throw errror
## Suggested solution(s)
I think it could be problem with webpack tree shaking

---

- Formik Version:   "^1.0.2",
- React Version: ^16.4.0
- TypeScript Version: no typescript
- Browser and Version: Chrome 66.0.3359.139
- OS:  Linux Mint
- Node Version: v8.11.2
- Package Manager and Version: yarn 1.7.0

**Comment by jaredpalmer** [comment]
hrmmm. maybe it is.
