### ISSUE TITLE
unexpected content found on stack - using <Field /> on react-native

### ISSUE THREAD

**Issue by yjose** [jaredpalmer/formik#821]
## Current Behavior

![image](https://user-images.githubusercontent.com/11137944/43992964-6fd85246-9d7e-11e8-9046-0c71eeae92a4.png)

## Steps to Reproduce
try to render this component 
```jsx
import React from "react";
import { TextInput } from "react-native";
import { Formik, FormikProps, Form, Field, FieldProps } from "formik";

export default () => (
  <Formik
    initialValues={{ firstName: "" }}
    onSubmit={values => alert(JSON.stringify(values))}
    render={formikBag => (
      <Form>
        <Field
          name="firstName"
          render={({ field, form }) => <TextInput {...field} />}
        />
      </Form>
    )}
  />
);

```
## Expected behavior
unexpected content found on stack

## Additional context
React-native

---

- Formik Version: 1.0.2
- React Version: 16.4.1
- React-native : 0.56.0

**Comment by jaredpalmer** [comment]
`<Form>` doesn't work in react native.
