### ISSUE TITLE
Possible to replace default label used in Yup error message?

### ISSUE THREAD

**Issue by dantheman99** [jaredpalmer/formik#822]
I see I could use the `errors` prop to pass custom messages for each field, but unsure if it's possible to just replace the label that is used in the error messages? i.e. Ideally I don't want to re-write all the error messages, I just want to replace the label used in Yup's error messages.

Yup itself provides a way - `Yup.mixed().label()` - https://github.com/jquense/yup#validationerrorerrors-string--arraystring-value-any-path-string

... But can't find a way to do this via Formik's API.

I'm currently using the `<Formik/>` approach.

```
<Formik
                                initialValues={myValues}
                                validationSchema={Yup.object().shape(myValidationObject)}
                                onSubmit={(values, { setSubmitting, setErrors }) => {
                                           // do some stuff
                                }}
                                render={formikProps => <MyForm {...formikProps} myCustomProp={myCustomData}/>}
                            />
```

Thanks

**Comment by seb-lean** [comment]
What was the solution?

**Comment by seb-lean** [comment]
In your schema:

`amount_value_blah: Yup.string().required().label('Amount')`
