### ISSUE TITLE
Wrong error merging, when values contains array of objects

### ISSUE THREAD

**Issue by alex-kozlov-dev** [jaredpalmer/formik#829]
## Current Behavior
When both ```validationSchema``` and ```validate``` are used, errors object may be broken, if values contains array of objects.

Yup schema:
```javascript
const validationSchema = yup.object({
  array: yup.array().of(
    yup.object({
      firstField: yup.string().required("Invalid (yup)")
    })
  )
});
```

Validate function:
```javascript
const validate = values => {
  let errors = {};

  values.array &&
    values.array.forEach((item, i) => {
      if (!item.secondField) {
        errors.array = errors.array || [];
        errors.array[i] = { secondField: "Invalid (validate)" };
      }
    });

  return errors;
};
```

Form data:
```javascript
{
  array: [
    {
      firstField: "",
      secondField: ""
    }
  ]
}
```

Resulted errors object:
```javascript
{
  "array": [
    {
      "firstField": "Invalid (yup)"
    },
    {
      "secondField": "Invalid (validate)"
    }
  ]
}
```

## Expected behavior
Resulted errors object:
```javascript
{
  "array": [
    {
      "firstField": "Invalid (yup)",
      "secondField": "Invalid (validate)"
    }
  ]
}
```

## Steps to Reproduce
Open [sandbox](https://codesandbox.io/s/ll9yv28kpm), enter character in any field and remove it

## Suggested solution(s)
Looks like this issue comes from [deepmerge](https://www.npmjs.com/package/deepmerge) package, in which this is default behavior for arrays ([link](https://www.npmjs.com/package/deepmerge#example-usage))

**CodeSandbox Link**: https://codesandbox.io/s/ll9yv28kpm

---

- Formik Version: 1.0.3

**Comment by jaredpalmer** [comment]
@lightespresso oof that's a bug. I guess we need to implement our own array merge? Do you know what that would look like?

**Comment by lightespresso** [comment]
@jaredpalmer Yes. Actually, there is solution in deepmerge docs. Let me prepare a PR for it
