### ISSUE TITLE
Issue with Typescript Definitions using withFormik()

### ISSUE THREAD

**Issue by mattoni** [jaredpalmer/formik#831]
## Current Behavior
Recently upgraded from v0.11.11 to 1.0.3. When attempting to build, my forms that 
were once building now have the following typescript error:

```
Property 'registerField' is missing in type 'SingleStepProps & FormikState<FormValues> & FormikActions<FormValues> & FormikHandlers & FormikComputedProps<FormValues> & { children?: ReactNode; }'.
```

## Steps to Reproduce
Build SFC component 
`export const MyForm: SFC<OtherFormProps & FormikProps<FormValues>>`

then attempt to wrap it in withFormik().

## Expected behavior
Typescript should still compile

## Suggested solution(s)
Not sure what's wrong with the definitions that's causing it.

## Additional context

The error is actually quite long and I have no idea how to decipher this, but it worked on previous versions of Formik.

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/5110855/44296573-6a6a6b80-a276-11e8-9ea6-a2edc2209c9f.png">

---

- Formik Version: 1.0.3
- React Version: 16.4.2
- TypeScript Version: 3.0.1
- Browser and Version: Firefox 61.0.2
- OS: Mac
- Node Version: 8.9.1
- Package Manager and Version: 6.1.0

**Comment by jaredpalmer** [comment]
Hrmmm. Let me look into this.

**Comment by andiriedl** [comment]
I've got the same Error when trying to compile the provided  Example:

https://github.com/jaredpalmer/formik#withformik
 
```
TS2345: Argument of type '(props: OtherProps & FormikSharedConfig & FormikState<FormValues> & FormikActions<FormValues> & FormikHandlers & FormikComputedProps<FormValues> & { registerField(name: string, fns: { ...; }): void; unregisterField(name: string): void; }) => Element' is not assignable to parameter of type 'CompositeComponent<InjectedFormikProps<MyFormProps, FormValues>>'.
  Type '(props: OtherProps & FormikSharedConfig & FormikState<FormValues> & FormikActions<FormValues> & FormikHandlers & FormikComputedProps<FormValues> & { registerField(name: string, fns: { ...; }): void; unregisterField(name: string): void; }) => Element' is not assignable to type 'StatelessComponent<InjectedFormikProps<MyFormProps, FormValues>>'.
    Types of parameters 'props' and 'props' are incompatible.
      Type 'MyFormProps & FormikState<FormValues> & FormikActions<FormValues> & FormikHandlers & FormikComputedProps<FormValues> & { children?: ReactNode; }' is not assignable to type 'OtherProps & FormikSharedConfig & FormikState<FormValues> & FormikActions<FormValues> & FormikHandlers & FormikComputedProps<FormValues> & { registerField(name: string, fns: { ...; }): void; unregisterField(name: string): void; }'.
        Type 'MyFormProps & FormikState<FormValues> & FormikActions<FormValues> & FormikHandlers & FormikComputedProps<FormValues> & { children?: ReactNode; }' is not assignable to type '{ registerField(name: string, fns: { validate?: ((value: any) => string | Function | Promise<void> | undefined) | undefined; }): void; unregisterField(name: string): void; }'.
          Property 'registerField' is missing in type 'MyFormProps & FormikState<FormValues> & FormikActions<FormValues> & FormikHandlers & FormikComputedProps<FormValues> & { children?: ReactNode; }'.
```

My Versions:

- Formik Version: 1.1.1
- React Version: 16.4.2
- TypeScript Version: 3.0.1
- OS: Ubuntu 18.04
- Node Version: 10.9.0
- Npm Version: 6.4.0

**Comment by nonameolsson** [comment]
Any update on this? I'm also getting this issue.

**Comment by nonameolsson** [comment]
Added more details in #862

**Comment by jaredpalmer** [comment]
Looking at this now. I think I know what happened.

**Comment by mattoni** [comment]
Hi @jaredpalmer, did you end up finding the issue? Looking forward to getting rid of these build errors :)

**Comment by jaredpalmer** [comment]
This has been fixed

**Comment by vapstor** [comment]
> Looking at this now. I think I know what happened.

clarify please
