### ISSUE TITLE
Add focus tracking

### ISSUE THREAD

**Issue by johnhampton** [jaredpalmer/formik#838]
We are migrating from `react-redux-form` to `formik`. Several of our forms make use of the focus property in RRF for displaying errors and help information. 

It would be nice if Formik tracked which field was in focus as part of it's state. Something similar to the way blur/touched is tracked would work. Formik could provide `handleFocus` and `setFieldFocused` for setting the focus and a `focused` object that has the current field that is in focus set to `true` and all other known fields set to `false`.

Alternatively, we can implement a wrapper component to track focus outside of formik, but I think it would be cleaner if this functionality was implemented in formik.

**Comment by ematipico** [comment]
Can I try to implement this?

**Comment by AntiFish03** [comment]
@ematipico, Sorry. I was working on it before I found this issue because I needed it and I was also coming from `react-redux-form`

**Comment by mateodelnorte** [comment]
There's an outstanding PR for this: https://github.com/jaredpalmer/formik/pull/923

Should this be re-opened and the PR merged?
