### ISSUE TITLE
Values stale in onSubmit after setValues / setFieldValue

### ISSUE THREAD

**Issue by hkung77** [jaredpalmer/formik#839]
I need to change some values after submit. but the values object doesn't seem to be updated after calling setValues / setFieldValue.

I wanted to ask this on the discord chat but the invite has expired.

**Comment by timc13** [comment]
this is because the values are updated under the hood via a `setState` call.
#529 would help with this

**Comment by hkung77** [comment]
@timc13 Thank you so much for your response! I am looking forward to seeing this get merged!

**Comment by yashaRO** [comment]
Has this bug (if it is considered a bug) ever been fixed, or is there an alternative method that's supposed to be used?

**Comment by Joead** [comment]
Interested in if/when this will be resolved. I'm trying to trim field values on submit (I'm not using Yup) and unless I'm missing something it seems that calling `setValues` in `onSubmit` is the logical way to do this?

**Comment by jaredpalmer** [comment]
@Joead If you don't need rerun validation with the trimmed values, you should trim your payload in your `onSubmit` function. If you need to trim your values, you should do so with  either 1) custom input components or 2) a `<form>` like so.

```jsx
<form onSubmit={e => { 
     setValues(trimMyStuffBeforeSubmit(values)); 
     handleSubmit(e); 
}}>
    ...
</form>
```

**Comment by Joead** [comment]
Thanks @jaredpalmer for your reply. I am using Formik with a render prop and am trying to trim values in `onSubmit` however the following is not working and the :

```jsx
<Formik
  initialValues={{
    message: 'Trim me      ',
  }}
  onSubmit={(values, { setSubmitting, setValues }) => {
    const trimmedMessage = values.message.trim()
    setFieldValue('message', trimmedMessage)
    console.log(values)
    setSubmitting(false)
   }}
  render={....}
/>
```

**Comment by jaredpalmer** [comment]
Your `onSubmit` function does not execute if validation fails. To understand what happens when a user attempts to submit, check out this guide: https://jaredpalmer.com/formik/docs/guides/form-submission#submission-phases

**See previous comment for desired behavior**

**Comment by jaredpalmer** [comment]
Okay, I think I understand what you're having issues with. 

Using `setValues` or setFieldValue inside of `onSubmit` will not update the `values` object that is in scope, but rather Formik's internal state. This is because submission does not magically rerun. You will need to modify `values` (i.e. the first parameter of `onSubmit`) directly. Perhaps a better way to think of `onSubmit` here is like `onSubmit(valuesSnapshot: Values, actions: FormikActions) => void`.

**Comment by Joead** [comment]
I don't need to run validation though. I am just trying to trim the value before for submission.

**Comment by jaredpalmer** [comment]
Got it. You should just modify that object as you wish... and then sync it back to Formik.

```diff
<Formik 
   initialValues={{ message: 'Trim me ', }} 
   onSubmit={(values, { setSubmitting, setValues }) => { 
      const trimmedMessage = values.message.trim() 
-    setFieldValue('message', trimmedMessage)        
+    const payload = {...values, message: trimmedMessage } // Construct the new payload
+    setValues(payload) // Updates Formik's internal state
-     console.log(values) 
+    console.log(payload) 
      setSubmitting(false) 
     }} 
    render={....} />
```

**Comment by Joead** [comment]
Superb, worked perfectly 🎉 

Thanks for your help. Fantastic lib 👍

**Comment by quyle92** [comment]
> 



> ```diff
>   const payload = {...values, message: trimmedMessage } // Construct the new payload
> ```

but spread syntax (...) only works for show object, what if the `values` has nested property?
