### ISSUE TITLE
Benchmarking suite (vs. Redux Form, React Form) etc.

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/formik#84]
In initial tests, Formik is ~2-2.5x faster than Redux Form. As in, Redux Form yields input latency that is twice that of Formik’s using the same inner component, validation function, CSS, and initial state. (~16ms vs ~6ms on a single key down event).

I am working on a multi-input benchmark.  

Formik’s speed could be cranked even further by:
- implementing a pure component option
- adding preact-like linkState memoization to handleChange and handleBlur

**Comment by eonwhite** [comment]
I would suspect including an option to only validate a single field at a time might improve performance too, although it might be negligible.

**Comment by jaredpalmer** [comment]
@eonwhite This is how preact + linkstate caches input values...

```js
/** Get a deep property value from the given object, expressed in dot-notation.
 *	@private
 */
export function delve(obj, key) {
	for (let p=key.split('.'), i=0; i<p.length && obj; i++) {
		obj = obj[p[i]];
	}
	return obj;
}

function linkState(component, key, eventPath) {
  let c = component._linkedStates || (component._linkedStates = {});
  return c[key+'\n'+eventPath] || (c[key+'\n'+eventPath] = function(e) {
    let path = key.split('.');
	return function(e) {
		let t = e && e.target || this,
			state = {},
			obj = state,
			v = typeof eventPath==='string' ? delve(e, eventPath) : t.nodeName ? (t.type.match(/^che|rad/) ? t.checked : t.value) : e,
			i = 0;
		for ( ; i<path.length-1; i++) {
			obj = obj[path[i]] || (obj[path[i]] = !i && component.state[path[i]] || {});
		}
		obj[path[i]] = v;
		component.setState(state);
	};
  });
}
```
