### ISSUE TITLE
ant design select and date picker

### ISSUE THREAD

**Issue by ahmadtharwt** [jaredpalmer/formik#847]
I'm trying to work with ant design form items with Formik
it is working very smoothly except when it comes to date picker or select
it reads the initial value but handle change gives this error

```
Uncaught TypeError: Cannot read property 'type' of undefined
    at executeChange (formik.esm.js:203)
    at Object.Formik._this.handleChange [as onChange] (formik.esm.js:231)
    at Object.CalenderWrapper._this.handleChange [as onChange] (createPicker.js:51)
    at ProxyComponent.onCalendarSelect (Picker.js:106)
    at Object.chainedFunction [as onSelect] (createChainedFunction.js:18)
    at ProxyComponent.setSelectedValue (CalendarMixin.js:92)
    at ProxyComponent.onSelect (CalendarMixin.js:63)
    at ProxyComponent.onDateTableSelect (Calendar.js:159)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at Object.invokeGuardedCallback (react-dom.development.js:187)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:201)
    at executeDispatch (react-dom.development.js:461)
    at executeDispatchesInOrder (react-dom.development.js:480)
    at executeDispatchesAndRelease (react-dom.development.js:581)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:592)
    at forEachAccumulated (react-dom.development.js:562)
    at runEventsInBatch (react-dom.development.js:723)
    at runExtractedEventsInBatch (react-dom.development.js:732)
    at handleTopLevel (react-dom.development.js:4477)
    at batchedUpdates$1 (react-dom.development.js:16660)
    at batchedUpdates (react-dom.development.js:2131)
    at dispatchEvent (react-dom.development.js:4556)
    at interactiveUpdates$1 (react-dom.development.js:16715)
    at interactiveUpdates (react-dom.development.js:2150)
    at dispatchInteractiveEvent (react-dom.development.js:4533)
```

**Comment by yuritoledo** [comment]
On ``onChange`` event, try to use `` () => setFieldValues('name', value) ``

**Comment by raisiqueira** [comment]
Hey @yuritoledo, i have the some problem with `antd`.

```jsx
<DatePicker
  placeholder="Data de Nascimento"
  style={{ width: '100%' }}
  onChange={(date, dateString) => setFieldValue(dateString)}
  value={values.birthday}
/>
```

How to pass the value from DatePicker to the Formik?

**Comment by yuritoledo** [comment]
@raisiqueira 
```jsx
<DatePicker
  placeholder="Data de Nascimento"
  style={{ width: '100%' }}
  onChange={(_, dateString) => setFieldValue('birthday', dateString)}
  value={values.birthday}
/>
```

You forgot call the value that will receive the DateString
Qualquer coisa dá um toque ;)

**Comment by ahmadtharwt** [comment]
Thank you for your help

**Comment by minhth-1529** [comment]
> @raisiqueira
> 
> ```js-jsx
> <DatePicker
>   placeholder="Data de Nascimento"
>   style={{ width: '100%' }}
>   onChange={(_, dateString) => setFieldValue('birthday', dateString)}
>   value={values.birthday}
> />
> ```
> 
> You forgot to call the `value` that will receive the DateString (In this case, `birthday`)
> Qualquer coisa dá um toque ;)

Hi, now i want to resetForm when submit, but i dont know how?

**Comment by Arshazar** [comment]
I used yup for validation, when I use Datepicker from 'formik-antd' module, I get error while selecting date...

                            <Formik
                initialValues={{
                    id: filter !== null ? filter.id : '',
                    status: filter !== null ? filter.status : '',
                    created_at_from: filter !== null ? filter.created_at_from : '',
                }}
                validationSchema={Yup.object().shape({
                    id: Yup.number(),
                    status: Yup.string(),
                    created_at_from: Yup.string(),
                })}
                onSubmit={(fields, { resetForm }) => {
                    onSearch(fields)
                    resetForm()
                }}
            >
                {({ values, handleChange, handleBlur, submitForm, isSubmitting }) => (
                    <Form layout="vertical">
                        <div>
                            <Form.Item name="id" label="ID" className="form-item">
                                <Input
                                    id="formId"
                                    type="number"
                                    name="id"
                                    placeholder="ID"
                                    onChange={handleChange}
                                    onBlur={handleBlur}
                                    value={values.id}
                                />
                            </Form.Item>
                            <Form.Item name="status" label="Status" className="form-item">
                                <Select
                                    id="formStatus"
                                    name="status"
                                    placeholder="Status"
                                    onChange={handleChange}
                                    onBlur={handleBlur}
                                    value={values.status}
                                >
                                    <Select.Option value="">
                                        <p />
                                    </Select.Option>
                                    <Select.Option value="active">
                                        <p>active</p>
                                    </Select.Option>
                                    <Select.Option value="waiting">
                                        <p>waiting</p>
                                    </Select.Option>
                                    <Select.Option value="banned">
                                        <p>banned</p>
                                    </Select.Option>
                                </Select>
                            </Form.Item>
                            <Form.Item
                                name="created_at_from"
                                label="Created At From"
                                className="form-item"
                            >
                                <DatePicker
                                    name="created_at_from"
                                    format="YYYY-MM-DD HH:mm:ss"
                                    onBlur={handleBlur}
                                    onChange={handleChange}
                                    value={values.created_at_from}
                                    showTime
                                />
                            </Form.Item>
                        </div>
                        <br />
                        {isSubmitting}
                        <br />
                        <div className="form-buttons">
                            <SubmitButton
                                className="submit-button"
                                type="primary"
                                htmlType="submit"
                                disabled={isSubmitting}
                                onClick={submitForm}
                            >
                                Search
                            </SubmitButton>
                            <SubmitButton
                                className="cancel-button"
                                type="default"
                                htmlType="button"
                                disabled={isSubmitting}
                                onClick={onHide}
                            >
                                Cancel
                            </SubmitButton>
                        </div>
                    </Form>
                )}
            </Formik>
```

> Error: TypeError: can't access property "type", target is undefined
> TypeError: date.clone is not a function
