### ISSUE TITLE
Additions needed to make FormikErrors and FormikTouched typings account for field arrays

### ISSUE THREAD

**Issue by bbenezech** [jaredpalmer/formik#850]
Hi Jared!

https://github.com/jaredpalmer/formik/blob/master/src/types.tsx#L13-L15
should read something like

```typescript
export type FormikErrors<Values> = {
  [K in keyof Values]?: Values[K] extends any[]
    ? FormikErrors<Values[K][number]>[] // [number] is the special sauce to get the type of array's element. More here https://github.com/Microsoft/TypeScript/pull/21316
    : Values[K] extends object ? FormikErrors<Values[K]> : string
};
```

Same for FormikTouched I guess.

Cheers and millions of thanks for your hard work!

**Comment by josephluck** [comment]
Agreed on this, running in to an issue in our project atm with a field of type `string[]` which should have an error property of `string` rather than `FormikErrors<Values[K]>` - this looks like a good fix!

**Comment by jaredpalmer** [comment]
Feel free to submit a PR

**Comment by frantic1048** [comment]
To be more strict, may we limit the definition of  "Array" to a normal typed Array(`T[]`), not Tuple(`[T1, T2, T3, ...]`) ?

And I think we should only take care of `string` key of an `object`.

```ts
type FormikErrors<Values> =
  Values extends Array<infer T> ? Array<FormikErrors<T>>
  : Values extends object ? { [K in Extract<keyof Values, string>]?: FormikErrors<Values[K]> }
  : string
```

**Comment by JSoet** [comment]
Reopen - I just ran into this too... 

But I'm not sure that the solution mentioned above is correct, if you have an object in your values like
```
type tempType {
  arrayVal: number[]
}
```

then `errors.arrayVal` will be of type `number[]`? Which doesn't seem correct to me?

For me with a schema like the following:
```
validationSchema: Yup.object().shape({
    arrayVal: Yup.array()
      .required("required")
      .of(Yup.number())
      .min(1, "Minimum value: 1"),
  }),
```

Then it gives me a single string in `errors.arrayVal`. In which case the type should be 
```
export declare type FormikErrors<Values> = {
    [K in keyof Values]?: Values[K]  extends any[] ? string[] : Values[K] extends object ? FormikErrors<Values[K]> : string;
};
```

But I'm not sure if there's a way to create a different type of schema where you can get a different result from yup depending on how you create your validation schema?

@bbenezech @josephluck @frantic1048 ?

**Comment by JSoet** [comment]
Update - I realized that it can be an array of strings or just a single string, depending on whether the `Yup.array()` has a yup object inside it or if it's just a simple array check, so the type should actually be:

```
export declare type FormikErrors<Values> = {
    [K in keyof Values]?: Values[K]  extends any[] ? string[] | string : Values[K] extends object ? FormikErrors<Values[K]> : string;
};
```
