### ISSUE TITLE
<FastField> is undocumented

### ISSUE THREAD

**Issue by pimlottc-gov** [jaredpalmer/formik#857]
Aside from a single passing reference, FastField is completely undocumented in the README.md.

There's some information in #422 but it's not really geared towards the end user, nor is it clear if things have changed since it was original implemented.  It definitely looks like there are some important conditions you need to know in order to use it safely, so some up-to-date documentation from someone who understands how it works would be very useful.

**Comment by jaredpalmer** [comment]
Coming soon.
