### ISSUE TITLE
Validation by field

### ISSUE THREAD

**Issue by sshmyg** [jaredpalmer/formik#860]
## Current Behavior
Formik call validation for __ALL__ fields on validation event like `blur, focus, change`
![image](https://user-images.githubusercontent.com/1410608/44837601-b20fd080-ac42-11e8-8d68-d008aa929c8f.png)

## Steps to Reproduce
Changes in some field, leads to validation execution for all others fields in this form. 

## Expected behavior
Formik should validate only __CURRENT__ field on `blur, change or focus`

## Suggested solution(s)
Validate only current field

**CodeSandbox Link**:
https://codesandbox.io/s/jj1w56035y
See console.

---

- Formik Version: 1.1.1
- React Version: 16.4
- TypeScript Version: -
- Browser and Version: Latest chrome
- OS:  mac os
- Node Version: 10.7.0
- Package Manager and Version: 6.4.0

**Comment by jaredpalmer** [comment]
This is a Formik design decision and not possible to implementwith Yup / `validationSchema` (at the moment) See #780 . You can, however, trigger independent field validation by passing a `validate` prop to a `<Field>` component.

**Comment by sshmyg** [comment]
@jaredpalmer Design decision is to trigger validation for every field?

**Comment by jaredpalmer** [comment]
Yes. This allows people to have the most flexibility with their schemas.

**Comment by sshmyg** [comment]
@jaredpalmer I think it could be implement like an option, globally for all form. I've described real prod bug with server api request.

**Comment by morgs32** [comment]
@sshmyg where'd you validate the "real prod bug"?

**Comment by jaredpalmer** [comment]
If you're talking about merging server requests -> errors, my opinion is that these should be set as `status` and then conditional logic used in render() to show `status` messages or `errors` messages. However, people have requested that Formik be in charge of merging api errors (#645).

**Comment by sshmyg** [comment]
@morgs32 Sorry, my mistake, description is in other issue https://github.com/jaredpalmer/formik/issues/512#issuecomment-417215838

**Comment by weyert** [comment]
I wasn't aware we had a `status`-field/flag

**Comment by hunter2009** [comment]
@jaredpalmer Reopen, please!

**Comment by lm2almeida** [comment]
Is there any update on this?

**Comment by jaredpalmer** [comment]
Not at the moment. 

> This was a Formik design decision and was not possible to implement with Yup / `validationSchema` (initially). There is a WIP PR enabling this for `validationSchema` #780. You can, however, trigger independent field validation by passing a `validate` prop to a `<Field>` component.

**Comment by jaredpalmer** [comment]
However Formik supports Field-level validation now, which does only run one-at-a-time.

**Comment by jaredpalmer** [comment]
Duplicate of #512

**Comment by sebastianpatten** [comment]
It feels like everything formik does feels like the opposite of what i expect it to do lol

**Comment by tushkyparikh** [comment]
Formik call validation for ALL fields on validation.
Changes in some field, leads to validation execution for all others fields in this form. It happens when i am using independent field validation by passing a validate prop to a <Field> component.

`
isRequired = value => {
    console.log(value);
     return "errorMessage";
  }
<Form>
                <FieldArray
                    name='fields'
                    render = { arrayHelpers => (
                      <div>
                        {formFields.fields && formFields.fields.length > 0 &&
                         formFields.fields.map((field, index) => (
                            <div key={field.name}>
                              <Field 
                                type="text" 
                                name={field.name}  
                                placeholder={field.caption}
                                options={field.options || undefined}
                                label={field.caption}
                                component={stringToComponentMapper[field.component]}
                                type={field.component}
                                validate={this.isRequired}
                              /> 
                              <ErrorMessage name={field.name}/>
                            </div>
                         ))
                        }
                        <button type='submit' className='btn'>Submit</button>
                      </div>
                    )}
                />
              </Form>`
Can you please let me know why this is happening?

**Comment by silasdavis** [comment]
> Formik call validation for ALL fields on validation.

I think what you mean is formik calls a per-field validation when any field other field on the form is changed. I am trying to avoid this behaviour too but I suspect it originates from the fact that one fields validity may change when other fields changes because of references.

**Comment by tushkyparikh** [comment]
> > Formik call validation for ALL fields on validation.
> 
> I think what you mean is formik calls each field's validation when any field on the form is changed.
> 
> I am trying to avoid this behaviour too but I suspect it originates from the fact that one fields validity may change when other fields changes because of references.

Thanks for the information. But i have one more doubt. As you said, validate will invoke for the rest of the field as well. So let say, if there is a site which has more form fields then will it impact the performance?

**Comment by strizzaflex** [comment]
To the original post about validation calling back end API. I can understand not wanting that to happen for every field change. I got around expensive calculations or call just by using a short lived cache for API calls. The idea for that being it was valid when you last changed that field. If it's invalid at post then the api should be catching that and informing the user that it has become invalid.  For other expensive non api calculations I just use memoization on the validation functions. 

I know this is not an exact answer to your riddle. But hope it can help you or others mitigate some cost.

**Comment by clu7ch3r** [comment]
I've found a workaround. You should only display an error message when the text input field changes. Luckily, formik has a method called `getFieldMeta` for that and when you pass the field name to it, it returns an object. The only thing that changes in that method is the `value` prop which you would do a check on.

Example:

```
errorMessage={
 formikProps.getFieldMeta("username").value
  ? formikProps.errors.username
   : ""
}
```

**Comment by LndnMdiaLb** [comment]
My solution for field level validation was the following.  Feedback is greatly appreciated

`    <Field name={name} validate={validatation}>
      {({ field, form }) => {
        /*
          this method wraps the form methods in a timeout
          as a way of making the action asyncronous
          to guarantee the above method executes first
        */
        const handleFieldError = (fieldName, frm = form) => {
          setTimeout(() => {
            frm.validateField(fieldName).then(msg => {
              frm.setFieldError(fieldName, msg)
            })
          }, 0)
        }
        return (
              <input
                {...field}
                onChange={ev => {
                  form.handleChange(ev)
                  handleFieldError(name)
                }}
                onBlur={ev => {
                  form.handleBlur(ev)
                  handleFieldError(name)
                }}
              />
        )
      }}/></Field>`

The setTimeout with 0 milisecs was necessary otherwise the error object would reflect the previous interactions validation.  Is there a way to clean this up?  What am I missing

**Comment by ivanfuzuli** [comment]
I use <Field /> with validation but it also re-run all validations. Is there any work around? I make api calls and I don't wanna send request every other fields change.

**Comment by aarongodin** [comment]
I'm confused on how async validation should be accomplished in formik if the above comments are still the case. In my example, I'm calling an endpoint to validate that a name is unique after the name field blurs, and I'm doing this through my Yup schema. I don't want to call the endpoint every time that the other fields in the form change as this leads to 10s of requests while the user fills out the rest of the form.

Is there a pattern that allows me to avoid calling the endpoint on every validation run?

**Comment by thexpand** [comment]
@aarongodin I have the exact same issue. I thought of keeping record of the previously set value of the field somewhere, but that seems very hack-ish and I'm not even sure if it will work correctly. Were you able to solve your problem?

**Comment by aarongodin** [comment]
> @aarongodin Were you able to solve your problem?

My current solution is to track it as a separate piece of state in a higher level component that is rendering the form. Then the validation only retries if the state for the tracked value has changed. The validation schema ends up being a function that takes the state value and returns the Yup schema, to create a closure around the state value.

**Comment by plamber** [comment]
@aarongodin: I have exactly the same problem. I will follow your suggestion and track the value of this field in a separate state

**Comment by thexpand** [comment]
@aarongodin @plamber I think there should be a better solution to this. Are there any limitations in Formik that restrict us from implementing this in the library itself?
