### ISSUE TITLE
 Property 'registerField' is missing in type 'FormProps & FormikState

### ISSUE THREAD

**Issue by nonameolsson** [jaredpalmer/formik#862]
## Current Behavior

```bash
(39,4): Argument of type '(props: FormikProps<FormValues>) => Element' is not assignable to parameter of type 'CompositeComponent<InjectedFormikProps<FormProps, FormValues>>'.
  Type '(props: FormikProps<FormValues>) => Element' is not assignable to type 'StatelessComponent<InjectedFormikProps<FormProps, FormValues>>'.
    Types of parameters 'props' and 'props' are incompatible.      Type 'FormProps & FormikState<FormValues> & FormikActions<FormValues> & FormikHandlers & FormikComputed...' is not assignable to type 'FormikProps<FormValues>'.        Type 'FormProps & FormikState<FormValues> & FormikActions<FormValues> & FormikHandlers & FormikComputed...' is not assignable to type '{ registerField(name: string, fns: { validate?: ((value: any) => string | Function | Promise<void...'.
          Property 'registerField' is missing in type 'FormProps & FormikState<FormValues> & FormikActions<FormValues> & FormikHandlers & FormikComputed...'.
```

## Steps to Reproduce
Copy and paste following example: https://github.com/jaredpalmer/formik#withformik

## Expected behavior
The form should render

## Suggested solution(s)
Something could might be wrong with Type Definitions?

## Additional context

**CodeSandbox Link**:
https://codesandbox.io/s/v6913xz4z7
---

- Formik Version: 1.1.1
- React Version: 16.4.2
- TypeScript Version: 2.9.2
- Browser and Version: All browsers
- OS: All OS
- Node Version: 8.11.4
- Package Manager and Version: Yarn 1.5.1

**Comment by egmanoj** [comment]
Thanks for the quick fix! Any idea when these changes will be published to npmjs?

**Comment by nonameolsson** [comment]
Great! Thank you!

But when I clone the repo, or add the specific commit ID to my package json to get the latest from `master` then I get the following error:
`odule not found: Can't resolve './formik.cjs.development.js' in '/Users/andreasolsson/Code/CDAB.PlanningSystem/CDAB.PlanningSystem.Client/node_modules/formik'`
