### ISSUE TITLE
How to style validation on a field with multistep example?

### ISSUE THREAD

**Issue by lmichailian** [jaredpalmer/formik#869]
Hi! I followed the example for build a multistep form like wizard, the example works fine but I don't know how make a border on inputs when validation error is triggered.

Any suggestions ?

**Comment by jaredpalmer** [comment]
Style is left up to you. Just conditionally change the class name or css when there is an error on `touched.firstName && errors.firstname`

**Comment by lmichailian** [comment]
Yes, but following multistep repo example I've avalilable props.touchable and props.error inside to Wizard not inside each active page.

**Comment by akshaybosamiya** [comment]
I'm facing the same issue. Can anyone please explain how errors and touched props get accessed within wizard active page?

**Comment by akshaybosamiya** [comment]
Thanks. I just found an example. 
Codesandbox link: https://codesandbox.io/s/62nk7x0p73
@lmichailian You can try it.
