### ISSUE TITLE
Promise error in IE11

### ISSUE THREAD

**Issue by davidspiess** [jaredpalmer/formik#870]
## Current Behavior
When calling `setFieldValue`  with `shouldValidate` equals `true`, i get a `Promise is undefined` error in in IE11 (Formik 1.1.1).
This wasn't the case in 0.11.11.
Same happens when calling `submitForm()`.

---
- Formik Version: 1.1.1
- React Version: 16.4.13
- TypeScript Version: 3.0.3
- Browser and Version: IE 11
- OS:  Windows 10
- Node Version: 8.11.4
- Package Manager and Version: 6.4.0

**Comment by mvestergaard** [comment]
Not related to formik. IE11 does not have native support for promises. You need to polyfill them.

**Comment by davidspiess** [comment]
Maybe add a notice about that in the README.
It worked without polyfills before, so upgrading could cause IE 11 errors for a lot of users, without them noticing.

**Comment by prichodko** [comment]
It is usually handled during build process (using `babel-preset-env` for example), otherwise you have to polyfill it manually.
