### ISSUE TITLE
FastField successful validation creates object in `errors`

### ISSUE THREAD

**Issue by koyta** [jaredpalmer/formik#871]
## Current Behavior

When you using `<Field />` with name parameter `name="friends.Ivan"`, handling validation by Formik is good, but when you using `<FastField />` with the same name parameter, then:
1) when you make mistake/fail validation, Formik handle this well
2) when you resolve error (e.g. fill the required field), then `errors` object becomes like `errors: { friends: {} }`

## Expected behavior

When every field is valid, `formik.isValid` should be `true`, not `false`

## Suggested solution(s)

FastField should not creating an empty object for valid fields

## Additional context

**CodeSandbox Link**:
https://codesandbox.io/s/y0yy6vyr29

---

- Formik Version: 1.1.1
- React Version: 16.4
- Browser and Version: Chrome 60+
- OS: Windows/Mac
- Node Version: any

**Comment by jaredpalmer** [comment]
I am about to slightly break, but _actually_ fix FastField in the next release in a few hours. This will be fixed.

**Comment by jaredpalmer** [comment]
Try 1.2 and lmk

**Comment by koyta** [comment]
@jaredpalmer works well, thanks!
