### ISSUE TITLE
Using from Typescript

### ISSUE THREAD

**Issue by anykao** [jaredpalmer/formik#88]
Hi, I have a problem when using formik from Typescript
My code looks like this

`import { Formik, InjectedFormikProps } from 'Formik';`

but got a compile error

`Module not found: `/Users/developer/jswork/promo/node_modules/Formik/dist/formik.es6.js` does not match the corresponding path on disk `formik`.`

**Comment by jaredpalmer** [comment]
Lowercase the second part of your import
