### ISSUE TITLE
Examples with 'Yup' package have problems with import

### ISSUE THREAD

**Issue by steadylearner** [jaredpalmer/formik#883]
## Current Behavior
I was following the example from codesandbox and found that
In this [example](https://jaredpalmer.com/formik/docs/guides/validation), import Yup from 'yup';  doesn't work because of it default import was removed from Yup package. 

## Desired Behavior
I want you to change this and other exampels with Yup 

## Suggested Solution
Like the author of Yup suggested [here](https://github.com/jquense/yup/issues/218)
I want to you to upload new examples with 

```
import * as yup from "yup" or import * as Yup from 'yup'
```

**Comment by jaredpalmer** [comment]
Good to know. Can you make a PR to update?

**Comment by steadylearner** [comment]
I would make it yes. Thanks for the fast response.

**Comment by steadylearner** [comment]
I ended doing it and hope it worked well.   
I want to you to have interest in Codesandbox examples with Yup also.
I wrote about it here again because I don't know if you read PR and it was my first time to do so.

I also wanted to say thanks for writing great package and improved document recently.
It helped so much to understand better.

**Comment by jaredpalmer** [comment]
Merged!
