### ISSUE TITLE
isSubmitting does not update after submit when using custom validation

### ISSUE THREAD

**Issue by jonasbhe** [jaredpalmer/formik#89]
I noticed this in my own project, but it can also be seen in the 'Sync Validation' example: https://codesandbox.io/s/q8yRqQMp

'isSubmitting' does not change value to 'true' when submitting. I believe using 'validate' could be causing the issue as it does not happen when using Yup validation.

**Comment by jaredpalmer** [comment]
Good catch

**Comment by jaredpalmer** [comment]
Pushing out a patch right meow

**Comment by jaredpalmer** [comment]
Updated the example to use the latest version
