### ISSUE TITLE
handleReset on FieldArray of objects is not as expected

### ISSUE THREAD

**Issue by chhornponleu** [jaredpalmer/formik#892]
I have initialValues as below.
```
user = {
   name: '',
   positions: [
       
  ]
}
```
The dynamic array field [position] that user can add object [position]
```
user = {
   name: 'Ponleu',
   positions: [
       {name: 'CTO', salary: 2000, ...},
       {name: 'Senior Developer', salary: 1000, ...}
  ]
}
```
Initially, the positions is empty, so as it said in the doc, **handleReset will reset 'values' to its initialState so I expect the field 'positions' to be an empty array**.
But the result is weird. it reset object values as below

```
user = {
   name: '',
   positions: [
       {name: '', salary:'', ...},
       {name: '', salary: '', ...}
  ]
}

```

**Comment by jaredpalmer** [comment]
Do you have a suggested solution as to how you would implement a fix to this?
