### ISSUE TITLE
Crash with React Native

### ISSUE THREAD

**Issue by henrikra** [jaredpalmer/formik#894]
## Current Behavior
When using Formik with React Native the app will crash. Here is minimal code for reproduction https://github.com/henrikra/formikTest/blob/master/App.js
![image](https://user-images.githubusercontent.com/12229968/45352664-acf73d80-b5c1-11e8-9309-19f0503e0b96.png)

## Steps to Reproduce
Make fresh React Native project and add the code from example: https://jaredpalmer.com/formik/docs/guides/react-native

## Expected behavior
I expect the app not to crash when using Formik

## Suggested solution(s)
I have no idea how to solve this at the moment. Looks like React Native doesn't have `context` object?

## Additional context
Here is minimal reposity to reproduce this crash: https://github.com/henrikra/formikTest/blob/master/App.js

---

- Formik Version: 1.2.0
- React Native Version: 0.54.4
- TypeScript Version: 3.0.1
- OS: OSX
- Node Version: 8.11.3
- Package Manager and Version: Npm version 5.6.0

**Comment by jaredpalmer** [comment]
Yep JavaScript error. Props are not defined in the example

**Comment by henrikra** [comment]
Dude check my example repo. Props are not the problem as you can see if you look at it.

Yes there is mistake in the documentation but I already fixed that. Please reopen
