### ISSUE TITLE
Showing FieldArray validation errors

### ISSUE THREAD

**Issue by tsongas** [jaredpalmer/formik#897]
Wondering if anyone has worked out a way to show validation errors after a FieldArray? I'm following this very helpful example of how to create a FieldArray https://codesandbox.io/s/o5pw1vx916.

I'm trying to show errors similar to how I show them for text inputs like this:
```
<div className="form-group">
  <label>First Name *</label>
  <Field type="text" name="firstName" className={`form-control ${errors.firstName && touched.firstName && 'is-invalid'}`} />
  {touched.firstName && errors.firstName && <p className="invalid-feedback">{errors.firstName}</p>}
</div>
```
however in the case of a FieldArray that doesn't work because the inputs are nested inside a bunch of divs, with the error element coming after those divs, and this selector `.form-control.is-invalid~.invalid-feedback` used to un-hide the error element depends on the error element coming directly after the input that caused the error. Anyone solved this or is something in the works?

**Comment by jaredpalmer** [comment]
Try using the brand new `<ErrorMessage>` component? 

See https://jaredpalmer.com/formik/docs/api/errormessage

**Comment by tsongas** [comment]
Didn't know about that I'll take a look, thanks for all your work on this!!!

**Comment by tsongas** [comment]
Guessing you want to add it to the import `import { Formik, Form, Field } from 'formik';` in the example?

**Comment by tsongas** [comment]
Guessing you want to add it to `import { Formik, Form, Field } from 'formik';` in your example?

**Comment by jaredpalmer** [comment]
Good to close?

**Comment by tsongas** [comment]
Yes I think my problem is actually with Bootstrap but I'm happy to know about `<ErrorMessage>`

**Comment by tsongas** [comment]
Yes looks like my problems are with Bootstrap but it's helpful to know about `<ErrorMessage>`.
