### ISSUE TITLE
Rerender <FastField /> when `isSubmitting` has changed

### ISSUE THREAD

**Issue by stalmok** [jaredpalmer/formik#906]
Currently `<FastField />` isn't being rerendered when `isSubmitting` changes. Is there a good reason to not rerender it?

`isSubmitting` is a form wide attribute that doesn't change too often. From my experience typing or tabbing through the form is what causes bad perfrormance if all the fields are being rerendered.

I can create a PR If you would consider adding this.

**Comment by jaredpalmer** [comment]
yep makes sense
