### ISSUE TITLE
Using ContextApi with a lifecycle, the setError breaks

### ISSUE THREAD

**Issue by MontoyaAndres** [jaredpalmer/formik#912]
When I use the setError method in a lifecycle, in this case componentWillReceiveProps, the setError method breaks, it's repeated like 50 times...

I return a error in the function of context and that error is pass in the setError, but does not work.

This is the CodeSandbox, to understand what I'm doing

https://codesandbox.io/s/409nrvkj10

- Formik Version: 1.3.0
- React Version: 16.4.2
- Browser and Version: Firefox Quantum 62.0 (64-bit)
- OS: Ubuntu 18.04.1
- Node Version: 10
- Package Manager and Version: Yarn 1.9.4

**Comment by jaredpalmer** [comment]
setError has been deprecated for a while. Did you mean setErrors?

**Comment by MontoyaAndres** [comment]
@jaredpalmer whatever I put is wroke... setStatus, setErrors, etc... You can check it in the codesanbox example :)

**Comment by prichodko** [comment]
If it's still relevant - there is no check inside cWRP, so you always set a new state inside the lifecycle method and component gets re-rendered.
