### ISSUE TITLE
Default component rendered by <ErrorMessage />

### ISSUE THREAD

**Issue by Tomekmularczyk** [jaredpalmer/formik#914]
## Current Behavior
Currently ErrorMessage renders nothing when there was no validation error.

## Desired Behavior
I would like to "react" to validation errors with ErrorMessage. I have this problem:

```js
const FormikInput = ({ field, ...rest }) => <Input {...field} {...rest} />;
...
<Field
  component={FormikInput}
  name="url"
  placeholder="Enter here"
>
    URL
</Field>
<ErrorMessage component={Error} name="url" />
```
The above works correctly, however I would like to pass `invalid` prop to `Input` so it get's styled differently. I know I can do this that way:
```js
const FormikInput = ({ field, form, name, ...rest }) => {
  const error = form.errors[field.name] && form.touched[field.name];
  return <Input isValid={!error} {...field} {...rest} />;
};
```
...but this seems redundant when I already have a "smart" component like ErrorMessage. I wonder whether I could just:

## Suggested Solution

```js
<ErrorMessage name="url">
  {error => 
    <> 
      <Field ... isValid={!!error} />
     {error && <Error>error</Error>}
    </>
 }
</ErrorMessage>
```

**Comment by jaredpalmer** [comment]
ErrorMesage is optimized to limit retenders. A better solution Field metadata
