### ISSUE TITLE
Localstorage gets reset on form reload

### ISSUE THREAD

**Issue by harry2312** [jaredpalmer/formik#918]
Hi All,

I'm making forms using formik. To make the state of the form persist i'm using formik-persist which saves the data in to local storage with the name provided to it. As soon as we reload this form the local storage also resets. And the values from form also disappears along with it.

I'm expecting that the local storage don't get clear on reload so that form can persist it's state from local storage.

---
- Formik Version: 1.2.0
- React Version: 16.4.0
- TypeScript Version:
- Browser and Version: Chrome Version 68.0.3440.106
- OS:  Mac Os - 10.13.3
- Node Version: 8.11.4
- Package Manager and Version: yarn - 1.9.4

**Comment by jaredpalmer** [comment]
Move to formik-persist issues please.
