### ISSUE TITLE
Using Formik with yup, without blocking submit via validationSchema

### ISSUE THREAD

**Issue by mmotamimi** [jaredpalmer/formik#920]
Hi,
i'm using formik with yup
and i need to use `validationSchema` only to get the error messages
same time, if it's not valid, it blocks the `handleSubmit` --> which is not what i need
i need to submit even with the existence of non valid fields
so i'm hoping that i can find one of those 2 solutions, or any else if found:
1- either i can make the `validationSchema` not blocking to the `handleSubmit`
2- or, i can parse the errors coming form yup in another way other than `validatoinSchema`

**Comment by yuritoledo** [comment]
Hello, 

Can you create a codesandbox with your code?

**Comment by litkod** [comment]
I am facing this issue as well. When on a Yup validationSchema, I am unable to trigger handleSubmit on the HOC yet the component version works fine.

(Example with Formik component)
https://codesandbox.io/s/zKrK5YLDZ

(Issue example with withFormik HOC)
https://codesandbox.io/s/o48nlv2knz
