### ISSUE TITLE
FormikProps are not listed in docs

### ISSUE THREAD

**Issue by najisawas** [jaredpalmer/formik#921]
GENERIC BUG

The `FormikProps` (values, errors, touched, etc.) are not listed anywhere on the documentation website. Unless there is something I'm missing, I did not see them in any of the available pages. They are displayed in the examples but it is unclear as to whether or not the examples use all of the available props or if there are more available.

**Comment by jaredpalmer** [comment]
They are called the Formik bag in the docs. I think it makes sense to potentially have dedicated api pages just for these though. Docusaurus is not great for these kind of large render props.

**Comment by mthahzan** [comment]
In case anyone else (or me in the future) gets lost and ends up here, they can be found here
https://jaredpalmer.com/formik/docs/api/formik#formik-render-methods-and-props
