### ISSUE TITLE
FieldArray render method documentation

### ISSUE THREAD

**Issue by CodingDutchman** [jaredpalmer/formik#940]
Documentation at 
https://jaredpalmer.com/formik/docs/api/fieldarray#fieldarray-render-methods
says there are 3 ways to render things with `<FieldArray />` but it only lists 2. 

I experimented with using `children` (since `<Field />` has "component", "render", and "children") and it appears to work, so `children` needs to be added  to this section of the `<FieldArray />` docs.

---

- Formik Version: 1.3.0
- React Version: N/A
- TypeScript Version: N/A
- Browser and Version: N/A
- OS: N/A
- Node Version: N/A
- Package Manager and Version: N/A

**Comment by Saifadin** [comment]
This has been included in #953, you can close this issue. :)
