### ISSUE TITLE
Field ownProps are not passed into render function

### ISSUE THREAD

**Issue by zidik** [jaredpalmer/formik#942]
According to documentation:
Field's render props are an object containing:
- field: An object containing onChange, onBlur, name, and value of the field
- form: The Formik bag.
- **Any other props passed to field**

## Current Behavior

**myCustomProp** is not passed to the render function 

```
<Field
     name="lastName"
     myCustomProp="YES!"
     render={({ field, form, ...ownProps }) =>
          "This is not passed in: " + ownProps.myCustomProp
     }
/>
```

BUT it is, when using custom component:

```
<Field name="firstName" component={CustomInputComponent} />

const CustomInputComponent = ({ field, form, ...ownProps }) =>
  "Works here: " + ownProps.myCustomProp;
```

## Steps to Reproduce

- run code in CodeSandbox
- Following result appears:

> Works here: YES!
> but not here: undefined

## Expected behavior
- Following result appears:

> Works here: YES!
> but not here: YES!

## Additional context

**CodeSandbox Link**:
[![Edit llp0zjqrp9](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/llp0zjqrp9)

---

- Formik Version: 1.3.0
- React Version: 16.3.2
- TypeScript Version: N/A
- Browser and Version: Chrome 69.0.3497.100 (64bit)
- OS: Win 10
- Node Version: 8.12.0
- Package Manager and Version: Yarn 1.10.1

**Comment by jaredpalmer** [comment]
Duplicate pf #957

**Comment by prajavk** [comment]
Sorry for commenting on closed ticket. 
@jaredpalmer I m facing same issue with Field render. Can someone give working example related to fix?
FYI @christianchown
<Field
     name="lastName"
     myCustomProp="YES!"
     render={({ field, form, ...ownProps }) =>
          "This is not passed in: " + ownProps.myCustomProp
     }
/>

**Comment by christianchown** [comment]
Hi @prajavk, don't think this is going to change. Your best (only?) hope is not to use `render` (or child-as-function), but use `component`, which receives `myCustomProp`:
```
function MyComponent({myCustomProp}) {
  return <>{/* myCustomProp === "YES!" */}</>;
}

<Field name="lastName" myCustomProp="YES!" component={MyComponent} />
```
