### ISSUE TITLE
Add Rich Harris' Treeshake rollup plugin to build

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/formik#946]
## Current Behavior

Formik doesn't ensure that it can be treeshaken.
## Desired Behavior

Formik can always be treeshaken. 
## Suggested Solution

Add the rollup plugin and fail the build if formik can't treeshake.

## Who does this impact? Who is this for?

Everyone

**Comment by TrySound** [comment]
Rich's tool is just rollup under the hood which is not able to treeshake transpiled classes at all.
