### ISSUE TITLE
Use formik between components that are not directly related (or nested)

### ISSUE THREAD

**Issue by dannyhuly** [jaredpalmer/formik#947]
Hi all, 
I’m tying to share a single Formik functionality between components that are not directly related in the tree. 
The catch is I can’t wrap the components with \<Formik\> and benefit from connect().

Here is a mock scenario here https://codesandbox.io/s/xl60n597xq

The idea is to implement a table with the option to edit a row.  
Sadly the table API allows me to only modify the cell component and not the row.  

Any ideas ?
Thanks.

FWY:
I'm re-asking the question here due to no't receiving any responses at Reactiflux#formik.

**Comment by miturostislav** [comment]
Hi.
I'm not sure if this is what you want, but hope to be useful for you:
https://codesandbox.io/s/wy5kn7rkr5

**Comment by dannyhuly** [comment]
@miturostislav Thank for the response but I'm unable to wrap the component directly which line 68 dose.
```js
const FormikApp = myFormHOC(App);
```

**Comment by dannyhuly** [comment]
I was able to find my solution in another lib.
