### ISSUE TITLE
Form submission should not require a form to be dirty.

### ISSUE THREAD

**Issue by Alex-BHN** [jaredpalmer/formik#954]
## Current Behavior
Dirty is computed like this:

`const dirty = !isEqual(this.initialValues, this.state.values);`

Because of this and the decision to not allow not dirty forms to be submit, if a form isn't modified, it can't be submit.

## Steps to Reproduce
Don't modify a form and attempt to submit it.

## Expected behavior
An unmodified form should be able to be submit.

## Suggested solution(s)
A flag to allow this possibility or removal of the restriction.

## Additional context
Imagine a form with a single checkbox. The user should be able to submit this without modification.

**CodeSandbox Link**:

---

- Formik Version: 0.11.11
- React Version: 16.2.0
- TypeScript Version:
- Browser and Version: 
- OS: 
- Node Version:
- Package Manager and Version:

**Comment by Saifadin** [comment]
`const dirty = !isEqual(this.initialValues, this.state.values);` is the definition of the dirty state.

But submitting a form without being dirty and touched is possible. There is no check for the dirty before an internal submit execution. 

In version `0.11.11` you can also pass `isInitialValid` to tell formik the form is valid.

**Comment by prichodko** [comment]
@Saifadin is correct. Form is always submitted when there are no errors.
