### ISSUE TITLE
Reset field error

### ISSUE THREAD

**Issue by mdelclaro** [jaredpalmer/formik#969]
After submitting my form, I use` Keyboard.dismiss()` and then reset the form. Something like this:

```javascript
    Keyboard.dismiss();
    resetForm({ title: '', artist: '', album: '', genre: '' }); // it works, the fields are cleaned
    setFieldTouched('genre', false, false);
```
You can see that I'm resetting the form and the "touched" property of my last field, but after the keyboard is dismissed, it blurs the field and then shows its validation error, as if I'm not using `setFieldTouched`. I tried using `setFieldError` but with no succes. This situation also happens when using `onSubmitEditing` on my `TextInput` 

When I dismiss the keyboard, and then press the submit button to submit the form, everything works well.

Any suggestions, please?

I can share more code if needed.

**Comment by Saifadin** [comment]
`resetForm` already sets all fields as not touched. Can you provide a reproduction and your Formik version.

**Comment by mdelclaro** [comment]
@Saifadin the submit handler is located at [Home.js](https://github.com/mdelclaro/CadastroPDM/blob/master/src/screens/Home.js). The form is in [here](https://github.com/mdelclaro/CadastroPDM/blob/master/src/components/AddForm.js).
Here's a few screenshots of when I press submit with the keyboard shown or in the keyboard itself (with `onSubmitEditing`), and after the keyboard is hidden the error on the last modified field is there.

![img1](https://user-images.githubusercontent.com/32961172/46623713-e9f11a00-cb04-11e8-9885-d67cc45fc218.png)

If I click on Submit or on the 'V' on the keyboard, I get this:

![img2](https://user-images.githubusercontent.com/32961172/46623712-e9588380-cb04-11e8-97b3-4d63fb474606.png)

Although, if I close the keyboard and then press submit, it works fine.

**Comment by Saifadin** [comment]
You forgot `setSubmitting(false);`

```
 submitHandler = (values, { resetForm, setFieldTouched, setSubmitting }) => {
    const id = uuidV1();
    this.props.onTrackAdd(
      id,
      values.title,
      values.artist,
      values.album,
      values.genre
    );

    Keyboard.dismiss();
    setSubmitting(false);
    resetForm({ title: '', artist: '', album: '', genre: '' });
    setFieldTouched('genre', false, false);

    // Navigation.mergeOptions('bottomTabs', {
    //   bottomTabs: {
    //     currentTabIndex: 1
    //   }
    // });
  }
```

**Comment by mdelclaro** [comment]
It seems that it didn't make any difference :/

**Comment by Saifadin** [comment]
I think I know why. It has less to do with Formik but more with how the fields are touched with the keyboard open. Because you are still focussing that field, it is being seen as touched even if you reset the form.
It's a bit hacky but doing this might help:

```
Keyboard.dismiss();
setTimeout(() => {
  setSubmitting(false);
  resetForm({ title: '', artist: '', album: '', genre: '' });
}, 0);
```
This will the code to wait after the Keyboard is dismissed. 
Hope it works, because I can't test it over here.

**Comment by mdelclaro** [comment]
It worked, dude! :-)

**Comment by Saifadin** [comment]
Good to hear :)
