### ISSUE TITLE
how will props be passed that should not be turned into values to be used within a FieldArray? example uses: options

### ISSUE THREAD

**Issue by roderickfung** [jaredpalmer/formik#971]
What are the options to pass in an array of options as a prop into the `withFormik()` HOC without converting it as a value?

It doesn't make sense to have to manually write `options` for each and every one of them, and all of the tutorials found so far only shows select with manually punched in options, which seems insufficient for the majority of the practical users out there.

**Comment by prichodko** [comment]
Please provide a snippet of what you mean.

**Comment by roderickfung** [comment]
found solution #480
