### ISSUE TITLE
setFieldValue is not setting the value properly

### ISSUE THREAD

**Issue by sumanth10** [jaredpalmer/formik#978]
I have a radio button which I have rendered by running a loop over an array. So every radio button that is rendered by the loop contains the setFieldValue element along with the corresponding value from array. But I think the re-render that happens after the FieldValue is set is making the value attribute blank.

```jsx
 const codeLangauge = ["Andriod", "Windows", "IOS", "Web"];
 {codeLangauge.map(code => (
                        <RadioButton
                          value={values.codevalue}
                          id={lang-${code}}
                          labelText={code}
                          key={lang-${code}}
                          onBlur={handleBlur}
                          onChange={() => setFieldValue('codevalue', {code})}
                          name="codevalue"
                          defaultChecked />
                        ))} 

```

<img width="1440" alt="screen shot 2018-10-09 at 5 42 09 pm" src="https://user-images.githubusercontent.com/14212012/46668670-c6080400-cbea-11e8-9a95-82f05ced565e.png">

As you can see in the watch filed of the image codevalue is being set to empty . But the code field is set to windows

**Comment by Saifadin** [comment]
`type= "radio"` inputs expect not a value field but a `checked` field. Also each value on each RadioButton should be different. Something like this:

```
 const codeLangauge = ["Andriod", "Windows", "IOS", "Web"];
 {codeLangauge.map(code => (
                        <RadioButton
                          value={code}
                          id={`lang-${code}`}
                          labelText={code}
                          key={lang-${code}}
                          onBlur={handleBlur}
                          onChange={() => setFieldValue('codevalue', code)}
                          checked={values.codeValue === code}
                          name="codevalue"
                          defaultChecked />
                        ))} 
```
Also you are setting the value `code` as an object, you should just pass it as an argument.
