### ISSUE TITLE
Touching nested fields should always deep merge

### ISSUE THREAD

**Issue by switz** [jaredpalmer/formik#984]
## Current Behavior
If you touch a field, and then try to touch a further nested field, it throws an error.
```
Cannot create property 'baz' on boolean 'true'
```

## Steps to Reproduce
```            
setFieldTouched('foo.bar');
setFieldTouched('foo.bar.baz');
```

Code Sandbox (hit trigger error, runs the code above): https://codesandbox.io/s/x94zq9098q

## Expected behavior
It should overwrite the previous `touched` state and deeply nest the new state.

```
{ foo: { bar: true } }
// should become
{ foo: { bar: { baz: true } } }
```

## Suggested solution(s)
I haven't looked internally at the code, but essentially if the setTouched key isn't the final layer (e.g. `foo` or `bar`, while `baz` is the last layer), it should automatically create an object before moving on to the next level of nesting. A deep merge.

## Additional context
Now, I understand that this loses context on non-nested fields for `touched`. In our use-case, this doesn't break our requirements, but it may for others. One solution may be to add some meta fields on an object that store `touched` rather than a simple primitive boolean.

---
- Formik Version: 1.3.1
- React Version: 16.4.2
- TypeScript Version: NaN
- Browser and Version: Chrome 69
- OS: OS X Sierra
- Node Version: 9.11.2
- Package Manager and Version: yarn 1.9.4

**Comment by joe-gre** [comment]
As a workaround, after setting the non-nested field's touched and before setting the nested field's touched you can set the non-nested field's touched to false:

```
setFieldTouched('foo.bar'); // or clicking on the "foo.bar" field
...
setFieldTouched("foo.bar", false);
setFieldTouched("foo.bar.baz"); // or clicking on the "foo.bar.baz" field
```

**Comment by gogaz** [comment]
Another workaround, a very ugly one, is to use objects instead of booleans:

```js
setFieldTouched('foo.bar');
setFieldTouched('foo.bar.baz'); // does not work

setTouched({ foo: { bar: {} }'); // considered touched because an empty object is truthy
setFieldTouched('foo.bar.baz'); // works
```
