### ISSUE TITLE
FieldArray populate 0 when adding new item?

### ISSUE THREAD

**Issue by eldyvoon** [jaredpalmer/formik#985]
Try to click the `-` and `+` button, I saw inconsistency in the input field

https://codesandbox.io/s/53l39x5rzp

**Comment by jericbas** [comment]
Push an object instead empty string

replace `arrayHelpers.push("")`
to
`arrayHelpers.push({name: ""})`


https://jaredpalmer.com/formik/docs/api/fieldarray#fieldarray-helpers

**Comment by eldyvoon** [comment]
@jericbas it doesn't make any different https://codesandbox.io/s/v0lqm6n3nl

**Comment by eldyvoon** [comment]
I grab the code from the doc (https://jaredpalmer.com/formik/docs/api/fieldarray#fieldarray-helpers) and tested it in codesandbox, it's buggy too, try to click the `+` button,
https://codesandbox.io/s/v03wykkw53
 the values are off.

**Comment by jericbas** [comment]
> @jericbas it doesn't make any different https://codesandbox.io/s/v0lqm6n3nl

Check line 58:  `onClick={() => arrayHelpers.push(index, "")}`

push()  should have 1 object argument

> `push: (obj: any) => void:` Add a value to the end of an array

**Comment by eldyvoon** [comment]
@jericbas , the link you gave has bug itself, try to click on the `+` button. Didn't you see the `0` in the input?
