### ISSUE TITLE
Mapping Values on conditional components.

### ISSUE THREAD

**Issue by CaitlinSweeney** [jaredpalmer/formik#996]
Hello! React newb and reading the docs as I write. Having trouble pin-pointing where I'm going wrong with mapping the input values (answer). The data is hard-coded, similar to the JSON I'll be getting back. The form inputs will be rendered conditionally based on the question types in the API. So each `name` is set to an `id`, etc.  

I'm trying to set the` values` from the input values (answers). I linked my Sandbox (I apologize for some sloppines 😬 ) I just started Front-End a few months ago.

https://codesandbox.io/s/7mwvj041yx

**Comment by Saifadin** [comment]
Hi,
where is it going wrong? I did not understand the question fully.
I can see that the `onChange` for the checkboxes are not working properly.

**Comment by CaitlinSweeney** [comment]
My apologies. The checkbox is working properly, I believe. I just have it set to `onChange={onChange}`.
Each question has an id and an answer value, they are being set in the `values`.
My question is how to set these properly to be accesses within `values` ? For validation, etc. 
I'm ultimately going to need to update each field value to the server onChange (not onSubmit).

**Comment by Saifadin** [comment]
Whatever you put into the `name` field will be the mapping inside values. Which makes it easy to access the selected values. If you want to update the values onChange you would need to have a custom onChange method, which makes the server call and uses `setFieldValue`
